### ISSUE TITLE
Smart saving

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#106]
When a user calls `save_expectations_config`, they usually *don't* want to save failed expectations.

Similarly, they usually don't want to save the `output_format`, `include_config`, or `catch_exceptions` parameters. With rare exceptions, the default behavior should be

To implement these defaults, I propose we add four parameters to `get_expectations_config`: `discard_failed_expectations`, `discard_output_format_kwargs`, `discard_include_configs_kwargs`, `discard_catch_exceptions_kwargs`. All should default to True.

While we're at it, we may as well add the same parameters to `save_expectations_config` It calls get_expectations_config, so we'd just pass parameters through without adding any duplicate logic.

This would directly resolve #95. I think it also (tangentially) helps resolve the root causes for issue #68.

---

As far as the API goes, this is pretty simple. And implementing the `discard_*_kwargs` parameters is very straightforward.

OTOH, implementing `discard_failed_expectations` requires a bunch of work under the hood. Specifically, the DataSet object has to remember which expectations have succeeded and failed---something it doesn't do right now.

I see two options here. Either we can (1) add a "results" object for each expectation within `_expectation_config`, or (2) we can create a completely separate object. I'm inclined to do (1), because we already have good logic for overwriting expectations within that config.

```
{
  "expectations": [
    {
      "expectation_type": "expect_column_to_exist", 
      "kwargs": {
        "column": "a"
      },
      "success": true
    },
    ...
}
```

The only downside is that the config object itself will get cluttered up with extra information. I'm not too concerned about this because we already have good methods for de-cluttering expectation configs (see above), and it's possible that there are circumstances where we'll actually want to export that metadata.

So unless I hear objections, I'm going to go ahead with this approach.

**Comment by jpcampb2** [comment]
Looking good. Let's modify the temporary ```success``` parameter to ```success_on_last_run```
