### ISSUE TITLE
Prevent expectations from running until validate()

### ISSUE THREAD

**Issue by avanderm** [fivetran/great_expectations#1092]
Hey,

Simple scenario, yet I have trouble finding it back in the docs: we want to specify our expectations in code (not JSON) on a rather large CSV data set, which we load in with `read_csv()`. Each time we add an expectation it runs the expectation, taking up a fair amount of time.

Is there a way to simple declare the expectation without actually running it, until at the end when I run the whole suite with validate() to generate a the report? None of the methods seem to indicate any such option.

Thanks in advance

**Comment by jcampbell** [comment]
Hi @avanderm : yes, you can use the `interactive_evaluation` flag for just that. Check out: https://docs.greatexpectations.io/en/latest/reference/data_asset_features.html#interactive-evaluation

**Comment by avanderm** [comment]
Thanks, did the job!
