### ISSUE TITLE
MSSQL Server error when building column expectation(s)

### ISSUE THREAD

**Issue by mark-w-325** [fivetran/great_expectations#1098]
There seems to be an issue in the way that the query is being built using SQL Server for the column "Missing values, unique values, and types" glossary. I get the below error trying to build any of those expectations:

`ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'THEN'. (4145) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
[SQL: SELECT count(*) AS element_count, sum(CASE WHEN ? THEN ? ELSE ? END) AS null_count, sum(CASE WHEN (client_short_name IS NULL AND ? = 0) THEN ? ELSE ? END) AS unexpected_count 
FROM dbo.[DIM_PNP_CLIENTS]]
[parameters: (0, 1, 0, 0, 1, 0)]`

**Comment by mark-w-325** [comment]
This appears to be the same issue as [932](https://github.com/great-expectations/great_expectations/issues/932)

**Comment by abegong** [comment]
#1269 is related, but I don't know if it will fully resolve this issue.

**Comment by alexsherstinsky** [comment]
Fixed -- in the upcoming release.  This is the Pull Request: https://github.com/great-expectations/great_expectations/pull/1717 (merged).
