### ISSUE TITLE
sample_expections_dataset_profiler crashes when unexpected_percent is Decimal

### ISSUE THREAD

**Issue by toddabrams** [fivetran/great_expectations#1109]
I ran into this after continuing after "Great Expectations will choose a couple of columns and generate expectations about them to demonstrate some examples of assertions you can make about your data."

```
great_expectations/profile/sample_expectations_dataset_profiler.py", line 78, in _create_non_nullity_expectations 
mostly_value = max(0.001, (100.0 - not_null_result.result["unexpected_percent"] - 10) / 100.0)
TypeError: unsupported operand type(s) for -: 'float' and 'decimal.Decimal'
```

I demonstrated that the TypeError could be reproduced by running the following:

```
max(0.001, (100.0 - Decimal(10.0123) - 10) / 100.0)
TypeError: unsupported operand type(s) for -: 'float' and 'decimal.Decimal'
```

I haven't traced the issue back further than either `not_null_result.result["unexpected_percent"]` shouldn't be a Decimal or this line should be able to handle Decimals.

**Comment by eugmandel** [comment]
Thank you for reporting this - we will address this right away!

**Comment by roblim** [comment]
Addressed in https://github.com/great-expectations/great_expectations/pull/1118
