### ISSUE TITLE
Documentation : Create Expectations 

### ISSUE THREAD

**Issue by kkwanyang** [fivetran/great_expectations#1119]
In 0.9.2 Tutorial for create expectations
https://docs.greatexpectations.io/en/0.9.2/tutorials/create_expectations.html#load-a-batch-of-data-to-create-expectations

Loading a batch of data
Unless I am missing something but it's my understanding that datasource must be referenced in the batch_kwargs command, otherwise it will fail.

Currently documentations only mentions the inclusion of the path.

**Comment by PSUlion16** [comment]
@kkwanyang -- Here is a snippet of how to pull from a flat file DIR data source, and a pandas dataframe. This is what I have been using locally. @jcampbell @eugmandel - can the documentation for BATCH_KWARGS be updated in a glossary for users so we have a comprehensive listing of options? This would be very helpful.

![image](https://user-images.githubusercontent.com/24613077/76249377-32889780-6211-11ea-8394-1a3e2e709de2.png)

**Comment by kkwanyang** [comment]
@PSUlion16 thanks for that. :)  What I intended to say if it wasn't clear is that if one follows the documentation as written today you wouldn't be able to successfully get the batch because there is no mention of having the datasource as part of the batch_kwarg.

And ditto to having a comprehensive list of options.
