### ISSUE TITLE
Validation Operator: Bug in Dictionary

### ISSUE THREAD

**Issue by kkwanyang** [fivetran/great_expectations#1120]
Currently the dictionary that is outputted by the run_validation_operator() command returns a dictionary that one can't navigate. Also maybe the format can be more "readable". Putting a snippet of the result

`{'success': True,
 'details': {<great_expectations.data_context.types.resource_identifiers.ExpectationSuiteIdentifier at 0x146d6ccd0>: {'validation_result': {
     "statistics": {
       "evaluated_expectations": 2,
       "successful_expectations": 2,
       "unsuccessful_expectations": 0,
       "success_percent": 100.0
     },
     "meta": {
       "great_expectations.__version__": "0.9.2",
       "expectation_suite_name": "warehouse_maria_expectations",
       "run_id": "1012",
       "batch_kwargs": {
         "datasource": "maria",
         "query": "select * from mis.dummy_data where date=\"2019-10-01\";"
...`

The line `<great_expectations.data_context.types.resource_identifiers.ExpectationSuiteIdentifier at 0x146d6ccd0>` should be in quotes so that one properly navigate it.

This may or may not be such a big deal, it seems like we aren't meant to parse this. 
But I guess I was trying to as part of failure in Airflow (for example) have something that could quickly extract which specific expectations failed. 
My understanding is that I can do something similar through custom modifying the validation operators.

**Comment by jcampbell** [comment]
@kkwanyang -- thanks for reporting this. You're right, currently the key itself is an object, which is primarily intended for use via the `stores` API.

As an admittedly painful workaround, I believe you could access that by constructing an ExpectationSuiteIdentifier:

```
id = ExpectationSuiteIdentifier("my_expectation_suite")
my_details = res["details"][id]
```

I think the right solution would be to convert that dictionary from run_validation_operator into a typed object along the lines of the expectation validation result object and related types.

**Comment by jcampbell** [comment]
I'm going to close this for now--I've improved the way this is visualized in the results, and we *will* update the validation operator result to be typed in the future.
