### ISSUE TITLE
Collections deprecation warning when importing GE inside CLI app

### ISSUE THREAD

**Issue by mzjp2** [fivetran/great_expectations#1131]
I'm trying to write a Click CLI app that import great expectations (specifically, all I'm doing at the moment is `from great_expectations import __version__ as ge_version`) but installing the CLI app using the `entrypoint` kwarg in `setup.py` gives

```
/Users/zain_patel/code/<snip>/lib/python3.7/site-packages/great_expectations/data_asset/data_asset.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import namedtuple, Hashable, Counter, defaultdict
<CLI stuff here>
```

Quickest solution here is to move the `Hashable` import to `from collections.abc`. For now, I'm going to filter warnings in my CLI app, but will also open a PR here to do this, since it's painless and probably needs to be done at some point anyway 😀

**Comment by mzjp2** [comment]
Open PR addressing this #1112 🎉

**Comment by jcampbell** [comment]
Thank you!!
