### ISSUE TITLE
Allow creating an empty expectation suite

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#1139]
Whenever I run the `great_expectations suite new` workflow, GE runs the profiler and creates a few expectations for a subset of columns. In a lot of cases I don't care about these expectations, so I have to go and delete them one by one in the `suite edit` notebook.

I would like an option to create a blank expectation suite for a batch using the cli, e.g. something like this:

```
>> great expectations suite new
>> (choose data asset)
>> "Would you like to create sample expectations Y/n?
>> (maybe open the jupyter notebook automatically instead of data docs since there's nothing to look at in data docs anyway)

**Comment by PSUlion16** [comment]
Is the request here that you want an empty expectation suite, created by CLI only? I am just clarifying as there is an easy way to do this via a py script (I am currently making a generic script for my team to do this adhoc based off new input files)

**Comment by spbail** [comment]
@PSUlion16 Correct. This seems like a neat and pretty simple built-in feature in the CLI rather than users having to create their custom scripts (which seems straightforward, but still...). 

Would your team use that if it was available, or would your script be doing something else besides that?
