### ISSUE TITLE
Docs fail to build, with `Could not import extension sphinxcontrib.lastupdate`

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#1160]
Trying to build docs locally, it fails as follows:

```
$ make html
Running Sphinx v2.3.1

Extension error:
Could not import extension sphinxcontrib.lastupdate (exception: No module named 'sphinxcontrib.lastupdate')
make: *** [html] Error 2
```

**Comment by abegong** [comment]
`pip install sphinxcontrib-lastupdate` fixes this.

Looks like we have a missing line in `requirements-dev.txt`.

**Comment by abegong** [comment]
I'm curious if this has broken any of our doc builds.

**Comment by jcampbell** [comment]
Docs are built from the `docs/` directory, which has its own requirements file (see `.readthedocs.yml`); to build docs locally, you need to ensure all required dependencies are available.
