### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by tatianamck** [fivetran/great_expectations#1185]
Hello, first, thank you for this incredible library.

I found a documentation typo, it should be _min_ instead of _sum_:
https://great-expectations.readthedocs.io/en/v0.4.5/dataset_module.html
![image](https://user-images.githubusercontent.com/53178461/76786285-bacce680-6795-11ea-84a7-77ea34f21d6d.png)

**Comment by Aylr** [comment]
Thanks! We'd love to give you the opportunity to submit a tiny PR to fix this! Does that interest you?

**Comment by jcampbell** [comment]
Fixed as part of a WIP PR
