### ISSUE TITLE
Implement the datasource API

### ISSUE THREAD

**Issue by jpcampb2** [fivetran/great_expectations#12]

**Comment by abegong** [comment]
Discussion notes from December:

# 
## Scenario 1
(We like this one)

```
#class DataContextManager(object):
#	"""
#  is a factory
#	"""
#	def connect(“sqlite”, “mypw”, “my_un”)
#	def connect(“pandas_directory”, local_dir_path)
#

def get_data_context(context_type, *args, **kwargs):
		if self.data_context_type == "sqlalchemy":
			SqlAlchemyDataContext(args, kwargs)
		elif self.data_context_type == "pandas_directory":
			PandasDataContext(args, kwargs)
		elif ...
	

class DataContext(object)
	def __init__(*args, **kwargs):
		self.connect(*args, **kwargs)

	def connect(“mypw”, “my_un”):
		return NotImplementedError
	def list_datasets():
		return NotImplementedError
	def get_data_set()
		return NotImplementedError

class SqlAlchemyDataContext(DataContext)
	def connect(mypw, my_un):
		self.engine = sqlalchemy.create_engine(my_un, my_pw)

	def list_datasets():
		return engine.get_all_the_datesets()

	def get_data_set()
		...

class PandasDirectoryDataContext(DataContext)
	def __init__():
		#pandas-specific stuff
		super.__init__()

	def connect(local_filepath):
		self.directory = local_filepath
		import glob

	def list_datasets():
		return glob.glob(self.directory)

	def get_data_set()
		...

class SqlAlchemyDataSet(DataSet)
class PandasDataSet(DataSet)

```

## Scenario 2

```
class DataContext(object)
	.__init__(“pandas_directory”, local_dir_path)
	.connect(“pandas_directory”, local_dir_path):
		self.data_context_type = data_context_type
		if self.data_context_type == "sqlalchemy":
			...
		elif self.data_context_type == "pandas_directory":
			...
		elif ...

	.list_datasets()
	.get_data_set()

class SqlAlchemyDataSet(DataContext)
class PandasDataSet(DataContext)

```


`column_map_summary_obj`

**Comment by abegong** [comment]
This is implemented in a bare bones way in #209.

**Comment by jpcampb2** [comment]
I commented on the PR that I don't think it deals with the SQL store properly, and have pushed a branch with an alternate approach: feature/data_context_api. We can review the different approaches hopefully in person to ensure we're thinking through the right use cases.

**Comment by abegong** [comment]
@jpcampb2 I don't see the comment on the PR...

**Comment by jpcampb2** [comment]
@abegong ... you're right it was in slack. Here:

I'm struggling with the data context PR because it looks like it's mostly adding commented-out versions of what already exists, or exactly duplicated code. In particular, there don't appear to be any expectations implemented that actually touch the data in the SQL store. I think it makes more sense to refocus it to strip out spark, keep lots of notimplemented-flagged-sql functions, and implement at least one expectation actually in the sql store.

**Comment by abegong** [comment]
Apologies for the confusion. You're right that #209 does very little to implement new subclasses of DataSet. It's mainly scaffolding and prep work for #213.

The real progress in #213 was setting up Docker (Spark is part of that) and ensuring that we can connect, test, and develop efficiently using containers.

**Comment by jpcampb2** [comment]
Understood. Recommend then that we keep these branches out of PRs so it's clear we're not imminently planning to merge them, but demonstrating patterns. To that effect, I also pushed a branch, feature/data_context_api with a pattern for implementing the sqldataset.

**Comment by jpcampb2** [comment]
I've put an initial commit with some documentation and examples (not under test) of the data context api for this upcoming release.

cc: @abegong

**Comment by abegong** [comment]
This is great. I'd recommend liberally throwing around docstring warnings.

"Warning: this feature is new in v0.4 and may change based on community feedback."

**Comment by jpcampb2** [comment]
Sounds good. I added tests, caveats, and docs, and updated the PR.
