### ISSUE TITLE
Suggestion: enable creating new suites or datasources from Commandline when an existing source is offline

### ISSUE THREAD

**Issue by pentatone** [fivetran/great_expectations#1200]
At the moment if a connection fails, the commandline tool crashes out.
I think adding or redefining a Datasource or Suite from commandline tool should be facilitated, as it can rapidly fix configurations for sandbox environments where sources and connections might change quickly. Although the workaround isn't complex, I would suggest you to consider implementing this behaviour.

**Comment by Aylr** [comment]
I agree that particularly for datasources this is a problem. However creating suites without data isn't a very productive experience.

**Comment by jcampbell** [comment]
This is very related to #1201; please consider them linked.
