### ISSUE TITLE
Alternative APIs for validation, especially using method chaining

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#1219]
I had a great conversation with @ericmjl about this today, including some prototyping in notebooks.

The gist: it'd be great if GE could support alternative APIs for validation:
1. No indirection
2. No indirection, plus chaining
3. Indirection

(I'll add examples once I get a copy of @ericmjl's notebooks.)

**Comment by abegong** [comment]
Also, for method chaining specifically, we verified that Great Expectations dataframes are chainable via `pandas_flavor`.

Toy example:

```
import great_expectations as ge
import pandas as pd
import pandas_flavor as pf

@pf.register_dataframe_method
def do_something(df, something):
    df.expect_column_values_to_be_between("x", 0, 5)
    return df

df = ge.from_pandas(pd.DataFrame({"x": [1,2,3,4,5], "y": list("abcde")}))

(
    df
        .do_something("hi")
        .drop_duplicates("x")
)
```
Returns this, demonstrating that method chaining works:
```
	x	y
0	1	a
1	2	b
2	3	c
3	4	d
4	5	e
```

After that, 
```
df.get_expectation_suite()
```

...returns this, demonstrating that DataFrame subclasses are persisted after chaining:
```
{
  "data_asset_type": "Dataset",
  "expectations": [
    {
      "meta": {},
      "kwargs": {
        "column": "x",
        "min_value": 0,
        "max_value": 5
      },
      "expectation_type": "expect_column_values_to_be_between"
    }
  ],
  "meta": {
    "great_expectations.__version__": "0.9.7+18.gd9593290"
  },
  "expectation_suite_name": "default"
}
```

**Comment by ericmjl** [comment]
Great call today, @abegong! 

I'm pasting here some of the API sketches we went through:

```python
# my data functions
def load_data():
    data = (
        pd.read_csv(...)
        .clean_names()
        .do_other_stuff()
        .some_pandas_function()
        .more_stuff()
    )
    return data

def load_more_data():
    # do stuff
    return data

def merge_data():
    return load_data().merge(load_more_data())
# test_data.py
# the unit tests for data

def test_load_data():
    # One "explicit" API:
    data = load_data()
    expected_columns = [...]
    data.expect_table_columns_to_match_ordered_list(expected_columns)
    data.expect_another_thing(...)

    # Another "explicit" API:
    (
        data
        .expect_table_columns_to_match_ordered_list(expected_columns)
        .expect_another_thing(...)
    )

    # And if there's more complex expectations:
    my_es = load_expectation_suite()
    data.validate(my_es)
```

And for the notebook I was using today, please find it [here](https://gist.github.com/ericmjl/f7874622d81b309b323d5ed8b873c0f6)!

**Comment by abegong** [comment]
A few other notes from the call:

Explicit API #1 (which I called "no indirection") would treat each expectation like an assertion and raise an error on failure. Note: @schrockn asked for something similar for dagster integration.

This might be simple to accomplish by adding another `result format` (`RAISE ERROR`) to the expectation decorator.

If we wanted to get fancy, it could raise an error with a nicely rendered message. `ExpectationError: Column values in "my_col" should be between 0 and 10, but 7 exceptions (3.7%) were found. Examples: 11, 11, 11, -9, 20, 14, 11`

This seems like a great candidate for a future refactor to class-first Expectations.

The second Explicit format (which I called "no indirection, plus chaining") would act like a single assertion. Since we haven't used method chaining elsewhere in the library, I'd be inclined to treat this as a small extension to `pyjanitor`. If it's popular, we could eventually incorporate it into GE using `pandas_flavor`

The third type of validation is the mode already supported in Great Expectations.

**Comment by jcampbell** [comment]
I think there are some good ideas in here. There's also potentially some commingling of APIs that will remain separate:

1. There is actually some fairly specific handling that we've added to PandasDataset to enable the chaining (and subsetting) behavior you're using in these examples, but that is not relevant in either the SqlAlchemyDataset or the SparkDFDataset worlds. In fact, we're planning to further distance the concept of the data-to-validate ("batch") from the expectation suite, which means that any chaining operations should be assigned to the *batch* as *distinct from* the expectation suite.

2. Raising an error as a particular result format makes some sense to me as an option, but I'd make two cautions: (a) any resulting API should probably take care to avoid implying that running individual expectations is the preferred way of using GE; and (b) it would need to provide some way to suggest or guarantee evaluation order or would produce inconsistent results. Those things aside, it would be a welcome PR. (Of course, I'd also flag that it's currently easily replicated by raising an exception based on a success value of false).
