### ISSUE TITLE
HDFS Support with Spark

### ISSUE THREAD

**Issue by lfpll** [fivetran/great_expectations#1222]
Hi Guys,

I'm trying to start great expectations on some hdfs files but it's not working

Simply when it asks:

`Enter the path (relative or absolute) of a data file`

I input with my hdfs absolut path of my csv which is a folder.

`hdfs://***`

And respond with the file not working, but I'm able to open with spark.read.csv is this a bug?

**Comment by jcampbell** [comment]
@Ifpll, yes, I believe that is a bug, related to the way that the CLI is trying to read the path. If you could download a file locally just to get through CLI init, you could then use the hdfs paths once your datasource is configured.

I'll also flag for a colleague who has been doing work on the CLI the need to develop a fix, and hopefully he can get back to us soon with an idea for when that could happen.

**Comment by lfpll** [comment]
@jcampbell  Heads up. did some investigation on decode, no debugging but I believe the problem is here

https://github.com/great-expectations/great_expectations/blob/bb30649f1aa845e96b1464e0b497b92cc55abd30/great_expectations/cli/datasource.py#L630

I believe click is throwing an error when trying to check if the file exists, if I have time I will try to contribute on that.

**Comment by lfpll** [comment]
@jcampbell Is he working on this? Maybe on monday I can start to contribute on this.

**Comment by Aylr** [comment]
@lfpll That would be awesome! Please let us know how we can support you!

**Comment by lfpll** [comment]
@Aylr thanks, I confirmed right now where is the problem.

Lines 996-1006 on **great_expectations/cli/datasource.py**
```
        path = click.prompt(
            msg_prompt_file_path,
            type=click.Path(
                exists=True,
                file_okay=True,
                dir_okay=dir_okay,
                readable=True
            ),
            show_default=True,
            default=path
        )
```
The exists clause break the code because it's unable to check hdfs systems, I will take a look at slack and see opinions for the solutions I have in mind.

**Comment by Aylr** [comment]
@lfpll I think the right answer to this is to move the file exist check logic from the click built-in to some custom code. That way we can still have the same functionality, but not be limited by click. Want to take a crack at this?

**Comment by lfpll** [comment]
@Aylr  I started working on this over the weekend, I'm going to probably finish over this weekend,  I just added another prompt that if the user is trying to acess via spark ask then if it's hdfs or a common folder I still need to test but I believe it will work.

Any problems on this approach? 

The possible problem and what I think it's bad, is that the only way to check if the file exists in hdfs using python is using subprocess, which is very ugly.

**Comment by Aylr** [comment]
I'm glad you are making progress on this! Additional prompts make sense to me. I do agree that subprocess can be a little gross, but that may be the best way. Spotify has an ancient library called snakebite that was a native HDFS client. I wonder if there is something better?

**Comment by lfpll** [comment]
Just Some updates on this, I found out that when you connect with great expectations using a virtual environment it needs to grab the python configuration file, which don't happen automatically (at least no on my HDFS cluster).

So I will have to add some piece of logic for that also.
