### ISSUE TITLE
Documentation : BatchKwargs Examples and explaination

### ISSUE THREAD

**Issue by troxil** [fivetran/great_expectations#1224]
Hi All!

I found it confusing to find how to use the different flavours of `BatchKwargs` against different datasources. 

There's plenty of documentation on the purpose of batch generators as they relate to Datasources and highlight their integral need. But I found it confusing to link how to string my own set together.

What I really wanted was to create a new data source using `SparkDFDatasource` with just a single S3 Path pointing to Parquet files. 

This was not obvious throughout my reading. But seemed doable. 

A page or diagram or something similar on how these `BatchKwargs` plug in to datasources and how they can be used would great. 

DataSource > Generator > Assets > Parameters for data source?

Thank you

**Comment by jcampbell** [comment]
Great call, @troxil : we've got a note to build improved documentation.

One thing to note: in general, you can just pass in a dictionary, and GE will convert it to the appropriate BatchKwargs object as needed.
