### ISSUE TITLE
Instantiating a DataContext will fail when done outside of the GE provided notebook folders

### ISSUE THREAD

**Issue by PSUlion16** [fivetran/great_expectations#1231]
As a user, we have a use case where a python file may invoke GE from outside the great_expectations/ folder structure. In this scenario, the following command will fail:

# Grab Context for GE Run
context = ge.data_context.DataContext()

![image](https://user-images.githubusercontent.com/24613077/77593078-8bb72300-6ec1-11ea-9413-f3f7fd80a882.png)

It would be ideal if GE could search for the YAML file from the relative path as part of this script if result is NONE.

**Comment by jcampbell** [comment]
If you're running outside of the "normal" paths, I'd recommend using the `GE_HOME` environment variable to point to the location of your data context. You can also pass the path in as the first parameter to the call to instantiate the constructor.

Would either of those options work for you?

**Comment by PSUlion16** [comment]
James,

Passing the path to the context call works fine -- For some of the basic calls such as these, can we make a note in the documentation, or at least in the exception make a note that running outside of the GE normal paths will require the optional PATH var on call?

In terms of GE_HOME, what about setting this config var by default on great_expectations.init, and referencing automatically in the context grab?

**Comment by jcampbell** [comment]
I love the idea of adding better errors here. My colleague @alexsherstinsky is actually going through several of those issues right now, so I'll ask him to add that to the list.

I don't think we should update an environment variable without explicit request from the user, but with the improved error message I think the net result will be great.

**Comment by alexsherstinsky** [comment]
I will defer to James on the question about the environment.  Regarding my current project, I hope that it will help that the error messages will be more specific in terms of which problem actually occurred at lower levels, instead of simply reporting a high level error, which is difficult to trace down to the problem.  Thank you.

**Comment by PSUlion16** [comment]
@jcampbell - My suggestion is to not force change the GE_HOME var, but rather reference for a Root search in that procedure. That way, regardless of where people are running the notebook, script, etc, it will always know the root GE directory -- right now that procedure is only referencing the os current dir. Make sense?

**Comment by jcampbell** [comment]
I think so, but in that case, it seems like it would likely lead to confusion if the "HOME" contains multiple projects (which seems like would be an implied acceptable configuration with a search path).

In this case, I think the improved error message is the right solution to avoid that ambiguity.

**Comment by PSUlion16** [comment]
@jcampbell, I think I agree with you. I had not considered if we had multiple projects in the same folder. In this scenario, are we opening it up to a scenario where a user could corrupt a project without properly setting GE_HOME themselves at runtime?

**Comment by jcampbell** [comment]
I think the preferred approach should be to just pass in the path for the desired project directly.

**Comment by PSUlion16** [comment]
Cool - Want me to close this then, or leave open for a better exception? I may have some free bandwidth at the end of the week if you want me to take something on ...

**Comment by jcampbell** [comment]
I think adding an improved error message is worthwhile, and if you could submit a PR it's welcome! That said, I'd still say close the issue if you're comfortable with that.

**Comment by PSUlion16** [comment]
Will do @jcampbell
