### ISSUE TITLE
Building of HTML Documents raises exceptions (0.9.7)

### ISSUE THREAD

**Issue by PSUlion16** [fivetran/great_expectations#1234]
All,

This is the first time we've tried to build documents on 0.9.7 but we receive an exception when running the context.build_docs(). I have also tried to do this from CLI with 'great_expectations build docs' with same exception.

Initially I thought I had messed up my folder structure locally, so I completely rebuilt doing the following:

1. great_expectations init (CLI)
2. Created a simple expectation suite:
         expectation_suite_name = 'tplt_inbound.transactions.failure'
         context.create_expectation_suite(expectation_suite_name, overwrite_existing=False)

3. Loaded a batch of data from a DF and Added a simple expectation:
         my_batch.expect_column_values_to_be_in_set('ISO_ALPH2_CNTRY_CD', ['CN', 'ID'])
4. Validated the batch:
         my_batch.validate()
5. Saved the Suite:
         my_batch.save_expectation_suite()
6. Using my initial context - tried to build my docs:
         context.build_data_docs()

Presented with the following error:

![image](https://user-images.githubusercontent.com/24613077/77659186-b945b000-6f45-11ea-8abd-68162fdfe37a.png)

From CLI, error is similar - with more traceback:

![image](https://user-images.githubusercontent.com/24613077/77659267-d8444200-6f45-11ea-8e9f-cb89298d34e7.png)

**Comment by Aylr** [comment]
Thank you for the excellent error report @PSUlion16! It looks like there are some jupyter notebook checkpoints (which are also JSON files) that happen to be in the expectations folders. GE currently expects those folders to **only store expectations** as it has no current way to deal with non GE json files.

As a workaround, simply delete the `ipynb_checkpoints` folder in your `transactions` directory.

**Comment by PSUlion16** [comment]
@Aylr -- I double checked this - I definitely do not have that folder locally. The error is noting the folder is missing -- considering that I rebuilt my structure from scratch, what could be cause?

File "/opt/oss/conda3/lib/python3.7/site-packages/great_expectations/cli/cli.py", line 62, in main
    cli()
  File "/opt/oss/conda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/oss/conda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/oss/conda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/oss/conda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/oss/conda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/oss/conda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/oss/conda3/lib/python3.7/site-packages/great_expectations/cli/docs.py", line 39, in docs_build
    build_docs(context, site_name=site_name, view=view)
  File "/opt/oss/conda3/lib/python3.7/site-packages/great_expectations/cli/docs.py", line 62, in build_docs
    index_page_locator_infos = context.build_data_docs(site_names=site_names)
  File "/opt/oss/conda3/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 937, in build_data_docs
    index_page_resource_identifier_tuple = site_builder.build(resource_identifiers)
  File "/opt/oss/conda3/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 197, in build
    site_section_builder.build(resource_identifiers=resource_identifiers)
  File "/opt/oss/conda3/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 282, in build
    resource = self.source_store.get(resource_key)
  File "/opt/oss/conda3/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 68, in get
    return self.deserialize(key, self._store_backend.get(self.key_to_tuple(key)))
  File "/opt/oss/conda3/lib/python3.7/site-packages/great_expectations/data_context/store/store_backend.py", line 28, in get
    value = self._get(key)
  File "/opt/oss/conda3/lib/python3.7/site-packages/great_expectations/data_context/store/tuple_store_backend.py", line 216, in _get
    with open(filepath, 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/datascientist/data_quality_framework/great_expectations/expectations/tplt_inbound/transactions/ipynb_checkpoints/failure-checkpoint.json'

**Comment by PSUlion16** [comment]
One thing, this issue did not present self in 0.9.3 for me, has been doing consistently on .9.7

**Comment by roblim** [comment]
Hm. That error seems odd. Not sure why it's looking for file there. If you're doing everything out of box, without any changes to config, an expectation suite named `tplt_inbound.transactions.failure` should be saved in /expectations/tplt_inbound/transactions/failure.json. When you say you rebuilt everything, did you completely delete the `great_expectations` directory in your project, then run `great_expectations init`? If not, can you try that?

**Comment by PSUlion16** [comment]
@roblim - yes, I went ahead and deleted the great_expectations dir, then re-initialized using great_expectations init in this situation

**Comment by PSUlion16** [comment]
All, I did the following:

1. Rebuilt my GE instance, one more time using version 0.9.7
      Result - Same error above when building DATA DOCS
2. Rebuilt my GE instance, using 0.9.3 where it last worked for me
      Result - Data Documents are viewable and run correctly.

In both instances, I am using: context.build_data_docs()

I will continue to work through our use case on 0.9.3 until I hear of a potential workaround / fix for 0.9.7 - I am more than willing to share out to core dev team (@Aylr @roblim @jcampbell ) if that is easier

@subuda - FYI

**Comment by Aylr** [comment]
@PSUlion16 I'm going to work on reproducing this today. Thanks a ton for your patience and details!

**Comment by Aylr** [comment]
I was able to reproduce this by creating a jupyter notebook checkpoint inside the expectations directory. Great expectations assumes that every json file in the `expectations` dir is in fact an expectation suite, and hidden directories, such as the `.ipynb_checkpoints` dir cause the StoreBackend to crash. I will be submitting a tiny patch to ignore this directory, however ideally there should be no other files other than expectation json and directories in this folder.

**Comment by PSUlion16** [comment]
Thanks @Aylr -- I rebuilt my directory structure completely on 0.9.7 and still experienced this (confirming what you say above), but on 0.9.3 that behavior did not present. Do you know what causes this hidden dir to be generated?

Chris

**Comment by Aylr** [comment]
Are you using jupyter notebooks or juypter lab for anything?

**Comment by PSUlion16** [comment]
Yes, using both during our vetting of our new process

**Comment by PSUlion16** [comment]
I just realized why you are asking. Yeah -- I can see this occurring consistently from this environment, your fix should take care of this for Jupyter users in a datascience workspace!
