### ISSUE TITLE
Data Docs jumps with to many columns

### ISSUE THREAD

**Issue by krlng** [fivetran/great_expectations#1243]
The Data Docs UI jumps to the last expectation and can't be scrolled up after, if you have more columns than those fitting to the left sidebar on your screen. As soon as you scroll bellow the last visible column header, the gui jumps to the bottom. (Version 0.9.7, Browser Chrome)

Best work-around I found till now is zooming out as far as you can (which is definitely limited when dealing with really man columns)

**Comment by roblim** [comment]
Thanks for reporting this bug! We're working on a fix now.

**Comment by roblim** [comment]
Addressed in https://github.com/great-expectations/great_expectations/pull/1242
