### ISSUE TITLE
Regex Error with BigQuery

### ISSUE THREAD

**Issue by weber-nate** [fivetran/great_expectations#1244]
We are having an issue running the following expectation on a string column:
```python
batch.expect_column_values_to_match_regex("UNIQUE_ID", "^[0-9]*$", catch_exceptions=True)
```

Error is as follow:

DatabaseError: (google.cloud.bigquery.dbapi.exceptions.DatabaseError) 400 Syntax error: Parenthesized expression cannot be parsed as an expression, struct constructor, or subquery at [1:154] [SQL: 'SELECT count(*) AS `element_count`, sum(CASE WHEN (`UNIQUE_ID` IS NULL) THEN %(param_1)s ELSE %(param_2)s END) AS `null_count`, sum(CASE WHEN (NOT (`UNIQUE_ID` REGEXP_CONTAINS %(param_3)s) AND `UNIQUE_ID` IS NOT NULL) THEN %(param_4)s ELSE %(param_5)s END) AS `unexpected_count` \\nFROM `dataset.raw_table`'] [parameters: {'param_1': 1, 'param_2': 0, 'param_3': '^[0-9]*$', 'param_4': 1, 'param_5': 0}] (Background on this error at: http://sqlalche.me/e/4xp6)"

When checking the query in BQ, we see that the NOT in sum(CASE WHEN (**NOT** ( is throwing a syntax error.

Luckily, the regex is quite simple...and as a temporary work around we are casting column as int and doing a null check. More complicated regex would certainly fail. Note: We prefer to run ge on raw tables whenever possible, as maintaining custom SQL is one more thing that we have to update in our pipeline.

Thanks in advance!

**Comment by jcampbell** [comment]
Wow -- this one looks tricky.

It appears to me that what's going on is that bigquery updated its query language, and the generated query is straddling the two.

In particular, under the "legacy sql" dialect, this particular parenthesized expression is valid...but the REGEXP_CONTAINS function is not (it was called REGEXP_MATCH and has a slightly different syntax).

On the other hand, the new "standard sql" dialect doesn't support this parenthesized expression. I *suspect* the pybigquery team will be amenable to looking at this more closely (and we could probably get a PR for them). What version of pybigquery are you using?

**Comment by jcampbell** [comment]
I've continued to look at this, and actually think the above is at least incomplete: the underlying issue seems to be that GE currently treats all regular expression matching as a binary expression, but in the bigquery dialect, it's actually a (binary) function. I think an easier fix will be to update GE to generate a function in this case.

**Comment by weber-nate** [comment]
Thanks for your work on this. It doesn't seem all that applicable due to your second comment, but we are running pybigquery==0.4.14.

**Comment by jcampbell** [comment]
@webernathan : you're right, I don't think that in fact you'll need to touch on pybigquery. The current PR should address the issue -- we'll merge and probably release a fix in the next day (there's another PR that needs to be released soon!)
