### ISSUE TITLE
DataContext.create cannot create directory inside a azure function

### ISSUE THREAD

**Issue by sponde-squirrel** [fivetran/great_expectations#1262]
I am trying to run GE profiler inside serverless function,  
on creating context
`context = DataContext.create(context.function_directory)`

it gives following error :
```
Exception: OSError: [Errno 38] Function not implemented: '/home/site/wwwroot/Function1/great_expectations'
    context = DataContext.create(context.function_directory)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/great_expectations/data_context/data_context.py", line 1377, in create
    safe_mmkdir(ge_dir, exist_ok=True)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/great_expectations/data_context/util.py", line 33, in safe_mmkdir
    os.makedirs(directory)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
```

Inside the serverless function, I can create the directory using os.makedirs directly, but not using datacontext.create(dir). The same code runs on the local machine and able to generate profiling results.

**Comment by Aylr** [comment]
Azure functions do not support writing files, hence this will not work. This SO post explains it well. https://stackoverflow.com/questions/57955013/error-in-azure-functions-for-python-whenever-trying-to-create-new-directory

You may need to find another way to run this.
