### ISSUE TITLE
Expectations stacked on top of column which may be null, will throw exception (expect_column_value_lengths_to_equal)

### ISSUE THREAD

**Issue by PSUlion16** [fivetran/great_expectations#1268]
As a user - we may want to stack multiple expectations on a column checking both for NULL as well as length attributes when NOT NULL.

In a use where have a column in a PandasDataframe which has null values, the expectation expect_column_value_lengths_to_equal will fail due to the implementation of the len() attribute check.

Line 1078 of great_expectations\dataset\PandasDataset.py uses the str.len() operator on the column value, which will fail on NULL values as this operator is only applicable to actual string values.

I've looked at the other expectations and can see similar implementations - I would recommend using a coalesce on the series element or changing the implementation to do purely a .len() which would return NULL - with a slight modification on the return logic.

As an editorial comment - I suppose we would want to only output offending % of lines for NON NULL variables in this stacking of expectations situation. This would be a larger feature.

See screenshot for offending line as well as output on the docs:
![image](https://user-images.githubusercontent.com/24613077/78671781-5b01c100-78a5-11ea-8ca1-b570dc670551.png)
![image](https://user-images.githubusercontent.com/24613077/78671917-8a183280-78a5-11ea-97b1-779fe83b0430.png)

**Comment by PSUlion16** [comment]
I am willing to take this PR for PandasSet, but I need input from the CoreDev team on if we should expand to other dataSources

**Comment by Aylr** [comment]
@PSUlion16 I'd say go ahead with the pandas PR without gating on other backends and we can investigate it!
