### ISSUE TITLE
Clean up and document conventions for example notebooks

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#1278]
Currently, not all the notebooks in `examples/notebooks` run.

I suggest we adopt the following conventions, and clean up notebooks to match:

All example notebooks should live in `examples/notebooks`.
All example data should live in `examples/data`.

Each notebook should be self-contained, using only data in `examples/data`. For example, we should not use data in `tests/`, even if that means some duplication of data within the repo. Datasets should be small anyway: 5MB absolute max, with most datasets under 1MB.

Notebooks should be run from `examples/notebooks`, not `examples/` or the great_expectations root.

Therefore, data should be imported from relative directory as follows: `df_test = ge.read_csv('../data/adult.data.b_2_test.csv')`

**Comment by Aylr** [comment]
:100: % agree with this
