### ISSUE TITLE
Standardize Validation "Observed Value" outputs in HTML Documents

### ISSUE THREAD

**Issue by PSUlion16** [fivetran/great_expectations#1279]
As a user,

It would be nice to have the "Observed Value" Field be standardized to show percentages of "successful" validations, vs a mix of 0% / 100%. This causes confusion as there are different levels of validation outputs with different verbage (making someone not used to the expectations confused) I've given an example below in a screenshot for what I mean:

![image](https://user-images.githubusercontent.com/24613077/78909763-9b01a900-7a49-11ea-8912-275f7304bef8.png)

In this example we have a mix of No output, 100% not null and 0% unexpected.

It would be helpful to standardize out to percentage of conformance to expectation, such as "100% expected". Perhaps change "Observed Value" to "Validation Result" and output values as a percentage with # of records out of total.

For example, a field marked as NOT NULL with 50000 records could display 80% Expected (40000 out of 50000). I realize we are putting the error counts below the expectations, but putting into the observed value field with consistent messaging would be more user (in our case Biz user) friendly. I've already received feedback from a few people in my Organization on the helpfulness of consistent validation messaging, this would be a great win!

Chris

**Comment by Aylr** [comment]
This is an excellent write up. And I agree completely. This would also be a relatively easy contribution if you are interested. The relevant code is in `def _get_observed_value(cls, evr)` in the file `validation_results_table_content_block.py`
