### ISSUE TITLE
Add `expect_join_columns`

### ISSUE THREAD

**Issue by peleyal** [fivetran/great_expectations#1281]
Hi, in the last few days I was looking into the library and its expectations and I found the library to be very promising! 

However, I didn't find any example of joinable columns. I'm looking for some expectation that column A in table boo is a foreign key (or joinable...) of column B in table foo.
This is useful for a database like BigQuery where Foreign Key is not part of the schema.

Is there an open request for that or is it on anyone radar?

Thanks!
Eyal

**Comment by Aylr** [comment]
@peleyal Thanks for the idea! We would love to implement things like this in the future, and in the interim we have some pretty good design patterns that you can use as workarounds.

The main design pattern we recommend for anything like this is called a check asset. Here's a doc on what that means: https://docs.greatexpectations.io/en/latest/reference/check_assets.html

Obviously we'd love a PR if this is something you'd like to work on!

**Comment by peleyal** [comment]
Sorry for not responding earlier. I was distracted by other tasks I have on my plate.

We are planning to integrate our validations to great_expectations in the next few weeks to come, so it will be more relevant then.

Thank you!
