### ISSUE TITLE
Disabling table of contents in data docs webpage

### ISSUE THREAD

**Issue by tejsvirai** [fivetran/great_expectations#1282]
Is there any way to disable the Table of Contents scroll bar on the left side of the data docs webpage? Even with the new fix to scrolling, the scrolling experience is still jumpy and I suspect it's because it tries to pair the scrolling in the table of contents with that of the main page. A quick way to disable the ToC would be helpful especially if it currently exists.

**Comment by Aylr** [comment]
To me this sounds like the table is still buggy. I'd like to replicate this. Can you give me either a screenshot or a rough idea of how many columns are in the page you are seeing this behavior in?

**Comment by tejsvirai** [comment]
Approximately 200 columns

**Comment by Aylr** [comment]
Nice. What browser and operating system? How many expectations on this wide table?

**Comment by tejsvirai** [comment]
Safari and MacOS Mojave 10.14.6. One kinds of expectations across the 200 odd columns, namely 'expect_column_values_to_be_in_set'

**Comment by tejsvirai** [comment]
any thoughts on this issue?

**Comment by Aylr** [comment]
Thanks for the ping! For now, I'm going to disable the javascript itself. This will leave the TOC functionality, but remove any of the javascript wonkiness. I'll get a PR in by tomorrow!
