### ISSUE TITLE
Why can't you have to expect_column_pair_values_to_be_equal() calls in an expection suite?

### ISSUE THREAD

**Issue by akozlu** [fivetran/great_expectations#1287]
I'm just curious why, 

batch.expect_column_pair_values_to_be_equal( column_A= **A**, column_B= **B**')
batch.expect_column_pair_values_to_be_equal(column_A=**C**, column_B=**D**)

only creates a single expectation, overriding all previous calls. Even though both expectations are on different pairs of columns. Same goes for batch.expect_column_pair_values_A_to_be_greater_than_B.

**Comment by abegong** [comment]
This is a bug. I think I know why it's doing this---will investigate this weekend.

**Comment by abegong** [comment]
Also, out of curiosity: why did you close this issue, @akozlu ?

**Comment by akozlu** [comment]
At that point, I was still unsure whether I was messing up stuff on my end. 

It works fine if you add additional additional `expect_column_pair_values_A_to_be_greater_than_B` manually to your json file by the way.

**Comment by akozlu** [comment]
Thank you for the PR @abegong. 
Is it possible to give a rough timeline on the PR review, or whether this issue is even a priority for the GE team? 
The reason I'm asking is, to integrate the rest of my team to GE, I am expected to report whether they should use ```suite edit``` or directly edit suite JSON files to work around this issue. 
Thanks.

**Comment by abegong** [comment]
Best estimate is that we're just a few days away. Normally it won't take this long, but I ran into the testing glitches that led to #1333. Once @Aylr (or someone else) has a chance to review and finalize, I can do the remaining work to close out this PR.
