### ISSUE TITLE
Add Functionality to Delete old Validations AND/OR expectation suites

### ISSUE THREAD

**Issue by PSUlion16** [fivetran/great_expectations#1305]
As a User,

I would like to have the ability to delete validations that are older than a certain number of days, or on an adhoc basis specifying the days. These validations would no longer clutter up the data_docs once cleansed. Additionally, removing expectation suites would be great as well if a source of expectations is deprecated.

I initially was taking the approach of cleaning up my own validations and expectation suites, but I corrupted my folders enough (and I would think other users would need this) to have this functionality built into the GE tool.

Proposed addition of new CLI or CONTEXT functions:
      great_expectations suite delete <suite_name> # Deletes expectation suite along with Validations
      great_expectations suite clean_validations <suite_name> <days_back> #Clean up validations older than the days back for given expectation suite

I realize this is similar to issue #658. I propose closing that item, and refreshing to this. Would make maintenance off suites / validations easier.

Chris

**Comment by Aylr** [comment]
@PSUlion16 These are all excellent points. @ayirplm has some good work underway right now that should ship in a few days that adds `suite delete` functionality!

I also like your idea for validations older than a certain time. Are you interested in working on that feature?

**Comment by PSUlion16** [comment]
Taylor,

I can, but my free time is tight haha! When would you like to get into code
base? If you have some free time, maybe we can have a quick call to discuss
ongoing features and where i can help out.

Chris

**Comment by Aylr** [comment]
Awesome! Give this a quick glance to see if it's something you are up for. https://docs.greatexpectations.io/en/latest/contributing.html

DM me on slack and we can arrange a call!

**Comment by PSUlion16** [comment]
@Aylr -- Will do
