### ISSUE TITLE
data docs link has multiple slashes

### ISSUE THREAD

**Issue by tejsvirai** [fivetran/great_expectations#1314]
In version 0.10.0, there are two slashes before 'index.html' which make link invalid, at least on Safari. Replacing the double slash with a single slash fixes the issue so this appears to be a simple typo in the code

**Comment by Aylr** [comment]
@tejsvirai can you show me an example URL so I can fix this stat?

**Comment by Aylr** [comment]
It would be helpful to know what store backend you are using too.

**Comment by tejsvirai** [comment]
example URL: https://s3-us-west-2.amazonaws.com/kh-greatexpectations.net/DSVC/prod//index.html

backend: S3

**Comment by Aylr** [comment]
Thanks! I'll ship a fix on Monday!

**Comment by dmateusp** [comment]
I think this issue was re-introduced on the develop branch

I'm doing unrelated development (adding a Docker image), and when I build my Docker image on top of `develop` , the produced site docs get uploaded to S3 on a path that contains an extra `/` as described on the Issue

This does not happen when I cherry-pick my Docker commits on top of the `tags/0.11.4 `

**Comment by Aylr** [comment]
Thanks for the report! Reopening! Disclaimer I have not verified this.

**Comment by Patechoc** [comment]
I can also add that on Windows, the path to the generated HTML file get messed up between '/' and '\\'.
This causes the resulting URL to have a double slash.

I don't know if a systematic use of Pathlib could fix that!?

**Comment by Shinnnyshinshin** [comment]
@dmateusp Following up on your previous message, I'm wondering if this has something to do with how the Docker image is pulling from `develop`. Could I get a little more information on how you're doing this?

**Comment by Shinnnyshinshin** [comment]
@Patechoc Thank you for pointing this out. The previous issue was caused paths in S3 that had empty`prefix` values, meaning the files were being stored in the base directory of the S3 bucket.  This usecase is now (supposed to be) handled by #1317 . 

What you're describing on Windows may actually be a separate issue. Is there a way I could get some more information on this ? how are the paths changing for the generated HTML file?

**Comment by Patechoc** [comment]
I will try to come up soon with copy/paste and a reproducable case, but quickly, my setup is running GE directly on Windows within a pipenv virtual environment. Not through docker. I should defintely try running it from Docker to see if things go wild with WSL to, and I used GE in version 0.11.4
