### ISSUE TITLE
Expectations to all columns

### ISSUE THREAD

**Issue by solalatus** [fivetran/great_expectations#1316]
For `expect_column_values_to_not_be_null` and alike, it might make sense to make it easily possible to be applied to all columns (in case of eg. hundreds of columns, one does not have to loop)...

Separate expectations with an "all" prefix are maybe an overkill. How about an "all" string as column name in the existing function?

(If such facilities exist, please point me to them and accept my apologies...)

**Comment by colmsnowplow** [comment]
+1 but rather than either 'all' or 'just one', a list of given columns would be helpful.

**Comment by solalatus** [comment]
I still feel it relevant, but maybe subjective.

**Comment by crypdick** [comment]
+1, I think this is a much-needed feature. @solalatus @colmsnowplow I came up with a work-around in the meantime: https://stackoverflow.com/a/63475386/4212158
