### ISSUE TITLE
Add great_expectations version to a expectations configuration

### ISSUE THREAD

**Issue by jpcampb2** [fivetran/great_expectations#132]
To ensure that diagnosing changes to expectations themselves can be easier.

**Comment by abegong** [comment]
Can you give an example of what this would look like?

**Comment by jpcampb2** [comment]
I was thinking of adding a new entry to the expectations_config object, along the lines of:

```
{
  "dataset_name": null,
  "meta": {
      "ge_version": 0.2.1
    },
   "expectations": [ ... ]
}
```

The goal would be to ensure that if behavior/parameters of an expectation changes (e.g. `expect_column_kl_divergence`) we make it easier to match the config object to the version of ge that created it).
