### ISSUE TITLE
Defining multiple 'column' keys in expectation config json results in silently ignoring one of them

### ISSUE THREAD

**Issue by colmsnowplow** [fivetran/great_expectations#1320]
I noticed some unexpected behaviour when testing how the tool works - if I define two columns in an expectation, running it can still pass even though one of the two columns is ignored. For example:

```
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "page_view_id",
        "column": "session_id"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    }
```

Results in a passed config test, but only `session_id` is in the result set. 

Assuming `page_view_id` has been ignored, I would expect this to either throw a warning or an error - otherwise there's a risk of accidentally missing the fact that a (badly configured) test didn't run. It's the users fault, but still sub-optimal UX IMO.

**Comment by Aylr** [comment]
For single column expectations I agree that this is not the best user experience. Thanks for raising this in such a clear crisp way!

**Comment by colmsnowplow** [comment]
> Is this still relevant? 

🤷  it's not a major bug but I think it still exists - it's an inconvenience rather than a big problem.

For the record I would love to contribute a fix but my python is v rusty and I really struggle to find the time to put to side-projects these days, so I'm hesitant to stick my hand up to say I'll do so for now.  (sadly the case for several issues I've raised)
