### ISSUE TITLE
Notes not rendered by ValidationResultsPageRenderer in DataDocs

### ISSUE THREAD

**Issue by mlondschien** [fivetran/great_expectations#1331]
**Describe the bug**
Notes added to expectations via meta are not rendered when rendering using the `ValidationResultsPageRenderer`

**To Reproduce**
Minimal reproducible example:

```python
import pandas as pd
import great_expectations as ge
df_test = pd.DataFrame({"test_column": [1, 2, 3]})
ge_df = ge.from_pandas(df_test)
ge_df.expect_column_to_exist(
    column="test_column",
    meta={
        "notes": {
            "format": "markdown",
            "content": [
                "#### These are expectation notes \n - you can use markdown \n - or just strings"
            ],
        }
    },
    result_format="COMPLETE",
)
validation_result = ge_df.validate()
document_model = ge.render.renderer.ValidationResultsPageRenderer().render(
    validation_result
)
with open("path_to_file.html", "w") as writer:
    writer.write(ge.render.view.DefaultJinjaPageView().render(document_model))
```

**Expected behavior**
I would expect notes to be rendered with the validation results in the Data Docs.

**Environment (please complete the following information):**
 - OS: Linux
 - both GE 0.9.11, 0.10.2

**Additional context**
Thanks @eugmandel for helping me out!

Additionally it would be nice if one could add notes to the variables. We have notes describing each variable and it would be great if there was a possibility to add them to the Data Docs below the variable name.

**Comment by mlondschien** [comment]
Notes are still not rendered unter 0.11.5.

**Comment by satyakiroy1992** [comment]
Any fix to this issue ?
