### ISSUE TITLE
Validation-operator should support overwriting validation_operator_name and injecting values

### ISSUE THREAD

**Issue by dmateusp** [fivetran/great_expectations#1336]
I currently have a cli script which offers many of the features provided now by `validation-operator` CLI command. So I would like to deprecate this custom cli script, but I'm lacking some features.

* I think the `--name` should be usable along with `--validation_config_file` to overwrite the validation_operator_name, in my case I would want users to be able to use a validation_operator that publishes docs locally, and use the same config file in production but with S3 targets

* I would like to be able to template some parts of the validation_config_file or be able to pass it completely from the CLI, this is because we want to run QC on a subset of the data, based on timestamp: SELECT * FROM table WHERE event_time>'{{ some date that depends on today}}'

**Comment by Aylr** [comment]
@dmateusp Yes! We've been thinking similar things. In the next week there will be a new set of commands that allow this kind of thing:
- `checkpoint new` will allow configuration of a "checkpoint" (now known as taps), including specifying which `ValidationOperator` to run along with data and suites.
- `checkpoint run` will use a given config to run.

When I have a candidate PR available, I'd love your feedback on it.

**Comment by dmateusp** [comment]
I'll be happy to help! thanks

**Comment by Aylr** [comment]
Awesome! @dmateusp I'll ping you on a PR later this week!

**Comment by Aylr** [comment]
@dmateusp Please check out PR #1351 at let me know what you think in a PR review there!
