### ISSUE TITLE
Allow result_format to be configurable at the run_validation_operator level

### ISSUE THREAD

**Issue by colmsnowplow** [fivetran/great_expectations#1350]
**Is your feature request related to a problem? Please describe.**
If one would like to use different result formats for local and automated execution, this feature would improve workflow.

**Describe the solution you'd like**
Configure the result format per validation config. Perhaps this over-rides any configuration configured at expectation level.

**Additional context**
Asked about whether it's possible in Slack and was asked to raise an issue - so here you go! :)

**Comment by kolaworld** [comment]
Thanks for opening the issue @colmsnowplow.

It would be great if `result_format` could be set in _great_expecations.yml_ under the `validation_operators` section as a default. 

This default could then be overridden in the call to `context.run_validation_operator()` by passing in an arg for a `result_format` parameter.
