### ISSUE TITLE
MSSQL Server: non-boolean expression where condition is expected

### ISSUE THREAD

**Issue by user1002** [fivetran/great_expectations#1356]
**Describe the bug**
When running the init command on my MS SQL Server Query, I can getting the error

> [31m(pymssql.OperationalError) (4145, b"An expression of non-boolean type specified in a context where a condition is expected, near 'THEN'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n") [SQL: 'SELECT count(*) AS element_count, sum(CASE WHEN %(param_1)s THEN %(param_2)s ELSE %(param_3)s END) AS null_count, sum(CASE WHEN ([Result] IS NULL AND %(param_1)s = 0) THEN %(param_4)s ELSE %(param_5)s END) AS unexpected_count \nFROM [#ge_tmp_6e03e335]'] [parameters: {'param_1': 0, 'param_2': 1, 'param_3': 0, 'param_4': 1, 'param_5': 0}] (Background on this error at: http://sqlalche.me/e/e3q8)[0m[0m

I believe the error is happening within this logic:
` sum(CASE WHEN %(param_1)s THEN %(param_2)s ELSE %(param_3)s END) AS null_count`

Before WHEN, it should be a condition. Pasting this query in SQL Management Studio gives you this result:

_An expression of non-boolean type specified in a context where a condition is expected, near 'THEN'._

**To Reproduce**
1. Connect to MS SQL Server via SQL Alchemy
2. CLI great_expectations init
3. Provide query

**Expected behavior**
When the package generates this query, there should be a conidtion before **WHEN**

**Environment (please complete the following information):**
 - Windows 10 
 - GE Version: [e.g. 0.10.0]

**Additional context**

**Comment by alexsherstinsky** [comment]
Fixed -- in the upcoming release.  This is the Pull Request: https://github.com/great-expectations/great_expectations/pull/1717 (merged).
