### ISSUE TITLE
Can we add signatures to expectations? (Also autocomplete for arguments)

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#137]
I can't see function signatures in expectations.

They only contain `*args, **kwargs`, as in: `df.expect_column_value_lengths_to_be_between(*args, **kwargs)`

Example:
![screen shot 2017-12-01 at 7 11 52 am](https://user-images.githubusercontent.com/1239085/33488877-00b8db12-d667-11e7-840f-eaf243412325.png)

I suspect that if got signatures to show up, we'd also get tabbed autocomplete for expectation arguments. Also, it might help with the automatic expectation checking proposed in https://github.com/great-expectations/great_expectations/pull/130

**Comment by jpcampb2** [comment]
This is a python2 vs 3 thing, (in that @wraps doesn't preserve signatures in python2).

Can you see signatures properly when using python 3? I think we could bring in the decorator module to make this work in python2, but I'd rate it low on the priority list.

**Comment by jpcampb2** [comment]
@abegong I'd recommend closing this issue, or at least pulling it from the milestone as a blocker.

**Comment by abegong** [comment]
Yes, agreed.

**Comment by jcampbell** [comment]
Close.
