### ISSUE TITLE
Use click.(s)echo and click.style for terminal printing

### ISSUE THREAD

**Issue by mzjp2** [fivetran/great_expectations#1375]
**Is your feature request related to a problem? Please describe.**
Minimal impact on end-user, but I notice that codebase has a pretty hacky `cli_message` functionality that `print`s things to the terminal -- which isn't ideal. `print` shouldn't really be part of a codebase. I suspect things might have been done this way because of prior support of Python 2?

**Describe the solution you'd like**
Replace `cli_message` with `click.secho` or `click.style`, so `cli_message("<cyan>my_terminal_string</cyan>)"` that then gets regexed (slow?) and replaced gets replaced with `click.secho("my_terminal_string", fg="cyan")`.

`cli_message("<cyan>hi</cyan><green>bye</green>")` becomes `click.echo(click.style("hi", fg="cyan") + click.style("bye", fg="green")` and moreover `click` will fail if `fg` isn't a correct color, unlike `cli_message` which will simply print malformed text (e.g I can see one instance of `</greem>` in the codebase right now).

Additionally, you get to drop an extra dependency `termcolor` and the import error handling there, since `click` will just work on all/most? environments and is already a dependency. It also leaves the intricacies of dealing with `stdout` to `click` instead of simple `print` statements on GE's side.

Thoughts? I'm happy to give this a go piecemeal, but it'll be a rather large rewrite and will take a while on my side.

**Comment by Aylr** [comment]
We'd love it if you give this a shot! This would actually help with a known issue on windows where the ANSI colors are not displayed and show up as raw ANSI codes. And from a quick look at the click docs, if we use their recommendation with `colorama` that will get better for windows users to! https://click.palletsprojects.com/en/7.x/utils/#ansi-colors

Would you like me to assign this issue to you?

**Comment by mzjp2** [comment]
> Would you like me to assign this issue to you?

Go ahead, unless someone on the internal teams want to take it over. I'll make slow progress over the weekends. 😅

**Comment by Aylr** [comment]
We'd love you to have a shot. The nasty bits will be in ensuring the integration tests run - some are more "snapshotty" than I like - so ping me or open a "Draft PR" and we can collaborate!
