### ISSUE TITLE
Host a great_expectations Docker image

### ISSUE THREAD

**Issue by dmateusp** [fivetran/great_expectations#1377]
**Problem**

At Earnest we prefer using container-based Operators on Airflow rather than using the "Python Operators". This is because we previously were using Luigi with Python "Tasks" and felt the pain of accumulating dependencies in a shared image and tying up ETL related code with the scheduler.

**Solution**

A Docker image for great_expectations could be created, using checkpoint as an entrypoint (related PR https://github.com/great-expectations/great_expectations/pull/1351)

On Airflow, such an image could be used with the KubernetesPodOperator. Here's some code (obviously not working!) hopefully it helps getting the idea across.

In Airflow:

```python
KubernetesPodOperator(
        task_id='ge_transactions',
        image='great-expectations/great_expectations:v1.0',
        name='ge-transactions',
        cmds=[
            'run, 'transactions',
            '--validation-operator-name', 'validation_operator_prod',
            '--batch-kwargs', ...
        ],
        ...
    )
# I think it's important to be able to pass the "validation operator name", 
# in dev I would like analysts/engineers to be able to do everything locally.
# In production I want the validations to be pulled/pushed from and to S3,
# with central site documentations built iteratively across DAGs owned by different  teams

# {{ ds }} is the execution_date, if the batch kwargs use queries that filter on `{{ ds }}` 
# you could create idempotent data QC.

# I assume everything could be passed from the CLI. This is to avoid having
# users create their own Docker image just to include the `YAML` configs
# or having to integrate using configmaps (I think cli args are more analyst friendly)
```
**YAML vs CLI args**

I think as part of this effort, we should discuss the best way to parameterize checkpoint runs.

It might make sense to support checkpoints being ran without a YAML file (purely through CLI args). 
That's because 1. I think most of the parameters  will have to be dynamic due to dev/prod differences and to inject environment related information (execution_date), 2. not sure those parameters will be big enough to justify using a file vs CLI args, 3. these yaml files would have to be included in customized Docker images built on top of the GE-provided image, or added through ConfigMaps or sidecar/init containers in Kubernetes. 

Both could be supported, but for YAML files, I think the cli should support injecting vars, possibly the same way DBT supports it (YAML dictionaries) https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-variables/#defining-variables-on-the-command-line

e.g.

```yml
validation_operator_name: validation_operator_${env}
batches:
  - batch_kwargs:
      query: SELECT * FROM db_${env}.transactions WHERE ds = ${ds}
      datasource: redshift_${env}
    expectation_suite_names:
      - suite_one
      - suite_two
```

Note that this is a very Airflow-centric example, but the advantage of providing a container would also be being less tied to a specific scheduling technology. I'm thinking [KubeFlow](https://www.kubeflow.org/docs/pipelines/sdk/build-component/) and Data QC integrated in ML pipelines for example (although I never used KubeFlow)

**Comment by dmateusp** [comment]
@Aylr @eugmandel I tried to document in detail the use case for the Docker image I was talking about in https://github.com/great-expectations/great_expectations/pull/1351, let me know :)

**Comment by Aylr** [comment]
This  write up is wonderful!

**Comment by eugmandel** [comment]
@dmateusp Great description!

**Comment by dmateusp** [comment]
Now that https://github.com/great-expectations/great_expectations/pull/1584 was merged, could the GE team add details here of the first images being published (when they are published)?

Just for people finding this issue and looking for the official GE images

**Comment by Aylr** [comment]
Reopening just to track that images have not yet been published. I'll close this and add links to images once published!

**Comment by Aylr** [comment]
I've published a few 0.12.0 images here! https://hub.docker.com/repository/docker/greatexpectations/great_expectations
After verification I can publish some more and we can publicize this more widely.

**Comment by Aylr** [comment]
@danielledalton Please lmk how these go for you!

**Comment by Aylr** [comment]
Additional FYI here's a small doc on how to use them: https://github.com/great-expectations/great_expectations/pull/1797 (feedback would be delightful!)

**Comment by ddaltonrtr** [comment]
> Additional FYI here's a small doc on how to use them: #1797 (feedback would be delightful!)

@Aylr - I left some initial feedback on #1797 and will give the Docker image a try today!
