### ISSUE TITLE
Python API for creating suites

### ISSUE THREAD

**Issue by edublancas** [fivetran/great_expectations#1389]
**Is your feature request related to a problem? Please describe.**

I have a pipeline that I want to integrate with great expectations, and would like to automate creating suites for each file.

**Describe the solution you'd like**

Instead of doing this for every file:

```sh
great_expectations suite new

(prompt for file location)
(confirm suite name)
```

I'd like to code a Python script:

```python
for path in paths:
    ge.create_suite(path)
```

**Additional context**

I started looking at the source code to see what happens when I type (`great_expectations suite new`), this is what I have:

```python
from great_expectations.cli import toolkit

context = toolkit.load_data_context_with_error_handling('great_expectations')

toolkit.create_expectation_suite()
```
But `toolkit.create_expectation_suite()` uses `click.prompt`, seems like there is no Python API and everything should be done interactively. 

Are there any plans to provide a Python API to support this? Am I on the right track to get this done? (I'm ok mocking user input if it's my only choice).

**Comment by Aylr** [comment]
@edublancas Thanks for the thoughtful write up! Here are some ideas that should unblock you:

1. There is a python api `DataContext.create_expectation_suite()` that should be what you need: https://docs.greatexpectations.io/en/latest/module_docs/data_context_module.html?highlight=create_exp#great_expectations.data_context.BaseDataContext.create_expectation_suite

2. We definitely don't want you to mock user input. The intent of the CLI toolkit is to wrap the lower level python apis such as the one above in interactivity. The CLI is much newer code and in general does much less than the core `DataContext` apis.

**Comment by Aylr** [comment]
However, depending on what you mean by "create a suite" you may want to explore using the `BasicSuiteBuilderProfiler` that can help you write more boilerplate expectations.

**Comment by edublancas** [comment]
Hi @Aylr,

Thanks for the prompt response, I was able to make some progress.

This is my current code:

```python
import pandas as pd

from great_expectations.data_context import DataContext

# sample data
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
df.to_csv('iris.csv')

# creates great_expectations/ folder (just like the cli)
ctx = DataContext.create('.')

# creates an empty data suite
ctx.create_expectation_suite('new_suite')
```

The code above works well, but I'm wondering how can I get the same results as when executing: `great_expectations suite new`. The CLI asks for a data file and uses it to generate a pre-filled suite. Is that related to using `BasicSuiteBuilderProfiler`?

`BasicSuiteBuilderProfiler` takes a data asset parameter so I tried this:

```python
from great_expectations.profile.basic_suite_builder_profiler import BasicSuiteBuilderProfiler
from great_expectations.data_asset.file_data_asset import FileDataAsset

# throws error: GreatExpectationsError: Invalid data_asset for profiler; aborting
BasicSuiteBuilderProfiler().profile(FileDataAsset('iris.csv'))

# same error
BasicSuiteBuilderProfiler().profile('iris.csv')
```

Any ideas how to make that work?

**Comment by Aylr** [comment]
Ok! Now I understand that you want the "demo" suite! Here's a snippet that should get you there:

Typically you only create a `DataContext` once in any given project, so in this script you'll see I'm using one already in the current directory.

```
import great_expectations as ge
from great_expectations.profile import BasicSuiteBuilderProfiler

# Use an existing context or create a new one
context = ge.data_context.DataContext()

expectation_suite_name = "iris"
suite = context.create_expectation_suite(
    expectation_suite_name, overwrite_existing=True
)

batch_kwargs = {
    "path": "/path/to/your/csv/iris.csv",
    "datasource": "files_datasource",
    "reader_method": "read_csv",
}
batch = context.get_batch(batch_kwargs, suite)

suite, validation_result = BasicSuiteBuilderProfiler().profile(batch, profiler_configuration="demo")

context.save_expectation_suite(suite, expectation_suite_name)
```

If you want something better than the demo suite, I'd encourage you to try out the `great_expectations suite scaffold` command which builds a working notebook for you that only uses python APIs to write lots of boilerplate expectations for you in a highly configurable way.

Both the "demo" and what I've just described use the same BasicSuiteBuilderProfiler documented here:

https://docs.greatexpectations.io/en/latest/module_docs/profile_module.html#great_expectations.profile.basic_suite_builder_profiler.BasicSuiteBuilderProfiler

**Comment by edublancas** [comment]
I tried the code above but I'm getting an error when running:

```python
batch = context.get_batch(batch_kwargs, suite)
```

Traceback:

```pytb
In [25]: batch = context.get_batch(batch_kwargs, suite)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-4e4996738b8f> in <module>
----> 1 batch = context.get_batch(batch_kwargs, suite)

~/miniconda3/envs/ploomber/lib/python3.6/site-packages/great_expectations/data_context/data_context.py in get_batch(self, batch_kwargs, expectation_suite_name, data_asset_type, batch_parameters)
    686             expectation_suite = self.get_expectation_suite(expectation_suite_name)
    687
--> 688         datasource = self.get_datasource(batch_kwargs.get("datasource"))
    689         batch = datasource.get_batch(batch_kwargs=batch_kwargs, batch_parameters=batch_parameters)
    690         if data_asset_type is None:

~/miniconda3/envs/ploomber/lib/python3.6/site-packages/great_expectations/data_context/data_context.py in get_datasource(self, datasource_name)
    861         else:
    862             raise ValueError(
--> 863                 f"Unable to load datasource `{datasource_name}` -- no configuration found or invalid configuration."
    864             )
    865         datasource_config = datasourceConfigSchema.load(datasource_config)

ValueError: Unable to load datasource `files_datasource` -- no configuration found or invalid configuration.
```
I'm assuming I'm missing one step involving `ge.datasource.pandas_datasource.PandasDatasource` and
`context.add_datasource()`?

**Comment by Aylr** [comment]
Ah Yes! that snippet does assume you have a datasource. That's easiest with the CLI `great_expectations datasource new` but you can also use `context.add_datasource()` https://docs.greatexpectations.io/en/latest/module_docs/data_context_module.html?highlight=add_datasource#great_expectations.data_context.DataContext.add_datasource

**Comment by edublancas** [comment]
Thanks a lot @Aylr, it works now!

Here's the full working code in case it's useful for anybody:

```python
from great_expectations.profile import BasicSuiteBuilderProfiler
import great_expectations as ge
import pandas as pd

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',
                 names=['sepal_length', 'sepal_width',
                        'petal_length', 'petal_width',
                        'class'])
df.to_csv('iris.csv', index=False)

# Use an existing context or create a new one
context = ge.data_context.DataContext()

# Add a data source with class PandasDatasource
context.add_datasource('pandas_datasource', class_name='PandasDatasource')

# create an empty suite
expectation_suite_name = "iris_suite"
suite = context.create_expectation_suite(
    expectation_suite_name, overwrite_existing=True
)

# create a batch from a csv file
batch_kwargs = {
    "path": "iris.csv",
    "datasource": "pandas_datasource",
    "reader_method": "read_csv",
}
batch = context.get_batch(batch_kwargs, suite)

# generate demo suite
suite, validation_result = BasicSuiteBuilderProfiler().profile(
    batch, profiler_configuration="demo")

# overwrite suite on disk
context.save_expectation_suite(suite, expectation_suite_name)

```
