### ISSUE TITLE
Tidy up and standardize expectation docstrings

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#142]

**Comment by abegong** [comment]
* Formatting is inconsistent across expectations
* Orderings are wrong
* This is building the glossary *twice*---once from base and once from pandas.
* Should parameters include expected types?

Bad example: http://great-expectations.readthedocs.io/en/latest/great_expectations.dataset.html#great_expectations.dataset.base.DataSet.expect_column_to_exist

Good example:
http://great-expectations.readthedocs.io/en/latest/great_expectations.dataset.html#great_expectations.dataset.pandas_dataset.PandasDataSet.expect_column_kl_divergence_to_be_less_than

Things this gets right:
* Parameters are clearly identified and indented
* Returns are clearly identified and indented

Some nits about the KL_divergence example
* Remove grayed paragraphs
* Formatting of result objects is weird

### Plan of record:
Abe to convert ~3 of these to gold standard, then review formatting with @jpcampb2, and make a plan for converting the rest.

**Comment by abegong** [comment]
@jpcampb2 How do you like this formatting?

![screen shot 2017-12-09 at 8 32 18 am](https://user-images.githubusercontent.com/1239085/33797385-a221f43e-dcbb-11e7-9d02-ade21a5f39ec.png)

Formatting those output dictionaries has been a huge pain.

**Comment by jpcampb2** [comment]
I really like it. Couple questions:

1. Does that way of formatting allow us to nest deeper (for example when describing summary_obj?
2. Is it possible to link to the docstring for `@column_map_expectation` and describe the common return object elements that will be part of the summary_obj in the expectation's return?
3. What do you think of instead of using two conventions (one for parameters and one for returns), describing each of the components in returns in a bullet list, along the lines of:

```
Returns:
- success (bool): True if the most common value in the column is from the provided set.
- true_value (any): The most common value in the column
- summary_obj: {
(<href: column_map_expectation summary information>)
}
```

Nits: 
 - return types should be real types or Any/Union etc. (so `bool or None` instead of `bool_or_none`)
 - `parameter (type):` (vs. `parameter (type) -` )
 - Confirming this is format focused (e.g. true_value is describing the wrong thing in this expectation)

**Comment by abegong** [comment]
@jpcampb2 We should discuss.

Derek and I went with Google-style formatting early on, without much reflection. Now, we should make a real decision.

The three main options are
* Sphinx-style (great HTML output; hard-to-read docstrings)
* Google-style (lousy HTML output++; easy-to-read docstrings)
* Numpy-style (lousy HTML output++; longer, more descriptive docstrings)

(Ref: https://bwanamarko.alwaysdata.net/napoleon/format_exception.html)

++ The relatively new Napolean library is supposed to solve this problem. It compiles make Google and Numpy-style docstrings to clean HTML docs. (Ref: https://pypi.python.org/pypi/sphinxcontrib-napoleon)

I'm inclined to try Numpy-style (Examples: http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html). We have quite a few long descriptions, and (assuming Napolean works), there's no real tradeoff between the quality of HTML and docstrings any more.

Also, this may be a case of grass-is-greener, but after spending the last 3 hours on Sphinx-style RST docstrings, I've started to loathe it. How can a documentation tool have such lousy documentation?

**Comment by abegong** [comment]
Okay, I've tested Napoleon on a few cases. So far, it just works. Here's an example:

![screen shot 2017-12-09 at 9 53 47 am](https://user-images.githubusercontent.com/1239085/33798070-1efc24e2-dcc7-11e7-80f8-583ef575fb05.png)


Also, it doesn't appear to mess up any of the stuff that I got working in RST-style earlier this morning. This makes me much more confident in the tool---if we don't like the output in specific cases, we can always override with RST.

@jpcampb2 If this looks good to you, I'll tidy up the rest of the expectations docstrings. Just say the word!

PS: several of the non-expectation methods in DataSet are missing docstrings. I've opened a separate issue for that: #151

**Comment by abegong** [comment]
Oops, I missed your earlier response.

1. Yes, we can nest deeper.
2. I haven't figured out a way to do this, but I agree that it absolutely should be part of the docstring. Worst case, we can just manually add parameters to the docstrings in base.py
3. I don't love mixing formats, but I think it's important to emphasize that return values are dictionaries. Doing this visually feels much better than using bullet points to me.

**Comment by abegong** [comment]
On nits: I agree with 1 and 2.

3 is the Sphinx default. I haven't been able to find a simple way to switch it off. I agree that it'd be better without the hyphen, but it doesn't bother me that much.

**Comment by jpcampb2** [comment]
OK, sounds like we have a plan! Thank you very much for researching so much, especially to now have the Napolean option seems perfect!
