### ISSUE TITLE
great_expectations checkpoint run verbosity

### ISSUE THREAD

**Issue by anordin95** [fivetran/great_expectations#1437]
**Is your feature request related to a problem? Please describe.**
```
 $ great_expectations checkpoint run my_checkpoint
Heads up! This feature is Experimental. It may change. Please give us your feedback!
Validation Failed!
```

`my_checkpoint` runs a batch of sample data against two distinct `expectation suite`'s. Currently one of the suites passes and one fails, however that is not apparent from the terse output provided by `checkpoint run`.

**Describe the solution you'd like**
A solution inspired by pytest would be nice.

E.g.

suites                |          result
null_checker ................. PASS
value_checker .............. FAIL

etc...

**Comment by Aylr** [comment]
@anordin95 Is this something you'd be interested in working on? It'd be a relatively small and contained PR!

**Comment by anordin95** [comment]
Hey @Aylr! This does look cool and I'm keen to contribute, but to be frank I'm already rather swamped with my regular job at the moment, so I'm hesitant to commit to something I may not be able to complete.

**Comment by Aylr** [comment]
No worries at all! Thanks for the refreshing candor!

**Comment by Aylr** [comment]
FYI @anordin95 something good is coming your way! #1922
