### ISSUE TITLE
suite new leaks paths in expectations

### ISSUE THREAD

**Issue by ghost** [fivetran/great_expectations#1451]
**Describe the bug**

The `suite new` command leaks the full path to the data being tested.  This is a problem because when developing, that path will typically be within the engineer's home directory, which means the username may leak when the expectation is published.

This appears not to be necessary, as a relative path also works.

**To Reproduce**
1. Run `great_expectations suite new` and create a new suite for a local file (using a relative path or not)
2. Run `grep -r path great_expectations/expectations/`
4. See full paths listed

**Expected behavior**
Instead of full paths, a relative path should be used when the user has provided one in the `suite new` command.

**Environment (please complete the following information):**
 - OS: Mac
 - GE Version: 0.10.10

**Additional context**
I have removed the full path locally, and a relative one appears to be working fine - eg. `data/example.csv`

**Comment by syahdeini** [comment]
This look relatively simple, CMIIW you just need to change this line.
https://github.com/great-expectations/great_expectations/blob/9d85b7e0543d170e73df99dcc985c649a0f395bb/great_expectations/cli/datasource.py#L1141

I will work on this issue @Aylr, please can assign me.

**Comment by Aylr** [comment]
Thanks for volunteering @syahdeini !

**Comment by vanderGoes** [comment]
@syahdeini Great to see you here too Aldy. Did it work out in the end, or shall we fix it together?
