### ISSUE TITLE
New expectation: expect_sum_of_columns_to_be_equal

### ISSUE THREAD

**Issue by franciscorubin** [fivetran/great_expectations#1452]
**Is your feature request related to a problem? Please describe.**
I would like to be able to enforce the sum of multiple columns in a row to be equal to 1 (each column represents a percentage of the total).

**Describe the solution you'd like**
A new expectation type "expect_sum_of_columns_to_be_equal" which allows defining a set of columns for which the sum of their values should equal to a specified number.

**Describe alternatives you've considered**
Another more flexible alternative would be to allow to define custom expectations programatically (for example with python functions).

**Comment by jcampbell** [comment]
@pancho111203: this is a great idea, and we'd be happy to work with you on a PR!

**Comment by chipmyersjr** [comment]
@jcampbell @pancho111203 Is it ok if I try this one?
