### ISSUE TITLE
KL Divergence graphs in validations should have same Y maxiumum

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1463]
**Describe the bug**
When comparing expected and observed KL divergence plots they should have the same Y axis maximum.
**To Reproduce**
1. Run a KL divergence validation
2. Build docs
3. Note the sometimes unequal max Y value.

<img width="1463" alt="Screen Shot 2020-05-20 at 2 43 54 PM" src="https://user-images.githubusercontent.com/928247/82495553-81239f00-9aa8-11ea-9b21-26e8bbbe99b5.png">

**Expected behavior**
In the case above I would expect both of the Y axes maximums to be 1.0 for easy visual comparison.

**Environment (please complete the following information):**
 - OS: macOS
 - GE Version: 0.10.11

**Comment by bjakubowskiVNSNY** [comment]
Would love to see this reopened!

**Comment by Buedenbender** [comment]
Just stumbled upon this issue while looking for something else is this implemented in the meantime? It sounds reasonable
