### ISSUE TITLE
Output list of failed rows

### ISSUE THREAD

**Issue by CornerTakenQuickly** [fivetran/great_expectations#1473]
My users requirement is to see a list of rows from the input dataset that failed expectations. So, I would like the ability to configure Great Expectations to output a specified set of fields from the failed input row. Upon execution of an expectation, output a list that contains the specified fields from the input for each row that fails.

**Comment by eugmandel** [comment]
@CornerTakenQuickly The validation result contains the unexpected values in the column. As a workaround, you can filter out all records where the value of that column is in the unexpected list.

We are thinking of supporting an easy split of the data into "passing" and "failing" row, but this is not on the immediate roadmap.
