### ISSUE TITLE
Input handling inconsistent between column_(pair_)map_expectation wrappers

### ISSUE THREAD

**Issue by mlondschien** [fivetran/great_expectations#1481]
Wheras the `column_map_expectation` wrapper passes `column` as a string containing the name of the column, the `column_pair_map_expectation` wrapper passes `column_A` and `column_B` as a `pd.Series` (see [here](https://github.com/great-expectations/great_expectations/blob/ef289ea1700aee3c2d49685348cbc00eb991a0ca/great_expectations/dataset/pandas_dataset.py#L171)). Is this as expected?

**Comment by Aylr** [comment]
I could be mistaken, but on my read of that code the `column_A` and `column_B` parameters are passed as strings to the expectation, and the series is used internally to extract the column data from the dataframe. I think this is intentional.

**Comment by mlondschien** [comment]
Sorry, my mistake. The inconsistency is actually between the `column_(pair_)map_expectation` and the `column_aggregate_expectation` wrappers. For the former two, `column` and `column_A(_B)` are passed as `pd.Series`, whereas in the latter, `column` is passed as string, see [expect_column_values_to_be_in_set](https://github.com/great-expectations/great_expectations/blob/e9f71b2707c880d8a637ec6cfdc0139aba77cd58/great_expectations/dataset/pandas_dataset.py#L939) and [expect_column_pair_values_to_be_equal](https://github.com/great-expectations/great_expectations/blob/e9f71b2707c880d8a637ec6cfdc0139aba77cd58/great_expectations/dataset/pandas_dataset.py#L1571) compared to [expect_column_bootstrapped_ks_test_p_value_to_be_greater_than](https://github.com/great-expectations/great_expectations/blob/e9f71b2707c880d8a637ec6cfdc0139aba77cd58/great_expectations/dataset/pandas_dataset.py#L1462). Again, is this intentional?

**Comment by jcampbell** [comment]
@mlondschien  -> Yes, this is intentional. In the case of the map-style expectations, the decorator handles the translation of the boolean series into the result format so that the implementations can be very lean. 

In contrast, the aggregate expectations need to handle more of their own implementation, and/or often have more difference in backends, so they work with the backend and the column name directly.
