### ISSUE TITLE
Support Presto (0.172) and AWS Athena as a SQLAlchemy backend

### ISSUE THREAD

**Issue by dmateusp** [fivetran/great_expectations#1486]
# Why?

[AWS Athena](https://aws.amazon.com/athena/features/?nc=sn&loc=2) is an AWS service that supports a server-less query system. It is based on Presto version 0.172 [(source)](https://docs.aws.amazon.com/athena/latest/ug/presto-functions.html). Without worrying about infrastructure, users can query data on S3, which makes it a really good tool to provide to analysts.

[Presto](https://prestodb.io/) is a distributed SQL engine that has the special feature of being able to unify data from different databases (join a hive dataset with an elastic search dataset for example).

At Earnest, we are very interested in AWS Athena support for Great Expectations. AWS Athena leverages Presto and is mostly (if not 100%) compatible with the Presto dialect.

While Presto is not of interest to us immediately at Earnest, I think we could use a Dockerized image of Presto to implement integration testing for both AWS Athena and Presto (so we don't rely on an AWS account to run the automated tests of the repo).

The folks at DBT have a [dbt-presto](https://github.com/fishtown-analytics/dbt-presto) plug-in that they test through an image spun up in CI: [fishtownanalytics/presto](https://hub.docker.com/r/fishtownanalytics/presto)

# Implementation

* Conditionals need to be added in `great_expectations/dataset/sqlalchemy_dataset.py` for presto and athena
* Tests need to be updated to take in account data types that are not supported by Presto (like DATETIME for example)
* Potential tweaks in implementation of expectations
* AWS Athena and Presto do not support creating temporary tables, we should CREATE TABLE instead, or give a choice between CREATE TABLE and CREATE VIEW
* A Docker image with Presto should be spun up during CI to test expectations

I have started the work on this [PR](https://github.com/EarnestResearch/great_expectations/pull/9), I have yet to get the tests working but I wanted to start a discussion / raise awareness around this feature request since we talked about it with the core GE team during an Earnest <> GE meeting

# Related

[Temporary table creation when using Presto](https://github.com/great-expectations/great_expectations/issues/569)

**Comment by Aylr** [comment]
This is going to be an excellent addition and we are pumped about it!

**Comment by dmateusp** [comment]
@mascah highlighted that Presto 0.172 used by AWS Athena today can have differences in dialect and features compared to the most recent version of Presto

I am going to split the combined PR of AWS Athena and Presto into 2 PRs:
- Presto 0.172 PR (to add Presto support for that version, and expectation tests)
- AWS Athena PR (once Presto 0.172 is tested and working, adding AWS Athena support *should* be easy)

The goal for us at Earnest is to integrate with AWS Athena, so we don't have an immediate interest in supporting a recent Presto version (0.172 is only to run tests on CI, compatible with AWS Athena without having to use an AWS Account). I'm going to update the Issue title (if there's interest in the community for a recent Presto version, another issue / PR could be created?)

@abegong

**Comment by mascah** [comment]
@dmateusp I'm certainly in favor of targeting 0.172 first, as we're primarily interested in Athena support in our organization as well. 

As far as how we can add test support for Athena/0.172 specifically, I took a look at how PyAthena is running their tests and as far as I can tell they're running integration tests against S3 & Athena in an AWS account. 

The dbt plugin for Athena (https://github.com/Dandandan/dbt-athena/) doesn't seem to include any tests at the moment either.

I wasn't able to find a presto image for 0.172 either. What are your thoughts on this?

**Comment by dmateusp** [comment]
I read more about the Presto versions and learned about PrestoDB vs PrestoSQL.

PrestoDB seems to be the project we refer to when we talk about 0.172, it is the original project maintained by Facebook, PrestoSQL seems to be a fork created by the contributors of PrestoSQL when they created the Presto Foundation. See this issue: https://github.com/prestosql/presto/issues/380

I should update the issue to be very clear about the distinction (this issue is about PrestoDB). The DBT image we were using is actually based on PrestoSQL.

I found an image on [0.174](https://hub.docker.com/layers/pubnative/prestodb/0.174/images/sha256-3e07ebbb86fab65312a3139acf93efbc4a8bc54c9b6a57ce4f0a4f3199e9932d?context=explore), we could potentially fork the [repository](https://github.com/pubnative/docker-images/blob/master/prestodb/Dockerfile) and build/deploy an image at 0.172 to more closely match AWS Athena

**Comment by mascah** [comment]
😕 huh... very interesting, I was unaware of this as well. Learned something new today, thank you for the link. 

Good find on the image, that will be extremely helpful if it works correctly! It looks like the changes between [0.172 -> 0.173/0.174 are minor](https://prestodb.io/docs/0.174/release/release-0.174.html). We can hopefully save ourselves the trouble of managing an image.

**Comment by valerii-vorobiov** [comment]
Hey

@dmateusp , I also faced with the same issue, but using **PrestoSQL** version 326. And as we are using Presto as our main computation engine it is super useful to have Presto integration.
Could you share the progress on that?

**Comment by dmateusp** [comment]
hi @valerii-vorobiov internally we have started using Great Expectations on Redshift (we're migrating off Redshift), right now it seems like we are going to interact with S3 data mainly through Snowflake external tables in the future rather than AWS Athena.

I haven't made progress on this issue as other requirements became higher priority (for the reason above) since with Snowflake external tables, AWS Athena is not a blocker for us.

I still have this Draft PR: https://github.com/EarnestResearch/great_expectations/pull/9 with some Work in progress which allows the tests to run, maybe you'd want to start from that branch and potentially take over?

**Comment by Shinnnyshinshin** [comment]
Thank you both for your responses. @valerii-vorobiov, since this is no longer a priority for the original author, would you be interested in taking this issue over? We would be more than happy to provide support and feedback.

**Comment by dmateusp** [comment]
Also, @valerii-vorobiov @Shinnnyshinshin, this issue is related to PrestoDB, not PrestoSQL, my original motivation for this issue was to provide a local integration testing environment as close to AWS Athena as possible.

I think PrestoSQL might warrant a different implementation and different issue?

**Comment by Dandandan** [comment]
Great to see that you started a PR let me know when I can help here @dmateusp :D

Would be very useful for me as well to see Athena support! I saw for profiling it's working for 95% currently for `greatexpectations datasource profile`

But got some errors as well:

`botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:42: missing 'BY' at '('` 

`botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 4:10: mismatched input 'OFFSET' expecting <EOF>`

Do you think that would be fixed by your PR?

**Comment by Dandandan** [comment]
Ah I see you mention those in the PR as well, quite some things to fix still :)

**Comment by dmateusp** [comment]
hey @Dandandan great to see you here :), I'm just back from OOO so let me give a quick update on this issue:

We (at Earnest) initially foresaw running most of our GE workloads through AWS Athena, but with our move to Snowflake we are now thinking about (at least initially) using Snowflake instead. This has shifted my focus away from this PR, so I'm happy with someone else from the community taking over this work if more aligned with their requirements (more urgent).

### About integration tests on this PR:

I was trying to run the GE tests against a PrestoDB image (which Athena is based on), but per our discussion (with you @Dandandan on the DBT #athena Slack https://getdbt.slack.com/archives/C013MLFR7BQ/p1593622592042300), your experience with developing the `dbt-athena` integration was that Athena actually differs from Presto in meaningful ways. The PR I ended up opening on your repo (@Dandandan) https://github.com/Dandandan/dbt-athena/pull/32 just gives some instructions on how to run the integration tests against an AWS Account (so each contributor / reviewer can run it). 

I think we could do the same thing here, forget about PrestoDB and use an AWS account for testing, and then we could talk about adding it to the CI, wdyt?
