### ISSUE TITLE
Validate should return entire row not just index

### ISSUE THREAD

**Issue by eringong** [fivetran/great_expectations#150]
It would be nice if validate could return the entire row for failed expectations, not just the index. This would streamline the flow for seeing problems in context.

**Comment by abegong** [comment]
Proposal: Validate should take an optional boolean `return_affected_rows` argument. If it's true, then validate returns:
```
{
  "meta" : {...the normal meta object...},
  "results" : [ ...the normal list of results...],
  "affected_rows" : [A list of dictionaries, similar to df.to_records()]
}
```

Since most of the output formats already include an `exception_index_list` or `partial_exception_index_list`, it would be easy look up records from `affected_rows` by their indexes.

**Comment by dlwhite5** [comment]
Taking a look at this.

What do we want the default behaviour to be with respect to the list of rows in affected_rows?

Should the index be included in the rows that constitute affected_rows or just the row data?

Or do we want another boolean that gives the user the option of requesting the index or not? If so, what is the default? Index included or not?

**Comment by dlwhite5** [comment]
I'm going to punt on this issue so someone else can work on it if they want.

**Comment by jcampbell** [comment]
ping on this: just got a new request here @eugmandel

**Comment by jcampbell** [comment]
Further enhancement here would require additional design that isn't currently on the backlog, but is tracked in our long-term roadmap.
