### ISSUE TITLE
JSON file path issue while creating new Expectation Suite 

### ISSUE THREAD

**Issue by pankaj890** [fivetran/great_expectations#1508]
After I upgraded to GE version 0.11.0, I am getting the incorrect file path error for the expectation's JSON file.

1. Try creating a new expectation suite by using either of below commands
        great_expectations init
        great_expectations suite new

You will get below error while saving suite's JSON file:
[WinError 123] The filename, directory name, or volume label syntax is incorrect

**Environment (please complete the following information):**
 - OS: Windows 10
 - GE Version: 0.11.0

**Comment by Aylr** [comment]
@pankaj890 thank you for this report! I suspect that last night's release of version `0.11.1` fixes this issue since it had some windows path fixes in it. Would you mind upgrading and verifying this for me? https://github.com/great-expectations/great_expectations/releases/tag/0.11.1

**Comment by pankaj890** [comment]
Yup!
It seems to be working now!

**Comment by Aylr** [comment]
Thanks a ton! I'm closing this issue.
