### ISSUE TITLE
DataSet docstrings

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#151]
* initialize_expectations needs a docstring, and should be a private function
* append_expectation needs a docstring, and should be a private function
* _copy_and_clean_up_expectation needs a docstring
* _copy_and_clean_up_expectations_from_indexes needs a docstring
* get_default_expectation_arguments needs a docstring
* set_default_expectation_argument needs a docstring
* save_expectations_config needs a docstring
* validate needs a docstring
* format_column_map_output needs a docstring, and should be a private function
* calc_map_expectation_success needs a docstring, and should be a private function

**Comment by abegong** [comment]
Most of these docstrings are still missing, except for the last 2, `get_default_expectation_arguments` and `set_default_expectation_argument`.

**Comment by ccnobbli** [comment]
I'll take a crack at this, I want a good look at the guts anyhow

**Comment by ccnobbli** [comment]
I played around with changing these to private methods, but it was messing up certain tests. Given the current overhaul of the testing framework, that half of this issue should sit on the back burner.

**Comment by abegong** [comment]
:+1:

**Comment by abegong** [comment]
@ccnobbli When I said private function, I basically meant renaming from `format_column_map_output` to `_format_column_map_output`.

Were you thinking of something more involved?

**Comment by nobbyhawk** [comment]
@abegong That's what I had understood, adding the underscore to make them private. There are a few  places in the tests that use these functions explicitly, outside of their class. For example `initialize_expectations()` is used to wipe any expectations config from a great expectations object in a few places. 

I'll try my hand at this today but I'll ping you if I can't get it rolling!

**Comment by ccnobbli** [comment]
@abegong That's what I had understood, adding the underscore to make them private. There are a few places in the tests that use these functions explicitly, outside of their home class. For example initialize_expectations() is used to wipe any expectations config from a great expectations object in a couple of tests.

I'll try my hand at this today but I'll ping you if I can't get it rolling!

**Comment by abegong** [comment]
@ccnobbli Can we close this issue, or are there still unfinished bits?

**Comment by ccnobbli** [comment]
@abegong it's all done! Close 'er on up.
