### ISSUE TITLE
Equivalent Regex '^S[0-9]{9}' and '^S\d{9}' yield different results for expect_column_values_to_match_regex on batch data

### ISSUE THREAD

**Issue by bkraft4257** [fivetran/great_expectations#1517]
**Describe the bug**
When I applied expect_column_values_to_match_regex to a column in a 

batch of data pulled from a database I obtained two different answers for two equivalent regex expressions. Regular expression one is '^S[0-9]{9}'. I also tried the equivalent regular expression '^S\d{9}'. Although the regular expressions are equivalent the first regular expression worked as expected while the second regular expression failed. I have included my batch setup, which was created automatically by Great Expectations. Along with a screenshot of the results. PHI has been blurred out.

I have also done some initial testing to try and isolate the problem. I was surprised to learn that both regular expressions work as expected on Pandas and Great Expectation data frames. I tried to run Great Expectation test to investigate this problem but encountered issues with my test environment. I am also new to Great Expectations so it was going to be a while before I will be able to understand the code to create an appropriate pull request.

**To Reproduce**
See the attached PDF and image for more details. 

<img width="597" alt="ge_batch_regex_bug" src="https://user-images.githubusercontent.com/10143816/83356807-7b467d00-a336-11ea-9892-7ea26d2ac0c5.png">

[great_expectations_regex_bug_in_batch.pdf](https://github.com/great-expectations/great_expectations/files/4707921/great_expectations_regex_bug_in_batch.pdf)

**Expected behavior**
Equivalent regular expressions should produce identical results.  If you use these two equivalent regex expressions in an expectation directly on a Great Expectations data frame they produce identical results. 

**Environment (please complete the following information):**
 - OS: MacOs X
 - GE Version: 0.11

**Comment by jcampbell** [comment]
@bkraft4257 -> GE is passing your regular expression through to the underlying engine (which is why this is working in pandas); what database environment are you using where the second is failing?

**Comment by bkraft4257** [comment]
MySql.

**Comment by jcampbell** [comment]
MySQL does not support the `\d` syntax: https://dev.mysql.com/doc/refman/5.7/en/regexp.html

The equivalent syntax in MySql would be `^S[[:digit:]]{9}`
