### ISSUE TITLE
great_expectations checkpoint list truncating name

### ISSUE THREAD

**Issue by anthonyburdi** [fivetran/great_expectations#1518]
**Describe the bug**
When running `great_expectations checkpoint list` the checkpoint name is truncated to either 14 characters or the last character is removed (I am not sure which).

**To Reproduce**
1. Create a checkpoint with at least 15 characters
2. Run `great_expectations checkpoint list`

**Expected behavior**
The list should be accurate based on the checkpoint names

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - GE Version: 0.11.0

**Comment by eugmandel** [comment]
Confirmed.

**Comment by Aylr** [comment]
`great_expectations checkpoint list` also suffers from this bug.

**Comment by Aylr** [comment]
`great_expectations checkpoint list` appears to strip off all `l`s so if you have a checkpoint named `lllll` it will show up as `- `

**Comment by eugmandel** [comment]
@Aylr , yes, "rstrip" was used to remove the yml file extension. Fixing.
