### ISSUE TITLE
Docs and tool omit it can only handle tabular data

### ISSUE THREAD

**Issue by stitch** [fivetran/great_expectations#1524]
**Describe the bug**
The documentation and tool do not notice that validation can only happen for tabular data (rows and columns). In our project we get only json files via API requests, and want to validate those (akin to schema validation, but better and automated).

After attempting loading five different json files, analyzing the errors and then trying the sample data, it became clear that only rows and columns seem to be supported. If i'm wrong: please include a sample with a reasonably interesting json file with some lists and dicts mixed.

**To Reproduce**
Use `great_expectations init` and select a json file. Parsing will crash with at least some of the following errors:

- ValueError: If using all scalar values, you must pass an index
- ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.
- TypeError: unhashable type: 'dict'
- ValueError: arrays must all be same length
- TypeError: unhashable type: 'list'

Resuming the process, great_expectations thinks everything went well and asks to generate (empty) docs.

**Expected behavior**
A warning that only tabular data is supported, and that json files with nested lists or dicts will result in an error.
Re-attempting to run init would not produce empty docs, but should let you select a file again.
 
**Environment (please complete the following information):**
Mac OS catalina, great expectations 0.11.1

**Additional context**
Looks promising, and if you only work with tabular data, this library can be spectacular. We're not, but it's not apparent that this project wasn't for us.

**Comment by eugmandel** [comment]
@stitch Thank you for pointing this out! This document says that the existing expectations support only tabular data, but we should make it more prominent.

**Comment by eugmandel** [comment]
@stitch We added a brief article on our Discuss forum: https://discuss.greatexpectations.io/t/can-i-use-great-expectations-to-validate-non-tabular-data/255
