### ISSUE TITLE
Validations nested under two slightly different timestamped folders

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1527]
**Describe the bug**
Validations are stored locally under 2 folders named with timestamps that are milliseconds different.

**To Reproduce**
1. `great_expectations checkpoint run foo` (that validates a suite named `staging.foo.warning`)
2. Navigate to `great_expectations/uncommitted/validations`
3. Note directory structure:

```bash
great_expectations/uncommitted/validations
└── staging
    ├── foo
    │   └── warning
    │       ├── 20200601T234803.119165Z
    │       │   └── 20200601T234803.119210Z
    │       │       └── f5c630840c6dceeeac5c437655ddc42e.json
    │       └── 20200601T235855.283993Z
    │           └── 20200601T235855.284041Z
    │               └── f5c630840c6dceeeac5c437655ddc42e.json
```
4. Note that when data docs are built this same double nested structure occurs in the breadcrumbs, directory structure and urls.

<img width="1264" alt="Data_documentation_compiled_by_Great_Expectations" src="https://user-images.githubusercontent.com/928247/83551522-ae6b4680-a4c5-11ea-9119-be7717bfa00e.png">

**Expected behavior**
I would not expect the second layer deep of timestamped directories

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - GE Version: [e.g. 0.10.0] 0.11.1

**Additional context**

**Comment by jcampbell** [comment]
Those come from the two components of the run_id: run_name and run_id.

Normally, we expect you would provide a run_name, in which case that will become one of the components used to store the result.

It might make sense to use the *same* timestamp both times when the user does not provide a run_name...what do you think @roblim ?

**Comment by roblim** [comment]
Oh, that's not a bad idea. Right now if no run_name is given, it's just `None`, which gets translated to `__none__` for stores. 

Looking into above bug now. Those timestamps should def be the same. If user provides just a run_name, (or a string run_id), we try parsing it as datetime first, and if we can, we use same timestamp for run_time. May have overlooked something when doing the timezone stuff.

**Comment by Aylr** [comment]
This was fixed in https://github.com/great-expectations/great_expectations/pull/1547
