### ISSUE TITLE
Distributional expectations should provide hints for display

### ISSUE THREAD

**Issue by mgasner** [fivetran/great_expectations#153]
For display purposes, it is helpful to know whether a distributional expectation concerns a Bernoulli, discrete, or continuous distribution.

**Comment by jcampbell** [comment]
Can you clarify where that hint would be most useful?

Currently, only `expect_column_kl_divergence_to_be_less_than` is able to accept both continuous and discrete distributions. `expect_column_chisquare_p_value_to_be_less_than` only works for discrete partitions, and `expect_column_bootstrapped_ks_test_p_value_to_be_less_than` only works for continuous partitions.

(Currently, a Bernoulli distribution would be described as just a special case of a discrete partition in great expectations).

**Comment by jpcampb2** [comment]
Can you clarify where the hints would be most useful?

Currently, only `expect_column_kl_divergence_to_be_less_than` is able to accept both continuous and discrete distributions. `expect_column_chisquare_p_value_to_be_less_than` only works for discrete partitions, and `expect_column_bootstrapped_ks_test_p_value_to_be_less_than` only works for continuous partitions.

(Currently, a Bernoulli distribution would be described as just a special case of a discrete partition in great expectations).

**Comment by jpcampb2** [comment]
I'm going to close this since there hasn't been activity on it; I think the docstrings inheriting now address this.
