### ISSUE TITLE
Expectation glossary link in suite edit notebook is broken

### ISSUE THREAD

**Issue by roselightheart** [fivetran/great_expectations#1557]
**Describe the bug**
Expectation glossary link in suite edit notebook is broken

**To Reproduce**
1. open suite edit notebook
2. click on expectation glossary link
3. oh no it's broken

**Expected behavior**
Link should not be broken

**Environment (please complete the following information):**
 - OS: N/A
 - GE Version: 0.11.2

**Additional context**
N/A

**Comment by Aylr** [comment]
Closed in https://github.com/great-expectations/great_expectations/pull/1569
