### ISSUE TITLE
Example of a restful GE implementation?

### ISSUE THREAD

**Issue by cwerner** [fivetran/great_expectations#1562]
Hi (and sorry if this is the wrong place for this)

I want to implement a restful app/ endpoint (using fastapi) that gets sent a CSV and return the validation result. Additionally I’d like to allow to pass new expectations to the app for future validations. Is there any example of something like this? best practices? And would you say this setup is feasible or should I think about another design?

Cheers,
C

**Comment by eugmandel** [comment]
@cwerner We don't have an example of something like that, but the idea makes sense. One issue to watch for is the size of the CSV files. This design means that that you "bring the data to the compute", not the other way around.

**Comment by cwerner** [comment]
Yes, the CSV files are 1MB max. Not ideal, but I can send them... I'll try to come up with some code on my own then...

Thanks @eugmandel
