### ISSUE TITLE
Rename great_expectations.__version__ key in JSON response

### ISSUE THREAD

**Issue by cwerner** [fivetran/great_expectations#1564]
Currently, the GE version is encoded in the meta section of run_results in the form of `great_expectations.__version__`

If one uses utilities that provide dot-notation to navigate the deep JSON tree (i.e. python-benedict, https://github.com/fabiocaccamo/python-benedict) this breaks since there now is a dot in the key (not sure if this is prohibited in any standards)...

Proposed change: rename key from `great_expectations.__version__` to `great_expectations_version`

 - OS: MacOS
 - GE Version: 0.11.2

**Comment by jcampbell** [comment]
Did you decide to work around this? I think not using '.' in a key makes sense as well.

**Comment by cwerner** [comment]
I had another fix locally, but the change would be nice line the less if it does not break things...
By the way: are the changes in my PR ok? Not sure if I addressed both requests to your liking...

Cheers,
C

**Comment by cwerner** [comment]
I feared this change might inconvenience people and I found a way around it locally, but I’d still suggest changing it.

**Comment by cwerner** [comment]
I added a rather “naive” approach in a PR. There, I simply replaced any occurrence with the new key. Not sure if you’d want to accept old and new versions keys?
