### ISSUE TITLE
No columns description in GE page

### ISSUE THREAD

**Issue by rchojn** [fivetran/great_expectations#1573]
After generating such an expectation suite I can't see column description (latitude, critical).
`{
  "data_asset_type": "Dataset",
  "expectation_suite_name": "about_corona_suite",
  "expectations": [
    {
      "expectation_type": "expect_table_column_count_to_equal",
      "kwargs": {
        "value": 22
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_table_columns_to_match_ordered_list",
      "kwargs": {
        "column_list": [
          "country_info_updated_at",
          "latitude",
          "longitude",
          "name",
          "code",
          "population",
          "critical",
          "death_rate",
          "recovery_rate",
          "recovered_vs_death_ratio",
          "cases_per_million_population",
          "cases_info_updated_at",
          "date",
          "deaths",
          "confirmed",
          "active",
          "recovered",
          "new_confirmed",
          "new_recovered",
          "new_deaths",
          "tech_download_date",
          "tech_granularity"
        ]
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "code"
      },
      "meta": {
        "notes": {
          "format": "markdown",
          "content": [
            "country ISO-3166-1 Alpha2 code"
          ]
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "latitude"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        },
        "meta": {
          "notes": {
            "format": "markdown",
            "content": [
              "country latitude"
            ]
          }
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "longitude"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "name"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "critical"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_to_exist",
      "kwargs": {
        "column": "name"
      },
      "meta": {
        "notes": {
          "format": "markdown",
          "content": [
            "this column contains indoor temp readings - CA, spring and summer"
          ]
        }
      }
    },
    {
      "expectation_type": "expect_column_to_exist",
      "kwargs": {
        "column": "critical"
      },
      "meta": {
        "notes": {
          "format": "markdown",
          "content": [
            "this column contains indoor temp readings - CA, spring and summer"
          ]
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "cases_per_million_population"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "cases_info_updated_at"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "date"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "deaths"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "active"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "recovered"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "new_confirmed"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "new_recovered"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "new_deaths"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_value_lengths_to_be_between",
      "kwargs": {
        "column": "tech_download_date",
        "min_value": 1
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "tech_granularity"
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    },
    {
      "expectation_type": "expect_column_value_lengths_to_be_between",
      "kwargs": {
        "column": "tech_granularity",
        "min_value": 1
      },
      "meta": {
        "BasicSuiteBuilderProfiler": {
          "confidence": "very low"
        }
      }
    }
  ],
  "meta": {
    "BasicSuiteBuilderProfiler": {
      "batch_kwargs": {
        "data_asset_name": "about_corona",
        "datasource": "storage",
        "path": "path",
        "reader_options": {
          "sep": "$"
        }
      },
      "created_at": 1591719730.2517865,
      "created_by": "BasicSuiteBuilderProfiler"
    },
    "citations": [
      {
        "batch_kwargs": {
          "data_asset_name": "about_corona",
          "datasource": "storage",
          "path": "some path",
          "reader_options": {
            "sep": "$"
          }
        },
        "batch_markers": {
          "ge_load_time": "20200609T162209.799817Z",
          "pandas_data_fingerprint": "af79c91a032a79143fd0f967989d6eaa"
        },
        "batch_parameters": null,
        "citation_date": "20200609T162210.405590Z",
        "comment": "BasicSuiteBuilderProfiler added a citation based on the current batch."
      }
    ],
    "columns": {
      "active": {
        "description": ""
      },
      "cases_info_updated_at": {
        "description": ""
      },
      "cases_per_million_population": {
        "description": ""
      },
      "code": {
        "description": ""
      },
      "confirmed": {
        "description": ""
      },
      "country_info_updated_at": {
        "description": ""
      },
      "critical": {
        "description": ""
      },
      "date": {
        "description": ""
      },
      "death_rate": {
        "description": ""
      },
      "deaths": {
        "description": ""
      },
      "latitude": {
        "description": ""
      },
      "longitude": {
        "description": ""
      },
      "name": {
        "description": ""
      },
      "new_confirmed": {
        "description": ""
      },
      "new_deaths": {
        "description": ""
      },
      "new_recovered": {
        "description": ""
      },
      "population": {
        "description": ""
      },
      "recovered": {
        "description": ""
      },
      "recovered_vs_death_ratio": {
        "description": ""
      },
      "recovery_rate": {
        "description": ""
      },
      "tech_download_date": {
        "description": ""
      },
      "tech_granularity": {
        "description": ""
      }
    },
    "great_expectations.__version__": "0.11.1",
    "notes": {
      "content": [
        "_To add additional notes, edit the <code>meta.notes.content</code> field in the appropriate Expectation json file._"
      ],
      "format": "markdown"
    }
  }
}`

**Comment by roblim** [comment]
Hi @rafal0502 - I wasn't able to replicate this issue locally (MacOS Catalina, Chrome, Safari, Firefox, GE 0.11.1). I copied the suite you posted above and built docs using `great_expectations docs build`.

Can you provide a bit more info about your environment, and perhaps your data docs directory or the suite html page? Useful info would be:
- operating system
- GE version
- browser name and version
- how you're generating docs
- any errors/stack traces found in the developer console in the browser when you open the expectation suite page with missing descriptions

Thanks!

<img width="1791" alt="Screenshot 2020-06-11 12 13 17" src="https://user-images.githubusercontent.com/3468435/84429505-1e23b480-abdd-11ea-95cb-84ae1a3c6f9c.png">

**Comment by rchojn** [comment]
Hello, so:
* system: 18.04.4 LTS (Bionic Beaver)
* 0.11.1
* I was using scaffold, then I just changed expectations directly in json. Command for docs:
``` great_expectations doss build```
*  browsers: Chrome and Firefox 
* I am using image for rendering pages: flashspys/nginx-static

**Comment by alexsherstinsky** [comment]
@rafal0502 We found the issue.  The "meta->notes" section should be a sibling of the "meta->BasicSuiteBuilderProfiler".  In our Expectation Suite JSON, the "meta->notes" section is a child of the "meta->BasicSuiteBuilderProfiler" section.  Please see attached the corrected Expectation Suite JSON.  Thank you!
`{
    "data_asset_type": "Dataset",
    "expectation_suite_name": "about_corona_suite",
    "expectations": [
        {
            "expectation_type": "expect_table_column_count_to_equal",
            "kwargs": {
                "value": 22
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_table_columns_to_match_ordered_list",
            "kwargs": {
                "column_list": [
                    "country_info_updated_at",
                    "latitude",
                    "longitude",
                    "name",
                    "code",
                    "population",
                    "critical",
                    "death_rate",
                    "recovery_rate",
                    "recovered_vs_death_ratio",
                    "cases_per_million_population",
                    "cases_info_updated_at",
                    "date",
                    "deaths",
                    "confirmed",
                    "active",
                    "recovered",
                    "new_confirmed",
                    "new_recovered",
                    "new_deaths",
                    "tech_download_date",
                    "tech_granularity"
                ]
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "code"
            },
            "meta": {
                "notes": {
                    "format": "markdown",
                    "content": [
                        "country ISO-3166-1 Alpha2 code"
                    ]
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "latitude"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            },
			"meta": {
				"notes": {
					"format": "markdown",
					"content": [
						"country latitude"
					]
				}
			}
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "longitude"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "name"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "critical"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_to_exist",
            "kwargs": {
                "column": "name"
            },
            "meta": {
                "notes": {
                    "format": "markdown",
                    "content": [
                        "this column contains indoor temp readings - CA, spring and summer"
                    ]
                }
            }
        },
        {
            "expectation_type": "expect_column_to_exist",
            "kwargs": {
                "column": "critical"
            },
            "meta": {
                "notes": {
                    "format": "markdown",
                    "content": [
                        "this column contains indoor temp readings - CA, spring and summer"
                    ]
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "cases_per_million_population"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "cases_info_updated_at"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "date"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "deaths"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "active"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "recovered"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "new_confirmed"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "new_recovered"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "new_deaths"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_value_lengths_to_be_between",
            "kwargs": {
                "column": "tech_download_date",
                "min_value": 1
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_values_to_not_be_null",
            "kwargs": {
                "column": "tech_granularity"
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        },
        {
            "expectation_type": "expect_column_value_lengths_to_be_between",
            "kwargs": {
                "column": "tech_granularity",
                "min_value": 1
            },
            "meta": {
                "BasicSuiteBuilderProfiler": {
                    "confidence": "very low"
                }
            }
        }
    ],
    "meta": {
        "BasicSuiteBuilderProfiler": {
            "batch_kwargs": {
                "data_asset_name": "about_corona",
                "datasource": "storage",
                "path": "path",
                "reader_options": {
                    "sep": "$"
                }
            },
            "created_at": 1591719730.2517865,
            "created_by": "BasicSuiteBuilderProfiler"
        },
        "citations": [
            {
                "batch_kwargs": {
                    "data_asset_name": "about_corona",
                    "datasource": "storage",
                    "path": "some path",
                    "reader_options": {
                        "sep": "$"
                    }
                },
                "batch_markers": {
                    "ge_load_time": "20200609T162209.799817Z",
                    "pandas_data_fingerprint": "af79c91a032a79143fd0f967989d6eaa"
                },
                "batch_parameters": null,
                "citation_date": "20200609T162210.405590Z",
                "comment": "BasicSuiteBuilderProfiler added a citation based on the current batch."
            }
        ],
        "columns": {
            "active": {
                "description": ""
            },
            "cases_info_updated_at": {
                "description": ""
            },
            "cases_per_million_population": {
                "description": ""
            },
            "code": {
                "description": ""
            },
            "confirmed": {
                "description": ""
            },
            "country_info_updated_at": {
                "description": ""
            },
            "critical": {
                "description": ""
            },
            "date": {
                "description": ""
            },
            "death_rate": {
                "description": ""
            },
            "deaths": {
                "description": ""
            },
            "latitude": {
                "description": ""
            },
            "longitude": {
                "description": ""
            },
            "name": {
                "description": ""
            },
            "new_confirmed": {
                "description": ""
            },
            "new_deaths": {
                "description": ""
            },
            "new_recovered": {
                "description": ""
            },
            "population": {
                "description": ""
            },
            "recovered": {
                "description": ""
            },
            "recovered_vs_death_ratio": {
                "description": ""
            },
            "recovery_rate": {
                "description": ""
            },
            "tech_download_date": {
                "description": ""
            },
            "tech_granularity": {
                "description": ""
            }
        },
        "great_expectations.__version__": "0.11.1",
        "notes": {
            "content": [
                "_To add additional notes, edit the <code>meta.notes.content</code> field in the appropriate Expectation json file._"
            ],
            "format": "markdown"
        }
    }
}`

**Comment by rchojn** [comment]
@alexsherstinsky  I've tested it and now it not only does not work, but highlights the error in the code

**Comment by alexsherstinsky** [comment]
@rafal0502 It was a pleasure to troubleshoot the issue with you; glad you are unblocked now!
