### ISSUE TITLE
Suggestion: allow overwriting existing suites OR don't create suites when there's a failure

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#1586]
**Is your feature request related to a problem? Please describe.**
I run into this problem a lot and it really affects usability/iteration speed:
- I run `suite new` and for some reason there's an issue during suite creation, e.g. I mistype the table name, or the table doesn't exist etc
- I then want to try again and create a suite with the same name, but GE tells me the suite already exists
- I have to manually delete the suite, then rerun suite new

**Describe the solution you'd like**
I see 2 possible solutions:
1. Don't create the expectation dir/json if there is a failure in the suite new process or nothing is saved
2. When running suite new with an existing suite name, ask if I want to overwrite the existing suite (default to NO to provide a safety net)

I think option 1 addresses somewhat unexpected behavior (I don't expect a suite to be created if there was an error!) that would be nice to fix anyway, but option 2 would also be a nice feature for other use cases.

**Describe alternatives you've considered**
Run suite delete each time... which is not fun.

**Additional context**
None, I hope this is pretty self explanatory!

**Comment by spbail** [comment]
I'd expect the GE core team to chime in on the design since the current behavior might be intentional and maybe my suggestions are controversial haha - FYI @jcampbell @eugmandel

**Comment by jcampbell** [comment]
Are you encountering this behavior in the CLI, I imagine? There is currently an option to overwite_existing in the underlying API, so I imagine it will be possible to make that available from CLI, if that's what you need.

**Comment by spbail** [comment]
Yes, I encounter this when I run `suite new <existing suite name>` in the CLI. Do we want to allow overwriting via CLI or is there a reason why we wouldn't? If this sounds like a reasonable feature to implement, I'd maybe mark it as "good first issue" since it's just a CLI change!

**Comment by spbail** [comment]
This is starting to become an actual problem when iterating/debugging - I would very much argue that when `suite new` fails with an error, it should *not* create the directory/json (i.e. go with solution 1 I suggested). It's unexpected, not very helpful, and costs time to delete manually each time.
