### ISSUE TITLE
CLI > init > Add Datasource leads to infinite loop when can't be profiled

### ISSUE THREAD

**Issue by troxil** [fivetran/great_expectations#1628]
**Describe the bug**
When using `init` on datasource folder that contains file extensions that aren't within the default 4 (csv, parquet, excel or json) you enter an infinite loop being asked the type and that it can't determine the type.

Example: Using this file: `https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports-extended.dat` you will find it's just CSV. 

**To Reproduce**
The following steps are using windows and `great_expectations==0.11.2` in a venv.

#### Problem Path
1. Create folder `data`
2. Download into that folder: [airports-extended.dat](https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports-extended.dat) as mentioned on [Openflights](https://openflights.org/data.html) (don't rename this file)
2. Activate venv and use `great_expectations init` to setup the datasource of your new downloaded folder containing **dat** file.
3. Instead of being asked to profile, you are guided to enter a file to profile - enter `data\airports-extended.dat`
4. Enter a infinite loop of "We could not determine the format of the file. What is it?" and entering CSV (choice 1).

#### Fixed Path
1. Rename `data\airports-extended.dat` to `data\airports-extended.csv`
2. delete the `great_expectations\` folder
3. Activate venv and use `great_expectations init` to setup the datasource of your new downloaded folder containing **csv** file.
4. Be prompted to profile new expectations for a single data asset - `Y` to proceed
5. Select 1 for a file
5. See `airports-extended (file)`
6. Proceed to successfully profile a new expectation suite + data docs.

**Expected behavior**
1. CSV is the obvious data type, user chose `CSV` during adding data source of the **dat** file this is what should happen. The feature of detecting and profiling should be in sync
2. Offer a way out, as this is an infinite loop asking for input of a file to profile and failing to choose

**Environment (please complete the following information):**
 - OS: Windows
 - GE Version: `0.11.2`

**Additional context**
n/a

**Comment by pspeter** [comment]
I just ran into this same issue when trying to create a new suite:

```
Enter the path of a data file (relative or absolute, s3a:// and gs:// paths are ok too)
: C:/path/to/file.parquet.snappy

We could not determine the format of the file. What is it?
    1. CSV
    2. Parquet
    3. Excel
    4. JSON
: 2

Enter the path of a data file (relative or absolute, s3a:// and gs:// paths are ok too)
[C:/path/to/file.parquet.snappy]: C:/path/to/file.parquet.snappy


We could not determine the format of the file. What is it?
    1. CSV
    2. Parquet
    3. Excel
    4. JSON
: 2
```
..... and so on

OS: Windows 10
GE Version: `0.13.12`

**Comment by pspeter** [comment]
Still an issue

**Comment by pspeter** [comment]
Why was this closed? This problem has not been solved yet!
