### ISSUE TITLE
Make "suite edit" generated Notebooks customizable

### ISSUE THREAD

**Issue by dmateusp** [fivetran/great_expectations#1643]
**Is your feature request related to a problem? Please describe.**
I would like to:
- Inject company-specific notes and documentation links inside the generated notebooks
- Change code generated by `suite edit` in the "footer" specifically, so a specific validation operator and site is used

**Describe the solution you'd like**
I would like to be able to pass configuration and use Markdown / Python files from my plugins package

**Additional context**
Our current footer code generated by "suite edit" is invalid for us, as it tries to build all the sites (including S3 sites we only want to touch explicitly), and we want to overwrite the validation operator used

So if I couldn't customize the generated code, I would have to add some warning for users to change the footer code to use this snippet:
```python
results = context.run_validation_operator("local", assets_to_validate=[batch], run_id=run_id)
validation_result_identifier = results.list_validation_result_identifiers()[0]
context.build_data_docs(site_names=["site_local"])
context.open_data_docs(validation_result_identifier, site_name="site_local")
```

**Comment by Aylr** [comment]
Closing (fixed in #1642 🎉
