### ISSUE TITLE
`docs build` does not ask for confirmation before opening a browser.

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#1647]
**Describe the bug**
When running `great_expectations docs build`, the CLI (appropriately) asks for confirmation before building the site, but does not ask for confirmation before opening the site in a browser.

**To Reproduce**
```
$ great_expectations docs build

The following Data Docs sites will be built:

 - local_site: file:///Users/abe/Desktop/earnestresearch/great_expectations/temptemp/great_expectations/uncommitted/data_docs/local_site/index.html

Would you like to proceed? [Y/n]: 

Building Data Docs...

Done building Data Docs
```

A browser window will open automatically, without asking for confirmation from the user.

**Expected behavior**
As a general rule, the CLI doesn't write to disk or perform similar actions (like opening a browser) without asking for confirmation first. I would have expected the same behavior here.

**Environment (please complete the following information):**
 - OS: MacOS
 - GE Version: 0.11.4

**Comment by Aylr** [comment]
Honestly I find it tiring to have to answer `Y` a bunch when I know what command I ran and just want it to do it's thing so I can get about my work, which involves this command **very often**

**Comment by Aylr** [comment]
Here's a counter proposal:
1. remove the opening behavior from `great_expectations docs build`
2. create a new command `great_expectations docs open`

**Comment by abegong** [comment]
This makes sense to me. It's consistent with the approach of having almost all CLI commands be thin wrappers for atomic actions.

I'd also suggest that:
* `docs build` end with a help message: "If you're on a supported operating system, you can open your docs in a browser with `great_expectations docs open`"
* In `great_expectations init`, we should run both `docs build` and `docs open`, with a confirmation step for each.
