### ISSUE TITLE
Nice to have: Allow treating empty strings as NULL in expect_column_values_to_not_be_null

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#1655]
**Is your feature request related to a problem? Please describe.**
We've run into a few situations where text fields can have both NULLs and empty strings, which we want to test. In this case, we consider NULL and empty strings to be the same value, but it requires us to add two separate expectations (not be null and not in set), which is just more effort.

**Describe the solution you'd like**
It would be nice to add in a flag, e.g. like `expect_column_values_to_not_be_null(person_id, treat_empty_string_as_null=True) to implement this behavior out of the box for text type columns. The flag could default to False to preserve the existing behavior.

**Describe alternatives you've considered**
This can be done with an additional expectation, but it would be nice to have a shortcut.

**Comment by Aylr** [comment]
This is related to, or a duplicate of #1535

**Comment by spbail** [comment]
Good call, thanks @Aylr ! I'll close this one!
