### ISSUE TITLE
Nice to have: better error message when S3 connection fails

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#1656]
**Is your feature request related to a problem? Please describe.**

Setup: GE context configured with a postgres database as datasource, and S3 as validation store.

I ran into an issue where `suite new` failed with a boto error: `botocore.exceptions.NoCredentialsError: Unable to locate credentials` after connecting to a datasource and selecting a data asset (i.e. IIRC at the step where it says "we're now going to profile some expectations")

This was pretty confusing since I was just trying to create an expectation suite and the DB connection to my datasource worked just fine. It took a while to realize that this was happening when `suite new` was running validation on profiled expectations as a final step before rendering data docs, and my S3 credentials weren't set up correctly to store the validation results in an S3 store. 

It would be nice to have a more meaningful error message there, since it's always a little unclear that validation is run as part of suite new.

This becomes clearer when running `run_validation_operator` in a notebook when S3 credentials are missing. I assume this also happens when trying to store expectations in S3 and there are issues with credentials.

**Describe the solution you'd like**
Maybe just have a clearer error message that says something like "storing validations failed because store connection failed, make sure you have the right credentials set up", and the same for storing expectations. It currently just bubbles up to the standard boto error.

**Additional context**
Note, the confusion here comes in part from the fact that the S3 error happened during `suite new` which runs and stores validations behind the scenes, which is somewhat unexpected. This doesn't happen during `suite new --empty`. I know this is going to be the future behavior of `suite new`, but I think clear error messages to indicate what failed would be nice regardless.

**Comment by psychuil** [comment]
Hey there, I started taking a look at the issue, saw that run_validation_operator run fine in a notebook (the one where I can edit my suite)
Can you provide steps to reproduce? 

Also, where are your validations stored?

**Comment by spbail** [comment]
@psychuil Hey thanks for picking this up! I *hopefully* clarified my description, I realized it was a little confusing.

Steps to reproduce: 
- configure an S3 validation store in your great_expectations.yml
- **don't** set up your S3 credentials correctly (I was working on a project that someone else had configured, so didn't see that the validation store in great_expectations.yml was S3)
- run either `suite new` and go through to the last step, or run `run_validation_operator` in a notebook on a batch. At the step where GE tries to store the validations in S3 it'll fail due to the missing creds. It currently just throws the standard boto3 error, would be nice to be more specific.

As I described above, this was mainly confusing during the `suite new` workflow, as it's not completely transparent that it runs validation and tries to store the results. I was basically like "huh I can connect to the SQLAlchemy datasource just fine, why is it failing with an S3 error?"

**Comment by alfredo-f** [comment]
Hello @spbail , can you please check whether the user experience is still the same, and provide related screenshots?

Please remove any PII or sensitive information 😄

**Comment by austiezr** [comment]
Hey @spbail @alfredo-f @psychuil thanks for surfacing this and your further discussion; we believe this to be a V2 issue that may now be resolved, so we're going to close this out for now. Feel free to re-open if you feel this is still an issue.
