### ISSUE TITLE
Failed to save multiple Column Pair expectations 

### ISSUE THREAD

**Issue by khotkevych** [fivetran/great_expectations#1657]
**Describe the bug**
Not possible to save more than 1 Column Pair expectation of the same expectation type. 

**To Reproduce**
1. Create an expectation suit for data source that supports Column Pair expectations (f.e. Pandas)
2. Add 2 Column Pair expectations with the same expectation type, but different columns values, f.e.
`batch.expect_column_pair_values_to_be_equal(column_A="Provider First Name", column_B="Provider Name Prefix Text")`
`batch.expect_column_pair_values_to_be_equal(column_A="Provider Last Name (Legal Name)", column_B="Provider Name Prefix Text")`
and run them.
3. Save the expectation suit
`batch.save_expectation_suite(discard_failed_expectations=False)`
4. Check generated json file with expectations and see 1 Column Pair expectation instead of 2.

**Expected behavior**
2 Column Pair expectations saved. 

**Environment**
 - OS: macOS Mojave 10.14.6
 - GE Version: 0.11.6

**Additional context**
As far as I get from code [here](https://github.com/great-expectations/great_expectations/blob/0.11.6/great_expectations/data_asset/data_asset.py#L411), it's possible to have multiple expectations of the same type only if `column`  field is provided. In the case of Column Pair expectations, there is no `column` field, but there are `column_A` and `column_B`. 
Also, this will be an issue for any custom expectation without the `column` field.

**Comment by Shinnnyshinshin** [comment]
Thank you for submitting this issue @khotkevych and sorry that it's taken so long to get back to you. This issue will likely be resolved in PR #1217 . Please feel free to comment or follow the PR if you'd like
