### ISSUE TITLE
suite new throws this error when TupleS3StoreBackend store backend is used for the expectations store: "TypeError: _set() got an unexpected keyword argument 'allow_update'"

### ISSUE THREAD

**Issue by eugmandel** [fivetran/great_expectations#1681]
**Describe the bug**
suite new throws this error when TupleS3StoreBackend store backend is used for the expectations store: "TypeError: _set() got an unexpected keyword argument 'allow_update'"

**To Reproduce**
1. Switch the expectations store in your Data Context to use TupleS3StoreBackend
2. Run suite new in the CLI
3. See error: "TypeError: _set() got an unexpected keyword argument 'allow_update'"

**Expected behavior**
No error

**Environment (please complete the following information):**
 - OS: any
 - GE Version: 0.11.7

**Additional context**

**Comment by Shinnnyshinshin** [comment]
closed by #1683
