### ISSUE TITLE
CLI flag to say yes to prompt

### ISSUE THREAD

**Issue by hamelsmu** [fivetran/great_expectations#1690]
I'm working with @Aylr on https://github.com/superconductive/great_expectations_action

We want to generate data profiles with the CLI 

The command

> great_expectations datasource profile

Asks us for yes/no interactively.  Because I want to run this in CI automatically, it would be useful to have a `-y` flag or something like that to allow me to skip the prompt. 

Thank you for the cool project ❤️

**Comment by thcidale0808** [comment]
Hello, I've been looking into this one and looks very simple. Can I pick up this?

**Comment by jcampbell** [comment]
@thcidale0808 -- yes, we'd love to have you build this PR!

**Comment by geokats7** [comment]
Hi guys! Is this issue still open?

**Comment by talagluck** [comment]
It looks like this was closed in #1881

Thanks, everyone!
