### ISSUE TITLE
When a Data Docs site is configured to be hosted on an S3 bucket (without an extra prefix), the URL is not accessible unless an extra slash is added before "index.html"

### ISSUE THREAD

**Issue by eugmandel** [fivetran/great_expectations#1693]
**Describe the bug**

**To Reproduce**
1. Create a Data Context
2. Follow the https://docs.greatexpectations.io/en/latest/how_to_guides/configuring_data_docs/how_to_host_and_share_data_docs_on_s3.html guide to configure a Data Docs site to be hosted on an S3 bucket. NOTE: DO NOT SPECIFY A PREFIX!
3. Run the CLI command `great_expectations docs build` to build Data Docs 
4. Attempt loading the newly built site in the browser - use the URL that the previous command outputted. - Verify that instead of seeing the page, you get an "AccessDenied" error.
5. Add an extra "/" before "/index.html" in the URL - verify that the site loads in the browser.

**Expected behavior**
The Data Docs site is accessible in the browser on the URL outputted by the `great_expectations docs build`  CLI command.

**Environment (please complete the following information):**
 - OS: OSX
 - GE Version: 0.11.7

**Additional context**

**Comment by jcampbell** [comment]
@eugmandel  -> can you confirm this is now fixed and close?
