### ISSUE TITLE
CLI option to specify port for launching Jupyter Notebook (in suite CLI)

### ISSUE THREAD

**Issue by ccecora** [fivetran/great_expectations#1708]
**Context**
Having to manage dependency issues has led my team to experimenting with great_expectations from inside a docker image.  Using suite commands with `--jupyter` will generate a Jupyter notebook in your localhost, which isn't necessarily the default IP address used by the Docker container, so we cannot use the suite CLI when great_expectations is run inside a docker container.  

To expose a port from inside a container to your a local machine, you need to specify [`host.docker.internal`](https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds) as one's port.

**The solution**
Allow for a `-p` or `--port` option for the cli:
```
great_expectations suite edit -p host.docker.internal

great_expectations suite demo -p localhost:4040

great_expectations suite scaffold -p 9999

great_expectations suite new --port localhost:8888
```

**Comment by Aylr** [comment]
Great points! - We do have an undocumented feature that _might_ unblock you: if you set an environment variable named `GE_JUPYTER_CMD` to something like `jupyter notebook --port=9999` that will be used anytime GE invokes `jupyter`.

**Comment by ccecora** [comment]
@Aylr that is a pretty good substitution, will try this out for myself.
