### ISSUE TITLE
Snowflake: provide the option to use temporary tables instead of transient tables

### ISSUE THREAD

**Issue by verhey** [fivetran/great_expectations#1747]
## Why

```python
batch_kwargs = {
    ...
    'snowflake_transient_table': 'my_transient_table'
}
```

GE creates transient tables when running expectation suites via the `snowflake_transient_table` argument in `batch_kwargs`. While transient tables are fine, they are not automatically dropped after session end, meaning developers may choose to add an extra step to their pipeline to drop those GE-generated tables, or just isolate them to another schema. This isn't particularly difficult, but seems unnecessary, as Snowflake does support more traditional temporary tables that I see are created in other SQLalchemy engine dialects and I don't see GE creating more than one session that would require the use of transient tables instead. 

## Proposed Solution

[Snowflake does support more "traditional" temporary tables](https://docs.snowflake.com/en/user-guide/tables-temp-transient.html#comparison-of-table-types) that automatically drop at the end of a session. While I understand users may be utilizing (or prefer) the existing transient table implementation, it seems worthwhile to give them a choice to utilize temporary tables as well. 

![image](https://user-images.githubusercontent.com/22968861/88987369-91b37b00-d28a-11ea-8e00-c032c0034485.png)

I'd initially recommend an additional `batch_kwargs` keyword `snowflake_temporary_table` to exist alongside the existing `snowflake_transient_table` (and thus be non-breaking for anyone who would like to continue to use transient tables) but I'm very open to ideas here as I'm not particularly familiar with the codebase. 

I definitely wouldn't want to suddenly change the behavior of `batch_kwargs.snowflake_transient_table` or replace it entirely, as other users may prefer the transient table workflow. 

## Notes 

I wouldn't have opened this if I didn't see GE using traditional temp tables for other SQL dialects or saw more than one session being initiated by GE. It seems like a clear decision to use transient tables for Snowflake and temp tables for other SQL dialects, so I may be missing some historical context here. 

https://github.com/great-expectations/great_expectations/blob/873e304b718cb9ba08d3b17386aed5eb45674913/great_expectations/dataset/sqlalchemy_dataset.py#L1179-L1206

**Comment by roblim** [comment]
I believe @alexsherstinsky was working with Snowflake support recently. @alexsherstinsky - do you have any feedback on this issue? Thanks!

**Comment by alexsherstinsky** [comment]
Hi @verhey !!!  Thank you for your observation.  From my perspective, it traditional temporary tables can work for Snowflake, then we should use them, rather than the transient tables.  The reason is that the purpose of these tables is to store intermediate information for the given session, after which these tables are not needed anymore, and if we could leverage the underlying DB/Platform to reap them, that is advantageous to the user/administrator having to do so as part of additional work.  Hence, I would love to see a PR that changes the Snowflake part of the SQLAlchemy Dataset to use temporary tables.  I would also like to solicit the input from @jcampbell before we call this decision as a "final" one.  Thank you. /cc @eugmandel

**Comment by jcampbell** [comment]
I'd love this change! We converted snowflake to use transient tables because of a problem with finding temporary tables--however, the decision was based on a user's reported experience (we had not independently done significant testing), which I later came to believe may have been related to some now-fixed handling of quoting table names in snowflake.

net/net --> strongly support this proposal.

**Comment by alexsherstinsky** [comment]
@verhey It would be ideal if you could make a quick PR of your anticipated fix.  If that is all right with you, when might we expected to receive it?  I will be happy to review it, so please feel free to tag me for that.  Thank you very much.

**Comment by verhey** [comment]
Thanks for the comments @alexsherstinsky and @jcampbell 

I'll look into throwing a PR together over the next couple weeks or so. Hard to give you too much of an ETA since I'm not super familiar with the codebase yet and this would be my first contribution. 

Any opinions from either of you on modifying the behavior of the existing `snowflake_transient_table` kwarg vs. introducing a new optional `snowflake_temporary_table` option (or similar)? 

I know my team would prefer the temporary table implementation, and think it'd be more consistent with the rest of the SQLalchemy datasources implemented, but I'm hesitant to introduce anything potentially breaking for other Snowflake GE users. I do see the utility of the transient table option (as did [another user in slack](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1596554866041200)) as well - I just don't think it should be the only or default option. 

Let me know your thoughts and appreciate all the feedback.

**Comment by alexsherstinsky** [comment]
Hi @verhey : Since another user found transient tables to be useful, perhaps it is safer to introduce the temporary tables as a separate option?  Any thoughts and design proposals when you have time are welcome.  Thank you!

**Comment by verhey** [comment]
Looks like someone may have got to this in #2031 

Apologies I never got around to a PR, but let me know if you'd like some help updating the docs or testing the fix.

**Comment by eugmandel** [comment]
PR https://github.com/great-expectations/great_expectations/pull/2031 addressed this issue and was released in https://github.com/great-expectations/great_expectations/releases/tag/0.12.8
