### ISSUE TITLE
Data Docs expect_table_row_count_to_be_between is unclear

### ISSUE THREAD

**Issue by roselightheart** [fivetran/great_expectations#1750]
**Describe the bug**
Data docs for expect_table_row_count_to_be_between say "Must have more than X rows", but the min_value is inclusive. "more than" is slightly ambiguous and doesn't clearly indicate if the inequality is inclusive or not.

**To Reproduce**
1. run expect_table_row_count_to_be_between with only a min_value

**Expected behavior**
It should say "Must have at least X rows."

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - GE Version: 0.11.9

**Additional context**

**Comment by anthonyburdi** [comment]
@rexboyce does the referenced PR (#1837) fully address this issue?
