### ISSUE TITLE
Evaluation Parameters support in Checkpoint

### ISSUE THREAD

**Issue by dmateusp** [fivetran/great_expectations#1794]
**Is your feature request related to a problem? Please describe.**
The `checkpoint` feature does not support evaluation parameters

**Describe the solution you'd like**
I would like the ability to pass evaluation parameters either through the CLI or in the `checkpoint` YAML file

**Additional context**
In my experience the usability of the checkpoint file is limited because of its lack of template-ability, and we end up generating the checkpoint YAML files from scratch on each run dynamically in Airflow (using the parameters passed to the Operator).
Short term if we could have a way to use evaluation parameters with checkpoint even through the YAML file it would be great, longer term I think there's a larger discussion that needs to happen around how `checkpoint` gets its arguments / inputs

**Comment by ed-turner** [comment]
I second this notion and need.  I am currently using great_expectations within Airflow, and we have the need to template time stamps
