### ISSUE TITLE
DataContext, BaseDataContext, DataContextConfig, and get_checkpoint()

### ISSUE THREAD

**Issue by williamBartos** [fivetran/great_expectations#1795]
The [documentation](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_data_contexts/how_to_instantiate_a_data_context_on_an_emr_spark_cluster.html) outlines a way to dynamically generate a data context. I'm planning on running this from the script created from the `checkpoint script` cli call. 

However there's a few issues:

1. `DataContextConfig` can only be used to instantiate `BaseDataContext` and not `DataContext`. The `DataContextConfig` is passed in via the `project_config` arg. 
2. `BaseDataContext` doesnt have a `get_checkpoint()` method. So I can't use it in place of `DataContext`. 

`__init__` of BaseDataContext: https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/data_context/data_context.py#L224
`__init__` of DataContext: https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/data_context/data_context.py#L2245

If I'm understanding correctly, this means that I'm unable to create a `DataContextConfig` dynamically and use it in a Checkpoint. This is because `DataContext` seems to only accept a yaml file as a config and not a `DataContextConfig`. 

**Describe the solution you'd like**

`DataContext` should be able to be instantiated with a `DataContextConfig`, either through  a `project_config` arg like `BaseDataContext` or through some other method.

**Comment by eugmandel** [comment]
Replied on this in https://discuss.greatexpectations.io/t/datacontext-basedatacontext-datacontextconfig-and-get-checkpoint/315/2 - since the workaround exists, closing the issue.
