### ISSUE TITLE
[FEATURE] Add small text describing variables to Data Docs

### ISSUE THREAD

**Issue by lbittarello** [fivetran/great_expectations#1799]
### Context

We use GEs and their Data Docs to keep an up-to-date documentation of the data produced by our data pull before we use them in modelling. As part of the data pull, we have prepared docstrings with a description of each variable after the pull, which look something like this:

```python
def compute_age_in_days(birthday, today):
    """Compute age in days.
    Returns
    -------
    age:
        Age in days. Computed via `birthday` and `today`. Should never be
        smaller than zero.
    """
    return (today - birthday).dt.days
```

We then collect these docstrings in a dictionary
```
{"age": "Age in days. Computed via `birthday` and `today`. Should never be smaller than zero."}
```
and create a document (seperate from the data docs, basically sphinx) with descriptions for each variable.

### Describe the solution you'd like

It would be nice if we could join these two data related documents into one, by adding the docstrings (which we have already gathered as `variable: string` pairs) to the Data Docs.

Could someone with a better understanding of the `ValidationResultsPageRenderer` and `Jinja` comment on the feasibility of this?

### Describe alternatives you've considered

We have tried adding a `expect_column_to_exist` with 
```
meta={
    "notes": {
        "format": "markdown",
        "content": [docstring]
    }
}
```
to the list of expectations. However these will not be rendered due to #1331 (bug).

**Comment by lbittarello** [comment]
Related: #1331

**Comment by mlondschien** [comment]
Also related: #1840.

**Comment by quinten-goens** [comment]
This would indeed be a very welcome feature as it would allow to simultaneous check data quality and describe your variables. People reading the data docs validation sheet would thus immediately understand the current state of the data quality.
