### ISSUE TITLE
Enable Partially configured/Ephemeral data contexts

### ISSUE THREAD

**Issue by FishmanL** [fivetran/great_expectations#1801]
I'd like to build support for programmatic expectation validation and programmatic context generation, where the generated contexts are going to be used to validate in memory dataframes, with pickled/in memory expectation suites, and the results are only going to be in memory.  Right now, I still need to provide full config (including stores for a whole bunch of things I want to stay in memory), and that means creating configs with a lot of dummy values (e.g. routing things to tempfiles or dev/null)

**Describe the solution you'd like**
I'd like two things:  1) for there to be methods for creating DataContexts with most of the parameters/boilerplate set to defaults, and 2) for DataContexts to support ephemerality/in-memoryness.

**Describe alternatives you've considered**
For the defaults issue, I'm currently planning to build 98% of the config as a dict and parameterize the few things I care about changing.  For ephemerality I can just route all the stores to dev/null, but that's ugly.

**Comment by spbail** [comment]
FYI @alexsherstinsky is this something that will be solved with the data context work you're doing?
