### ISSUE TITLE
Minor enhancement: Make data asset name more visible in Data Docs

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#1804]
**Is your feature request related to a problem? Please describe.**
Currently, the data asset name on the Data Docs validation results page is tucked away behind the "Show more info" link, which makes it difficult to see what the validation results are for.

**Describe the solution you'd like**
I would like the data asset name to show up in the grey header bar at the top of the validation results page as shown in the attached mockup, rather than in the "Show more info" section.

**Describe alternatives you've considered**
None.

![Screen Shot 2020-07-23 at 11 49 58 AM](https://user-images.githubusercontent.com/1734474/90263271-74031b80-de1d-11ea-842d-8532231f07ed.png)

**Comment by haydarai** [comment]
The issue looks related to https://github.com/great-expectations/great_expectations/issues/1805. If it's okay for me to take the first one, can I also take this one?

**Comment by spbail** [comment]
@haydarai It's somewhat related, but in this case, the data asset name is already in the docs, it's just a little further down the page (hidden behind "Show more info"). So this fix should be super easy.

See https://docs.greatexpectations.io/en/latest/contributing.html for step-by-step guidance on contributions. As I mentioned on the other issue, make sure the tests still pass since we have tests on a lot of outputs.

Thank you!
