### ISSUE TITLE
Minor enhancement: Show data asset name in Slack message

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#1805]
**Is your feature request related to a problem? Please describe.**
Currently, the Slack notifications sent by GE don't show the data asset name for validation results, which makes it hard to tell what has been validated. See the attached screenshot for the current state.

**Describe the solution you'd like**
 It would be nice to be able to see both the expectation suite + data asset name in the message, to make it clearer what has been validated.

**Describe alternatives you've considered**
None.

![Screen Shot 2020-07-23 at 11 46 25 AM](https://user-images.githubusercontent.com/1734474/90263680-fc81bc00-de1d-11ea-9121-151be2663874.png)

**Comment by haydarai** [comment]
This looks fairly simple, can I try to work on this?

**Comment by spbail** [comment]
@haydarai Absolutely, that would be great. If you haven't seen them yet, here are our step-by-step instructions for contributions: https://docs.greatexpectations.io/en/latest/contributing.html

One thing to flag is tests, we probably have pytests on all our outputs (like CLI, Slack messages, etc), so you'll want to run the test suites before submitting. Looking forward to seeing the result!
