### ISSUE TITLE
[Enhancement] Implement "checkpoint delete" CLI command

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#1806]
**Is your feature request related to a problem? Please describe.**
Right now there is no CLI command to delete checkpoints, like there is with suites, for example. This means I have to manually delete the checkpoints.

**Describe the solution you'd like**
I would like to be able to run `great_expectations checkpoint delete <checkpoint name>` and delete all traces of the checkpoint.

**Describe alternatives you've considered**
Do it manually.

**Comment by haydarai** [comment]
@spbail can I give this a shot?

**Comment by spbail** [comment]
Hi @haydarai! Sure this would be great! Keep in mind that any CLI changes need new tests, but you can probably follow the patterns of the existing CLI tests pretty well :)

**Comment by spbail** [comment]
Also @haydarai feel free to assign this issue to yourself so it's clear it's being worked on! Thank you!

**Comment by haydarai** [comment]
@spbail I don't think I have the permission to assign myself to this issue

**Comment by alfredo-f** [comment]
`checkpoint delete` is implemented in [checkpoint.py](https://github.com/great-expectations/great_expectations/blob/b83fc816474af1dd60521104b89a64970823022b/great_expectations/cli/checkpoint.py#L189) 

Can we close this issue? @anthonyburdi

**Comment by anthonyburdi** [comment]
This has been implemented in the CLI, thanks for the heads up on this issue @alfredo-f!
