### ISSUE TITLE
[FEATURE] Enable hive support in spark

### ISSUE THREAD

**Issue by Dandandan** [fivetran/great_expectations#1810]
**Is your feature request related to a problem? Please describe.**
The spark engine context doesn't support hive, which is enabled by  `enableHiveSupport()` on the builder.

**Describe the solution you'd like**
An option to enable hive support and call `enableHiveSupport()`

**Comment by gumartinm** [comment]
Shouln't be this configuration enough?

`spark.sql.catalogImplementation     hive `
`spark.sql.warehouse.dir             /tmp/hive`
`spark.hadoop.hive.metastore.uris    thrift://localhost:9083`

See: https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_datasources/how_to_configure_a_self_managed_spark_datasource.html


`enableHiveSupport()` just sets this Spark configuration: `spark.sql.catalogImplementation  hive`

**Comment by Dandandan** [comment]
Thanks @gumartinm that worked indeed, we are using this now :)
