### ISSUE TITLE
Data Docs: add comments/notes to the validation results pages

### ISSUE THREAD

**Issue by eugmandel** [fivetran/great_expectations#1840]
Adding comments to expectations and having them rendered in Data Docs (as described in this [how-to guide](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_data_docs/how_to_add_comments_to_expectations_and_display_them_in_data_docs.html)) is very useful.

Currently Data Docs displays these comments only on the Expectation Suite pages, but on Validation Results ones. This is a request to implement this missing functionality.

**Comment by deeprout** [comment]
What does the description in the meta :-> columns represent? I am not talking about expectation level metadata.
