### ISSUE TITLE
Context.build_data_docs() generating TypeErrors for old validation results

### ISSUE THREAD

**Issue by ccecora** [fivetran/great_expectations#1841]
**Describe the bug**
Running `context.build_data_docs()` in the auto-generated Jupyter Notebook for `suite edit` repeatedly generates the following error several times before generating the HTML for the expectation suite edited in the notebook:

`Message: 'An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:\n            TypeError: "unhashable type: \'dict\'".  Traceback: "Traceback (most recent call last):\n  File "/Users/chasec/.local/share/virtualenvs/great_expectations-9QQSxJXa/lib/python3.7/site-packages/great_expectations/render/renderer/content_block/validation_results_table_content_block.py", line 474, in row_generator_fn\n    unexpected_table = cls._get_unexpected_table(evr)\n  File "/Users/chasec/.local/share/virtualenvs/great_expectations-9QQSxJXa/lib/python3.7/site-packages/great_expectations/render/renderer/content_block/validation_results_table_content_block.py", line 164, in _get_unexpected_table\n    if string_unexpected_value not in sampled_values_set:\nTypeError: unhashable type: \'dict\'\n".'
Arguments: (TypeError("unhashable type: 'dict'"),)`

@eugmandel suspects it could be the result of old validation results from a prior version of GE trying to be generated into data_docs.  This would make sense, as running build_data_docs once keeps generating this error repeatedly, at least 5-10 times until my expectation suite I was testing in the notebook gets generated into HTML.

**To Reproduce**
1. `pipenv run great_expectations suite edit suite_name`
3. Enter s3 file path in batch_kwargs contained in first cell of the Notebook
4. Run all expectations
5. With validations created by old GE version in project directory, run final cell and build data docs

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Pipenv environment (Python 3.7)
     **Requirements:**
    - boto3 = "==1.14.40"
    - great-expectations = "==0.12.0"
    - SQLAlchemy = "==1.3.18" 
 - GE Version: 0.12.0

**Comment by eugmandel** [comment]
@ccecora Thank you for writing up the steps to reproduce! My colleague @roblim is looking into this issue. We will post a comment here once we know more.
