### ISSUE TITLE
Broken links/images throughout "Getting Started" docs

### ISSUE THREAD

**Issue by charleswm** [fivetran/great_expectations#1842]
**Describe the bug**
There are missing images throughout the getting started guide. Seems like there might be a bad reference somewhere that's effecting several docs pages

## Quickstart guide
The [quickstart-guide](https://docs.greatexpectations.io/en/latest/guides/tutorials/quick_start.html) in the docs is missing the following items:

- The link to the expecations notebook
- the gif

![image](https://user-images.githubusercontent.com/11549389/91179485-8d755480-e6b4-11ea-9efc-9e2b745750b7.png)

## Connect to Data
Also found missing images in the [Connect to Data docs page](https://docs.greatexpectations.io/en/latest/guides/tutorials/getting_started/connect_to_data.html)

![image](https://user-images.githubusercontent.com/11549389/91182577-5608a700-e6b8-11ea-92f0-020f1a7a9f87.png)

## Set up Data Docs

[Set up Data docs](https://docs.greatexpectations.io/en/latest/guides/tutorials/getting_started/set_up_data_docs.html) is missing a few images as well.
![image](https://user-images.githubusercontent.com/11549389/91184793-08416e00-e6bb-11ea-8676-5de30ff7b220.png)

**Comment by eugmandel** [comment]
@charleswm Thank you for reporting this!

**Comment by spbail** [comment]
Will fix!

**Comment by spbail** [comment]
The PRs should address this issue, thanks again for reporting!
