### ISSUE TITLE
Great Expectations Airflow operator for validation

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#1848]
**Is your feature request related to a problem? Please describe.**
There are examples to run validation/checkpoints in Airflow using a Python or Bash operator, but it would be nice to have a GE Airflow operator for convenience to easily run validations.

**Describe the solution you'd like**
For example, the operator could be called passing in the expectation suite name and batch kwargs perhaps

**Describe alternatives you've considered**
Implement the validation in a PythonOperator

**Additional context**
For reference, this is what we currently do with a PythonOperator:

validation = PythonOperator(
    task_id='validation_task',
    python_callable=validation_method,
    op_kwargs={
        'data_asset_name': 'demo__dir/default/npidata_pfile',
        'expectation_suite_name': 'warning',
        'batch_kwargs': BatchKwargs(
            path='/data/demo/npidata_pfile/npidata_pfile_20050523-20191001_1.csv'
        )
    },
    dag=dag,
)

**Comment by spbail** [comment]
@eugmandel This is the request I mentioned that came out of a user interview!

**Comment by bouke-nederstigt** [comment]
At TAPP we built a validation operator. I'll see if I can commit this some time this week.

**Comment by HugoManoMano** [comment]
:wave: Our own implementation of Airflow Operator for validation also has following parameters :
- The location of the great_expectations.yml, for multiple configuration management
- The validation operator to use, as defined in the .yml used for the context
- The run id that is automatically prefixed by "airflow", and that could use the dag / task ids with the schedule time

**Comment by NickBenthem** [comment]
I'm happy to work on this - we use a custom version with Great Expectations - and I have some time this week to work on it. 

Let me see if I can get a draft PR together.

**Comment by spbail** [comment]
Amazing, thanks @NickBenthem @HugoManoMano @bouke-nederstigt - thanks so much for offering to help out! I'd actually love to see the different implementations if you don't mind submitting draft PRs (don't sweat it though). We'll probably review and see which one is closest to finished. We might also shift this to actually live in the Airflow repo - tbd!

**Comment by dmateusp** [comment]
we created a GreatExpectationsCheckpoint operator based on the KubernetesPodOperator, I'm currently working on making it open source

**Comment by spbail** [comment]
Hi all! We've gotten together with the folks from Astronomer and implemented a first version of a GE Airflow operator: https://github.com/great-expectations/airflow-provider-great-expectations
You should be able to import it into your DAG as shown in the example code. This is an early release and I'm happy to take feedback and make tweaks to it. @bouke-nederstigt @HugoManoMano @NickBenthem - feel free to try it out and open issues in the repo!

**Comment by spbail** [comment]
I'm actually going to close this issue since there's an operator available now.
