### ISSUE TITLE
Typo in CLI output for great_expectations validation-operator run error

### ISSUE THREAD

**Issue by colmsnowplow** [fivetran/great_expectations#1857]
**Describe the bug**
`great_expectations validation-operator run` outputs a typo in the suggested command when no suite is specified.

**To Reproduce**
run `great_expectations validation-operator run`:

```
$ great_expectations validation-operator run
In the next major release this command will be deprecated.
Please consider using either:
  - `checkpoint new` if you wish to configure a new checkpoint interactively
  - `checkpoint run` if you wish to run a saved checkpoint

Please use --suite argument to specify the name of the expectation suite.
Call `great_expectation suite list` command to list the expectation suites in your project.
```

**Expected behavior**
`great_expectation suite list` should read `great_expectations suite list`

**Environment (please complete the following information):**
 - OS: MacOS
 - GE Version: 0.12.0

**Additional context**
No biggie, just an FYI :)

**Comment by eugmandel** [comment]
Thank you for reporting this, @colmsnowplow ! The fix will be in the next release.
