### ISSUE TITLE
Credentials are written to config_variables.yml even if datasource creation is aborted

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#1859]
**Describe the bug**
This is basically one of the issues I called out in #1855:
When I run `datasource new` and exit the process at any point (e.g. ctrl+c), I still get a block for the credentials in config_variables.yml. *However* great_expectations.yml doesn't have the datasource entry. I would expect any kind of failure in the datasource creation process to not leave any artifacts.

**To Reproduce**

- run `great_expectations datasource new`
- pick a SQLalchemy datasource (not tested with file datasources, but might be the same)
- just hit enter on any of the inputs
- ctrl+c to exit the process, or exit when prompted to re-enter the incorrect creds
- open uncomitted/config_variables.yml - it will have an entry for the datasource creds, which is unexpected behavior
- open great_expectations.yml - it won't have an entry for the datasource (which is expected behavior)

**Expected behavior**
I would expect any failure in the CLI workflows to not leave artifacts. **This is similar to another issues I've filed** where `suite new` also leaves a suite JSON even if the creation process fails/is canceled. I would expect GE to be better at cleanup/not leave artifacts if the CLI workflow fails at any point.

**Environment (please complete the following information):**
 - OS: mac OS
 - GE Version: 0.12.0

**Comment by felipebormann** [comment]
Can I tackle this problem? Or is it addressed somewhere else already?

**Comment by spbail** [comment]
Hi @felipebormann I'd try and reproduce the issue first, but I'm pretty sure this hasn't been fixed yet. You're more than welcome to tackle this!

**Comment by alfredo-f** [comment]
Now, when creating a new datasource, the Jupyter notebook that opens up reads

> **Credentials will not be saved until you run the last cell.** The credentials will be saved in `uncommitted/config_variables.yml` which should not be added to source control.

@anthonyburdi Has this issue been solved?

**Comment by talagluck** [comment]
Hi! I believe this issue is closed.
