### ISSUE TITLE
Importing Great Expectations captures warnings

### ISSUE THREAD

**Issue by stephen-hoover** [fivetran/great_expectations#1861]
**Describe the bug**

Importing Great Expectations alters a global logging setting which redirects emits produced by the `warnings` module to the logger. This globally hides warnings unless the user also attaches a log handler which makes "WARNING" emits from the "py.warnings" logger visible.

**To Reproduce**

```python
import warnings
warnings.warn("This is a warning", RuntimeWarning)
# A warning emit appears here

import great_expectations as ge
warnings.warn("This is another warning", RuntimeWarning)
# No screen output

import logging
logging.basicConfig(level="WARNING")
warnings.warn("I'm logging this warning", RuntimeWarning)
# The message appears on the screen, but as a WARNING level log emit from the py.warnings logger.
```

**Expected behavior**

I expect that importing a library will not change warning or logging behavior in the caller application.

**Environment (please complete the following information):**
 - OS: OSX
 - GE Version: First observed in v0.8.5, but this is also present in v0.12.0.
 - Python Version: 3.7.6

**Additional context**

My team has a data processing library which imports Great Expectations to run data validation on pandas `DataFrame` objects in memory. We also have a series of convenience functions for use cleaning data in Jupyter notebooks. Some of those interactive data cleaning functions make use of the `warnings` module to alert users to potential problems with their data. A recent code change led the interactive data cleaning module to import a common utility module which also imported GE, and we noticed that the warning emits became hidden.

This appears to be the line of code which redirects warnings to the logger: https://github.com/great-expectations/great_expectations/blob/f5abb426d3837c587846d91157c9a663d6698c4d/great_expectations/data_asset/data_asset.py#L34 It runs every time a user import Great Expectations.

As a separate potential issue related to `warnings` module behavior, I also noticed this line, which will globally silence warnings when the module is imported: https://github.com/great-expectations/great_expectations/blob/f5abb426d3837c587846d91157c9a663d6698c4d/great_expectations/cli/cli_logging.py#L4 The module name implies that it would only be imported as part of the CLI, but it might make sense to move that filter to the `if __name__ == "__main__":` block of `cli/cli.py`.

**Comment by eugmandel** [comment]
@stephen-hoover Thank you for filing this with detailed steps to reproduce. Confirmed - this is a bug.

**Comment by elsander** [comment]
👋 I'm back for Hacktoberfest! I'll have some hack time to pick up tickets next week. Happy to take a look at this one.

**Comment by elsander** [comment]
I could replicate this issue on `master`, but not `develop`. Has a fix been merged, but not released? If so, should this ticket be closed?

**Comment by stephen-hoover** [comment]
I believe the issue is still relevant. I still see the `logging.captureWarnings(True)` line in great_expectations/data_asset/data_asset.py.
