### ISSUE TITLE
hdfs datasource

### ISSUE THREAD

**Issue by gandesirijugalkishore** [fivetran/great_expectations#1864]
Unable to create an datasource using hdfs path although giving the path in the yml file and jupyter notebook explicitly  works.

**Comment by eugmandel** [comment]
Thank you for submitting this, @gandesirijugalkishore ! CLI does not currently support HDFS paths. This work is not scheduled for a near term, but community contributions are welcome.

**Comment by daavidstein** [comment]
We at Dendra Systems would also like this feature.

**Comment by l00173745** [comment]
Any update in supporting HDFS?
