### ISSUE TITLE
Window style backslash folder created on GCS

### ISSUE THREAD

**Issue by noklam** [fivetran/great_expectations#1886]
**Describe the bug**
Window style backslash folder created on GCS
![image](https://user-images.githubusercontent.com/18221871/92753902-e9caba80-f3bc-11ea-884b-2bb289423fe2.png)

**To Reproduce**
1. Configure validation datastore `TupleGCSStoreBackend`
2. run ge then push the results to GCS
3. duplicate folder with backslashes appears

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Window 10
 - GE Version: 0.12.0

**Additional context**

**Comment by eugmandel** [comment]
We acknowledge this is a bug. The core team is not prioritizing the fix in the near term, but community contribution is welcome.
