### ISSUE TITLE
The path of the generated json file is too long (Windows)

### ISSUE THREAD

**Issue by fpnick** [fivetran/great_expectations#1896]
**Describe the bug**
On Windows, the generation of an Expectation Suite crashes with "No such file or directory".
I assume this is because the file cannot be created since its path is too long (I tried to create in manually):

```
Generating example Expectation Suite...
[Errno 2] No such file or directory: 'C:\\Users\\Fabian.Nick\\Documents\\01_Projects\\*\\*\\*\\INTERNAL\\great_expectations\\uncommitted/validations/ma_klarnamen\\warning\\20200916T142925.370596Z\\20200916T142925.370596Z\\e1088205b931238fd870b213ec305f50.json'
```
_(* used to mask customer name)_

**To Reproduce**
1. Init great_expectations in a directory with at least 113 characters (in my case)
2. Follow the steps until generating the expectation suite
3. Observe the crash

**Expected behavior**
The json file should be created, probably using a shorter name?
At least I would expect to see an error message on why great_expectations crashed.

**Environment (please complete the following information):**
 - OS: Windows 10
 - GE Version: 0.12.1

**Comment by eugmandel** [comment]
@fpnick Thank you for reporting this! Your assumption is correct - the path in your example exceeds 260 characters, the default value of MAX_PATH env variable in Windows 10. 

There are 2 possible workarounds:
1. Init great_expectations in a directory with a shorter path
2. Increase the value of MAX_PATH on your system: https://helpdeskgeek.com/how-to/how-to-fix-filename-is-too-long-issue-in-windows/

**Comment by fpnick** [comment]
@eugmandel Thanks for your suggestions. Given I don't have admin privileges on my machine, I'll stick with running great_expectations in another directory for now. ;)

I'll leave this open because I think some fix/error message would still be nice. But feel free to close it if you think it's not that much of an issue for now.
