### ISSUE TITLE
Databricks python env REPL breaking due to nbconvert dependency

### ISSUE THREAD

**Issue by msch3ung** [fivetran/great_expectations#1904]
**Describe the bug**
Installing great_expectations pulls in the dependency ipywidgets which takes the latest version of nbconvert.   Recent releases since 9/10 causes an error that breaks the python env REPL causing the rest of the notebook to fail.  Databricks has advised us to install nbconvert 6.0.0rc0 to work around this.

`/databricks/python/lib/python3.7/site-packages/IPython/nbconvert.py:13: ShimWarning: The 'IPython.nbconvert' package has been deprecated since IPython 4.0. You should import from nbconvert instead.
 "You should import from nbconvert instead.", ShimWarning)
Traceback (most recent call last):
 File "<frozen importlib._bootstrap>", line 900, in _find_spec
AttributeError: 'ShimImporter' object has no attribute 'find_spec'
`

**To Reproduce**
Using dbutils install the great-expectations pyPi dependency and restart the python environment afterwards try any other python code to get a PythonDriverLocal.PythonException: Python interpreter is not defined for ReplId-XXXXX-XXXXX-XXXXX-X
error

`
dbutils.library.installPyPI("great-expectations", version="0.11.2")
dbutils.library.restartPython()
`

**Expected behavior**
I can run python in a databricks notebook afterwards.

**Environment (please complete the following information):**
 - OS: Databricks Runtime Version 6.5
 - GE Version: 0.11.2+

**Additional context**

**Comment by eugmandel** [comment]
Thank you for reporting this, @msch3ung ! 

I am quoting the workaround that Databricks suggested to you for the benefit of other users who encounter this issue: 
**Databricks has advised us to install nbconvert 6.0.0rc0 to work around this.**

This issue is not scheduled to be fixes yet, community contribution is welcome.

**Comment by bachhavdipak** [comment]
Still facing this issue with the databricks

```
%python
%pip install great-expectations
PythonDriverLocal.PythonException: Python interpreter is not defined for ReplId-35cae-f9149-fg1006-8
Python interpreter is not defined for ReplId-35cae-f9149-fg1006-8
```

**Comment by gpiotti** [comment]
same issue here
