### ISSUE TITLE
Column names with umlauts make Jupyter Notebook throw an error on startup

### ISSUE THREAD

**Issue by fpnick** [fivetran/great_expectations#1911]
**Describe the bug**
Using a data source with umlauts in the column names leads to the Jupyter Notebook with which the suite can be edited throw an error on startup. The Notebook then doesn't load.
This might be a Jupyter Notebook bug, not sure?!

**To Reproduce**
1. Initialize a suite with this xlsx file as a data source (nothing fancy: Just two columns, the first column contains the letter "Ä" in its header): 
[test.xlsx](https://github.com/great-expectations/great_expectations/files/5254989/test.xlsx) (Renaming the first column leads to a perfectly working example)
2. great_expectations suite edit test.warning
3. Observe the following error:

> Unreadable Notebook: C:\Users\Fabian.Nick\Desktop\tmp\ge\great_expectations\uncommitted\edit_test.warning.ipynb UnicodeDecodeError('utf-8', b'{\r\n "cells": [\r\n {\r\n "cell_type": "markdown",\r\n "metadata": {},\r\n "source": [\r\n "# Edit Your Expectation Suite\\n",\r\n "Use this notebook to recreate and modify your expectation suite:\\n",\r\n "\\n",\r\n "**Expectation Suite Name**: `test.warning`\\n",\r\n "\\n",\r\n "We\'d love it if you **reach out to us on** the [**Great Expectations Slack Channel**](https://greatexpectations.io/slack)"\r\n ]\r\n },\r\n {\r\n "cell_type": "code",\r\n "execution_count": null,\r\n "metadata": {},\r\n "outputs": [],\r\n "source": [\r\n "import datetime\\n",\r\n "import great_expectations as ge\\n",\r\n "import great_expectations.jupyter_ux\\n",\r\n "from great_expectations.data_context.types.resource_identifiers import (\\n",\r\n " ValidationResultIdentifier,\\n",\r\n ")\\n",\r\n "\\n",\r\n "context = ge.data_context.DataContext()\\n",\r\n "\\n",\r\n "# Feel free to change the name of your suite here. Renaming this will not\\n",\r\n "# remove the other one.\\n",\r\n "expectation_suite_name = \\"test.warning\\"\\n",\r\n "suite = context.get_expectation_suite(expectation_suite_name)\\n",\r\n "suite.expectations = []\\n",\r\n "\\n",\r\n "batch_kwargs = {\\n",\r\n " \\"data_asset_name\\": \\"test\\",\\n",\r\n " \\"datasource\\": \\".__dir\\",\\n",\r\n " \\"path\\": \\"C:\\\\\\\\Users\\\\\\\\Fabian.Nick\\\\\\\\Desktop\\\\\\\\tmp\\\\\\\\ge\\\\\\\\great_expectations\\\\\\\\..\\\\\\\\.\\\\\\\\test.xlsx\\",\\n",\r\n "}\\n",\r\n "batch = context.get_batch(batch_kwargs, suite)\\n",\r\n "batch.head()"\r\n ]\r\n },\r\n {\r\n "cell_type": "markdown",\r\n "metadata": {},\r\n "source": [\r\n "## Create & Edit Expectations\\n",\r\n "\\n",\r\n "Add expectations by calling specific expectation methods on the `batch` object. They all begin with `.expect_` which makes autocompleting easy using tab.\\n",\r\n "\\n",\r\n "You can see all the available expectations in the **[expectation glossary](https://docs.greatexpectations.io/en/latest/reference/glossary_of_expectations.html?utm_source=notebook&utm_medium=create_expectations)**."\r\n ]\r\n },\r\n {\r\n "cell_type": "markdown",\r\n "metadata": {},\r\n "source": [\r\n "### Table Expectation(s)"\r\n ]\r\n },\r\n {\r\n "cell_type": "code",\r\n "execution_count": null,\r\n "metadata": {},\r\n "outputs": [],\r\n "source": [\r\n "batch.expect_table_row_count_to_be_between(max_value=3, min_value=2)"\r\n ]\r\n },\r\n {\r\n "cell_type": "code",\r\n "execution_count": null,\r\n "metadata": {},\r\n "outputs": [],\r\n "source": [\r\n "batch.expect_table_column_count_to_equal(value=2)"\r\n ]\r\n },\r\n {\r\n "cell_type": "code",\r\n "execution_count": null,\r\n "metadata": {},\r\n "outputs": [],\r\n "source": [\r\n "batch.expect_table_columns_to_match_ordered_list(column_list=[\\"Column \xc4\\", \\"Column 2\\"])"\r\n ]\r\n },\r\n {\r\n "cell_type": "markdown",\r\n "metadata": {},\r\n "source": [\r\n "### Column Expectation(s)"\r\n ]\r\n },\r\n {\r\n "cell_type": "markdown",\r\n "metadata": {},\r\n "source": [\r\n "#### `Column \xc4`"\r\n ]\r\n },\r\n {\r\n "cell_type": "code",\r\n "execution_count": null,\r\n "metadata": {},\r\n "outputs": [],\r\n "source": [\r\n "batch.expect_column_values_to_not_be_null(column=\\"Column \xc4\\")"\r\n ]\r\n },\r\n {\r\n "cell_type": "code",\r\n "execution_count": null,\r\n "metadata": {},\r\n "outputs": [],\r\n "source": [\r\n "batch.expect_column_value_lengths_to_be_between(column=\\"Column \xc4\\", min_value=1)"\r\n ]\r\n },\r\n {\r\n "cell_type": "markdown",\r\n "metadata": {},\r\n "source": [\r\n "## Save & Review Your Expectations\\n",\r\n "\\n",\r\n "Let\'s save the expectation suite as a JSON file in the `great_expectations/expectations` directory of your project.\\n",\r\n "If you decide not to save some expectations that you created, use [remove_expectation method](https://docs.greatexpectations.io/en/latest/module_docs/data_asset_module.html?highlight=remove_expectation&utm_source=notebook&utm_medium=edit_expectations#great_expectations.data_asset.data_asset.DataAsset.remove_expectation).\\n",\r\n "\\n",\r\n "Let\'s now rebuild your Data Docs, which helps you communicate about your data with both machines and humans."\r\n ]\r\n },\r\n {\r\n "cell_type": "code",\r\n "execution_count": null,\r\n "metadata": {},\r\n "outputs": [],\r\n "source": [\r\n "batch.save_expectation_suite(discard_failed_expectations=False)\\n",\r\n "\\n",\r\n "results = context.run_validation_operator(\\"action_list_operator\\", assets_to_validate=[batch])\\n",\r\n "validation_result_identifier = results.list_validation_result_identifiers()[0]\\n",\r\n "context.build_data_docs()\\n",\r\n "context.open_data_docs(validation_result_identifier)"\r\n ]\r\n }\r\n ],\r\n "metadata": {},\r\n "nbformat": 4,\r\n "nbformat_minor": 4\r\n}\r\n', 2701, 2702, 'invalid continuation byte')

**Expected behavior**
The Notebook should load and be editable.

**Environment (please complete the following information):**
 - OS: Win 10
 - GE Version: 0.12.1

**Comment by eugmandel** [comment]
Thank you for reporting this, @fpnick ! We will triage and respond within a couple of days.

**Comment by haydarai** [comment]
I wasn't able to reproduce this on Mac, so maybe probably his installation of Windows doesn't have the language pack with an umlaut character installed?

**Comment by fpnick** [comment]
Since I am a native German, I have the necessary language pack installed. ;)
I would expect that MacOS copes a lot better with those things than Windows... :/

**Comment by haydarai** [comment]
@fpnick is it possible for you to share the generated notebook perhaps? wanted to know if the problem is on the generated notebook itself or it's a problem with the cli process to generate the notebook

**Comment by fpnick** [comment]
I went ahead and uploaded the full folder structure for you to look at :)
[ge.zip](https://github.com/great-expectations/great_expectations/files/5340774/ge.zip)

**Comment by fpnick** [comment]
Still relevant.
