### ISSUE TITLE
Creating a new suite on Presto datasource fails with pyhive.exc.DatabaseError

### ISSUE THREAD

**Issue by srjonemed** [fivetran/great_expectations#1917]
**Describe the bug**
Creating a new suite on Presto datasource fails with pyhive.exc.DatabaseError
`(pyhive.exc.DatabaseError) {'message': "line 1:8: mismatched input 'TEMPORARY'. Expecting: 'OR', 'ROLE', 'SCHEMA', 'TABLE', 'VIEW'", 'errorCode': 1, 'errorName': 'SYNTAX_ERROR', 'errorType': 'USER_ERROR', 'errorLocation': {'lineNumber': 1, 'columnNumber': 8}, 'failureInfo': {'type': 'com.facebook.presto.sql.parser.ParsingException', 'message': "line 1:8: mismatched input 'TEMPORARY'. Expecting: 'OR', 'ROLE', 'SCHEMA', 'TABLE', 'VIEW'", 'cause': {'type': 'org.antlr.v4.runtime.NoViableAltException', 'suppressed': [], 'stack': ['org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2028)', 'org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)', 'org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)', 'com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1594)', 'com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:237)', 'com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:156)', 'com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:97)', 'com.facebook.presto.execution.QueryPreparer.prepareQuery(QueryPreparer.java:56)', 'com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:342)', 'com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:304)', 'com.facebook.presto.$gen.Presto_0_227____20200703_160309_1.run(Unknown Source)', 'io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)', 'java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)', 'java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)', 'java.lang.Thread.run(Thread.java:748)']}, 'suppressed': [], 'stack': ['com.facebook.presto.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:109)', 'org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)', 'org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)', 'org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)', 'org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)', 'com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:3105)', 'com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:237)', 'com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:156)', 'com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:97)', 'com.facebook.presto.execution.QueryPreparer.prepareQuery(QueryPreparer.java:56)', 'com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:342)', 'com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:304)', 'com.facebook.presto.$gen.Presto_0_227____20200703_160309_1.run(Unknown Source)', 'io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)', 'java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)', 'java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)', 'java.lang.Thread.run(Thread.java:748)'], 'errorLocation': {'lineNumber': 1, 'columnNumber': 8}}}
[SQL: CREATE TEMPORARY TABLE "ge_tmp_e4d9335d" AS select * from ...;]
(Background on this error at: http://sqlalche.me/e/13/4xp6)
`

**To Reproduce**
`
$ great_expectations suite new
Select a datasource
    1. presto
    2. snowflake
    3. tmp__dir
: 1

Which table would you like to use? (Choose one)
    1. backups.aaa (table)
    2. backups.bbb (table)
    3. backups.ccc (table)
    4. data_store.ddd (table)
    5. data_store.eee (table)
    Do not see the table in the list above? Just type the SQL query
: select * from ... ;
`

**Expected behavior**

**Environment (please complete the following information):**
 - OS: MacOS
 - GE Version: 0.12.1

**Additional context**

**Comment by serkef** [comment]
How did you configure the presto source?
There is a relevant issue https://github.com/great-expectations/great_expectations/issues/1486 for supporting Presto. Currently it's not officially supported.

**Comment by srjonemed** [comment]
Yes I figured that might be the case, thanks for the pointer. 
Here's how I configured it..
-- config_variables.yml
presto_connxn:
  url: presto://user@host:8889/hive/<schema>

-- great_expectations.yml
 presto_query:
    data_asset_type:
      module_name: great_expectations.dataset
      class_name: SqlAlchemyDataset
    credentials: ${presto_connxn}
    module_name: great_expectations.datasource
    class_name: SqlAlchemyDatasource

I was able to get it to work by patching sqlalchemy_dataset.py to use the correct syntax for creating TEMP table, however will wait for it to be officially supported.

**Comment by eugmandel** [comment]
Great Expectations is not officially supporting Presto yet. When you are validating a result set of a query, Great Expectations saves the result set into a temporary table for performance reasons. The implementation of temporary tables varies across database engines. This is why you are getting this error. I am not sure if Presto has temporary tables - found this feature request: https://github.com/prestodb/presto/issues/3499.

We at the core team do not have immediate plans to implement this, but would love to get help from the community - someone who uses Presto and would be willing to contribute a PR that makes Great Expectations support it.

**Comment by giaosudau** [comment]
Is there any update on this issue?

Presto is more suitable for this kind of purpose.

**Comment by tooptoop4** [comment]
@srjonemed did u get it to work when presto needs password auth? mine is complaining that extra args about protocol=https need to be supplied to create_engine of sqlalchemy. but in the great_expectations docs its not clear how to pass them

**Comment by FreyaDingDing** [comment]
> @srjonemed did u get it to work when presto needs password auth? mine is complaining that extra args about protocol=https need to be supplied to create_engine of sqlalchemy. but in the great_expectations docs its not clear how to pass them

have you got any progress? I passed protocal=https but still got error
<img width="996" alt="image" src="https://user-images.githubusercontent.com/46193284/203713736-d59ae4e0-415c-4e62-97cc-cb7f084cec26.png">

my args is like:
datasource_config = {
    "name": "my_datasource",
    "class_name": "Datasource",
    "execution_engine": {
        "class_name": "SqlAlchemyExecutionEngine",
        "connection_string": "presto//username:password@host:port/hive/schema",
        "connect_args": {
            'protocol': 'https',
            'requests_kwargs': {'verify': False}
        }
    },
    "data_connectors": {
        "default_runtime_data_connector_name": {
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": ["default_identifier_name"],
        },
        "default_inferred_data_connector_name": {
            "class_name": "InferredAssetSqlDataConnector",
            "include_schema_name": True,
        },
    },
}

**Comment by srjonemed** [comment]
sorry, i was just evaluating the tool back then and our presto setup was not auth enabled

**Comment by FreyaDingDing** [comment]
btw, for the question has been for a long time, does GE support presto now? @eugmandel  I need help to check on this ticket https://github.com/great-expectations/great_expectations/issues/6428  Thanks a lot!
