### ISSUE TITLE
HTML for Custom Expectations Shows Hard to Read Parameters with **{

### ISSUE THREAD

**Issue by jdimatteo** [fivetran/great_expectations#1925]
**Describe the bug**
When following the guide [How to create custom Expectations](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_and_editing_expectations/how_to_create_custom_expectations.html), expectations in the data docs html show parameters with `**{` as in this screenshot::

![image](https://user-images.githubusercontent.com/3752732/94312704-a33b9b00-ff3a-11ea-8f9a-1ec389f3dba1.png)

**To Reproduce**
1. Define `SqlAlchemyDataset` custom expectations `expect_column_values_to_equal_2` and `expect_column_mode_to_equal_0` following the guide [How to create custom Expectations](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_and_editing_expectations/how_to_create_custom_expectations.html)
2. Follow the tutorial [Getting started with Great Expectations](https://docs.greatexpectations.io/en/latest/guides/tutorials/getting_started.html) 
2. Add the custom expectations to `great_expectations/expectations/taxi/demo.json`
3. Run `great_expectations checkpoint run staging.chk`
4. navigate to the Data Docs Home page
5. Click the latest validation result

**Expected behavior**
Parameters are shown without `**{`.

**Environment:**
 - OS: Debian Linux, Python 3.8.5, Chrome
 - GE Version: 0.12.1

**Additional context**
https://docs.greatexpectations.io/en/latest/reference/spare_parts/data_docs_reference.html?highlight=RenderedStringTemplateContent#custom-page-renderer-example looks related to a possible fix

**Comment by eugmandel** [comment]
@jdimatteo Thank you for reporting this. We acknowledge that this is a bug. Since it is not blocking a use case and based on the queue we are working on, I am marking it as "won't fix". This means that the core team does not expect to get to it, but we will gladly accept a contribution from the community.

**Comment by jdimatteo** [comment]
It looks like the problem is that `_missing_content_block_fn` defines `string_template` as `$expectation_type(**$kwargs)` here: https://github.com/great-expectations/great_expectations/blob/0.12.6/great_expectations/render/renderer/content_block/expectation_string.py#L117

Is there anyway to override the `_missing_content_block_fn` or specify a `string_template` for custom expectations (e.g. like how the built in expectations define string templates [like here](https://github.com/great-expectations/great_expectations/blob/0.12.6/great_expectations/render/renderer/content_block/expectation_string.py#L144))?

**Comment by ryanaustincarlson** [comment]
Some additional context in this discuss thread -- it sounds like v0.13 may bring some helpful improvements to how custom expectations are implemented and rendered
https://discuss.greatexpectations.io/t/how-to-customize-the-data-docs-output-for-a-custom-expectation/442/4
