### ISSUE TITLE
Working notes: Geo-related Expectations

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#1928]
On Friday, I had an awesome conversation with Mike about adding support for Geo-related Expectations. We’ve had several requests for this feature. I’m relatively new to working with Geo data; Mike enough was kind enough to walk me through some of the essentials.

Several major databases have recently (almost) standardized on a set of geographic functions. We’re looking primarily at Postgresql, Redshift, Snowflake, and BigQuery, and methods like:
```
	ST_CONTAINS
	ST_COVEREDBY
	ST_COVERS
	ST_DISJOINT
	ST_DWITHIN
	ST_EQUALS
	ST_INTERSECTS
	ST_INTERSECTSBOX
	ST_TOUCHES
	ST_WITHIN
	ST_AREA
	ST_DISTANCE
	ST_LENGTH
	ST_MAXDISTANCE
	ST_PERIMETER
```

Other DBs probably support similar methods—we’ll need to do some research. We should also look into support in pandas and Spark. Hopefully, there are good, well-maintained libraries that we can build on top of.

From a development perspective, we’re looking in to the idea that the main functionality would break into three groups.

1. Expectations that could be implemented strictly using built-in Geo functions within postgresql, Redshift, Snowflake, and Bigquery.
	`expect_geo_lat_lon_columns_to_be_within_column_region(lat_column, long_column, region_column, mostly)`
`expect_geo_lat_lon_column_distances_to_be_between(lat_column_A, lon_lon_column_A, lat_column_B, lon_column_B, min_distance, max_distance, mostly)`

The names need work—hopefully the parameters make the intent clear enough. The main idea is that all of the geo data is stored in columns that are already in the DB, so we don’t need to worry about handling, serializing, etc. those types. (At least not in SQLalchemy implementations; pandas and Spark could be different stories.)

2. Expectations that could be implemented primarily using built-in Geo functions within postgresql, Redshift, Snowflake, and Bigquery, but would require Expectations to accept external geo objects as  arguments.

`expect_geo_lat_lon_columns_to_be_within_region(lat_column, lon_column, region, mostly)`
`expect_geo_lat_lon_column_pair_distances_to_be_between(lat_column lon_column, lat_value, lon_value, mostly)`

3. More exotic stuff.
TBD

We’re excited about the possibility of building out geo-focused Expectations. The plan is to start a conversation/lightweight design doc here. As chunks of work become well-scoped, well pull them off into specific issues marked for contributors. These could be good issues for #hacktoberfest.

PS: Please be aware the most of the core team is focused on finishing the 0.13.0 release in the next couple weeks.

**Comment by noklam** [comment]
@abegong is GE opt-in for hackforberfest? i just notice they changes the rule and requires either project add #hacktoberfest to the repository topic or add a specific label to individual PR. It would help my progress if GE joins it.
