### ISSUE TITLE
Expectations with relationships between two data columns

### ISSUE THREAD

**Issue by gouker** [fivetran/great_expectations#194]
One area that I have intuitively wanted to build expectations around are relationships between two columns — from skimming through the documentation it seems like that’s not a thing (yet?).  For instance, I may want an expectation that col A value is always greater than or equal to col B.  

Col A | Col B | Expectation Result
-- | -- | --
5 | 0 | Pass
4 | 3 | Pass
6 | 6 | Pass
6 | 8 | Fail

A more specific use case that I have that would be great to build in is to build an expectation around the load date and a timestamp field. 

For example:

Unique ID | Load Date | Timestamp | Expectation Result
-- | -- | -- | --
A | 2018-02-10 | 2018-02-10 05:00:00 | Pass
B | 2018-02-10 | 2018-02-10 06:15:00 | Pass
C | 2018-02-11 | 2018-02-11 08:10:30 | Pass
D | 2018-02-11 | 2018-02-10 13:24:00 | Fail
E | 2018-02-11 | 2018-02-11 15:25:00 | Pass

In this made up example, maybe it would be useful to have an expectation that says I expect 98% of my records to have a timestamp that falls on my load date.  If my data falls below that margin then that may indicate an issue with the loading process and I’d want to know about it.

**Comment by abegong** [comment]
Can you check out PR #173 and see if it would fit the bill? 

In particular, this commit (<https://github.com/great-expectations/great_expectations/pull/173/commits/2554e642d64f914ed76aa08fcebcd063061f85fc) introduces an expectation called `expect_column_pair_values_to_be_greater_than` that I think does exactly what you're asking for.

For the second one, the same PR includes a commit <https://github.com/great-expectations/great_expectations/pull/173/commits/bdf737c037a950e953e9d5f110dac8aca7ab7718>
introducing `expect_column_pair_values_to_be_equal`. It allows `mostly`, so would be easy to set `mostly=.98`.

A complicating factor is matching dates versus datetimes. Is it possible for you to create a derived column from the timestamp column before processing with GE? Alternatively, we could implement that conversion as a preprocessing step in the expectation (see Issue #80), but that isn't implemented yet.

Does that make sense?

**Comment by abegong** [comment]
Bleh. Updated my previous comment to get rid of the horrible formatting from gmail.

@gouker If this looks like a good path forward, I can implement the multi-column expectations in the next couple days.

**Comment by gouker** [comment]
@abegong I think with the expect_column_pair_values_to_be_equal expectation there would be a way I could format the date data in the second column to get it to play nicely with the expectation.  I agree that date/datetime columns are finicky and probably not worth their own expectation right now.

I'll play around with it once it's available and ready for user testing.
