### ISSUE TITLE
links in Data Docs footer are broken

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1941]
**Describe the bug**
The first and third CTA footer links are broken.

**To Reproduce**
1. `great_expectations docs build`
2. click on the footer CTA buttons
3. Note broken RTD links

**Expected behavior**
Correct links

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS, Windows
 - GE Version: [e.g. 0.10.0] 0.12.3

**Comment by eugmandel** [comment]
@Aylr @sbrugman has a PR that addressed it: https://github.com/great-expectations/great_expectations/pull/1946 - I will review it shortly.

**Comment by eugmandel** [comment]
Merged the PR - thanks to @sbrugman !
