### ISSUE TITLE
Support for nd-array / xarray data

### ISSUE THREAD

**Issue by rabernat** [fivetran/great_expectations#1942]
**Is your feature request related to a problem? Please describe.**

Just learned about this cool project via [twitter](https://twitter.com/expectgreatdata/status/1311700419522048001). Thanks for providing this great tool!

I am a climate scientist working with labeled ND-array data, usually via numpy or [xarray](http://xarray.pydata.org/). Such datasets are common in many scientific fields. Your docs state you support

> pandas, SQL (including distributed environments like BigQuery and Redshift), and Spark.

I'm curious whether there are plans to support nd-array data / xarray data from great_expectations. Or is the scope limited to tabular-style data?

**Comment by eugmandel** [comment]
@rabernat Currently Great Expectations supports only tabular data (or at least data that can be made tabular, e.g. nested JSON that can be "unfurled"). The architecture does not preclude implementing support for non-tabular/nested data.

The core team has no immediate plans to add support for nd-array/xarray. However, our next major release (0.13.0) will make it much easier to implement new kinds of expectations, so we will be looking to the community to come up with many more expectations.

**Comment by shaunc** [comment]
I'm curious if any community users have taken @eugmandel's suggestion and extended g-e to xarray datasets?

**Comment by fmfreeze** [comment]
Curious too, as this would expand the coverage of potential use-cases for GE massively.
