### ISSUE TITLE
Data Docs build does not build suite pages if being run via a checkpoint and does not upload assets

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1944]
**Describe the bug**
Data Docs build does not build suite pages if using a GCS bucket

**To Reproduce**
1. Create a number of suites
2. Set up a GCS site
3. `great_expectations docs build`
4. Note a GCS site with an index page only - no other files or assets.

**Expected behavior**
I expect a full datadocs site

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - GE Version: [e.g. 0.10.0] 0.12.3

**Comment by noklam** [comment]
I think you have to also set your validation store, expectation store to be GCS.

The doc site setting really just setting the index page.

**Comment by Aylr** [comment]
<img width="1636" alt="Data_Docs_created_by_Great_Expectations" src="https://user-images.githubusercontent.com/928247/94960938-f2407d80-04b0-11eb-9077-125ace0870ec.png">

**Comment by anthonyburdi** [comment]
FYI while trying to reproduce this: currently `great_expectations docs build` seems to work as expected, however this issue does crop up when using `great_expectations checkpoint run ...`

**Comment by anthonyburdi** [comment]
FYI this issue was reproduced on s3 & Filesystem as well when using `great_expectations checkpoint run <checkpoint_name>`

**Comment by anthonyburdi** [comment]
Quick update @Aylr @eugmandel - I have a proposed method to fix this in branch [anthony/bugfix/issue_1944](https://github.com/great-expectations/great_expectations/compare/anthony/bugfix/issue_1944) and am adding tests before submitting a PR.
The proposed fix is to check for the existence of a data docs site (via a method on `HtmlSiteStore` to check for an existing `index.html`) and if it does not exist, recreating the data docs site from scratch during an `SiteBuilder.build()` by removing the `resource_identifiers`. This will keep existing functionality as-is, i.e. running a checkpoint for an existing data docs site will only add a page for the new validation and fix the linked issue by rebuilding data docs in full if they don't exist.
Feedback / other ideas welcome!

**Comment by Aylr** [comment]
A note of mild warning - I vaguely recall the original intent of the resource identifier being passed was to build only the new page rather than the very slow rebuild of the entire site. If a user has many suites (or few large ones), or many validation results this can take quite some time to do.

**Comment by anthonyburdi** [comment]
Makes perfect sense! Just to be clear - the resource_identifier is only removed if there is no existing site, in which case you would likely want to rebuild. However noted that it could take a very long time, and a user may not have set a `validation_results_limit`. 

Maybe there is a middle ground where if there is no existing site during a checkpoint run, we just make sure the index / expectation / static sections of the site are built (in addition to the given resource identifier for the validation). I'm looking into `DefaultSiteSectionBuilder.build()` to see if we can force a build of the expectations pages if the site does not exist and the given resource_identifier is not an `ExpectationSuiteIdentifier` (assuming that in this case a user would just want to render that single expectation suite).

**Comment by anthonyburdi** [comment]
@Aylr FYI - I changed the functionality to the following: All expectation suites are always rendered unless resource_identifiers contains ExpectationSuiteIdentifier(s). If resource_identifiers contains ExpectationSuiteIdentifier(s) then only those are rendered. PR is now ready for review.
