### ISSUE TITLE
Add ge.read_json_lines() API

### ISSUE THREAD

**Issue by rjurney** [fivetran/great_expectations#195]
My data is not columnar in format, although it is by nature columnar. Therefore a method `read_json_lines()` would help me to load my data. After running an optional accessor function (for nested tables), it would evaluate the top line in the array to determine fields. Then it would iterate the fields and build whatever dataframe format `ge` needs.

data: `{"type": "prediction", "values": [{"field1": 1.0, "field2": 0.1}, ...]}`

```
def read_json_lines(filename, accessor=None):
  record = json.load(filename)
  records = accessor(record) if accessor else record
  ...
```

Thanks!

**Comment by jpcampb2** [comment]
Your use case makes a lot of sense. Does the pandas [read_json](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_json.html) function correctly handle your data? If so, I expect it would make sense for us to allow that as a first-class way to create new dataframes.

That would also allow you to get a ge object easily today by creating the ge PandasDataSet object directly from your dataframe:

```
df = pd.read_json(your_json_data)
ge_df = ge.dataset.PandasDataSet(df)
```

**Comment by abegong** [comment]
@rjurney I'm confused about what an `accessor` is in this use case. Can you clarify?

**Comment by rjurney** [comment]
@jpcampb2 With one exception, read_json would work. With many of my pipelines, the tabular data is held inside a metadata wrapper describing the dataset. The accessor is therefore needed to pull the tabular data out. That is why I have included an accessor function argument in the API. Otherwise I would need to use `pandas.DataFrame(accessor(json.load('myfile.json')))` or something like `pandas.DataFrame(json.load('myfile.json')['my_accessor_key'])`.

@abegong The accessor is an optional function that pulls the table out of a nested JSON record. It is common for the output of data pipelines to have metadata wrappers describing the record type, date of creation, etc. for the entire file and not one line of a row. In these cases, the table is nested inside an outer metadata wrapper, so you need to do something like record['accessor_key'] to access it. In this case typically accessor would be `lambda x: x['my_accessor_key']` or some such function.

**Comment by abegong** [comment]
:+1:
