### ISSUE TITLE
Can I pass a complete data frame into Column Map & Column Aggregate Expectation while creating a Custom expectation?

### ISSUE THREAD

**Issue by GuptaTanay** [fivetran/great_expectations#1963]
I want to create a custom expectation wherein I have created a python function which involves several functions on the pandas data frame and based on those function, I want to create a custom expectation, Can I pass a complete pandas data frame in Column Aggregate or Column Map Expectation decorator?

eg. I want to compare 2 columns after performing the SQL windows function on the PandasDataSet.

**Comment by eugmandel** [comment]
@GuptaTanay If you using the generic expectation decorator, you can create an expectation that accepts anything as its arguments. Closing this issue, since it is a question.

**Comment by GuptaTanay** [comment]
@eugmandel  Thanks for the answer. Apologies had to ask a question here as I did not receive any reply over the discussion forum. 
This will help, I will look for the Generic decorator in the documentation,
