### ISSUE TITLE
path in checkpoint metadata is not relative path

### ISSUE THREAD

**Issue by deep-diver** [fivetran/great_expectations#1971]
**Describe the bug**
when I push checkpoints to a remote repo, the metadata says it's path doesnt exist. I have inspected the file, and I found the path is not relative path. It literally shows the path in my local machine.

**To Reproduce**
1. great_expectations init (create with new suite scaffold)
2. great_expectations checkpoint new new.checkpoint suite.name
3. vim great_expectations/checkpoints/new.checkpoint.yaml
4. see the path variable

**Expected behavior**
the path should not be absolute path but relative one. 

**Environment (please complete the following information):**
 - OS: Linux and Great Expectation GitHub Action
 - GE Version: 0.12.3

**Comment by deep-diver** [comment]
@eugmandel what does the labels mean?

**Comment by eugmandel** [comment]
@deep-diver Here is the workaround: If the CLI put the absolute path of the file to validate in the checkpoint's yml config file, you can manually edit the file to switch the path to relative.

**Comment by deep-diver** [comment]
@eugmandel Sure
The problem is that I need to change it "manually". Do you think that is good enough? Just wondering

**Comment by deep-diver** [comment]
@eugmandel when you say "workaround", this issue is unacceptable?
