### ISSUE TITLE
Feature request: Support nesting in jsonschema profiler

### ISSUE THREAD

**Issue by colmsnowplow** [fivetran/great_expectations#1977]
**Is your feature request related to a problem? Please describe.**

I'm experimenting with the jsonschema profiler. We use Jsonschema quite heavily, sometimes those schemas have several levels of nesting. It would be awesome if this was supported in some future version.

**Describe the solution you'd like**
Jsonschema profiler can iterate through n degrees of nesting and generate expectations for all nested fields where required.

**Describe alternatives you've considered**

Could possibly be worked around with some custom code, or by splitting out the nested definitions into their own schemas - just experimenting atm so haven't tried either at this point.

**Comment by eugmandel** [comment]
@colmsnowplow This is a good suggestion! Marking this with "**_help wanted_**" label to invite a community contribution.

**Comment by Arwiim** [comment]
@colmsnowplow Hey! i'm working whit the jsonschema profiler but there is not example for how we have to create the schema. You have some example to share?

**Comment by talagluck** [comment]
Hi @colmsnowplow - thanks for raising this! This is great feedback. Realistically, this isn't something that we will be able to implement in the immediate future, but we've logged this feedback to consider later.
