### ISSUE TITLE
dynamic replacement of the enviroment variable supports only one variable per line

### ISSUE THREAD

**Issue by wingriderr** [fivetran/great_expectations#1981]
**Describe the bug**
By default anything in between ${} should be replaced by the corresponding value in the environment variable. However for url type credentials , the substitute variable is  not working. Tried in great_expectations.yml and config_variables.yml

**config_variables.yml**
```
pedsprd:
  url: mssql+pyodbc://${SQL_USERNAME}:${SQL_PASWD}@hostname.db.windows.net:1433/db?driver=ODBC+Driver+17+for+SQL+Server&autocommit=true
```

However the below is working when i replace the environment variable with the actual password

```
pedsprd:
  url: mssql+pyodbc://${SQL_USERNAME}:thisisthepassword@hostname.db.windows.net:1433/db?driver=ODBC+Driver+17+for+SQL+Server&autocommit=true
```

**To Reproduce**
1. Setup great_expecatations.init
2. Try connecting to Azure synapse database using the odbc url . 
3. You will get an error with the below
```
- (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'sysdba'. (18456) (SQLDriverConnect)")
(Background on this error at: http://sqlalche.me/e/13/rvf5)
```

**Expected behavior**
Should be able to connect

**Environment (please complete the following information):**
 - GE Version: [e.g. 0.10.0]

**Additional context**
I believe its inability to specify multiple parameters in one line. In MSSQL based connection we have to use url based connectivity and this demands to use more than 1 environment variable in one line

**Comment by eugmandel** [comment]
@wingriderr Thank you for reporting this issue! The root cause is exactly what you are saying in the "Additional context" section: current implementation has a limitation - **only one variable can be substituted in a line**. 

I edited the title of the issue to make sure that it is clear.

**Workaround:** 
replace 
```
pedsprd:
  url: mssql+pyodbc://${SQL_USERNAME}:thisisthepassword@hostname.db.windows.net:1433/db?driver=ODBC+Driver+17+for+SQL+Server&autocommit=true
```
with 
```
pedsprd:
  url: ${SQL_SERVER_SQLALCHEMY_URL}

```
I will leave this issue open. The core team will not work on it in the near term (based on current workload), but we welcome contributions.

**Comment by wingriderr** [comment]
nws @eugmandel . Didnt work on fixing this as found a  real workaround is to specify the username password in one environment variable as below in the url 
```
export SQL_USERNAME='sysuser'
export SQL_PASSWORD='thisistherealpassword'
export SQL_CRED=$SQL_USERNAME:$SQL_PASSWORD
and use the url as below 
url: mssql+pyodbc://${SQL_CRED}@hostname:port/dbname?driver=ODBC+Driver+17+for+SQL+Server&autocommit=true
```

**Comment by eugmandel** [comment]
@wingriderr That's another good workaround!
