### ISSUE TITLE
[Feature Request] - Site allow right click to open a validation result as a new tab

### ISSUE THREAD

**Issue by noklam** [fivetran/great_expectations#1986]
Currently, the GE site shows a table of the validation results. When there are lots of validations results, some filtering and search is needed. The UI does not allow a right click to open the validation result as a new tab. When user click "Go Back", it will remove all the search/filtering criteria.

See screenshots below:
![image](https://user-images.githubusercontent.com/18221871/96073187-890d3100-0ed8-11eb-8423-6b604b51a77c.png)

**Comment by eugmandel** [comment]
@noklam This is a great suggestion! Added "help wanted" tag to invite a community PR.

**Comment by mmetzger** [comment]
I mentioned this in Slack but I've looked into implementing this - the cleanest option might be a simple link (ie, the Expectation Suite link) vs trying to add a context menu / etc. I’m new to the codebase - is there a preference for web behavior in this instance?

**Comment by noklam** [comment]
I think as long as it is easy to start a new tab it would be fine, a simple link like the expectation would be fine.
