### ISSUE TITLE
Failed To Provide partial_unexpected_counts in Validation Results

### ISSUE THREAD

**Issue by prajwal-kesava** [fivetran/great_expectations#1994]
**Describe the bug**
GE is failing to give correct "**partial_unexpected_counts**" in validation  json result after running "**action_list_operator**.
When I am Validating Column Type with **Integer** ,which has mixed data types in it, then in GE JSON result i am seeing like
**"partial_unexpected_counts": ["partial_exception_counts requires a hashable type"]** as one key-value pair.

This is Happening with all versions of GE and this is due to **Counter** that we are using to calculate "partial_unexpected_counts" in **great_expectations\data_asset\data_asset.py** file.
**To Reproduce**
1. create a batch with dataframe like df=pd.DataFrame(
    { 
        'Id' :[ 45.02 , 21.123 , 40.12 , 25.122 , "43" ],
        'Name' :[ ' %% JobID %% ' , 21.0 , 40 , 21 , np.nan],
        'Age' :[ ' %% JobID %% ' , 21.0 , 40.0 , 21 , np.nan],
        'Age2' :[ ' %% JobID %% ' , 21.0 , 40.0 , 2 , np.nan]
    }
)
2. create an expectation suite with batch.expect_column_values_to_be_of_type('Id','int')
3. save expectation_suite with above 1 expectation
4. run  

- 1. results = context.run_validation_operator("action_list_operator", assets_to_validate=[batch], run_id=run_id)
- 2. expectation_suite_identifier = ExpectationSuiteIdentifier(expectation_suite_name)
- 3. validation_result_identifier = ValidationResultIdentifier(expectation_suite_identifier=expectation_suite_identifier, 
batch_identifier=batch.batch_kwargs.to_id(), run_id=run_id')

5. Verify the  **partial_unexpected_counts**  value in Json Result under your **Validation_Store** 
Please find GE Result in below attached file
![Screenshot (24)](https://user-images.githubusercontent.com/51196441/96203074-95e46000-0f7e-11eb-95c3-60a7d0df6b57.png)

**Expected behavior**
Json Validation Result should have like this  "partial_unexpected_counts": [{"value": 45.02, "count": 1}, {"value": "21.123", "count": 1},{"value": "25.122", "count": 1}]

**Environment (please complete the following information):**
 - OS: All
 - GE Version: All [Latest Too]
**Additional context**
@alexsherstinsky @eugmandel

**Comment by eugmandel** [comment]
@prajwal-kesava Thank you for providing easy-to-follow steps to reproduced! I see the same error that you are reporting. Marking this "core-team-priority", but not sure when we will get to it. In the meantime, if there is a community PR that addresses this, it will be very much welcome.

**Comment by spbail** [comment]
FYI @prajwal-kesava The fix has been merged, should go into a release in the next few days. Thanks for reporting it!
