### ISSUE TITLE
Is it possible to have the click dependency to a lower version? Or have CLI as an extra?

### ISSUE THREAD

**Issue by Selvaticus** [fivetran/great_expectations#1996]
**Is your feature request related to a problem? Please describe.**
When using multiple dependencies that have CLIs they sometimes clash as often projects will depend on `click` to build their CLIs and end up setting some arbitrary version requirement.

**Describe the solution you'd like**
An improvement would be to have the `click` version set to the minimum that provides the features that the project needs. Allowing flexibility on package resolution. E.g. instead of `Click>=7.1.2` have `Click>=6.7` or whatever minimum works.
Is this possible?

**Describe alternatives you've considered**
Have the entire CLI feature + deps as an extra. I think this is a better solution to minimise clashes with other tools and still allow developers to use `great_expectations` programatically the possibility to do so.

**Additional context**

In my particular case, I'm using `elasticsearch-curator` and now adding `great_expectations` they clash on completely incompatible versions of `click` which forces me to go all the way down to 0.6.1 for `great_expectations`, not ideal 😢

**Comment by eugmandel** [comment]
@Selvaticus Thank you for reporting this! Our long term solution for issues like that is to have a second package - something like "great_expectations_minimal" that will have just the absolute essentials. This is the plan, but not going to be implemented immediately. Unfortunately, we cannot lower the requirements for click, since we upgraded to 7 for some newer features.

I will keep this issue open to track progress.

**Comment by Selvaticus** [comment]
Thank you for the quick response. I understand the constraints.

When time comes to split packages, may I suggest to have the `cli` as a separate package, or as an extra dependency on current.

I can see use cases where having the full offering of `great_expectations` minus `cli` would be advantageous:
- Users that are comfortable writing config by hand or want to
- Users that like to have code as config and hence would use the APIs
- Deployed scenarios were file systems might not present and/or having code as config would be preferred for reproducible versioned runs.

Just some food for thought. And once again thank you for the promptly response
