### ISSUE TITLE
[Feature Request] - SubdirReader for S3

### ISSUE THREAD

**Issue by noklam** [fivetran/great_expectations#2000]
**Is your feature request related to a problem? Please describe.**

I found that it is hard to use different backend for GE. For example, when I started development, I use my local filesystem. Once I move to cloud storage(S3), I found that the migration is not simple. I have to change a lot of configuration. There are no sub-directory reader for S3 but only GlobReader.

The file path is coupled with very specific method, especially with checkpoint. Imagine if I started development in local, I would have all my checkpoint hard-coded to local path. If I need to move them to a cloud storage later, there are no easy way to do that. As a result, I always write code to dynamically construct these path instead of using the path.

**Describe the solution you'd like**
I think we can make use of `s3fs` to clean up the configuration. The ideal case is I can simple add some additional configurations to make it works from local to S3. (i.e. endpoint_url, key and secret).

**Comment by eugmandel** [comment]
Thank you for writing this up, @noklam ! We will look at the PR and comment there.
