### ISSUE TITLE
CLI should support GCS and S3 paths for Pandas Datasources

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#2006]
**Describe the bug**
Suite new CLI fails when passed a file on GCS

**To Reproduce**
0. `pip install gcsfs` (this allows pandas to use `gs://` urls natively in `read_csv`)
1. Set up a vanilla pandas datasource
```
  gcs:
    data_asset_type:
      class_name: PandasDataset
    class_name: PandasDatasource
    module_name: great_expectations.datasource
```
2. `great_expectations suite new`
3. choose gcs datasource
4. enter gs path to existing file such as gs://my-bucket/data/foo.csv
5. Note the error. The CLI assumes a file is local or possibly S3 only.
```
Enter the path (relative or absolute) of a data file
: gs://my-bucket/data/foo.csv
Error: File 'gs:/my-bucket/data/foo.csv' does not exist.
```

**Expected behavior**
I expect the file to be found and proceed with the suite creation without arduous workarounds that require contributor level experience.

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - GE Version: [e.g. 0.10.0] 0.12.6

**Additional context**

Note when you have a working notebook (which requires selecting a local file then modifying the batch kwargs) you can prove that it _should_ work:
```
import datetime
import great_expectations as ge
import great_expectations.jupyter_ux
from great_expectations.data_context.types.resource_identifiers import (
    ValidationResultIdentifier,
)

context = ge.data_context.DataContext()

# Feel free to change the name of your suite here. Renaming this will not
# remove the other one.
expectation_suite_name = "gcs"
suite = context.get_expectation_suite(expectation_suite_name)
suite.expectations = []

batch_kwargs = {
    "data_asset_name": "foo",
    "datasource": "gcs",
    "path": "gs://my-bucket/data/foo.csv",
    "reader_method": "read_csv",
}
batch = context.get_batch(batch_kwargs, suite)
batch.head()
```

**Comment by eugmandel** [comment]
CLI will accept filesystem, "s3a://" and "gs://" paths as valid inputs when prompting for a data file for a Pandas Datasource. Implemented.
