### ISSUE TITLE
Images not found when running taxi-demo

### ISSUE THREAD

**Issue by hugohjerten** [fivetran/great_expectations#2008]
**Describe the bug**
I am doing the "Getting started with Great Expecations" tutorial, with the taxi dataset. After having run the `great_expectations suite scaffold taxi.demo` command and generated the first docs page, I was greeted with some "first time" cards with 7 cards. In several of these cards there were multiple images that were not found.

page 1: static/images/iterative-dev-loop.png
page 5: static/images/validation_failed_unexpected_values.gif
page 6: static/images/glossary_scroller.gif

**To Reproduce**
 - Do the "Getting started with Great Expecations" tutorial
 - Follow the steps as stated in the documentation
 - After the command `great_expectations suite scaffold taxi.demo`

**Expected behavior**
Images shown.

**Environment (please complete the following information):**
 - OS: Mac OS
 - GE Version: 0.12.6
 - Poetry version: 1.1.3
 - Python version: 3.8.5

<img width="800" alt="Screenshot 2020-10-24 at 09 27 13" src="https://user-images.githubusercontent.com/11174653/97082205-4817c980-1608-11eb-8b67-afeb514bc3aa.png">
<img width="793" alt="Screenshot 2020-10-24 at 09 27 26" src="https://user-images.githubusercontent.com/11174653/97082212-56fe7c00-1608-11eb-9524-c1f57c7a917c.png">

**Comment by eugmandel** [comment]
Thank you for reporting this, @hugohjerten ! We will triage it today.

**Comment by miike** [comment]
Posting here as this is related: https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1596683377075000

Looks like it can be fixed in the Jinja template here `great_expectations/render/view/templates/carousel_modal.j2`

**Comment by talagluck** [comment]
Thanks for reporting, @hugohjerten! The latest version of GE no longer has this issue. I'm going to close this issue, but please reach out if you have any further questions or issues!
