### ISSUE TITLE
ModuleNotFoundError: No module named 'ruamel' while importing great_expectations

### ISSUE THREAD

**Issue by amraf1002** [fivetran/great_expectations#2016]
We are trying to use GE with GCP DataProc clusters. While cluster creation we are installing great-expectations==0.12.4. This installs ruamel.yaml==0.15.35 as dependency. After cluster creation if we try to import great_expectations we get error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/default/lib/python3.6/site-packages/great_expectations/__init__.py", line 7, in <module>
    from great_expectations.data_context import DataContext
  File "/opt/conda/default/lib/python3.6/site-packages/great_expectations/data_context/__init__.py", line 1, in <mo
dule>
    from .data_context import BaseDataContext, DataContext, ExplorerDataContext
  File "/opt/conda/default/lib/python3.6/site-packages/great_expectations/data_context/data_context.py", line 17, i
n <module>
    from ruamel.yaml import YAML, YAMLError
ModuleNotFoundError: No module named 'ruamel'

For the above ruamel.yaml version correct way to import is "import ruamel_yaml" instead of "import ruamel.yaml". But if we upgrade ruamel.yaml version to 0.16 and then try to import GE, it works as expected. Dependency version issue of ruamel.yaml should be upgraded to 0.16 so that we don't have to upgrade ruamel.yaml version separately after install GE for GE to work

**To Reproduce**
1. install great-expectations==0.12.4
2. Check if ruamel-yaml version <= 0.15.35
3. import great_expectations

**Expected behavior**
ruamel.yaml==0.16 should be installed as dependency for great-expectations==0.12.4

**Environment (please complete the following information):**
 - OS: Debian, GCP 
 - DataProc Image Version=image_version='1.4'
 - GE Version: 0.12.4

**Comment by eugmandel** [comment]
@amraf1002 Thank you for reporting this! Would you like you to submit a PR with the fix (`ruamel.yaml>=0.16`) ?

**Comment by shivamneeraj23** [comment]
@eugmandel Can I help in fixing this issue? I am new to this library. Would like to start with this issue 😄
