### ISSUE TITLE
Failed validation on expectation: expect_table_columns_to_match_set

### ISSUE THREAD

**Issue by rubenssoto** [fivetran/great_expectations#2017]
Hello Guys,

Thank you, for this great product!

I created a validation with expectation expect_table_columns_to_match_set, and I got a validation "failed",
but the first column of expected results is wrong "eval_col_order_id", the real column name is only order_id.

Could you help me? Thank you

<img width="1680" alt="Captura de Tela 2020-10-29 às 11 41 04" src="https://user-images.githubusercontent.com/36298331/97596000-0cec1080-19e3-11eb-945c-176d2f90bf17.png">

**Comment by bhcastleton** [comment]
This does indeed look suspicious. I went through the columns that are expected and they're all showing up in the observed values in the screenshot (even the 'order_id' column does show up later in the observed values.) And as @rubenssoto mentions, the first observed value in Observed Values looks suspicious.

**Comment by anthonyburdi** [comment]
Hi @rubenssoto!! We are so glad that you are getting good use out of Great Expectations 😄 I am assuming based on the first tab in your screenshot that you are using EMR Spark?
I have a suspicion that the `__eval_col_` prefix is coming from spark_dataset.py: https://github.com/great-expectations/great_expectations/blob/ad62cf6e04cf9df8b444b4f5d689afe635d1a942/great_expectations/dataset/sparkdf_dataset.py#L94
I'm trying to determine if there is a better fix than filtering this spurious column out in the expectation.

**Comment by rubenssoto** [comment]
Yes Im using Emr 6.1 with spark 3.0.0

**Comment by roblim** [comment]
Hi @rubenssoto! I just wanted to check in. I investigated your issue this week but was unable to replicate locally. In addition, I've confirmed with the GE team that this issue should be nonexistent in the new Expectations API. Given that, we've decided not to investigate this issue further but of course always welcome community contributions in case you've come up with a fix!

If you're able, would you mind attempting the same validation using the new API? It would be helpful to know if you still run into issues. Here are some links to relevant docs:
- [Checkpoints and Actions Introduction](https://docs.greatexpectations.io/en/latest/reference/core_concepts/checkpoints_and_actions.html)
- [How to create a new Checkpoint (Docs for Class-Based Checkpoints (>=0.13.8))](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/validation/how_to_create_a_new_checkpoint.html)

**Comment by gleman2** [comment]
First of all, thank you for a great product!
@roblim , I was able to reproduce it locally on great-expectations==0.13.9
To reproduce it, run any expectation on a column before running `expect_table_columns_to_match_set`. 
By doing so, sparks creates a new column `__eval_col_{column_name}` . Because of that validation fails.
