### ISSUE TITLE
[BUG] pip install -r requirements-dev.txt failure

### ISSUE THREAD

**Issue by shapiroj18** [fivetran/great_expectations#2028]
**Describe the bug**
When I set up a contribution environment according to the [documentation](https://docs.greatexpectations.io/en/latest/contributing/setting_up_your_dev_environment.html#contributing-setting-up-your-dev-environment), I run into the issue below when I run `pip install -r requirements-dev.txt.`

```ERROR: Double requirement given: black==19.10b0 (from -r requirements-dev-test.txt (line 6)) (already in black>=19.10b0 (from -r requirements.txt (line 7)), name='black')```

**To Reproduce**
1. Set up new environment using python3 venv
2. `pip install -r requirements-dev.txt.` after forking repo and following other steps in setting up development environment [documentation](https://docs.greatexpectations.io/en/latest/contributing/setting_up_your_dev_environment.html#contributing-setting-up-your-dev-environment)

**Expected behavior**
When I run `pip install -r requirements-dev.txt.` in a fresh environment it should run install all necessary dependencies.

**Environment (please complete the following information):**
 - iOS

**Comment by eugmandel** [comment]
@shapiroj18  Thank you for reporting this! 
For now, documenting a workaround: install black 19.10b0 or higher manually before running the command.

**Comment by shapiroj18** [comment]
@eugmandel added a pull request to fix this https://github.com/great-expectations/great_expectations/pull/2052. What do you think?
