### ISSUE TITLE
 CLI commands should print out out pass/fail status of each expectation 

### ISSUE THREAD

**Issue by sahilds1** [fivetran/great_expectations#2040]
**Is your feature request related to a problem? Please describe.**

`great_expectations validation-operator run`  and `great_expectations checkpoint run` both return Validation succeeded or Validation failed and details on each validation (as of PR #1922). 

Building off of PR #1922,  I want to surface the status of each expectation because we're running GE in production (specifically in Docker containers on AWS) and we want to be able to inspect failing expectations after the job has finished running in the logs. 

**Describe the solution you'd like**

My point of reference for a solution is pytest (https://docs.pytest.org/en/stable/). 

My issue is related to PR #1922 but I want the CLI commands to print out not only details for each expectation suites, but also the details on checks within each suite. 

Though this may result in the details of hundreds of expectations in the logs, our requirements would still be met because we could parse the text file ourselves. Also, part of this solution could be a flag to only optionally surface failed expectations

**Describe alternatives you've considered**

Alternatively, I can write a Python script, import ge and ge.validate  returns a JSON with the expectations.

**Comment by eugmandel** [comment]
@sahildshah1 Thank you for posting this! Would like to understand your use case better.

Great Expectations stores validation results in the store that you configure in your project and also renders them into HTML in the Data Docs site that can be configured to be on your machine or in a shared location such as S3 or GCS. Would this be sufficient for reviewing the detailed validation results in your use case?

Also, if you would like to integrate the results into another system, please check out this thread:
https://discuss.greatexpectations.io/t/how-do-i-integrate-validation-results-into-my-dashboard/488
