### ISSUE TITLE
0.12.8 unexpressed s3fs dependency

### ISSUE THREAD

**Issue by alangenfeld** [fivetran/great_expectations#2050]
**Describe the bug**
The observed error after updating to `0.12.8` is:
```
great_expectations.exceptions.PluginModuleNotFoundError: No module named `great_expectations.datasource.batch_kwargs_generator` could be found in your plugins directory.
--
               - Please verify your plugins directory is configured correctly.
               - Please verify you have a module named `great_expectations.datasource.batch_kwargs_generator` in your plugins directory.
```

but if you import directly you can see the real issue is the new `S3SubdirReaderBatchKwargsGenerator` has a dep on `s3fs` that is not expressed in `setup.py`

```
>>> import great_expectations.datasource.batch_kwargs_generator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alangenfeld/venvs/dagenv38/lib/python3.8/site-packages/great_expectations/datasource/batch_kwargs_generator/__init__.py", line 8, in <module>
    from. s3_subdir_reader_batch_kwargs_generator import S3SubdirReaderBatchKwargsGenerator
  File "/Users/alangenfeld/venvs/dagenv38/lib/python3.8/site-packages/great_expectations/datasource/batch_kwargs_generator/s3_subdir_reader_batch_kwargs_generator.py", line 7, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
```

**To Reproduce**
I am not terribly familiar with use of great expectations - I caught this in our test suite for integration seen here:
https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-ge

**Expected behavior**
* All expected dependencies for general use should be declared in setup.py, if this isn't always required inline import and add as an install extra
* [bonus] Module loading errors are reported differently than missing plugins

**Environment (please complete the following information):**
 - GE Version: 0.12.8

**Additional context**

**Comment by eugmandel** [comment]
Thank you for reporting this - this issue was fixed in on 0.12.9
