### ISSUE TITLE
ExpectationSuiteIdentifier does not work with directories containing dots

### ISSUE THREAD

**Issue by janhicken** [fivetran/great_expectations#2055]
**Describe the bug**
In the implementation of `ExpectationSuiteIdentifier`, an expectation suite found in a subdirectory of the expectations store will be created by separating the path elements with dots. For example, an identifier for `a/b/suite.json` will result in `a.b.suite`. This behaviour is problematic, when a subdirectory contains dots, e. g. `..something/mysuite.json` will create an identifier of `..something.mysuite` which will result in an invalid path of `//something/mysuite.json` when converting it back using `.to_tuple()`

I'm currently using Great Expectations inside a Kubernetes pod, where the expectations suite files are provided as a mounted config map. The mounting of a config map results in directories containing dots, for example:

```
checkpoints/
    my.chk.yml # contains a reference to mysuite
expectations/
    mysuite.json -> ..2020_11_16_09_54_44.190043793/mysuite.json
    ..2020_11_16_09_54_44.190043793/
        mysuite.json
```

In a nutshell, this makes `ExpectationSuiteIdentifier` convert any dots in directory names to slashes in the resulting path.

**To Reproduce**
1. Create the directory structure as shown above
2. Create the suite `mysuite`
3. Create a checkpoint `my.chk.yml` including the suite `mysuite`
4. Run `great_expectations checkpoint run my.chk`

The error shown will be: 
```
Unable to retrieve object from TupleFilesystemStoreBackend with the following Key: //2020_11_16_09_54_44/190043793/mysuite.json
```

**Expected behavior**
I would expect `great_expectations checkpoint run my.chk` to work without it making dots to slashes.

**Environment (please complete the following information):**
 - OS: Linux on Kubernetes
 - GE Version: 0.12.7

**Workaround**
In my current setup, I added a workaround for the `ExpectationSuiteIdentifier`, where the dot separator is exchanged for a slash, which works fine for me.

**Comment by eugmandel** [comment]
Thank you for reporting this! We added the "help wanted" label - this is a fix we would love to get from the community.
