### ISSUE TITLE
Duplicate code in data_context.store.tuple_store_backend

### ISSUE THREAD

**Issue by philthyharry** [fivetran/great_expectations#2056]
https://github.com/great-expectations/great_expectations/blob/739f7a1c9dd20cb462635d2b85e31b1bcbce7b11/great_expectations/data_context/store/tuple_store_backend.py#L549

Lines 549-555 are a duplication of lines 540-546.

**Comment by eugmandel** [comment]
Thank you for reporting this, @philthyharry ! This might be a merge issue and does look like a straightforward code duplication.

**Comment by eugmandel** [comment]
We are managing the queue of issues to be handled by the core team pretty tightly now, so would love to get this fixed by the community. This sounds like a great easy first PR for a new community contributor.

**Comment by shril** [comment]
Hi @eugmandel, can I pick this up?

**Comment by spbail** [comment]
Phew. Finally got to merge the PR. Closing this.

**Comment by vanderGoes** [comment]
Thanks @spbail!
