### ISSUE TITLE
TypeError: profile() got an unexpected keyword argument 'configuration' when doing BasicSuiteBuilderProfiler().profile(batch, configuration="demo")

### ISSUE THREAD

**Issue by y-tee** [fivetran/great_expectations#2066]
**Describe the bug**
I get a type error when specifying configuration in BasicSuiteBuilderProfiler().profile(batch, configuration="demo") following the [documentation](https://docs.greatexpectations.io/en/latest/autoapi/great_expectations/profile/index.html?highlight=BasicSuiteBuilderProfiler#great_expectations.profile.BasicSuiteBuilderProfiler)

**To Reproduce**
1. I run `python run_test.py` in the airflow docker container of  ge_dbt_airflow_tutorial calling function
```
    def create_expectation_from_table_profiled(self, schema, table, datecolumn, startdate, enddate):
        batch_kwargs = self.context.build_batch_kwargs(
            "my_redshift_db",
            "queries",
            "query_template",
            query_parameters={
                "schema": schema,
                "table": table,
                "datecolumn": datecolumn,
                "start": startdate,
                "end": enddate
            }
        )
        suite_name="profiled_expectation_suite"

        suite = self.context.create_expectation_suite(suite_name, overwrite_existing=True)

        batch = self.context.get_batch(
            batch_kwargs=batch_kwargs,
            expectation_suite_name=suite
        )

        suite, validation_result = BasicSuiteBuilderProfiler().profile(batch, configuration="demo")

        self.context.save_expectation_suite(suite,suite_name)
```

2. The error I get: 
```
suite, validation_result = BasicSuiteBuilderProfiler().profile(batch, configuration="demo") 
TypeError: profile() got an unexpected keyword argument 'configuration'
```

**Expected behavior**

**Environment (please complete the following information):**
 - OS: iOS Catalina 
 - GE Version: requirement.txt that was triggered in docker-compose did not specify version of ge, should be the latest. 

**Additional context**
I am however able to use the profiler to generate the expectation suite if i use 
 `suite, validation_result = BasicSuiteBuilderProfiler().profile(batch, profiler_configuration="demo")` though in the [source code](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/profile/basic_suite_builder_profiler.py) the variable name is `configuration`

**Comment by eugmandel** [comment]
@y-tee Thank you for reporting this! We will triage the issue next week. I am not sure if you are in our Slack channel and saw the announcement that we are working toward finalizing the 0.13 release and might be slower than usual responding to issues next week.

**Comment by eugmandel** [comment]
BasicSuiteBuilderProfiler does not support the configuration argument. We need to clean this up. In the meantime, the workaround is to call the profile method without passing this argument.
