### ISSUE TITLE
README's Slack link invalid

### ISSUE THREAD

**Issue by raphael-riel** [fivetran/great_expectations#2067]
**Describe the bug**
The link to join the Slack Community is not valid.
![image](https://user-images.githubusercontent.com/474697/99819153-19184900-2b1d-11eb-98a1-d5e3a11d15eb.png)

**To Reproduce**
1. Click on the Slack Link in the README

**Comment by eugmandel** [comment]
Thank you for reporting this, @raphael-riel ! These links expire  - we will update with a fresh one.

**Comment by kyleaton** [comment]
Did a quick replacement with a link that will last 30 days. Going to look into a more permanent solution but setting a reoccurring task for now.

@raphael-riel THANK YOU!!!!!

**Comment by eugmandel** [comment]
Thank you @kyleaton for fixing it and, again, thanks to @raphael-riel for spotting this in time! Closing the issue.
