### ISSUE TITLE
Improve typing 

### ISSUE THREAD

**Issue by jpcampb2** [fivetran/great_expectations#207]
This is a long-term issue that will collect issues surrounding the use of types in great expectations.

Opening now to flag the coercion of boolean True/False by column_aggregate_expectations in ways that may be counterintuitive.

In general, we've talked about wanting to handle gracefully all of the following realities, while emphasizing semantic types:
 - "semantic" types, such as continuous, categorical, boolean
 - "data" types: such as number, string, boolean
 - "implementation" types: int64, int32, utf-8, etc

**Comment by abegong** [comment]
Linking #110

**Comment by abegong** [comment]
Here's how SQLAlchemy handles typing: http://docs.sqlalchemy.org/en/latest/core/type_basics.html. 

Might be a good starting point...

**Comment by jcampbell** [comment]
Improvements to "implementation" types are in place, and other type issues are currently handled by bundling expectations or custom expectations in practice.
