### ISSUE TITLE
When a docs site does exist and is not publicly accessible GE says it does not exist on docs list

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#2076]
**Describe the bug**
When a docs site does exist and is not publicly accessible GE says it does not exist on docs list. This may lead users to rebuild their sites when it is not needed.

**To Reproduce**
1. Configure a data docs site that is not publicly accessible
2. Build it
3. run `great_expectations docs list`
```

❯ great_expectations docs list
1 Data Docs site configured:
 - gcs_site: site configured but does not exist. Run the following command to build site: great_expectations docs build --site-name gcs_site
```

❯ great_expectations docs list
1 Data Docs site configured:
 - gcs_site: site configured but does not exist. Run the following command to build site: great_expectations docs build --site-name gcs_site

**Expected behavior**
A simple wording change could fix this.

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - GE Version: [e.g. 0.10.0] 0.12.7

**Comment by eugmandel** [comment]
@Aylr I agree that the imprecise wording of the error message is an issue. Do you have the exact wording in mind?
