### ISSUE TITLE
Documentation on Custom Expectations seems to be out of date

### ISSUE THREAD

**Issue by jvgagliardi** [fivetran/great_expectations#2077]
The documentation found here: https://docs.greatexpectations.io/en/v0.3.0/custom_expectations.html

makes it seem that there is a '@expectation' decorator found using 'from great_expectations.dataset import PandasDataSet, expectation' but there is no such decorator there.

I am hoping to see what the actual way to extend expectations is.

I have been going into the code and have yet to find a simple extension solution. 

Thanks

**Comment by eugmandel** [comment]
@jvgagliardi "v0.3.0" in your docs URL points to an older version of Great Expectations documentation. Please find the latest here: https://docs.greatexpectations.io/en/latest/

**Comment by jvgagliardi** [comment]
@eugmandel My mistake. Thanks for the clarification
