### ISSUE TITLE
`datasource new` overwrites existing datasources with the same name

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#2085]
**Describe the bug**
Creating a new datasource with the CLI overwrites existing datasources with the same name without warning.
 
**To Reproduce**
1. Run `great_expectations datasource new` and create a new filesystem datasource e.g. "data__dir", pointing to a directory "dir1"
2. Do the same thing again, give it the same name but point it at "dir2", and check great_expectations.yml - only the second datasource is in the yml.

**Expected behavior**
I would expect a warning or a confirmation that I'm overwriting an existing datasource.

**Environment (please complete the following information):**
 - OS: mac OS 11 (Big Sur)
 - GE Version: GE 0.13 (but I assume this exist in previous versions too)

**Comment by thcidale0808** [comment]
@eugmandel can I implement this issue?

**Comment by eugmandel** [comment]
@thcidale0808 Of course! This is why we added the "help wanted" label. Please submit a PR and we will help you get it in.

**Comment by thcidale0808** [comment]
will do! Thanks!

**Comment by alfredo-f** [comment]
It seems like function [check_if_datasource_name_exists](https://github.com/great-expectations/great_expectations/blob/b83fc816474af1dd60521104b89a64970823022b/great_expectations/cli/datasource.py#L754) has been implemented to solve this issue. 

Is this correct @anthonyburdi ?

**Comment by anthonyburdi** [comment]
That is correct, thanks for the heads up @alfredo-f !
