### ISSUE TITLE
Creating a new expectation via CLI / SQL Query throws TypeError 'missing execution_engine' error

### ISSUE THREAD

**Issue by segoldma** [fivetran/great_expectations#2093]
**Describe the bug**
Just upgraded to version 0.13.0. When creating a new expectation using the CLI, GE throws an error when I provide a SQL query as an alternative to the top 5 tables that are recommended (i.e., _Do not see the table in the list above? Just type the SQL query_)

This throws error: `TypeError: __init__() missing 1 required positional argument: 'execution_engine'`

**To Reproduce**
1. great_expectations suite edit my_suite
2. SELECT * FROM my_database.my_schema.my_table

**Expected behavior**
Launch the Jupyter Notebook with the suite editing interface for the corresponding query result.

**Environment (please complete the following information):**
 - OS: Windows
 - GE Version: [e.g. 0.13.0]

**Additional context**  

I am using the Snowflake connector, configured as described in the docs.

I was able to use this workflow without issue prior to updating to 0.13.0.

I am able to generate expectations by running `great_expectations suite edit my_suite` selecting one of the top 5 tables, and then updating the batch_kwargs in the jupyter notebook with the desired table, for what it's worth.

**Comment by eugmandel** [comment]
Thank you for reporting this, @segoldma ! We are going to address this in the next couple of days.

**Comment by Shinnnyshinshin** [comment]
@segoldma Thank you for creating this issue, and the details in reproducing the error. I've submitted a PR that will do the fix. #2099
