### ISSUE TITLE
Missing markown_text jinja template

### ISSUE THREAD

**Issue by lccambiaghi** [fivetran/great_expectations#2098]
**Describe the bug**
I am trying to render our JSON expectations to markdown. I followed a tutorial that showed how to do that for validation results but I think a jinja template is missing.

Here is the traceback:
```
~/Library/Caches/pypoetry/virtualenvs/ge-MUDrC1sS-py3.7/lib/python3.7/site-packages/great_expectations/render/view/view.py in _get_template(self, template)
    106         env.filters["add_data_context_id_to_url"] = self.add_data_context_id_to_url
    107 
--> 108         template = env.get_template(template)
    109         template.globals["now"] = lambda: datetime.datetime.now(datetime.timezone.utc)
    110 

TemplateNotFound: markdown_text.j2
```

I just hacked a template just containing:
```
{{ text | render_content_block }}
```
and it fixed the error, however the comments added to the expectations are missing!

**To Reproduce**
```
import great_expectations as ge
from great_expectations.render.renderer import ValidationResultsPageRenderer, ExpectationSuitePageRenderer
from great_expectations.render.view import DefaultMarkdownPageView
from great_expectations.validation_operators.types.validation_operator_result import (
    ValidationOperatorResult,
)

context = ge.DataContext()

def render_to_markdown(run_info_at_end, expectations):
    expectation_suite_page_renderer = ExpectationSuitePageRenderer()
    rendered_document_content_list = expectation_suite_page_renderer.render(
        expectations
    )
    return DefaultMarkdownPageView().render(rendered_document_content_list)

expectations = context.get_expectation_suite("suite-name")

render_to_markdown(True, expectations)
```

**Expected behavior**
I would expect the expectations to be rendered as markdown

**Environment (please complete the following information):**
 - OS: macOS
 - GE Version: 0.12.10

**Comment by eugmandel** [comment]
Thank you for reporting this, @lccambiaghi ! We are going to triage this issue within next couple of days.

**Comment by eugmandel** [comment]
@lccambiaghi Could you please post the link to the tutorial that you followed? Thank you!

This does look like a bug. Adding to the core team's queue.

**Comment by lccambiaghi** [comment]
I adapted the code from this util function: https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/render/page_renderer_util.py#L37

I hope the example I provided is clear enough. We have worked around it for the moment by adding the custom jinja template to a custom_views_directory (nice feature!) 

```python
custom_views_directory = "assets/jinja_templates"

def render_expectations_to_markdown(expectations):
    rendered_dcument_contents = {
        dataset_name: ExpectationSuitePageRenderer().render(expectation)
        for dataset_name, expectation in expectations.items()
    }

    markdown_rendered_documents = {
        dataset_name: DefaultMarkdownPageView(custom_views_directory=custom_views_directory).render(
            document=rendered_document_content
        )
        for dataset_name, rendered_document_content in rendered_dcument_contents.items()
    }

    return markdown_rendered_documents
```

The output of this however is badly formatted. I use the python library `mdformat` to format the markdown plus some custom `replace()` calls. Of course, I would love this functionality to be implemented upstream, maybe streamlined with the other rendering capabilities you have.

One issue with our current approach is that comments to JSON expectations are not rendered to markdown. Here is a screenshot of the result:

![Screenshot 2020-12-10 at 11 13 10](https://user-images.githubusercontent.com/15185927/101758594-cd800c00-3ad8-11eb-9d2a-5a42179c71d1.png)

I would expect the comments to be inserted within the dotted lines.

Thank you so much for looking at this!

**Comment by lccambiaghi** [comment]
Hi @eugmandel I was wondering if there had been any progress on this issue? I don't mean to rush you or anything, I am sure you have many exciting features coming that are more worthy of your time!

**Comment by rchojn** [comment]
@Aylr @eugmandel what is the status of that issue?

**Comment by Shinnnyshinshin** [comment]
Hi @gardnerdev and @lccambiaghi thank you for submitting the issue, and sorry about the delay. 

I just got assigned this issue through the Triage process. Should have something for you soon :)

**Comment by Shinnnyshinshin** [comment]
Hi @gardnerdev and @lccambiaghi I just wanted to let you know that a PR that addresses this issue has just been merged, and should be part of an upcoming release of Great Expectations. Could you try it with your current workflow and let us know if there are any additional adjustments that need to be made?
