### ISSUE TITLE
Batch Kwargs should support "database" keyword

### ISSUE THREAD

**Issue by dmateusp** [fivetran/great_expectations#2109]
**Is your feature request related to a problem? Please describe.**

We use an isolated database for great_expectations work, this is where we let GE create its temporary tables and where we write some transformed versions of table we want to QC, our credentials file looks like this:
```yaml
  database: great_expectations_db
  query:
      schema: temporary_tables
      ...
```

Now I was trying to use batch_kwargs `table` as opposed to `query`, because the table I'm trying to QC is quite big so I don't want GE to create a temporary table from it (I'm trying to run some counts).
My issue is that `batch_kwargs` allows overwriting the `schema` from the credentials but not the `database` of the "batch".

so if I had the following batch_kwargs:

```python
{
   "table": "my_big_table",
   "schema": "my_schema",
   "database": "my_database",
}
```

Currently GE ignores the "database" keyword and tries to find `great_expectations_db.my_schema.my_big_table`

**Describe the solution you'd like**

I would like a keyword `database` to be supported by `batch_kwargs` which should overwrite what is defined in credentials

**Describe alternatives you've considered**

For the time being, I could do a Snowflake Clone into the great_expectations database, or I could add another credentials entry for this specific suite.

**Comment by dmateusp** [comment]
I looked more into it and it seems like a change to the Snowflake sqlalchemy dialect would have to happen: https://github.com/snowflakedb/snowflake-sqlalchemy/blob/6615f51444c539d56ade2be08c542dd4827a70a8/snowdialect.py#L325

Schema columns are fetched for the "current database" and there doesn't seem to be a way to pass a "database" as an argument

**Comment by eugmandel** [comment]
@dmateusp Thank you for looking into this! So, looks like we cannot implement this enhancement until the dialect changes, correct?
