### ISSUE TITLE
Using a TupleFilesystemStoreBackend for validations with a TupleGCSStoreBackend for data docs builds only the index

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#2121]
**Describe the bug**
Using a TupleFilesystemStoreBackend for validations with a TupleGCSStoreBackend for data docs builds only the index

**To Reproduce**
1. Configure a local validations store
2. Configure a GCS data docs site
3. run `great_expectations docs build --yes --site-name my_gcs_site`
4. observe the resulting site has only an index.html an no other files, regardless of what was on the bucket beforehand

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - GE Version: [e.g. 0.10.0] 0.13.1, 0.12.10, apocryphal stories of this on much older versions

**Comment by eugmandel** [comment]
Triaged to be fixed by the core team.

**Comment by soundian** [comment]
I'm seeing the same issue, intermittently, with an S3 site. Watching the S3 bucket shows that the expectations, validations and static folders all have their files updated, but somewhere between this and the index file being uploaded the bucket is emptied of all files, resulting in the only file present being index.html

**Comment by anthonyburdi** [comment]
Hi @Aylr @soundian - I have been trying to replicate this issue with our latest version (0.13.8) and everything appears to be working as expected, including in a bucket with over 1000 validations. I'm going to close this issue, but please reopen if you continue to encounter this issue.

**Comment by anthonyburdi** [comment]
@Aylr @soundian I was able to replicate this issue by removing validations from my validations store. It may not be related to the intermittent issue you were experiencing, but I just wanted to bring it to your attention in case that is what was happening. See my note in issue #2384.
