### ISSUE TITLE
bare decimals in arithmetic in evaluation parameters cause a parsing error

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#2141]
**Describe the bug**
bare decimals in arithmetic in evaluation parameters cause a parsing error

**To Reproduce**
1. Write an expectation with an evaluation parameter that...
2. has a `urn` and some simple arithmetic with...
3. a bare decimal value
4. execute the expectation and note the parsing failure

```python
downstream_batch.expect_column_mean_to_be_between(
    "age",
    min_value={"$PARAMETER": "urn:great_expectations:validations:metrics.get:expect_column_mean_to_be_between.result.observed_value:column=age * .9"},
)
```

```
EvaluationParameterError: Parse Failure: Expected end of text, found '*'  (at char 128), (line:1, col:129)
Statement: urn:great_expectations:validations:metrics.get:expect_column_mean_to_be_between.result.observed_value:column=age * .9
```

**Expected behavior**
I'd expect this to parse correctly

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - GE Version: [e.g. 0.10.0] 0.13.2

**Comment by eugmandel** [comment]
@Aylr Since the feature works when a non-bare decimal is specified ("0.9" instead of ".9"), I am marking this as a "bug" with "workaround_exists". It is unlikely that the core team will get to this the near term, so adding "help wanted" label.

**Comment by makotonium** [comment]
Took a stab at the issue and created PR #2725
