### ISSUE TITLE
Ability to recognise empty string as null values in expectations

### ISSUE THREAD

**Issue by utkarshshukla2912** [fivetran/great_expectations#2147]
**Is your feature request related to a problem? Please describe.**
While identifying null values in a string column empty strings are not considered as null. 

**Describe the solution you'd like**
Add a parameter in the expectation to identifiy empty string as null values. Or create a new expectation that identifies empty string as null

**Additional context**
https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1607692753092600

**Comment by eugmandel** [comment]
@utkarshshukla2912 Thank you for submitting this issue following the Slack thread! This has come up in the past - we will dig out out previous notes and triage this.

**Comment by utkarshshukla2912** [comment]
> @utkarshshukla2912 Thank you for submitting this issue following the Slack thread! This has come up in the past - we will dig out out previous notes and triage this.

Thanks
