### ISSUE TITLE
Feature request: Ability to create a checkpoint without cli

### ISSUE THREAD

**Issue by sidhreddy** [fivetran/great_expectations#2162]
**Is your feature request related to a problem? Please describe.**
Ability to create a checkpoint without cli would greatly help

**Describe the solution you'd like**
Ability to create a checkpoint with code

**Comment by eugmandel** [comment]
@sidhreddy Thank you for creating this issue! This is absolutely fantastic timing, because we revising the Checkpoint feature is is our current active project. We will make sure that the update will satisfy this requirement.

Please watch for it in the next few weeks.

**Comment by eugmandel** [comment]
@roblim @alexsherstinsky Tagging you on this one, since you are currently working on the next rev of Checkpoints. No action required, just wanted you to be aware.
