### ISSUE TITLE
--directory flag at top level cli command

### ISSUE THREAD

**Issue by daidoji** [fivetran/great_expectations#2163]
**Is your feature request related to a problem? Please describe.**
Not a problem but an ease of use issue.  I noticed that some commands like `great_expectations suite list` take a `--directory` for the great_expectations directory (when not named `great_expectations`) that is incredibly helpful as this directory doesn't necessarily need to be named that.  However, its hard to know which commands take this flag and many of the default commands fail when the great_expectations directory isn't named `great_expectations`.  

**Describe the solution you'd like**
It would be nice if `--directory` or even better `--ge-location <vfs_loc>` so that this could be stored anywhere and passed just once at the top level cli command when the directory name changes.  ie) `great_expectations --directory <ge_parent_directory_location> GE_COMMAND [OPTIONS]` so that the defaults would all work without needing to pass --directory to the end of each of them.

**Describe alternatives you've considered**
The workaround is just to pass the flag at the end of the commands as is currently supported.  This would just be an ease of use thing since the directory stays where it is most of the time.

**Additional context**

**Comment by eugmandel** [comment]
@daidoji This is a great suggestion! We applied the "help wanted" label inviting a community PR.

**Comment by spbail** [comment]
https://github.com/great-expectations/great_expectations/issues/2163

**Comment by anthonyburdi** [comment]
Hi @daidoji we are updating our CLI for our new API and are incorporating your suggestion! We will have a global `--config` or `-c` parameter that takes a filepath or a directory path e.g. `great_expectations --config /my/path/to/great_expectations.yml suite list`. Keep your eyes peeled for a release with this functionality in the coming weeks!
