### ISSUE TITLE
Update requests requirement

### ISSUE THREAD

**Issue by valedtn** [fivetran/great_expectations#2180]
**Describe the bug**
Impossible to install GE on Google Cloud Composer environment together with latest Apache-Beam version

**To Reproduce**
1. set up composer environment
2. install pypi packages: 
   - apache-beam[gcp]==2.25.0
   - great_expectations==0.13.2

**Expected behavior**
Being able to install GE on composer environment

**Environment:**
 - Composer version: composer-1.13.0-airflow-1.10.12
 - GE Version: 0.13.2

**Additional context**
ERROR: apache-beam 2.25.0 has requirement requests<3.0.0,>=2.24.0, but you'll have requests 2.23.0 which is incompatible

**Comment by eugmandel** [comment]
Thank you for following up on our Slack conversation and posting this issue! We will look into it and see what is a good solution for this incompatibility.

**Comment by marhoy** [comment]
I would also be happy if you stopped requiring requests to be <2.24.0.
Please try with only:
```
requests>=2.20
```
and see if that causes any problems.

**Comment by spbail** [comment]
This was addressed in #2020. Feel free to reopen the issue if this isn't fully solved!
