### ISSUE TITLE
URL related to missing substitution variable error is leading to nowhere

### ISSUE THREAD

**Issue by felipebormann** [fivetran/great_expectations#2208]
**Describe the bug**
I created an expectation which uses environment variables to replace it's content. 
When the environment variable is missing the following error appears:

Unable to find a match for config substitution variable: `GCP_PROJECT`.
Please add this missing variable to your `uncommitted/config_variables.yml` file or your environment variables.
See https://great-expectations.readthedocs.io/en/latest/reference/data_context_reference.html#managing-environment-and-secrets

**To Reproduce**
1. Create a datasource and parametrize it using a environment variable
2. Create an expectation using said datasource
3. Run the expectation

**Expected behavior**
That the link used to guide the user is a valid one in the docs.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - GE Version: 0.13.3

**Comment by eugmandel** [comment]
@felipebormann Thanks for spotting this! Would you like to submit a PR that replaces the out of date URL with the correct one?

**Comment by felipebormann** [comment]
Yes, for sure :) Will do, I am still trying to make the  `pip install requirements-dev.txt` finish on my machine though. But I would like to close this issue too
