### ISSUE TITLE
Consider adding friendly names to great expectations

### ISSUE THREAD

**Issue by schrockn** [fivetran/great_expectations#221]
It would be useful for great expectations to have a friendly name synthesized from the contents of the expectation.

Eg the expectation produced by expect_column_to_exist('foo')

could have the friendly name

"expect_column_to_exist.foo" or something.

This would serve as a unique key to identify an expectation. It would be useful both for APIs like

df.remove_expectation("expect_column_to_exist.foo")

as well as for use cases like logging.

I'm running into the need for this while building a pipeline runner utilizing ge.

**Comment by schrockn** [comment]
cc: @abegong

**Comment by jpcampb2** [comment]
This also reminds me of #16, @schrockn, though it hadn't risen to the top of the queue. Any chance you've got an example implementation you'd point to?

**Comment by schrockn** [comment]
Nope! No example implementation. I could demo the runner I am working on to show you the exact use case. Feel free to email me at schrockn@gmail.com if you want to chat.

**Comment by abegong** [comment]
If you want to demo the runner, that could be a good fit for #104, (even if the runner isn't actually technically really Airflow.)
