### ISSUE TITLE
NameError: name 'AsyncGenerator' is not defined

### ISSUE THREAD

**Issue by sharath-quotient** [fivetran/great_expectations#2213]
**Describe the bug**
I am using Python version 3.6.0. When I run `great_expectation init` command, I am getting `NameError: name 'AsyncGenerator' is not defined` error.

**To Reproduce**
1. Install great expectations
2. Run command `great_expectation init`

**Environment (please complete the following information):**
 - OS: macos
 - GE Version: 0.13.4
 - Python version: 3.6.0

**Comment by eugmandel** [comment]
@sharath-quotient Thank you for reporting this. I don't think this is specific to Great Expectations. Please see this issue on Python's project: https://github.com/python/typing/issues/530

Closing this issue, please reopen if you have a comment.
