### ISSUE TITLE
data docs columns shrink to 1 character width with long query

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#2214]
**Describe the bug**
data docs columns shrink to 1 character width with long query

**To Reproduce**
1. make a batch from a long query string
2. run validation
3. render result to data docs
4. See screenshot
<img width="1525" alt="Data_documentation_compiled_by_Great_Expectations" src="https://user-images.githubusercontent.com/928247/103230647-30eca500-48f3-11eb-872c-720af9870bd0.png">

**Expected behavior**
I expect the columns to be readable and shrink only to a minimum width.

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - GE Version: [e.g. 0.10.0] 0.13.4

**Comment by eugmandel** [comment]
Most likely, applying CSS min-width property should improve this behavior. Figuring this out and testing it is a great opportunity for a first time community contributor - applied "good first issue" label.

**Comment by cdkini** [comment]
@eugmandel  @Aylr can I submit a PR to close this down?

**Comment by Aylr** [comment]
@cdkini Yes please!

**Comment by talagluck** [comment]
I'm going to close this, as I don't think it's relevant any longer, but please feel free to re-open if it's still an issue!

**Comment by mkopec87** [comment]
> I'm going to close this, as I don't think it's relevant any longer, but please feel free to re-open if it's still an issue!

It's still open, @talagluck maybe you can indeed close it to avoid confusion?

**Comment by milithino** [comment]
@eugmandel @Aylr can i go head in this issue or was fixed in other PR?

**Comment by austiezr** [comment]
Closing this out as above! 🙇
