### ISSUE TITLE
Expectation `expect_column_distinct_values_to_contain_set` does not report partial unexpected list

### ISSUE THREAD

**Issue by vkostyuk** [fivetran/great_expectations#2221]
**Describe the bug**
Expectations 

- `expect_column_distinct_values_to_be_in_set`
- `expect_column_distinct_values_to_contain_set`
- `expect_column_distinct_values_to_equal_set`

do not report partial unexpected values, making data issue diagnosis more laborious than need be.

**To Reproduce**
```
import great_expectations as ge
import pandas as pd 

test_df = ge.from_pandas(pd.DataFrame({"a": [1, 2]}))
test_df.expect_column_distinct_values_to_contain_set("a", [1, 5])
```

**Expected behavior**
Results should include that 5 is missing, but they do not.

**Additional context**
Currently, this seems to be a design issue. These expectations are grouped under "Aggregate functions" with other expectations that should not produce partial unexpected list in the results. For these three expectations, however, this design decision does not make sense.

**Comment by eugmandel** [comment]
@vkostyuk The way these aggregate expectations show how the data violates your expectation is by putting "observed_value" in the validation result. This way you can compare the expected set against the observed set:

![image](https://user-images.githubusercontent.com/80363/103585341-bf36cd00-4e97-11eb-9d1f-6bfd1fbaacb1.png)

It is a design decision and these always depend on personal preferences. Same test can be sometimes expressed both using the aggregate language and the mapping one. For example, expect_column_values_to_be_in_set and expect_column_distinct_values_to_be_in_set. The only difference between these two expectations is that the first one has the partial unexpected list in its result object.

**Comment by vkostyuk** [comment]
@eugmandel Thanks for the reply: indeed, it's a valid design decision. However, there's no mapping counterpart to `expect_column_distinct_values_to_contain_set`. E.g., in my use case, I need to validate that a column contains a complete ranking of 1 to 100000. I.e,. each integer appears at least once as a value, but the column can contain other values as well.

In case of 3 categories, as in your example, it's visually clear which one is missing. But with 100000 categories, and an observed list of comparable length, it's not.

**Comment by eugmandel** [comment]
@vkostyuk That's a really good point - these aggregate expectations can benefit from having a "column mapping" counterparts.
