### ISSUE TITLE
Switch travis to use pytest instead of unittest

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#223]
Our docs say `pytest`, and it's included in `requirements-dev.txt.` But it's not being used by travis.

Might be good to do this at the same time as dockerizing tests: https://github.com/great-expectations/great_expectations/tree/dockerized-tests

**Comment by jpcampb2** [comment]
This is done in the current feature/refactor-tests branch, soon to be merged.

**Comment by abegong** [comment]
https://gph.is/1fhC1qr

**Comment by jpcampb2** [comment]
Closed with recent PR #224
