### ISSUE TITLE
DataContext scans through all datasources even if only one is being used

### ISSUE THREAD

**Issue by Shinnnyshinshin** [fivetran/great_expectations#2241]
**Describe the bug**
When creating an Expectation suite with a datacontext that contains multiple datasources, GE will create connections to all datasources, even if only one is being used. 

**To Reproduce**

1. The following GE DataContext contains 2 Datasources that are connections to databases: one to a locally run postgres database (`my_postgres_db`) and one to a Redshift database (`my_redshift_db`). The postgres database is not actively running, but the configuration still exists.

`Select a datasource
    1. ge_data__dir
    2. my_postgres_db
    3. my_redshift_db
: 3`

2. Create an Expectation Suite and open the notebook to Edit Expectation Suite. 

![Screen Shot 2021-01-07 at 10 49 11 PM](https://user-images.githubusercontent.com/25670697/103983740-a8fc6b80-513a-11eb-93d8-4d7b5d10d6f5.png)

* Notice that `batch_kwargs` only contains a reference to `my_redshift_db`. 

3.  When the above code is run we get the following error about `my_postgres_db`

`DatasourceInitializationError: Cannot initialize datasource my_postgres_db, error: Cannot initialize datasource my_postgres_db, error: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5433?

(Background on this error at: http://sqlalche.me/e/13/e3q8)
`

**Expected behavior**
`context.get_batch()` should only initialize the `my_redshift_db` datasource and ignore the connection to postgres since it is not configured in `batch_kwargs`

**Environment (please complete the following information):**
 - OS: Mac OS 11.0.1
 - GE Version: 0.13.4

**Comment by eugmandel** [comment]
Added "core-team-priority" label.

**Comment by Shinnnyshinshin** [comment]
fixed in #2250
