### ISSUE TITLE
Allow construction of ge dataframe from arbitrary pd dataframe

### ISSUE THREAD

**Issue by schrockn** [fivetran/great_expectations#225]
Right now it appears that the way to convert an existing pd dataframe to a ge dataframe is the internal function `_convert_to_dataset_class`. It would be nice if there was a fully supported way to do this in the public api. That way ge would not have to replicate all pandas factory methods as well as other use cases.

`df = ge.from_pandas_dataframe(pd.read_sql_table('column_name', engine))`

for example would be nice.

**Comment by schrockn** [comment]
Some like this:

```diff
diff --git a/great_expectations/__init__.py b/great_expectations/__init__.py
index 313d227..f5b93d6 100644
--- a/great_expectations/__init__.py
+++ b/great_expectations/__init__.py
@@ -22,17 +22,22 @@ def read_csv(
     *args, **kwargs
 ):
     df = pd.read_csv(filename, *args, **kwargs)
+    # Instantiate the new DataSet with default expectations
+    try:
+        df = _construct_from_df(df, dataset_class, expectations_config)
+    except:
+        raise NotImplementedError("read_csv requires a DataSet class that can be instantiated from a Pandas DataFrame")
+    return df
+
+def _construct_from_df(df, dataset_class, expectations_config):
     if expectations_config is not None:
         # Cast the dataframe into the new class, and manually initialize expectations according to the provided configuration
         df.__class__ = dataset_class
         df.initialize_expectations(expectations_config)
+        return df
     else:
-        # Instantiate the new DataSet with default expectations
-        try:
-            df = dataset_class(df)
-        except:
-            raise NotImplementedError("read_csv requires a DataSet class that can be instantiated from a Pandas DataFrame")
-    return df
+        return dataset_class(df)
+
 
 # Removed. Preferred solution will be to use ge.dataset.PandasDataSet(df) instead.
 # def df(df, dataset_config=None, *args, **kwargs):
@@ -41,5 +46,12 @@ def read_csv(
 #
 #     return df
 
+def from_pandas(df, expectations_config=None):
+    return _construct_from_df(
+        df,
+        dataset.pandas_dataset.PandasDataSet,
+        expectations_config
+    )
+
 def expect(data_source_str, expectation):
     raise NotImplementedError
```

**Comment by abegong** [comment]
?

Bit confused by that last trace.

I'm totally open to a PR with something like `from_pandas` in it.

**Comment by schrockn** [comment]
Cool.

Last thing was just a rough diff of what it would look like.

**Comment by abegong** [comment]
Gotcha. Yes, a PR for `from_pandas` would be awesome.

I'm not sure how that pattern will generalize to SQLAlchemy, etc., but I don't think we should worry about that yet.

**Comment by schrockn** [comment]
I think you'd want to mimic the pandas top-level APIs for sure.

e.g. 

```python
engine = get_your_sql_engine()
ge.read_sql_table('some_table', engine)
ge.read_sql('SELECT * from table', engine)
```

**Comment by abegong** [comment]
I'm not so sure.

That pattern totally makes sense for loading data into pandas.DataFrames---but if the data is on remote SQL, that'll require a lot of IO.

I'm guessing that people will also want to be able to apply Expectations directly in SQL, using the `SQLAlchemyDataSet` class.

"Take the compute to the data."

**Comment by jpcampb2** [comment]
Re: the very top of this issue...have you tried `ge.dataset.PandasDataSet(df)`? That should already work out of the box, and is how I often construct datasets. I actually had a from_dataframe helper originally, and dropped it in favor of that constructor. Improved documentation sounds valuable, assuming that makes sense.

Re: the top-level API, I think there are two sort of different things that are getting conflated.

1. I agree with @schrockn that implementing read_sql makes sense...it should just exactly mimic the pandas read_sql (in the same way we've got parity now with read_csv and read_json).

That would look like:
```
engine = get_your_sql_engine()
my_pandas_dataset = ge.read_sql('select * from table', engine)
```
(basically, just calling https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql.html)

(of course, even today you could do:
```
engine = get_your_sql_engine()
my_pandas_dataframe = pd.read_sql('select * from table', engine)
my_pandas_dataset = ge.dataset.PandasDataSet(my_pandas_dataframe)
```

2. That said, I think in many cases (e.g. with large datasets) you're still going to want to follow the pattern wherein you are actually using a SqlAlchemyDataset:
```
engine = get_your_sql_engine()
my_sql_context = get_data_context('sql', engine)
my_sqlalchemy_dataset = my_sql_context('my_table')
```

**Comment by schrockn** [comment]
Ah ok I can just use ge.dataset.PandasDataSet for now. I was just using this in a notebook context and the convenience seemed nice. No additional imports and better discoverability. However this is no big deal at all and i'm happy to close this as resolved.

**Comment by jpcampb2** [comment]
Good we've got a workaround, but I agree a clearer API would be nice. I'm going to leave this open pending finalizing the data context api points now that we have a sqlalchemydataset at least partially implemented that we can work from.

**Comment by abegong** [comment]
For my money, I'd love to see @schrockn merge his `from_pandas` proposal and use it for a while.

It's an immediately useful change, and the working experience would be useful for informing the "right" API down the road.

**Comment by nobbyhawk** [comment]
> For my money, I'd love to see @schrockn merge his from_pandas proposal and use it for a while.

I agree with @abegong.  As a new user, the existing API was not clear/discoverable, I think this would be very beneficial for new users in exploring GE even if this isn't a final solution.

**Comment by zack3241** [comment]
+1 to getting this into the package or at least documenting very clearly that ge.dataset.PandasDataSet(df) will do this for you. I love the idea of pulling in great expectation's easy ability to apply testing to data, less enthused about the fact that it looked like I could only import my data either through a CSV or JSON. I feel like this is probably an incredibly common vector for data coming into GE, so I wouldn't want to force everyone to dig into the issues on github to find this (although I guess you only need to do it once).

**Comment by schrockn** [comment]
https://github.com/great-expectations/great_expectations/pull/230
