### ISSUE TITLE
Scaffolding does not work when comma is in column

### ISSUE THREAD

**Issue by rchojn** [fivetran/great_expectations#2268]
**Describe the bug**
When trying to run scaffolding (profiling) command, it fails because of commas in columns.

**To Reproduce**
1. Run `great_expectations suite scaffold scaffold-name` on datasource where commas are in column 
2. Bug `pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 5323 saw 2`

**Expected behavior**
Data profiling is working with choosen separator ($, /t) eventhough there are commas in columns

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.4

**Comment by eugmandel** [comment]
@gardnerdev Thank you for reporting this! This is indeed a bug. We are inviting the community to submit a fix if we do not get to this first.

**Comment by eugmandel** [comment]
@gardnerdev When you are reading your file with Pandas directly (without using Great Expectations), are you passing some extra arguments to read_csv (encoding?). If yes, you can pass the same arguments through by adding them under "reader_options" key in batch_kwargs.

**Comment by rchojn** [comment]
@eugmandel yes, I know "reader_option" option. Encoding is not needed in that scenario. Would be great for scaffolding to support commas in column and not treat it as additional column which generates error. Maybe it's because of GE is underneath using comma as separator for column?

**Comment by scouvreur** [comment]
Hi @eugmandel - do you mind if I open a PR to try and fix this issue ?

**Comment by eugmandel** [comment]
@scouvreur Of course - please go ahead!

**Comment by scouvreur** [comment]
@gardnerdev Could you provide a minimal dataset where you face this issue ? You can remove any PII or sensitive information as long as your sample produces the behaviour.
