### ISSUE TITLE
Add a concept of partitions, so that expectations can be applied to portions of tables.

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#227]

**Comment by jpcampb2** [comment]
👍 

Would also be nice to in general support referencing the partition point from meta.

**Comment by abegong** [comment]
Interesting. I can think of a few different ways to define partitions:

`where(my_timestamp_or_unique_incremental_index > some_value)`
`where(my_batch_id == some_value)`
`where(CAST(my_timestamp AS DATE) == some_date)`
`where(ROUND(my_unique_incremental_index/some_batch_size) == some_date)`
