### ISSUE TITLE
Add the option for a transformation hook for PandasDataset

### ISSUE THREAD

**Issue by jstammers** [fivetran/great_expectations#2312]
**Is your feature request related to a problem? Please describe.**
There are occasions where I would like to validate a subset of a dataset. If the data are stored in a database, then this is straightforward as I can generate a batch of data by transforming the data source using the `query` keyword argument, for example
```python
batch_kwargs = {
"datasource":"my_db",
"data_asset_name": "my_data_asset",
"query": "SELECT * FROM my_table where col = condition"
}
```
However if the data source is a file then there is no equivalent method for creating a batch after transforming the data. In order to do this, I would have to first transform the data and save them as two separate files
```python
def transform(df):
    return df.groupby('x').sum()

df = pd.DataFrame({'x':[1,1,2,3,4], 'y':[1,2,3,4,5]})
transformed_df = transform(df)

df.to_csv('data.csv')
transformed_df.to_csv('transformed_data.csv')

batch_kwargs = {
"datasource":"local",
"data_asset_name":"my_data",
"file":"data.csv"
}

batch_transform_kwargs = {
"datasource":"local",
"data_asset_name":"my_data",
"file":"transformed_data.csv"
}
```
**Describe the solution you'd like**
Rather than requiring two separate files, it would be simpler to apply the transformation after loading the data, for instance
```python
batch_kwargs = {
"datasource":"local",
"data_asset_name":"my_data",
"file":"data.csv",
"hook":transform
}
```

So that after loading the data from the specified file, the function defined by `batch_kwargs["hook"]` is applied to it.
I can foresee issues with this when trying to apply functions that take additional arguments that cannot be serialised to JSON.
Perhaps this should be restricted to unary functions

**Describe alternatives you've considered**
As described above, I have used the method of saving two files and operating on them separately, but I would like to avoid repeating myself wherever possible

**Comment by eugmandel** [comment]
@jstammers Are you validating this data within some data pipeline code? If yes, it might be easier to add a step to your pipeline that transforms the original data and submits it for validation as a Pandas df.

If you are running GE on the files as its own script (not within some pipeline code), I'd love to discuss this further.

**Comment by jstammers** [comment]
@eugmandel In my case, I am running it within a script as I am using GE to validate the output of a model. The workflow I have is similar to the following
```python
input_data = load_data()

model = load_model()

results = model.predict(input_data)

transformed_results = transform(results)

results.to_csv('results.csv')

transformed_results.to_csv('transformed_results.csv')

validate_data() #runs checkpoint on 'results' and 'transformed_results'

upload_data(results) #uploads if validations are successful
```

In actual fact, I have a few transformations of my results that I would like to validate against, but I think this illustrates the process. I'm also happy to discuss this further if that would help
