### ISSUE TITLE
ExpectColumnValuesToBeBetween validate_configuration disregards parse_strings_as_datetimes 

### ISSUE THREAD

**Issue by LavinaVRovine** [fivetran/great_expectations#2341]
Assertion
https://github.com/great-expectations/great_expectations/blob/ddb6a090ce792ed3144ac4e448a29dfef67fbb6c/great_expectations/expectations/core/expect_column_values_to_be_between.py#L137

fails, when string DateTime is provided.

**Comment by eugmandel** [comment]
@LavinaVRovine Good catch! Would you like to submit a PR with a fix? It would be super helpful!

**Comment by victorwyee** [comment]
Took a quick look at this. Looks like https://github.com/great-expectations/great_expectations/blob/ddb6a090ce792ed3144ac4e448a29dfef67fbb6c/great_expectations/expectations/core/expect_column_values_to_be_between.py#L122 is duplicating code from https://github.com/great-expectations/great_expectations/blob/ddb6a090ce792ed3144ac4e448a29dfef67fbb6c/great_expectations/expectations/expectation.py#L1068 It looks like many other expectations use this. So this issue might affect other column aggregate interval expectations?

Would be happy to look further and propose a fix, unless @LavinaVRovine would like to take this?

**Comment by victorwyee** [comment]
Took a closer look but wasn't able to reproduce @LavinaVRovine's issue...

**Comment by victorwyee** [comment]
Well, never mind. Didn't test the right thing earlier. PR updated.

**Comment by victorwyee** [comment]
@eugmandel -- I think this issue can be closed now. :)
