### ISSUE TITLE
Getting started example failing with config version 3.0

### ISSUE THREAD

**Issue by tsitsimis** [fivetran/great_expectations#2358]
**Describe the bug**
Hi,
I made a fresh install of latest ge version (0.13.8) and followed the [getting started example](https://docs.greatexpectations.io/en/latest/guides/tutorials/getting_started/create_your_first_expectations.html). After I run the `scaffold` command and run the jupyter notebook, the last cell "Save & review the scaffolded Expectation Suite" throws an error at `results = context.run_validation_operator("action_list_operator", assets_to_validate=[batch])`

**Error message**:  
`DataContextError: No validation operator `action_list_operator` was found in your project. Please verify this in your great_expectations.yml`

**To Reproduce**
1. Clone the tutorial `git clone https://github.com/superconductive/ge_tutorials` and start postgres container
2. Initialize a new expectations project `great_expectations init` following the steps at the [tutorial docs](https://docs.greatexpectations.io/en/latest/guides/tutorials/getting_started/initialize_a_data_context.html)
3. Run the `scaffold` command `great_expectations suite scaffold taxi.demo` and execute notebook cells
4. See error at last cell

**Environment (please complete the following information):**
 - Operating System: Windows, Python 3.8.0
 - Great Expectations Version: [0.13.8]

**Additional context**
If I manually add the `action_list_operator` in `great_expectations.yml` as shown at the [Github example](https://github.com/superconductive/ge_tutorials/blob/ad93033d0ecf99d35834dafccfacf32bc9adfb9e/ge_getting_started_tutorial/great_expectations/great_expectations.yml#L40) the notebook cell is executed but then when I run a new checkpoint it shows a deprecation message: 
`You appear to be using a legacy capability with the latest config version (3.0).
    Your data context with this configuration version uses validation_operators, which are being deprecated.  Please update your configuration to be compatible with the version number 3.`

I couldn't find any similar issue. Thank you!

**Comment by eugmandel** [comment]
Thank you for reporting this, @tsitsimis ! The core team will update this tutorial to be compatible with the new APIs.

**Comment by l00173745** [comment]
May I know any update on this issue ? as i encounter same issue too

**Comment by tsitsimis** [comment]
By the way, the tutorial works normally on version 0.13.7

**Comment by MatteoFelici** [comment]
I have the same problem with my personal project, since the `results = context.run_validation_operator("action_list_operator", assets_to_validate=[batch])` is included in every suite notebook, not only in getting started.
Is it ok for now to add the `action_list_operator` in `great_expectations.yml`, even if it's deprecated?

**Comment by spbail** [comment]
We're actively working on this, will update on #2418! Thanks everyone who reported this.
