### ISSUE TITLE
Multi-Column Expectations for Uniqueness

### ISSUE THREAD

**Issue by zack3241** [fivetran/great_expectations#236]
Hi! I saw that on your road map that you had included ideas around multi-column expectations, but was wondering if there was any discussion on how this might be implemented. I know specifically I'd love to have an expectation that identifies records in a DataFrame which violate unique constraints (sorry for the SQL terms) for a set of columns. Really looking to see if I can help contribute but couldn't find a mechanism for these types of discussion outside of the issues in github, and given its on your road map, I imagine considerations have already been made. While the use case I have is specific, I feel like there are broad implications across expectations as a general concept seeing as extending the existing expectations right now is limited to a single column. In terms of ETL as a data engineer, multi-column assertions is an incredibly common workflow for me/my team.

FYI, great presentation at STRATA.

**Comment by abegong** [comment]
Thanks!

Let me see if I understand the use case. You're looking for something like `[expect_column_values_to_be_unique](http://great-expectations.readthedocs.io/en/latest/dataset_module.html#great_expectations.dataset.base.DataSet.expect_column_values_to_be_unique)`, except you'd like to check for uniqueness across multiple columns.

Something like this...?

```
(1,"A") - unique
(2,"B") - not unique
(3,"A") - unique
(2,"A") - unique
(2,"B") - not unique
(3,"B") - unique
```

Is that right?

**Comment by jpcampb2** [comment]
@zack3241 Thanks! I definitely agree, and multicolumn relations are on the short list of things that we want to bring into great_expectations. We'd love your input on the best design.

The ability to express uniqueness constraints is certainly a key pattern there.

One thing that I think we'd consider as an option for that is to write expectations against a "check" dataset (and, for example, map the constraint condition into a single column in that dataset, where expect_column_proportion_of_unique_values_to_be_between can be used).

Also check out discussion in:  #79, #80, #194

**Comment by zack3241** [comment]
@abegong yeah you nailed it completely albeit extended beyond just two columns. My experience with helping Data Scientists map data into a SQL data warehouse is that the SQL errors kicked backed when inserting data when using pandas can be obtuse (e.g. it usually reports the error from the database rather than something that is intelligible to the user that is working with the data frame). Identifying the issue with the pandas.DataFrame being inserted into the table can be really hard at least in terms of what is violating those expectations which is why I think this package has a lot of potential. As someone manages the database (I know a lot of roles), I always apply a unique constraint to the data in almost every table/situation that I can to ensure data integrity. I was hoping to reflect the expectations from a table into GE and then apply them to data that I would insert via our data pipelines.

(Forgive me if I've misinterpreting this @jpcampb2) To @jpcampb2 's point, I thought about creating a compound column from the columns and then checking uniqueness about that column. The problem with that is that there is no guarantee about the data types of column and how those combine into a single column. I've struggled with type conversions in pandas, especially around datetime time zone aware values. It could work in most cases, but would probably be more of hack around a problem than a true solution. I'll have to look into the issues you identified @jpcampb2. I feel (or hope) most of the basic expectations (not the more advanced statistical measures which make this package awesome) could easily be applied to multiple columns. In terms of larger scale data, I also don't love restoring existing data into another column, however transient.

Anyway, I did this specific thing already with interface I'm building for ETL into the DB with pandas aggregations and custom error raising (which as a fan of the package I'd like to avoid).  I should do some benchmarking around different methodologies to figure out the fastest way to identify the duplicate column sets for this specific use case. Basic methodology was to group by the unique columns and filter to those with a size greater than one. Seemed like a quicker way to identifying the offending records than the elasticsearch style return all the records and the aggregations together, though I may be a little biased against that approach.

**Comment by abegong** [comment]
This makes a lot of sense.

If you're up for it, I'd love to figure out a path to add an `expect_multicolumn_values_to_be_unique` method. I see two steps

1. Define a `@multicolumn_map_expectation` decorator
2. Implement `expect_multicolumn_values_to_be_unique` using that decorator.

Step 1 is probably the harder step, but hopefully not too hard. PR #173 does something similar for column pairs. The `@column_pair_map_expectation` in that PR would be a good starting point for a multicolumn decorator.

We'd also need to put some thought into the API for multicolumn expectations. My first reaction is to have them accept a `columns` parameter containing a list of column names, but other approaches could make sense, too...

Last, I'd advocate for doing this just in pandas to start with---sqlAlchemy can come later, and there's no reason to overcomplicate things to start.


@zack3241 LMK if this is something you'd like to take a crack at. I expect to get around to it eventually, but I do have some other features/fixes that I need to knock out first.

PS: reflecting expectations from DB schemas is a really cool use case. I'd love to explore that further.

**Comment by zack3241** [comment]
@abegong, I'd like to give it a shot, but I don't think I'll necessarily have the time until maybe about 2 weeks from now.

Just some design thoughts I wanted to put somewhere:
In terms of the API, I thought it might be nice to have the ability to have all expectations get handed **either** a list of strings or a single string and then handle it appropriately rather than having a completely separate API for multiple columns which does the same thing. That would simplify the interface for some expectations and make it easier to apply them, but may make it difficult to understand in terms of actually **what** the expectation would do. It would be straightforward with some of the value checking expectations, you just apply the same expectation to every column. But that sets up the interface that looks like you can apply multiple expectations at once in some cases but not in others, given that the unique constraint would be apply across columns not to each columns. I think you're right that we want to make it an explicit API, so the design and tasks you outlined make sense to me. 

Re: DB Reflection. I totally agree. I'll make another issue regarding that when I get some more time.

**Comment by rlshuhart** [comment]
Just a vote. I would find multi-column uniqueness useful as well.

**Comment by aiguofer** [comment]
I was around looking to see if there's a way to check the cardinality of the relationship between two columns and found this. In a way, "multi-column uniqueness" is synonymous with a 1-to-1 constraint.

I'd love to have a way to check data to ensure that joins don't create any unexpected row duplicates due to 1-many, many-1, or many to many relationships that may unknowingly exist between 2 columns.

Does this seem like a potential place to be added?

**Comment by anthonyburdi** [comment]
@zack3241 @rlshuhart @aiguofer please check out PR #1822 for the new expectation `expect_compound_columns_to_be_unique` as it may help with some of your use cases. 

We also deprecated `expect_multicolumn_values_to_be_unique` and renamed it to `expect_select_column_values_to_be_unique_within_record` to better describe what that expectation was doing.

**Comment by andymiller-og** [comment]
> @zack3241 @rlshuhart @aiguofer please check out PR #1822 for the new expectation `expect_compound_columns_to_be_unique` as it may help with some of your use cases.
> 
> We also deprecated `expect_multicolumn_values_to_be_unique` and renamed it to `expect_select_column_values_to_be_unique_within_record` to better describe what that expectation was doing.

Is this not available in the latest v3 version?

**Comment by anthonyburdi** [comment]
> > @zack3241 @rlshuhart @aiguofer please check out PR #1822 for the new expectation `expect_compound_columns_to_be_unique` as it may help with some of your use cases.
> > We also deprecated `expect_multicolumn_values_to_be_unique` and renamed it to `expect_select_column_values_to_be_unique_within_record` to better describe what that expectation was doing.
> 
> Is this not available in the latest v3 version?

Thanks for your interest! The team is currently working on porting additional expectations to v3, look for releases in the near future on this and other expectations. cc: @spencerhardwick

**Comment by krithikabalu** [comment]
Can you tell the status on this "expect_select_column_values_to_be_unique_within_record"? I am also needing this in v3
