### ISSUE TITLE
scafold_taxi.demo missing from tutorial

### ISSUE THREAD

**Issue by mxlei01** [fivetran/great_expectations#2383]
Not sure if this is a bug, but I'm working through the tutorial, but I don't see the scafold_taxi demo ipynb anywhere to be found in [link](https://docs.greatexpectations.io/en/latest/guides/tutorials/getting_started/create_your_first_expectations.html)?

Also the command `great_expectations suite scaffold taxi.demo` also doesn't work with taxi.demo being existed already inside the repository?

**Comment by spbail** [comment]
Hi @mxlei01, thanks for submitting this issue! We had a few issues regarding the tutorial, so will tackle an update as soon as possible.

**Comment by spbail** [comment]
Hi @mxlei01 also for clarification:
1. You should be running all `great_expectations` commands in a *new* directory (we named it `ge_example` in the tutorial), that way you don't have clashes with the existing solution. [See the instructions on the first page of the tutorial.](https://docs.greatexpectations.io/en/latest/guides/tutorials/getting_started/initialize_a_data_context.html#create-a-data-context)
2. When running `great_expectations suite scaffold taxi.demo` this should automatically open a new Jupyter notebook for you. I'm unsure why this does not work for you. Please check whether jupyter is installed. You should be seeing the jupyter output in the same terminal where you run the CLI command.

You should be able to run the above steps with the current version of the tutorial. We are working on fixing some issues in the "Validation" steps, see #2358. But it looks like your issues are unrelated.

**Comment by mxlei01** [comment]
@spbail 

Thanks for the reply!

1. Seems that I'm not following the instructions carefully.
2. I'm running the commands through SSH, so maybe that's why there was no jupyter notebook?

Max
