### ISSUE TITLE
Mismatch between unexpected_percent and unexpected_percent_nonmissing in expect_column_values_to_not_be_null

### ISSUE THREAD

**Issue by jpcampb2** [fivetran/great_expectations#239]
This seems confusing, if my statement is 'not null' how can these numbers be different?  
```
'exception_percent': 0.35288888888888886,
'exception_percent_nonmissing': 0.5453296703296703,
```

(yes, this is from 0.3.2, not from develop)

**Comment by abegong** [comment]
I think this was a bug in `expect_column_values_to_be_not_null` that has since been fixed.

Not certain, though.

**Comment by ccnobbli** [comment]
This issue persists.

Weird things happen when number of null values > number of non-null values
It returns a ratio greater than 1

```
Currently:
            if nonnull_count > 0:
                **unexpected_percent_nonmissing = float(unexpected_count) / nonnull_count**
            else:
                unexpected_percent_nonmissing = None
```

**Comment by ccnobbli** [comment]
Unexpected_count should be 0.

I forgot to mention this happens in _format_column_map_output. The problem is that it never checks whether the `unexected_list` contains `None` values. In the case of this expectatation, that is all of the values.

**Comment by jpcampb2** [comment]
Thanks, @ccnobbli !
