### ISSUE TITLE
Need to enforce conda env Python version to 3.7 in the developer setup docs to install dependencies

### ISSUE THREAD

**Issue by scouvreur** [fivetran/great_expectations#2390]
**Describe the bug**
In the developer docs, when using conda to setup a new environment, if the python version is not enforced to 3.7 as so : `conda create --name great_expectations_dev python=3.7` conda raises some issues related to incompatibility with several packages, including `boto3`.

Source [here](https://github.com/great-expectations/great_expectations/blob/develop/docs/contributing/setting_up_your_dev_environment.rst#L55-56) :
```rst
Install python dependencies
------------------------------

**5. Create a new virtual environment**

    * Make a new virtual environment (e.g. using virtualenv or conda), name it "great_expectations_dev" or similar.
    * Ex virtualenv: ``python3 -m venv <path_to_environments_folder>/great_expectations_dev`` and then ``<source path_to_environments_folder>/great_expectations_dev/bin/activate``
    * Ex conda: ``conda create --name great_expectations_dev`` and then ``conda activate great_expectations_dev``
    * This is not required, but highly recommended.
```

**To Reproduce**
1. Follow steps on the dev environment setup page [here]()

**Expected behavior**
The packages should install without error using Python 3.7 (tested locally).

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.8

**Additional context**
I will open a PR to propose a fix to this.

**Comment by spbail** [comment]
This was merged in #2391
