### ISSUE TITLE
suite scaffold does NOT include 'expect_column_values_to_be_of_type' and some other expectations

### ISSUE THREAD

**Issue by hparsa741** [fivetran/great_expectations#2399]
**Describe the bug**
`suite scaffold` on GE 0.13.7 does NOT include `'expect_column_values_to_be_of_type'` and some other expectations.  Adding the expectations explicitly will not include it either.  
`"included_expectations": ['expect_column_values_to_be_of_type']` 
2021-01-31T18:35:57-0500 - INFO - 	**0 expectation(s) included in expectation_suite.**

**To Reproduce**
1. Go to GE project directory 
2. Run `great_expectations suite scaffold type.warning`
3. Choose the data source (CSV file type in this case)
4. Once the Jupyter notebook opens up run the first cell 
5. Uncomment a column in the second cell and run it
6. In the 3rd cell, **Run the scaffolder**, uncomment the "included_expectation", add "expect_column_values_to_be_of_type" to the list `"included_expectations": ["expect_column_values_to_be_of_type"]` and run the cell
7. See the output `2021-02-05T15:30:21-0500 - INFO - 	0 expectation(s) included in expectation_suite.`

**Expected behavior**
It is expected that in step 7 the output is **1 expectation(s) included** but 0 is returned.

**Environment (please complete the following information):**
 - Operating System: MacOS Catalina 10.15.7
 - Great Expectations Version: 0.13.7

**Comment by eugmandel** [comment]
@hparsa741 [The profiler that the  suite scaffold command uses](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/profile/basic_suite_builder_profiler.py) does not ask questions about the storage type of columns (the expect_column_values_to_be_of_type Expectation). One of the reasons that we did not include this Expectation in that profiler's logic is this: https://discuss.greatexpectations.io/t/how-does-the-expect-column-values-to-be-of-type-expectation-work/630

It is important to emphasize that this profiler is just one possible profiler implementation. You can extend the base class and express some different logic of profiling. Each profiler implementation is a set of questions that are asked about data.
