### ISSUE TITLE
Usage of boto3_options when connected to s3-compatible Yandex Object Storage (https://storage.yandexcloud.net)

### ISSUE THREAD

**Issue by TkachevKonstantin** [fivetran/great_expectations#2420]
**Describe the bug**
I try to get batch from csv file stored on s3 using attached config (see  config in **Additional context**).
 I've set environmet vars AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and set aws CLI (see aws config list output below).
```
$ aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************6O2H              env
secret_key     ****************YCJe              env
    region                us-east-1      config-file    ~/.aws/config
```

My virtual environment use follow packages (also see packages.png):
great_expectations == 0.13.8
boto3 == 1.17.3

I can write expectations and validations on s3 but when I try to read file on s3 using follow code I get error.
```
expectation_suite_name2 = "s3.pandas.warning"
suite2 = context.create_expectation_suite(expectation_suite_name2, overwrite_existing=True)
suite2.expectations = []
batch_kwargs2 = {
    "datasource": "pandas_s3",
    "s3": "s3a://t-dp-dq/source_test/test.csv",
    "delimiter": "/",
}
batch2 = context.get_batch(batch_kwargs2, suite2)
batch2.head()

```
Stack trace:
```
Traceback (most recent call last):
  File "C:\Users\60067287\PycharmProjects\ge_test\main.py", line 85, in <module>
    batch2 = context.get_batch(batch_kwargs2, suite2)
  File "C:\Users\60067287\PycharmProjects\ge_test\venv\lib\site-packages\great_expectations\data_context\data_context.py", line 1420, in get_batch
    return self._get_batch_v2(
  File "C:\Users\60067287\PycharmProjects\ge_test\venv\lib\site-packages\great_expectations\data_context\data_context.py", line 1138, in _get_batch_v2
    batch = datasource.get_batch(
  File "C:\Users\60067287\PycharmProjects\ge_test\venv\lib\site-packages\great_expectations\datasource\pandas_datasource.py", line 227, in get_batch
    s3_object = s3.get_object(Bucket=url.bucket, Key=url.key)
  File "C:\Users\60067287\PycharmProjects\ge_test\venv\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\60067287\PycharmProjects\ge_test\venv\lib\site-packages\botocore\client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the GetObject operation: The AWS Access Key Id you provided does not exist in our records.
```

At the  same time I can get file content via boto3.
```
import boto3
session = boto3.session.Session()
s3 = session.client(
    service_name='s3',
    endpoint_url='https://storage.yandexcloud.net'
)
get_object_response = s3.get_object(Bucket='t-dp-dq',Key='source_test/test.csv')
print(get_object_response['Body'].read().decode('utf-8'))
### OR ###
import boto3
s3 =boto3.client(
    service_name='s3',
    endpoint_url='https://storage.yandexcloud.net'
)
s3_file = s3.get_object(Bucket='t-dp-dq', Key='source_test/test.csv')
print(s3_file['Body'].read().decode('utf-8'))
```

**To Reproduce**
I  debug problem case and I realize that **endpoint_url** which I set don't used.
In config I set - 'https://storage.yandexcloud.net' but in **pandas_datasource.py**
**_boto3_options** is empty and then used apparently endpoint_url = 'https://s3.amazonaws.com'.
See attached files (trace1.png and trace2.png).

Also when you call self._init_datasources(self.project_config_with_variables_substituted)  in data_context.py object self.project_config_with_variables_substituted doesn't contain boto3_options provided in my config (see config in **Additional context**).

**Expected behavior**
I expect that endpoint_url parameter inside boto3_options will be used correctly as I set one in my config (see config in **Additional context**).

**Environment (please complete the following information):**
 - Operating System:
 - Windows 10 and Ubuntu 20.04.1 LTS
 - Great Expectations Version: 0.13.8

**Additional context**
#----------            CONFIG         ---------------
```
config_datasources = {
    'pandas_s3': {
        'data_asset_type': {
            'class_name': 'PandasDataset',
            'module_name': 'great_expectations.dataset'
        },
        'boto3_options': {
            'endpoint_url': 'https://storage.yandexcloud.net',
            'region_name': 'us-east-1'
        },
        'class_name': 'PandasDatasource',
        'module_name': 'great_expectations.datasource',
        'batch_kwargs_generators': {}
    }
}
config_stores = {
                "expectations_S3_store": {
                    "class_name": "ExpectationsStore",
                    "store_backend": {
                        "class_name": "TupleS3StoreBackend",
                        "endpoint_url": "https://storage.yandexcloud.net",
                        "bucket": "t-dp-dq",
                        "prefix": "great_expectations/data_platform/expectations/",
                    },
                },
                "validations_S3_store": {
                    "class_name": "ValidationsStore",
                    "store_backend": {
                        "class_name": "TupleS3StoreBackend",
                        "endpoint_url": "https://storage.yandexcloud.net",
                        "bucket": "t-dp-dq",
                        "prefix": "great_expectations/data_platform/validations/",
                    },
                },
                "evaluation_parameter_store": {"class_name": "EvaluationParameterStore"},
            }
config_data_docs_sites = {
    "s3_site": {
        "class_name": "SiteBuilder",
        "store_backend": {
            "class_name": "TupleS3StoreBackend",
            "endpoint_url": "https://storage.yandexcloud.net",
            "bucket": "t-dp-dq",
            "prefix": "great_expectations/data_platform/data_docs/",
        },
        "site_index_builder": {
            "class_name": "DefaultSiteIndexBuilder",
            "show_cta_footer": True,
        },
    },
}
project_config = DataContextConfig(
	config_version=2,
	plugins_directory=None,
	config_variables_file_path=None,
	datasources=config_datasources,
	stores=config_stores,
	expectations_store_name="expectations_S3_store",
	validations_store_name="validations_S3_store",
	evaluation_parameter_store_name="evaluation_parameter_store",
	data_docs_sites=config_data_docs_sites,
	validation_operators=config_validation_operators,
	anonymous_usage_statistics=config_anonymous_usage_statistics
)

#ATTENTION! After call below we lose boto3_options. context doesn't contain one.
context = BaseDataContext(project_config=project_config)

```
#----------            CONFIG         ---------------

(url
<img width="960" alt="packages" src="https://user-images.githubusercontent.com/47427912/107327807-ca949e00-6abe-11eb-8a9f-07a71be261aa.png">
<img width="960" alt="trace1" src="https://user-images.githubusercontent.com/47427912/107327810-cbc5cb00-6abe-11eb-91b3-d2da123ebafd.png">
<img width="960" alt="trace2" src="https://user-images.githubusercontent.com/47427912/107327814-ccf6f800-6abe-11eb-9424-c6ffe6002957.png">

)

**Comment by eugmandel** [comment]
@TkachevKonstantin Thank you for following up and posting this issue description. We are having a (virtual) offsite this week, so will triage on Monday.

**Comment by TkachevKonstantin** [comment]
You lose boto3_options after this call `context = BaseDataContext(project_config=project_config)` cause **project_config** contains boto3_options but **context** doesn't.
I think it's happen in get_config_with_variables_substituted function (see great_expectations\data_context\data_context.py, class BaseDataContext) here:

```
return DataContextConfig(
 **substitute_all_config_variables
 ( config, substitutions, self.DOLLAR_SIGN_ESCAPE_STRING 
 )
 )
```

And then in substitute_all_config_variables function (see great_expectations\data_context\util.py) after this step

```
    if isinstance(data, DataContextConfig):
        data = DataContextConfigSchema().dump(data)
```
we lose boto3_options which was in data.

May be DataContextConfigSchema().dump method incorrect uses nested stuctures
or in substitute_all_config_variables  functon recursive processing is wrong?

-------------------------------------------------------------------------------------------

My debug steps:
0. `context = BaseDataContext(project_config=project_config) `

then in class BaseDataContext:
1. `__init__` (see call "result = func(*args, **kwargs)" where` func = data_context.__init__` in usage_statistics.py)
2. `_init_datasources` (see call self._init_datasources in data_context.py)
3. `get_config_with_variables_substituted` (see call in data_context.py)

and then invoked 
4. `substitute_all_config_variables` (see great_expectations\data_context\util.py)

**Comment by TkachevKonstantin** [comment]
Hello guys!
Can I understand when you take issue in work?

**Comment by eugmandel** [comment]
@TkachevKonstantin Let me update you tomorrow after our next triage.

**Comment by eugmandel** [comment]
Added to the core team's backlog.

**Comment by TkachevKonstantin** [comment]
Eugene, colleagues, thanks a lot!
I hope my thoughts regards to problem will help to solve one.

**Comment by TkachevKonstantin** [comment]
Hello guys!
Is there news regarding my problem?

**Comment by MatthewC12** [comment]
Anyone have a fix for this yet?

**Comment by TkachevKonstantin** [comment]
Hello everyone!
I'am not sure but I think anyone have NOT a fix for this yet.

**Comment by talagluck** [comment]
Hi @TkachevKonstantin! Apologies for delays here. I know we've had a couple of PRs regarding boto3 come through recently. Would you please confirm whether this is still an issue?

**Comment by TkachevKonstantin** [comment]
Hello! Yes, this still an issue.

**Comment by 6B6C6D** [comment]
Can confirm. This is still a present issue

**Comment by talagluck** [comment]
Hi @TkachevKonstantin and @6B6C6D - thank you for your patience, and again, apologies for delays. We have been having a hard time reproducing this locally, but it looks as though you have already tracked down the source of the issue. Is this something which you would be interested in contributing? Please let us know if we can help support a contribution, and we are happy to prioritize a PR review if you are able to make one. Thanks!

**Comment by fbardos** [comment]
I ran into a similar issue, trying to connect GE with [Minio](https://min.io/).

When printing out `request_dict` in `site-packages/botocore/client.py:965` I saw, that not all URLs got rewritten to my desired endpoint, but selecting `https://<bucket-name>.s3.amazonaws.com/`instead.

So, I made use of `boto3_options` inside all `TupleS3StoreBackend` references:
- ExpectationsStore
- ValidationsStore,
- CheckpointStore,
- ProfilerStore
- SiteBuilder (Data docs)

With:
```python
from great_expectations.data_context.types.base import DataContextConfig, S3StoreBackendDefaults
from great_expectations.data_context import BaseDataContext

boto3_options = {
    'endpoint_url': 'http://localhost:9000',
    "aws_access_key_id": "<your-access-key>",
    "aws_secret_access_key": "<your-secret-key>",
}

# Set config for data docs with boto3_options
config_data_docs_sites = {
    "s3_site": {
        "class_name": "SiteBuilder",
        "store_backend": {
            "class_name": "TupleS3StoreBackend",
            "bucket": "great-expectations-meta",
            "prefix": "data_docs",
            "boto3_options": boto3_options
            }
        },
    },
}

# Init DataContextConfig with defaults for store_backend, rewrite later
data_context_config = DataContextConfig(
    store_backend_defaults=S3StoreBackendDefaults(default_bucket_name="great-expectations-meta"),
    data_docs_sites=config_data_docs_sites,
)

# Rewrite config to use boto3_options
for store in data_context_config['stores'].values():
    if store.get('store_backend', {}).get('class_name') == 'TupleS3StoreBackend':
        store['store_backend']['boto3_options'] = boto3_options
context = BaseDataContext(project_config=data_context_config)
```

After setting `endpoint_url` inside `boto3_options` for all relevant stores, all calls were rewritten to the correct endpoint, and the mentioned error (`botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the GetObject operation: The AWS Access Key Id you provided does not exist in our records.
`) from @TkachevKonstantin didn't occure anymore.

Maybe, this helps you.

**Comment by talagluck** [comment]
Hi all - thanks again for raising this and for your feedback! Realistically, this isn't something that we will be able to implement in the near-term especially since it sounds like there is a workaround, though we have logged this feedback to consider if we are working in this area. In the meantime, I'm going to close this Issue, but if you are interested in making a contribution, please feel free to re-open this and let us know.
