### ISSUE TITLE
Invalid column name "Distinct (%)" in BasicDatasetProfiler HTML output

### ISSUE THREAD

**Issue by Skolim007** [fivetran/great_expectations#2423]
Hi,

I think there is some issue with HTML renderer used to build pages form profiling results. There are two columns displayed as "Distinct (%)" - where in my opinion first column should be "Distinct count" and not displayed as pecentage.
In my case data set has 4 rows and two unique values in that column.
![image](https://user-images.githubusercontent.com/73521262/107485724-6fc57a00-6b84-11eb-8a8b-a4969682fb30.png)

**Comment by eugmandel** [comment]
@TkachevKonstantin Thank you for reporting this issue! We are having a (virtual) offsite this week, so will triage on Monday.

**Comment by roblim** [comment]
Thanks for reporting this @Skolim007! This has been addressed in #2455 and merged into `develop` - it will appear in the next release.
