### ISSUE TITLE
BigQuery documentation link broken after `GE init`

### ISSUE THREAD

**Issue by peteratemarsys** [fivetran/great_expectations#2424]
**Describe the bug**

After typing `great_expectations init` in terminal, selecting BigQuery later on as my datasource but not being able to auth, so pressing 'n' to the question 'Enter the credentials again? [Y/n]:' I got the following message:

> Since we could not connect to the database, you can complete troubleshooting in the configuration files documented here:
> https://docs.greatexpectations.io/en/latest/tutorials/add-sqlalchemy-datasource.html?utm_source=cli&utm_medium=init&utm_campaign=0_13_9#bigquery

The link is broken.

**Environment (please complete the following information):**
 - Operating System: MacOS BigSur
 - Great Expectations Version: 0.13.9

**Comment by eugmandel** [comment]
Thank you for filing it, @peteratemarsys !
