### ISSUE TITLE
It is difficult to make expectations about index columns

### ISSUE THREAD

**Issue by jpcampb2** [fivetran/great_expectations#243]
Because pandas index is not accessible via the normal mechanism, expect_column_* expectations cannot currently be written against Pandas Indices.

This needs design thought, but an initial implementation might do something like allow for an is_index flag to the expect_column_* expectations.

**Comment by ccnobbli** [comment]
another way we could do this is have a universal name for the index, e.g. "index" or "INDEX". This could be caught in the expectation decorator and pass on the index as if it were a column.

**Comment by jpcampb2** [comment]
I think your proposal is better--we would just need to document that index ceases to be a valid column name. Also, of course, it only makes sense in pandas, and we'd want to double check that it's not a multiindex in which case we would potentially just throw an error.
