### ISSUE TITLE
Tutorial failing on checkpoint new command with config 3.0 error

### ISSUE THREAD

**Issue by blake-enyart** [fivetran/great_expectations#2437]
**Describe the bug**
When I am working through the tutorial, the 

**To Reproduce**
1. Follow the tutorial up to `Validate your data using a Checkpoint`
2. Run the command `great_expectations checkpoint new staging.chk taxi.demo`
3. See error:
```
Heads up! This feature is Experimental. It may change. Please give us your feedback!
The `checkpoint new` CLI command is not yet implemented for GE config versions >= 3.
```

**Expected behavior**
Generation of a checkpoint according to the tutorial

**Environment (please complete the following information):**
 - Operating System: MacOS 10.15.7 (19H114)
 - Great Expectations Version: 0.13.10

**Additional context**
The above should replicate the issue. When I drop down to config 2.0 the system raises an error that is must be at 3.0 for this command.

**Comment by TheOriginalAK47** [comment]
+1, experiencing same issue as Blake.

**Comment by sou-joshi** [comment]
+1, Same issue. Was anyone able to fix this?

**Comment by luke321321** [comment]
FYI looks like some of the `3.0` is still a WIP for full support across all of GE: https://discuss.greatexpectations.io/t/can-i-use-the-new-experimental-v3-api-in-production/629

**Comment by eugmandel** [comment]
Thank for you reporting this! We are adjusting the tutorial to be compatible with the V3 API. @luke321321 thank you for linking to the Discuss post that clarifies the state of the V3 API.

We will triage this issue today.

**Comment by eugmandel** [comment]
There is a PR that addresses this issue. It is about to be merged shortly: https://github.com/great-expectations/great_expectations/pull/2418

**Comment by spbail** [comment]
#2418 was just merged. The tutorial now describes how to create a new Checkpoint for validation without the CLI, which should address the issues here when creating a new data context with 0.13.8 and higher.
