### ISSUE TITLE
Generating docs concurrently can potentially create uncomplete index

### ISSUE THREAD

**Issue by dmateusp** [fivetran/great_expectations#2446]
we're having a recurring problem where we run Great Expectations suites in parallel and sometimes the index is updated incompletely. We think there is a race condition when the index is updated simultaneously.

Would it be possible to expose this new feature by allowing folks to turn off building the index on a validation operator and having a `great_expectations docs` command specifically to rebuild the index? (we don't use GE through the python API)

_Originally posted by @dmateusp in https://github.com/great-expectations/great_expectations/issues/2224#issuecomment-764833272_

**Comment by dmateusp** [comment]
cc @Aylr

**Comment by Aylr** [comment]
@spbail this would be very easy to add to the ongoing CLI work...

**Comment by eugmandel** [comment]
@dmateusp This [PR](https://github.com/great-expectations/great_expectations/pull/2224) by @Aylr back in January added `build_index` argument to BaseDataContext.build_data_docs method.

To expose this new functionality and make it configurable, the UpdateDataDocsAction that is invoked by Checkpoints (or Validation Operators in older versions) needs to be modified: https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/checkpoint/actions.py#L710

A PR from a community contributor would be super appreciated.

**Comment by chaos87** [comment]
I am also encountering this issue.
I'd like to help for this PR, unless anyone else is already doing it?

**Comment by jbkai** [comment]
I am also encountering this issue.
I'd like to help for this PR, unless anyone else is already doing it?
