### ISSUE TITLE
Broken 'typical_workflow' link

### ISSUE THREAD

**Issue by seb-afk** [fivetran/great_expectations#2456]
The[ `init_notebooks`](https://github.com/great-expectations/great_expectations/tree/develop/great_expectations/init_notebooks) have a link to a "typical workflow" documentation page which seems to have only existed up until version [0.9.11](https://docs.greatexpectations.io/en/0.9.11/getting_started/typical_workflow.html). I could not find the page in newer versions of the docs, but would be more than happy to fix the link and submit a PR if someone can tell me where the new page is. 🙌 

https://github.com/great-expectations/great_expectations/blob/352514a9dc33543ab1b6039f463a57449f445fd2/great_expectations/init_notebooks/sql/validation_playground.ipynb#L199

https://github.com/great-expectations/great_expectations/blob/352514a9dc33543ab1b6039f463a57449f445fd2/great_expectations/init_notebooks/pandas/validation_playground.ipynb#L195

https://github.com/great-expectations/great_expectations/blob/352514a9dc33543ab1b6039f463a57449f445fd2/great_expectations/init_notebooks/spark/validation_playground.ipynb#L196

**Comment by eugmandel** [comment]
@sebastianbertoli Good catch - thank you! This docs page indeed was removed and broken up into multiple guides.

If you create a PR, could you please replace this:

```
### 1. Read about the typical workflow with Great Expectations:

[typical workflow](https://docs.greatexpectations.io/en/latest/getting_started/typical_workflow.html?utm_source=notebook&utm_medium=validate_data#view-the-validation-results-in-data-docs)

```

with this:

```
### 1. Consult these guides for typical workflows with Great Expectations:

[Guides](https://docs.greatexpectations.io/en/latest/guides.html?utm_source=notebook&utm_medium=validate_data#view-the-validation-results-in-data-docs)

```
?

Thank you!

**Comment by seb-afk** [comment]
Sounds good, will get to it tomorrow! Thanks!
