### ISSUE TITLE
Broken 'Validation Operators tutorial' link

### ISSUE THREAD

**Issue by seb-afk** [fivetran/great_expectations#2457]
The[ `init_notebooks`](https://github.com/great-expectations/great_expectations/tree/develop/great_expectations/init_notebooks) have a link to a "Read more about Validation Operators in the tutorial" documentation page which seems to have only existed up until version [0.9.11](https://docs.greatexpectations.io/en/0.9.11/getting_started/typical_workflow.html). I could not find the page in newer versions of the docs, but would be more than happy to fix the link and submit a PR if someone can tell me where the new page is. 🙌 

https://github.com/great-expectations/great_expectations/blob/352514a9dc33543ab1b6039f463a57449f445fd2/great_expectations/init_notebooks/sql/validation_playground.ipynb#L139

https://github.com/great-expectations/great_expectations/blob/352514a9dc33543ab1b6039f463a57449f445fd2/great_expectations/init_notebooks/pandas/validation_playground.ipynb#L135

https://github.com/great-expectations/great_expectations/blob/352514a9dc33543ab1b6039f463a57449f445fd2/great_expectations/init_notebooks/spark/validation_playground.ipynb#L136

**Comment by eugmandel** [comment]
@sebastianbertoli Looks like we missed this one! Validation Operators's functionality is replaced by Checkpoints in 0.13.8. We are still updating the documentation. Until this is cleaned up, it would be the best to remove this link from the notebooks completely. Thank you!
