### ISSUE TITLE
`expect_compound_columns_to_be_unique` can't be saved multiple times in the same suite

### ISSUE THREAD

**Issue by Gfeuillen** [fivetran/great_expectations#2464]
**Describe the bug**
When `expect_compound_columns_to_be_unique` is used multiple times in a suite, only the last occurence gets saved

**To Reproduce**
1. Create a new project
2. Load a Spark Dataset using `QueryBatchGenerator`
3. Create a new suite with 2 `expect_compound_columns_to_be_unique` expectations
4. Save it on disk
5. See that there is only 1 saved (already checked this is not due to one being failed on the other not)

**Expected behavior**

That all occurrences of the expectation are saved

**Environment (please complete the following information):**

 - Operating System: Linux
 - Great Expectations Version: 0.13.9

**Additional context**

As stated in the steps, I am using a Spark Dataframe source from a Hive table using the `query` arg

**Comment by Shinnnyshinshin** [comment]
HI @Gfeuillen thank you for submitting the issue. A fix was made that should address the problem you were having, and will be part of the upcoming 0.13.11 release. Please let us know if you continue to run into the issue

**Comment by Gfeuillen** [comment]
Just tested, it's fixed indeed.

Thanks for the fix !
