### ISSUE TITLE
open_data_docs fails to open on Windows browsers when length of path exceeds 260 characters

### ISSUE THREAD

**Issue by manishgk** [fivetran/great_expectations#2469]
**Describe the bug**
If your expectation_suite_name is large (multiple subfolders), Windows has this limitation to allow only 260 characters when loading any file in the browser. So the expectation here is if this can be controlled from GE team while calling open_data_docs  function to check if the length is over 260 characters or not.

https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

**To Reproduce**
1. Go to Jupyter Notebook and run your expectation suite
2. Wait till it runs all cells and calls open_data_docs function
3. It automatically opens the Data docs in the browser
4. But as the length of the path is exceeding 260 characters, it says "Your file couldn't be accessed" on the browser

![image](https://user-images.githubusercontent.com/41348103/109025712-973c3c80-7684-11eb-8da4-1de7fe2cdf41.png)

**Expected behavior**
Data docs should open irrespective of the length of the path.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.13.10

**Additional context**
I'm on Windows 10 version 1903.
The workaround right now for me is to reduce the suite name String and move the path to upper folder, but would be great if this is taken care by the library

**Comment by eugmandel** [comment]
@manishgk This is a good find. We invite a community contribution to address this issue.

**Comment by josiah-eichelman** [comment]
Hello! I'm new to great-expectations, but recently came across this bug aswell. Any fix? Can we re-open this issue?  Maybe a fix would be to have a link to the file, that way the browser is only opening a small filepath to the link and not the entire path?
