### ISSUE TITLE
Join tables in SqlAlchemyDataset

### ISSUE THREAD

**Issue by bouke-nederstigt** [fivetran/great_expectations#249]
It would be great to join multiple tables / execute queries and execute expectations on the result. I've been thinking a little on how to implement it. 

Options I came up with so far
- Replacing all ```select_from(sa.table(self.table_name))``` in the SQLAlchemyDataset class with subqueries. This would also require to add some logic for inspecting column types etc. by analyzing the query. Might have a performance penalty because every expectation would require executing the subquery.
- Create a temporary table in the constructor of the SQLAlchemyDataset class based on provided sql query. This would leave the rest of the class as is. It also means the join query needs to be executed just once. 

Let me know what you think about this. I'd be happy to implement it if there's a good idea/direction on how to solve this.

Cheers

**Comment by jpcampb2** [comment]
Joining tables will no doubt come up a lot--thank you for opening the issue!

The proposal to allow providing SQL that creates a temporary table against which expectations will be run makes the most immediate sense to me, and seems in line with an eventual view wherein a given data_context (the sql database) could expose a mechanism for creating check datasets. It also provides a lot of flexibility right away.

Question for you: depending on the use case you have in mind, it seems to me that there may also be a relationship to the preprocessing steps we've discussed a bit in #80; do you see useful functionality described in that issue? It may depend a bit on whether the joined table should ever persist at all. That might incline us toward creating an even more ephemeral temporary table, that exists only during validate or evaluation of an expectation.

**Comment by bouke-nederstigt** [comment]
Although I don't think it's necessary for my immediate use case preprocessing would definitely be a nice to have. I didn't really run into the need for it yet, but then again I've only just begun experimenting with the great_expectations library.

From my point of view I would never expect the library to ever persist anything with respect to data preparation or joining. I would push that kind of functionality to other jobs in my ETL pipeline (at least if persistence is required). Using the temporary table would definitely still allow for preprocessing though. The preprocessing_method would just be called as always, after the temporary table has been created.  Something that I would be interested in when it comes to persistence is the ability to write expectation output to the database, but that's probably a topic for a different issue.

If you agree the temporary table might be a valid approach I'll see if I can mock something up. See how it works in practice.

**Comment by abegong** [comment]
I really like the idea of exploring temporary tables and preprocessing. I bet it'll be important for convenience and optimization.

Thanks for taking a first crack at this, @bouke-nederstigt !

**Comment by jpcampb2** [comment]
Thanks again, @bouke-nederstigt. I'm going to close this issue, but we're interested in your experience using the feature, as well as the new SqlAlchemyDataset in general.
