### ISSUE TITLE
Outdated Docker image registry

### ISSUE THREAD

**Issue by frederikdesmedt** [fivetran/great_expectations#2495]
**Describe the bug**
[Current documentation](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/miscellaneous/how_to_use_official_docker_images.html) provides a link to the official registry, but the repository doesn't look like it's updated.

**To Reproduce**
1. Go to https://hub.docker.com/r/greatexpectations/great_expectations/tags
2. See only 0.12 versions

**Expected behavior**
See images for more recent great-expectation versions.

**Comment by eugmandel** [comment]
@frederikdesmedt 

We want to start publishing Docker images for every new release, but there is no timeline for this yet.
The images currently on dockerhub are experimental.

**Comment by tooptoop4** [comment]
any update?
