### ISSUE TITLE
Testing for different types of Missing Values in expect_column_values_to_[not]_be_null

### ISSUE THREAD

**Issue by ccnobbli** [fivetran/great_expectations#250]
Spin off from #239 and PR #246 

Currently when testing expect_column_values_to_not_be_null(), see test_pandas_dataset, it expects all Null values to be returned as `None` in `result['unexpected_list']`.

There are a few different ways to represent Null, especially across data contexts. I propose that we try to keep the native Null format when returning it in the `unexpected_list`. The biggest problem I've observed when just using numpy's `np.nan` is that unittest's `assertEquals([np.nan], [np.nan])` fails, so our current testing framework of comparing the `unexpected_list` to the test output fails.

Perhaps the best way to approach this is having a helper function that compares arrays with any variety of Null values.

**Comment by jpcampb2** [comment]
This may be best thought of as an a different issue, but I'm wondering about some additional nuance in handling null values. For example:

```
>>> a = ge.dataset.PandasDataset({'a': [ 1,2,3,4]})
>>> a.expect_column_values_to_be_in_set('a', [2,3,4])
{'success': False, 'result': {'element_count': 4, 'missing_count': 0, 'missing_percent': 0.0, 'unexpected_count': 1, 'unexpected_percent': 0.25, 'unexpected_percent_nonmissing': 0.25, 'partial_unexpected_list': [1]}}
>>> a = ge.dataset.PandasDataset({'a': [ None, 1,2,3,4]})
>>> a.expect_column_values_to_be_in_set('a', [2,3,4])
{'success': False, 'result': {'element_count': 5, 'missing_count': 1, 'missing_percent': 0.2, 'unexpected_count': 1, 'unexpected_percent': 0.2, 'unexpected_percent_nonmissing': 0.25, 'partial_unexpected_list': [1.0]}}
>>> a.expect_column_values_to_be_in_set('a', [None, 2,3,4])
{'success': False, 'result': {'element_count': 5, 'missing_count': 1, 'missing_percent': 0.2, 'unexpected_count': 1, 'unexpected_percent': 0.2, 'unexpected_percent_nonmissing': 0.25, 'partial_unexpected_list': [1.0]}}
>>>
```

**Comment by abegong** [comment]
@jpcampb2 Is this what the method does now, or what you wish it would do?

**Comment by jpcampb2** [comment]
That's the current behavior. I don't like that my set of values can't include None/null.

**Comment by abegong** [comment]
In parallel with the current proposal for column_pairs, we could do:
`ignore_row_if="value_is_missing" / "never"`

Problem is, we could apply that to a lot of column map expectations...

**Comment by jpcampb2** [comment]
I agree...but I think it's worth it to control. I think adding it everywhere is a better call...much more explicit.

**Comment by abegong** [comment]
You're probably right.

I vote we Implement `ignore_row_if` on the column_pair expectations, then watch it for a while. If it's a good experience, we can roll it out to all the column_map expectations as well.

I don't think there's any urgency---it there is, people will tell us---and I'd much rather not have to undo a big "add a parameter to every docstring" change.

Also, tangentially related: should `expect_column_values_to_[not]_be_null` be `expect_column_values_to_[not]_be_missing`?

**Comment by ccnobbli** [comment]
> should expect_column_values_to_[not]_be_null be expect_column_values_to_[not]_be_missing?

That makes sense to me, that seems very relevant to this issue. 

I like the `ignore_row_if="value_is_missing" / "never"` idea. As to how many expectations to apply it to, we would probably get feedback more quickly if we rolled it out to the other column_map expectations... but @abegong is right about a large undo once we get that feedback.

**Comment by jpcampb2** [comment]
I think the right intermediate approach is a small documentation section that describes how we use the terms "null" and "missing." That will force us to be explicit about it and can trigger a search for the right consistent behavior (e.g. re the move from np.nan to pd.isna checks in the new column pair expectations).

**Comment by abegong** [comment]
💯
