### ISSUE TITLE
Progress Bar for profiler

### ISSUE THREAD

**Issue by peterdhansen** [fivetran/great_expectations#2500]
Some processes can take a long time, like the BasicSuiteBuilderProfiler and a progress bar can make it much more bearable.

There is a great progress bar package `tqdm` (https://github.com/tqdm/tqdm) that would be great addition to these longer process. Would this addition interest others?

**Comment by eugmandel** [comment]
@peterdhansen This sounds like a great contribution - yes, please go ahead. We looked at adding a progress bar in the past, but ran out of time.
