### ISSUE TITLE
Cannot open a directory with name "checkpoints" in jupyter notebooks / jupyterlab

### ISSUE THREAD

**Issue by filipj8** [fivetran/great_expectations#2502]
**Describe the bug**
Cannot open a directory with name "checkpoints" in jupyter notebooks / jupyterlab

**To Reproduce**
1. Try opening the auto-created directory `great_expectations/checkpoints` directory.

**Expected behavior**
The directory should open

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.11

**Additional context**
This is an issue with jupyter notebooks, see https://github.com/jupyterlab/jupyterlab/issues/4099 and https://github.com/jupyter/notebook/issues/5569

**Comment by eugmandel** [comment]
@filipj8 I see - "checkpoints" is a special name in Jupyter. Checkpoint is also a central concept in Great Expectations. of course with a very different meaning :). I think a workaround is to open that directory with some other editor.
