### ISSUE TITLE
Problem installing with pipenv

### ISSUE THREAD

**Issue by ounis** [fivetran/great_expectations#2504]
When trying to install `great-expectations` using `pipenv` I run into some issues

**To Reproduce**
1. install pipenv (one way to install it is `pip install pipenv`)
2. Create a python project that uses pipenv to install dependencies (Could be empty)
2. add to your `Pipfile` this line `great-expectations = "0.13.12"` under `[packages]` section
3. run `pipenv install`inside your python project

**Expected behavior**
1. `pipenv install` command should not fail
2. `great-expectations` should be added to the project dependencies
3. `great-expectations` should be added to the `Pipfile.lock`

**Environment (please complete the following information):**
 - Docker image `python:3.7-alpine`
 - Great Expectations Version: `0.13.12`

**Additional context**
I created a small project as example that shows the failure here https://github.com/ounis/install-great-expectations
Also I created a Travis CI build that show the output when running it here https://travis-ci.org/github/ounis/install-great-expectations/builds/761442345

**Comment by eugmandel** [comment]
@ounis Thank you for posting the link to Travis output! It looks like what is failing is numpy installation. Since users use Great Expectations in various environments, we really appreciate the help from the community with issues like this one. Would you investigate it further? For example, does installing numpy (without Great Expectations) works on pipenv? Thank you!

**Comment by ounis** [comment]
@eugmandel Sure! I will try `numpy` by itself, and give feedback.

**Comment by ounis** [comment]
@eugmandel you are right the issue comes from `numpy`
I did this change https://github.com/ounis/install-great-expectations/commit/14d0f72c3eb1c045c651df567c52a5b70670ced6
And here is the build https://travis-ci.org/github/ounis/install-great-expectations/builds/761670672

It seems more people are complaining about `numpy` here
https://stackoverflow.com/questions/66003811/pipenv-locking-for-numpy-fails-on-python3-9-and-pip21-0-1
https://github.com/numpy/numpy/issues/17569

I'm not sure what you should do about it, maybe just close this issue and just wait for the issue to be fixed.

**Comment by ounis** [comment]
Please keep this open until the numpy issue is fixed.
