### ISSUE TITLE
build_categorical_partition_object for V3

### ISSUE THREAD

**Issue by peterdhansen** [fivetran/great_expectations#2533]
the function `great_expectations.dataset.util.build_categorical_partition_object` expects a Batch, which I don't have if I am using a validator

**Comment by eugmandel** [comment]
@peterdhansen The batch is "hiding" inside validator.active_batch - please try and report back. Thank you!

**Comment by eugmandel** [comment]
@peterdhansen I am closing this issue - please reopen, if this does not work for you.

**Comment by peterdhansen** [comment]
This was my mistake, The function looks for a `DataSet` not a `Batch`. I don't think there is a way to get a dataset from a validator

Doc: [build_continuous_partition_object](https://docs.greatexpectations.io/en/latest/autoapi/great_expectations/dataset/util/index.html?highlight=build%20continuous%20partition%20object#great_expectations.dataset.util.build_continuous_partition_object)

**Comment by peterdhansen** [comment]
Doesn't look like I can reopen, but this is still an issue i think
