### ISSUE TITLE
azure static website prompt users to download the file instead of rendering the contents of datadoc

### ISSUE THREAD

**Issue by benoitLebreton-perso** [fivetran/great_expectations#2537]
I'm trying to [host and share data docs on azure blob storage](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_data_docs/how_to_host_and_share_data_docs_on_azure_blob_storage.html?highlight=expose%20azure). And I'm trying using a simple [static website](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website-how-to?tabs=azure-cli).

**Describe the bug**
azure upload html files with `content-type=application/octet-stream`. So when I'm exposing the data doc using a static website, it makes the browser prompt users to download the file instead of rendering the contents.
This problem doesn't exist with GCP : I can host and share simply with making my html files public.

this behavior of azure is mentioned in a Note [here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website-how-to?tabs=azure-portal). 
The obvious solution would be to force the upload method to have : --content-type 'text/html; charset=utf-8'. 

But when I look at the code (**class HtmlSiteStore** in great_expectations/great_expectations/data_context/store/html_site_store.py) it seems to be already done...
Maybe the problem a full azure issue.

**Comment by benoitLebreton-perso** [comment]
I'm tying to modify code to set configuration just like explained here : 

https://stackoverflow.com/questions/59752380/set-content-type-when-uploading-to-azure-blob-storage.

It doesn't make a difference for now. I'm continuing on this.

**Comment by benoitLebreton-perso** [comment]
Ok I've found it ! 
I'm opening a PR #2539 that will solve it :)

**Comment by eugmandel** [comment]
Yet again, my favorite kind of GitHub issue, one that comes with a PR that addresses it! @benoitLebreton-perso, thank you for being a contributor!

**Comment by eugmandel** [comment]
The PR merged - closing the issue as fixed.
