### ISSUE TITLE
Applying Identical Expectations to Multiple Columns

### ISSUE THREAD

**Issue by ccnobbli** [fivetran/great_expectations#254]
I am working with data that has groups of columns that I want to apply the exact same expectations.
`df.expect_column_values_to_not_be_in_set('colA', [list of values])
df.expect_column_values_to_not_be_in_set('colB', [same list of values])
df.expect_column_values_to_not_be_in_set('colC', [same list of values])`

It would be very convenient to be able to apply these by just passing a list of columns instead of just the one. 
`df.expect_column_values_to_not_be_in_set(['colA', 'colB', 'colC'], [list of values])`

It may pose a headache when we consider Multi-column expectations (see #236 ), where we apply a single expectation to multiple columns vs. what I am proposing here, applying multiple expectations that are identical to multiple columns.

**Comment by jpcampb2** [comment]
I agree this case isn't well settled. See a tiny bit of old discussion in #10

**Comment by abegong** [comment]
What about a helper function like this?

```
ge.create_multiple_column_expectations(
    dataset=df,
    columns=['colA', 'colB', 'colC'],
    expectation_type='expect_column_values_to_not_be_in_set',
    kwargs={
        values=[list of values]
    }
)
```

**Comment by ccnobbli** [comment]
I added a helper function to ge.dataset.util that follows @abegong's suggestion. It makes sense to me, and it works!
