### ISSUE TITLE
'PandasDataset' object has no attribute 'expect_column_max_to_be_between_custom'

### ISSUE THREAD

**Issue by vmoulds01** [fivetran/great_expectations#2543]
Hello,

I was trying to write a custom v3 expectation and I was following the documentation - https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_and_editing_expectations/how_to_create_custom_expectations.html#how-to-guides-creating-and-editing-expectations-how-to-create-custom-expectations.

However, when i try out this new expectation I get the following error:

**_'PandasDataset' object has no attribute 'expect_column_max_to_be_between_custom'_**

Just wondering is there some step that isn't in the documentation that I am missing to be able to get this to work?  

I am thinking that the fact this function doesn't appear in pandas_dataset.py is the reason that this is failing but not sure.

Thanks for any help or advice you could provide.

Vicky

**Comment by peterdhansen** [comment]
If you are using the v3 custom expectation documentation. You have to use the v3 API for everything else.
So Batch Request and Validator instead of batch_kwargs and dataset.
Go here: https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_batches/how_to_load_a_pandas_dataframe_as_a_batch.html
and click V3 API

**Comment by vmoulds01** [comment]
Ok thanks for sharing that documentation.  I am new to Great Expectations so still learning so apologies if these are simple questions.

I tried to follow that document there for the RuntimeDataConnector and I am getting the following error message when trying to create the validator:

_**DataConnectorError: RuntimeDataConnector "csv_data_runtime_connector" requires batch_data and partition_request to be both present or both absent in the batch_request parameter.**_ 

I believe I do have them both in my batch request object from the following code:

```
batch_request = BatchRequest(
    datasource_name="csv_data_dir",
    data_connector_name="csv_data_runtime_connector",
    data_asset_name="transformed_train_data",
    batch_data=training_data_df,
    partition_request={
        "batch_identifiers": {
            "pipeline_stage": "ingestion step 1",
            "run_id": "run 18"
        }
    }
)
```

Is there something I am missing in my batchRequest?

**Comment by vmoulds01** [comment]
Never mind I resolved that issue by updating "batch_identifiers" to be "partition_identifiers" per runtime_data_connector.py validation code.  I was copying code from the documentation but it looks like it's slightly wrong for step 3. Construct a BatchRequest

**Comment by vmoulds01** [comment]
Oh another thing I noted that was slightly wrong in the documentation is that if you are using the runtime_data_connector then data_asset_name must be set to "IN_MEMORY_DATA_ASSET" in your batchRequest object else you will get an empty BatchDefinition returned from runtime_data_connector.py _get_batch_definition_list_from_batch_request() method.

**Comment by eugmandel** [comment]
@vmoulds01 The [V3 API](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/migrating_versions.html#v3-vs-v2-api) is still experimental, so the documentation needs improving. Thank you @peterdhansen for answering the original question. The "IN_MEMORY_DATA_ASSET" is a temporary limitation - of course you should be able to name the asset in order for this to be useful. This improvement is coming soon.

I am closing this issue, as the original question was resolved.
