### ISSUE TITLE
skip columns with high cardinality

### ISSUE THREAD

**Issue by gityow** [fivetran/great_expectations#2551]
**Is your feature request related to a problem? Please describe.**
I used the BasicProfiler on a 177M record table with 338 cols and it took 4.5 days to run. Most of my columns returned this:
`Failed to get cardinality of column <column name> - continuing...`

**Describe the solution you'd like**
 Most of my columns were continuous variables and I was wondering if there is a way to skip columns with high cardinality counts.

**Describe alternatives you've considered**
limit the expectations being ran using:
```
from great_expectations.dataset.sparkdf_dataset import SparkDFDataset
from great_expectations.profile.basic_dataset_profiler import BasicDatasetProfiler
scaffold_config = {
    "included_columns": ["col_name"],
    # "excluded_columns": [],
    "included_expectations": ["expect_table_row_count_to_be_between", "expect_column_values_to_not_be_null", "expect_column_values_to_be_in_set", "expect_column_kl_divergence_to_be_less_than"],
    # "excluded_expectations": [],
}
data = spark.sql("SELECT * FROM table")
spark_data = SparkDFDataset(data)
exp_suite = "suite_name.validate"
context.create_expectation_suite(exp_suite, overwrite_existing = True)
suite, evr = BasicDatasetProfiler().profile(batch, profiler_configuration=scaffold_config)
context.save_expectation_suite(suite, exp_suite)
```

**Additional context**
Ran on databricks cluster.

**Comment by peterdhansen** [comment]
Have you tried 
* `great_expectations.profile.basic_suite_builder_profiler` OR
* `great_expectations.profile.user_configurable_profiler`

**Comment by eugmandel** [comment]
@gityow The profiler can be configured to exclude some columns by name ("excluded_columns" config key). However, I would like to focus on the "Failed to get cardinality of column" error - we will triage this.

**Comment by eugmandel** [comment]
@gityow Having discussed this issue in our triage, we have a request for you - could you help us debug this?

Most likely, the underlying problem is an error in executing an Expectation that the profiler encounters.

Could you please replace the last four lines in your code snippet with this:

```
column = "TODO: ONE OF THE COLUMNS YOUR WERE GETTING THE ERROR ON"
batch.expect_column_unique_value_count_to_be_between(column, None, None)
batch.expect_column_proportion_of_unique_values_to_be_between(column, None, None)
```
?

Most likely, you will see an exception - please post the error and the stack trace.
Thank you!

**Comment by gityow** [comment]
@peterdhansen I tried the following 

```
from great_expectations.profile import BasicDatasetProfiler  
profile = my_df.profile(BasicDatasetProfiler)
```
and I got the same cardinality error again and again for all my columns. Is there a difference between using this and the options you provided?
```
great_expectations.profile.basic_suite_builder_profiler OR
great_expectations.profile.user_configurable_profiler
```

Hi @eugmandel , thanks for the response! Here is the error I get


```
AttributeError: 'BatchRequest' object has no attribute 'expect_column_unique_value_count_to_be_between'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-2661230912100884> in <module>
     15 )
     16 column = "<some column name>"
---> 17 batch.expect_column_unique_value_count_to_be_between(column, None, None)
     18 batch.expect_column_proportion_of_unique_values_to_be_between(column, None, None)

AttributeError: 'BatchRequest' object has no attribute 'expect_column_unique_value_count_to_be_between'
```


For completeness, here is the batch init
```
batch = BatchRequest(
    datasource_name="my_spark_datasource",
    data_connector_name=DATA_CONNECT_NM,
    batch_data=my_df,
    data_asset_name="cftm",
    partition_request={
        "partition_identifiers": {
            "pipeline_stage": "task_trx",
            "some_other_key_maybe_run_id": RUN_ID
        }
    }
)
```
