### ISSUE TITLE
Links on the readthedocs intro page aren't rendering correctly.

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#256]
http://great-expectations.readthedocs.io/en/latest/intro.html#what-is-great-expectations

For example:

<img width="711" alt="screen shot 2018-04-04 at 9 31 47 am" src="https://user-images.githubusercontent.com/1239085/38321002-155c61d4-37eb-11e8-96a1-1cbc247077b7.png">

**Comment by jpcampb2** [comment]
Oops...looks like an error when I put the new md version in directly. Fixing.
