### ISSUE TITLE
Duplicate subfolders in Data Docs URL

### ISSUE THREAD

**Issue by manishgk** [fivetran/great_expectations#2560]
**Describe the bug**
When GE opens Data Docs in the browser, the URL has duplicate subfolders under **/great_expectations/uncommitted/data_docs/local_site/validations** where it creates the .html file

**To Reproduce**
1. Go to Jupyter Notebook
2. Run all the cells and let the Data docs open
3. See the URL in the browser at the end where it shows the .html file

/**20210317T142217.448119Z**/**20210317T142217.448119Z**/6869f7f1d7e63d8e0ef5fd08db5ce7d8.html
Attached the tree structure for other files
![image](https://user-images.githubusercontent.com/41348103/111484909-2b3d7900-8704-11eb-99ca-5199d588753f.png)

**Expected behavior**
GE shouldn't create duplicate subfolders, in my example it should be
/**20210317T142217.448119Z**/6869f7f1d7e63d8e0ef5fd08db5ce7d8.html

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.13.10

**Additional context**
I'm on Windows 10 version 1903.

**Comment by eugmandel** [comment]
@manishgk Thank you reporting this! My understanding is that while the folder structure is duplicated, the URL is functional and Data Docs can open - please confirm.  If this is the case, I'll mark this issue as "help-wanted" for a community contributor.

**Comment by manishgk** [comment]
yes, it's functional and Data docs opens fine.
