### ISSUE TITLE
'Validator'  object has no attribute 'expect_column_chisquare_p_value_and_cramers_v_to_be_above_custom'

### ISSUE THREAD

**Issue by vmoulds01** [fivetran/great_expectations#2564]
**Describe the bug**
I am struggling to build a custom v3 expectation.  I followed the document https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_and_editing_expectations/how_to_create_custom_expectations.html and was able to get the custom expectation in the document working.  However, when I try and build my own custom TableExpectation for a chisqaured test that I want to implement then I get the following error:

**_great_expectations/validator/validator.py in __getattr__(self, name)
    161             return getattr(self.active_batch.data.dataframe, name)
    162         else:
--> 163             raise AttributeError(
    164                 f"'{type(self).__name__}'  object has no attribute '{name}'"
    165             )

AttributeError: 'Validator'  object has no attribute 'expect_column_chisquare_p_value_and_cramers_v_to_be_above_custom'_**

**To Reproduce**
1. I've created custom expectation in custom_expectations.core module within my great_expectations/plugins/ directory
2. I'm able to import this custom expectation ok into jupyter notebook so it does exist on my python path
3. When I try and call this custom validation it doesn't work.  However, I've similar setup for another custom expectation but it does work

**Expected behavior**
Expected behavior is that the custom expectation would be picked up as I've built it according to V3 API docs 

**Environment (please complete the following information):**
 - MacOS
 - Great Expectations Version: 0.13.12

**Comment by vmoulds01** [comment]
It looks like it might be to do with how I am naming the python function.  When I rename the ExpectColumnMaxToBeBetweenCustom function to something else then I am seeing the same error even though I was able to get this one working.

Is there a naming convention that needs to be followed for custom validations?

**Comment by eugmandel** [comment]
@vmoulds01 The CamelCase name of your Expectation's class is translated to snake_name of the Expectation. I would first check the name of the class. If it still does not work, you can attach your Expectation's code here, so that this issue can be reproduced.
