### ISSUE TITLE
Create an API to allow meta to act like a variable for expectations

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#257]
@jpcampb2 I was looking for documentation on this idea---couldn't find anything that described intended use cases and candidate APIs directly.

Imagine you're running data through an ETL process. The file started with 1,000 rows, and you want to ensure that no more than 2% of rows are lost in the process.

Then an API something like this could work:

```
my_df.expect_table_row_count_to_be_between(
    "my_column",
    min_value={"$meta" : "my_lower_bound"},
    max_value={"$meta" : "my_upper_bound"}
)
```

```
ge.validate(
    my_df, 
    expectation_config=my_config_json,
    meta={
        "my_lower_bound" : 980,
        "my_upper_bound" : 1000
    }
)
```

More to come. Throwing this out now for feedback/reactions...

**Comment by jpcampb2** [comment]
This issue is closed via parameterized expectations, yay! Check them out: http://great-expectations.readthedocs.io/en/latest/evaluation_parameters.html
