### ISSUE TITLE
Feature Request: Expect output of an anomaly detection model to be inlier

### ISSUE THREAD

**Issue by brunocous** [fivetran/great_expectations#2571]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I was thinking of an expectation that could take a Python anomaly detection model (see the ones offered by the [PyOD project](https://github.com/yzhao062/pyod)) as an input, and expect rows of a table to be inliers (=negate class in an anomaly detection task). That model should be able to train in an unsupervised context on an user-specified part of the data, and applied to unseen parts thereafter. 
It could be something in the lines of `expect_anomaly_detection_model_to_classify_row_as_inlier`.  

**Describe alternatives you've considered**
Not sure if that is possible, but if you're able to run a Python script or function (calling a `.fit` or a `.transform` on a anomaly detection model) on incoming data, you should already have enough with calling a `expect_column_values_to_be_between`-expectation on the outlier scores of the rows. 

**Additional context**
I am not that familiar yet with Great Expectations, but I'm investigating if I could this tool to do something more automatic than just setting expectations, or Great Expectations suggesting good expectations. If yes, and this FR is deemed relevant, I will put time in it.

**Comment by eugmandel** [comment]
@brunocous This how-to guide shows how to contribute a new Expectation to the library: https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_and_editing_expectations/how_to_contribute_a_new_expectation_to_great_expectations.html

**Comment by brunocous** [comment]
I'm not going to implement it using GE. It's going to be too heavy for the intended use. Closing this FR.
