### ISSUE TITLE
Dev environment setup fails due to missing required dependencies for pyspark package

### ISSUE THREAD

**Issue by jarandaf** [fivetran/great_expectations#2580]
**Describe the bug**
Setting up dev environment fails due to missing `pyspark` package dependency.

**To Reproduce**
1. Create an empty virtual environment and activate it.
2. Update pip: `pip install --upgrade pip`
3. Install dependencies: `pip install -r requirements-dev.txt -c constraints-dev.txt`
4. See error (related to `pyspark` package): `Could not import pypandoc - required to package PySpark`.

**Expected behavior**
Dependencies should be installed without errors.

**Environment (please complete the following information):**
 - Operating System: Mac OS Big Sur (11.2.2)
 - Great Expectations Version: 0.13.14 (commit 414e45ba9980fa033abf119e9c38421a807561c1)

**Additional context**
Installing `pypandoc` seems to fix the issue, so I guess it could be added to `requirements-dev-spark.txt`.

**Comment by eugmandel** [comment]
@jarandaf Good find! Can I ask you to create a PR with your suggested fix? Thank you!

**Comment by jarandaf** [comment]
I think this only appears in old pyspark versions (<2.4.7), see [here](https://github.com/apache/spark/pull/27376). I am not sure it is worth to be addressed.
