### ISSUE TITLE
GE github action fail for Snowflake tables

### ISSUE THREAD

**Issue by tomas-sobotik** [fivetran/great_expectations#2582]
**Describe the bug**
I have tried to use GE github action: https://github.com/great-expectations/great_expectations_action but the validation always fail for my Snowflake tables with following error:

`"No snowflake_transient_table specified. Snowflake with a query batch_kwarg will create "
ValueError: No snowflake_transient_table specified. Snowflake with a query batch_kwarg will create a transient table, so you must provide a user-selected name.` 

It looks like the GH action is using great_expectations==0.11.5 while the change to SF temp table behavior was released in 0.12.8. I am using GE 0.12.10

Because GH action does not allow to select which GE version should be used I did a workaround and create my own GitHub action which does following steps:

- install python
- install great expectations
- install sql alchemy
- install sql alchemy for snowflake (my DB)
- my repository checkout
- running the checkpoint 

Here I can specify which version of GE i want to use. 

**To Reproduce**
1. Use GE 0.12.10 and create some expectations on top of snowflake table
2. Create a checkpoint
3. Try to run the checkpoint through github action

**Expected behavior**
I think that it would be good if the github action allows to user to select which version of GE he wants to use.

**Environment (please complete the following information):**
 - Operating System: ubuntu-latest
 - Great Expectations Version: 0.12.10

**Comment by eugmandel** [comment]
@tomas-sobotik Thank you for reporting this - we will triage and respond shortly.

**Comment by eugmandel** [comment]
@tomas-sobotik I think the action allows to configure a specific version of Great Expectations (search https://github.com/great-expectations/great_expectations_action README for "version"). Then you can use the latest version that will not require to specify the table. Could you please try it? Thank you!

**Comment by tomas-sobotik** [comment]
@eugmandel Sorry for late reply. I think this version refers to version of the github action itself not the Great Expectations version. There you can choose v0.2 or v.0.1 which are versions of the actions.

I was checking the DOCKERFILE file of the action and it is using following docker image

`FROM greatexpectations/great_expectations:python-3.7-buster-ge-0.12.0`

I checked that image and it looks like it uses Great expectations version 0.12.0. The `great_expectations --version` command returns this: `great_expectations, version 0.12.0+0.g9701509a.dirty`

I think currently there is no way to select GE version which should be used by action.

**Comment by AFineDayFor** [comment]
Howdy @tomas-sobotik , closing this issue here; however, can you open one in the repo for the project it's self [great-expectations/great_expectations_action](https://github.com/great-expectations/great_expectations_action)
