### ISSUE TITLE
Can we remove the numpy<1.2 pin?

### ISSUE THREAD

**Issue by jtilly** [fivetran/great_expectations#2588]
numpy was pinned to <1.2 as part of https://github.com/great-expectations/great_expectations/commit/f904313ab3c67f57c3bf7575296d4dd7b4b1db47. The commit message says that this was meant to get rid of deprecation warnings. Is there a plan to remove this pin at some point? Which deprecation warnings are causing the problems here?

**Comment by eugmandel** [comment]
@jtilly We will triage today and respond.

**Comment by stonebig** [comment]
numpy-1.20.2 is out now. Is it functionnaly normal for great-expectations to depend so much of a numpy version ?

**Comment by lccambiaghi** [comment]
Hi, are there any updates on this issue? We would really love to remove this hard constraint on the numpy version

**Comment by mbakunze** [comment]
@eugmandel any update on this? This is blocking us to upgrade. Also blocking people with M1 Macs to run GE!

**Comment by bhcastleton** [comment]
@mbakunze - I see your comment. I'm talking with @jcampbell today to make sure we get an update on this and we'll post back here.

**Comment by bhcastleton** [comment]
@mbakunze - @jcampbell spent some time on this yesterday and merged a fix into develop. We're planning on a release tomorrow.
