### ISSUE TITLE
AttributeError: 'SqlAlchemyDatasource' object has no attribute 'get_batch_list_from_batch_request'

### ISSUE THREAD

**Issue by henriquejsfj** [fivetran/great_expectations#2607]
**Describe the bug**
Afaik `SqlAlchemyDatasource` seems to not be compatible with V3 API. I wasn't able to use it with BigQuery.

**To Reproduce**
1. Create a BigQuery Datasource
2. Try to run a checkpoint against it or to create new expectation doing `context.get_validator(batch_request=batch_request, expectation_suite=suite)`
4. See error: `AttributeError: 'SqlAlchemyDatasource' object has no attribute 'get_batch_list_from_batch_request'`

**Expected behavior**
A validator created or checkpoint running successfully.

**Environment (please complete the following information):**
 - Operating System: Linux Ubuntu 20.04
 - Great Expectations Version: 0.13.15
 
See: [Slack Topic](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1616349449083900)

**Comment by eugmandel** [comment]
@henriquejsfj You are right - SQLAlchemyDatasource is a class that belongs to V2 API. Please use this how-to guide to configure a V3 API Datasource for BigQuery: https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_datasources/how_to_configure_a_bigquery_datasource.html
