### ISSUE TITLE
[FEATURE] Value set expectations to display set difference in Expectation column of Data Docs in addition to expected value set

### ISSUE THREAD

**Issue by NathanFarmer** [fivetran/great_expectations#2643]
**Problem**
Some of my stakeholders will only be using visual inspection in the Data Docs. For expectations `expect_column_values_to_be_in_set` and `expect_column_values_to_not_be_in_set`, it becomes difficult to identify the issues with a failed test once the expected value set gets to be longer than a few values. For example, I currently expect the country codes in a certain field to be in a set of 100+ values. Can you identify all of the differences between the example sets below?

| Status | Expectation | Observed Value |
| ------------- | ------------- | ------------- |
| X | AE AF AG AL AR AS AT AU AW BA BB BD BE BG BH BM BN BO BQ BR BS BT BW BY BZ CA CD CH CK CL CM CN CO CR CW CY CZ DE DJ DK DM DO EC EE EG ES FI FJ FM FR GB GE GH GI GP GR GT GU GY HK HM HN HR HT HU IC ID IE IL IN IQ IS IT JM JO JP KE KG KH KI KN KR KY LA LB LC LK LT LU LV MA MC MM MN MO MQ MT MU MV MX MY N/A NA NC NG NI NL NO NP NZ OM PA PE PF PG PH PK PL PT PY QA RE RO SA SB SE SG SI SK SL SN SR SV SY TC TH TL TN TO TR TT TW UA UG US UY VE VG VI VN VU WS YT ZA ZM | ['0', '3M', 'AD', 'AE', 'AF', 'AG', 'AL', 'AM', 'AN', 'AO', 'AR', 'AS', 'AT', 'AU', 'AW', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BG', 'BH', 'BJ', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'ET', 'FI', 'FJ', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GN', 'GP', 'GQ', 'GR', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'IC', 'ID', 'IE', 'IL', 'IN', 'IQ', 'IS', 'IT', 'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KN', 'KR', 'KV', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'M', 'MA', 'MC', 'MD', 'ME', 'MG', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PR', 'PT', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'SV', 'SY', 'SZ', 'TC', 'TD', 'TG', 'TH', 'TJ', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VE', 'VG', 'VI', 'VN', 'VU', 'WS', 'XC', 'XK', 'YE', 'YK', 'YT', 'ZA', 'ZM', 'ZW'] |

**Proposed Solution**
I am proposing a change to the `expect_column_values_to_be_in_set` and `expect_column_values_to_not_be_in_set` expectations where a new key-value pair named "values_not_in_set" for the former and "values_in_set" for the later will be returned by the batch.expectation nested under "result". This new key-value pair would then be able to be passed to the checkpoint and the checkpoint would prepare the Data Docs output (I have not fully looked into the technical implementation of this, pending interest from others for a PR). This new key-value pair would be the result of the set operation Observed Value - Expectation and could be used to display the difference between the sets below the current output in the Expectation column. My apologies for the formatting, getting the markup to look like I want is a challenge.

| Status | Expectation | Observed Value |
| ------------- | ------------- | ------------- |
| X | AE AF AG AL AR AS AT AU AW BA BB BD BE BG BH BM BN BO BQ BR BS BT BW BY BZ CA CD CH CK CL CM CN CO CR CW CY CZ DE DJ DK DM DO EC EE EG ES FI FJ FM FR GB GE GH GI GP GR GT GU GY HK HM HN HR HT HU IC ID IE IL IN IQ IS IT JM JO JP KE KG KH KI KN KR KY LA LB LC LK LT LU LV MA MC MM MN MO MQ MT MU MV MX MY N/A NA NC NG NI NL NO NP NZ OM PA PE PF PG PH PK PL PT PY QA RE RO SA SB SE SG SI SK SL SN SR SV SY TC TH TL TN TO TR TT TW UA UG US UY VE VG VI VN VU WS YT ZA ZM **4 Unexpected values found**: 0, 3M, AD, AM, etc... | ['0', '3M', 'AD', 'AE', 'AF', 'AG', 'AL', 'AM', 'AN', 'AO', 'AR', 'AS', 'AT', 'AU', 'AW', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BG', 'BH', 'BJ', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'ET', 'FI', 'FJ', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GN', 'GP', 'GQ', 'GR', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'IC', 'ID', 'IE', 'IL', 'IN', 'IQ', 'IS', 'IT', 'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KN', 'KR', 'KV', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'M', 'MA', 'MC', 'MD', 'ME', 'MG', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PR', 'PT', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'SV', 'SY', 'SZ', 'TC', 'TD', 'TG', 'TH', 'TJ', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VE', 'VG', 'VI', 'VN', 'VU', 'WS', 'XC', 'XK', 'YE', 'YK', 'YT', 'ZA', 'ZM', 'ZW'] |

**Alternative Solutions**
I considered changing the "observed_value" key-value pair instead of creating a new key-value pair, but figured this would cause backward compatibility issues.
I considered a new column in the Data Docs (possibly named something like "Difference") but I noticed that among other expectations the output in the Expectation and Observed Value columns is not standard and could be changed here as well.

I am willing to work on a PR to implement this, if the community decides that it is something that would add value!

**Comment by eugmandel** [comment]
@NathanFarmer This sounds like a solid proposal - would you like to create a PR? Thank you!

**Comment by NathanFarmer** [comment]
@eugmandel I am working on a PR for this.

**Comment by NathanFarmer** [comment]
Update: there is not currently an active/planned PR for this.

**Comment by talagluck** [comment]
Thanks, @NathanFarmer! We've logged this feature request,and are going to close this for now. If you or anyone else is interested in making a contribution, please feel free to re-open or let us know. Thanks!
