### ISSUE TITLE
expect_column_values_to_be_in_set only works when values_set is list

### ISSUE THREAD

**Issue by lyra-victor** [fivetran/great_expectations#2646]
**Describe the bug**

I create a validator and some expectations on some data. I then save the expectations and noticed that `value_set` is `null`  in my `expecations/suite.json` for the expectation `expect_column_values_to_be_in_set`. The reason is in the `"exception_message": "Object of type set is not JSON serializable"`. If I change the `value_set` to type `list` it works

**To Reproduce**
```python


import great_expectations as ge
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.cli.datasource import sanitize_yaml_and_save_datasource

import pandas as pd


context = ge.get_context()
df = pd.DataFrame({"col1": ["a", "a", "b", "c"], "col2": [1, 2, 3, 4]})
config = """
    name: my_pandas_datasource
    class_name: Datasource
    execution_engine:
        class_name: PandasExecutionEngine
    data_connectors:
        my_runtime_data_connector:
          class_name: RuntimeDataConnector
          batch_identifiers:
              - some_batch_identifier_so_this_can_work
"""



context.test_yaml_config(
    yaml_config=config
)
sanitize_yaml_and_save_datasource(context, config, overwrite_existing=True)


runtime_batch_request = RuntimeBatchRequest(
    datasource_name="my_pandas_datasource",
    data_connector_name="my_runtime_data_connector",
    data_asset_name="insert_your_data_asset_name_here",
    runtime_parameters={
      "batch_data": df
    },
    batch_identifiers={
        "some_batch_identifier_so_this_can_work": "blah",
    }
)
suite = context.create_expectation_suite("my_test_suite")
my_validator = context.get_validator(
    batch_request=runtime_batch_request,
    expectation_suite=suite
    
)

my_validator.expect_column_values_to_be_in_set("col1", {"a", "b"})

```

**Expected behavior**
I expected the last line above to work. Instead it gives me an error with `"exception_message": "Object of type set is not JSON serializable"`

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.17

**Additional context**
None

**Comment by eugmandel** [comment]
@lyra-victor This argument should be a list. It is possible to make it more flexible, but I don't believe it is a priority right now.
