### ISSUE TITLE
SQLAlchemy v. 1.4 changes RowProxy to Row and makes ge.dataset.sqlalchemy_dataset fail to load sa

### ISSUE THREAD

**Issue by calderonjesus** [fivetran/great_expectations#2650]
**Describe the bug**
In SQLAlchemy's update to version 1.4 [renamed the class RowProxy to Row and the Row class is no longer a Proxy](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#rowproxy-is-no-longer-a-proxy-is-now-called-row-and-behaves-like-an-enhanced-named-tuple). This affects Great Expectation's [`ge.dataset.sqlachemy_dataset`](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/dataset/sqlalchemy_dataset.py) module, which expects a RowProxy instead of a Row (line 36). As a consequence, querying a table via sqlalchemy fails and profiles and suites cannot be created.

**To Reproduce**
1. Install Great Expecations and SQL Alchemy **version 1.4**.
2. Setup a new data source using SQL Alchemy, in this case, I used MS SQL server.
3. Create data source and attempt to create a new profile or suite.
4. In the JupyterNotebook's first chunk, the line that reads `batch = context.get_batch(batch_kwargs, suite)` fails with the following error:

```
2021-03-31T13:53:38-0300 - INFO - Great Expectations logging enabled at 20 level by JupyterUX module.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-7b07895e397c> in <module>
     14 
     15 batch_kwargs = {'table': 'my_table', 'schema': 'my_schema', 'data_asset_name': 'my_schema.my_table', 'datasource': 'my_schema_dsa'}
---> 16batch = context.get_batch(batch_kwargs, suite)
     17 batch.head()

c:\users\my_user\work\data_quality\dq_env\lib\site-packages\great_expectations\data_context\data_context.py in get_batch(self, arg1, arg2, arg3, **kwargs)
   1419             data_asset_type = arg3
   1420         batch_parameters = kwargs.get("batch_parameters")
-> 1421         return self._get_batch_v2(
   1422             batch_kwargs=batch_kwargs,
   1423             expectation_suite_name=expectation_suite_name,

c:\users\my_user\work\data_quality\dq_env\lib\site-packages\great_expectations\data_context\data_context.py in _get_batch_v2(self, batch_kwargs, expectation_suite_name, data_asset_type, batch_parameters)
   1145             expectation_engine=data_asset_type,
   1146         )
-> 1147return validator.get_dataset()
   1148 
   1149     def _get_batch_v3(

c:\users\my_user\work\data_quality\dq_env\lib\site-packages\great_expectations\validator\validator.py in get_dataset(self)
   1429             init_kwargs = self.batch.data.get_init_kwargs()
   1430             init_kwargs.update(self.init_kwargs)
-> 1431             return self.expectation_engine(
   1432                 batch_kwargs=self.batch.batch_kwargs,
   1433                 batch_parameters=self.batch.batch_parameters,

c:\users\my_user\work\data_quality\dq_env\lib\site-packages\great_expectations\dataset\sqlalchemy_dataset.py in __init__(self, table_name, engine, connection_string, custom_sql, schema, *args, **kwargs)
    508                 temp_table_schema_name = conn_object.engine.url.query.get("schema")
    509 
--> 510self._table = sa.Table(table_name, sa.MetaData(), schema=schema)
    511 
    512         # Get the dialect **for purposes of identifying types**

AttributeError: 'NoneType' object has no attribute 'Table'
```

**Expected behaviour**
Great Expectations should be able to connect to DB and obtain data from the source.

**Environment (please complete the following information):**
 - Operating System: Windows 10 Pro
 - Great Expectations Version: 0.13.15
 - SQLAlchemy Version: 1.4.0

**Additional context**
Install and use SQLAlchmeny Version < 1.4 as a workaround.

**Comment by Shinnnyshinshin** [comment]
Hi @calderonjesus thank you for submitting this issue. We're attempting to address this issue in the following PR, which is still a WIP. I'll be sure to update you when there is more definite progress

https://github.com/great-expectations/great_expectations/pull/2641

**Comment by Shinnnyshinshin** [comment]
https://github.com/great-expectations/great_expectations/pull/2641 has been merged :) Thank you for your patience with this issue @calderonjesus

**Comment by calderonjesus** [comment]
Thank you!
