### ISSUE TITLE
Hierarchical multi-column expectations

### ISSUE THREAD

**Issue by bouke-nederstigt** [fivetran/great_expectations#266]
I've been keeping an eye on the multi-column expectations. I think the work so far looks great. I was wondering if you guys considered hierarchical expectations based on multiple columns?

So something like the following. IF column A == y expect column B in set (z,x). Do you think this would be useful to have in the great_expectations package, or should I just implement it as a custom expectation?

**Comment by abegong** [comment]
Do you have a use case in mind?

This seems similar to `expect_column_pair_values_to_be_in_set`:

```
A     B
------
y     x
y     z
w     ?
v     ?
```

Maybe there's some way to accomplish this with wildcard values...?

**Comment by bouke-nederstigt** [comment]
Mm, this seems to be in the right direction. However it doesn't quite offer the right functionality, or I'm having a hard time understanding how to use it correctly.

My example use case would be checking categorisation of products. My dataset is a list of products, and each product has a group and a category. Groups are e.g. food or drinks, and categories are e.g wine or beer. Obviously wine and beer are only acceptable for products that are in the drinks group, but not those in the food group. 

A              B       Result
---------------------  
Food      None     True
Drinks    Beer     True
Drinks    Wine     True
Food      Beer     False

From the docs / code it doesn't become completely clear to me on how to execute the ```expect_column_pair_values_to_be_in_set```. The docs in base.py specify value_pairs_set to be a list of lists. But I can only run the method successfully using a list with a single tuple of two values. So e.g. ```df.expect_column_pair_values_to_be_in_set('Group', 'Category', [("Drinks", "Beer")])```. This doesn't give me the option to specify multiple values in the category column for Drinks, or ignore anything in the food column.

Hopefully it's clear what I'm getting at?

As a side note I ran into the following issue:
 
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''.

 But this could easily be solved by changing `np.isnan` to `pd.isnull` in `pandas_dataset.expect_column_pair_values_to_be_in_set`.  Is this intended behaviour or should I commit this fix?

**Comment by bouke-nederstigt** [comment]
Never mind the first issue above. A good night sleep solved the issue as usual. The ```expect_column_pair_values_to_be_in_set``` definitely solves the issue. Small improvement might be to change the docs from ```value_pairs_set (list of lists)``` to ```value_pairs_set (list of tuples)```

The TypeError for columns with object type still stands though.

**Comment by jpcampb2** [comment]
@bouke-nederstigt Great! Your PR is in for fixing the TypeError. Is this issue ready to close?

**Comment by bouke-nederstigt** [comment]
Yeah, the issue can be closed!
