### ISSUE TITLE
Airflow plugin

### ISSUE THREAD

**Issue by bouke-nederstigt** [fivetran/great_expectations#267]
We'll be running great_expectations as part of our ETL pipelines, and those are managed by Airflow. As such it'd be great to have an airflow plugin as part of the great_expectations package. I'll be creating this for internal use in the next couple of weeks anyway, happy to share in case you guys think it would be nice to include in the great expectations package.

In case you agree I'd like to hear your thoughts on what functionality should definitely be in the plugin. As far as I'm concerned it should have an operator to execute expectation json files. Perhaps it would be nice if expectation output is nicely formatted in the admin interface as well.

Finally it's probably a good idea to be able to specify where expectation output should be stored (if not viewed in the admin interface) e.g. S3, or a database. This is another thing I've been thinking about (slightly related). Perhaps it's an idea to be able to dump expectation output to the database, that way it becomes possible to track data quality over time. However, I can also imagine this might be too specific of a use-case to make it part of the base package.

Anyhow, let me know what you guys think and/or if you it should be part of the package at all.

Cheers.

**Comment by bouke-nederstigt** [comment]
#104

**Comment by jpcampb2** [comment]
We've talked about but not yet implemented anything in this space, so would definitely like to have the contribution! #104 also aimed at providing an example and documentation, but it hasn't risen to the priority list yet, so we'll be able to close that issue too with your submission, I hope!
