### ISSUE TITLE
Comments not rendering in Data Docs and Validator output for v3 API

### ISSUE THREAD

**Issue by anthonyburdi** [fivetran/great_expectations#2674]
**Describe the bug**
When using the v3 API to edit an Expectation Suite and adding comments per [How to add comments to Expectations and display them in Data Docs](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_data_docs/how_to_add_comments_to_expectations_and_display_them_in_data_docs.html) the comments appear in the json on-disk Suite but are not rendered in the validator output and not in Data Docs.

**To Reproduce**
1. Create or edit an expectation suite `great_expectations --v3-api suite new`
2. Add expectations with notes e.g. in the examples below
3. Notes don't appear in validator.expect_* output
4. View the my_expectation_suite_name.json and see the notes
5. View data docs and notes do not appear

Notes not showing in validator:
![image](https://user-images.githubusercontent.com/9903066/114732836-d8f67480-9d10-11eb-919d-ad4b4acee34d.png)
![image](https://user-images.githubusercontent.com/9903066/114732879-deec5580-9d10-11eb-879c-e407917206f3.png)
Notes showing in suite .json file
![image](https://user-images.githubusercontent.com/9903066/114733028-ff1c1480-9d10-11eb-975d-a415d09e1617.png)
Notes not showing in Data Docs:
![image](https://user-images.githubusercontent.com/9903066/114733077-093e1300-9d11-11eb-9e42-30bf467cdf05.png)
![image](https://user-images.githubusercontent.com/9903066/114733112-122ee480-9d11-11eb-99fe-7e8366f9e0dc.png)

**Expected behavior**
Notes should be rendered as they are in the v2 API as documented here: [How to add comments to Expectations and display them in Data Docs](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_data_docs/how_to_add_comments_to_expectations_and_display_them_in_data_docs.html)

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.17

**Additional context**

**Comment by AFineDayFor** [comment]
Closing and connecting with 3917.
