### ISSUE TITLE
Make `ipywidgets` an optional dependency

### ISSUE THREAD

**Issue by twcurrie** [fivetran/great_expectations#2688]
**Is your feature request related to a problem? Please describe.**
Great expectation's dependency on `ipywidgets` constrains the ways the library can be used.  `ipywidgets` is utilized as a core part of `jupyter`'s requirements, but through that library's use of iPython, the transitive dependencies can block other libraries that may have differing or competing libraries/dependencies for visualization.  

Furthermore, this dependency creates a transitive dependency on `tornado`.  This is a major blocker for usage within Apache Airflow and potentially other libraries and frameworks.    

**Describe the solution you'd like**
From my perspective, I think moving forward with an optional requirement of ipywidgets would be ideal.  Not all use cases of great expectation require a heavyweight interactive shell, widgets and visualizations.  With this approach, the typical install of:
```bash 
pip install great_expectations
```
would not install the ipywidgets dependency.  This could be issued within Apache Airflow, command line tools and with other frameworks and libraries.

The issue with this approach is the typical install for those who want to utilize it in jupyter would need to perform the command: 
```bash
pip install great_expectations[ipywidgets]
```    
The typical extensions and widgets provided within a jupyter notebook would not be available without this optional `extra`.  This would force updates in likely _a lot_ of documentation.  

However, this install approach would provide the minimum level of requirements to a user and in my opinion, that makes this library more accessible and portable to a wider array of projects. 

**Describe alternatives you've considered**
An alternative approach would be to also package a `great_expecations_cli` as part of the build.  This package would not include ipywidgets.  This approach is also acceptable. 

**Additional context**
I have seen some efforts to develop a [library of Airflow operators for great_expectations](https://github.com/great-expectations/airflow-provider-great-expectations).  I think this would simplify some of that work.

**Comment by eugmandel** [comment]
@twcurrie thank you for posting this idea! It is a good suggestion. Based on the core team's current backlog, this is unlikely to be implemented in the near future, so we are inviting a community contribution.

**Comment by twcurrie** [comment]
@eugmandel Does the core team find the desired solution acceptable or prefer the alternate one?  These are feasible changes for the community to complete, but they do have quite different implications on the repo's code publishing and the user onboarding experience.
