### ISSUE TITLE
🐛 Meta(data) added to "Table Shape"-expectations are saved to the Expectation Store, but not displayed in Jupyter when editing the suite

### ISSUE THREAD

**Issue by Patechoc** [fivetran/great_expectations#2692]
**Describe the bug**

While adding custom information to every expectations' metadata passing a dictionary to the `meta` parameter of these expectations, all get stored in the Expectation Store.
However, editing the expectation suite displays the added meta(data) except for the "Table Shape" type of expectation.

**To Reproduce**
1. Create an expectation suite, from scratch or using "demo" or "scaffold"
2. Make sure you create/have a Table Shape expectation (expect_table_row_count_to_be_between, expect_table_column_count_to_equal, ...) and add metadata to it  `batch.expect_table_row_count_to_be_between(min_value=1, meta={"type":"expect_table_..."})`
3. Make sure you create/have other type of expectations (expect_column_values_to_not_be_null, expect_column_value_lengths_to_be_between, ...) and add metadata to it `batch.expect_column_value_lengths_to_be_between(
    column="STATION_NAME", max_value=8, min_value=1, meta={"type":"anything but Table Shape expectation"}`
4. Save your expectation suite
5. delete your local version of the Jupyter notebook
6. edit your suite: `great_expectations suite edit my_suite`

**Expected behavior**
You should see that the Table Shape expectations do no display the metadata you added as part of the parameters while other expectations will show them.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.9

**Comment by eugmandel** [comment]
@Patechoc This does look like a bug - thank you for reporting it.

**Comment by austiezr** [comment]
Hey @Patechoc! Thank you for raising this. I believe this has now been resolved by #3129; closing for now, please feel free to reopen if this issue isn't resolved for you by #3129.
