### ISSUE TITLE
Bug: Creating suites from `.csv.gz` files on S3

### ISSUE THREAD

**Issue by luke321321** [fivetran/great_expectations#2694]
**Describe the bug**
When creating a suite on S3 using `.csv.gz` files the `read_options` aren't passed to the `batch_kwargs`.  So the `datasource` doesn't know it should try to decompress the file.  This is using `v2` of the CLI.

**To Reproduce**
1. Have a `.csv.gz` on S3
2. Try to scaffold a suite on the CLI

![Screenshot 2021-04-19 at 16 25 24](https://user-images.githubusercontent.com/1042275/115261980-03d73300-a12c-11eb-8aa4-37dd917015f5.png)

**Expected behavior**
Great Expectations to detect the read options needed, as it does in other contexts, and use these

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.17

**Additional context**
I'll submit a PR to fix this

**Comment by eugmandel** [comment]
@luke321321 Our favorite issues are the ones that come with a PR that fixes them :) - thank you!
