### ISSUE TITLE
"Tuple index out of range" for running checkpoint with snowflake datasource

### ISSUE THREAD

**Issue by Kwarks85** [fivetran/great_expectations#2709]
**Describe the bug**
When trying to run a checkpoint with a single expectation against a snowflake datasource I receive an error running "update_data_docs" that says "Tuple index out of range" I thus cannot setup a running checkpoint for my expectations

**To Reproduce**
Set up datasource based on snowflake. The connection and validation works just fine. This is the code from the yml that configures the datasource

```
my_snowflake_datasource_1:
    class_name: SimpleSqlalchemyDatasource
    credentials:
      drivername: snowflake
      username: GREATEXPECTATIONS
      password: [redacted]
      host: [account@snowflake]
      database: RAW
      query:
        schema: EXCHANGERATES
        warehouse: REPORTING
        role: REPORTER
    Data connectors:
        whole_table : SqlDataConnector
    introspection:
       whole_table:
            data_asset_name_suffix: __whole_table
```

Set up expectation suite that could connect to data source and configured a checkpoint that looks like this

```
name: test_checkpoint_2
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template:
expectation_suite_name:
batch_request:
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: my_snowflake_datasource_1
      data_connector_name: whole_table
      data_asset_name: stg_exchangerates__whole_table
      expectation_suite_name: exchangerate_v31
profilers: []
```

Then running `great_expectations --v3-api checkpoint run test_checkpoint_2`
I receive the following error
```
Error running action with name update_data_docs
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\great_expectations\validation_operators\validation_operators.py", line 388, in _run_actions
    action_result = self.actions[action["name"]].run(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\great_expectations\checkpoint\actions.py", line 58, in run
    return self._run(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\great_expectations\checkpoint\actions.py", line 935, in _run
    self.data_context.build_data_docs(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\great_expectations\core\usage_statistics\usage_statistics.py", line 262, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\great_expectations\data_context\data_context.py", line 2384, in build_data_docs
    index_page_resource_identifier_tuple = site_builder.build(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\great_expectations\render\renderer\site_builder.py", line 293, in build
    site_section_builder.build(resource_identifiers=resource_identifiers)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\great_expectations\render\renderer\site_builder.py", line 388, in build
    source_store_keys = self.source_store.list_keys()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\great_expectations\data_context\store\store.py", line 142, in list_keys
    return [self.tuple_to_key(key) for key in keys_without_store_backend_id]
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\great_expectations\data_context\store\store.py", line 142, in <listcomp>
    return [self.tuple_to_key(key) for key in keys_without_store_backend_id]
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\great_expectations\data_context\store\store.py", line 110, in tuple_to_key
    return self._key_class.from_tuple(tuple_)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\great_expectations\data_context\types\resource_identifiers.py", line 164, in from_tuple
    RunIdentifier.from_tuple((tuple_[-3], tuple_[-2])),
IndexError: tuple index out of range
tuple index out of range

```
**Expected behavior**
Expected the checkpoint to run properly as all preview validations in test yml files worked fine except for running the actual checkpoint

**Environment (please complete the following information):**
 - Operating System: running on a virtual machine Microsoft Windows 2019 Server datacenter hosted on AWS
 - Great Expectations Version:  0.13.17

**Comment by eugmandel** [comment]
@Kwarks85 "site_names: []" looks suspicious - could you please remove this line, rerun and report back? Thank you!

**Comment by Kwarks85** [comment]
@eugmandel updated the checkpoint as suggested by you and still receive the same error. Anything else I can provide as reference?

**Comment by Faith-des** [comment]
I also have the same issue. Some updates?

**Comment by talagluck** [comment]
Hi @Kwarks85 - so sorry for delays. Could you please confirm whether this is still an issue on the latest version?

**Comment by vgcshub** [comment]
@talagluck 
yes still getting same issue on spark

**Comment by talagluck** [comment]
Hi @vgcshub - could you please include your project and checkpoint config?

**Comment by vgcshub** [comment]
@talagluck sorry for delay Here is my config
Running on AWS Glue spark enviroument
`#Initiate great_expectations context
data_context_config = DataContextConfig(
    config_version=3,
    plugins_directory=None,
    config_variables_file_path=None,
    datasources={
        "my_spark_datasource": {
            "class_name": "Datasource",
            "module_name": "great_expectations.datasource",
            "execution_engine": {
                "class_name": "SparkDFExecutionEngine",
                "force_reuse_spark_context": True,
            },
            "data_connectors": {
                "my_runtime_data_connector": {
                    "class_name": "RuntimeDataConnector",
                    "module_name": "great_expectations.datasource.data_connector",
                    "batch_identifiers": {
                        "e": "1"
                    },
                }
            },
        }
    },
    stores={
        "expectations_S3_store": {
            "class_name": "ExpectationsStore",
            "store_backend": {
                "class_name": "TupleS3StoreBackend",
                "bucket": args['GE_S3_STORE'], #Bucket storing great_expectations suites results
                "prefix": f"{args['GE_EXPECTATIONS']}/", #Trailing slash is important
            },
        },
        "validations_S3_store": {
            "class_name": "ValidationsStore",
            "store_backend": {
                "class_name": "TupleS3StoreBackend",
                "bucket": args['GE_S3_STORE'],
                "prefix":f"{args['GE_VALIDATON_RESULT']}/"
            },
        },
        "checkpoint_S3_store": {
            "class_name": "CheckpointStore",
            "store_backend": {
                "class_name": "TupleS3StoreBackend",
                "bucket": args['GE_S3_STORE'],
                "prefix": f"{args['GE_CHECKPOINT']}/"
            },
        },
        "evaluation_parameter_store": {"class_name": "EvaluationParameterStore"},
    },
    expectations_store_name="expectations_S3_store",
    validations_store_name="validations_S3_store",
    checkpoint_store_name="checkpoint_S3_store",
    evaluation_parameter_store_name="evaluation_parameter_store",
    store_backend_defaults=S3StoreBackendDefaults(default_bucket_name=args['GE_S3_STORE']),
    data_docs_sites={
        "s3_site": {
            "class_name": "SiteBuilder",
            "store_backend": {
                "class_name": "TupleS3StoreBackend",
                "bucket":  args['GE_S3_STORE'],
                "prefix":  "adata_docs",
            },
            # "site_index_builder": {
            #     "class_name": "DefaultSiteIndexBuilder",
            #     "show_cta_footer": True,
            # },
        }
    },
    validation_operators={
        "action_list_operator": {
            "class_name": "ActionListValidationOperator",
            "action_list": [
                {
                    "name": "store_validation_result",
                    "action": {"class_name": "StoreValidationResultAction"},
                },
                {
                    "name": "store_evaluation_params",
                    "action": {"class_name": "StoreEvaluationParametersAction"},
                },
                # {
                #     "name": "update_data_docs",
                #     "action": {"class_name": "UpdateDataDocsAction"},
                # },
            ],
        }
    },
    anonymous_usage_statistics={
      "enabled": False
    }
)

print("GE DATA CONTEXT CONFIG", data_context_config)

context = BaseDataContext(project_config=data_context_config)


batch_kwargs = {'dataset': df1, 'datasource': 'my_spark_datasource'}

expectation_suite_name = args['SUITE_FILE_NAME']

suite: ExpectationSuite = context.get_expectation_suite(expectation_suite_name)


runtime_batch_request = RuntimeBatchRequest(
    datasource_name="my_spark_datasource",
    data_connector_name="my_runtime_data_connector",
    data_asset_name="vendor_table",
    runtime_parameters={
      "batch_data": df1
    },
    batch_identifiers={
        "e": "1"
    }
)


my_validator: Validator = context.get_validator(
    batch_request=runtime_batch_request,
    expectation_suite=suite,  # OR
    # expectation_suite_name=suite_name
)
print(my_validator.head())

print("going to validate")
result = my_validator.validate()
print(f"result {result}")




print("result message here")


batch_request = runtime_batch_request
checkpoint_config = {
    "class_name": "SimpleCheckpoint",
    "validations": [
        {
            "batch_request": batch_request,
            "expectation_suite_name": expectation_suite_name
        }
    ]
}
checkpoint = SimpleCheckpoint(
    f"_tmp_checkpoint_{expectation_suite_name}",
    context,
    **checkpoint_config
)
checkpoint_result = checkpoint.run()`

**Comment by vgcshub** [comment]
Getting the following Error

Error running action with name update_data_docs Traceback (most recent call last): File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/validation_operators/validation_operators.py", line 455, in _run_actions checkpoint_identifier=checkpoint_identifier, File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/checkpoint/actions.py", line 69, in run **kwargs, File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/checkpoint/actions.py", line 1008, in _run expectation_suite_identifier, File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 263, in usage_statistics_wrapped_method result = func(*args, **kwargs) File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 2620, in build_data_docs build_index=(build_index and not self.ge_cloud_mode), File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 303, in build site_section_builder.build(resource_identifiers=resource_identifiers) File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/render/renderer/site_builder.py", line 406, in build source_store_keys = self.source_store.list_keys() File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 172, in list_keys return [self.tuple_to_key(key) for key in keys_without_store_backend_id] File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 172, in <listcomp> return [self.tuple_to_key(key) for key in keys_without_store_backend_id] File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 133, in tuple_to_key return self.key_class.from_tuple(tuple_) File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/data_context/types/resource_identifiers.py", line 165, in from_tuple RunIdentifier.from_tuple((tuple_[-3], tuple_[-2])), IndexError: tuple index out of range``

**Comment by kenwade4** [comment]
This seems to be a configuration issue. We are going to work on improving the error messaging around this so that the actual problem is more clear.

**Comment by rakeshgirase** [comment]
I am also facing same issue and was wondering what was the exact config issue here?
