### ISSUE TITLE
Deal with MySQL returning decimal.Decimal

### ISSUE THREAD

**Issue by bouke-nederstigt** [fivetran/great_expectations#271]
The count query 

```
count_query = sa.select([
                sa.func.count().label('element_count'),
                sa.func.sum(
                    sa.case([(sa.column(column) == None, 1)], else_=0)
                ).label('null_count'),
                sa.func.sum(
                    sa.case([(sa.not_(expected_condition), 1)], else_=0)
                ).label('unexpected_count')
            ]).select_from(sa.table(self.table_name))
```

to calculate succes, percent_success etc. in sqlalchemy_dataset.MetaSqlAlchemyDataset returns decimal.Decimal types when executed (at least on my MySQL db). 
This in turn results ```TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'``` in the ```_format_column_map_output``` and ```_calc_map_expectation_success``` methods of the Dataset class.

Easy fix would be to remove the cast of success_count to float in the ```_format_column_map_output```, or also cast nonnull_count to float. This doesn't seem to break any tests or functionality. Just wondering if that cast is there for a reason?

Other solution is to make sure that sqlalchemy returns an int, or cast the decimal to int.

**Comment by jpcampb2** [comment]
I agree--the correct fix is to remove the cast to `float` in _format_column_map_output and _calc_map_expectation_success. They are there to support python 2 compatibility, but the better approach there is to ensure that the change also imports python 3 division: `from __future__ import division` in base.py.
