### ISSUE TITLE
Difficult to know what metrics are collected, and to save all by default

### ISSUE THREAD

**Issue by kconvey** [fivetran/great_expectations#2715]
**Is your feature request related to a problem? Please describe.**
It would be nice to know "what metrics am I computing?" and to be able to say "record _all_ metrics in a MetricStore" (as opposed to specifying them explicitly). This is particularly useful if great expecations is used in evaluating metrics, but those metrics may be used downstream by another tool (ex. a dashboarding tool), without having to do a lot of guesswork / trial and error to save most/all metrics explicitly.

**Describe the solution you'd like**
Presumably, the metrics computed for an Expectation Suite should be determined from the Expectation Configurations for that suite, and it shouldn't require evaluation to know what they are.

It should be possible to list these metrics, given an Expectation Suite, and there should be a way to record all computed metrics in a MetricStore.

**Describe alternatives you've considered**
This may not be a heavily demanded feature, so maybe it isn't worth supporting.

**Additional context**
As far as I could tell, the logic for what metrics are "gettable" on a validation result object exists [here](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/core/expectation_validation_result.py#L181), but I don't know a lot else

**Comment by jcampbell** [comment]
We're actively improving the MetricStore right now, in part to enable exactly this sort of feature, as part of the Multi-batch Profiling work going on. I think this is a great use case, and we'll work to expose it more directly.

Let's leave this issue open so we can circle back as needed and flag for people the work; @kconvey if you'd like to chat with the team working on the issue, please ping @OrtalG .

**Comment by AFineDayFor** [comment]
Howdy @kconvey,

Currently this is in the road-map, we're going to go ahead and close this for now. We will be very public when it's released. Make sure to check out the community meetups as well!
