### ISSUE TITLE
Bug: Variable name in v3-api checkpoint new notebook is invalid when using "." in checkpoint name

### ISSUE THREAD

**Issue by spbail** [fivetran/great_expectations#2717]
**Describe the bug**
The boilerplate in the notebook creates an invalid variable name when using "." in the checkpoint name, see description and screenshot.

**To Reproduce**
- Run `great_expectations --v3-api checkpoint new my.checkpoint.name`
- Notebook opens
- The second code cell will look like this:

```
my_checkpoint_name = "my.checkpoint.name"  # This was populated from your CLI command.

my.checkpoint.name_config = f"""
(more yaml here)
"""
print(my.checkpoint.name_config)
```
where `my.checkpoint.name_config` is not a valid variable name in python, hence the print statement throws an error. I assume this will be the same when using other invalid characters.

**Workaround**
Manually change the config variable name.

**Expected behavior**
The variable name should just be `config` or `checkpoint_config` and doesn't need the checkpoint name prefix. 

**Environment (please complete the following information):**
 - Operating System: Mac OS Big Sur
 - Great Expectations Version: 0.13.18

**Additional context**
See screenshot.

![Screen Shot 2021-04-22 at 3 15 57 PM](https://user-images.githubusercontent.com/1734474/115773794-90206a80-a365-11eb-9b30-97fbcea99c50.png)

**Comment by eugmandel** [comment]
Hi @spbail - it is a good find! Any chance you could fix as part of your getting started tutorial work or should we ask the engineering to fix this?

**Comment by spbail** [comment]
I'm taking this one!
