### ISSUE TITLE
when % sign is used in query GE adds escape characters in the condition, which results in unsupported character at SQL engine

### ISSUE THREAD

**Issue by gadekarabhijit** [fivetran/great_expectations#2727]
**If we use a special character in where the condition of a query, GE adds escape characters**
When % sign is used in query GE adds escape characters in the condition, which results in unsupported character at SQL engine

**To Reproduce**
1. Create batch kwargs with query having % sign as below
```
batch_kwargs = {
    "data_asset_name": "custom_sql_query",
    "datasource": "athena",
    "query": """select * from "db_name"."table_name" where not asset_manager_id like '0C%'"""
}
```
2. Create a batch for the above kwargs

while GE trying to create a batch encounters an issue in the SQL engine and throws the below error.
```
packages\pyathena\formatter.py in format(self, operation, parameters)
    167                 )
    168 
--> 169         return (operation % kwargs).strip() if kwargs is not None else operation.strip()
ValueError: unsupported format character ''' (0x27) at index 151
```
when I try to debug I found that GE format above query as below, it adds escape(\) character in the query as below.

```
CREATE TEMPORARY TABLE "ge_tmp_8bd16457" AS select * from "managed_investment__esg__stg"."esg_commitment_levels_asset_manager" where not asset_manager_id like \'0C%\'
```
**Expected behavior**
The query must be something below
```
CREATE TEMPORARY TABLE "ge_tmp_8bd16457" AS select * from "managed_investment__esg__stg"."esg_commitment_levels_asset_manager" where not asset_manager_id like '0C%'
```

version: 0.13.8

**Comment by eugmandel** [comment]
@gadekarabhijit Thank you for reporting this - the core team will take this on.

**Comment by jcampbell** [comment]
@gadekarabhijit -- is the reason to use the single-quote character to support the percent character? It looks to me like it's that character that is being escaped, and by pyathena directly. Are you using athena?

**Comment by jcampbell** [comment]
@gadekarabhijit --> actually, it looks like the pyathena docs cover this:

https://github.com/laughingman7743/PyAthena/ says "if % character is contained in your query, it must be escaped with %% like the following:"

```
SELECT col_string FROM one_row_complex
WHERE col_string = %(param)s OR col_string LIKE 'a%%'
```

**Comment by gadekarabhijit** [comment]
thanks, @jcampbell I tried this and it worked. one thing I didn't understand that I tried the query with pyathena but I didn't get any error there. here is the code that I tried. this is working.

```python
from pyathena import connect

cursor = connect(work_group="dnalab", region_name="us-east-1").cursor()
query = """select * from "managed_investment__esg__stg"."esg_commitment_levels_asset_manager" where not asset_manager_id like '0C%' """
cursor.execute(query)
```

**Comment by jcampbell** [comment]
Interesting; I'm not sure what causes the difference, but it seems potentially like it could be either a function of the way the driver is used (connect and getting a cursor vs an engine (?)) or perhaps the use of the driver to compile the statement. I only scanned the pyathena docs, but it also seems possible that there's a way to control escaping by the driver.

Sounds like we may be able to close this issue if your query is up and running now?

**Comment by eugmandel** [comment]
Closing this issue. @gadekarabhijit , please reopen and comment, if further action is needed.
