### ISSUE TITLE
Great Expecations breaking the Spark Context in an AWS EMR Notebook

### ISSUE THREAD

**Issue by j-f-r** [fivetran/great_expectations#2732]
**Describe the bug**
When using Great Expectations in AWS EMR with Spark, if a preexisting context is created before using Great Expectations, the `get_or_create_spark_application` function always restarts the context - regardless of whether or not the exact same `spark_config` is passed, which causes the preexisting context to crash.

To make matters worse, when using AWS EMR with a Notebook, once you stop a context, it cannot be restarted/recreated until you reset the notebook kernel, which disables any further usage of the context, even by Great Expectations.

**To Reproduce**
1. Create a spark context on a notebook: `spark = pyspark.sql.SparkSession.builder.appName('app').getOrCreate()`
2. Create a `DataContextConfig` with
```
config = DataContextConfig(
    ...
    datasources={
        "my_spark_datasource": {
             ...
             "spark_config": dict(spark.sparkContext.getConf().getAll())
```
3. Create the `BaseDataContext` using this config: `context = BaseDataContext(project_config=config)`
4. Try to load a batch using `context.get_batch({...})`
5. Spark will error out with `java.lang.IllegalStateException: Promise already completed` 

**Expected behavior**
Expected behavior is for the context to not be restarted if `spark.sparkContext.getConf().getAll()` is replicated into `spark_config` so that Great Expectations can coexist with an external Spark Context.

**Environment (please complete the following information):**
 - Operating System: AWS EMR (Linux)
 - Great Expectations Version: 0.13.19

**Comment by eugmandel** [comment]
@j-f-r Thank you for fixing this in your PR!

**Comment by rubenssoto** [comment]
Hello, how this option works?

Im trying:

`datasources={
                "my_spark_datasource": {
                    "data_asset_type": {
                        "class_name": "SparkDFDataset",
                        "module_name": "great_expectations.dataset",
                       
                    },
                    "class_name": "SparkDFDatasource",
                    "module_name": "great_expectations.datasource",
                     "force_reuse_spark_context": True
                    "batch_kwargs_generators": {},
                }
            }`

and I have the same problem

**Comment by sou-joshi** [comment]
Yes, having same issue. Adding the parameter mentioned, Does nothing! Please help @j-f-r

**Comment by j-f-r** [comment]
Hello,

You have to check of a version with this PR was already released, and if you are already using it

**Comment by j-f-r** [comment]
@sou-joshi you need to use version >= 0.13.20
