### ISSUE TITLE
Enable setting the schema for SparkDFDatsource with the CSV reader

### ISSUE THREAD

**Issue by j-f-r** [fivetran/great_expectations#2734]
**Is your feature request related to a problem? Please describe.**
There is currently no option for defining the schema of the data being loaded using the `csv` reader for `SparkDFDatasource`. The only option to circumvent this is to use `inferSchema: true` in `options`.

However, relying `inferSchema` has two problems:
- It requires passing through the data one extra time, causing it to be around 2 times slower than usual.
- `inferSchema` is not perfect and you might want to explicitly set the types to something else (an example would be an all empty column).

**Describe the solution you'd like**
Add a `schema` parameter to SparkDFDatasource that can be used to load the dataframe using a Spark Schema.

**Describe alternatives you've considered**
Again, the current alternative is `inferSchema`, which is not ideal.

**Comment by eugmandel** [comment]
@j-f-r This sounds like a great suggestion! Would you like to take this on and create a PR? Thank you!

**Comment by AFineDayFor** [comment]
Closing as it appears to be for v2;if it's a contribution you'd be keen on submitting, or it appears to still be an issue in v3 feel free to re-open this issue.
