### ISSUE TITLE
Parameter include_config=True for rules is not work with check for pandas

### ISSUE THREAD

**Issue by Zoynels** [fivetran/great_expectations#2739]
**Describe the bug**
Parameter include_config=True for rules is not work with check for pandas. I expect that after rule complete I will recieve information with config for this rule like is described in [docs](https://docs.greatexpectations.io/en/latest/reference/core_concepts/expectations/standard_arguments.html?highlight=include_config#include-config).

**To Reproduce**
```
import great_expectations as ge
import pandas as pd

df = pd.DataFrame({"my_var": ["A", "B", "C", "D", "F", "G", "H"]})
df_ge = ge.dataset.PandasDataset(df)
df_ge.expect_column_values_to_be_in_set(
    "my_var",
    ["B", "C", "D", "F", "G", "H"],
    result_format="COMPLETE",
    include_config=True,
)
```
and I have result:
```{
  "result": {
    "element_count": 7,
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_count": 1,
    "unexpected_percent": 14.285714285714285,
    "unexpected_percent_total": 14.285714285714285,
    "unexpected_percent_nonmissing": 14.285714285714285,
    "partial_unexpected_list": ["A"],
    "partial_unexpected_index_list": [0],
    "partial_unexpected_counts": [{"value": "A", "count": 1}],
    "unexpected_list": ["A"],
    "unexpected_index_list": [0]
  },
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "success": false,
  "meta": {}
}
```

**Expected behavior**
Expect as described in [docs](https://docs.greatexpectations.io/en/latest/reference/core_concepts/expectations/standard_arguments.html?highlight=include_config#include-config) than in result will have information about config like 
```
...
    'expectation_type': 'expect_column_values_to_be_in_set',
    'expectation_kwargs': {
        'column': 'my_var',
        'result_format': 'COMPLETE',
        'value_set': ['B', 'C', 'D', 'F', 'G', 'H']
    },
...
```

**Environment (please complete the following information):**
 - Operating System: Windows 10
 - Great Expectations Version: 0.13.19

**Comment by eugmandel** [comment]
@Zoynels Thank you - will reproduce and decide on the next step.

**Comment by vaidehid1305** [comment]
Facing same issue with CSV and Athena datasources. Any updates on this investigation?

**Comment by talagluck** [comment]
Hi - apologies for delays. I believe this should work in V3, and we are unable to prioritize this for V2. That said, we always welcome contributions! Feel free to reach out if you are interested and need support.

**Comment by AFineDayFor** [comment]
Howdy @Zoynels, we're going to go ahead and close this; however, feel free to submit a contribution at any time, we'll always be glad to review it!
