### ISSUE TITLE
Dumping results to database

### ISSUE THREAD

**Issue by bouke-nederstigt** [fivetran/great_expectations#274]
It would be interesting to be able to dump expectation results to a database. e.g. some kind of error fact table, or a table specific to a set of expectations. That way it becomes much easier to track the quality of your data over time.

Is this something you guys have considered? Happy to help.

**Comment by jpcampb2** [comment]
I can see that working well as an integration that reads the GE json-based output format, and translates it into a result table. Do you have a schema in mind already?

**Comment by bouke-nederstigt** [comment]
The integration approach was on my mind as well. Not completely sure about the schema yet. I think depending on the use case it might be necessary to add some context as well. e.g. stuff like where in the pipeline the tests where executed, or during what batch run. 

I think there are two major options when it comes to a relation schema. 
- One is to use a single expectation as the grain of the expectation results table. This would definitely include columns for the expectation_type and success properties, possibly also the kwargs.column, or even kwargs.min_value and max_value. Besides this it would be nice to store results as well. If you can track the unexpected_count over time it becomes possible to see improvements in data quality. One might even go as far as to add all of the result array elements.
- The other option is to take the unexpected_list as grain for the exception table. This means you get at least one row in the results table for every failing expectation per row in the dataset. This might result in lots of rows in the results table, but I think this is a not uncommon approach in data warehouses. This way you get the most flexibility in auditing your data quality, if you want in relation to actual rows in a fact table.

There are however a couple of downsides with both of these approaches. 
- You either lose data by not incorporating all possible json properties in the schema, or end up with lots of null values when you do add columns for all possible properties.
- Data might not be available at all depending on the specified result_format argument.
- It's quite hard to add contextual information because this is probably highly specific on the environment in which great_expectations is being used.

A different approach that might be more suitable given the fact that results are outputted in json is to us a NoSql database. It could e.g. be a great solution to just ingest the json result straight into Elasticsearch. From here it's easy to do analytics / create dashboards using Kibana. This is a much easier solution to implement, but it would require users to have access to such a database, and it's a bit harder to link actual data to data quality data. It also becomes much easier to add contextual information, because users can just add an extra json array with all their specific contextual information..

Let me know what you think.

**Comment by jpcampb2** [comment]
I think the idea of dropping the output of the expectation into elasticsearch as a document, and then providing a kibana dashboard setup that is aimed at allowing the monitoring of data quality probably makes most sense right away. It also allows the great_expectations library to remain focused on the construction and validation of expectations, with good separation from the execution on one hand and  monitoring/display of the pipeline on the other.

**Comment by jpcampb2** [comment]
@bouke-nederstigt Thank you for raising the issue and using GE--I'm going to close this issue as resolved for now, but interested to hear more about your experience.
