### ISSUE TITLE
ArgumentError thrown when creating expectation suites for some table names

### ISSUE THREAD

**Issue by balexander** [fivetran/great_expectations#2741]
**Describe the bug**
A table with the name "content" results in an `ArgumentError`

**To Reproduce**
1. Create a Redshift data source
2. Create a new expectation suite using the v3 api 
3. Select Interactively, with a sample batch of data when prompted
4. Select the Redshift data source 
5. Select Enter a table name and schema. Enter `some_schema` for the schema name and `content` for the table name.
6. A notebook opens with code to print column names of the table. Executing the first cell results in an error due to [this issue](https://github.com/great-expectations/great_expectations/issues/2740). Resolve it by changing the batch request to 
```
batch_request = {'datasource_name': 'rs', 'data_connector_name': 'whole_table', 'data_asset_name':'content__whole_table', 'limit': 1000}
```
Execute the cell.

```
ArgumentError: Textual SQL expression 'content' should be explicitly declared as text('content')
```

**Expected behavior**
No 

**Environment (please complete the following information):**
 - MacOS
 - Great Expectations Version: 0.13.19

**Additional context**
I don't think Redshift being the type of data store makes any difference, but I included it for completeness.

**Comment by eugmandel** [comment]
@balexander Is there anything special about "content"? I don't think it's a SQL reserved keyword. Could you please try to identify the pattern here? Thank you!

**Comment by balexander** [comment]
@eugmandel Hmm I'll check. I discovered this during the process of debugging another [issue I added](https://github.com/great-expectations/great_expectations/issues/2740) and found `content` was the only table in the schema to cause an error. Besides the name, I can't think of anything about that table that distinguishes it from other tables. I'll do a little debugging and see whats up.

**Comment by balexander** [comment]
No there is nothing special about the word "content". It is with any name I choose. If I update `def column_reflection_fallback(` in expectations/metrics/util.py like this:
```
       # Add sa.text(selectable)
        query: Select = sa.select([sa.text("*")]).select_from(sa.text(selectable)).limit(1)
       # instead of 
       # query: Select = sa.select([sa.text("*")]).select_from(selectable).limit(1)
```
then I get a different error message saying that the relation I'm looking for doesn't exist. But that error message is related to [this other issue I reported](https://github.com/great-expectations/great_expectations/issues/2740), or at least I think it is.

**Comment by balexander** [comment]
This appears to have been fixed with the most recent release.
