### ISSUE TITLE
Great Expectations should totally do Spark DataFrames.

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#276]
discuss.

**Comment by ccnobbli** [comment]
So what do you think will be the most challenging aspect of this data context?

**Comment by Hellsen83** [comment]
Hello World!
New to this project, which i recently discovered and I got to say I totally love it. That said, I am not yet aware of possible integration challenges, that said, I totally agree that (Py)Spark is the way to go.  
Looking forward to contribute!

**Comment by Boottexy** [comment]
Hi @abegong, hope you are doing well!
To clarify, shouldn't this issue be closed? Or is this not yet fully implemented?

**Comment by abegong** [comment]
You're totally right. This should be closed.
