### ISSUE TITLE
Splitting data asset using _split_on_converted_datetime() method fails for MSSQL and any other SQL dialect not implementing strftime()

### ISSUE THREAD

**Issue by marzlevane** [fivetran/great_expectations#2768]
**Describe the bug**
Splitting data asset using **_split_on_converted_datetime()** method fails for MSSQL and any other SQL dialect not implementing **strftime()**.

**To Reproduce**
Set up datasource in great_expectations.yaml similar to:

    
    datasources:
      DATASOURCE_NAME:
        connection_string: <VALID_CONNECTION_STRING_TO_MSSQL_DATASOURCE>
        module_name: great_expectations.datasource
        introspection:
          my_tables:
            included_tables:
              - dbo.MY_TABLE_1
              - dbo.MY_TABLE_2
              - dbo.MY_TABLE_3
            splitter_method: _split_on_converted_datetime
            splitter_kwargs:
              column_name: MY_DATE_COLUMN
        class_name: SimpleSqlalchemyDatasource

Error message:

    DatasourceInitializationError: Cannot initialize datasource my_datasource, error: (pyodbc.ProgrammingError) ('42000', "[42000] 
    [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]'strftime' is not a recognized built-in function name. (195) 
    (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")

**Expected behavior**
Working config, data assets MY_TABLE_[N] split by converted datetime value

**Environment (please complete the following information):**
 - Operating System: Windows 10
 - Great Expectations Version: 0.13.19

**Additional context**
_split_on_converted_datetime() is implemented by passing the call to strftime() on to the RDBMS, as sqlalchemy is not aware of a strftime()-function. This works for SQLite, but not most other SQL dialects.

https://github.com/great-expectations/great_expectations/blob/6d9a0ad886207086019bc43b2bc2629ce38a4f38/great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py#L287

**Comment by eugmandel** [comment]
@marzlevane Thank you for reporting this - adding to the core team's backlog.

**Comment by kenwade4** [comment]
@marzlevane Is this still an issue when using v3 of Great Expectations?

**Comment by talagluck** [comment]
Hi @marzlevane - we have added a few new splitter methods around datetimes, and these should work for MSSQL. We have more information around these in our docs. I'm going to close this for now, but please let us know if you have any follow-up questions.
