### ISSUE TITLE
Unable to exclude multiple regex patterns from single column.

### ISSUE THREAD

**Issue by njsmith8** [fivetran/great_expectations#277]
I am working with a lot of text data, and I want to use expect_column_values_to_not_match_regex to check for the presence of multiple regex patterns in the same column.

The reasons for looking for the different regex patterns are unrelated, so I created them as separate expectations, but only the last pattern is kept in the final expectation list.

expect_column_values_to_not_match_regex_list does not currently appear to exist as expectation.

**Comment by jpcampb2** [comment]
Thank you for flagging this issue. I think as an intermediate fix, we should just add `expect_column_values_to_not_match_regex_list`, but the deeper issue will be a revision to the way that expectation matching happens when new expectations are made, and a need for a way to signal whether the new expectation should replace or complement the old one.

**Comment by ccnobbli** [comment]
Thanks for bringing up this issue @njsmith8! My first thought is to have a `replace_similar_expectations` argument in the expectation, defaulted to `True`. 

I haven't sold myself with that, but I think it's better than having some sort of global flag - you probably won't need this behavior for all but a handful of your expectations.

Another way to differentiate expectation matching could be to look at the `values` argument - if they are different, keep both. I feel like this would be annoying to deal with in an exploratory setting though. I'm imagining amending one expectation a few times and realizing later that you have 8 of them...

**Comment by jpcampb2** [comment]
I'm definitely open for more discussion on fixing the deeper matching issue, but that think we should open a different issue for that discussion!
