### ISSUE TITLE
How do I customize an sql datasource/data connector?

### ISSUE THREAD

**Issue by marzlevane** [fivetran/great_expectations#2770]
I would like to implement my own splitting method for the inferred SQL data connector. I want to reuse the inferred asset SQL data connector but change the splitting method. This is what I have tried:

- Subclassing **InferredAssetSqlDataConnector** and defining/overriding any **_split_on...()**-methods I want to use.

- Subclassing **SimpleSqlalchemyDatasource** and overriding **_init_data_connectors()** to use my custom version of **InferredAssetSqlDataConnector**

However, I cannot configure this datasource due to this piece of validation code:
https://github.com/great-expectations/great_expectations/blob/6d9a0ad886207086019bc43b2bc2629ce38a4f38/great_expectations/data_context/types/base.py#L664-L689

I could just rename the keywords and translate in the _init-method, but it makes no sense why I would have to.

How do I properly customize the datasources and data connectors, and in particular the splitting methods?

Is there a reason why the configuration keywords are reserved to these inbuilt datasource classes?

**Comment by eugmandel** [comment]
@marzlevane Would it work if you use "Datasource" class in your config (instead of SimpleSqlAlchemyDatasource) and subclass InferredAssetSqlDataConnector?

**Comment by marzlevane** [comment]
Hi, thank you for the suggestion.

I run into other problems of the same type, as there are validation checks on keywords on the data connector as well. I get this error message when trying to configure my subclassed InferredAssetSqlDataConnector:

    InvalidConfigError: Your current configuration uses one or more keys in a data connector, that are required only by an
    SQL type of the data connector (your data conntector is "CustomMssqlInferredAssetSqlDataConnector").  Please update your 
    configuration to
    continue.

In this case, this is the validation code that trips me up:

https://github.com/great-expectations/great_expectations/blob/57967e1b98ea63278f2b888753141d6a284c5e63/great_expectations/data_context/types/base.py#L336-L458

Is there a reason why these keywords are reserved for certain data connectors? Are you supposed to be able to extend the data connectors, and in that case, how?

**Comment by kenwade4** [comment]
A lot of this code has changed in the last 6 months, so this may be simpler to implement/resolve. Please let us know if this is not the case and open a new issue.
