### ISSUE TITLE
SQLAlchemy `expect_column_values_to_not_be_null` can't handle columns with 100% missing values

### ISSUE THREAD

**Issue by ccnobbli** [fivetran/great_expectations#278]
While migrating tests, found a bug that seems to happen when all column values are missing. Returns `success`=`True` even though it should be `False`.

The expectation correctly fails when there is at least one, non-missing value. I'm not really familiar with SQL Alchemy to understand why this might be happening.

**Comment by abegong** [comment]
This only affects SQLAlchemy? Not pandas?

**Comment by ccnobbli** [comment]
Yes, the same tests that fail on SQA are hunkey-dory for pandas

**Comment by jpcampb2** [comment]
Are you testing cases where the entire table is empty, or where the table has rows, but you're testing against a column that has all nulls? If the former, it sort of makes sense to me...

**Comment by ccnobbli** [comment]
Unfortunately, it's the latter. The dataset is defined in the tests like:

```
"data" : {
      "x" : [2, null, 2, 5],
      "y" : [2, null, 2, 5],
      "z" : [2, 5, 7, 9],
      "a" : [null, null, null, null],
      "b" : [null, null, 5, 5]
    }
```

In this case, I am expecting the column `a` to have no nulls when it they are in fact all nulls. The expectation returns `True`, that it doesn't have any... which is clearly not the case.

Interestingly, the Pandas context correctly identifies it as a failing expectation, but not SQA.

**Comment by jpcampb2** [comment]
It looks like this is perhaps a legacy of having converted the pandas expectations away from column_map_expectations, but leaving the sqlalchemy expectations as column_map_expectations.

The `_calc_map_expectation_success` function from base returns true any time that the nonnull_count is zero...which is clearly wrong for expect_column_values_to_not_be_null.

Seems like there should be a conditional that returns true only if success_count > 0.

**Comment by jpcampb2** [comment]
Also...was this condition not tested before, but was in one of the tests you were converting, or were you also expanding the test cases for existing cases (great catch).

**Comment by ccnobbli** [comment]
Fantastic, I think you found the smoking gun. 

This condition was being tested before, but only in Pandas. And to be honest, I think I added this 100% missing column condition only after wrangling with a previous issue concerning the `to_[not]_be_null` expectations and the mismatched `nonmissing percent` output.

**Comment by jpcampb2** [comment]
@ccnobbli can you build a patch to address this issue?

**Comment by ccnobbli** [comment]
So, iirc we ended up nixing the `expect_column_values_to_[not]_be_null` from the `map` expectations framework - mostly because of this missing value issue in `_calc_map_expectations_success`. 

I've been trying to think of workarounds to prevent issues with `unexpected_percent_nonmissing` and weird success calculations with `mostly` - it seems simpler to deviate from the map framework tbh.  I'll go ahead and do this, but let me know if that seems silly.

**Comment by jpcampb2** [comment]
That sounds good to me.

**Comment by abegong** [comment]
From today's discussion:

*Stop-gap solution:*
* In the `SQLAlchemyDataset.column_map_expectation` decorator, add conditional logic to adjust the denominator for `expect_column_values_to_be_null` and `expect_column_values_to_not_be_null`
* Change `unexpected_count` and `unexpected_query_results` to select on unexpected condition AND not missing.

*Better solution:*
* Add an `ignore_values` kwarg to all expectations. It will need good documentation, to make sure that intent and usage are clear.
* Implement sensible defaults for `ignore_values` in pandas and sqlalchemy.
* Make it possible for expectations to inherit `ignore_values` from `meta`

*Open questions*
How does Spark handle missing values?

**Comment by ccnobbli** [comment]
See #280

**Comment by ccnobbli** [comment]
Fixed in that merge! Boom!
