### ISSUE TITLE
MS SQL Server Integration Throws "Invalid object name" During Expectation Creation

### ISSUE THREAD

**Issue by FredHermann** [fivetran/great_expectations#2815]
I setup Great Expectations following the documentation (https://docs.greatexpectations.io/en/stable/guides/how_to_guides/configuring_datasources/how_to_configure_a_mssql_datasource.html). I have a data context setup that connects to SQL Server. The code: `context.test_yaml_config(
    yaml_config=config
)` works as expected. I am running this script on windows 10 with SQL Server version:

> Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64) 
> 	Feb 15 2020 01:47:30 
> 	Copyright (c) Microsoft Corporation
> 	Developer Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

When I attempt to run the first cell in the generated Notebook, `validator.head(n_rows=5, fetch_all=False)` throws a SQLalchemy programming error:

> ---------------------------------------------------------------------------
> ProgrammingError                          Traceback (most recent call last)
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
>    1275                 if not evt_handled:
> -> 1276                     self.dialect.do_execute(
>    1277                         cursor, statement, parameters, context
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py in do_execute(self, cursor, statement, parameters, context)
>     608     def do_execute(self, cursor, statement, parameters, context=None):
> --> 609         cursor.execute(statement, parameters)
>     610 
> 
> ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#ge_tmp_52625c8d'. (208) (SQLExecDirectW)")
> 
> The above exception was the direct cause of the following exception:
> 
> ProgrammingError                          Traceback (most recent call last)
> <ipython-input-2-a9b555dfaddf> in <module>
>      22 column_names = [f'"{column_name}"' for column_name in validator.columns()]
>      23 print(f"Columns: {', '.join(column_names)}.")
> ---> 24 validator.head(n_rows=5, fetch_all=False)
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\validator\validator.py in head(self, n_rows, domain_kwargs, fetch_all)
>    1335             }
>    1336 
> -> 1337         data: Any = self.get_metric(
>    1338             metric=MetricConfiguration(
>    1339                 metric_name="table.head",
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\validator\validator.py in get_metric(self, metric)
>     325     def get_metric(self, metric: MetricConfiguration) -> Any:
>     326         """return the value of the requested metric."""
> --> 327         return self.get_metrics({"_": metric})["_"]
>     328 
>     329     def build_metric_dependency_graph(
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\validator\validator.py in get_metrics(self, metrics)
>     317                 runtime_configuration=None,
>     318             )
> --> 319         self.resolve_validation_graph(graph, resolved_metrics)
>     320         return {
>     321             metric_name: resolved_metrics[metric_configuration.id]
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\validator\validator.py in resolve_validation_graph(self, graph, metrics, runtime_configuration)
>     501                 pbar.update(0)
>     502             metrics.update(
> --> 503                 self._resolve_metrics(
>     504                     execution_engine=self._execution_engine,
>     505                     metrics_to_resolve=ready_metrics,
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\validator\validator.py in _resolve_metrics(self, execution_engine, metrics_to_resolve, metrics, runtime_configuration)
>     545         """A means of accessing the Execution Engine's resolve_metrics method, where missing metric configurations are
>     546         resolved"""
> --> 547         return execution_engine.resolve_metrics(
>     548             metrics_to_resolve, metrics, runtime_configuration
>     549         )
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\execution_engine\execution_engine.py in resolve_metrics(self, metrics_to_resolve, metrics, runtime_configuration)
>     255                 )
>     256             elif metric_fn_type == MetricFunctionTypes.VALUE:
> --> 257                 resolved_metrics[metric_to_resolve.id] = metric_fn(
>     258                     **metric_provider_kwargs
>     259                 )
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\expectations\metrics\metric_provider.py in inner_func(*args, **kwargs)
>      34         @wraps(metric_fn)
>      35         def inner_func(*args, **kwargs):
> ---> 36             return metric_fn(*args, **kwargs)
>      37 
>      38         inner_func.metric_engine = engine
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\expectations\metrics\table_metrics\table_head.py in _sqlalchemy(cls, execution_engine, metric_domain_kwargs, metric_value_kwargs, metrics, runtime_configuration)
>      90                 compile_kwargs={"literal_binds": True},
>      91             )
> ---> 92             df = pd.read_sql(sql, con=execution_engine.engine)
>      93 
>      94         return df
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\sql.py in read_sql(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize)
>     508         )
>     509     else:
> --> 510         return pandas_sql.read_query(
>     511             sql,
>     512             index_col=index_col,
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\sql.py in read_query(self, sql, index_col, coerce_float, parse_dates, params, chunksize)
>    1292         args = _convert_params(sql, params)
>    1293 
> -> 1294         result = self.execute(*args)
>    1295         columns = result.keys()
>    1296 
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\sql.py in execute(self, *args, **kwargs)
>    1160     def execute(self, *args, **kwargs):
>    1161         """Simple passthrough to SQLAlchemy connectable"""
> -> 1162         return self.connectable.execution_options().execute(*args, **kwargs)
>    1163 
>    1164     def read_table(
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in execute(self, object_, *multiparams, **params)
>    1009             )
>    1010         else:
> -> 1011             return meth(self, multiparams, params)
>    1012 
>    1013     def _execute_function(self, func, multiparams, params):
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\compiler.py in _execute_on_connection(self, connection, multiparams, params)
>     335     def _execute_on_connection(self, connection, multiparams, params):
>     336         if self.can_execute:
> --> 337             return connection._execute_compiled(self, multiparams, params)
>     338         else:
>     339             raise exc.ObjectNotExecutableError(self.statement)
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in _execute_compiled(self, compiled, multiparams, params)
>    1145         dialect = self.dialect
>    1146         parameters = _distill_params(multiparams, params)
> -> 1147         ret = self._execute_context(
>    1148             dialect,
>    1149             dialect.execution_ctx_cls._init_compiled,
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
>    1314 
>    1315         except BaseException as e:
> -> 1316             self._handle_dbapi_exception(
>    1317                 e, statement, parameters, cursor, context
>    1318             )
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
>    1508                 util.raise_(newraise, with_traceback=exc_info[2], from_=e)
>    1509             elif should_wrap:
> -> 1510                 util.raise_(
>    1511                     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
>    1512                 )
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py in raise_(***failed resolving arguments***)
>     180 
>     181         try:
> --> 182             raise exception
>     183         finally:
>     184             # credit to
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
>    1274                             break
>    1275                 if not evt_handled:
> -> 1276                     self.dialect.do_execute(
>    1277                         cursor, statement, parameters, context
>    1278                     )
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py in do_execute(self, cursor, statement, parameters, context)
>     607 
>     608     def do_execute(self, cursor, statement, parameters, context=None):
> --> 609         cursor.execute(statement, parameters)
>     610 
>     611     def do_execute_no_params(self, cursor, statement, context=None):
> 
> ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#ge_tmp_52625c8d'. (208) (SQLExecDirectW)")
> [SQL: SELECT TOP 5 * 
> FROM [#ge_tmp_52625c8d]]
> (Background on this error at: http://sqlalche.me/e/13/f405)
> 

In the next notebook cell, `suite = profiler.build_suite()` also throws the same error:

> ---------------------------------------------------------------------------
> ProgrammingError                          Traceback (most recent call last)
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
>    1275                 if not evt_handled:
> -> 1276                     self.dialect.do_execute(
>    1277                         cursor, statement, parameters, context
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py in do_execute(self, cursor, statement, parameters, context)
>     608     def do_execute(self, cursor, statement, parameters, context=None):
> --> 609         cursor.execute(statement, parameters)
>     610 
> 
> ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#ge_tmp_fd698cfc'. (208) (SQLExecDirectW)")
> 
> The above exception was the direct cause of the following exception:
> 
> ProgrammingError                          Traceback (most recent call last)
> <ipython-input-3-947aac85f826> in <module>
>       9     value_set_threshold="MANY",
>      10 )
> ---> 11 suite = profiler.build_suite()
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\profile\user_configurable_profiler.py in build_suite(self)
>     209             return self._build_expectation_suite_from_semantic_types_dict()
>     210 
> --> 211         return self._profile_and_build_expectation_suite()
>     212 
>     213     def _build_expectation_suite_from_semantic_types_dict(self):
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\profile\user_configurable_profiler.py in _profile_and_build_expectation_suite(self)
>     273                 column_list=self.primary_or_compound_key,
>     274             )
> --> 275         self._build_expectations_table(profile_dataset=self.profile_dataset)
>     276         with tqdm(desc="Profiling", total=len(self.column_info), delay=5) as pbar:
>     277             for column_name, column_info in self.column_info.items():
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\profile\user_configurable_profiler.py in _build_expectations_table(self, profile_dataset, **kwargs)
>    1130 
>    1131         if "expect_table_row_count_to_be_between" not in self.excluded_expectations:
> -> 1132             row_count = profile_dataset.expect_table_row_count_to_be_between(
>    1133                 min_value=0, max_value=None
>    1134             ).result["observed_value"]
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\validator\validator.py in inst_expectation(*args, **kwargs)
>     268 
>     269                 else:
> --> 270                     raise err
>     271             return validation_result
>     272 
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\validator\validator.py in inst_expectation(*args, **kwargs)
>     226                     )
>     227                 else:
> --> 228                     validation_result = expectation.validate(
>     229                         validator=self,
>     230                         evaluation_parameters=self._expectation_suite.evaluation_parameters,
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\expectations\expectation.py in validate(self, validator, configuration, evaluation_parameters, interactive_evaluation, data_context, runtime_configuration)
>     639             evaluation_parameters, interactive_evaluation, data_context
>     640         )
> --> 641         evr = validator.graph_validate(
>     642             configurations=[configuration],
>     643             runtime_configuration=runtime_configuration,
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\validator\validator.py in graph_validate(self, configurations, metrics, runtime_configuration)
>     461             metrics = dict()
>     462 
> --> 463         metrics = self.resolve_validation_graph(graph, metrics, runtime_configuration)
>     464         for configuration in processed_configurations:
>     465             try:
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\validator\validator.py in resolve_validation_graph(self, graph, metrics, runtime_configuration)
>     501                 pbar.update(0)
>     502             metrics.update(
> --> 503                 self._resolve_metrics(
>     504                     execution_engine=self._execution_engine,
>     505                     metrics_to_resolve=ready_metrics,
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\validator\validator.py in _resolve_metrics(self, execution_engine, metrics_to_resolve, metrics, runtime_configuration)
>     545         """A means of accessing the Execution Engine's resolve_metrics method, where missing metric configurations are
>     546         resolved"""
> --> 547         return execution_engine.resolve_metrics(
>     548             metrics_to_resolve, metrics, runtime_configuration
>     549         )
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\execution_engine\execution_engine.py in resolve_metrics(self, metrics_to_resolve, metrics, runtime_configuration)
>     266                 )
>     267         if len(metric_fn_bundle) > 0:
> --> 268             resolved_metrics.update(self.resolve_metric_bundle(metric_fn_bundle))
>     269 
>     270         return resolved_metrics
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\great_expectations\execution_engine\sqlalchemy_execution_engine.py in resolve_metric_bundle(self, metric_fn_bundle)
>     626             assert len(query["select"]) == len(query["ids"])
>     627             try:
> --> 628                 res = self.engine.execute(
>     629                     sa.select(query["select"]).select_from(selectable)
>     630                 ).fetchall()
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in execute(self, object_, *multiparams, **params)
>    1009             )
>    1010         else:
> -> 1011             return meth(self, multiparams, params)
>    1012 
>    1013     def _execute_function(self, func, multiparams, params):
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py in _execute_on_connection(self, connection, multiparams, params)
>     296     def _execute_on_connection(self, connection, multiparams, params):
>     297         if self.supports_execution:
> --> 298             return connection._execute_clauseelement(self, multiparams, params)
>     299         else:
>     300             raise exc.ObjectNotExecutableError(self)
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in _execute_clauseelement(self, elem, multiparams, params)
>    1122             )
>    1123 
> -> 1124         ret = self._execute_context(
>    1125             dialect,
>    1126             dialect.execution_ctx_cls._init_compiled,
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
>    1314 
>    1315         except BaseException as e:
> -> 1316             self._handle_dbapi_exception(
>    1317                 e, statement, parameters, cursor, context
>    1318             )
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
>    1508                 util.raise_(newraise, with_traceback=exc_info[2], from_=e)
>    1509             elif should_wrap:
> -> 1510                 util.raise_(
>    1511                     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
>    1512                 )
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py in raise_(***failed resolving arguments***)
>     180 
>     181         try:
> --> 182             raise exception
>     183         finally:
>     184             # credit to
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
>    1274                             break
>    1275                 if not evt_handled:
> -> 1276                     self.dialect.do_execute(
>    1277                         cursor, statement, parameters, context
>    1278                     )
> 
> ~\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py in do_execute(self, cursor, statement, parameters, context)
>     607 
>     608     def do_execute(self, cursor, statement, parameters, context=None):
> --> 609         cursor.execute(statement, parameters)
>     610 
>     611     def do_execute_no_params(self, cursor, statement, context=None):
> 
> ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#ge_tmp_fd698cfc'. (208) (SQLExecDirectW)")
> [SQL: SELECT count(*) AS [table.row_count] 
> FROM [#ge_tmp_fd698cfc]]
> (Background on this error at: http://sqlalche.me/e/13/f405)

I am able to successfully run the last cell and generate the expectation, but it only contains the `expect_table_columns_to_match_ordered_list` expectation.

Please let me know if there is any additional information I can provide.

**Comment by eugmandel** [comment]
@FredHermann Thank you for reporting this! I did not see in the report which version of GE this is happening on. Could you please specify it?

**Comment by FredHermann** [comment]
@eugmandel Thanks for looking into this! I am using GE version 0.13.19

**Comment by talagluck** [comment]
Hi @FredHermann - thanks for your question, and apologies for delays. I know we've done some work around SqlAlchemyExecutionEngine recently. Would you please confirm whether this is still not working as expected?

Thanks!

**Comment by talagluck** [comment]
Hi @FredHermann, I'm going to close this for now, but if this does turn out to still be an issue, please feel free to re-open.
