### ISSUE TITLE
[Help/Feature Request] Recommended approach for deploying expecations defined by historic trends

### ISSUE THREAD

**Issue by JeroenSchmidt** [fivetran/great_expectations#2823]
Are there materials, projects plans or ongoing PRs that I could look which have a clean implementation of dynamic expectations defined by historic trends? 

An example expectation; **Row count for partition_date=today() to be within 20% deviation of the historic row count for the last 5 days** 

At the moment we are programmatically calculating the historic values for our expectations every time an expectation validation is being run but this means that we are unable to use the expectation configs. This is preventing us from easily scaling our "dynamic" expectations because we need to write a lot of boiler plate for every table we would like to apply these checks on.

**Comment by eugmandel** [comment]
@JeroenSchmidt This is something that will be supported in the future. 
@jcampbell, you might be interested to take a look.

**Comment by kenwade4** [comment]
This is on the road map but you can accomplish some of this with [evaluation parameters](https://docs.greatexpectations.io/docs/reference/evaluation_parameters/)

**Comment by JeroenSchmidt** [comment]
Thanks for the resource @kenwade4  :)
