### ISSUE TITLE
Question : Spark DF Validation in GE

### ISSUE THREAD

**Issue by ashishmgofficial** [fivetran/great_expectations#2827]
Hi , I'm pretty new to GE. Need to know how can we validate a Spark Dataframe with another Spark DF. So essentially the expectation would be a Spark DF itself.

**Comment by Shinnnyshinshin** [comment]
Hi @ashishmgofficial thanks for your interest in GE. Your question is really interesting, and I don't think it's been done before.  Have you had a chance to talk to anyone on [GE Slack](https://greatexpectationstalk.slack.com/)?

**Comment by sou-joshi** [comment]
More details please, A simple "except" function would give a difference between dataframes.

**Comment by bhcastleton** [comment]
@ashishmgofficial - It looks like you're wanting to validate that two dataframes are identical. Is that what you're trying to do?

**Comment by ashishmgofficial** [comment]
There can be many scenarios like : 
1) two df are identical for a time window 
2) two df are equal based on a filter
Or
3) A column in a df is aggregate of two other columns in another df
Etc

Right now we were thinking of going with custom expectation approach

**Comment by talagluck** [comment]
Hi @ashishmgofficial! Thanks for your question. We have [this doc which details a workflow which may be useful for you](https://discuss.greatexpectations.io/t/how-to-compare-two-tables-with-the-userconfigurableprofiler/618/2). This doc is specifically for V2, and we are in the process of updating it for V3 - it should be released pretty soon. 

I'm going to close this issue for now, but feel free to post in Slack or Discuss to discuss this further. Thanks!
