### ISSUE TITLE
Checkpoint not executable --> TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by FollowJack** [fivetran/great_expectations#2828]
I have an expectation defined:
    {
      "expectation_type": "expect_column_pair_values_A_to_be_greater_than_B",
      "kwargs": {
        "column_A": "COL_Bigger",
        "column_B": "COL_Smaller",
        "or_equal": true
      },
      "meta": {}
    },

When executing this expectation I get the error: TypeError: 'NoneType' object is not callable 

**To Reproduce**
1. Creat suite edit
2. Add expectation (see above) in expectations/my_suite/suite.json file 
3. Run ```context.run_checkpoint(checkpoint_name=my_checkpoint_name)``` --> throws error

This is the error stack trace: 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-a3410a18831e> in <module>
----> 1 context.run_checkpoint(checkpoint_name=my_checkpoint_name)
      2 context.open_data_docs()

~/repository/trufa/oracle-importer/venv/lib/python3.9/site-packages/great_expectations/data_context/data_context.py in run_checkpoint(self, checkpoint_name, template_name, run_name_template, expectation_suite_name, batch_request, action_list, evaluation_parameters, runtime_configuration, validations, profilers, run_id, run_name, run_time, result_format, **kwargs)
   3051         )
   3052 
-> 3053         return checkpoint.run(
   3054             template_name=template_name,
   3055             run_name_template=run_name_template,

~/repository/trufa/oracle-importer/venv/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py in run(self, template_name, run_name_template, expectation_suite_name, batch_request, action_list, evaluation_parameters, runtime_configuration, validations, profilers, run_id, run_name, run_time, result_format, **kwargs)
    278                 )
    279                 val_op_run_result: ValidationOperatorResult = (
--> 280                     action_list_validation_operator.run(
    281                         assets_to_validate=[validator],
    282                         run_id=run_id,

~/repository/trufa/oracle-importer/venv/lib/python3.9/site-packages/great_expectations/validation_operators/validation_operators.py in run(self, assets_to_validate, run_id, evaluation_parameters, run_name, run_time, result_format)
    324                 run_id=run_id,
    325             )
--> 326             batch_validation_result = batch.validate(
    327                 run_id=run_id,
    328                 result_format=result_format if result_format else self.result_format,

~/repository/trufa/oracle-importer/venv/lib/python3.9/site-packages/great_expectations/validator/validator.py in validate(self, expectation_suite, run_id, data_context, evaluation_parameters, catch_exceptions, result_format, only_return_failures, run_name, run_time)
   1162                 expectations_to_evaluate.extend(columns[col])
   1163 
-> 1164             results = self.graph_validate(
   1165                 expectations_to_evaluate,
   1166                 runtime_configuration={

~/repository/trufa/oracle-importer/venv/lib/python3.9/site-packages/great_expectations/validator/validator.py in graph_validate(self, configurations, metrics, runtime_configuration)
    428 
    429             expectation_impl = get_expectation_impl(configuration.expectation_type)
--> 430             validation_dependencies = expectation_impl().get_validation_dependencies(
    431                 configuration, self._execution_engine, runtime_configuration
    432             )["metrics"]

TypeError: 'NoneType' object is not callable

```

**Expected behavior**
Expect values to be compared of two columns

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.19

**Additional context**
Using API v3

**Comment by eugmandel** [comment]
@FollowJack Could you please post your configuration, so that we can see the context? Thank you!

**Comment by aoguedao** [comment]
Hi! I have a similar issue using `expect_compound_columns_to_be_unique`. But I'm instantiating data contexts without a .yml file (configurator), reading local csv and development is in runtime (I'm trying to create a sort of expectations factory for different customers)

```
expect_keys_to_be_unique_config = ExpectationConfiguration(
    expectation_type="expect_compound_columns_to_be_unique",
    kwargs={"column_list": key_columns},
)
```

**Comment by vikramaditya91** [comment]
The [documentation](https://docs.greatexpectations.io/en/latest/reference/core_concepts/expectations/implemented_expectations.html#implemented-expectations) points out to the missing multi-column expectations. 

We are stuck with this too and are considering making a custom implementation around this until it is resolved

**Comment by vikramaditya91** [comment]
@eugmandel @spencerhardwick 
Any ETA on when the multi-column expectations will be available in v3?

**Comment by bhcastleton** [comment]
@vikramaditya91 - Multi-Column expectations are now available in v3. You probably already noticed. But just letting you know in case you missed it.

**Comment by vikramaditya91** [comment]
Hey @bhcastleton. We had noticed indeed. But thanks for the heads up

**Comment by JeffH72** [comment]
Any eta on when this will be resolved?  I'm using version 0.13.35 on a mac and I'm still getting the issue using expect_column_pair_values_A_to_be_greater_than_B

**Comment by bpovea** [comment]
Hi, I solved this problem... it's just a naming issue. the right name must be: `expect_column_pair_values_a_to_be_greater_than_b`. All in lower case.

This is the whole list of expectation suites dictionary:
`_registered_expectations.keys()
dict_keys(['expect_column_values_to_be_of_type', 'expect_column_distinct_values_to_be_in_set', 'expect_column_distinct_values_to_contain_set', 'expect_column_distinct_values_to_equal_set', 'expect_column_kl_divergence_to_be_less_than', 'expect_column_max_to_be_between', 'expect_column_mean_to_be_between', 'expect_column_median_to_be_between', 'expect_column_min_to_be_between', 'expect_column_most_common_value_to_be_in_set', 'expect_column_pair_values_a_to_be_greater_than_b', 'expect_column_pair_values_to_be_equal', 'expect_column_pair_values_to_be_in_set', 'expect_column_proportion_of_unique_values_to_be_between', 'expect_column_quantile_values_to_be_between', 'expect_column_stdev_to_be_between', 'expect_column_sum_to_be_between', 'expect_column_to_exist', 'expect_column_unique_value_count_to_be_between', 'expect_column_value_lengths_to_be_between', 'expect_column_value_lengths_to_equal', 'expect_column_value_z_scores_to_be_less_than', 'expect_column_values_to_be_between', 'expect_column_values_to_be_dateutil_parseable', 'expect_column_values_to_be_decreasing', 'expect_column_values_to_be_in_set', 'expect_column_values_to_be_in_type_list', 'expect_column_values_to_be_increasing', 'expect_column_values_to_be_json_parseable', 'expect_column_values_to_be_null', 'expect_column_values_to_be_unique', 'expect_column_values_to_match_json_schema', 'expect_column_values_to_match_like_pattern', 'expect_column_values_to_match_like_pattern_list', 'expect_column_values_to_match_regex', 'expect_column_values_to_match_regex_list', 'expect_column_values_to_match_strftime_format', 'expect_column_values_to_not_be_in_set', 'expect_column_values_to_not_be_null', 'expect_column_values_to_not_match_like_pattern', 'expect_column_values_to_not_match_like_pattern_list', 'expect_column_values_to_not_match_regex', 'expect_column_values_to_not_match_regex_list', 'expect_compound_columns_to_be_unique', 'expect_multicolumn_sum_to_equal', 'expect_select_column_values_to_be_unique_within_record', 'expect_table_column_count_to_be_between', 'expect_table_column_count_to_equal', 'expect_table_columns_to_match_ordered_list', 'expect_table_columns_to_match_set', 'expect_table_row_count_to_be_between', 'expect_table_row_count_to_equal', 'expect_table_row_count_to_equal_other_table'])`

`expect_column_pair_values_A_to_be_greater_than_B` don't match with any key!, for that reason, the dictionary returns None, and at the time to try to call `expectation_impl()...` a NoneType TypeError raises.

All this is under version 0.13.41

**Comment by talagluck** [comment]
Thanks for answering this, @bpovea! I'm going to close this for now.
