### ISSUE TITLE
ValueError on RunTimeBatchRequest.get_json_dict with a pandas df

### ISSUE THREAD

**Issue by majidaldo** [fivetran/great_expectations#2846]
**Describe the bug**
If you try to get a dict for a RunTimeBatchRequest with a pandas dataframe, you get `ValueError: The truth value of a PandasDataset is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`

**To Reproduce**
```
from great_expectations.core.batch import RuntimeBatchRequest
RuntimeBatchRequest(
    datasource_name="dsn",
    data_connector_name="dcn",
    data_asset_name="dan",
    runtime_parameters={
      "batch_data": pd.DataFrame({'c': [1,2,3]})
    },
    batch_identifiers={
        "id1": 123,
        "id2": 'abc'
    }
).get_json_dict()
```

**Expected behavior**
Should not try to serialize df.

**Environment (please complete the following information):**
 - Great Expectations Version:  0.13.19

**Comment by eugmandel** [comment]
@majidaldo Thank you for creating this issue! I see that you are trying to serialize the RuntimeBatchRequest. Could you show the broader context of this code snippet?

**Comment by majidaldo** [comment]
> @majidaldo Thank you for creating this issue! I see that you are trying to serialize the RuntimeBatchRequest. Could you show the broader context of this code snippet?

...to collect it to create a dataset. maybe i can take it out of 'meta' after validation.
