### ISSUE TITLE
Make suite-level meta (data) available in Validation Results

### ISSUE THREAD

**Issue by sushrut9898** [fivetran/great_expectations#2850]
**Is your feature request related to a problem? Please describe.**
We are creating a proper flattened table out of validation results JSON that is generated. We add a few meta (data) to the expectation suite so that we can use them as a filter while reviewing all the validation results but they never get reflected in the Validation results or data docs   

**Describe the solution you'd like**
So when ever we define a meta (data) it should get propagated to the validation results 

**Describe alternatives you've considered**
NA

**Additional context**
we define the meta tags like this in the expectation suites
![image](https://user-images.githubusercontent.com/84967939/120479779-f7e9bc80-c3cb-11eb-80ab-e1869a879c64.png)

So in validation results it should look like this 
![image](https://user-images.githubusercontent.com/84967939/120497456-0c35b580-c3dc-11eb-8ec4-a0d756a4906a.png)

**Comment by eugmandel** [comment]
@sushrut9898 I saw that you created a PR for this issue - could you please mention it in the PR's comment so that the link is visible? Thank you!

**Comment by talagluck** [comment]
Closing, as this has been resolved by #2881. Thanks, @sushrut9898!
