### ISSUE TITLE
Airflow dependency crashed when I installed develop branch

### ISSUE THREAD

**Issue by eringong** [fivetran/great_expectations#286]
I downloaded the develop branch and when I ran `python setup.py install` it crashed with this error:

```
  gcc -fno-strict-aliasing -I/Users/erin/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=442 -DPSUTIL_OSX=1 -I/Users/erin/anaconda2/include/python2.7 -c psutil/_psutil_osx.c -o build/temp.macosx-10.6-x86_64-2.7/psutil/_psutil_osx.o
  xcrun: error: invalid active developer path (/Applications/Xcode.app/Contents/Developer), missing xcrun at: /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
```
I was able to fix by removing airflow dependency.

This is likely specific to my environment/set up but wanted to document the issue here along with the fix, in case it affects anyone else.

**Comment by jpcampb2** [comment]
Thanks, @eringong for flagging. We've now removed the airflow dependency (it was only needed to use examples), so I'm going to close this issue.
