### ISSUE TITLE
Compatibility Issue between GE 0.13.7 and pybigquery 0.9.0 (or possibly other versions)

### ISSUE THREAD

**Issue by jan-aguja** [fivetran/great_expectations#2864]
**Describe the bug**
When running Great Expectations 0.13.7 (for instance to make use of the old validation operator) with the latest pybigquery (0.9.0) to validate BigQuery data, we get one of two errors. 

First is **"SchemaField object has no attribute 'precision'"**, but upon checking Google's documentation, this object _does_ have an attribute precision. If you implement ways to get around this (e.g. do a try except), you get the following error: 

> "exception_message": "ProgrammingError: (google.cloud.bigquery.dbapi.exceptions.ProgrammingError) 'param_1:INT64'\n[SQL: SELECT count(*) AS `element_count`, sum(CASE WHEN (`MONTH_VALUE` IS NULL) THEN %(param_1:INT64)s ELSE %(param_2:INT64)s END) AS `null_count`, sum(CASE WHEN (NOT (`MONTH_VALUE` >= %(MONTH_VALUE_1:INT64)s AND `MONTH_VALUE` <= %(MONTH_VALUE_2:INT64)s) AND `MONTH_VALUE` IS NOT NULL) THEN %(param_3:INT64)s ELSE %(param_4:INT64)s END) AS `unexpected_count` \nFROM `project_id.dataset_name.bq_ge_poc_temp`]\n[parameters: {'param_1': 1, 'param_2': 0, 'MONTH_VALUE_1': 1, 'MONTH_VALUE_2': 12, 'param_3': 1, 'param_4': 0}]\n(Background on this error at: http://sqlalche.me/e/f405)"

**To Reproduce**
1. Use Great Expectations 0.13.7 and pybigquery 0.9.0 and use any function that connects to BigQuery (like batch.expect_*).
2. Doing step 1 generates the first error. Modifying the code (or the pybigquery code) to avoid the offending line, you get the second error.

**Expected behavior**
It should work as expected when using an older version of pybigquery (0.5.0 is tested as working)

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows] Issue encountered within Google Cloud Composer environment
 - Great Expectations Version: [e.g. 0.13.2] 0.13.7

**Additional context**
Not really looking for a resolution since matching the versions does work and this seems to be more an issue with pybigquery than GE, but I'm filing this as instructed in Slack for whatever purpose it may serve. Hopefully it helps someone. :)

**Comment by eugmandel** [comment]
@jan-aguja Thank you for reporting this issue. Although, there is a workaround, we would invite the community to provide a fix.

**Comment by talagluck** [comment]
Hi @jan-aguja - thanks again for filing this! I'm going to close this for now, as the use of old validation operators is not a recommended pathway, and there is a workaround here, but feel free to re-open if there is a need.
