### ISSUE TITLE
Aggregate functions with DISTINCT of type STRUCT BigQuery

### ISSUE THREAD

**Issue by HustDolphin29598** [fivetran/great_expectations#2880]
**Describe the bug**
Aggregate functions with DISTINCT cannot be used with arguments of type STRUCT
`sqlalchemy.exc.DatabaseError: (google.cloud.bigquery.dbapi.exceptions.DatabaseError) 400 Aggregate functions with DISTINCT cannot be used with arguments of type STRUCT`

**To Reproduce**
1. Configure a BigQuery datasource table with a field of STRUCT type.
2. Run the generated notebook.

**Expected behavior**
It should ignore this field.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.2

**Comment by eugmandel** [comment]
@HustDolphin29598 Thank you for reporting this! We invite the community, especially someone who works with BQ regularly to create an enhancement for this issue, since it might take time before the core team gets to it.

**Comment by AFineDayFor** [comment]
Howdy @HustDolphin29598. We're closing this at the time as it's not a focus of the main team, and we haven't seen any rally behind it. As BQ has changed since, and so have we; if this is still an issue please open a new ticket for us to review.
