### ISSUE TITLE
How to switch schema with SqlAlchemyDataContext?

### ISSUE THREAD

**Issue by ilmari-abaenglish** [fivetran/great_expectations#289]
Hi,

Could you recommend a way to switch schema, which by default is public for PostgreSQL? Perhaps add set_schema method?

This works for me currently:
```
sql_context = ge.get_data_context('SqlAlchemy', options=connection_string)

sql_context.meta.schema = "other_schema"
with sql_context.engine.begin() as conn:
    conn.execute("SET search_path TO other_schema")
```

Best regards,
Ilmari

**Comment by jpcampb2** [comment]
If you'd like to set the default schema for the entire context, I believe another option would to specify it in the connection_string parameter using the currentSchema option. That would make your connection_string something like:
`postgresql://host:port/database?currentSchema=other_schema`

That would also avoid bringing postgres-specific issues into the sqlalchemy data context. Please let us know if that works for you!

**Comment by jpcampb2** [comment]
Please feel free to re-open if that doesn't work for some reason...

**Comment by ilmari-abaenglish** [comment]
Thanks @jpcampb2 for your answer, indeed it seems to work for PostgreSQL 9.4 and higher as mentioned in this answer [https://stackoverflow.com/questions/4168689/is-it-possible-to-specify-the-schema-when-connecting-to-postgres-with-jdbc](url)

We're on Redshift to be precise and this doesn't work unfortunately, but don't worry, I can work around it. I totally understand that you wouldn't like to include database specific code.
