### ISSUE TITLE
Data Docs update not working from within Databricks

### ISSUE THREAD

**Issue by anthonyburdi** [fivetran/great_expectations#2906]
**Describe the bug**
When running a databricks notebook which uses s3 as the store backend for metadata stores, all validation actions run except for the data docs validation action. The store backend for data docs is configured to the same store backend as the other metadata stores, which makes it unlikely (but still possible) that this is a bucket permissions issue.

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/9903066/121929504-458cf000-cd0f-11eb-9b00-95ab1dfe9975.png">
<img width="659" alt="image" src="https://user-images.githubusercontent.com/9903066/121929701-79681580-cd0f-11eb-9b7b-ef3d35565cf3.png">

**To Reproduce**
1. Set up a data context in-code within a databricks notebook using s3 as the metadata store backend (expectations store, validations store, checkpoint store, data docs)
2. Load or create an expectation suite 
3. Run a validation (checkpoint, etc) with writing to data docs as an action **OR** run `context.build_data_docs()`

**Expected behavior**
I expect data docs to be built successfully and written to the corresponding store backend (s3 in this case)

**Environment (please complete the following information):**
 - Operating System: Databricks
 - Great Expectations Version: 0.13.19

**Additional context**
Note: this configuration works locally for writing datadocs to the filesystem or to s3. This configuration uses the same s3 bucket for all other stores.

**Comment by shpolina** [comment]
I was experiencing something similar and I think it is a combination of two errors. The first - issue with accessing the bucket (`ClientError`) and a subsequent issue to render the error in the datadocs (`ValidationError`). I think the second error is fixed by https://github.com/great-expectations/great_expectations/pull/2909
