### ISSUE TITLE
Support for pyspark >=3.0.0

### ISSUE THREAD

**Issue by richagaur** [fivetran/great_expectations#2928]
We use Spark 3.0.1 and pyspark = 3.0.1  in our compute cluster.  I want to use Great Expectation for our feature pipeline validation tasks.

Please enable support for pyspark>=3.0.0.

**Comment by jcampbell** [comment]
@richagaur --> We've actually recently done the hard work on this, and need only to update the integration tests. I'm doing that now...stand by in https://github.com/great-expectations/great_expectations/pull/2930

**Comment by richagaur** [comment]
Thanks a lot @jcampbell. Looking forward to this.

**Comment by jcampbell** [comment]
@richagaur : fix is merged. Release coming tomorrow!
