### ISSUE TITLE
ENH: support hdf5 files

### ISSUE THREAD

**Issue by mattip** [fivetran/great_expectations#293]
Just heard the podcast about your package, and am interested if you had considered integration with hdf5 file format?

**Comment by ccnobbli** [comment]
We have no immediate plans - at the moment we're furiously working on getting SQL all the way up to speed and also hopefully rolling out support for Spark very soon.

Coincidentally, one of our core devs was wishing today that this existed though. I don't have much experience with the format myself but it seems there is a powerful pandas/hdf5 API through the `h5py` package (http://www.h5py.org/).  I bet that package would make it fairly simple to build support off of.
