### ISSUE TITLE
Bug in expect_column_values_to_be_of_type for PyAthena SQL dialect

### ISSUE THREAD

**Issue by BenGale93** [fivetran/great_expectations#2937]
In combination with PyAthena, I am unable to use the "expect_column_values_to_be_of_type" expectation when checking whether a column is of STRINGTYPE.

**To Reproduce**
1. Construct a SqlAlchemyDataset where the dialect is "module 'pyathena.sqlalchemy_athena'". Ensure that at least one column is of String type.
2. Run expect_column_values_to_be_of_type(col_name, "STRINGTYPE").
3. Observe that the resulting error is "TypeError: issubclass() arg 2 must be a class or tuple of classes".

**Expected behavior**
I would expect the method to check against the String class, not an instance of String().

**Environment:**
 - Great Expectations Version 0.13.19
 - PyAthena 2.3.0

**Additional Information**
Running the following code indicates why the error is occurring.

```python
from pyathena import sqlalchemy_athena

inspect.isclass(sqlalchemy_athena.STRINGTYPE)

inspect.isclass(sqlalchemy_athena.BIGINT)
```

The first function call returns False whereas the second call returns True.  The end result is that in great_expectations/dataset/sqlalchemy_dataset.py line 1622 the getattr call return an instance if the type specified is STRINGTYPE.

```python
success = issubclass(col_type, getattr(type_module, type_))
```

**Potential fix**
Replace the else clause with the following:

```python
type_module = self._get_dialect_type_module()
potential_type = getattr(type_module, type_)
if not inspect.isclass(potential_type):
    real_type = type(potential_type)
else:
    real_type = potential_type
success = issubclass(col_type, real_type)
```

**Comment by talagluck** [comment]
Hi @BenGale93 - thanks so much for raising this issue, and apologies for delays! 

This is something that we will not be able to prioritize work on in the immediate future. That said, it looks like you are most of the way to a fix, and we always welcome contributions. I'm happy to prioritize a PR review if you would like to make a contribution, and I can also offer additional guidance as needed. Is that something that would interest you?

**Comment by BenGale93** [comment]
Hi @talagluck it will be my fist open source pull request so apologies for any faux pas in advance. I'll set one up as soon as possible.

**Comment by talagluck** [comment]
Thanks, @BenGale93! No worries at all, I'm happy to help wherever I can. Looking forward!
