### ISSUE TITLE
Expectation-level preprocessing

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#294]
Here's a draft proposal for expectation-level preprocessing.

The gist: Similar to `Expectations`, we will implement `Preprocessors` as decorated function types within the main `Dataset` class.

Preprocessors are invoked like this:
```
my_df.expect_column_values_to_be_between(
	column = {
                “preprocessor” : build_timeseries_histogram,
                “input” : "my_timestamp_column"
        },
	min = 9, #9:00 to 5:00
	max = 17,
	mostly = .95
)
```

They are defined (something) like this:
```
class Custom(great_expectations.Dataset):
	def preprocessor:
		#I’m a decorator!

	@preprocessor
	def build_timeseries_histogram(self, series):
		#I'm a specific preprocessing method!
```

There's a lot more [owl to draw](https://www.reddit.com/r/restofthefuckingowl/) here, but that's the outline.

Notes:
* It's important that we're invoking the preprocessing function by name, not by executing a code snippet (e.g. a lambda stored as a string). Code snippets would introduce a massive security hole into GE.
* Because the preprocessing function belongs to a specific namespace, we can be confident that preprocessing string names will be uniquely identifiable.
* This approach doesn't preclude something like the proposal in #80. That's top-down. This is bottom-up. My sense is that starting bottom-up will be more useful.
* This proposal will likely lead to a large-ish library of common preprocessing functions. Individually, they should be fairly simple to build and test. There will be some complexity around cross-platform consistency, but we're already facing that with Expectations, so it shouldn't muddy up the codebase too badly.
* I recommend that we *not* treat preprocessor validation ("Can this preprocessor be applied to this expectation + column + data?") as in-scope for GE. Instead, we should content ourselves with informative error messages.

Other scratch notes from today's conversation:
```
my_df.expect_column_values_to_be_between(
	column = "my_unix_epoch_column",
	min = 9, #9:00 to 5:00
	max = 17,
	mostly = .95,
	element_preprocessor = "lambda x: convert_epoch_to_military_time(x)"
)


------------------------------------------------------------------------------------------


my_df.expect_column_values_to_be_between(
	column = "$preprocessor_output",
	min = 9, #9:00 to 5:00
	max = 17,
	mostly = .95,
	aggregate_preprocessor = "lambda series: convert_series_of_epochs_to_military_times(series)"
)


------------------------------------------------------------------------------------------


{
	"convert_epoch_to_military_time" : convert_epoch_to_military_time,
}

my_df.expect_column_values_to_be_between(
	column = "my_unix_epoch_column",
	min = 9, #9:00 to 5:00
	max = 17,
	mostly = .95,
	element_preprocessor = "convert_epoch_to_military_time"
)

------------------------------------------------------------------------------------------

class preProc(object):
	name = ‘basename’
	def getName():
		return __[class]name__

class myPreProc(ge.main.preProc):
	def map_preprocess(self, x):
		#dostuff

	def row_preprocess(self, x):
		
	def aggregate_preprocess(self, series):

}

my_df.expect_column_values_to_be_between(
	column = "my_unix_epoch_column",
	min = 9, #9:00 to 5:00
	max = 17,
	mostly = .95,
	element_preprocessor = myPreProc
)



------------------------------------------------------------------------------------------

my_df.expect_column_values_to_be_between(
	column = "$preprocessor_output",
	min = 9, #9:00 to 5:00
	max = 17,
	mostly = .95,
	aggregate_preprocessor = "lambda series: convert_series_of_epochs_to_military_times(series)"
)


---------------------------------------------------------------------__------------------

------------------------------------------------------------------------------------------

class Custom(dataset):
	def preprocessor:
		#I’m a decorator!

	@map[?]_preprocessor
	def build_timeseries_histogram(self, series):
		


my_df.expect_column_values_to_be_between(
	column = "$preprocessor",
	min = 9, #9:00 to 5:00
	max = 17,
	mostly = .95,
	element_preprocessor = build_timeseries_histogram(column_name)
)

-----------------------------------------------------------------------------------------------------------

my_df.expect_column_values_to_be_between(
	column = "my_timestamp_column",
	min = 9, #9:00 to 5:00
	max = 17,
	mostly = .95,
	element_preprocessor = build_timeseries_histogram
)

-----------------------------------------------------------------------------------------------------------

#Winner?

my_df.expect_column_values_to_be_between(
	column = {
“preprocessor” : build_timeseries_histogram,
“input” : "my_timestamp_column"
},
	min = 9, #9:00 to 5:00
	max = 17,
	mostly = .95
)
```

**Comment by jpcampb2** [comment]
Cross-referencing the open issue on this: #80 

Good convo today and good capture. I like it for the wish list!

**Comment by ccnobbli** [comment]
One minor thing from me: When I hear "preprocess" I think of optimization, but maybe it is more meaningful and closer to its intended definition for others.

I would have been more apt to call it a transformation or something along those lines.

**Comment by early-riser18** [comment]
What is the status on this issue? I cannot find any resolution and yet, it is still a very relevant topic.
