### ISSUE TITLE
Ability to use expectations on pandas timestamps

### ISSUE THREAD

**Issue by edwardcjohnson** [fivetran/great_expectations#2946]
Thank you for all the great work in this project!

My request is to be able to pass timestamp columns from pandas dataframes into expectations .

Example:
```
import pandas as pd
import numpy as np
df = pd.DataFrame({'date_time': pd.date_range('2021-01-01', periods=5, freq='T') })
df = ge.dataset.PandasDataset(df)

min_date = df.get_column_min(column='date_time')
max_date = df.get_column_max(column='date_time')

df.expect_column_values_to_be_between(
    column='date_time', 
    min_value=min_date,
    max_value=max_date
)
```

Currently fails with:
"TypeError: Column values, min_value, and max_value must either be None or of the same type." unless i cast the timestamp column to a string first.
I'd like to be able to directly pass a timestamp column without first having to cast to string.

Maybe this is already possible, and i am just missing something.

Thank you for your consideration.

**Comment by pppls** [comment]
The provided example code works (checked on commit 08b9283).

**Comment by talagluck** [comment]
Thanks for submitting, @edwardcjohnson and apologies for delays! Based on @pppls's comment, it appears that this might currently be working. Would you please confirm whether or not this is still an issue for you?

**Comment by edwardcjohnson** [comment]
@talagluck, yes I can confirm that this works in version '0.13.26'.
Thank you and @pppls for your support!
