### ISSUE TITLE
import great_expectation is slow

### ISSUE THREAD

**Issue by ynouri** [fivetran/great_expectations#2984]
## Describe the bug

Importing the `great_expectations` package is slow.

## To reproduce

Time it:
```
 $ time python -c "import great_expectations"
 2.60s user 0.80s system 179% cpu 1.889 total
```

Profile it:
```
$ echo "import great_expectations" > import_great_expectations.py
$ python -m cProfile --sort cumtime import_great_expectations.py | head -n 20

         1945600 function calls (1906899 primitive calls) in 2.090 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      191    0.012    0.000    7.965    0.042 __init__.py:1(<module>)
       17    0.001    0.000    2.882    0.170 __init__.py:2(<module>)
   2768/1    0.032    0.000    2.093    2.093 {built-in method builtins.exec}
        1    0.000    0.000    2.093    2.093 import_great_expectations.py:1(<module>)
   2200/1    0.010    0.000    2.093    2.093 <frozen importlib._bootstrap>:986(_find_and_load)
   2197/1    0.007    0.000    2.093    2.093 <frozen importlib._bootstrap>:956(_find_and_load_unlocked)
   2052/1    0.008    0.000    2.092    2.092 <frozen importlib._bootstrap>:650(_load_unlocked)
   1868/1    0.004    0.000    2.092    2.092 <frozen importlib._bootstrap_external>:777(exec_module)
   2667/1    0.001    0.000    2.092    2.092 <frozen importlib._bootstrap>:211(_call_with_frames_removed)
        1    0.000    0.000    2.087    2.087 data_context.py:1(<module>)
       12    0.000    0.000    1.920    0.160 util.py:1(<module>)
   791/75    0.002    0.000    1.598    0.021 {built-in method builtins.__import__}
2458/1328    0.003    0.000    0.867    0.001 <frozen importlib._bootstrap>:1017(_handle_fromlist)
        1    0.000    0.000    0.714    0.714 expectation_suite.py:1(<module>)
        1    0.000    0.000    0.695    0.695 expectation_configuration.py:1(<module>)
```

## Expected behavior

2 seconds is a lot - especially for "light" users. Only a couple hundred milliseconds of import time would be more reasonable.

I looked for settings or environment variables that could maybe disable or minimize the loading of all Great Expectations dependencies, confgurations, data contexts, but couldn't find anything.

## Environment

 - Operating System: MacOS
 - Great Expectations Version: 0.13.21

## Additional context

A very similar issue was raised in 2019 and received a fix: https://github.com/great-expectations/great_expectations/issues/573
It seems that the performance drag related to IPython is gone.

**Comment by jcampbell** [comment]
@ynouri -- I think you're absolutely right about this, and unfortunately, it's largely related to the way that the current imports are structured. That's the bad news.

The good news is that it is definitely on my radar to fix it, and a lot of the preparatory work has already been done, incrementally, over the past few months to help break GE to be inherently more modular. I'd recommend we keep this issue open -- I've got an analogous internal issue -- and we can try to stay in sync here about updates as they come.

The ugly news: I haven't been able to get this to rise to the top of the priority list yet, so I think it'll be at least several months before we have the really visible progress that we both want on it. Thank you for flagging it, and I'll keep in mind in case I can work in marginal improvements sooner!

**Comment by AFineDayFor** [comment]
Howdy @ynouri.

There hasn't been any activity on this in some while, so we're going to close this issue.
If you would like to open a new one with more context, or provide a contribution which would alleviate this in some way we'd be very welcome to it indeed.

That said, we have been working on some things internally that may improve this.
