### ISSUE TITLE
S3 InvalidKeyError: Unable to retrieve object from TupleS3StoreBackend with the following Key

### ISSUE THREAD

**Issue by alermolaev** [fivetran/great_expectations#2993]
**Describe the bug**
I'm trying to setup the config from the code and use S3 backend store for storing expectations. 

Here is my code

```
data_context_config = DataContextConfig(
            datasources={
                "my_datasource": DatasourceConfig(
                    class_name="SqlAlchemyDatasource",
                    credentials={
                        "drivername": "postgresql+psycopg2",
                        "host": "my_host",
                        "port": "my_port",
                        "username": "my_user",
                        "password": "my_pass",
                        "database": "my_db",
                    },
                )
            },
            validation_operators={
                "action_list_operator": {
                    "class_name": "ActionListValidationOperator",
                    "action_list": [
                        {
                            "name": "store_validation_result",
                            "action": {"class_name": "StoreValidationResultAction"},
                        },
                        {
                            "name": "store_evaluation_params",
                            "action": {"class_name": "StoreEvaluationParametersAction"},
                        },
                        {
                            "name": "update_data_docs",
                            "action": {"class_name": "UpdateDataDocsAction"},
                        },
                    ],
                }
            },
            stores={
                "expectations_S3_store": {
                    "class_name": "ExpectationsStore",
                    "store_backend": {
                        "class_name": "TupleS3StoreBackend",
                        "bucket": "my_bucket",
                        "prefix": "my_prefix",
                    },
                },
                "validations_S3_store": {
                    "class_name": "ValidationsStore",
                    "store_backend": {
                        "class_name": "TupleS3StoreBackend",
                        "bucket": "my_bucket",
                        "prefix": "my_prefix",
                    },
                },
                "evaluation_parameter_store": {"class_name": "EvaluationParameterStore"},
            },
            data_docs_sites={
                "s3_site": {
                    "class_name": "SiteBuilder",
                    "store_backend": {
                        "class_name": "TupleS3StoreBackend",
                        "bucket": "my_bucket",
                        "prefix": "my_prefix",
                    },
                    "site_index_builder": {
                        "class_name": "DefaultSiteIndexBuilder",
                        "show_cta_footer": True,
                    },
                }
            },
            store_backend_defaults=S3StoreBackendDefaults(default_bucket_name="my_bucket"),

        )


context = BaseDataContext(project_config=data_context_config)
batch_kwargs = {"data_asset_name": 'custom_sql_query', "datasource": 'my_datasource', 'limit':1000, 
                'schema': 'my_schema',
               'table': 'my_table'}

suite = context.create_expectation_suite('test_configless2')

batch = context.get_batch(batch_kwargs, suite)

batch.expect_table_row_count_to_be_between(min_value=1,max_value=100000000)

batch.save_expectation_suite(discard_failed_expectations=False)

results = context.run_validation_operator("action_list_operator", assets_to_validate=[batch])
```

On S3 path looks like 
`test_configless2/20210705T133824.449268Z/20210705T133824.449268Z/some_string.json`

But I get an error 

`Unable to retrieve object from TupleS3StoreBackend with the following Key: test_configless2/20210705T133824/449268Z/20210705T133824/449268Z/some_string.json`

**To Reproduce**
1. Run the code against some data source and check S3

**Expected behavior**
Formatting should match imo

**Environment (please complete the following information):**
 - MacOS 10.15.7
 - Great Expectations Version: 0.13.19
 - boto3 version: 1.17.105

**Additional context**
Same with Great Expectations Version: 0.13.21

**Comment by alermolaev** [comment]
Anyone, please?

**Comment by talagluck** [comment]
Hi @alermolaev - apologies for delays! We've had a bit of a backlog of contributions, but are starting to expand our devrel team, so response times will be improving!

Thank you for your question - I've tried setting up a project based on the config you shared, and I'm not getting the same issue. I noticed the problem you pointed to, which indeed seems like an issue

> On S3 path looks like
> test_configless2/20210705T133824.449268Z/20210705T133824.449268Z/some_string.json
> 
> But I get an error
> 
> Unable to retrieve object from TupleS3StoreBackend with the following Key: test_configless2/20210705T133824/449268Z/20210705T133824/449268Z/some_string.json

but I am not getting this issue - for me, the s3 subdirectory created contains a name with a dot in it, and it does not parse the `.` as a `/`. Would you mind creating a new GE project, trying this again, and confirming you get the same issue?

**Comment by alermolaev** [comment]
Hi @talagluck. I tried on a different machine and still got this error :(
For the reference: on the other machine I have boto3 1.16.40, ge 0.13.19

**Comment by talagluck** [comment]
Hi @alermolaev - I was able to reproduce and determine a work-around, though I'll need to dig a little deeper to find out exactly why this is happening. Currently, the prefixes for all of your stores are the same: `my_prefix`. For some reason, the parsing of the bucket name is failing on this. Could you try appending `expectations`, `validations`, etc to the prefixes for each of the stores (e.g. `my_prefix/expectations`, `my_prefix/validations`, etc.)? I believe this should solve your problem.

As an aside, this is the convention that we would generally recommend - otherwise, all of your expectations, validations, and data docs sites will wind up in the same directory, and it can become hard to distinguish between them.

**Comment by alermolaev** [comment]
Hi @talagluck, thank you for reaching out. Just tested appending to the prefixes and it seems to work 👍

**Comment by talagluck** [comment]
Awesome - thanks for letting me know!
