### ISSUE TITLE
Remove airflow dependency

### ISSUE THREAD

**Issue by schrockn** [fivetran/great_expectations#301]
The inclusion of apache-airflow[s3] in requirements.txt -- only there for an example -- dramatically expands the footprint of installing ge. 

Repro: Create two virtual environments. Install currently checked in requirements file. If you list the pip modules, there are 69 of them, and lots of them are very heavyweight (e.g. flask)

(ge_with_airflow) $ pip list | wc -l
69

Removing 

apache-airflow[s3]>=1.9.0
boto3>=1.7.3

from requirements.txt leaves you with only 14 modules.

(ge_without_airflow) $ pip list | wc -l
14

cc: @abegong

**Comment by jpcampb2** [comment]
Wow, yes, I think I'd pulled that out locally because it was added as an example for dev and we specifically pulled it out of the build codepath. I'll take that as a quick chore.
