### ISSUE TITLE
Adding GCP storage as a Datasource

### ISSUE THREAD

**Issue by sephiartlist** [fivetran/great_expectations#3021]
**Why**
Currently GE supports[ S3 as a Datasource](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_datasources/how_to_configure_a_pandas_s3_datasource.html) .  The suggestion is to support [GCP storage](https://cloud.google.com/storage) in the same manner

**How**
Support the same features as S3, with  similar [data-connector](https://github.com/great-expectations/great_expectations/tree/develop/great_expectations/datasource/data_connector) architecture:

TBD
Should it be based on [gcsfs library](https://github.com/dask/gcsfs)?

**Additional context**
Include an [how to guideline](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_datasources.html) to the documentation

**Comment by talagluck** [comment]
Hi @sephiartlist - thanks so much again for submitting this issue! This is actually on the roadmap for one of the next few sprints. When our product engineering team begins work on this, someone will be in touch to collaborate.

**Comment by talagluck** [comment]
Hi @sephiartlist ! Just a heads-up, @cdkini and @fjork3 will be working on this this sprint, and so they will set up a time to connect.

**Comment by talagluck** [comment]
Thanks again for opening this! I believe this has been implemented, so I will close this issue for now.
