### ISSUE TITLE
Add `expect_column_names_to_be_unique`

### ISSUE THREAD

**Issue by sotte** [fivetran/great_expectations#303]
When working with messy data (ie always) something like `expect_column_names_to_be_unique` would be great. What do you think?

PS: great-expectations is a great tool btw!

**Comment by ccnobbli** [comment]
Wow, and here I thought this sort of thing would be implicit in pandas! This is a great idea for an expectation, imo.

Thanks for the love!

**Comment by jpcampb2** [comment]
Agreed--PR welcome!

**Comment by ncsu-las** [comment]
One of the reasons it might not be in pandas is because pandas is trying to be helpful. For example, if you have a CSV file and your columns are named ['x', 'y', 'z', 'z', 'z'], then pandas' read_csv method will happily read the file, but the column names will be ['x', 'y', 'z', 'z.1', 'z.2'].
