### ISSUE TITLE
Add native support for validating files in orc format

### ISSUE THREAD

**Issue by Sekhar1988** [fivetran/great_expectations#3033]
**Is your feature request related to a problem? Please describe.**
Currently, orc is not one of the formats that is supported for validation

**Describe the solution you'd like**
It would be great if great expectations could support orc files validation natively.

**Describe alternatives you've considered**
In order to work around with this, we have decided to offload the reading of orc to spark and then pass in the spark dataframe as a configuration parameter to the batch kwargs API.

**Comment by talagluck** [comment]
Hi @Sekhar1988 - thanks for submitting this issue. We have discussed this internally, and are unable to support this in the near future. That said, we would welcome and can provide support on a contribution around this if you would like to help. I'm going to close this issue for now, but if this is of interest to you, feel free to re-open, or just open a PR.

Thank you!
