### ISSUE TITLE
Add an overall success field to the report created by `.validate()`

### ISSUE THREAD

**Issue by sotte** [fivetran/great_expectations#305]
I think it would be great if the validation report (the json/dict you get when you call `.validate()`) would contain the overall validation success, not just a list of of results.
```
>>> my_df.validate()
{
  "results" : [ ...],
  "success": True  # <--- this is new
}
```

**Comment by abegong** [comment]
Yes, we should definitely do that.

Also, summary stats "x% succeeded and y% failed" would be great.

**Comment by jpcampb2** [comment]
Agree--this will be a great addition.

Wrt the way to convey the stats: I'd suggest we either use the key 'details' paralleling the way column_aggregate_expectations return addition information, or the key 'result', paralleling the usual result. I'd prefer 'result' probably except it could be confusing given our current use of 'results', and we may want to expand what goes there (e.g. listing when variables are substituted from meta) in the future.

So:
```
{
  "results": [...],
  "success": True,
  "details": {
    "evaluated_expectations": k,
    "successful_expectations": k',
    "unsuccessful_expectations": k''
    "success_percent": k' / k
  }
}
```
