### ISSUE TITLE
InferredAssetFilesystemDataConnector : Nested directory structure with the data_asset_name on the outside not working

### ISSUE THREAD

**Issue by nilavghosh** [fivetran/great_expectations#3080]
**Describe the bug**
The example mentioned here in the documents is not working: 
[https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_datasources/how_to_configure_an_inferredassetdataconnector.html#example-4-nested-directory-structure-with-the-data-asset-name-on-the-outside] 

**To Reproduce**
1. Create a folder structure 
<img width="188" alt="image" src="https://user-images.githubusercontent.com/657155/126331822-04fa8edf-6b97-427c-b5e1-1d63dcb0c34f.png">

2. Create a new datasource yaml config
![image](https://user-images.githubusercontent.com/657155/126332572-d5426691-4c2b-40c5-b793-7da8d3c0933e.png)

3. When I run the command to test the yaml config, this is what i get
![image](https://user-images.githubusercontent.com/657155/126332219-9f369924-fd0f-4ded-be50-f0556e9b64c6.png)

4. I do not see the data asset groups as mentioned in the documentation.

**Expected behavior**
![image](https://user-images.githubusercontent.com/657155/126332450-335f7d0c-5a88-4781-ab4a-3b332ad42e90.png)

**Environment (please complete the following information):**
 - Operating System: MacOS, Linux
 - Great Expectations Version: 0.13.8

**Additional context**

**Comment by talagluck** [comment]
Hi @nilavghosh - thank you for submitting this issue and apologies for delays! Someone will review and be in touch over the next few days.

**Comment by kimyphan** [comment]
You need to include `glob_directive` such that you would have the following:

```python
example_yaml = f"""
name: {datasource_name}
class_name: Datasource
execution_engine:
  class_name: PandasExecutionEngine
data_connectors:
  {datasource_name}_example_data_connector:
    class_name: InferredAssetFilesystemDataConnector
    base_directory: /data
    glob_directive: '*/*.csv'
    default_regex:
      group_names:
        - data_asset_name
        - filename
      pattern: (\d+)/(.*)\.csv
"""
print(example_yaml)
```

I found the answer to this in the legacy documentation for ["How to configure a ConfiguredAssetDataConnector"](https://legacy.docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_datasources/how_to_configure_a_configuredassetdataconnector.html). It's not currently in the new documentation (nor was in the legacy documentation for ["How to configure an InferredAssetDataConnector"](https://legacy.docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_datasources/how_to_configure_an_inferredassetdataconnector.html) for that matter so perhaps you could ask your team update this @talagluck?

**Comment by talagluck** [comment]
Thanks so much for jumping in on this @kimyphan! One of us could definitely update this - I also wanted to offer you the opportunity to submit a PR for this docs update in case you were interested? Let me know (and let me know if you need any help)! Otherwise we'll take care of this early next week.
