### ISSUE TITLE
Add service principal authentication support for `TupleAzureBlobStoreBackend`

### ISSUE THREAD

**Issue by trymzet** [fivetran/great_expectations#3089]
Currently, `TupleAzureBlobStoreBackend` only supports blob connection string (`AZURE_STORAGE_CONNECTION_STRING`). However, in many companies, the preferred way to authenticate is through service accounts ("service principals" as Msoft calls them).

Could possibly be done using [adlfs](https://github.com/dask/adlfs):
```python
from adlfs import AzureBlobFileSystem

fs = AzureBlobFileSystem(
    account_name=storage_account_name,
    tenant_id=tenant_id,
    client_id=client_id,
    client_secret=client_secret,
)
fs.cp(from_path, to_path)
fs.exists(path)
fs.download(rpath, lpath)
...
```

**Comment by talagluck** [comment]
Hi @Trymzet - thank you so much for submitting this issue! After some internal discussion, this is something that we can't prioritize in the near future. That said, if this is something that you would like to contribute, I'd be happy to offer support and guidance. Is this something in which you might be interested?

**Comment by talagluck** [comment]
We may also be doing some work on authentication for an Azure DataConnector which could dovetail nicely with this. If that is the case, someone working on this from the core team will be in touch.

**Comment by sdebruyn** [comment]
The PR I've linked above adds support for all common Azure authentication methods for store backends

**Comment by alexszym** [comment]
Would love to see this merged
