### ISSUE TITLE
All `great_expectations` commands output a deprecation warning

### ISSUE THREAD

**Issue by cdkini** [fivetran/great_expectations#3108]
**Describe the bug**
`great_expectations --version` outputs a deprecation warning from `collections` that should not be outputted to the user:
<img width="932" alt="Screen Shot 2021-07-23 at 12 55 43 PM" src="https://user-images.githubusercontent.com/49923762/126815873-2d584e13-35f1-4a06-a02b-b46d92046d46.png">

Additionally, should the commit hash be a part of the version? Might we want to truncate that? @talagluck cc'ing to put on your radar.

**To Reproduce**
1. `great_expectations --version` or any other GE command

**Expected behavior**
Just the GE version number is outputted. 

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.23

**Additional context**
This is a low priority issue so it may be a `good_first_issue` for new contributors?

**Comment by cdkini** [comment]
Please note that we are also seeing deprecation warnings around `column_aggregate_metric`/`column_aggregate_metric_provider` as a result of https://github.com/great-expectations/great_expectations/commit/a591cf94edec346513dac59444e315fbcdcc9f99.

That fix may be part of a separate issue but I will keep the status up-to-date here.

**Comment by cdkini** [comment]
Issue regarding `column_aggregate_metric` warning is to be resolved here: [INSERT PR]

**Comment by talagluck** [comment]
I believe this is resolved by #3228 and #3546. Closing for now.
