### ISSUE TITLE
column max has no datetime support in sqlalchemy

### ISSUE THREAD

**Issue by Hrithvik-Alex** [fivetran/great_expectations#3115]
**Is your feature request related to a problem? Please describe.**
#414 added support to parse strings as datetimes within sqlalchemy, but only for `expect_column_values_to_be_between`. `expect_column_max_to_be_between` does not have support for this however, since `get_column_max` throws `NotImplementedError`.

**Describe the solution you'd like**
To potentially add support for this `expect_column_max_to_be_between` to support datetime parsing

**Describe alternatives you've considered**
If anyone could point me to a better way to determine data freshness (when table was last written to), I would love to know. I am currently trying to create an expectation that data has been written in the last 4 hours.

**Comment by talagluck** [comment]
Hi @Hrithvik-Alex - thanks for raising this issue!

With the V3 Batch Request API, we have decided to remove all support for `parse_strings_as_datetimes` - the inclusion with `expect_column_values_to_be_between` was actually an oversight, and this will be removed in a future release.

I recognize that this might be the opposite answer that you expected, but it comes after a lot of careful thought and deliberation. GE is designed for validating data and if we use GE to translate strings, we are blurring the data pipeline with the validation tool, and not validating the actual data contained in our datasource. We are working to create a distinct separation between the “transform” and “validate” stages of a pipeline. Our recommendation would be to transform strings into datetimes as part of a "transform" process prior to validation.

I'm going to close this issue for now, though I will make a new issue to signal our removal of `parse_strings_as_datetimes` from `expect_column_values_to_be_between`.

Thank you again for your question!
