### ISSUE TITLE
Snowflake pip install error with python3.9

### ISSUE THREAD

**Issue by jdimatteo** [fivetran/great_expectations#3116]
**Describe the bug**

**To Reproduce**

Follow instructions at https://docs.greatexpectations.io/en/latest/contributing/setting_up_your_dev_environment.html#contributing-setting-up-your-dev-environment with Python 3.9, e.g.

```
# use Python 3.9, e.g. below runs python:3.9.6-buster latest official Python 3.9.6 as of July 27, 2021 with Debian Buster
$ docker run -it --entrypoint bash --rm python@sha256:59f4ce1606587995e38fe148b9218375418d0ef273fabf138b8987e9de2e3cde

# this example was tested with great expectations develop commit 45cbe84
root@f88da3bd88d1:/# apt-get update && apt-get install unixodbc-dev
root@f88da3bd88d1:/# python3.9 -m pip install --upgrade pip
root@f88da3bd88d1:/# git clone https://github.com/great-expectations/great_expectations.git
root@f88da3bd88d1:/# cd great_expectations/
root@f88da3bd88d1:/great_expectations# python3.9 -m venv great_expectations_dev
root@f88da3bd88d1:/great_expectations# source great_expectations_dev/bin/activate
(great_expectations_dev) root@f88da3bd88d1:/great_expectations# pip install -r requirements-dev.txt -c constraints-dev.txt
...
ERROR: No matching distribution found for snowflake-connector-python==2.3.8
```

See [full pip install error here](https://github.com/great-expectations/great_expectations/files/6888000/pip.install.snowflake.error.2.txt).

**Expected behavior**
No pip install error.

**Environment (please complete the following information):**
 - Operating System: Linux (e.g. Debian Buster)
 - Great Expectations Version: develop branch at commit 45cbe84

**Additional context**
Problems with pip install was discussed recently at https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1627063334302600.

**Comment by jdimatteo** [comment]
FWIW, separately from this PR, I suggest using pip-compile to pin all requirements (even indirect dependencies) to help prevent problems like this -- see https://github.com/jazzband/pip-tools#readme

**Comment by ismaildawoodjee** [comment]
@jdimatteo Happened to me as well, Python v3.9.5 Windows 10
