### ISSUE TITLE
Write a great "Tutorial" / "Getting Started" guide

### ISSUE THREAD

**Issue by sotte** [fivetran/great_expectations#312]
great_expectations is great ;) But it took me a bit till it really clicked.
I suggest to write a short tutorial/getting started guide that walks the user through a simple data analysis and shows of the great_expectations workflow.

**Comment by clmeha** [comment]
I want to tackle this one

**Comment by abegong** [comment]
Yes, please!

We have some links in the README, but they leave plenty to be desired...

**Comment by Aylr** [comment]
The project has come a long way since this request. Closing.
