### ISSUE TITLE
Running a SimpleCheckpoint on a Spark DataFrame validation data returns 'RecursionError'

### ISSUE THREAD

**Issue by davideromano** [fivetran/great_expectations#3148]
**Bug description**
When you use GE api v3 and you try to run a SimpleCheckpoint on a SparkDF passed on the run as a validation object, the error `RecursionError: maximum recursion depth exceeded while calling a Python object` was thrown.
This error does not occur when I use Pandas as Execution Engine (and to read the dataframe) instead of Spark.

**To Reproduce**
Here the code that you can use to reproduce the issue. Please fill it with a valid `.csv` dataset file and with an expectations suite that can fit the dataset.

```
from great_expectations.data_context.types.base import DataContextConfig
from great_expectations.data_context import BaseDataContext

spark = SparkSession.builder.master('local').getOrCreate()
sc = spark.sparkContext
df = spark.read.format("csv").load("file_name.csv")

data_context_config_test = DataContextConfig(
    datasources={
        "name": "ds_name",
         "class_name": "Datasource",
         "execution_engine": {"class_name": "SparkDFExecutionEngine"},
             "data_connectors": {
                 "dc_name": {
                     "class_name": "RuntimeDataConnector",
                     "batch_identifiers": ["batch_id"],
                 },
             },
    },
    stores={
        "checkpoints_store": {
            "class_name": "CheckpointStore",
            "store_backend": {
                "class_name": "TupleFilesystemStoreBackend",
                "base_directory": "/opt/project/checkpoints",
            }
        },
        "expectations_store": {
            "class_name": "ExpectationsStore",
            "store_backend": {
                "class_name": "TupleFilesystemStoreBackend",
                "base_directory": "/opt/project/expectation_suites",
            }
        },
        "validations_store": {
            "class_name": "ValidationsStore",
            "store_backend": {
                "class_name": "TupleFilesystemStoreBackend",
                "base_directory": "/opt/project/validations",
            }
        },
        "evaluation_parameter_store": {"class_name": "EvaluationParameterStore"},
    },
    expectations_store_name="expectations_store",
    validations_store_name="validations_store",
    evaluation_parameter_store_name="evaluation_parameter_store",
    checkpoint_store_name="checkpoints_store",
    data_docs_sites={
        "s3_site": {
            "class_name": "SiteBuilder",
            "store_backend": {
                "class_name": "TupleFilesystemStoreBackend",
                "base_directory": "/opt/project/docs",
            },
            "site_index_builder": {
                "class_name": "DefaultSiteIndexBuilder",
                "show_cta_footer": False,
            },
        }
    },
    anonymous_usage_statistics={
        "enabled": False
    }
)

context = BaseDataContext(project_config=data_context_config_test)

yaml_config = f"""
    name: checkpoint_name
    config_version: 1
    class_name: SimpleCheckpoint
    validations: []
    expectation_suite_name: table.suite
    """

checkpoint = context.test_yaml_config(
        yaml_config=yaml_config,
        name="checkpoint_name",
    )

checkpoint.run(validations=[
                   {"batch_request": {
                       "datasource_name": "ds_name",
                       "data_connector_name": "dc_name",
                       "data_asset_name": "da_name",
                       "runtime_parameters": {"batch_data": df},
                       "batch_identifiers": {"batch_id": "test_id"},
                   },
                    "expectation_suite_name": 'table.suite',
                   }
               ])
```

**Expected behavior**
When you run the code linked above, you will be able to reproduce the error `RecursionError: maximum recursion depth exceeded while calling a Python object`. It seems that GE tries to `.dump()` the CheckpointConfig ([Link to the code](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/data_context/util.py#L465)) and it perhaps failed to serialize the Spark DataFrame that you pass on the run with ` "runtime_parameters": {"batch_data": df}`.
**The error thrown prevents you to accomplish data validation with success.**

**Environment:**
The expectations suites and the checkpoints are developed using a Docker image which contains:
 - Ubuntu 20.04.2 LTS
 - Great Expectations 0.13.24
 - Python 3.6
 - Spark 2.4.7
 - Hadoop 2.8
 - Jupyter Notebook

**Additional context**
In order to enrich the issue I also attach the stack trace with the Error return, hope this can be helpful.
Stack trace export: [stack_trace_error.txt](https://github.com/great-expectations/great_expectations/files/6908414/stack_trace_error.txt)

**Comment by luizfgoncalves** [comment]
I'm currently having this same problem of `RecursionError` with v3. Building the expectation suite with a validator and a SparkDF works well, but I can't use a checkpoint to validade it.

Is there any workaround to validate it until its fixed?

**Comment by davideromano** [comment]
Hi, didn't find any workaround, yet.
When I opened the issue I used Great Expectations v0.13.24, but right now it is available the v0.13.28; which version did you use?

**Comment by luizfgoncalves** [comment]
I've used Great Expectations v0.13.27, and the problem still persists. I looked at the changelog of v0.13.28, but there is no mention of any fixes about this problem either

**Comment by davideromano** [comment]
Yes, the changelog doesn't mention anything about this issue, but I saw that the team just released a new official documentation related to API v3. I didn't read/used it yet, since I am still using API v2, but maybe inside it there is workaround or a suggestion related to `RuntimeDataConnector` and how to use a SparkDF as a validation object.
Did you check it?

**Comment by luizfgoncalves** [comment]
I'm using API v3, but didn't find any workaround it. The problem seems to be on the `SimpleCheckpoint` itself, because I can create an expectation suite based on my SparkDF with no issues. It only crashes when sending to validate.

Maybe there is a better way to build the validation parameters of the Checkpoint (batch_request and expectation_suite) to avoid it, but I couldn't find anything yet

**Comment by iancmoritz** [comment]
Any updates to this? On v0.13.28 and API v3 and haven't heard of any changes that will fix with Spark.

**Comment by InesFakh** [comment]
Hello,
I'm facing the same issue using a Checkpoint.
Validators work fine with spark dataframes but when it comes to running the validation using a checkpoint it fails.

great expectations  : 0.13.33 
API : V3
spark : 2.2.0.2.6.4.0-91
python : 3.6

the issue comes from using [deepcopy](https://github.com/great-expectations/great_expectations/blob/acbe0e5a8ee2b9f91673d3d535b5c47e6aa32bf5/great_expectations/data_context/types/base.py#L1935)

Thanks !

Edit : 
work-around to the issue : 
Since Spark dataframes are immutable, there is no need to deepcopy them. So, to fix this issue I have commented the deepcopy execution in [remove_keys_if_none](https://github.com/great-expectations/great_expectations/blob/acbe0e5a8ee2b9f91673d3d535b5c47e6aa32bf5/great_expectations/data_context/types/base.py#L1935)
I think commenting this line won't bother since I'll only be using spark dataframes.

**Comment by luizfgoncalves** [comment]
Nice workaround suggestion @InesFakh . I will try it on my end here.

Given that I use both pandas and Spark, maybe creating a data check to run the deepcopy only for pandas DF may work too.

EDIT:
It did not work for me. Maybe I'm configuring the checkpoint wrong, but it is still working for pandas.

I got another error, this time at `great_expectations/checkpoint/checkpoint.py` .

```
    148             if not template_name:
--> 149                 substituted_config = copy.deepcopy(config)
    150                 if any(runtime_kwargs.values()):
    151                     substituted_config.update(runtime_kwargs=runtime_kwargs)
```

`AttributeError: 'CheckpointConfig' object has no attribute '_get_object_id'`

**Comment by talagluck** [comment]
Hi, I believe the original issue has been resolved here, and the most recent issue is a duplicate of #3473, so I'm closing this for now.
