### ISSUE TITLE
Installation using conda

### ISSUE THREAD

**Issue by rpanai** [fivetran/great_expectations#3163]
In the section [Quick start](https://github.com/great-expectations/great_expectations/blob/develop/README.md#quick-start) on the `README.md` one could add the possibility to install via conda (see [link](https://anaconda.org/conda-forge/great-expectations)) via `conda install -c conda-forge great-expectations`

**Comment by talagluck** [comment]
Thanks for raising this @rpanai! If you are interested, this would make an excellent community contribution!
