### ISSUE TITLE
Integration of Great Expectations with Robot Framework

### ISSUE THREAD

**Issue by nehadahiya88** [fivetran/great_expectations#3164]
**Is your feature request related to a problem? Please describe.**
I want to use the Great Expectations with Robot Framework.

**Describe the solution you'd like**
Library compatible with robot framework

**Describe alternatives you've considered**
exploring

**Additional context**

**Comment by NathanFarmer** [comment]
Hi @nehadahiya88! Thanks for raising this idea. It isn't on our immediate roadmap, but if you would like to make a contribution and collaborate with the community, we would be happy to offer our guidance.
