### ISSUE TITLE
include_config parameter does not give expectation suite info when executed against Athena and CSV datasources

### ISSUE THREAD

**Issue by vaidehid1305** [fivetran/great_expectations#3166]
**Describe the bug**
I am executing following example expectations against a table in Athena:

- expect_column_max_to_be_between
- expect_column_values_to_not_be_null
- expect_column_values_to_be_in_set

For all these expectations, I added the parameter include_config = True, but still I do not see the expectation information in the result set.
Below is an example:

batch.expect_column_values_to_not_be_null("<column_name>", result_format = "SUMMARY", include_config = True)

Result:
{
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "element_count": 11137852,
    "unexpected_count": 1451826,
    "unexpected_percent": 13.035062775120373,
    "unexpected_percent_total": 13.035062775120373,
    "partial_unexpected_list": []
  },
  "success": false
}

Also tried executing same expectation with result_format = COMPLETE, still got the same results.

**To Reproduce**
1. Connect to Athena datasource
2. Execute any expectation with include_config = True
3. Check if you get expectation suite information in the result set

**Expected behavior**
As per the documentation here:
https://docs.greatexpectations.io/en/latest/reference/core_concepts/expectations/standard_arguments.html#include-config

I expect to see expectation type, column name, result_format information in the result set.
For example this is how the output should look like:

'exception_index_list': [0, 10, 11, 12, 13, 14],
    'exception_list': ['A', 'E', 'E', 'E', 'E', 'E'],
    'expectation_type': 'expect_column_values_to_be_in_set',
    'expectation_kwargs': {
        'column': 'my_var',
        'result_format': 'COMPLETE',
        'value_set': ['B', 'C', 'D', 'F', 'G', 'H']

**Environment (please complete the following information):**
 - Operating System: Mac OS
 - Great Expectations Version: 0.13.20

**Additional context**

**Comment by talagluck** [comment]
Thanks for raising this @vaidehid1305! Could you please confirm whether you are using the V2 BatchKwargs or V3 BatchRequest API?

**Comment by vaidehid1305** [comment]
Hi @talagluck thanks for getting back, I am using V2 (Batch Kwargs) API. Is this not compatible with include_config?

**Comment by talagluck** [comment]
Hi @vaidehid1305 - thanks for your reply! Yes, `include_config` is compatible with V2. 

In order to get the results, are you running expectations in a notebook? If so, I believe that this is not a bug, but has to do with the string representation of the output. If instead of just running 
`batch.expect_column_values_to_not_be_null("<column_name>", result_format = "SUMMARY", include_config = True)` 

and viewing the output, you were to print the output like so:

`print(batch.expect_column_values_to_not_be_null("<column_name>", result_format = "SUMMARY", include_config = True))` 

do you see the full expectation config?

**Comment by vaidehid1305** [comment]
Thanks @talagluck, with print included i do see the full expectation config.
Appreciate your help.
