### ISSUE TITLE
Proposal for adding strict typing to tests

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#317]
Right now, tests rely on automatic schema generation by sqlalchemy and spark. This is nontransparent, bad magic. As we move into checking typing in general, it will become completely untenable.

Instead, let's add a `schemas` k/v to our tests:

```
{
  "expectation_type": "expect_column_to_exist",
  "datasets": [{
    "data": {
      "c1": [4, 5, 6, 7],
      "c2": ["a", "b", "c", "d"],
      "c3": [null, null, null, null]
    },
    "schemas" : {
      "pandas" : {
        "c1" : "float", #I don't actually know the pandas dtypes. They might be different.
        "c2" : "string",
        "c3" : "int",
      },
      "sqlite" : {
        "c1" : "float",
        "c2" : "varchar(50)",
        "c3" : "int",
      },
      "spark_df" : {
        "c1" : "FloatType",
        "c2" : "StringType",
        "c3" : "IntegerType",
      },
    },
    "tests": [{
      ...
```

`schemas` are used to define types when instantiating datasets in in `test_utils.get_dataset`. They vary by database.

We will want to write a utility (one per execution context) to generate these upgraded test files. The utilities will probably be based on the same automatic schema generators we're using today. But we'll explicitly declare our types, instead of relying on nontransparent magic.

**Comment by jpcampb2** [comment]
@abegong looking at old issues...we hadn't talked about this in a long time. Interest in pursuing it?

**Comment by jcampbell** [comment]
(This is now available in the testing harness).
