### ISSUE TITLE
Automatic profiler errors on Postgres DB timestamp columns

### ISSUE THREAD

**Issue by mpalfi** [fivetran/great_expectations#3170]
**Describe the bug**
For a colum defined in Postgres as timestamp (cntrc_hdr_end_dt timestamp)
Value samples:
2017-07-01 00:00:00
2013-12-01 00:00:00
2015-10-01 00:00:00

When running the automatic profiler the following error is thrown:

~\AppData\Roaming\Python\Python37\site-packages\great_expectations\dataset\sqlalchemy_dataset.py in get_column_min(self, column, parse_strings_as_datetimes)
    764     def get_column_min(self, column, parse_strings_as_datetimes=False):
    765         if parse_strings_as_datetimes:
--> 766             raise NotImplementedError
    767         return convert_to_json_serializable(
    768             self.engine.execute(
NotImplementedError:

![image](https://user-images.githubusercontent.com/4368292/128078372-40299ac9-b68b-4fd5-bdb1-f73bbe4f7f96.png)

**To Reproduce**

**Expected behavior**
Expectations should be generated for the timestamp fields. 

**Environment (please complete the following information![image](https://user-images.githubusercontent.com/4368292/128078240-8749c2fd-1478-4159-baea-0a8a75b42de7.png):**
 - Operating System: Microsoft Windows [Version 10.0.18363.1679]
 - Great Expectations Version: 0.13.19 using V2 API

**Additional context**

**Comment by talagluck** [comment]
Hi @mpalfi - thank you for raising this issue! We are looking into this, and will be in touch over the next week or so to follow up.

**Comment by talagluck** [comment]
Hi @mpalfi - apologies for delays. I believe the issue here is that `parse_strings_as_datetimes` does not work for SQL Alchemy backends. As `parse_strings_as_datetimes` is a feature which we are planning to deprecate for all backends anyway, I'm going to close this issue for now, but please feel free to re-open if you have any new information.
