### ISSUE TITLE
Can't specify schema in expect_table_row_count_to_equal_other_table

### ISSUE THREAD

**Issue by armandduijn** [fivetran/great_expectations#3186]
**Describe the bug**
The expectations `expect_table_row_count_to_equal_other_table` can't find the other table I specify in the `other_table_name` parameter. I tried adding the schema name as part of the table name, but then SQLAlchemy wraps it in double quotes, causing my database (Redshift) to interpret it as an escaped table name.

**To Reproduce**
1. In a database, create a schema `my_schema` and, inside that schema, create tables `my_table_1` and `my_table_2`
2. Next, create or edit an existing Great Expectations test suite
3. Modify your batch to load the table `my_schema.my_table_1`
4. Add the expectation `batch.expect_table_row_count_to_equal_other_table(other_table_name='my_table_2')`

    The expectation will throw the following error:
    ```
    ProgrammingError: (psycopg2.errors.UndefinedTable) relation "my_table_2" does not exist
    
    [SQL: SELECT count(*) AS count_1 
    FROM my_table_2]
    (Background on this error at: http://sqlalche.me/e/14/f405)
    ```  

5. Change the `other_table_name` to include the schema name: `my_schema.my_table_2`

    The expectation will throw the following error:
  
    ```
    ProgrammingError: (psycopg2.errors.UndefinedTable) relation "my_schema.my_table_2" does not exist
    
    [SQL: SELECT count(*) AS count_1 
    FROM "my_schema.my_table_2"]
    (Background on this error at: http://sqlalche.me/e/14/f405)
    ```

**Expected behavior**
I expect the expectation to be able to compare `my_table_1` with `my_table_2` in schema `my_schema`. Currently, the expectation doesn't allow me to specify the schema of the other table.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.13.9

**Additional context**
Link to documentation: https://docs.greatexpectations.io/en/0.13.24/autoapi/great_expectations/expectations/core/expect_table_row_count_to_equal_other_table/index.html

**Comment by talagluck** [comment]
Thanks for raising this issue @armandduijn! I'm not sure whether this is currently possible, but will check back in with the team and be in touch over the next few days.

**Comment by armandduijn** [comment]
@talagluck Is there any update on whether it's possible?

**Comment by Hugoberry** [comment]
I went with the workaround of creating a `dbo` view of the other table and referencing it without the schema in my expectation.

**Comment by manuelhc621** [comment]
Not an optimal solution, but you can set the search path as an argument when defining the data source config:

```
    datasources={
            "warehouse": DatasourceConfig(
                class_name="Datasource",
                execution_engine={
                    "class_name": "SqlAlchemyExecutionEngine",
                    "credentials": {
                        "drivername": "postgresql",
                        "host": db_conn.host,
                        "port": db_conn.port,
                        "username": db_conn.login,
                        "password": db_conn.password,
                        "database": self.database,
                        "connect_args": {'options': '-csearch_path=schema1,schema2,schema3'}
                    }
                },
                data_connectors={
                    "query_runtime_connector": {
                        "class_name": "RuntimeDataConnector",
                        "batch_identifiers": ["default_identifier_name"],
                    }
                }
            )
        }

```

A couple of warnings here:
- Not sure if it will work with other databases than postgres
- Watch-out for table names collisions

**Comment by molliemarie** [comment]
Hi @armandduijn. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core  quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example). 

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for more updates on GX Core. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
