### ISSUE TITLE
glossary.rst is out of date.

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#319]
it's very sad.

**Comment by ccnobbli** [comment]
I'm on it

**Comment by abegong** [comment]
🙇

**Comment by ccnobbli** [comment]
I actually had trouble with the very last function `expect_file_hash_to_equal`, I couldn't link the doc reference to the declaration in the source code :(

**Comment by jpcampb2** [comment]
Closing this issue based on recent PR...yay!
