### ISSUE TITLE
Feature to disable CTE use, required for compatibility with MySQL < 8.0

### ISSUE THREAD

**Issue by nrawling** [fivetran/great_expectations#3199]
**Is your feature request related to a problem? Please describe.**
When running scaffold on a MySQL 5.6 database, enable any columns and you will receive an error similar to this one, since MySQL versions prior to MySQL 8.0 do not support CTEs:

```
An SQL syntax Exception occurred.ProgrammingError: "(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 't AS \n(SELECT is_active_s, CAST(percent_rank() OVER (ORDER BY is_active_s ASC) A' at line 1")
[SQL: WITH t AS 
(SELECT is_active_s, CAST(percent_rank() OVER (ORDER BY is_active_s ASC) AS DECIMAL(18, 15)) AS p 
FROM naviance_dev.student ORDER BY p ASC)
 SELECT DISTINCT first_value(is_active_s) OVER (ORDER BY CASE WHEN (t.p <= CAST(%(param_1)s AS DECIMAL(18, 15))) THEN t.p END DESC) AS q_0, first_value(is_active_s) OVER (ORDER BY CASE WHEN (t.p <= CAST(%(param_2)s AS DECIMAL(18, 15))) THEN t.p END DESC) AS q_1, first_value(is_active_s) OVER (ORDER BY CASE WHEN (t.p <= CAST(%(param_3)s AS DECIMAL(18, 15))) THEN t.p END DESC) AS q_2, first_value(is_active_s) OVER (ORDER BY CASE WHEN (t.p <= CAST(%(param_4)s AS DECIMAL(18, 15))) THEN t.p END DESC) AS q_3, first_value(is_active_s) OVER (ORDER BY CASE WHEN (t.p <= CAST(%(param_5)s AS DECIMAL(18, 15))) THEN t.p END DESC) AS q_4 
FROM t ORDER BY t.p DESC]
[parameters: {'param_1': 0.05, 'param_2': 0.25, 'param_3': 0.5, 'param_4': 0.75, 'param_5': 0.95}]
(Background on this error at: https://sqlalche.me/e/14/f405)".  Traceback: "Traceback (most recent call last):
  File "/Users/nathan.rawling/.pyenv/versions/3.9.6/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
```

Notably, AWS Aurora does not support MySQL 8.0 compatibility yet, so many potential Great Expectations users will be affected by this limitation.

**Describe the solution you'd like**
An optional flag to disable CTE use for scaffolding, so that Great Expectations can be used on RDBMS systems like MySQL 5.6/5.7 which do not support this functionality. Perhaps temporary tables could be used instead.

Ideally, this would become the default behavior on systems that doesn't support CTEs.

**Describe alternatives you've considered**
CTEs are a useful and widely supported mechanism for organizing queries, but he scaffolding could be rewritten not to require them at all. The advantage of this approach would be that it would minimize the number of code pathways (to use CTE or not) which require maintenance. However, it seems reasonable to use CTEs for databases that support it. Eventually MySQL 5.6/5.7 will die out and this extra code can be retired.

**Additional context**
I was unable to find current numbers on MySQL 8.0 adoption, but since AWS Aurora doesn't support version 8.0 yet, I have to assume that many potential Great Expectations users are going to struggle with this problem.

**Comment by talagluck** [comment]
Thank you for submitting this issue, @nrawling ! We will review internally and be in touch in the next week or so.

**Comment by nrawling** [comment]
I know you have all been busy rolling out awesome new features, but it would be great to get an update on this issue. Thank you!

**Comment by talagluck** [comment]
Thanks for the follow-up, @nrawling! We have discussed some possibilities internally, and hope to do some further investigation in the next few days.

**Comment by kenwade4** [comment]
https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-aurora-mysql-8-0/

If you are still having this issue, see if you can update your Aurora instance

**Comment by jiaxiang521** [comment]
I have encountered a similar situation. How to solve it if I do not upgrade mysql
