### ISSUE TITLE
result_format argument does not appear to be working properly in V3

### ISSUE THREAD

**Issue by talagluck** [fivetran/great_expectations#3225]
**Describe the bug**
The `result_format` argument does not appear to work properly in V3:
1. When setting it with `validator.set_default_expectation_argument("result_format", "BOOLEAN_ONLY")`, it appears to set it at the `Validator` level, but this does not propagate when created expectations with `validator.expect_...`

2. When creating an `ExpectationConfiguration` with `result_format` as an argument e.g. `expect_column_values_to_not_be_null("column_name", result_format="BOOLEAN_ONLY"). In this case, there are three problems:
  - The immediate return from the interactive validation while creating the expectation in a notebook is not BOOLEAN_ONLY - it doesn't include things like `unexpected_count`, but it returns more than a simple boolean.
  - When calling `validator.validate()`, `result_format` appears in the `kwargs` of the `expectation_configuration`, but does not actually apply to the validation result.
  - When saving the `ExpectationSuite`, `result_format` does not appear to be saved in the json file.

**To Reproduce**
1. Create a new Suite, and try to set the `result_format` when creating a new `ExpectationConfiguration` from a `Validator`. Then observe the above.

**Expected behavior**
I expect `result_format` to work as [detailed in the docs](https://legacy.docs.greatexpectations.io/en/latest/reference/core_concepts/expectations/result_format.html?highlight=result_format).

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.26

**Comment by milosz-dm** [comment]
I use 0.13.34 and it is worth to mention that the following works as expected:
`validator.expect_column_values_to_be_between(column="my_column", max_value=0,strict_max=False,result_format={"result_format": "BOOLEAN_ONLY"})`
However, it does not work properly when I use expectaion suite from JSON, example:
```
{
    "data_asset_type": null,
    "expectation_suite_name": "x_tmp_test",
    "expectations": [
        {
            "expectation_type": "expect_column_values_to_be_between",
            "kwargs": {
                "column": "my_column",
                "max_value": 0,
                "strict_max": false,
                "result_format": {
                    "result_format": "BOOLEAN_ONLY"
                }
            }
        }
    ],
    "ge_cloud_id": null,
    "meta": {
        "great_expectations_version": "0.13.34"
    }
}
```

**Comment by talagluck** [comment]
Hi @milosz-dm - thanks for chiming in here! This issue was actually resolved by #3364. 

I understand the confusion with what you have raised. This is not a bug, but rather is an expected change that comes with the way we are handling ExpectationValidationResults in V3. The essentials of the result are the same — the success boolean flag is returned, and, while the results key is still present, its dictionary value is empty.  Other metadata is also present as part of the new API, but it can be safely ignored while in the BOOLEAN_ONLY mode.  Hence, the output is equivalent to the one in the legacy documentation.  We are in the process of updating our documentation to reflect this as  part of the V2 to V3 API transition.

I'm going to close this issue for now, but please let us know if you have any further questions regarding this.

**Comment by milosz-dm** [comment]
@talagluck - Why the issue is closed? Is it OK that expectations loaded from JSON with the `"result_format": {"result_format":"BOOLEAN_ONLY"}` logs the wrong values?

**Comment by talagluck** [comment]
Hi @milosz-dm - apologies, maybe I misunderstood your question. What are the wrong values logged?

**Comment by milosz-dm** [comment]
Let's go through an example. IMO it is not valid that I have different results depends on whether I use `ge_validator.expect_column_values_to_be_between` or `ge_validator.validate()`.  After going through the example I think that is the main issue. To be clear - there is no "partial_unexpected_list" result in point 4 which is OK IMO.

1. Create expectation suite x_tmp_test using the following JSON:
`{
    "data_asset_type": null,
    "expectation_suite_name": "x_tmp_test",
    "expectations": [
        {
            "expectation_type": "expect_column_values_to_be_between",
            "kwargs": {
                "column": "a",
                "max_value": 0,
                "strict_max": false,
                "result_format": {
                    "result_format": "BOOLEAN_ONLY"
                }
            }
        }
    ],
    "ge_cloud_id": null,
    "meta": {
        "great_expectations_version": "0.13.35"
    }
}`
2. Add the following data asset in great_expectation.yaml:
`datasources:
  pandas_datasource:
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: PandasExecutionEngine
    module_name: great_expectations.datasource
    class_name: Datasource
    data_connectors:
      runtime_data_connector:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - pipeline_step
          - job_id`
3. Run the following commands in python:
`import pandas as pd
import numpy as np
from great_expectations import DataContext
from great_expectations.core import ExpectationSuite
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.validator.validator import Validator
pandas_df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=["a", "b", "c"])
batch_identifiers: dict = {"pipeline_step": None, "job_id": None}
batch_request: dict = {
    "datasource_name": "pandas_datasource",
    "data_connector_name": "runtime_data_connector",
    "data_asset_name": "not_relevant_for_pandas_datasource",
    "runtime_parameters": {"batch_data": pandas_df},
    "batch_identifiers": batch_identifiers,
}
runtime_batch_request: RuntimeBatchRequest = RuntimeBatchRequest(**batch_request)
ge_context: DataContext = DataContext(context_root_dir="ProvideYourPath")
suite: ExpectationSuite = ge_context.get_expectation_suite("x_tmp_test")
ge_validator: Validator = ge_context.get_validator(
    batch_request=runtime_batch_request, expectation_suite=suite
)
ge_validator.validate()`

The output is:
`{
  "results": [
    {
      "success": false,
      "expectation_config": {
        "expectation_type": "expect_column_values_to_be_between",
        "meta": {},
        "kwargs": {
          "column": "a",
          "max_value": 0,
          "strict_max": false,
          "result_format": {
            "result_format": "BOOLEAN_ONLY"
          },
          "batch_id": "54857ec4ad5ebccd81add38b256436f8"
        }
      },
      "meta": {},
      "result": {
        "element_count": 3,
        "unexpected_count": 3,
        "unexpected_percent": 100.0,
        "partial_unexpected_list": [
          1,
          4,
          7
        ],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 100.0,
        "unexpected_percent_nonmissing": 100.0
      },
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "evaluation_parameters": {},
  "success": false,
  "meta": {
    "great_expectations_version": "0.13.35",
    "expectation_suite_name": "x_tmp_test",
    "run_id": {
      "run_name": null,
      "run_time": "2021-10-07T05:06:31.328761+00:00"
    },
    "batch_spec": {
      "data_asset_name": "not_relevant_for_pandas_datasource",
      "batch_data": "PandasDataFrame"
    },
    "batch_markers": {
      "ge_load_time": "20211007T050621.942938Z",
      "pandas_data_fingerprint": "9762ced20d27292712e6a2065b6d6226"
    },
    "active_batch_definition": {
      "datasource_name": "pandas_datasource",
      "data_connector_name": "runtime_data_connector",
      "data_asset_name": "not_relevant_for_pandas_datasource",
      "batch_identifiers": {
        "pipeline_step": null,
        "job_id": null
      }
    },
    "validation_time": "20211007T050631.328645Z"
  },
  "statistics": {
    "evaluated_expectations": 1,
    "successful_expectations": 0,
    "unsuccessful_expectations": 1,
    "success_percent": 0.0
  }
}`
4. Run additional python command
`ge_validator.expect_column_values_to_be_between(column="b", max_value=0,strict_max=False,result_format={"result_format": "BOOLEAN_ONLY"})`
Output is:
`{
  "success": false,
  "expectation_config": {
    "expectation_type": "expect_column_values_to_be_between",
    "meta": {},
    "kwargs": {
      "column": "b",
      "max_value": 0,
      "strict_max": false,
      "result_format": {
        "result_format": "BOOLEAN_ONLY"
      },
      "batch_id": "54857ec4ad5ebccd81add38b256436f8"
    }
  },
  "meta": {},
  "result": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}`
5. Run additional python command
`ge_validator.validate()`
Output is:
`{
  "results": [
    {
      "success": false,
      "expectation_config": {
        "expectation_type": "expect_column_values_to_be_between",
        "meta": {},
        "kwargs": {
          "column": "a",
          "max_value": 0,
          "strict_max": false,
          "result_format": {
            "result_format": "BOOLEAN_ONLY"
          },
          "batch_id": "54857ec4ad5ebccd81add38b256436f8"
        }
      },
      "meta": {},
      "result": {
        "element_count": 3,
        "unexpected_count": 3,
        "unexpected_percent": 100.0,
        "partial_unexpected_list": [
          1,
          4,
          7
        ],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 100.0,
        "unexpected_percent_nonmissing": 100.0
      },
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "expectation_type": "expect_column_values_to_be_between",
        "meta": {},
        "kwargs": {
          "column": "b",
          "max_value": 0,
          "strict_max": false,
          "result_format": {
            "result_format": "BOOLEAN_ONLY"
          },
          "batch_id": "54857ec4ad5ebccd81add38b256436f8"
        }
      },
      "meta": {},
      "result": {
        "element_count": 3,
        "unexpected_count": 3,
        "unexpected_percent": 100.0,
        "partial_unexpected_list": [
          2,
          5,
          8
        ],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 100.0,
        "unexpected_percent_nonmissing": 100.0
      },
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "evaluation_parameters": {},
  "success": false,
  "meta": {
    "great_expectations_version": "0.13.35",
    "expectation_suite_name": "x_tmp_test",
    "run_id": {
      "run_name": null,
      "run_time": "2021-10-07T05:08:26.926936+00:00"
    },
    "batch_spec": {
      "data_asset_name": "not_relevant_for_pandas_datasource",
      "batch_data": "PandasDataFrame"
    },
    "batch_markers": {
      "ge_load_time": "20211007T050621.942938Z",
      "pandas_data_fingerprint": "9762ced20d27292712e6a2065b6d6226"
    },
    "active_batch_definition": {
      "datasource_name": "pandas_datasource",
      "data_connector_name": "runtime_data_connector",
      "data_asset_name": "not_relevant_for_pandas_datasource",
      "batch_identifiers": {
        "pipeline_step": null,
        "job_id": null
      }
    },
    "validation_time": "20211007T050826.926734Z"
  },
  "statistics": {
    "evaluated_expectations": 2,
    "successful_expectations": 0,
    "unsuccessful_expectations": 2,
    "success_percent": 0.0
  }
}`

**Comment by milosz-dm** [comment]
@talagluck - have you seen my last comment?

**Comment by talagluck** [comment]
Hi @milosz-dm - thank you for your patience, and your thorough reply. Based on this, I agree that there appears to be a bug, and I believe this is due to the fact that we have changed the way result_format is specified between V2 and V3, which is why I was not able to reproduce this at first. I am out for the rest of today through Monday, but will prioritize this when I have returned on Tuesday and will update you with our progress.

**Comment by abekfenn** [comment]
Hi all,
I'm seeing a related - possibly different root cause - bug where results does not include `unexpected_index_list` despite setting result_format to "COMPLETE". I have an example attached below that reproduces the issue.

After diving into the code, my hunch is that this is something to do with running this using  a RuntimeBatchRequest.
It seems that when using the below implementation - passing in a dataframe and expectations directly in the code - I don't see unexpected_index_list returned from any of the expectation methods used.
However, when I run this using the same expectation suite via the command line or a jupyter notebook, I do see the unexpected_index_list in the results..
What's going on here? How can I get the unexpected_index_list to be returned for these methods?

P.S. I'm happy to help try to solve this issue if someone can point me in the right direction of where to look.

Example portable code below:
```import great_expectations as ge
import great_expectations.jupyter_ux
from great_expectations.core.batch import RuntimeBatchRequest
import numpy as np
import pandas as pd
import json
from ruamel import yaml


df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))

context = ge.get_context()

datasource_config = {
                        "name": "test",
                        "class_name": "Datasource",
                        "dataset": "pandas_dataset",
                        "module_name": "great_expectations.datasource",
                        "execution_engine": {
                            "module_name": "great_expectations.execution_engine",
                            "class_name": "PandasExecutionEngine",
                        },
                        "data_connectors": {
                            "default_runtime_data_connector_name": {
                                "class_name": "RuntimeDataConnector",
                                "module_name": "great_expectations.datasource.data_connector",
                                "batch_identifiers": ["default_identifier_name"],
                            },
                        },
                    }
context.test_yaml_config(yaml.dump(datasource_config))
context.add_datasource(**datasource_config)

batch_request = RuntimeBatchRequest(
    datasource_name="test",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="test",  # This can be anything that identifies this data_asset for you
    runtime_parameters={"batch_data": df},  # df is your dataframe
    batch_identifiers={"default_identifier_name": "default_identifier"},
)
context.create_expectation_suite(
    expectation_suite_name="test", overwrite_existing=True
)
validator = context.get_validator(
    batch_request=batch_request, expectation_suite_name="test"
)

validator.expect_table_row_count_to_be_between(max_value=250, min_value=10)

validator.expect_table_column_count_to_equal(value=4)

validator.expect_table_columns_to_match_ordered_list(
    column_list=[
        "A",
        "B",
        "C",
        "D",
    ]
)

validator.expect_column_values_to_not_be_null(column="A",
    result_format='COMPLETE')

validator.expect_column_values_to_be_null(column="A",
    result_format='COMPLETE')

validator.expect_column_values_to_be_in_set(
    column="A",
    value_set=["A", "B", "C", "D", "E", "F"],
    result_format='COMPLETE'
)

results = validator.validate()

with open('validation_results.json', 'w') as f:
    f.write(str(results))
```
In other words, this great_expectation.yaml datasource works as expected
```
    batch_kwargs_generators:
      subdir_reader:
        class_name: SubdirReaderBatchKwargsGenerator
        base_directory: /client
    class_name: PandasDatasource
    data_asset_type:
      class_name: PandasDataset
      module_name: great_expectations.dataset
    module_name: great_expectations.datasource
```
whereas this one does not (doesn't return unexpected_index_list)
```

    execution_engine:
      class_name: PandasExecutionEngine
      module_name: great_expectations.execution_engine
    class_name: Datasource
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
    module_name: great_expectations.datasource
```
This seems to be due to the fact that the first yaml results in [pandas_dataset](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/dataset/pandas_dataset.py) being used (which makes sense) but the second causes [pandas_execution_engine](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/execution_engine/pandas_execution_engine.py) to be used.
I can't figure out how to configure the yaml to use the data_asset_type of the first config without producing new issues.

Relevant slack thread:
https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1635294992066800

Environment (please complete the following information):

Operating System: MacOS
Great Expectations Version: 0.13.40

**Comment by bhcastleton** [comment]
Thanks @abekfenn for adding that. Very helpful!

**Comment by abekfenn** [comment]
@talagluck thoughts on the above issue being related to the failure of the result_format arg to propagate or an issue of datasource configuration/handling? Again, would be more than happy to look into solving this if I could be pointed in the right direction.

**Comment by talagluck** [comment]
Hi @abekfenn - thanks so much for the follow-up! We believe that this is an issue of functionality that has not yet been fully updated for the V3 API. As you demonstrate in your example, this works with the V2 Batch Kwargs API (`PandasDataset` and `PandasDatasource`), but does not yet work with the V3 Batch Request API (`PandasExecutionEngine`). It is not possible to mix and match from these APIs, and that will lead to issues.

Ordinarily, we would really appreciate a contribution here! However, I know that in this case, the issue is quite deep, and will be worked on internally in an upcoming sprint. However, if you are interested in seeing where some of this code lives, and taking a stab at it, I believe it is a combination of the `ExpectationConfiguration` and `Validator` classes in V3. Again, thank you so much for your offer, and please don't hesitate to reach out if you have additional questions.

**Comment by abekfenn** [comment]
Thank you for the thorough response @talagluck. Would the recommended interim solution be to use the V2 API then?

I've leveraged the documentation for [How to instantiate a Data Context without a yml file](https://legacy.docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_data_contexts/how_to_instantiate_a_data_context_without_a_yml_file.html#how-to-guides-configuring-data-contexts-how-to-instantiate-a-data-context-without-a-yml-file) & [How to load a Pandas DataFrame as a Batch](https://legacy.docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_batches/how_to_load_a_pandas_dataframe_as_a_batch.html#how-to-load-a-pandas-dataframe-as-a-batch) to do this using the V2 API. I've documented this below using the same example as above in case someone else runs across this issue with a similar need.

Let me know if you all are still accepting updates to V2 documentation and I would be happy to update the examples there to include how to set this up for an in-memory dataframe without a yml file.

I'll take a look at the aforementioned classes, but definitely looking forward to being able to do this in V3!

```
import great_expectations as ge
from great_expectations.data_context.types.base import DataContextConfig, DatasourceConfig, FilesystemStoreBackendDefaults
from great_expectations.data_context import BaseDataContext
import numpy as np
import pandas as pd
import json
import os

df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
abs_path = os.getcwd() + '/great_expectations'
domain_name = 'test'

data_context_config = DataContextConfig(
    datasources={
        "my_pandas_datasource": DatasourceConfig(
            class_name="PandasDatasource",
        )
    },
    store_backend_defaults=FilesystemStoreBackendDefaults(root_directory=abs_path),
)

context = BaseDataContext(project_config=data_context_config)

suite = context.create_expectation_suite(domain_name, overwrite_existing=True)

batch_kwargs = {
    "datasource": 'my_pandas_datasource',
    "dataset": df,
    "data_asset_name": domain_name,
}

batch = context.get_batch(batch_kwargs, "test")

print(batch.head())

batch.expect_table_row_count_to_be_between(max_value=250, min_value=10)

batch.expect_table_column_count_to_equal(value=4)

batch.expect_table_columns_to_match_ordered_list(
    column_list=[
        "A",
        "B",
        "C",
        "D",
    ]
)

batch.expect_column_values_to_not_be_null(column="A",
    result_format='COMPLETE')

batch.expect_column_values_to_be_null(column="A",
    result_format='COMPLETE')

batch.expect_column_values_to_be_in_set(
    column="A",
    value_set=["A", "B", "C", "D", "E", "F"],
    result_format='COMPLETE'
)

results = batch.validate()

with open('validation_results.json', 'w') as f:
    f.write(str(results))
```

**Comment by talagluck** [comment]
Great news, @milosz-dm and @abekfenn! This was just merged into `develop` this morning, and should be released next week. This should work as expected at this stage, so please do chime in if that turns out to not be the case.

@abekfenn, we generally recommend that users work from the V3 API, as we will stop full support of the V2 API in the not-too-distant future. That said, if you would like to make contribution to our legacy docs, we will still take the time to review it.

Thanks so much for bearing with us through this!
