### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by Haze211** [fivetran/great_expectations#3229]
Thanks for the great project!
I have found some broken links on new website with docs.

Broken link: [Expectation Glossar](https://docs.greatexpectations.io/docs/reference/expectations/)
Another broken link: [supported Expectations](https://docs.greatexpectations.io/docs/reference/expectations/expectations/implemented_expectations) (in this case this link works just fine https://docs.greatexpectations.io/docs/reference/expectations/implemented_expectations

**Comment by petermoyer** [comment]
Thank you for calling this to our attention. It will be fixed quickly
GDOC-216 has been opened for internal tracking

**Comment by petermoyer** [comment]
Should be updated soon
