### ISSUE TITLE
TypeError when getting latest validation result from DataContext

### ISSUE THREAD

**Issue by zachzIAM** [fivetran/great_expectations#3237]
**Describe the bug**
I am trying to get the latest validation result from a `DataContext` using the `get_validation_result` method but am getting a

```
Traceback (most recent call last):
  File "C:\workspace\ge_tutorials\get_validation_result_error.py", line 10, in <module>
    latest_validation_result = data_context.get_validation_result("demo")
  File "C:\workspace\ge_tutorials\venv\lib\site-packages\great_expectations\data_context\data_context.py", line 2354, in get_validation_result
    filtered_key_list = sorted(filtered_key_list, key=lambda x: x.run_id)
TypeError: '<' not supported between instances of 'RunIdentifier' and 'RunIdentifier'
```

**To Reproduce**
1. [Clone `ge_tutorials`](https://docs.greatexpectations.io/docs/tutorials/getting_started/initialize_a_data_context#set-up-your-machine-for-the-tutorial) as per documentation tutorial
2. Run the following code at project root:
```python
import great_expectations as ge

expectations_root = "./getting_started_tutorial_final_v3_api/great_expectations"

data_context = ge.DataContext(context_root_dir=expectations_root)

# need multiple runs to compare
for _ in range(2):
    data_context.run_checkpoint(
        checkpoint_name="my_checkpoint"
    )
latest_validation_result = data_context.get_validation_result("demo")
print(latest_validation_result)
```

**Expected behavior**
When only the `expectation_suite_name` argument is provided the the `get_validation_result` should proceed to compare all of the validation results and return the latest, e.g. by comparing the timestamp-named subfolders alphabetically.

**Environment (please complete the following information):**
 - Operating System: Windows 10
 - Great Expectations Version: 0.13.26

**Additional context**
The problem boils down to a missing comparison dunder method implementation for the `RunIdentifier` class (or its super class). Currently only the `__eq__` / `__neq__` methods are implemented, at least one more, e.g. `__gt__` or `__lt__`, is need for the `sorted` operation [here](https://github.com/great-expectations/great_expectations/blob/d51afdd1af1ec1627cb5ee541847759255ce3bf1/great_expectations/data_context/data_context.py#L2274).

**Comment by talagluck** [comment]
Thanks for submitting this issue, @zachzIAM ! It sounds like you've done a good chunk of work in determining where the issue lies. Would you be interested in submitting a contribution for this? I'm happy to offer guidance or support wherever possible.

**Comment by zachzIAM** [comment]
Hi @talagluck, would do so happily. I've followed the contribution guide and have my work [here](https://github.com/zachzIAM/great_expectations/tree/bugfix/fix-error-getting-validation-result). 

Would love any prelim comments you might have. One thing that I was not sure about was where to include a test for this specific behaviour so I added a [new test case](https://github.com/zachzIAM/great_expectations/blob/dbdd616ba9355ead8ce79d11608b4387fa67f1b4/tests/data_context/test_data_context.py#L393-L409).

Alternatively let me know if I should just open the PR now and open up the conversation there.

**Comment by talagluck** [comment]
Hi @zachzIAM - thanks for this! I think the best way to continue the conversation would be to open the PR, and I can add feedback there. At that time I can take a look to see about the right place for testing, but adding a new test case is totally fine (and thank you for thinking about testing!)

Just a heads-up, I'll be out for the next few days, but I'm looking forward to taking a look once I'm back!

EDIT: Never mind, I see you just opened the issue this morning - thank you! I'll take a look later this week.
