### ISSUE TITLE
add expectation metadata to result format

### ISSUE THREAD

**Issue by majidaldo** [fivetran/great_expectations#3241]
[result format](https://docs.greatexpectations.io/docs/reference/expectations/result_format) does not include what I consider to be basic meta data: a description of the expectation: name/type, arguments. This is more annoying when going through the results of an expectation suite.

**Describe the solution you'd like**
Put this metadata under meta or expectation_info.

**Describe alternatives you've considered**
What you have to do is match the order of the expectation suite results to the expectation suite.

**Comment by talagluck** [comment]
Hi @majidaldo - thank you for submitting this issue! I agree that what you are describing is not what we would expect. Would you be able to add some more context here? What version of Great Expectations are you using? Are you using the V2 Batch Kwargs or V3 Batch Request API? Could you provide a screenshot of how Data Docs and/or your expectation json file looks?

**Comment by talagluck** [comment]
Closing this for now, but please feel free to re-open if you have more information.
