### ISSUE TITLE
Consistent parameter naming: values_set/value_set

### ISSUE THREAD

**Issue by roblim** [fivetran/great_expectations#326]
`expect_column_values_to_be_in_set` and `expect_column_values_to_not_be_in_set` use `values_set` and `expect_column_most_common_value_to_be_in_set` uses `value_set`

Should be one or the other to prevent errors.

**Comment by njsmith8** [comment]
Unless someone else has a strong opinion otherwise, 'value_set' feels more natural to me and seems to be the more common usage.

**Comment by ccnobbli** [comment]
I agree with @njsmith8. It also means that much less typing! 

Good catch on this inconsistency, @roblim

**Comment by jpcampb2** [comment]
Thanks @njsmith8 @roblim @ccnobbli
