### ISSUE TITLE
Default python JSON encoder shortcomings

### ISSUE THREAD

**Issue by AntonBiryukovUofC** [fivetran/great_expectations#3299]
**Is your feature request related to a problem? Please describe.**

If `BatchDefinition` or `BatchRequest` object receive a `datetime` object as an identifier, the JSON serialization fails, and the object is not usable downstream anymore. In fact, wherever there is another use of `datetime` in an object that is further to be serialized in JSON, GE's code will fail with:
```
TypeError: Object of type datetime is not JSON serializable
```

The problem is that standard python json library does not know how to encode `datetime`. The same problem will happen if `numpy` arrays were to be used either as parameters to expectations, or batch identifiers.

**Describe the solution you'd like**

One of the solutions is to use `pydantic` library-based encoder, that has extended json serialization to a lot of common Python library types.

**Describe alternatives you've considered**

Alternative solutions could be `orjson` or anything suggested by `pydantic` as a custom encoder.
Or custom json serialization methods to extend GE's default json encoder and avoid dependency bloat.

**Comment by talagluck** [comment]
Hi @AntonBiryukovUofC - thanks for raising this issue! I'll be bringing this to our internal triage meeting, and will be in touch in the next few days.

**Comment by talagluck** [comment]
Hi @AntonBiryukovUofC - I wanted to follow up. This is a bug, as `BatchDefinition` and `BatchRequest` should be running through our own internal `convert_to_json_serializable` utility function, which would correctly serialize `datetime`. Thank you again for pointing this out! Please let me know if this is something which you might be interested in contributing, and I'm happy to offer any guidance you may need.

**Comment by NathanFarmer** [comment]
Hi @AntonBiryukovUofC I am looking into a fix for this and I will let you know when it is resolved.

**Comment by NathanFarmer** [comment]
Hi @AntonBiryukovUofC the bug fix above was put in for this issue. It has been merged into `develop` and will be part of GE release 0.13.33.
