### ISSUE TITLE
Missing citation information

### ISSUE THREAD

**Issue by madelonhulsebos** [fivetran/great_expectations#3322]
I would like to be able to cite the Great Expectations software in my research, as intended by its authors.

### Desired solution

Steps to create a citation file: [citation file format site](https://citation-file-format.github.io/). 

The Great Expectations repository would then provide the information to cite it, e.g. in APA and BibTex format, as below.

![Screenshot 2021-08-12 at 09 36 04](https://user-images.githubusercontent.com/15101953/129156883-51a129c3-950a-47f0-bc42-3f601d589a22.png)

### Alternatives

Without this file I would cite the main website without authors etc., which might be preferred by the creators.

**Comment by talagluck** [comment]
Hi @madelonhulsebos - thank you for raising this issue! This is super interesting - we will discuss internally and be in touch.

**Comment by austiezr** [comment]
@madelonhulsebos Closing this out as resolved by #3697; thank you so much for reaching out about this!
