### ISSUE TITLE
Great expectations checkpoint creation takes too long

### ISSUE THREAD

**Issue by aseembansal-gogo** [fivetran/great_expectations#3327]
**Is your feature request related to a problem? Please describe.**
Same as https://github.com/great-expectations/great_expectations/issues/1670 but for checkpoints. 

I have datasource athena configured. Running
```
great_expectations --v3-api checkpoint CHECKPOINT_NAME
```
causes it to send queries for every database in athena. Then the jupyter notebook opens which has the following
```
from ruamel.yaml import YAML
import great_expectations as ge
from pprint import pprint

yaml = YAML()
context = ge.get_context()
```
This again causes queries to be sent for every database in athena.  

**Describe the solution you'd like**
Do not make excessive queries for getting schema

**Describe alternatives you've considered**
I tried using specific database name in athena as mentioned here https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/database/athena/ but it is still sending queries for every single database

**Additional context**
This query is sent for every database 2 times

```sql
SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'DATABASE_NAME'
```

**Comment by talagluck** [comment]
Thanks for raising this issue @aseembansal-gogo! This appears to be a bug. We will dive in to determine what the exact problem is, and respond in the next few days.

**Comment by NathanFarmer** [comment]
Hi @aseembansal-gogo! Have you tried using the `ConfiguredAssetDataConnector` instead of the `InferredAssetDataConnector`? This may result in a significant performance improvement.

**Comment by aseembansal-gogo** [comment]
`ConfiguredAssetDataConnector ` decreased the time taken significantly. Thanks @NathanFarmer

**Comment by NathanFarmer** [comment]
I am closing this for now. Additional documentation and communication around `DataConnectors` is forthcoming.
