### ISSUE TITLE
Two great_expectations command line tool suggestions

### ISSUE THREAD

**Issue by smontanaro** [fivetran/great_expectations#334]
By default, the great_expectations tool spits out the entire set of checks, and when you ask it for help, you get precious little output. Looking at the source, I noticed it takes a sizable set of command line arguments. (Hmmm... trying to pass --only_return_failures fails.) I don't know what argh is, but it should be tweaked to display more info when the user asks for help. It looks like the command line arg processing in general needs a bit of touch-up.

Perhaps more important though, is that the exit status of the tool doesn't reflect the overall result of the checks. It always exits with zero. Maybe it should exit with the number of failed checks. I think that would make it more useful when run from job schedulers which can be configured to alert in various ways if a job fails.

**Comment by jpcampb2** [comment]
These are great suggestions, and ironically I just refactored the CLI in the past couple of days without thinking about either of them, but I've just created a small patch that I think addresses these issues.

First, I've improved the help messages, so they now look like the following:

```
$ great_expectations validate -h
usage: great_expectations validate [-h]
                                   [--evaluation_parameters EVALUATION_PARAMETERS]
                                   [--result_format RESULT_FORMAT]
                                   [--catch_exceptions CATCH_EXCEPTIONS]
                                   [--only_return_failures ONLY_RETURN_FAILURES]
                                   [--custom_dataset_module CUSTOM_DATASET_MODULE]
                                   [--custom_dataset_class CUSTOM_DATASET_CLASS]
                                   dataset expectations_config_file

Validate expectations for your dataset.

positional arguments:
  dataset
  expectations_config_file

optional arguments:
  -h, --help            show this help message and exit
  --evaluation_parameters EVALUATION_PARAMETERS, -p EVALUATION_PARAMETERS
                        Path to a file containing JSON object used to evaluate
                        parameters in expectations config.
  --result_format RESULT_FORMAT, -o RESULT_FORMAT
                        Result format to use when building evaluation
                        responses.
  --catch_exceptions CATCH_EXCEPTIONS, -e CATCH_EXCEPTIONS
                        Specify whether to catch exceptions raised during
                        evaluation of expectations (defaults to True).
  --only_return_failures ONLY_RETURN_FAILURES, -f ONLY_RETURN_FAILURES
                        Specify whether to only return expectations that are
                        not met during evaluation (defaults to False).

custom_dataset:
  Arguments defining a custom dataset to use for validation.

  --custom_dataset_module CUSTOM_DATASET_MODULE, -m CUSTOM_DATASET_MODULE
                        Path to a python module containing a custom dataset
                        class.
  --custom_dataset_class CUSTOM_DATASET_CLASS, -c CUSTOM_DATASET_CLASS
                        Name of the custom dataset class to use during
                        evaluation.
```

If you have other language suggestions, we'd be happy to accept a PR!

Second, I've updated the CLI to set its return value to the number of unmet expectations, as you suggested.

**Comment by smontanaro** [comment]
Thanks for the quick response. I was messing around with a little program to do (ironically) more-or-less with the GE CLI tool does, then discovered there was one already. When it didn't do everything I wanted, I complained. Isn't that how open source is supposed to work? <wink>

I will try to be more in PR generation mode going forward.

**Comment by jpcampb2** [comment]
Hooray open source! We're definitely excited about PRs going forward, but also would love to hear how you're using great expectations right now--what kind of data you're using and so forth--to help inform how development moves forward.
