### ISSUE TITLE
CLA link is broken

### ISSUE THREAD

**Issue by DlaregY** [fivetran/great_expectations#3344]
See the last line of https://docs.greatexpectations.io/docs/contributing/contributing/

"Note that if it’s your first contribution, you will need to sign a there is a standard Contributor license agreement (CLA)."

The CLA link does not work. Additionally, this sentence should be edited (e.g. " you will need to sign a there is a ").

I'm happy to help with both of these, but I need a link to that CLA first so I can sign it!

**Comment by kyleaton** [comment]
Hey @DlaregY thanks so much for pointing this out! I'll jump on this one and keep you updated.
