### ISSUE TITLE
column_map_expectation_template.py error with SqlAlchemyExecutionEngine

### ISSUE THREAD

**Issue by rogersamso** [fivetran/great_expectations#3354]
When running the column_map_expectation_template.py as is with the SqlAlchemyExecutionEngine I get this error:
'\n\nexpect_column_values_to_equal_three raised an exception:\nNo provider found for column_values.equal_three.unexpected_count using PandasExecutionEngine'.
With the PandasExecutionEngine it works as expected.

Does this mean that I should also build the column_values.equal_three.unexpected_count metric for the SqlAlchemyExecutionEngine to make it run? 

Thanks

**Environment :**
 - Operating System: Linux
 - Great Expectations Version: 0.13.32

**Comment by talagluck** [comment]
Hi @rogersamso - thanks for contributing this issue! Yes, this is just a template, so you'll need to uncomment the `@column_condition_partial` functions for any backends you wish to use. You'll see that there are 3, for `pandas`, `sqlalchemy`, and `spark` (L45-L57)

If you are running the file itself, and thus the `run_diagnostics` test within the file, this file is currently only set up to test with `pandas`, so if the function is commented (e.g. unimplemented) in a different backend, that would not reveal itself.

**Comment by rogersamso** [comment]
Hi @talagluck,  thanks for your response! 
I just found the  origin of the issue. For some reason pybigquery was not installed in my environment.

The diagnostics report that I got was a bit obscure, though:

```json
"execution_engines": {
    "PandasExecutionEngine": true,
    "SqlAlchemyExecutionEngine": true,
    "SparkDFExecutionEngine": false
  },
  "test_report": [],
  "diagnostics_report": [
    {
      "error_message": "'NoneType' object has no attribute 'sqlalchemy_bigquery'",
      "stack_trace": "Traceback (most recent call last):\n  File \"/home/roger/Development/ge_code/great_expectations/expectations/expectation.py\", line 802, in run_diagnostics\n    introspected_execution_engines,\n  File \"/home/roger/Development/ge_code/great_expectations/expectations/expectation.py\", line 906, in _get_test_results\n    expectation_execution_engines_dict=execution_engines,\n  File \"/home/roger/Development/ge_code/great_expectations/self_check/util.py\", line 1562, in generate_expectation_tests\n    c, d[\"data\"], schemas=schemas\n  File \"/home/roger/Development/ge_code/great_expectations/self_check/util.py\", line 777, in get_test_validator_with_data\n    sqlite_db_path=sqlite_db_path,\n  File \"/home/roger/Development/ge_code/great_expectations/self_check/util.py\", line 918, in build_sa_validator_with_data\n    \"bigquery\": pybigquery.sqlalchemy_bigquery.BigQueryDialect,\nAttributeError: 'NoneType' object has no attribute 'sqlalchemy_bigquery'\n"
    }
  ]
}
```

Besides,  while debugging the issue,I tried adding the key  `"suppress_test_for":  ["bigquery"]` in the test, but this is not implemented in the `generate_expectation_tests` function in `utils.py'. There's certainly a good reason for that.

Thank you again for your answer.
Regards
