### ISSUE TITLE
Pandas FutureWarning for specifying the number of columns in Jupyter

### ISSUE THREAD

**Issue by miike** [fivetran/great_expectations#3355]
**Describe the bug**

Jupyter notebook raises a FutureWarning when using -1 for the max_colwidth display setting.

>FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new suite that uses pandas
2. `great_expectations suite edit suitename`
3. Run the first cell in the notebook
4. Observe the FutureWarning

**Expected behavior**
No FutureWarning should be raised.

**Environment:**
 - Great Expectations Version: 0.13.32

**Additional context**

N/A

**Comment by NathanFarmer** [comment]
Thanks for opening this issue, @miike! Would you be interested in opening a PR with the change you made in your fork linked above? I am happy to offer any guidance that is needed.

**Comment by talagluck** [comment]
Thanks! I believe this has been resolved in #3612! Closing for now.

**Comment by miike** [comment]
That's great news - thanks for the heads up!
