### ISSUE TITLE
AttributeError: 'Datasource' object has no attribute 'get_batch' in validation_playground.ipynb for Pandas

### ISSUE THREAD

**Issue by seve-martinez** [fivetran/great_expectations#3357]
**Describe the bug**
Using the v3 API, the validation_playground.ipynb that is created under the notebooks/pandas directory tries to return the v2 version of the batch_data object, which results in an error:
```
AttributeError: 'Datasource' object has no attribute 'get_batch'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/cf/2ksxt2dn7f55h6k3vd65j4880000gn/T/ipykernel_78183/1563605950.py in <module>
      6 
      7 
----> 8 batch = context.get_batch(batch_kwargs, expectation_suite_name)
      9 batch.head()

~/PycharmProjects/IEAP/venv/lib/python3.9/site-packages/great_expectations/data_context/data_context.py in get_batch(self, arg1, arg2, arg3, **kwargs)
   1495             data_asset_type = arg3
   1496         batch_parameters = kwargs.get("batch_parameters")
-> 1497         return self._get_batch_v2(
   1498             batch_kwargs=batch_kwargs,
   1499             expectation_suite_name=expectation_suite_name,

~/PycharmProjects/IEAP/venv/lib/python3.9/site-packages/great_expectations/data_context/data_context.py in _get_batch_v2(self, batch_kwargs, expectation_suite_name, data_asset_type, batch_parameters)
   1196 
   1197         datasource = self.get_datasource(batch_kwargs.get("datasource"))
-> 1198         batch = datasource.get_batch(
   1199             batch_kwargs=batch_kwargs, batch_parameters=batch_parameters
   1200         )

AttributeError: 'Datasource' object has no attribute 'get_batch'
```

**To Reproduce**
1. Create new datacontext using the `great_expectations --v3-api init`
2. Create a new pandas datasource using `great_expectations --v3-api datasource new`
3. Open the `notebooks/pandas/validation_playground.ipynb`

**Expected behavior**
The notebook would return a batch of data, not a `DataAsset`

**Environment (please complete the following information):**
 - Operating System: Mac
 - Great Expectations Version: 0.13.2

**Additional context**
The `[datasource['name'] for datasource in context.list_datasources() if datasource['class_name'] == 'PandasDatasource']`

Also returns no values because the datasource is configured as a `PandasExecutionEngine`

**Comment by NathanFarmer** [comment]
Thanks for submitting this issue, @The-Loud! We will review internally and respond over the next week or so.

**Comment by talagluck** [comment]
Hi @The-Loud - sorry for delays. I believe the issue is that the validation_playground notebook is not configured to work with V3. We have since removed these notebooks in #3467. I'm going to close this for now, but please feel free to chime in with any questions.
