### ISSUE TITLE
Data docs filter on date is broken

### ISSUE THREAD

**Issue by fosk06** [fivetran/great_expectations#3358]
**Describe the bug**

**To Reproduce**
1. Run few expectation suite
2. Generate the data docs
3. On the data docs, check the date of the last run and set this date in the "run time" date picker
4. The error is there : there is no data displayed for this day

It looks like the date picker don't format the date correctly, this is why the data grid component can't filter by date.
See the screeshots for details

![first step](https://user-images.githubusercontent.com/16429809/132181416-25752163-a713-4466-b462-a48f2b31dddf.png)
![second step](https://user-images.githubusercontent.com/16429809/132181442-26030a91-b0ce-4c8f-b24f-d7ab0f29c495.png)

**Comment by NathanFarmer** [comment]
Thanks for submitting this issue, @fosk06! We will review internally and respond over the next week or so.

**Comment by NathanFarmer** [comment]
Hi @fosk06! Would you be interested in making a contribution to address this? We would be happy to offer any guidance needed.

**Comment by fosk06** [comment]
i could do it i guess. I'm a JS developer after all.

**Comment by talagluck** [comment]
Hi @fosk06! I wanted to check in - is this something which you are interested in contributing? Please let us know how we can assist.

**Comment by austiezr** [comment]
Hey @fosk06! Just checking in again, is this something you would be interested in contributing?

**Comment by fosk06** [comment]
Sorry but I don't have time to contribute right now.
