### ISSUE TITLE
Locking and deadlocking for ms sql datasource

### ISSUE THREAD

**Issue by fitz-omny** [fivetran/great_expectations#3366]
**Describe the bug**
i have a Datasource that connects to an MS SQL instance. i’m noticing a lot of unexpected locking and even deadlocks when creating a new Suite using a simple custom SQL query for the data. Is there a way to prevent this from happening, maybe changing the isolation level associated with the connection?

I’m using SQLAlchemy, PYODBC and Microsoft ODBC Driver 17 for SQL Server (x64) for the connection.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.13.28

**Comment by NathanFarmer** [comment]
@fitz-omny How exactly does the locking and deadlocking manifest itself in your GE workflow? Do you see an error message? Is this something you would be interested in making a contribution for? As an aside, we are unable to prioritize bugs that are related to Windows with internal resources. If you are interested in contributing, we are happy to offer guidance where needed.

**Comment by fitz-omny** [comment]
@NathanFarmer its interesting, the locking and deadlocking manifest itself for connections when running a query that references the information_schema objects in tempdb.  I am not get an error message when the lock occurs, only when a deadlock occurs.

i'm interested in contributing, just not sure where to start, so direction on that would be helpful.

also, i don't think that it is a Windows issue.  does that help with prioritization?

**Comment by NathanFarmer** [comment]
@fitz-omny I also suspect that it is not a Windows issue, but there is only one way to find out! Most general questions that you have about contributing should be addressed [in this series of docs](https://docs.greatexpectations.io/docs/contributing/contributing). Can you provide the "deadlocking" error message next time you see it? Following the stack traceback for the error message is often a good place to start when trying to understand where in the codebase to make your contribution. Once you get the changes working on your PC, you can open a pull request and I will review before we merge it in!

**Comment by talagluck** [comment]
Hi @fitz-omny - thanks again for raising this. I wanted to confirm - is this still an issue for you? If so, would you please share some of the stack traceback message so we can see exactly where things are going wrong? That will make it easier to figure out where the bug is occurring.

**Comment by talagluck** [comment]
I'm going to close this for now, but if it turns out to still be an issue and you're able to provide us with more steps to reproduce, feel free to re-open.
