### ISSUE TITLE
Using allow_cross_type_comparisons in expect_column_pair_Values_A_to_be_greater_than_B raises Not Implemented Error

### ISSUE THREAD

**Issue by vivek89007** [fivetran/great_expectations#3373]
```@DocInherit
    @MetaPandasDataset.column_pair_map_expectation
    def expect_column_pair_values_A_to_be_greater_than_B(
        self,
        column_A,
        column_B,
        or_equal=None,
        parse_strings_as_datetimes=None,
        allow_cross_type_comparisons=None,
        ignore_row_if="both_values_are_missing",
        result_format=None,
        row_condition=None,
        condition_parser=None,
        include_config=True,
        catch_exceptions=None,
        meta=None,
    ):
        # FIXME
        if allow_cross_type_comparisons == True:
            raise NotImplementedError```

``

While using allow_cross_type_comparisons in 0.13.30 version is raising Not Implemented Error...When are we guys planning to add this support? Can someone provide a workaround?

**Comment by vivek89007** [comment]
@jcampbell @eugmandel @bhcastleton - Please help

**Comment by NfnqB** [comment]
Same problem with expect_column_pair_values_to_be_equal. The implementation is simply just throwing NotImplmentedError. Check some others multi-column expectations and seems all having the same problem.

**Comment by NathanFarmer** [comment]
Hi @vivek89007 and @NfnqB! You you for creating this issue. We are reviewing this internally and we will follow up in the next few days.

**Comment by NathanFarmer** [comment]
Hi @vivek89007 and @NfnqB! After some internal discussions, we were hoping you could provide a little more context around your specific use cases for this feature. There is a lot of complexity inherent in converting and comparing data types across the various supported backends. Performing those transformations during ETL would seem to be a more natural "line in the sand" between the data pipelines and measuring the quality of the data in those pipelines.

**Comment by NfnqB** [comment]
@NathanFarmer 
Mine is with SqlAlchemyDataset and Legacy v2 api
Great Expectations version 0.13.31
When trying to run expect_column_pair_values_to_be_equal expectation on debug mode and the function stops at abstract dataset.py with no actual implementation in Sqalchemy_dataset.py, while the other two dataset (pandas_dataset and sparkdf_dataset) have no problem working with it.
Maybe it is related to the version not updated enough issue?

**Comment by vivek89007** [comment]
I am using v2 LegacyCheckpoint for validation and version 0.13.30 version
of great expectations. I am trying to validate a pandas dataset and while
using allow_cross_comparisons=True and getting this error as its not
implemented.

**Comment by NathanFarmer** [comment]
@NfnqB @vivek89007 I'm sorry I wasn't clear. What I meant by your use case is, how are you intending to use this feature? What two data types are you comparing against each other?

**Comment by vivek89007** [comment]
I need to compare strings, floats, int and datetime.

**Comment by NfnqB** [comment]
Im trying to compare two Decimal value from a join query.

**Comment by NathanFarmer** [comment]
@NfnqB if the data types are the same, why are you needing to use `allow_cross_type_comparisons`?

**Comment by vivek89007** [comment]
Can we expect this fix in the next release?

**Comment by NathanFarmer** [comment]
Hi @vivek89007 and @NfnqB. We are intending to deprecate this feature as it has become our position that this should be handled during the ETL process (as opposed to the data quality testing process). More communication around this will be forthcoming, but it would be prudent for you to start looking for alternative ways of performing this transformation.

**Comment by talagluck** [comment]
I'm going to close this issue, since this feature is being deprecated. Please keep an eye out for a blog post providing more detail in the next couple of weeks!
