### ISSUE TITLE
A decimal(20,4) column in a spark dataframe cannot be interpret as a decimal.

### ISSUE THREAD

**Issue by derek-hk** [fivetran/great_expectations#3389]
**Describe the bug**
A decimal(20,4) in a spark dataframe is casted as "unknown" data type in the BasicDatasetProfilier's HTML output
![image](https://user-images.githubusercontent.com/90680179/133217120-45d77b71-56cb-4195-87e3-80d26c85db77.png)

**To Reproduce**
1. Declare a gdf by running
`ds = ge.dataset.SparkDFDataset(spark.sql('select * from xxx limit 10'))`
where xxx is a spark table which contains a decimal(20,2) column

2. Do the profiling and render it by
```
from great_expectations.profile.basic_dataset_profiler import BasicDatasetProfiler
expectation_suite_based_on_profiling, validation_result_based_on_profiling = ds.profile(BasicDatasetProfiler)

from great_expectations.render.renderer import ProfilingResultsPageRenderer, ExpectationSuitePageRenderer
from great_expectations.render.view import DefaultJinjaPageView
profiling_result_document_content = ProfilingResultsPageRenderer().render(validation_result_based_on_profiling)
expectation_based_on_profiling_document_content = ExpectationSuitePageRenderer().render(expectation_suite_based_on_profiling)
```
3. Generate the HTML report by
`profiling_result_HTML = DefaultJinjaPageView().render(profiling_result_document_content)`

4. Open the report and go to the decimal(20,2) column and check the datatype, which is unknown in my case
![image](https://user-images.githubusercontent.com/90680179/133217120-45d77b71-56cb-4195-87e3-80d26c85db77.png)

**Expected behavior**
The mention column is identified as decimal type

**Environment (please complete the following information):**
 - Databricks runtime version 6.4 environment
 - Great Expectations Version: 0.13.33

**Suspected root cause of the issue**
 "DecimalType", which is the data type of the involved spark column is not include in the "FLOAT_TYPE_NAMES" list in ProfilerTypeMapping class in base.py
![image](https://user-images.githubusercontent.com/90680179/133217748-90058b02-40f9-45ea-bf4a-8b4db2ac03b3.png)
![image](https://user-images.githubusercontent.com/90680179/133218175-dfeae53c-1782-4c6c-a4ea-92bfd0ca8d75.png)

**Comment by NathanFarmer** [comment]
Thanks for opening this issue @derek-hk! We will need to have some discussions about this internally and will respond in about a week.

**Comment by talagluck** [comment]
Closing as this is focused on V2, which we no longer fully support.
