### ISSUE TITLE
expect_column_values_to_be_between - not working as expected when min_value is 0 and strict_min - True. 0 is not getting captured as error

### ISSUE THREAD

**Issue by vivek89007** [fivetran/great_expectations#3390]
**Describe the bug**

**To Reproduce**
1. Create a expectation JSON. Put "min_value": 0 and strict_min: true
2. Add 0 in the data and do validation.

**Expected behavior**
0 should be thrown as validation error as strict min is true. However, 0 is not thrown as error even though we have strict_min.

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: 0.13.30

**Additional context**

**Comment by NathanFarmer** [comment]
Hi @vivek89007! Thank you for submitting this issue. In the meantime, you are welcome to make a contribution to address it, and I can guide you through the process. Otherwise, we will look into it and follow up over the next few days.

**Comment by vivek89007** [comment]
I would really like to contribute to the project. But, I am unaware of the
process to contribute to github.

**Comment by NathanFarmer** [comment]
@vivek89007 To get started contributing to Great Expectations you can reference [this series of docs](https://docs.greatexpectations.io/docs/contributing/contributing). The high level steps are:

1. Clone the `develop` branch from the GE repository to your local machine
2. Make changes to the code which address your issue on a new feature branch
3. Submit a pull request (PR) from within the GE repository for our team to review and merge into the codebase once approved

The docs I linked will have more detail about the contribution process. Thanks!

**Comment by vivek89007** [comment]
It was because of our custom logic of data conversion 0 was becoming NaN, and hence it was getting captured in not null expectation...We can close the issue..The logic in GE is correct..
