### ISSUE TITLE
Document how to pass through SqlAlchemy create_engine parameters

### ISSUE THREAD

**Issue by jdimatteo** [fivetran/great_expectations#3394]
**Is your feature request related to a problem? Please describe.**
Sometimes it is useful to customize the [SqlAlchemy create_engine](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine) parameters, however it isn't clear how to specify these in the data context config.

**Describe the solution you'd like**
Documentation showing an example data context config providing arbitrary SqlAlchemy create_engine parameters, including [pool_size](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.pool_size).

After documenting, consider updating how SqlAlchemy create_engine parameters are set with `async_executor.py` as added in https://github.com/great-expectations/great_expectations/pull/3362.

**Describe alternatives you've considered**
Updating the Great Expectations code to configure different create_engine parameters depending on the use case with https://github.com/great-expectations/great_expectations/pull/3362.

**Additional context**
@talagluck requested I create this issue when reviewing https://github.com/great-expectations/great_expectations/pull/3362. See https://github.com/great-expectations/great_expectations/pull/3362#discussion_r708437954.

**Comment by NathanFarmer** [comment]
Thanks for raising this issue @jdimatteo! We will get this into our queue and discuss where it falls in the priority list for docs.

**Comment by AFineDayFor** [comment]
Howdy @jdimatteo, thanks doubly so for raising this!

Could you test if passing the kwargs you'd want in `sqlalchemy.create_engine` when used as a `connection_string` in your `datasource` as indicated [here](https://github.com/great-expectations/great_expectations/pull/3991/files)?
If that indeed works for you, if you have any concerns with the document let me know as well please.

**Comment by AFineDayFor** [comment]
@jdimatteo have you had any success with [batch_spec_passthrough](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_create_a_batch_of_data_from_an_in_memory_spark_or_pandas_dataframe)?

**Comment by jdimatteo** [comment]
> Could you test if passing the kwargs you'd want in `sqlalchemy.create_engine` when used as a `connection_string` in your `datasource` as indicated [here](https://github.com/great-expectations/great_expectations/pull/3991/files)? If that indeed works for you, if you have any concerns with the document let me know as well please.

@AFineDayFor Sorry I do not understand this documentation. Can you please give a working example?

I added a complete example [here](https://github.com/jdimatteo/great_expectations/tree/issue_3394/issue_3394_example) with a few files. To create a sqlite db used in this example, please first run [create_sqlite_db.py](https://github.com/jdimatteo/great_expectations/blob/issue_3394/issue_3394_example/create_sqlite_db.py).

[query_with_connection_arg.py](https://github.com/jdimatteo/great_expectations/blob/issue_3394/issue_3394_example/query_with_connection_arg.py#L5) shows how using SQLAlchemy (without using Great Expectations) you can pass `create_engine` parameters like enabling echoing with `sqlalchemy.create_engine('sqlite:///example.db', echo=True)`.

In [great_expectations_example.py](https://github.com/jdimatteo/great_expectations/blob/issue_3394/issue_3394_example/great_expectations_example.py#L24), the connection string is specified as part of the context datasource:

```
context.add_datasource(
    name=DATASOURCE_NAME,
    class_name="Datasource",
    execution_engine={
        "class_name": "SqlAlchemyExecutionEngine",
        "connection_string": "sqlite:///example.db",
    },
    data_connectors={
        DATA_CONNECTOR_NAME: {
            "class_name": "ConfiguredAssetSqlDataConnector",
            "name": "whole_table",
            "assets": {SUITE_AND_ASSET_NAME: {}},
        },
    },
)
```

The [documentation you linked](https://github.com/great-expectations/great_expectations/pull/3991/files) says "If your usecase requires passing custom `sqlalchemy.create_engine` paramaters; you can take advantage of that by passing them in your `connection_string`" -- how does this apply to the example above? Can you please give a working example?

> have you had any success with [batch_spec_passthrough](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_create_a_batch_of_data_from_an_in_memory_spark_or_pandas_dataframe)?

Sorry I do not understand how to use `batch_spec_passthrough` for passing SQLAlchemy `create_engine` parameters based on that linked documentation. Can you please give a working example?

Please note that these examples are based on https://github.com/great-expectations/great_expectations/blob/main/tests/performance/taxi_benchmark_util.py .

The only way I've found so far to successfully get Great Expectations to use SQLAlchemy `create_engine` parameters is to modify the Great Expectations code like I did here: https://github.com/great-expectations/great_expectations/pull/3362/files#diff-2e0903f2ba2f628b8645e3bb6decf8d451c943e724fc3852f555e94e92b0430fR1090

**Comment by jdimatteo** [comment]
@AFineDayFor Sorry for the delay in my response and thank you for looking into this!

**Comment by AFineDayFor** [comment]
What I'd meant with batch_spec_passthrough would be like the example ["Here is a Runtime Batch Request using a path"](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_create_a_batch_of_data_from_an_in_memory_spark_or_pandas_dataframe/).

You should be able to pass options for reading your datasource. The particular documentation for valid options would be for the module in particular.

**Comment by AFineDayFor** [comment]
```
context.add_datasource(
    name=DATASOURCE_NAME,
    class_name="Datasource",
    execution_engine={
        "class_name": "SqlAlchemyExecutionEngine",
        "connection_string": "sqlite:///example.db",
        "batch_spec_passthrough": {"echo": True}  # you would be able to add it here in the
                                                  # datasource configuration, or in a batch request
    },
    data_connectors={
        DATA_CONNECTOR_NAME: {
            "class_name": "ConfiguredAssetSqlDataConnector",
            "name": "whole_table",
            "assets": {SUITE_AND_ASSET_NAME: {}},
        },
    },
)
```

**Comment by jdimatteo** [comment]
@AFineDayFor I tried your example and [checked in the modified code here](https://github.com/jdimatteo/great_expectations/tree/issue_3394_with_batch_spec_passthrough/issue_3394_example). In my testing, it does not work.

When I run the code, this is the output, and it is missing the [echo behavior](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.echo):

```
(venv) jdimatteo@erel:~/dev/great_expectations_fork_2/issue_3394_example$ python great_expectations_example.py 
All expectations succeeded? False
(venv) jdimatteo@erel:~/dev/great_expectations_fork_2/issue_3394_example$ 
```

The echo behavior can be turned on by [modifying the Great Expectations source code like this](https://github.com/jdimatteo/great_expectations/commit/a2d228467c774e65d5270ad81fb72f641fde7cbe), resulting in this output:

```
(venv) jdimatteo@erel:~/dev/great_expectations_fork_2/issue_3394_example$ python great_expectations_example.py
2022-02-08 17:10:36,608 INFO sqlalchemy.engine.Engine PRAGMA main.table_xinfo("person")
2022-02-08 17:10:36,609 INFO sqlalchemy.engine.Engine [raw sql] ()
All expectations succeeded? False
(venv) jdimatteo@erel:~/dev/great_expectations_fork_2/issue_3394_example$
```

Notice how this output includes logging like `PRAGMA main.table_xinfo("person")` -- this is the result of the `echo` SQLAlchemy `create_engine` parameter.

I also tried a few variations with `batch_spec_passthrough` and I could not get this to work as you suggested. I don't know if this is a bug in Great Expectations or a miscommunication or if my example is wrong -- please clarify with a working tested example.

**Comment by AFineDayFor** [comment]
Howdy @jdimatteo.
This may take more work on our end and I'll bring it up with the team. I apologize for any guff.

**Comment by jdimatteo** [comment]
Thank you @AFineDayFor for looking into this!

**Comment by AFineDayFor** [comment]
@jdimatteo the documentation has been updated to reflect how to pass options to the reader it's self [here](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/filesystem/spark#additional-notes)


e.g. 

```py
...
batch_spec_passthrough={"reader_method": "csv", "reader_options": {"echo": True}},
...
```
