### ISSUE TITLE
Optimize Data Docs Runtime

### ISSUE THREAD

**Issue by jdimatteo** [fivetran/great_expectations#3396]
**Is your feature request related to a problem? Please describe.**

Multithreading of database queries was introduced with https://github.com/great-expectations/great_expectations/pull/3362, and it was found that data doc creation is now the biggest bottleneck for the `test_taxi_trips_benchmark[100-True-V2]` benchmark, accounting for about 63% of the time (more than querying the database or any thing else):

* When data docs is enabled, `test_taxi_trips_benchmark[100-True-V2]` benchmark runs in [60.8 seconds](https://github.com/great-expectations/great_expectations/blob/857c4835bd0b0dbad4a8d0c7dbc48aeb0868f921/tests/performance/results/minimal_multithreading_run_2.json#L1084).
* When data docs is disabled, `test_taxi_trips_benchmark[100-False-V2]` benchmark runs in [22.5 seconds](https://github.com/great-expectations/great_expectations/blob/857c4835bd0b0dbad4a8d0c7dbc48aeb0868f921/tests/performance/results/minimal_multithreading_run_3.json#L1000).
* Enabling data docs accounts for 63% of the runtime (because `60.8 seconds - 22.5 seconds = 38.3 seconds`, and `38.3/60.8~=0.63`

Ideally rendering data docs would run 10x faster, e.g. so `test_taxi_trips_benchmark[100-True-V2]` completed in less than 26.3 seconds.

**Describe the solution you'd like**
Profile, optimize, record a benchmark result showing rendering data docs running 10x faster (e.g. so `test_taxi_trips_benchmark[100-True-V2]` completed in less than 26.3 seconds), and create a PR.

**Describe alternatives you've considered**
Disabling data docs generation or only computing them when there are failures.

**Additional context**
@talagluck requested I create this issue with the "help wanted" label when reviewing #3362. See https://github.com/great-expectations/great_expectations/pull/3362#issuecomment-919313487.

**Comment by NathanFarmer** [comment]
Thanks for raising this issue @jdimatteo! We will take a look and respond over the next week or so.

**Comment by talagluck** [comment]
Following up here, we will likely not be able to prioritize working on this internally in the immediate future, but if anyone is interested in making a contribution here, please let us know! We are happy to offer guidance and support.

**Comment by talagluck** [comment]
Thanks for raising this! This is great feedback. Realistically, this isn't something that we will be able to implement in the near-term, but we have logged this feedback to consider when we are working in this area.

I'm going to close this issue for now, but if you or anyone else is interested in contributing, please free to re-open or let us know.
