### ISSUE TITLE
Implementation of expectations for SQLAlchemyDataset

### ISSUE THREAD

**Issue by Ngg971** [fivetran/great_expectations#340]
Hi,

Thanks for putting together this very handy package.

I have been trying to integrate it with my SQLAlchemy setup but noticed that a bunch of expectations were still not implemented (throwing `NotImplemented` error), namely:
- `expect_column_values_to_match_strftime_format`
- `expect_column_values_to_be_unique`
- `expect_column_values_to_match_regex`

Do you know if they will be implemented for SQLAlchemy anytime soon, and if not is my best option to just sublcass `SqlAlchemyDataset` for now in order to custom implement them?

Thanks,
Nathanael

**Comment by jpcampb2** [comment]
Really glad you're finding the package useful!

We would most love it if you would be willing to create pull requests with implementations that could be directly integrated into the library, actually, though you're absolutely correct that you could also subclass `SqlAlchemyDataset` to implement them.

**Comment by jpcampb2** [comment]
I'm going to close this issue for now.
