### ISSUE TITLE
[FEATURE] add inter-batch KL-divergence metric (?) 

### ISSUE THREAD

**Issue by edjoesu** [fivetran/great_expectations#3415]
**Is your feature request related to a problem? Please describe.**
I think we would like a way to measure inter-batch changes in the distribution of a column. One thing we could do is have a ParameterBuilder that creates an Expectation for the interbatch KL divergence based on statistics from existing batches. Then this can be run against the a new target batch. 

**Describe the solution you'd like**
I think this requires a modified ParameterBuilder, it is very similar to the NumericMetricRangeMultiBatchParameterBuilder but we are using pairs of batches as the input. There might also be some gotchas with the histogram binning to take care of. 

**Describe alternatives you've considered**
I haven't thought about this very hard, open to suggestions, or to it being a dumb idea. This might actually be more important for discrete/categorical columns than for continuous ones, since many other numeric expectations should trigger on weirdness with continuous columns (though I am hopeful that this is still useful there). 

**Additional context**

**Comment by NathanFarmer** [comment]
Thanks for opening this issue @edjoesu! I have labeled this item for our core engineering team's backlog, as it is already on our roadmap.

**Comment by AFineDayFor** [comment]
Howdy @edjoesu,

Thanks again for the issue and being present with us in the community 😄 

I'm going to close this because it's already on the roadmap.
