### ISSUE TITLE
[FEATURE] add messages when expectation tests fail with wrong value

### ISSUE THREAD

**Issue by edjoesu** [fivetran/great_expectations#3416]
**Is your feature request related to a problem? Please describe.**
When tests in great_expectations/self_check/util.py::check_json_test_result fail, they raise an AssertionError, but no message. The incorrect value doesn't seem to be displayed. In some cases it may need to be truncated, but it's worth displaying something. 

**Describe the solution you'd like**
Add messages to the assertions so that the exception message contains the required and obtained values. 

**Describe alternatives you've considered**
Maybe this lives somewhere else? 

**Additional context**

**Comment by talagluck** [comment]
Thanks for raising this issue, @edjoesu! We will review and be in touch soon.

**Comment by kenwade4** [comment]
@edjoesu There was some improvement to the AssertionErrors shown in this merged PR https://github.com/great-expectations/great_expectations/pull/5239
