### ISSUE TITLE
Boolean output of a json from class MicrosoftTeamsRenderer()

### ISSUE THREAD

**Issue by derek-hk** [fivetran/great_expectations#3426]
**Describe the bug**
The JSON output from MicrosoftTeamsRenderer produces "True" boolean values
![image](https://user-images.githubusercontent.com/90680179/134102391-2d875f37-95c0-4ac7-ad1b-0db11e56cc6f.png)

Which turns the JSON become imparseable

**To Reproduce**
1. Run the Rule Based Validator and call MicrosoftTeamsRenderer() to render the JSON file
`y = MicrosoftTeamsRenderer().render(<your validation result>)`
2. You will see the "True" value when searching in the JSON file produced

**Expected behavior**
The value of the "True" should be "true"

**Environment (please complete the following information):**
Python 3.6
Great Expectations Version: 0.13.33

**Suspected root cause**
Values of a boolean in a JSON could only be either "true" or "false", instead of "True" or "False, while the query part in the source code is giving the latter
![image](https://user-images.githubusercontent.com/90680179/134102189-cda70a4b-13f0-4247-b636-cdb942e1e396.png)

**Comment by NathanFarmer** [comment]
Hi @derek-hk! Thank you for raising this issue. We will take a look and respond soon. In the meantime, if you would be interested in contributing a bug fix, I would be happy to offer any guidance you need.

**Comment by SanthoshS20** [comment]
@NathanFarmer Can I contribute to this?

**Comment by NathanFarmer** [comment]
@SanthoshS20 Yes of course! Please ping me here if you need any guidance, or once you open a PR and need a code review.

**Comment by talagluck** [comment]
Hi @SanthoshS20 - I wanted to check, are you still interested in contributing this? Please feel free to reach out if you have any questions.
