### ISSUE TITLE
Validation run copies entire source table using insert command

### ISSUE THREAD

**Issue by JoPrasanth** [fivetran/great_expectations#3428]
**Issue**
At start of validation, all underlying tables are copied ('insert into' not 'clone' command) into some temporary schema and only then the validations kick off. 
`CREATE OR REPLACE TEMPORARY TABLE ge_tmp_d49e60a2 AS SELECT * 
FROM temporary_tables.test_dataset_clone 
WHERE true`
Few tables have Billion rows and it takes a lot of time there. Is there any means to skip this, or force use clone command?

**Command used for running validation rules**
`> great_expectations checkpoint run FFS`

**checkpoint config**
![image](https://user-images.githubusercontent.com/91119573/134139672-a95aa3ec-3045-48ed-8264-b962ccbe9625.png)

**great_expectations.yml file**

![image](https://user-images.githubusercontent.com/91119573/134141297-035dcc15-dafe-4397-aab8-899dc8d7a150.png)

**Validation rule json**
![image](https://user-images.githubusercontent.com/91119573/134141868-661b133e-e9c5-477e-8f96-3f5d9788cfa7.png)

**Environment :**
 - Operating System: Windows 10
 - Great Expectations Version: 0.13.24
 - Database: Snowflake

**Comment by NathanFarmer** [comment]
Hi @JoPrasanth! Thank you for opening this issue. We will take a look and follow up soon. In the meantime, have you tried using the [ConfiguredAssetFilesystemDataConnector](https://docs.greatexpectations.io/docs/reference/datasources#data-connectors) instead of the `InferredAssetFilesystemDataConnector`?

**Comment by JoPrasanth** [comment]
@NathanFarmer, i tried ConfiguredAssetSqlDataConnector still i am seeing a full table copy (inserts).

**Comment by talagluck** [comment]
Hi @JoPrasanth - apologies for delays! Have you had any luck with this? What happens when you set `create_temp_table` to False?

**Comment by JoPrasanth** [comment]
@talagluck , i tried that, still the temp table creation happens. Can you let us know where all should i add that flag? I will double confirm if that works

**Comment by cdkini** [comment]
@JoPrasanth you can pass in a boolean value to either the `SQLAlchemyExecutionEngine` config or within batch spec passthrough. Let me know if that works!

**Comment by cdkini** [comment]
@JoPrasanth I'm going to close down this issue but please feel free to open a new one if this issue persists. Thank you!
