### ISSUE TITLE
Validation run always scans all schemas in Snowflake for Metadata

### ISSUE THREAD

**Issue by JoPrasanth** [fivetran/great_expectations#3429]
**Issue**
At start of validation, even before checkpoints/rules are parsed, multiple queries are fired for metadata (information_schema) info even when there are no rules around it. 
`
SHOW /* sqlalchemy:get_schema_names */ SCHEMAS;
SHOW /* sqlalchemy:get_table_names */ TABLES IN schema_1;
SHOW /* sqlalchemy:get_view_names */ VIEWS IN schema_1;
SHOW /* sqlalchemy:get_table_names */ TABLES IN schema_2;
SHOW /* sqlalchemy:get_view_names */ VIEWS IN schema_2;
.
.
.
.
.
.
SHOW /* sqlalchemy:get_table_names */ TABLES IN schema_n;
SHOW /* sqlalchemy:get_view_names */ VIEWS IN schema_n;
`
Is there any means to skip this?

**Command used for running validation rules**
`> great_expectations checkpoint run FFS`

**checkpoint config**
![image](https://user-images.githubusercontent.com/91119573/134139672-a95aa3ec-3045-48ed-8264-b962ccbe9625.png)

**great_expectations.yml file**

![image](https://user-images.githubusercontent.com/91119573/134141297-035dcc15-dafe-4397-aab8-899dc8d7a150.png)

**Validation rule json**
![image](https://user-images.githubusercontent.com/91119573/134141868-661b133e-e9c5-477e-8f96-3f5d9788cfa7.png)

**Environment :**
 - Operating System: Windows 10
 - Great Expectations Version: 0.13.24
 - Database: Snowflake

**Comment by strelnikoff** [comment]
Hi! I have the same problem when using Clickhouse

<img width="769" alt="image" src="https://user-images.githubusercontent.com/9088312/134499209-fb8f4da7-cbcf-4381-8d46-16c26b29ba30.png">


<img width="604" alt="image" src="https://user-images.githubusercontent.com/9088312/134498562-da974265-9a32-41a6-817b-5fe8dfa4bb71.png">

**Comment by NathanFarmer** [comment]
Hi @JoPrasanth! Thank you for opening this issue. We will take a look and follow up soon. In the meantime, have you tried using the [ConfiguredAssetFilesystemDataConnector](https://docs.greatexpectations.io/docs/reference/datasources#data-connectors) instead of the `InferredAssetFilesystemDataConnector`?

**Comment by JoPrasanth** [comment]
@NathanFarmer , i added a default_configured_data_connector_name with ConfiguredAssetSqlDataConnector still metadata scans were happening even though i pointed only to this connector. 
In 2nd attempt, I commented out other connectors and had only ConfiguredAssetSqlDataConnector in my datasource. It worked then. Metadata scans didnt happen

**Comment by NathanFarmer** [comment]
@JoPrasanth that's good news! The team is currently evaluating these data connectors and intends to roll out additional documentation to make it more straight forward. For now, I will close this issue as it seems to be addressed using `ConfiguredAssetSqlDataConnector`.
