### ISSUE TITLE
Validation report lacks input data context

### ISSUE THREAD

**Issue by kainoa21** [fivetran/great_expectations#343]
It would be helpful if a validation report object could explicitly include metadata about the input data that was validated.

Example:
```python
{
  "input": "my_dataset",
  "results" : [...],
  "success": False,
  "statistics": {...}
}
```

**Comment by jpcampb2** [comment]
Great idea, @kainoa21 . We have a dataset name property that is never populated in practice right now. Where do you think the input name should be drawn from?

**Comment by kainoa21** [comment]
I think my first instinct was that it would draw from the existing dataset name property.  Maybe this would be a reason to actually populate it?

**Comment by jpcampb2** [comment]
I think that makes sense, but I'm not sure what is the most useful thing to populate it with. We could change the default name from `None` to something else and add the field easily enough. What would you think works best for that name default?

**Comment by kainoa21** [comment]
Would it be okay to just continue to omit such a field from the results if it is not specified?  But also allow users to specify it (override existing dataset name if it exists) as part of calling validate?
