### ISSUE TITLE
Data Asset name is not displayed in slack notification

### ISSUE THREAD

**Issue by shpolina** [fivetran/great_expectations#3430]
**Describe the bug**
After running validations as part of a checkpoint the Data asset name shows as `__no_data_asset_name__`  in slack notifications
![image](https://user-images.githubusercontent.com/14918053/134176561-b97466be-e4a7-4f96-9d97-23dae164a564.png)

**To Reproduce**
1. Configure checkpoint with slack notification
2. Run checkpoint
3. See slack output

**Expected behavior**
Data asset name should display actual data asset name

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations 0.13.32

**Comment by NathanFarmer** [comment]
Thank you for raising this issue and PR @shpolina! Can you confirm that you are seeing this issue using the V3 api?

**Comment by shpolina** [comment]
@NathanFarmer yes, I am seeing it with V3
