### ISSUE TITLE
[FEATURE] Extend Slack Notifications to use slack apps

### ISSUE THREAD

**Issue by psheets** [fivetran/great_expectations#3439]
**Is your feature request related to a problem? Please describe.**
Slack is deprecating webhooks for slack apps. There is not a simple way to send notifications to different channels. 

**Describe the solution you'd like**
I would like to have the option to use a bot token to send notifications to a specific  channel depending on which checkpoint is running.

**Comment by NathanFarmer** [comment]
Hi @psheets! Thank you for opening this issue. We are reviewing your PR and will respond soon!

**Comment by NathanFarmer** [comment]
Hi @psheets! I am closing this issue as PR #3440 has been merged into `develop` and will be available in the next release!
