### ISSUE TITLE
[FEATURE] Data docs does not show Observed values for distribution tests

### ISSUE THREAD

**Issue by Mista-C** [fivetran/great_expectations#3447]
**Is your feature request related to a problem? Please describe.**
When using distribution expectations like `expect_column_bootstrapped_ks_test_p_value_to_be_greater_than`, the result in data docs does not show any values in the `Observed Value` field, also the expectation is highlighted yellow.

**Describe the solution you'd like**
It would be nice to show some values to find out why the expectation failed, maybe some feedback to the user why the expectation is marked yellow.

**Additional context**
@NathanFarmer mentioned that the `prescriptive_renderer` for this expectation has not been written yet.  

A screenshot of the data docs page can be seen below:  
![data_distribution_expectation](https://user-images.githubusercontent.com/15473076/134638024-a8f93701-a619-40d4-a351-992255000e25.png)

**Comment by NathanFarmer** [comment]
Thank you for opening this issue @cr4zy-C! As we discussed in Slack, if you would like to work on a contribution for this you can start by reviewing [this series of docs](https://docs.greatexpectations.io/docs/contributing/contributing). I believe the changes will be made starting [at this line](https://github.com/great-expectations/great_expectations/blob/67e6fbf25bbb3ca5a0e2a5c6e8320c5baaf6ddb2/great_expectations/expectations/core/expect_column_bootstrapped_ks_test_p_value_to_be_greater_than.py#L34). You will be able to find other working examples in [this directory](https://github.com/great-expectations/great_expectations/tree/develop/great_expectations/expectations/core).

**Comment by AFineDayFor** [comment]
Howdy @cr4zy-C 🎉 

I'm going to close this due to it's age. If you would like, provide a contribution we encourage you to do so 😄
