### ISSUE TITLE
`\n` and `,` transposed in notebook generation

### ISSUE THREAD

**Issue by mccalluc** [fivetran/great_expectations#3451]
**Describe the bug**
Following the tutorial, in the Jupyter notebook, the `ignored_columns` list has commas at the start of the line.
Probably just transpose [here](https://github.com/great-expectations/great_expectations/blob/c49e533c012c275a791fce09df207d2bd7126780/great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py#L74-L77) to fix:

```diff
-            f'    "{column_name}"\n,' for column_name in self.validator.columns()
+            f'    "{column_name}",\n' for column_name in self.validator.columns()
```

**To Reproduce**
1. Follow the tutorial.
2. In the jupyter notebook, notice the formatting for the `ignored_columns`.

**Expected behavior**
Generated code in notebooks should follow normal formatting conventions.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 
   - superconductive/ge_tutorials @ 5db831a92af51f77dde19723a81a2cea92e2a756
   - great-expectations==0.13.35

**Additional context**
Mentioned this when talking with Ortal on September 24: Might already be filed or handled somewhere else.

**Comment by NathanFarmer** [comment]
Hi @mccalluc! Thank you for opening this issue. Would you be interested in contributing a PR for this minor change?

**Comment by NathanFarmer** [comment]
Hi @mccalluc! I was unable to reproduce this issue. Are you referring to the `ignored_columns` in the [profiling step](https://docs.greatexpectations.io/docs/tutorials/getting_started/create_your_first_expectations)? My notebook looks like this:

```
ignored_columns = [
    "vendor_id",
    "pickup_datetime",
    "dropoff_datetime",
    "passenger_count",
    "trip_distance",
    "rate_code_id",
    "store_and_fwd_flag",
    "pickup_location_id",
    "dropoff_location_id",
    "payment_type",
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount",
    "congestion_surcharge",
]
```

**Comment by mccalluc** [comment]
huh: curious. If it's really useful, I can start it up again and grab the exact text I see, but just looking at the code, `\n,` would print a newline and then the comma, unless I'm confused. Maybe different execution paths or different code versions?

**Comment by NathanFarmer** [comment]
Hi @mccalluc! I figured out where you are seeing this now that I followed the tutorial all the way through. It only shows up when you chose the "profiler" option 3 while creating an Expectation Suite. If you could update the change log in your PR I can merge this into `develop`.
