### ISSUE TITLE
[DOCS] fix How to add a Validation Operator yaml snippets

### ISSUE THREAD

**Issue by jdalfons** [fivetran/great_expectations#3456]
**Describe the bug**
In the docs for [How to add a Validation Operator](https://docs.greatexpectations.io/docs/guides/validation/how_to_add_a_validation_operator/) this doc have a problem to show the yaml.

![imagen](https://user-images.githubusercontent.com/25759070/134995563-0c6a4451-d8d0-4cd7-b8f4-c751ac4067e1.png)

PR #3455

**Comment by NathanFarmer** [comment]
Hi @halcolo! Thank you for opening this issue. I have requested some changes on the PR before it can be merged.

**Comment by Rachel-Reverie** [comment]
Given PR #3734 this issue is no longer relevant to the most up to date documentation, so I am going to close it for now.  However, thank you @halcolo for bringing it to our attention so that we could update the V3 documentation to reflect the current best practices!
