### ISSUE TITLE
Creating a new datasource with snowflake fails if query parameters are left blank

### ISSUE THREAD

**Issue by vatsal2293** [fivetran/great_expectations#3458]
**Describe the bug**
When creating a new sqlalchemy datasource with snowflake using the notebook provided, I am required to add a few parameters to make the datasource connection like `host`, `username`, `database` etc. Among these parameters, `schema`, `warehouse` and `role` are supposedly optional and would be treated as None if left blank. When I left them blank the `example_yaml` shown below has a `query` key with `schema`, `warehouse` and `role` having null values.

Now when the `sqlalchemy.engine.url.create()` function is called using this query the `_str_dict()` assertion call fails as the "Query dictionary values must be strings or sequences of strings"

**To Reproduce**
1. Run `great_expectations --v3-api datasource new`
2. Select `Relational Database (SQL)` and `Snowflake` in the next steps and follow along till the datasource_new notebook is created
3. In the third cell add `host`, `username` and `database` but leave `schema`, `warehouse` and `role` empty. 
4. `context.test_yaml_config(yaml_config=example_yaml)` call should error out. 

**Expected behavior**
`query` dictionary should be formatted correctly before calling `sqlalchemy` such that the above call does not error out.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.35

**Comment by talagluck** [comment]
Thanks for raising this issue, @vatsal2293! We will review this issue and be in touch soon.

**Comment by NathanFarmer** [comment]
Hi @vatsal2293! This issue has been addressed by PR #3543. The direction provided by the comments has been updated to clarify for the user that they should remove the optional key from the `example_yaml` string if the parameter is not being used.
