### ISSUE TITLE
Fail to automatically create Expectation Suite with snowflake database

### ISSUE THREAD

**Issue by vatsal2293** [fivetran/great_expectations#3459]
**Describe the bug**
When a datasource connection with snowflake is created without the optional `query` parameters, the automatic creation of an Expectation Suite fails with the following error:

`(snowflake.connector.errors.ProgrammingError) Cannot perform CREATE TEMPTABLE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
[SQL: CREATE OR REPLACE TEMPORARY TABLE ge_tmp_9e41b647 AS SELECT * 
FROM dbo.betfact 
WHERE true]
(Background on this error at: https://sqlalche.me/e/14/f405)`

**To Reproduce**
1. Create a new datasource using snowflake following the steps here https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/database/snowflake/
2. Run `great_expectations --v3-api suite new`
3. Select `3. Automatically, using a profiler` and the snowflake db datasouce
4. Select any table in the datasource and name the expectations suite
5. See the above error

**Expected behavior**
Should be able to automatically profile a snowflake db table

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.35

**Comment by talagluck** [comment]
Thanks for raising this issue, @vatsal2293! We will review this issue as well and be in touch soon.

**Comment by NathanFarmer** [comment]
Hi @vatsal2293! I have reproduced this error when selecting options 2 or 3 if a schema is not set in the datasource:
```
How would you like to create your Expectation Suite?
    1. Manually, without interacting with a sample batch of data (default)
    2. Interactively, with a sample batch of data
    3. Automatically, using a profiler
```

Can you confirm that your datasource does not have a schema explicitly set in `great_expectations.yml`? In the meantime, I am working on a bug fix.

**Comment by NathanFarmer** [comment]
Hi @vatsal2293! Again, thanks for opening this issue. For the time being, we are no longer describing these Snowflake parameters as optional, and the Jupyter Notebook comments are being removed by PR #3639. If you still prefer not to set a schema in the `datasource`, you may be able to work around this by adding the option `create_temp_table: False` to your `datasource` configuration under `execution_engine`.

If you feel you still need the option to leave the schema unset in your `datasource` configuration and `create_temp_table: False` is not sufficient to solve your issue, feel free to open a new issue outlining your use case and describing this as a feature request.
