### ISSUE TITLE
Adding Sort param to concat breaks pandas 0.20.3 compatability

### ISSUE THREAD

**Issue by datariot** [fivetran/great_expectations#346]
Running 0.4.3 against pandas 0.20.3 I ran into the following error:

```
1079         expected_column = pd.Series(partition_object['weights'], index=partition_object['values'], name='expected') * len(column)
   1080         # Join along the indices to allow proper comparison of both types of possible missing values
-> 1081         test_df = pd.concat([expected_column, observed_frequencies], axis=1, sort=True)
   1082 
   1083         na_counts = test_df.isnull().sum()

TypeError: concat() got an unexpected keyword argument 'sort'
```

Which lead me to the following change:

https://github.com/great-expectations/great_expectations/commit/6c008899d803cd58301b0992f8a9b654564f9d22

that seems incompatible with pandas 0.20.3 which is the current minimum requirement:
http://pandas.pydata.org/pandas-docs/version/0.20/generated/pandas.concat.html

**Comment by jpcampb2** [comment]
@datariot Thank you for flagging this issue! I've just created a PR to address it--turns out there was an underlying issue with the travis configuration that meant the full version matrix wasn't being properly tested, so there were several related issues to fix.
