### ISSUE TITLE
Expectation run in Airflow very slow

### ISSUE THREAD

**Issue by carlsonp** [fivetran/great_expectations#3461]
**Describe the bug**
I'm using Airflow and the [airflow-provider-great-expectations](https://github.com/great-expectations/airflow-provider-great-expectations) operator to run some expectations.  When I run the expectation via the Jupyter notebook it works fine and runs immediately:

```
great_expectations suite edit myexpectation
```

However, when I run them via the operator in Airflow, it takes about 30 minutes:

```
some naming content removed...

[2021-09-27 02:31:44,126] {taskinstance.py:1114} INFO - Executing <Task(GreatExpectationsOperator): > on 2021-09-26T00:00:00+00:00
[2021-09-27 02:31:44,133] {standard_task_runner.py:52} INFO - Started process 31882 to run task
[2021-09-27 02:31:44,137] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', '', '', '2021-09-26T00:00:00+00:00', '--job-id', '122425', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/', '--cfg-path', '/tmp/tmp2oie767i', '--error-file', '/tmp/tmp94uvz8cn']
[2021-09-27 02:31:44,139] {standard_task_runner.py:77} INFO - Job 122425: 
[2021-09-27 02:31:44,180] {logging_mixin.py:109} INFO - Running <TaskInstance:  2021-09-26T00:00:00+00:00 [running]> on host 9e70e96795a3
[2021-09-27 02:31:44,232] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=
AIRFLOW_CTX_DAG_ID=
AIRFLOW_CTX_TASK_ID=
AIRFLOW_CTX_EXECUTION_DATE=2021-09-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-26T00:00:00+00:00
[2021-09-27 02:31:44,232] {great_expectations.py:161} INFO - Ensuring data context exists...
[2021-09-27 02:31:44,233] {great_expectations.py:163} INFO - Data context does not exist, creating now.
[2021-09-27 02:31:44,328] {data_context.py:602} INFO - Usage statistics is disabled; skipping initialization.
[2021-09-27 02:31:44,349] {great_expectations.py:166} INFO - Running validation with Great Expectations...
[2021-09-27 02:31:44,434] {checkpoint.py:583} INFO - Setting run_name to: 20210927T083144.434835Z
[2021-09-27 02:31:44,442] {data_asset.py:646} INFO - 	7 expectation(s) included in expectation_suite.
[2021-09-27 03:04:33,557] {great_expectations.py:235} INFO - Validation with Great Expectations successful.
[2021-09-27 03:04:33,582] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=, task_id=, execution_date=20210926T000000, start_date=20210927T083144, end_date=20210927T090433
[2021-09-27 03:04:33,662] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-09-27 03:04:33,684] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

This issue of taking 30 minutes is fairly consistent across all the Great Expectation checks I'm running.  It does not appear to be specific to a certain dataset.  I'm using the standard Pandas library to load in a `.feather` file.  The feather files are small, most are only a few MB.

Does anyone have suggestions on what this might be or how to trace down the issue?

**To Reproduce**
* Not really reproducible

**Expected behavior**
The expectation run in Airflow should execute much quicker.

**Environment (please complete the following information):**
 - Operating System: Linux (services via docker-compose)
 - Great Expectations Version: 0.13.35
 - airflow-provider-great-expectations: 0.0.8
 - airflow: 2.1.4

**Additional context**

**Comment by talagluck** [comment]
Thanks for raising this issue, @carlsonp! This definitely doesn't sound like it's working correctly. Some questions:
- How are you running the validation with the Airflow operator? 
- Are you using a checkpoint? 
- Would you mind running a checkpoint manually (not using Airflow), and seeing whether that takes a long time? 
- Are you able to share your Airflow dag (removing any sensitive information)?

I'm trying to understand whether this is an issue with the Airflow operator, or potentially an issue with .feather files and checkpoints.

**Comment by carlsonp** [comment]
Thanks for responding.

Here is the Airflow DAG code.  I've removed some of the other tasks and bits that are likely not relevant.

```
import pathlib, sys, json
from pathlib import Path
from datetime import datetime, timezone
from pprint import pprint
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.models.connection import Connection
from airflow.utils.dates import days_ago
from airflow import AirflowException
from airflow.exceptions import AirflowSkipException
from datetime import timedelta
from airflow.hooks.base_hook import BaseHook
import pandas as pd
from great_expectations_provider.operators.great_expectations import GreatExpectationsOperator
import great_expectations as ge
sys.path.append('/opt/airflow/dags/greatexpdatacentral/')

# https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/index.html#airflow.models.BaseOperator
default_args = {
    'owner': '',
    'depends_on_past': False,
    'email': [''],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 0,
    'retry_delay': timedelta(minutes=60)
}

dag = DAG(
    'database-greatexp',
    default_args=default_args,
    description='runs data quality checks via Great Expectations',
    schedule_interval='@daily',
    start_date=days_ago(2),
    max_active_runs=1, # how many DAG executions can run at once
    concurrency=3 # how many tasks to spin up at once
)

databasename = "database"

for table in getTableList():
 <snip, task is defined>

    my_ge_task = GreatExpectationsOperator(
        task_id='ge_' + str(databasename) + "." + str(table),
        expectation_suite_name='database_'+str(table),
        batch_kwargs={
            'path': '/cache/database_'+str(table)+'.feather',
            'datasource': 'database',
            'data_asset_name': 'database_' + str(table)
        },
        data_context_root_dir='/opt/airflow/great_expectations/',
        dag=dag
    )

    task >> my_ge_task
```

I'm not sure internally how the `GreatExpectationsOperator` works.  It does say in the [README](https://github.com/great-expectations/airflow-provider-great-expectations/blob/main/README.md): _"This operator has been updated to use Great Expectations Checkpoints instead of the former ValidationOperators."_  When I shell into the running container, the `checkpoints` folder is empty.

I tried creating a checkpoint on my local machine using the [instructions](https://docs.greatexpectations.io/docs/tutorials/getting_started/validate_your_data) and corresponding Jupyter notebook that gets created.  However, I ran into trouble.  I did see that if you edit the expectation suite, at the very bottom of the Jupyter notebook it generates, it looks like it's creating some sort of temp checkpoint:

```
batch.save_expectation_suite(discard_failed_expectations=False)

results = LegacyCheckpoint(
    name="_temp_checkpoint",
    data_context=context,
    batches=[
        {
          "batch_kwargs": batch_kwargs,
          "expectation_suite_names": [expectation_suite_name]
        }
    ]
).run()
validation_result_identifier = results.list_validation_result_identifiers()[0]
context.build_data_docs()
context.open_data_docs(validation_result_identifier)
```

I ran these Jupyter notebooks that let you modify and run validations on the expectations on a couple feather files and they all ran within a few seconds.

Given the naming above, is there a "legacy" version of the checkpoints as compared to a newer version?

**Comment by carlsonp** [comment]
I think we were able to resolve this issue.  The problem was we had about 90 tables, each had likely more than 60 JSON validation results on the filesystem.  For some reason, clearing these away dropped the runtime back to one second.  I've thus moved to using [Postgresql for the validation store](https://docs.greatexpectations.io/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_to_postgresql).  I'm still a little surprised that it was taking this long loading/parsing JSON but hopefully Postgresql and a true database backend will be more reliable and faster in the future.  Appreciate the help.

**Comment by talagluck** [comment]
Hi @carlsonp - thanks so much for following up with the update.

It doesn't surprise me that the quantity of validation results led to long runtimes - I believe this is less about loading/parsing the JSON and more about rendering the individual sites on Data Docs (since each Validation will get its own site). This is a known bottleneck that we're hoping to fix soon (though we would like a community contribution here as well)! There is also [this workaround](https://discuss.greatexpectations.io/t/what-does-the-validation-results-limit-option-in-data-docs-limit/310), which may be helpful in the future.

I'd be interested to know whether moving to Postgresql for the validation store makes a difference. If you are willing, please post your findings here!
