### ISSUE TITLE
Support for compound and nested rules

### ISSUE THREAD

**Issue by ankit018** [fivetran/great_expectations#347]
Hi

Wanted to check how we can apply compound and nested rules using great expectations.

Some examples:
1. WHEN (Column_A_value == 'A') AND ( Column_B_value in SET ['X','Y','Z'])
2. WHEN (Column_A_value == 'A') AND ( Column_B_Value NOT NULL AND Column_B_value IN ('X','Y','Z'))
3. WHEN (Column_A_value == 'A') AND ( Column_B_Value =='B' AND Column_C_value IN ('X','Y','Z'))
4. 3. WHEN (Column_A_value == 'A') AND ( Column_B_Value =='B' OR Column_C_value IN ('X','Y','Z'))

Note: These checks are still at roe level. Do you suggest we create custom functions to apply such rules.

Thanks

Ankit

**Comment by abegong** [comment]
Great question!

You should be able to create these expectations using `expect_column_pair_values_to_be_in_set`. Will that work?

Check out the docs [here](https://great-expectations.readthedocs.io/en/latest/glossary.html#column-pairs) and [here](https://great-expectations.readthedocs.io/en/latest/dataset_module.html#great_expectations.dataset.base.Dataset.expect_column_pair_values_to_be_in_set) for more info.

**Comment by abegong** [comment]
hm. On closer inspection, `expect_column_pair_values_to_be_in_set` will cover 1 and 2, but not 3 and 4 since they reference a third column...
