### ISSUE TITLE
[DOCS] Links to docs from google may add a trailing slash that break relative links

### ISSUE THREAD

**Issue by edjoesu** [fivetran/great_expectations#3479]
**Describe the bug**
Documentation links from google may add a trailing slash that break relative links

( this was the reason for my mistaken pull request https://github.com/great-expectations/great_expectations/pull/3410 ) 

**To Reproduce**
1. Go to 'https://www.google.com/search?q=great+expectations+new+suite+rule+based+profilers'
2. Click on the top link
3. Click the bottom link in the 'Prerequisites' section
4. The page 404s. 
5. Navigate to the same page from the sidebar 
6. The link is fine

**Comment by NathanFarmer** [comment]
Thanks for opening this issue @edjoesu! From our Slack conversation, it sounds like this might be affecting all relative links in the documentation. We will take a look to see if this is the case and follow up soon.

**Comment by kyleaton** [comment]
@petermoyer does this have anything to do with any redirects you've set?

**Comment by AFineDayFor** [comment]
howdy @edjoesu, thanks for raising this 🎉 

This has been addressed, and we're going to go ahead and close this issue. thank you very much for bringing it to us.
