### ISSUE TITLE
Evaluation Parameters | Configuration validation failure | min_value & max_value Expectations

### ISSUE THREAD

**Issue by BilalZahid22** [fivetran/great_expectations#3486]
**Describe the bug**
While Using Evaluation Parameters with the expectations having both min_value & max_value parameters , the internal configuration validation fails. As min and max values are technically dictionaries(When using evaluation parameters i.e. `min_value={"$PARAMETER": "trunc(upstream_row_count * 0.9)"}` ), so a dictionary comparison problem occurs. 
`TypeError: '>' not supported between instances of 'dict' and 'dict'`

The trace of the problem is as follows: 

> validator.expect_table_row_count_to_be_between(
>   File "...\venv\lib\site-packages\great_expectations\validator\validator.py", line 281, in inst_expectation
>     raise err
>   File "...\venv\lib\site-packages\great_expectations\validator\validator.py", line 228, in inst_expectation
>     expectation = expectation_impl(configuration)
>   File "...\venv\lib\site-packages\great_expectations\expectations\expectation.py", line 137, in __init__
>     self.validate_configuration(configuration)
>   File "...\venv\lib\site-packages\great_expectations\expectations\core\expect_table_row_count_to_be_between.py", line 106, in validate_configuration
>     self.validate_metric_value_between_configuration(configuration=configuration)
>   File "...\venv\lib\site-packages\great_expectations\expectations\expectation.py", line 1122, in validate_metric_value_between_configuration
>     if min_val is not None and max_val is not None and min_val > max_val:
> TypeError: '>' not supported between instances of 'dict' and 'dict'

**To Reproduce**
1. Use this example with validator [GE Example](https://docs.greatexpectations.io/docs/reference/evaluation_parameters)
2. Sample Code
3. 

> batch_request = {
>         "datasource_name": datasource_name,
>         "data_connector_name": data_connector_name,
>         "data_asset_name": data_asset_name
>     }
> 
> validator = context.get_validator(
>         batch_request=BatchRequest(**batch_request),
>         expectation_suite_name=expectation_suite_name,
>     )
> 
> validator.set_evaluation_parameter("upstream_row_count", 10)
>         validator.expect_table_row_count_to_be_between(
>             min_value={"$PARAMETER": "trunc(upstream_row_count * 0.9)"},
>             max_value={"$PARAMETER": "trunc(upstream_row_count * 1.1)"},
>             result_format={'result_format': 'BOOLEAN_ONLY'})

**Expected behavior**
validate_metric_value_between_configuration function should handle dictionaries to tackle evaluation parameters or should remove min_value > max_value check 

**Environment (please complete the following information):**
 - Operating System: [Windows 10]
 - Great Expectations Version: [0.13.35]

**Additional context**

**Comment by talagluck** [comment]
Thanks for opening this issue, @BilalZahid22! We will review and be in touch soon.
