### ISSUE TITLE
Validate Expectations in "bulk add" scenario, and on Checkpoint load

### ISSUE THREAD

**Issue by dbeswick-bupa** [fivetran/great_expectations#3494]
**Is your feature request related to a problem? Please describe.**
My platform is Databricks. While authoring an Expectation Suite, I tried the approach I see in the GE docs here: https://docs.greatexpectations.io/docs/guides/expectations/how_to_create_and_edit_expectations_based_on_domain_knowledge_without_inspecting_data_directly

I'm ultimately running the results via a Checkpoint.

It almost works well for me, but the main drawback is that there's no validation of Expectations. If you supply a non-existent Expectation or omit some field that an Expectation demands, then the Checkpoint runs and reports success, and that it ran zero expectations. 

I imagine that I would also run into this problem if I manually modified the Expectation Suite's json, but I made a mistake. If that's right, it could also create some nasty "silent" bugs if a code update changes the contract for an Expectation in certain ways (should usually not happen, but can happen.)

**Describe the solution you'd like**
Firstly, that there be a way of validating Expectations given just an ExpectationConfiguration object.

Secondly, that there be a way to validate Checkpoints, or that there be some mode where Checkpoints' Expectations are validated before running.

**Describe alternatives you've considered**
From my reading of the code, the only way to validate Expectations is to instantiate a Validator object. I'm then currently doing the following:

```
suite = context.create_expectation_suite("test", overwrite_existing=True)
validator = Validator(None, data_context=context, expectation_suite=suite, interactive_evaluation=False)
validator.expect_column_values_to_be_in_set(column="My_Column", value_set=["A", "B", "C"])
suite.add_expectation(validation_result.expectation_config)
context.save_expectation_suite(suite)
```

**Additional context**
I may have some bandwidth to work on solutions to the issues I raise, so if you would like me to look at that, please feel free to point me in the direction of any design you have in mind to implement this request. This also applies to any issue I raise, in general. Thank you!

**Comment by talagluck** [comment]
Thanks for opening this issue, @dbeswick-bupa! We will review and be in touch soon.

**Comment by talagluck** [comment]
Hi @dbeswick-bupa - thanks again for this, and apologies for delays.

Currently, we have two primary ways of creating Expectation Suites - interactive (using a Validator, which contains a Batch of data) and non-interactive (writing Expectations without using a Validator with a Batch of data).

Additionally, `ExpectationConfiguration` objects have a `.validate()` method, which takes a Validator containing some data. Do any of these match your use case? Could you explain a bit more about what you are seeking here that is not currently possible?

**Comment by dbeswick-bupa** [comment]
Hello there, no worries at all about the delay.

I'm casting my mind back a bit here, but I think this issue is mostly about validating parameters to expectations. When you use a Validator, you get instant feedback if you miss out or misname a parameter, but with the ExpectationConfiguration objects, you don't.

Say that I had created an ExpectationConfiguration non-interactively, and the Expectations I gave had invalid parameters. You don't get an error when creating the config, and from memory, when you actually run the config via a Checkpoint (when data should be available) you also don't get an error. The checkpoint just runs zero Expectations and returns success. 

From my point of view, this is a problem because it seems it can lead to silent errors when Expectations with config errors are run, or if the contract of an Expectation changes. You might not always run "validate" in between a config change and one of these events happening.

I will try to get another example for you shortly...

**Comment by dbeswick-bupa** [comment]
Apologies for this one, I have re-tested and have found that in the scenario I described an exception is recorded in the checkpoint results when the checkpoint is actually run. I think that the behaviour I was seeing was due to me not properly saving the Suite before running the checkpoint, and I mis-read the code.

You can close this issue, thanks!

**Comment by talagluck** [comment]
Got it - thanks for the follow-up, @dbeswick-bupa!
