### ISSUE TITLE
Jinja for expectations

### ISSUE THREAD

**Issue by pixie79** [fivetran/great_expectations#3495]
I would like to be able to use Jinja within my expectations to allow them to be dynamic.

Something like the following would be ideal for defining Jinja, but it is evaluated only when the expectation runs against the data. 

```
expectation_configuration = ExpectationConfiguration(**{
  "meta": {},
  "kwargs": {
    "column": "date_closed",
    "max_value": **{{ time.now + time.delta(months=-24, weeks=-1) }}**,
    "min_value": **{{ time.now. }}**,
    "parse_strings_as_datetimes": true
  },
  "expectation_type": "expect_column_values_to_be_between"
})
```

please note '**' only added to highlight where the Jinja is :)

**Comment by talagluck** [comment]
Thanks for opening this issue, @pixie79! This is essentially what EvaluationParameters are (though they do not use Jinja). We currently have a PR open with the specific NOW/time functionality that you are describing as well, and expect to merge this fairly soon (#3525).

I'm going to close this for now, but please feel free to reopen if there is functionality here that you would like to see not currently taken care of by Evaluation Parameters.
