### ISSUE TITLE
expect_column_pair_values_A_to_be_greater_than_B expectation name is case-sensitive

### ISSUE THREAD

**Issue by shpolina** [fivetran/great_expectations#3506]
**Describe the bug**

`expect_column_pair_values_A_to_be_greater_than_B` appears in [the documentation](https://docs.greatexpectations.io/docs/reference/glossary_of_expectations#multi-column) with capital `A` and `B` but in v3 it only works if low case name is used, aka `expect_column_pair_values_a_to_be_greater_than_b`.

**To Reproduce**
1. Try using `expect_column_pair_values_A_to_be_greater_than_B` expectation
2. Get error `TypeError: 'NoneType' object is not callable`

**Expected behavior**
Not sure if the documentation needs to be fixed or the name handling should be case insensitive. Need input from GE core team.

**Workaround**
Use `expect_column_pair_values_a_to_be_greater_than_b` instead

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version:  0.13.37

**Comment by talagluck** [comment]
Thanks for opening this, @shpolina! We will review and be in touch soon.

**Comment by austiezr** [comment]
Hey @shpolina! Thanks for surfacing this; we've had an opportunity to discuss and review, and we feel the expectation name here should be case insensitive. Is this something you'd be interested in contributing towards? We'd be happy to provide guidance and review if so!

**Comment by austiezr** [comment]
Hey @shpolina! Are you able to share an example of the workflow throwing this error? I've been unable to reproduce this issue on my end so far.

**Comment by shpolina** [comment]
My workflow is including this expectation in a suite and then validating using `run_checkpoint()`.
It's been a while since I opened this issue so it is possible that something have changed since then.

**Comment by shpolina** [comment]
@austiezr I had a chance to try it again and the issue is still reproducible on latest 0.13

I just used an expectation suite with a single expectation

This fails:
```
{
      "expectation_type": "expect_column_pair_values_A_to_be_greater_than_B",
      "kwargs": {
        "column_A": "mostrecentevent",
        "column_B": "firstevent"
      }
}
```

This works:
```
{
      "expectation_type": "expect_column_pair_values_a_to_be_greater_than_b",
      "kwargs": {
        "column_A": "mostrecentevent",
        "column_B": "firstevent"
      }
}
```

**Comment by austiezr** [comment]
Hey @shpolina ! Thank you again for raising this; our docs have been reworked and the expectation gallery now populates directly from the expectation file, which should resolve the discrepancy between docs and expectation.
