### ISSUE TITLE
pip install great_expectations does not work on an M1 Mac

### ISSUE THREAD

**Issue by donaldheppner** [fivetran/great_expectations#3511]
**Describe the bug**
pip install great_expectations fails on an M1 Mac. scipy and its dependency numpy need to be compiled as part of the installation.

**To Reproduce**
1. Run `pip install great_expectations` on an M1 Mac.

**Expected behavior**
The installation is successful

**Environment (please complete the following information):**
 - MacOS BigSur, M1 / Apple Silicon
 - Great Expectations Version:13.x

**Additional context**
Challenges installing scipy on an M1 via pip are widely reported; I have documented a work-around to resolve this issue

**Comment by xtomflo** [comment]
@donaldheppner where can one find the workaround documentation?

I went ahead using pre-built wheel of scipy and installation was successful, but subsequent run fails as below. 

> Traceback (most recent call last):
>   File "/opt/homebrew/bin/great_expectations", line 5, in <module>
>     from great_expectations.cli import main
>   File "/opt/homebrew/lib/python3.9/site-packages/great_expectations/__init__.py", line 7, in <module>
>     from great_expectations.data_context import DataContext
>   File "/opt/homebrew/lib/python3.9/site-packages/great_expectations/data_context/__init__.py", line 1, in <module>
>     from .data_context import BaseDataContext, DataContext, ExplorerDataContext
>   File "/opt/homebrew/lib/python3.9/site-packages/great_expectations/data_context/data_context.py", line 25, in <module>
>     from great_expectations.checkpoint import Checkpoint, LegacyCheckpoint, SimpleCheckpoint
>   File "/opt/homebrew/lib/python3.9/site-packages/great_expectations/checkpoint/__init__.py", line 15, in <module>
>     from .checkpoint import Checkpoint, LegacyCheckpoint, SimpleCheckpoint
>   File "/opt/homebrew/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 26, in <module>
>     from great_expectations.validator.validator import Validator
>   File "/opt/homebrew/lib/python3.9/site-packages/great_expectations/validator/validator.py", line 30, in <module>
>     from great_expectations.dataset import PandasDataset, SparkDFDataset, SqlAlchemyDataset
>   File "/opt/homebrew/lib/python3.9/site-packages/great_expectations/dataset/__init__.py", line 3, in <module>
>     from .dataset import Dataset
>   File "/opt/homebrew/lib/python3.9/site-packages/great_expectations/dataset/dataset.py", line 12, in <module>
>     from scipy import stats
>   File "/opt/homebrew/lib/python3.9/site-packages/scipy/__init__.py", line 153, in <module>
>     from scipy._lib._ccallback import LowLevelCallable
>   File "/opt/homebrew/lib/python3.9/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
>     from . import _ccallback_c
> ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/scipy/_lib/_ccallback_c.cpython-39-darwin.so, 2): no suitable image found.  Did find:
> 	/opt/homebrew/lib/python3.9/site-packages/scipy/_lib/_ccallback_c.cpython-39-darwin.so: mach-o, but wrong architecture
> 	/opt/homebrew/lib/python3.9/site-packages/scipy/_lib/_ccallback_c.cpython-39-darwin.so: mach-o, but wrong architecture

**Comment by donaldheppner** [comment]
Instructions that worked for me are now posted in our blog: https://greatexpectations.io/blog/m-one-mac-instructions/; I hope they work for you, please let me know if you continue to run into issues!
