### ISSUE TITLE
Getting Started guide requires setting datasource_name

### ISSUE THREAD

**Issue by donaldheppner** [fivetran/great_expectations#3512]
**Describe the bug**
The getting started guide requires we set the `datasource_name` to `data__dir`. This edit is repeated (through instructions) throughout the guide. It would be easier to get started if the guide used the default name of `my_datasource`.

**To Reproduce**
1. Go through the Getting Started guide, the rename instructions are located [here](https://docs.greatexpectations.io/docs/tutorials/getting_started/connect_to_data) under datasource new notebook, and repeated under "checkpoint new" notebook [here](https://docs.greatexpectations.io/docs/tutorials/getting_started/validate_your_data)

**Expected behavior**
Use the default datasource name of `my_datasource`

**Environment (please complete the following information):**
 - All

**Additional context**
None

**Comment by AFineDayFor** [comment]
Howdy @donaldheppner,

As this currently isn't an issue any longer, we're going to go ahead and close this. Thank you very very much for reporting it.
