### ISSUE TITLE
Similar transparent behavior for db schema configuration in V3 as in V2 API

### ISSUE THREAD

**Issue by frantakalab** [fivetran/great_expectations#3528]
**Is your feature request related to a problem? Please describe.**
I am connecting to a Postgres db that has the following structure using the cli:

- `schema1.table1`
- `schema2.table1`

In v3-api I am unable to select schema for the data asset on suite creation and therefore if I want to create a suite on `table1` I don't see which schema is being used. In v2-api I can use the standard notation of `schema_name.table_name` which is very easy to manage.

**Describe the solution you'd like**
Allow the same behavior as in v2: user can select data asset from a given database with `schema_name.table_name` notation.

**Describe alternatives you've considered**
I have tried to specify the default schema within the connstring or to add options parameter for psycopg2 into the datasource config (`options="-c search_path=default"`) but, I am told ([see the code](https://github.com/great-expectations/great_expectations/blob/fff3b5290d3a33dde02c12837373686f9077d2da/great_expectations/datasource/sqlalchemy_datasource.py#L324)), to set a default schema for the db user, which for me is both intransparent and inconvenient since I have many schemas in the same db I want to freely use within GE. What is the reason to have this managed on the db side?

**Additional context**
great_expectations, version 0.13.37

**Comment by z3z1ma** [comment]
Yes, I am having difficulties adapting the v3 api due to this exact constraint.

**Comment by talagluck** [comment]
Thanks @frantakalab and @z3z1ma! We will review and be in touch soon.

**Comment by talagluck** [comment]
Hi @frantakalab and @z3z1ma - I believe this was resolved by #3938, so I'm going to close this issue. Thanks!
