### ISSUE TITLE
Convenience method on ExpectationSuiteValidationResult to extract failed results

### ISSUE THREAD

**Issue by BenGale93** [fivetran/great_expectations#3531]
In great_expectations/data_context/data_context.py line 2538 it states:

"# TODO: This should be a convenience method of ValidationResultSuite"

The code below this extracts all the failed validation results from ExpectationSuiteValidationResult.

I've also found that in my project this convenience method would be useful. As such, if the maintainers agree, I'd like to implement this feature. I'm also opening this issue for discussion purposes on what the API should look like.

**Comment by talagluck** [comment]
Thanks for opening this and the corresponding PR, @BenGale93! We will review and be in touch soon.

**Comment by austiezr** [comment]
@BenGale93 Closing this out re: #3552; feel free to re-open if needed! Thank you for contributing!
