### ISSUE TITLE
GE has issues running on Azure Databricks cluster with ADLS Passthrough enabled

### ISSUE THREAD

**Issue by dbeswick-bupa** [fivetran/great_expectations#3538]
**Describe the bug**
This is kind of a tricky one.

Azure Databricks (and possibly the other flavours, I'm not sure) provide an option for "High Concurrency Clusters" called "ADLS Passthrough".

https://docs.microsoft.com/en-us/azure/databricks/security/credential-passthrough/adls-passthrough

This mode is used to allow users to authenticate with ADLS Gen 2 Storage Accounts using the same credentials that they logged in to Databricks with. Only Python and SQL statements may be executed and there are a number of other restrictions designed to ensure that users can't peek at each others' ADLS credentials.

Running the repro example results in this error:

`py4j.security.Py4JSecurityException: Constructor public org.apache.spark.SparkConf(boolean) is not whitelisted.`

Unfortunately, creating SparkConf instances is one feature that's restricted in this mode. `core.util.get_or_create_spark_application` is one place where this is done. No doubt creating Spark sessions with specific config is also disallowed. It seems there's no cluster config-based workaround for this behaviour, such as selectively allowing certain operations:

https://docs.microsoft.com/en-us/azure/databricks/security/credential-passthrough/adls-passthrough#--troubleshooting

If I find any other instances where GE has trouble with this feature enabled, then I'll update this bug.

**To Reproduce**
This should repro the error:

```
df = spark.createDataFrame([(1,)])

context = BaseDataContext(
    project_config=DataContextConfig(
      datasources={
        "databricks": DatasourceConfig(
          class_name="Datasource",
          execution_engine={
            "class_name": "SparkDFExecutionEngine"
          },
          data_connectors={
            "runtime": {
              "module_name": "great_expectations.datasource.data_connector",
              "class_name": "RuntimeDataConnector",
              "batch_identifiers": [
                "dummy"
              ]
          }
        }
      )},
    store_backend_defaults=FilesystemStoreBackendDefaults(root_directory="/tmp/ge")
  ))
print(context.get_available_data_asset_names())
```

**Expected behavior**
The above example should execute fine.

**Environment (please complete the following information):**
 - Databricks DBR 9.1 LTS
 - Great Expectations Version: 0.13.37

**Additional context**
GE can continue executing with this monkey-patch:

```
from great_expectations.execution_engine.sparkdf_execution_engine import SparkDFExecutionEngine

def patched_init(self, *args, persist=True, spark_config=None, force_reuse_spark_context=False, **kwargs):
  self._persist = persist
  self._spark_config = {}
  self.spark = spark
  azure_options = kwargs.pop("azure_options", {})
  self._azure_options = azure_options  
  
  super(SparkDFExecutionEngine, self).__init__(*args, **kwargs)
  
  self._config.update(
      {
          "persist": self._persist,
          "spark_config": spark_config,
          "azure_options": azure_options,
      }
  )

SparkDFExecutionEngine.__init__ = patched_init
```

**Comment by talagluck** [comment]
Thanks for opening this issue, @dbeswick-bupa! We will review and be in touch.

**Comment by kyleaton** [comment]
@dbeswick-bupa 

Would you mind submitting a PR with your proposed fix? I think that would help us get the ball rolling on our side.

**Comment by dbeswick-bupa** [comment]
Hello there Kyle,

I don't really have a PR to contribute at this stage -- the above is just a runtime "monkey patch" that might help others who run into the same problem, but it isn't a solution. It will no doubt break many non-Databricks cases.

I can look at some possible fixes, they'll no doubt involve adding a parameter to SparkDFExecutionEngine that skips the use of the SparkConf object, or probably better, allows users to pass in an existing SparkSession. But if the devs would like to add some information about the other parts of the system that might be relying on the current behaviour, then that would help.

**Comment by kyleaton** [comment]
Hi @dbeswick-bupa,

Sorry for the delay in response I just wanted to let you know that we've added this to our backlog to address and I should have more information on how we'll proceed later this week.

Thanks for your patience :)

**Comment by dbeswick-bupa** [comment]
Hi Kyle, no worries at all.

To be honest, I'm not sure how crucial this kind of support will be as the ADLS credential passthrough mode has some fairly large drawbacks depending on your use case, such as a maximum one hour job run time. These restrictions are detailed in the link I sent in the description.

We are still not clear to what extent we'll make use of the passthrough feature, but I thought I would note this issue anyway. Just some thoughts to help you prioritise the task.

**Comment by dbeswick-bupa** [comment]
This one isn't relevant to us anymore, thanks.

**Comment by kujaska** [comment]
While this issue is not reproducible on Databricks Community 11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12),
it **is reproducible** on AWS Databricks 12.2 LTS (includes Apache Spark 3.3.2, Scala 2.12)
with great_expectations-0.16.5-py3-none-any.whl 

Many thanks to @dbeswick-bupa - monkey-patch works!

Please consider merging the monkey-patch to core library...
