### ISSUE TITLE
great_expectations : expect_column_values_to_match_json_schema does not take json schema as input

### ISSUE THREAD

**Issue by abtpst** [fivetran/great_expectations#3545]
**Describe the bug**

expect_column_values_to_match_json_schema does not take json schema as input

**To Reproduce**
I am trying to invoke

`expect_column_values_to_match_json_schema` 

as per

https://legacy.docs.greatexpectations.io/en/latest/autoapi/great_expectations/dataset/dataset/index.html#great_expectations.dataset.dataset.Dataset.expect_column_values_to_match_json_schema

    jschema = {
            "type" : "object",
         "properties" : {
             "xyz" : {"type" : "string"}
         }
            }
    df_ge.expect_column_values_to_match_json_schema(column='abc',json_schema=jschema,row_condition="a=='1' and b=='2' and c=='3'",condition_parser='pandas')

however i got this error

    File "/some/path/lib/python3.7/site-packages/great_expectations/dataset/pandas_dataset.py", line 1554, in matches_json_schema
        val_json = json.loads(val)
      File "/usr/lib/python3.7/json/__init__.py", line 341, in loads
        raise TypeError(f'the JSON object must be str, bytes or bytearray, '
    TypeError: the JSON object must be str, bytes or bytearray, not dict

so i tried

    df_ge.expect_column_values_to_match_json_schema(column='abc',json_schema=json.loads(str(jschema)),row_condition="a=='1' and b=='2' and c=='3'",condition_parser='pandas')

but then i get
    

 
 
 
 

    df_ge.expect_column_values_to_match_json_schema(column='pg',json_schema=json.loads(str(pgschema)),row_condition="a=='1' and b=='2' and c=='3'",condition_parser='pandas')
      File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

how can i create a proper json object to feed to this method?

**Expected behavior**

ability to verify jsonschema via expect_column_values_to_match_json_schema

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.37

**Additional context**

**Comment by talagluck** [comment]
Hi @abtpst - thanks for asking this. We will review and be in touch with the configuration specifics shortly.

**Comment by talagluck** [comment]
Hi @abtpst - it appears that in order to properly configure this expectation, the json object will need to be wrapped in a double_string, like so:
```
jschema = "{
        'type' : 'object',
     'properties': {
         'xyz' : {'type' : 'string'}
     }
        }"
```

Note that this means that it will need to use single-quotation marks inside the json string.

**Comment by abtpst** [comment]
thanks @talagluck i tried the approach you suggested but i get the same errors

**Comment by abtpst** [comment]
@talagluck would it be possible to have a working example here? or in the docs

**Comment by talagluck** [comment]
Hi @abtpst - apologies for delays. I'm having trouble reproducing the issue with slightly different data. Here is my code:
```python
import pandas as pd
import datetime
import great_expectations as ge
import great_expectations.jupyter_ux
from great_expectations.checkpoint import LegacyCheckpoint
from great_expectations.data_context.types.resource_identifiers import (
    ValidationResultIdentifier,
)

df = pd.DataFrame({
      "w" : [2, 3, 4, 5, 6, 7, 8, 9, 10, None],
      "x" : ["{\"a\":1}", "{\"a\":2}", "{\"a\":3}", "{\"a\":4}", "{\"a\":5}", None, None, None, None, None]
    })

context = ge.data_context.DataContext()

expectation_suite_name = "json_schema_test"
suite = context.get_expectation_suite(expectation_suite_name)
suite.expectations = []

batch_kwargs = {
    "data_asset_name": "example",
    "dataset": df,
    "datasource":"v2_pandas"
}
batch = context.get_batch(batch_kwargs, suite)

json_schema = {
    "type": "object",
    "properties": {
            "a": {
              "type": "integer"
            }
          }
        }

batch.expect_column_values_to_match_json_schema("x", json_schema=json_schema)

```

**Comment by abtpst** [comment]
thanks @talagluck i will review the above

**Comment by talagluck** [comment]
Yes, you need to change the name of the `expectation_suite` with an `expectation_suite` that you have.

**Comment by abtpst** [comment]
@talagluck thanks, here is what i tried

```
import json
import pandas.io.json as pd_json
import great_expectations as ge
from great_expectations.profile.json_schema_profiler import JsonSchemaProfiler
import pandas as pd
import great_expectations.jupyter_ux
from great_expectations.checkpoint import LegacyCheckpoint
from great_expectations.data_context.types.resource_identifiers import (
    ValidationResultIdentifier,
)
in_df = pd_json.read_json(
  "./input/input.json",lines=True
).dropna()
req_df=in_df['request']
l=[]
for sr in req_df:
    l.append(pd.Series(sr['event']))
edf = pd.concat(l, axis=1).transpose()
context = ge.data_context.DataContext()

expectation_suite_name = "gexpTest"
suite = context.get_expectation_suite(expectation_suite_name)
suite.expectations = []

batch_kwargs = {
    "data_asset_name": "example",
    "dataset": edf,
    "datasource":"jpandas"
}
batch = context.get_batch(batch_kwargs,suite)

json_schema =  {
        "type" : "object",
     "properties" : {
         "xyz" : {"type" : "string"}
     }
        }

batch.expect_column_values_to_match_json_schema(column='abc',json_schema=jschema,row_condition="a=='1' and b=='2' and c=='3'",condition_parser='pandas')
print(batch.validate())
```

so this is essentially your sample code above but i have just replaced the dataframe with the one i am reading from the file

but i still get

```
 raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

note that i am able to run your sample (hardcoded dataframe)

**Comment by abtpst** [comment]
lastly, i am able to run other expectations with ease, such as

```
    batch.expect_column_to_exist(column=k)
    batch.expect_column_values_to_be_of_type(column=k,type_=v)
    batch.expect_column_values_to_be_in_set(
    column=k,
    value_set=t
)
```

**Comment by talagluck** [comment]
Hi @abtpst - thank you for sharing. I am not familiar with using Great Expectations on top of a pandas json object, and didn't think it was possible, so it's interesting to see that it works for other expectations. What do you get when you run `batch.head()`? Please make sure to remove any sensitive information, but I am especially curious about the json column that you are trying to validate.

**Comment by abtpst** [comment]
thanks @talagluck i see something like

        col1.      col2.       col3.       col4.       .............
0.     1.          {'a':'b','c':'d'}.        823658.         xvbvfy.      ............
1.     NaN.          {'z':'x','n':'m'}.        346.         utliiul.      ............
2.     2.          {'f':'g','h':'k'}.        908.         gmm.      ............
3.     1.          {'p':'o','h':'b'}.        94577.         bnoiefnben.      ............

**Comment by abtpst** [comment]
seems like the output from a regular dataframe

**Comment by abtpst** [comment]
also `type(batch)` is `<class 'great_expectations.dataset.pandas_dataset.PandasDataset'>`
and `batch.shape` is `(381,154)` in my case

**Comment by austiezr** [comment]
Hey @abtpst! I'm investigating this further; would you be able to try the following?

`batch.expect_column_values_to_match_json_schema(column='YOUR_COLUMN_NAME', json_schema={"properties": {"a": {"type": "string"}}})`

Similarly, can you try the same but with `json_schema={}`?

**Comment by austiezr** [comment]
Hey @abtpst! Closing this out for now as we've had some motion in the area and I've been unable to reproduce this issue with valid json schemas; if you are still experiencing this issue please feel free to re-open with further context!
