### ISSUE TITLE
[DOCS] buggy images make docs hard to read on Android

### ISSUE THREAD

**Issue by edjoesu** [fivetran/great_expectations#3559]
**Describe the bug**
On Android 11, Chrome 83.0, one of the sidebar images appears as ginormous and obscures large parts of the documentation. 

**To Reproduce**
1. Open the main documentation table of contents on this device/browser

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: [e.g. 0.13.2]

**Additional context**

**Comment by talagluck** [comment]
Hi @edjoesu - thanks for raising this! We will review and be in touch.

**Comment by kyleaton** [comment]
Hey @edjoesu. I was unable to replicate it. Do you think you could take some screenshots so I know where I should be testing and what images are getting in the way?
