### ISSUE TITLE
Add `expect_columns_to_be`

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#357]
Requires an exact, ordered match against a list of column names.

`expect_columns_to_be(["foo", "bar", "baz"])`

**Comment by jpcampb2** [comment]
Could the current `expect_table_columns_to_match_ordered_list` work for this?

**Comment by abegong** [comment]
Wait, we already have this?

**Comment by abegong** [comment]
Ha. This is the function I wrote during Strata. I had completely forgotten about it.
