### ISSUE TITLE
[DOCS] Carousel content, "not production"

### ISSUE THREAD

**Issue by donaldheppner** [fivetran/great_expectations#3572]
**Describe the bug**
The guide launched with a new suite notebook using the CLI highlights that this is "not a production suite" but does not articulate why it is not a product suite or what the differences might be between this suite and a production one.

This text is found on "slide 7" of the carousel shown when you create a new suite using the CLI command `suite new` (and found in the carousel_modal.j2 file). You can most easily get to this point by following the Getting Started Guide, "Creating Your First Expectations"

**To Reproduce**
1. Create a new expectation suite using the CLI `suite new` command as described in the getting started guide.
2. Execute the cells in the notebook to render and open the data docs.
3. Go through the carousel, "not production" note shows on slide 7

**Expected behavior**
If you tell me that something is "not production" you need to explain why (or at least link to an explanation). Unless it is absolutely necessary why we are advising users not use the output of the CLI, we should remove it. I would also expect that the CLI produces artifacts that are of production quality.

**Environment (please complete the following information):**
 - Great Expectations Version: 0.13.35

**Comment by kyleaton** [comment]
Suggested copy edit:

This Expectation Suite may not be a complete assessment of the quality of your data. You should review and edit the Expectations based on domain knowledge.

**Comment by donaldheppner** [comment]
resolved with https://github.com/great-expectations/great_expectations/pull/7456
