### ISSUE TITLE
GE get slow after add a BigQuery datasource

### ISSUE THREAD

**Issue by damon09273** [fivetran/great_expectations#3577]
**Describe the bug**
GE cli command or python script get slow after a BigQuery been added.

The Google settings (e.g credential, project) was been double checks.

**To Reproduce**
1. Add a BigQuery type datasource 
2. Running a cli command e.g great_expectations --v3-api checkpoint list
3. It will stuck at ```Using v3 (Batch Request) API``` and took at least 5 minutes to get the response.
4. Remove the BigQuery settings from `great_expectations.yml`
5. Running a cli command again and get response Immediately.

**Expected behavior**
The Response duration do not affected by a data source.

**Environment (please complete the following information):**
 - Linux, MacOS
 - Great Expectations Version: 0.13.38
 - airflow-provider-great-expectations: 0.0.8
 - pybigquery: 0.10.2
 - Gcloud SDK: 258.0.0

**Additional context**
It seems similar to https://github.com/great-expectations/great_expectations/issues/2771.

**Comment by ryperez** [comment]
I also have this issue. Currently, as I'm also using airflow, I just passed the data from BQ -> GCS -> downloaded on machine then do CSV validations there.

**Comment by talagluck** [comment]
Thanks for raising this @damon09273 and @ryperez! We will review and be in touch.

**Comment by damon09273** [comment]
The issue is gone after upgraded great-expectations to 0.13.41.

**Comment by talagluck** [comment]
Great - thanks so much for letting us know, @damon09273! Just to confirm, is that your experience as well, @ryperez?

**Comment by ryperez** [comment]
Yep! the issue is also gone on my end. @talagluck

**Comment by talagluck** [comment]
That's excellent - thanks for letting me know, @ryperez! I'll close this out for now then.
