### ISSUE TITLE
WinError 2 when editing suites

### ISSUE THREAD

**Issue by kc-garcia** [fivetran/great_expectations#3579]
**Describe the bug**
I can not edit suites in Jupyter notebooks, the command great_expectations suite edit [OPTION] gives me a WinError 2.

**To Reproduce**
After Congratulations! Great Expectations is now set up.
1. great_expectations suite edit [OPTION]
2. FileNotFoundError: [WinError 2] The system cannot find the file specified

**Expected behavior**
Open a new notebook to change the suite

**Environment (please complete the following information):**
 - Operating System: Windows
 - great_expectations, version 0.13.37

**Additional context**
![image](https://user-images.githubusercontent.com/80914099/138246824-6fda69b6-44ac-4adb-b164-23e9e4a4c5bc.png)

**Comment by talagluck** [comment]
Hi @kc-garcia - thanks for raising this! Silly question, but could you please confirm that you have a suite named `scenario_ge_demo` in your ExpectationsStore? Would you please paste the store part of your config here (taking care to remove any sensitive information)?

**Comment by talagluck** [comment]
Hi @kc-garcia - I'm going to close this for now, but if the issue persists, and you're able to provide more steps to reproduce, feel free to re-open.
