### ISSUE TITLE
[Docs] "Page not found" clicking on Expectation Glossary link on Expectations Reference

### ISSUE THREAD

**Issue by drewmck-superconductive** [fivetran/great_expectations#3582]
**Describe the bug**
On the [Expectations Reference page](https://docs.greatexpectations.io/docs/reference/expectations/expectations/), clicking the Expectations Glossary link is incorrect.

**To Reproduce**
1. Go to 'https://docs.greatexpectations.io/docs/reference/expectations/expectations/'
2. Click on 'Expectations Glossary'
3. See Page Not Found error

**Expected behavior**
User is sent to https://docs.greatexpectations.io/docs/reference/glossary_of_expectations/

**Comment by talagluck** [comment]
Thanks for opening this! It looks like this work has been done, so I'm going to close this.
