### ISSUE TITLE
Can't stop writing output to filesystem.

### ISSUE THREAD

**Issue by woods2021** [fivetran/great_expectations#3588]
I'm following the instructions here to validate some data entirely in memory. 

https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/in_memory/pandas

I am running Great Expectations in a Lambda function and I want to just process the output from the call to 

validator.validate() in the function, without writing anything to the file system.

It seems there is no way to do this?  Lambda functions will not allow me to write to the filesystem at run time.  

If I have missed something in the docs can someone point me in the right direction, it's a lot to navigate!

**Comment by talagluck** [comment]
Hi @woods2021 - thanks for asking this. Could you please confirm what you are seeing? I don't believe that `validator.validate()` should write to the filesystem, and when I test this out, that is what I am finding. it appears that `validator.validate()` just returns a json object without writing to the file system.

**Comment by talagluck** [comment]
Hi @woods2021 - I'm going to close this for now, but please feel free to re-open if this is still an issue, and you are able to provide more steps to reproduce.
