### ISSUE TITLE
Prefect RunGreatExpectationsValidation module can't run checkpoint created through notebook. 

### ISSUE THREAD

**Issue by samLozier** [fivetran/great_expectations#3609]
This error is coming from prefect, but I thought I'd share it here as well since it was my impression that the GE team helped with the prefect code and I'm unclear on wether the error is being caused by improper GE generated yml or non-working prefect code. 

Setup: 
- I'm new to GE and have been using notebooks to connect to a datasource, then a test suite. 
- I ran ```great_expectations --v3-api checkpoint new test_checkpoint```
- In the notebook, the final cell, `context.run_checkpoint(checkpoint_name=test_checkpoint)` executes as expected
- In prefect I try to run that same checkpoint:
```ge_validate = RunGreatExpectationsValidation(checkpoint_name="test_checkpoint", context_root_dir="./src/great_expectations/" )```

This results in a vague error: 
``` for batch in ge_checkpoint["batches"]:
TypeError: 'Checkpoint' object is not subscriptable
```

The error is coming from : 
https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/great_expectations/checkpoints.py line 246 and appears to be happening because the checkpoint yml that the notebook generates doesn't include a 'batches' field.

**Comment by talagluck** [comment]
Hi @samLozier - thanks for raising this issue! I believe the problem here is that the Prefect integration does not yet work with the V3 API of Great Expectations, though I believe there are plans in place to make that update.

**Comment by kenwade4** [comment]
This was fixed a couple months ago
