### ISSUE TITLE
Foreign key verification

### ISSUE THREAD

**Issue by afuetterer** [fivetran/great_expectations#361]
Hi,

the documentation mentions "[Foreign key verification and row-based accounting for ETL](https://great-expectations.readthedocs.io/en/latest/expectations.html?highlight=foreign)". Can you point me to the corresponding expectations or an example of a foreign key verification?

Thank you very much.

**Comment by abegong** [comment]
Good question. Can you describe your use case? There are a couple different ways to achieve FK verification...

**Comment by afuetterer** [comment]
I am not sure, if you support the verification across multiple csv files out of the box.

I have something like this in mind:

1) One csv contains information about studies.
`# studies.csv`

| name |
| --- |
| study_1 |

2) Another csv contains information about corresponding datasets.
`# datasets.csv`

| name | study |
| --- | --- |
dataset_1 | study_1 |
dataset_2 | study_1 |

I would like to verify that the entries for "study" in "datasets.csv" are defined in "studies.csv"

`# invalid_datasets.csv`

| name | study |
| --- | --- |
dataset_1 | study_1 |
dataset_2 | **study_2** |

The entry "study_2" is not defined in "studies.csv", so the foreign key verification should not be valid.

Is the example above alright? 

I think one could read the study names from the "name" column in "studies.csv" and then use "expect_column_values_to_be_in_set" on those study names. 

But as you wrote in the documentation about Foreign key verification I wanted to make sure I did not miss an expectation that is better suited.

Thank you.

**Comment by abegong** [comment]
Yes, what you're doing makes sense.

You might also want to use `expect_column_values_to_be_unique` on the `studies.name` column.

Another approach would be to do an outer merge on the two tables, then apply `expect_column_values_to_not_be_null` to the keys in the merged tables.

Eventually, we plan to add more direct expectations, like `expect_column_A_to_be_a_foreign_key_to_column_B`. This will probably use grouped expectations, as imaged here: https://github.com/great-expectations/great_expectations/issues/110#issuecomment-422015839

**Comment by afuetterer** [comment]
Alright, got it. Thank you. This can be closed then.
Looking forward to the `expect_column_A_to_be_a_foreign_key_to_column_B` expectation.
