### ISSUE TITLE
readthedocs.io page logo

### ISSUE THREAD

**Issue by ryan-wolbeck** [fivetran/great_expectations#3613]
**Describe the bug**
![87AD34D1-ECF4-471E-AE0C-E6E5D519B080](https://user-images.githubusercontent.com/41489316/139329441-18d49cd0-d148-4348-bfd2-e616b3e78c95.png)
The logo image on the read the docs site, is broken
https://great-expectations.readthedocs.io/en/latest/reference/glossary_of_expectations.html#expectation-glossary

**To Reproduce**
Navigate to 
https://great-expectations.readthedocs.io/en/latest/reference/glossary_of_expectations.html#expectation-glossary

**Expected behavior**
Great expectations logo appears

**Environment (please complete the following information):**
 - Operating System: Mac (Chrome)

**Comment by talagluck** [comment]
Thanks for opening this issue, @ryan-wolbeck! We will review and be in touch. In the meantime, you can also access our Legacy Docs through legacy.docs.greatexpectations.io.

**Comment by kyleaton** [comment]
Hopping the above solves it. It passed the test in develop but I'm not 100% confident we'll see the same result in production so we'll have to wait and see until the next release of the documentation.

**Comment by austiezr** [comment]
@kyleaton Bumping this for visibility; doesn't appear to have resolved.

**Comment by ryan-wolbeck** [comment]
I agree, this was not fixed by the PR

**Comment by talagluck** [comment]
Closing as this has since been resolved - see here: https://legacy.docs.greatexpectations.io/en/latest/
