### ISSUE TITLE
Expectation suite created via v3-api notebook cannot be run as created from the same notebook. 

### ISSUE THREAD

**Issue by samLozier** [fivetran/great_expectations#3617]
**Describe the bug**
An expectation suite created with the v3_api notebook cannot be run/edited using the same method without modifying auto-generated python code. Notably the json `null` value is left in a cell where the python `None` is likely needed. 

*To Reproduce**

Create a basic test suite without a ge_cloud_id field :
 `great_expectations --v3-api suite new`
Save the suite by running the final cell. 
Attempt to interactively edit the suite: 
`great_expectations --v3-api suite edit test_suite`

The notebook opens with cells containing un-runnable python code: 
```
expectation_configuration = ExpectationConfiguration(
    **{
        "meta": {},
        "ge_cloud_id": null, # note the non-string wrapped null, which should probably be converted to None
        "expectation_type": "expect_column_values_to_not_be_null",
        "kwargs": {"column": "caseid"},
    }
)
suite.add_expectation(expectation_configuration=expectation_configuration)
``` 

**Expected behavior**
Auto generated code should be valid + run-able python code. 

**Environment (please complete the following information):**
 - Operating System: [macos]
 - Great Expectations Version: [e.g. 0.13.39]

**Additional context**
I don't think it's related, but if it matters, I've been connecting to a snowflake DB.

**Comment by talagluck** [comment]
Hi @samLozier - thank you very much for raising this! This definitely appears to be a bug, and we will review and be in touch soon. Just to confirm STR, it appears that this issue arises when editing the suite not against an existing batch of data. Is that your experience as well?

**Comment by samLozier** [comment]
@talagluck The bug I'm raising is only related to editing, not running the suite itself. I only tested the suite after removing the problematic field, so unfortunately I don't have much to add regarding how it runs.

**Comment by talagluck** [comment]
Thanks, @samLozier! I have confirmed that this is the case when editing a suite without using an existing batch of data. We are working on this, and will reach out with progress.
