### ISSUE TITLE
Feature request: don't create `expect_column_to_exist` automatically

### ISSUE THREAD

**Issue by sotte** [fivetran/great_expectations#362]
I use `ge` for all my data cleaning and validation. But I dislike the automatic creation of the `expect_column_to_exist` validations.

When I read in some data, ge creates expectations for all the initial columns (`'expectation_type': 'expect_column_to_exist'`). Quite often I'm not interested in the column that were there when I read the data, but only the columns that I cleaned (and created expectations for). Is there a nice way to skip the `expect_column_to_exist` when loading data? Or can we add a flag for this?

My current workaround is to create an empty dataframe, add the transformed data to it, and write the expectation against that dataframe.

**Comment by jpcampb2** [comment]
I agree, and opened #338 in the same spirit, but I don't think we need to delay to make the change.

One small thought based on your workflow description: it might make sense to do your pre-cleaning first, potentially with a very basic expectations config that *does* include the expect_column_to_exist expectations, then to create a copy of the dataframe and a new config with your "real" expectations after the cleaning. That way, you'd have two expectations configs--one for what you expect of data coming into your cleaning/transformation step, and one for what you expect it to look like upon leaving.

**Comment by abegong** [comment]
I agree that we should go ahead on this. It's a small change that will signpost bigger things to come.

**Comment by sotte** [comment]
What are the next steps? Would you add a new keyword to `ge.DataFrame` and `ge.from_pandas`?
Maybe the `autoinspect_func` you mention in #338? 
- `autoinspect_func=None` does not do any auto inspection.
- `autoinspect_func="default"` does what it does right now.
- Later we could add function for auto inspections.

**Comment by abegong** [comment]
👍 
This is exactly what I had in mind...

**Comment by jpcampb2** [comment]
@sotte @abegong 👍 Yes, I think it just needs to go into `DataFrame` and to `_convert_to_dataset_class` (so that it will work with all of the read_X type DataFrame creators in addition to from_pandas).

I think it still makes sense to have the default be none, though, and to rename the current "add_default_expectations" to something like "add_expect_column_to_exist_expectations" moving that to a util that someone could use should they like that one (eventually more will be added).

@sotte are you interested in making a PR to that effect?

**Comment by sotte** [comment]
@jpcampb2 sadly I don't have the time right now.

**Comment by njsmith8** [comment]
I have run into this issue as well. 
Perhaps I could take a crack at putting together a PR.

**Comment by jpcampb2** [comment]
@njsmith8 I didn't see this in time, and started a refactor on this yesterday since we've been talking about it! I'll go ahead and turn it into a PR shortly...

**Comment by jpcampb2** [comment]
Thanks again @sotte -- closing this issue based on merging #371

**Comment by sotte** [comment]
Nice, thank you guys!
