### ISSUE TITLE
"--v3-api suite new" cli workflow does not display >50 data assets. 

### ISSUE THREAD

**Issue by samLozier** [fivetran/great_expectations#3623]
**Describe the bug**
When invoking the ` great_expectations --v3-api suite new` command and connecting to an asset with a large number of tables, it is apparently impossible to see the full list of tables or scroll through to see all the tables. 

**To Reproduce**
1. ` great_expectations --v3-api suite new`
2.  On step two select a data source with >50 assets, in my case, snowflake database tables
3. On step 3 "which data asset would you like to use?", Assets are listed in alphabetical order. It is apparently impossible to scroll through the full list, or at the very least no clear instructions are given RE how to do so. 

**Expected behavior**
Full list of assets will be listed for a given datasource OR ability to scroll through the full list should be offered

**Environment (please complete the following information):**
 - Operating System: [mac OS]
 - Great Expectations Version: [0.13.39]

**Additional context**
This is a large snowflake environment with lots of schema/tables per database.

**Comment by talagluck** [comment]
Thanks for opening this issue, @samLozier! This functionality is known, and was added so that we don't overwhelm users with too many tables. That said, we will discuss internally and be in touch.

**Comment by Marcdsv** [comment]
Hello, I'm encountering the same issue. Is there a way to select a table that does not appear in the list?

**Comment by talagluck** [comment]
Just for reference, there is a (not ideal) workaround here, which is to select another table, and then replace that table name in the BatchRequest with the table you'd like to use.

**Comment by samLozier** [comment]
I've found that I'm able to type the name of the table, in all lowercase (didn't test upper) and have it generate the notebook as expected. At a minimum, it might be helpful to end users to have a warning about the current functionality. 

Maybe something like: 
```
First 50 tables are listed here, you can select one that's not listed by typing the name of the table below. 
```

Regardless of your decision, thank you for the quick reply on the issue, it's nice to feel like someone is listening.

**Comment by talagluck** [comment]
Thanks for this, @samLozier! This issue has triggered a review of this workflow, and we're going to do some design work to figure out the best way to move forward. It may take us a little while, but we're working on it!

**Comment by frantakalab** [comment]
I support the issue that @samLozier is describing, it gets even more complicated when there are multiple schemas in the db, since the list does not contain which schema the first 50 listed tables come from (another issue: https://github.com/great-expectations/great_expectations/issues/3528)

**Comment by cdkini** [comment]
@samLozier @frantakalab I've introduced two possible solutions in this PR (pagination and regex based search): https://github.com/great-expectations/great_expectations/pull/3854

Would you mind taking a look and letting you know your thoughts? If you think there's a better approach, please let me know!

**Comment by samLozier** [comment]
I read your code but have not been able to execute it. Assuming it runs how i read it, i think it addresses the issue i described.

**Comment by cdkini** [comment]
Closing as this is addressed in the aforementioned PR!
