### ISSUE TITLE
Typos on Homepage

### ISSUE THREAD

**Issue by ghost** [fivetran/great_expectations#3628]
On the [homepage](https://greatexpectations.io/), in the 'Batteries-included data validation' section, there is a broken Markdown link:

![image](https://user-images.githubusercontent.com/55477181/140005634-34a3617c-3052-4c47-8e40-03a70a4c7e15.png)

Also, on the [homepage](https://greatexpectations.io/), it says that MS SQL Server is a 'Leading open source database', but I think it's proprietary?

![image](https://user-images.githubusercontent.com/55477181/140005719-aeae64e1-3dbd-41be-9fed-00802aa915e9.png)

**Comment by talagluck** [comment]
Thanks for opening this issue, @davidwales! We will review and update our docs accordingly soon.

**Comment by kyleaton** [comment]
This has been updated:

![Screen Shot 2021-11-30 at 3 22 51 PM](https://user-images.githubusercontent.com/6799312/144122244-4810d0cb-683a-40b7-a7fc-73d45b6b463b.png)

**Comment by daviewales** [comment]
Hi, the homepage still lists MS SQL Server as a "leading open source database".
