### ISSUE TITLE
"Code Coverage" + type-checker tool for GE 

### ISSUE THREAD

**Issue by samLozier** [fivetran/great_expectations#3631]
I was encouraged to post this here by @bhcastleton after asking about it on the GE slack. 

**Is your feature request related to a problem? Please describe.**
Changes to dbt/pandas/(data related code) in a project should be somehow tied to tests in GE code. 

**Describe the solution you'd like**
The end goal is something akin to a coverage report/mypy static analysis for a python project. The tool would audit, for example, a dbt models directory find a list of columns that are referenced and ensure that there is at least one GE expectation/column. 

If a column is dropped from or added to the model definition code, the coverage check could raise an error and prompt the user to add a matching test for that column. IMO this would be useful as a pre-commit hook or CI pipeline check and would help to ensure that as the data-source changes, the tests are kept in sync. 

Like linters that warn about using the python "Any" type, this could possibly be used to encouraged better code-side practices like avoiding the use of `select *` or `pd.read_csv()` without explicitly specifying input columns. 

At least with regard to dbt, this may be as simple as running `dbt docs generate` and then comparing the json output to the suites defined in the GE project. If so, this has the advantage of not requiring any connection to a data source so it could be run quickly in a pre-commit hook or ci pipeline. 

**Describe alternatives you've considered**

**Additional context**

**Comment by talagluck** [comment]
Hi @samLozier - thanks for opening this issue! This idea sounds really cool. Where would you imagine this tool would live? It feels to me like it would live outside of core Great Expectations functionality, but if you have thoughts about this, it would be great to get the additional context, and I can bring this to our internal engineering meeting in the next couple of weeks.

**Comment by samLozier** [comment]
@talagluck My mental model was that this would be analogous to mypy or pytest, so either a plugin or stand alone tool that worked along side of GE. As I mentioned, I personally viewed this as something I'd run in a pre-commit hook or in CI. When working in python, I roughly follow the workflow laid out in the "hypermodern python" article series and want to have the same rough flow when working with these tools. 


pre-commit:
- lint - possibly sqlfluff? - I haven't used it myself
- type check - this tool
- coverage check - this tool (statically comparing GE to dbt docs)
ci: 
- run the same + possibly actually validate against the datasource (or not?) 

Limiting the scope back to what I'd described initially, I think the one thing that might trip this up is when GE is used to validate tables upstream of dbt. To my knowledge there isn't a way to get GE to generate docs for tables that aren't created by dbt, but that's something I'm going to look into.

**Comment by talagluck** [comment]
Hi @samLozier - apologies for delays here! We have had some internal conversations about this. Overall, we agree that this is an awesome idea, but will likely not be able to resource it internally in the near-term. That said, we always welcome contributions, and are happy to offer guidance and support if you are interested in contributing! If so, I think the right place for this would be inside of a new directory within our `contrib` directory - e.g. `contrib/experimental/code_coverage/ge_model_checker.py`. Please feel free to reach out if this is of interest, or if you have follow-ups. Thanks!

**Comment by samLozier** [comment]
@talagluck thanks for the follow up. I actually took a pass at a basic version of this at work and will have to check before I share, but the basic gist of it is that you end up with collections of objects with table.schema.column syntax (or any sub part) and then you can do set operations against other collections of like objects from another project. Assuming I get the ok, I'll put a little thought into how I want to share it because it could be useful to a number of platforms including GE, dbt, pandas, pandera and more. Feel

**Comment by aodj** [comment]
@samLozier did you get anywhere with this? Your last post appears to cut off suddenly, and I'm curious to hear what came of your work.

**Comment by talagluck** [comment]
Hi @samLozier - I'd also be curious to see how this all resolved. I'm going to close this for now, but please feel free to re-open if you are interested in contributing.
