### ISSUE TITLE
Can this library be used with Java/ Scala ?

### ISSUE THREAD

**Issue by almogtavor** [fivetran/great_expectations#3647]
**Is your feature request related to a problem? Please describe.**
There are many Spark developers out there that use Java and Scala. I'd like to know if and how it is possible to use great expectations in such languages.

**Describe the solution you'd like**
I'd like to use this library with Apache Spark in Java.

**Describe alternatives you've considered**
There's an option of using some embedded python-in-Java library, but of course it ain't a preferred choice.

**Comment by cdkini** [comment]
Hey @almogtavor! Thanks for bringing this up!

We unfortunately do not support any language outside of Python. If you'd like to try to enable a workaround, I think the alternative you've suggested may be the best path forward. Best of luck getting things to work 🎉
