### ISSUE TITLE
Connect Spark to S3

### ISSUE THREAD

**Issue by xaraujo** [fivetran/great_expectations#3650]
**Describe the bug**
I'm trying implement pyspark with S3 using InferredAssetS3DataConnector but I got a message saying "ValueError: S3 query may not have been configured correctly".
One of the params that class receives is the prefix, that represents the file to read, after debug your code I found the issue related to prefix transformation that adds a trailing slash, in the line:
`self._prefix = os.path.join(prefix, "")`
I just edited and set it to:
`self._prefix = prefix`
and it worked.

**To Reproduce**
1. Setup the datasource like:
`example_yaml = f"""
name: {datasource_name}
class_name: Datasource
execution_engine:
  class_name: SparkDFExecutionEngine
data_connectors:
  default_inferred_data_connector_name:
    class_name: InferredAssetS3DataConnector
    bucket: bucket_name
    prefix: file.csv
    default_regex:
      group_names: 
          - data_asset_name
      pattern: (.*)\.csv
    boto3_options:
      endpoint_url: url
      aws_access_key_id: access_key
      aws_secret_access_key: secret_key
  default_runtime_data_connector_name:
    class_name: RuntimeDataConnector
    batch_identifiers:
        - default_identifier_name
"""
print(example_yaml)
context.test_yaml_config(yaml_config=example_yaml)
`
or just use the script:
`import os
prefix = "weather.csv"
prefix_new = os.path.join(prefix, "")
print(prefix_new) # it will return weather.csv/`

**Expected behavior**
Should  return the prefix without '/'  at the end

**Environment (please complete the following information):**
 - Operating System: [Linux, ]
 - Great Expectations Version: [0.13.41]

**Additional context**
The class ConfiguredAssetS3DataConnector has the same issue.
I would like get this sorted as soon as possible , so can I kindly ask to take a look?

Many Thanks,

With Best Regards
Xavier

**Comment by cdkini** [comment]
Leaving a note to also investigate Azure and GCS prefixing since they all use the same logic.

**Comment by talagluck** [comment]
Thanks for raising this issue, @xaraujo! We will review and be in touch soon.

**Comment by xaraujo** [comment]
Hi All,

Any update on that?

Many Thanks 
With Best Regards
Xavier

**Comment by cdkini** [comment]
Merged a hotfix PR!
