### ISSUE TITLE
Running expect_column_values_to_be_unique on Postgres datasource raises psycopg2 error.

### ISSUE THREAD

**Issue by gzamb08** [fivetran/great_expectations#3656]
**Describe the bug**
Running **expect_column_values_to_be_unique** expectation on a Postgres table column raises psycopg2 error:

expect_column_values_to_be_unique raised an exception:
(psycopg2.errors.SyntaxError) subquery in FROM must have an alias LINE 3: FROM (SELECT CASE WHEN (id_viagem IS NOT NULL AND id_viagem ... ^ HINT: For example, FROM (SELECT ...) [AS] foo. [SQL: SELECT "UnexpectedCountSubquery".unexpected_count FROM (SELECT sum(condition) AS unexpected_count FROM (SELECT CASE WHEN (id_viagem IS NOT NULL AND id_viagem IN (SELECT id_viagem FROM ge_temp_9ccb44eb GROUP BY id_viagem HAVING count(id_viagem) > %(count_1)s)) THEN CAST(%(param_1)s AS NUMERIC) ELSE CAST(%(param_2)s AS NUMERIC) END AS condition FROM ge_temp_9ccb44eb)) AS "UnexpectedCountSubquery"] [parameters: {'count_1': 1, 'param_1': 1, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/13/f405)

**To Reproduce**
1. Setup expectation suite:

{
  "data_asset_type": null,
  "expectation_suite_name": "ft_viagem_2.suite",
  "expectations": [
    {
      "expectation_type": "expect_column_values_to_be_unique",
      "ge_cloud_id": null,
      "kwargs": {
        "column": "id_viagem"
      },
      "meta": {}
    }
  ],
  "ge_cloud_id": null,
  "meta": {
    "citations": [
      {
        "batch_request": {
          "data_asset_name": "ft_viagem_2",
          "data_connector_name": "default_inferred_data_connector_name",
          "datasource_name": "dw_hml",
          "limit": 1000
        },
        "citation_date": "2021-11-10T19:49:30.318922Z",
        "comment": "Created suite added via CLI"
      }
    ],
    "great_expectations_version": "0.13.41"
  }
}

2. Run checkpoint via cli (great_expectations --v3-api checkpoint run ft_viagem_2_checkpoint).

3. Exception raised (can be seen on Data Docs).

**Expected behavior**
Expectation execute normally.
 
**Environment (please complete the following information):**
 - Operating System: Ubuntu 18.04
 - Great Expectations Version: 0.13.41

**Additional context**

**Comment by gzamb08** [comment]
**UPDATE:** Executed the same scenario using ge version 0.13.39 and it worked just fine.

**Comment by talagluck** [comment]
Thanks so much for opening this, @gzamb08! We will review and be in touch soon.

**Comment by austiezr** [comment]
@gzamb08 We've had some motion in this area recently; are you able to confirm this is still an issue for you in 0.13.45? If so, would you be able to share your checkpoint config?

**Comment by austiezr** [comment]
Hey @gzamb08! I'm going to close this out for now as we believe this may have recently resolved; if you're still experiencing this behavior on the latest version of GE, please feel free to re-open with that context.
