### ISSUE TITLE
BUG Broken link in Edit Your Expectation Suite starter notebook

### ISSUE THREAD

**Issue by discdiver** [fivetran/great_expectations#3663]
Thank you for this great tool!

[**Describe the bug**
A clear and concise description of what the bug is.]

Broken link in the automatically generated *Edit Your Expectation Suite* starter noteboook: https://docs.greatexpectations.io/en/latest/autoapi/great_expectations/data_asset/index.html?highlight=remove_expectation&utm_source=notebook&utm_medium=edit_expectations#great_expectations.data_asset.DataAsset.remove_expectation

**To Reproduce**

Scroll down to 

```
## Save & Review Your Expectations

Let's save the expectation suite as a JSON file in the `great_expectations/expectations` directory of your project.
If you decide not to save some expectations that you created, use [remove_expectation method](https://docs.greatexpectations.io/en/latest/autoapi/great_expectations/data_asset/index.html?highlight=remove_expectation&utm_source=notebook&utm_medium=edit_expectations#great_expectations.data_asset.DataAsset.remove_expectation). 
```

Click on the link and it returns a 404 error.

**Expected behavior**
A working link.

**Comment by talagluck** [comment]
Thanks for opening this issue, @discdiver! We will review and be in touch. We also welcome community contributions if you are interested!

**Comment by discdiver** [comment]
Thanks. I'm hesitant to submit a PR to fix the links because I see they have UTM params and I don't know what values you want for those. 🙂

BTW, the link to the expectation glossary in the same auto-generated notebook goes to an old version of the docs: 

```
## Create & Edit Expectations

Add expectations by calling specific expectation methods on the `batch` object. They all begin with `.expect_` which makes autocompleting easy using tab.

You can see all the available expectations in the **[expectation glossary](https://docs.greatexpectations.io/en/latest/reference/glossary_of_expectations.html?utm_source=notebook&utm_medium=create_expectations)**.
```

**Comment by Rachel-Reverie** [comment]
Hi @discdiver!  [PR #3745](https://github.com/great-expectations/great_expectations/pull/3745) and PR #3750 address the original issue you raised, and [PR #3747](https://github.com/great-expectations/great_expectations/pull/3747) addresses the issue in your later comment, so I'm going to close this issue for now.  Thank you for bringing these items to our attention!
