### ISSUE TITLE
Validating data in a hosted environment - Documentation sends you on a meaningless goose chase.

### ISSUE THREAD

**Issue by bhcastleton** [fivetran/great_expectations#3665]
**Describe the bug**
When I go to the documentation [here](https://docs.greatexpectations.io/docs/deployment_patterns/how_to_instantiate_a_data_context_hosted_environments) to find out how to deploy Great Expectations in a hosted environment, step three tells me to go to the guide showing how to validate data without a checkpoint. So I go [here](https://docs.greatexpectations.io/docs/guides/validation/advanced/how_to_validate_data_without_a_checkpoint) and it tells me we don't do that anymore in v3.

Let's get rid of this meaningless path in the documentation.

**Comment by kenwade4** [comment]
@bhcastleton A JIRA ticket has been added to update the issue
