### ISSUE TITLE
Add Metrics on other columns to the validation result

### ISSUE THREAD

**Issue by BilalHaniff** [fivetran/great_expectations#3671]
**Is your feature request related to a problem? Please describe.**
Expectation results currently only provide metrics for the column that is being checked.  I would like to add metrics of another column in my results.

**Describe the solution you'd like**
In the finance world, a DQ issue can have material impact on a calculation.  We therefore need to know what this impact is for each expectation.
For example, if I have a 10 loans of 1million each and the loanID is missing for 5 of them, the material impact of the  loanID missing, is 5 million. This should be logged as a metric in the results.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by talagluck** [comment]
Hi @BilalHaniff - thanks for opening this issue! We currently have an open PR that I believe will address this in #3346. 

I believe a more specific version of what you are requesting can be found in #3195. Let me know if you agree that these are the same issue, and I'll close this for now, but we are working on it.

**Comment by talagluck** [comment]
Hi @BilalHaniff - I'm going to close this for now, as I believe it is a duplicate. If you feel that this is substantively different from #3195, please feel free to re-open with the additional context of how it differs.
