### ISSUE TITLE
sparkdf_execution_engine Integration with S3

### ISSUE THREAD

**Issue by xaraujo** [fivetran/great_expectations#3685]
**Describe the bug**
The sparkdf_execution_engine does not have the boto3_options params to connect to S3 like pandas_execution_engine has.  

**To Reproduce**
Setup datasource and expectations suite using pyspark and load the dataset from S3 

**Expected behavior**
Load the data from S3 and run the validations, down the line generate a report.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version:  0.13.42

**Additional context**
Please take a look the file attached that works and compare it against to the current one to see the differences
[sparkdf_execution_engine.zip](https://github.com/great-expectations/great_expectations/files/7547728/sparkdf_execution_engine.zip)

PS.: there is another ticket related to Pyspark and S3 that would be good to solve it.
https://github.com/great-expectations/great_expectations/issues/3650

With Best Regards
Xavier

**Comment by talagluck** [comment]
Thanks for opening this issue, @xaraujo! We are currently working on your other ticket. To confirm, is this issue different from the other? If so, would you please rename this with something more descriptive and specific?

**Comment by xaraujo** [comment]
Many Thanks for your message, as you asked, I changed the name to sparkdf_execution_engine Integration with S3

**Comment by xaraujo** [comment]
Hi All,

Any update on that?

With Best Regards
Xavier

**Comment by cdkini** [comment]
Hey @xaraujo! This is on our radar but I'm still working to add the functionality you're looking for. Is this something you might be interested in contributing?

**Comment by cdkini** [comment]
@xaraujo would you mind elaborating your use-case? What fields from `boto3_options` are you looking to pass into the `SparkDFExecutionEngine`?

In the `PandasExecutionEngine`, we use `boto3_options` and other cloud-specific configuration dicts to supply fields directly into cloud-provider's connection object; this allows for some customization since you're directly impacting that connection object. 

For SparkDFExecutionEngine, this does not occur. The presence of `azure_options` is simply a way for the user to pass credentials down to Spark. This shouldn't be an issue in S3 since you're able to connect to Spark without any explicit credential field.

**Comment by xaraujo** [comment]
Hi @cdkini,
Many thanks to come to me.
Im running this without install pyspark, just using "normal" spark an passing spark_config:

```
spark_config = {
        "spark.hadoop.fs.s3a.aws.credentials.provider":"com.amazonaws.auth.DefaultAWSCredentialsProviderChain",
        "spark.hadoop.fs.s3a.endpoint": spark_endpoint_url
}

```

and loading the credentials from AWS_CREDENTIAL_PROFILES_FILE.

Without this piece of code 

```
elif isinstance(batch_spec, S3BatchSpec):
            if self._s3 is None:
                raise ge_exceptions.ExecutionEngineError(
                    f"""PandasExecutionEngine has been passed a S3BatchSpec,
                        but the ExecutionEngine does not have a boto3 client configured. Please check your config."""
                )
            s3_engine = self._s3
            reader_method: str = batch_spec.reader_method
            reader_options: dict = batch_spec.reader_options or {}
            path: str = batch_spec.path
            s3_url = S3Url(path)
            reader: DataFrameReader = self.spark.read.options(**reader_options)
            reader_fn: Callable = self._get_reader_fn(
                    reader=reader,
                    reader_method=reader_method,
                    path=s3_url.key,
                )
            batch_data = reader_fn(path)
```
The code is not able to find the datasource.

With the changes you can see in the attached file it works, however I dont know if there is any side effect in other feature that also it uses this code.

Please take a look and consider apply the change/development.


With Best Regards
Xavier

**Comment by cdkini** [comment]
@xaraujo would you mind seeing if https://github.com/great-expectations/great_expectations/pull/3800 covers your changes? I'm not sure we need to instantiate an S3 connection or pass in boto3_options since those aren't being used in your use-case (but please let me know if that's incorrect).

**Comment by xaraujo** [comment]
Hi @cdkini ,
Many thanks for your answer. I tested and it did not work. I think we really need boto3 as a param because my datasource(dataset) and the expectations file both are on S3 and to run the executor we really need to access to boto3.
If you need further information please let me know.

With Best Regards
Xavier

**Comment by cdkini** [comment]
Hey @xaraujo I'm not sure I'm fully understanding why you've instantiated `self._s3` if it isn't used at all (outside of the `None` check). Would your use-case still work if we just supported `boto3_options` as an arg but did not create the S3 connection? These changes are now reflected in the PR.

Is `self._s3 = boto3.client("s3", **boto3_options)` necessary to get this working for you? I'll add it if need be but I want to avoid creating cloud objects if they aren't used.

**Comment by cdkini** [comment]
@xaraujo I'm going to close this for the time being but let me know if you'd like to revisit!
