### ISSUE TITLE
Allow organization of checkpoints into nested directories. 

### ISSUE THREAD

**Issue by samLozier** [fivetran/great_expectations#3686]
**Is your feature request related to a problem? Please describe.**
It should be possible to organize checkpoints into nested directories. 

**Describe the solution you'd like**
Allow checkpoints to be nested arbitrarily inside the checkpoints directory. This will be most helpful on larger projects and in my own case, when used with a large dbt project that has nested models directories. 

**Describe alternatives you've considered**
tags or some other solution may be viable, but i'm hoping this should be easy enough to implement 

**Additional context**
```
checkpoints/mycheckpoint.yml # works
checkpoints/sub_projectA/mycheckpoint.yml #does not work
This is called from :
#with the checkpoint in the subdirectory
context.run_checkpoint(checkpoint_name='mycheckpoint' )
# and 
contex.run_checkpoint(checkpoint_name='./sub_projectA/mycheckpoint') 
# both don't work
```

**Comment by talagluck** [comment]
Thanks for opening this issue, @samLozier! We will review and be in touch.

**Comment by cdkini** [comment]
@samLozier this should be fixed as part of https://github.com/great-expectations/great_expectations/pull/3811.

The feature was always there but hidden behind a small bug; there should now be parity between expectations and checkpoints (in regards to dot notation). Thanks for bringing this up! I'll close this for now but please let me know if you're having any issues.
