### ISSUE TITLE
New approach for computating expect_column_values_to_be_in_set in spark environment

### ISSUE THREAD

**Issue by derek-hk** [fivetran/great_expectations#3699]
**Background**
We are trying to apply Great Expectations to check the data quality.
A foreign key checking between a 200k rows value_set against a 60k rows checking_set (60k rows) requires 1000 second to complete. This is much longer than our expectation in a spark environment. After looking into the source code of .expect_column_values_to_be_in_set() under a spark dataframe, we found that _"column[0].isin(value_set)"_ is the root cause of such behavior (see the first screen cap below)

**Is your feature request related to a problem? Please describe.**
Performance of the current solution which uses a python list as input of value_set deteriorates when a big dataset is involved.

Our input is a spark dataframe, it is casted into a list before it is thrown into the function.
After a series of testing, the runtime of the current solution grows linearly with len(value_set). This implies a large table may slow down the process. By testing on a ~10m rows value_set, the process cannot be completed after 3 days (we killed it at the end).

**Describe the solution you'd like**
In spark environment, we would like to use pyspark function which make use of the calculating power of spark to do the matching instead of using a python list
_i.e. use join() to replace isin() in the following module_ in _great_expectations/dataset/sparkdf_dataset.py_
![image](https://user-images.githubusercontent.com/90680179/142392615-06e8e162-1e20-4fe1-9b23-ee515e18c465.png)

**Testing result**
![image](https://user-images.githubusercontent.com/90680179/142389912-57007ad0-764a-43f3-ab91-662e92d884bd.png)
Join brings a tremendous improvement in runtime, which turns our big foreign key mapping from something like more than 3 days to just 10s under the Databricks environment
Therefore, joining is strongly recommended when the dataframe is a spark dataframe.

**Appendix**
Attached the codes for your further studies, thank you very much !!!! :)

```
import time
import numpy as np
import pandas as pd
from random import shuffle
from pyspark.sql import SparkSession
from pyspark.sql.functions import col,when
spark = SparkSession.builder.getOrCreate()

expect_column_values = spark.sql("select distinct member_key as column from rdm.f_transaction where business_date_key = 20211111")
to_be_in_set = spark.sql("select distinct member_key as column from rdm.d_member order by 1")

print(expect_column_values.count())
print(to_be_in_set.count())

df = expect_column_values.join(to_be_in_set,expect_column_values["column"] ==  to_be_in_set["column"] ,"left")
df1=df.withColumn("__success",when(to_be_in_set["column"] == None,False).otherwise(True))
df2 = df1.select(expect_column_values["column"],"__success").show(5,False)
```

**Comment by cdkini** [comment]
Hey @derek-hk! Thanks so much for opening up this issue after our discussion in Slack.

We'll discuss internally and be in touch!

**Comment by austiezr** [comment]
Hey @derek-hk! We would be able to accept a [contrib expectation](https://docs.greatexpectations.io/docs/guides/expectations/contributing/how_to_contribute_a_new_expectation_to_great_expectations) with this functionality in the short term; before accepting this as a change to a core expectation we would need testing to confirm that this approach is performant in both low-cardinality and high-cardinality situations.

Is this something you'd be willing to submit as a contribution? We're happy to provide guidance and review on that process.

**Comment by derek-hk** [comment]
Hi @austiezr 
Does it mean that it is preferred to exist as a new expectation instead of expect_column_values_to_be_in_set?

**Comment by austiezr** [comment]
Hey @derek-hk! Yes, in the short term we would accept this as a new expectation.

**Comment by derek-hk** [comment]
Hi, i think i might contribute with some help.

However, I did some development job on my hand, to the original expect_column_values_to_be_in_set() and i found confused.
**Firstly**, I changed great_expectation/dataset/sparkdf_dataset.py as follow
![image](https://user-images.githubusercontent.com/90680179/146629789-1e44bf62-0aa6-498c-ab8c-c3a88c6926e9.png)
After this changes, value_set is a spark dataframe instead of a list.
In line 860, I found `value_set is None` in line 868 always happening although my value set is not None.
So that I put my new logic for giving the __success column there.

Secondly, I add a logic to convert an spark df into `recursively_convert_to_json_serializable()` in great_expectations/data_asset/util.py
![image](https://user-images.githubusercontent.com/90680179/146629940-10f09763-6b59-4460-8e0e-322bc4836f00.png)
After that, my new sparkdf value_set could pretend a list's output, a list.

However, it gives error: 'list' object has no attribute '_jdf', and the entire error message is attached [ge_error.txt](https://github.com/great-expectations/great_expectations/files/7738760/ge_error.txt)
![image](https://user-images.githubusercontent.com/90680179/146629998-dac34ba6-af65-4cc6-b726-94a8f353d5f1.png)

But! There are one horrible observation: Validation result could be produced with `return column.withColumn("__success", lit(True))`
![image](https://user-images.githubusercontent.com/90680179/146630068-57630a1e-e589-471d-aaa0-ca6a61992d9c.png)

**Long Story In Short:** 
return `column.withColumn("__success", lit(True))` ---> Can produce validation result
return `column.join(value_set,column[0] ==  value_set[0] ,"left").withColumn("__success",when(value_set[0].isNull(),False).otherwise(True)).select(column[0],"__success")` ---> Cannot produce validation result, although it is giving the same tables as the original logic: `return column.withColumn("__success", column[0].isin(value_set))`

**Comment by derek-hk** [comment]
Sorry, I was drunk when I was typing that reply. Let me re-write it.
**Firstly**, I changed the logic of expect_column_values_to_be_in_set() in great_expectation/dataset/sparkdf_dataset.py from `column.withColumn("__success", column[0].isin(value_set))` to `column.join(value_set,column[0] == value_set[0] ,"left").withColumn("__success",when(value_set[0].isNull(),False).otherwise(True)).select(column[0],"__success")`
But I found that if in line 858-860 (`return column.withColumn("__success",lit(True))`) is always be returned, so that i put my logic into line 860 as well.

**Secondly** I changed recursively_convert_to_json_serializable() in great_expectations/data_asset/util.py
I add a if to handle a spark dataframe input, to convert a spark dataframe into a list.

After doing that, i got `'list' object has no attribute '_jdf'`.

But, if expect_column_values_to_be_in_set() is returning `return column.withColumn("__success",lit(True))`, a validation with zero unexpected count could be produced successfully.

Long story in short:
`return column.withColumn("__success", lit(True))` 
---> Can produce validation result
`return column.join(value_set,column[0] == value_set[0] ,"left").withColumn("__success",when(value_set[0].isNull(),False).otherwise(True)).select(column[0],"__success")` 
---> Cannot produce validation result, although it is giving the same tables as the original logic: `return column.withColumn("__success", column[0].isin(value_set))`

**Comment by derek-hk** [comment]
Hi @austiezr!
I did some development on my hand.
Here is my new expect_column_values_to_be_in_set()
![image](https://user-images.githubusercontent.com/90680179/146708594-57482bf9-a841-4d0f-8a04-ffe406d25ccb.png)
The new logic is returning the same as the old logic (column, __success)
But `AttributeError: 'list' object has no attribute '_jdf'` is thrown.
Attached the full error msg here [ge_error.txt](https://github.com/great-expectations/great_expectations/files/7742421/ge_error.txt)

And this is the verification of the identical result of both logic.
![image](https://user-images.githubusercontent.com/90680179/146709094-358dc592-99a5-4523-bea8-8559ee478ebe.png)

**Comment by derek-hk** [comment]
Hi @austiezr 
I have found that is it not easy to handle the pyspark dataframe datatype under great_expectations.data_asset.util.recursively_convert_to_json_serializable

I have tried to change the input "value_set" of expect_column_values_to_be_in_set() from a list to a spark dataframe

But I don't know how to handle it in great_expectations.data_asset.util.recursively_convert_to_json_serializable()
I tried to cast the spark value_set into list, then it becomes a list in computation as well, which is invalid.
![image](https://user-images.githubusercontent.com/90680179/147910980-a4f26615-f6e6-495f-b88a-4724137f2ab5.png)

What I want is:
1. Input of value_set: spark dataframe
2. It could be serialized into json serializable format for data docs generation (which should be a list)
3. In computation, value_set is still a spark dataframe

**Comment by derek-hk** [comment]
Hi @austiezr 
I would like to help in the testing of the proposed approach.
Please let me know if anything I can help!

**Comment by austiezr** [comment]
Hey @derek-hk! 

A couple of things you could do if interested:
- Submit a PR for this expectation as an [experimental Custom Expectation](https://docs.greatexpectations.io/docs/guides/expectations/contributing/how_to_contribute_a_new_expectation_to_great_expectations)
- Benchmark the performance of your new approach vs the current core approach on data of various size and complexity and report back here

Either / Both of these would help us drive the conversation forward around a change like this.

**Comment by derek-hk** [comment]
Hi @austiezr 
As far as I know, passing a spark dataframe into value_set and edit the return directly doesn't work.
So let me first share the performance of my approach vs the current approach.

**Methodology:**

1. Declare a dataframe called "column", which contains data with 248678 rows to be validated.
2. Declare the value_set for the testing, we have product_key, store_key, card_key and member_key as our testing case.
Note the following row count of different testing set: 
product_key: 199210
store_key: 728
card_key: 9874598
member_key: 9871723
2. Use `column.withColumn("__success", column[0].isin(value_set))`, where value_set is a list, to produce the `__success` column as follow.
![image](https://user-images.githubusercontent.com/90680179/152509358-29e4c6ed-902f-45c4-be0f-e28809a30468.png)

3. Use `column.join(value_set,column[0] == value_set[0] ,"left").withColumn("__success",when(value_set[0].isNull(),False).otherwise(True)).select(column[0],"__success")`, where value_set is a spark dataframe to produce the `__success` column as follow.
![image](https://user-images.githubusercontent.com/90680179/152509420-fd48f371-e3bb-48a4-80d7-87ee08b2ad18.png)

4. Compare and record the performance.

5. Result of the tests:
![image](https://user-images.githubusercontent.com/90680179/152510246-797b5e7d-c7af-47a8-af8c-11c2e6ce8cbf.png)

6. My conclusion: Joining approach is more efficient in both big value_set and small value_set

**Comment by austiezr** [comment]
@derek-hk We've implemented your above approach as a `contrib` / `experimental` expectation; see PR #5702. Closing this issue out; feel free to continue discussion on the PR!
