### ISSUE TITLE
Allow passing a schema name to SqlAlchemyDataset

### ISSUE THREAD

**Issue by elsander** [fivetran/great_expectations#370]
Currently, SqlAlchemyDataset accepts a table name but not a schema name. I'm currently working in Redshift. When I try to instantiate a `SqlAlchemyDataset`, I get a `KeyError` with `public.<tablename>`. After some inspection, I determined that the issue is popping up in this line:https://github.com/great-expectations/great_expectations/blob/d7a4ee03cfce8bea66c5f91573bb87e4385b1eb1/great_expectations/dataset/sqlalchemy_dataset.py#L222

Because I'm not passing a schema name, it uses the default schema, which is "public" for Redshift. When I run this line myself but specifying the schema name, the line runs successfully. Accessing non-default schemas seems like a common use case, so a schema argument would be helpful in many other cases.

**Comment by elsander** [comment]
I can actually take a stab at adding this feature. It might only take a few lines.

**Comment by abegong** [comment]
That would be great! Pull requests are very welcome.

**Comment by elsander** [comment]
Just a heads up-- I'm tied up with some work deadlines, but I haven't forgotten about this! I have the code working for my own use case, but I want to test more thoroughly before making a PR. It may not be until next week though. Sorry for the delay!
