### ISSUE TITLE
custom_sql fails for Redshift databases

### ISSUE THREAD

**Issue by elsander** [fivetran/great_expectations#372]
Redshift unfortunately does not have functionality for `IF NOT EXISTS`, so the temporary table creation fails when passing custom sql to a Redshift SQLAlchemy engine. It seems like the options are here are to introspect the engine and special-case Redshift (seems harder to maintain), to remove the `IF NOT EXISTS` for everyone and let the custom sql fail if the table exists (I think I'd expect this behavior as a user anyway), or to not support custom_sql for Redshift.

**Comment by elsander** [comment]
If the maintainers have thoughts on which approach makes the most sense for the library, I'm happy to take a stab at this next week as well. I'm hoping to make some contributions to this library for Hacktoberfest :)

**Comment by ccnobbli** [comment]
Cool! I haven't looked into it but the second option makes sense to me. @jpcampb2 is the author and resident expert on the SQLAlchemy implementations.
