### ISSUE TITLE
CLI Commands extremely slow after creation of Teradata datasource

### ISSUE THREAD

**Issue by dsehnbru** [fivetran/great_expectations#3720]
**Describe the bug**
After creating a teradata datasource all CLI commands are extremly slow. 
(reminds me of https://github.com/great-expectations/great_expectations/issues/3577, that one seems to have been solved though)

**To Reproduce**
1. Create a datasource to Teradata DB (the creation process already takes a quite long time)
2. Any CLI command (like great_expectations --v3-api suite new)
3. The next menu where you can choose the way you want to create your suite takes like 10 minutes to appear on the screen
4. If you take the datasource out of the great_expectations.yml File the response time is back to normal. 

**Expected behavior**
an additional datasource shouldn't bring down CLI performance for good.

**Environment (please complete the following information):**
 - Operating System: Windows 10
 - Great Expectations Version: [e.g. 0.13.43]

**Comment by rafaelkrysciak** [comment]
I figured out that the slowness comes from the introspection of the database done in inferred_asset_sql_data_connector.py. When the database has hundreds of schemas, it can take quite a long time. There is a way to limit the inspection to specific schemas, but I could not figure out how. Maybe some chapter in the documentation could be added.

**Comment by rafaelkrysciak** [comment]
When the schemas for the introspection can't be limited, it might be because of issue #3652 `InferredAssetSqlDataConnector` does not respect passed `introspection_directives`.

**Comment by cdkini** [comment]
Hey @dsehnbru! Thanks so much for opening up this issue. Would you mind providing your configuration (omitting any sensitive details)? I'll investigate the situation and also look into @rafaelkrysciak's suggestion here.

Please note that Teradata is not actively supported but I'll try my best to diagnose the issue at hand.

**Comment by dsehnbru** [comment]
Hi Chetan, thanks for getting back to me.

**Comment by dsehnbru** [comment]
In the datasource Section of the config file I defined the ds like that.

teradata:
    execution_engine:
      connection_string: teradatasql://<username>:<password>@<servername>
      class_name: SqlAlchemyExecutionEngine
      module_name: great_expectations.execution_engine
    class_name: Datasource
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
        module_name: great_expectations.datasource.data_connector
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        module_name: great_expectations.datasource.data_connector
        introspection_directives:
            schema_name: <teradataschema>


The schema in the introspection_directives section should actually take care that not the whole huge TD database is constantly checked, 
but only the specified schema. Unfortunately this doesn work. Rafaels workaround works, but ideally you wouldn't have to adapt the code :-)

**Comment by dsehnbru** [comment]
with the brackets I used it obivously doesn't work, so here we go again

teradata:
    execution_engine:
      connection_string: teradatasql://username:password@servername
      class_name: SqlAlchemyExecutionEngine
      module_name: great_expectations.execution_engine
    class_name: Datasource
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
        module_name: great_expectations.datasource.data_connector
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        module_name: great_expectations.datasource.data_connector
        introspection_directives:
            schema_name: teradataschema

**Comment by dsehnbru** [comment]
Workaround would be to set the variable schema to the schema you are working on in line 215 of great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py

**Comment by cdkini** [comment]
@dsehnbru whenever you utilize a CLI command, you're inherently creating a `DataContext` under the hood. The de-serialization from YAML to GE object will inherently get slower as that config grows in complexity.

That being said, I do believe this is a bug. I haven't been able to successfully recreate the scenario you're seeing here but the `introspective_directives` issue noted in https://github.com/great-expectations/great_expectations/issues/3652 definitely plays a role here. 

Since we're using an `InferredAssetSqlDataConnector` here, we end up invoking `_introspect_db` in the object's constructor (when instantiating the project `DataContext`).

For now, I think the approach recommended by @rafaelkrysciak is a decent way to circumvent the issue. Since the problem at hand is covered by the aforementioned issue, I'm going to close this down and use that as the primary way to track this bug.

Apologies for the inconvenience I hope we can get a solution up and running soon.
