### ISSUE TITLE
Add a debug mode to the cli which displays tracebacks on error

### ISSUE THREAD

**Issue by ghost** [fivetran/great_expectations#3725]
**Is your feature request related to a problem? Please describe.**

While trying to find the cause of issue #3717, I was significantly slowed in my investigation because the cli tool suppresses tracebacks.
I tried the verbose flag `-v`, but this didn't allow the traceback to appear.
Instead, I had to mess around in the `pdb` debugger with breakpoints until I found a function I could call using `interact` which showed me the traceback, and explained the cause of the error.

**Describe the solution you'd like**
It would be really nice if there was a `--debug` flag (Or extra verbose flag `-vv`), which allowed tracebacks to show when running the cli tool. This would make it easier for end users to provide useful bug reports.

**Describe alternatives you've considered**
I tried to see if tracebacks were written to a log file, but I was unable to find it if this is the case.

**Comment by cdkini** [comment]
Hey @davidwales! Appreciate you opening this up after our last conversation.

After discussing the matter internally, I think we're not prioritizing a flag of this nature. We try to keep the CLI as a higher level abstraction; if users want to debug or get deeply involved in the code, I think the recommend approach is actually using the underlying library.

Please let me know if you have any thoughts here and if I'm not fully recognizing your use-case. I'll close this issue for now but happy to start a discourse. Thanks!

**Comment by ghost** [comment]
Thanks @cdkini. I can understand that you want the CLI to be an 'end user' product. I don't expect to see tracebacks from consumer focussed GUI products, etc.

On the other hand, I like to provide high quality bug reports to projects when I encounter issues.

For me, it was not obvious how to go from the error message provided 'Invalid IPV6 URL' to a meaningful bug report.
I suspected that the error was related to my `sqlalchemy` connection string, but this was not entirely clear.

I didn't want to paste my connection string containing my username and password into an issue!
So the only option was to find the cause of the issue myself.

I spent a little bit of time looking for debug options to enable tracebacks, but couldn't find them. I also looked for a log file.
Not knowing the codebase, I didn't know what code I should run to do the same thing as the CLI, but with tracebacks.
I ended up stepping through the code in `pdb` for several hours trying different breakpoints to find the point in the code just before the error was shown.

I realise now that I should have used `interact` to run the first function below the level of the CLI, which would likely have given me a traceback quickly. However, I am not a regular user of `pdb`, so this thought didn't occur to me.

If I were a less persistent person, I would have submitted a poor quality bug report, which would have been hard to diagnose without sharing my connection string. Or I would have given up on GE entirely.

If you're not wanting to include a `--debug` flag or a logfile option, perhaps you could update the bug report template with a hint for how to run the code in a way that generates tracebacks or logs?

**Comment by cdkini** [comment]
The thoroughness is very much appreciated 🙇🏽 

Your point about being more clear in the bug report template is something we'll definitely take into consideration. I'll bring this up internally to determine how best to move forward. We're always working to bolster our documentation so any feedback is appreciated and recognized!

The team will be out for the holiday but I'll highlight this for our next team discussion.
