### ISSUE TITLE
Adding expectation based on subset of another field

### ISSUE THREAD

**Issue by Thijsjahae** [fivetran/great_expectations#373]
HI,

I would very much like to do expectations based on the value of another field. For instance, if i have a column 'Drinks' with values 'Beer', 'Wine' and 'Licors' and a column 'Volume' > I would like to be able to do expect_column_median_to_be_between for the volume column where the value of column 'Drinks' is 'Beer'. This I would like to do on Licors and Wine as well (with different min/max values) and put the output in one JSON for testing. Is there currently a possibility to do this?

Thanks

**Comment by abegong** [comment]
Something like this?

```
my_df.expect_grouped_column_medians_to_be_between(
  group_column="Drinks",
  value_column="Volume',
  medians={
    "Beer" : { "min_value" : 10, "max_value" : 20},
    "Wine" : { "min_value" : 100, "max_value" : 200},
    "Licors" : { "min_value" : 5, "max_value" : 15},
  }
)
```

**Comment by Thijsjahae** [comment]
Exactly! This would help a lot because I do not have to adapt my dataframe or create several JSON's.

**Comment by jpcampb2** [comment]
The use case of group_by makes a lot of sense to me, and seems to come up a lot. I definitely think there are a lot of ways to handle this, and we've been talking about a range of options.  I think the above is a lot cleaner than the below, but it does require adding lots of expectations.

Here are a couple additional (notional) suggestions:

This one introduces a new expectation `expect_column_group_expectation` that would create several new expectations...
```
my_df.expect_column_group_expectation("Drinks", expectation=expect_column_medians_to_be_between, column="Volume", parameters={
    "Beer" : { "min_value" : 10, "max_value" : 20},
    "Wine" : { "min_value" : 100, "max_value" : 200},
    "Licors" : { "min_value" : 5, "max_value" : 15},
  })
```

This one heavily uses parameters and is really ugly... :P
```
my_df.set_evaluation_parameters({
  "Beer_min": 10,
  "Beer_max": 20,
  "Wine_min": 100,
  "Wine_max": 200,
  "Licors_min": 5,
  "Licors_max: 15
})
my_df.expect_column_median_to_be_between(
    "Volume",
    preprocessing=group_by("Drinks"),
    min_value={"$PARAMETER": "$group{Drinks}_min"},
    max_value={"$PARAMETER": "$group{Drinks}_max"}
)
```
