### ISSUE TITLE
Building an index page for data docs takes too much time.

### ISSUE THREAD

**Issue by DemchenV** [fivetran/great_expectations#3732]
**Is your feature request related to a problem? Please describe.**
I have a bunch of expectation suites (40 and the number is growing) which are run every day. And one full run takes near 10 hours. I investigated why it takes so much time and realised that the longest part is the generation of index page for each of the expectation suite. Because I have a lot of data docs created earlier, and every time an index page is rendered for all of them and for new one.
Building an index page for one suite takes half an hour.

**Describe the solution you'd like**
Maybe I can somehow configure checkpoints for these suites for rendering index page after creating all of the data docs for my 40 expectation suites? Or maybe I can configure an incremental update for the index page, only for adding new data docs, without rendering a new index page for all history?

**Describe alternatives you've considered**
I found build_index parameter here - https://legacy.docs.greatexpectations.io/en/latest/autoapi/great_expectations/render/renderer/site_builder/index.html?highlight=DefaultSiteIndexBuilder.build
But I can't understand how to configure it in great_expectations.yml file and if it could help me.

**Comment by cdkini** [comment]
Hey @DemchenV! Thanks for posting this. Let me bring this up with the team to determine next steps.

**Comment by cdkini** [comment]
@DemchenV would you mind taking a look at the PR I've written? If you install the changes on that branch with `pip install -e .` and run `great_expectations --v3-api docs build --no-index`, you should be able to see if the new flag I've written speeds up the process.

It might need some refining (in the process of writing more tests) but I'm hoping it's a step in the right direction.

**Comment by DemchenV** [comment]
@cdkini I installed version from your branch and tested it in my local repo. I used this command:
`great_expectations --v3-api docs build -v --site-name test_site --no-index`
where test_site it's my test site in local repo.
As I understand, this command rendered new data docs for all validations, old and new? 

I can't test this on my prod data, because we have some custom tool for running GE checkpoint and I should ensure that new command won't ruin any other GE runs.

So, I changed one of checkpoint in my local repo, deleted step with updating data docs. I ran this checkpoint, after it I ran command:
`great_expectations --v3-api docs build -v --site-name test_site --no-index`
And now I want to build the index page for all these new docs, how can I do it?

**Comment by DemchenV** [comment]
And also I am sharing more info about why I think that the problem in building an index page. This is a part of logs from prod running:
2021-11-24T13:23:36.617+02:00 | 2021-11-24 11:23:36,575 EXO.exo.main - INFO: DefaultSiteIndexBuilder.build
2021-11-24T14:02:42.864+02:00 | 2021-11-24 12:02:42,839 EXO.exo.main - INFO: Found 2 data_docs_sites.
2021-11-24T14:02:43.235+02:00 | 2021-11-24 12:02:43,207 EXO.exo.main - INFO: Posted usage stats: message status 201
You can see that the DefaultSiteIndexBuilder.build step took time from 13:23:36 to 14:02:42.
So, I decided that the problem was in building the index page. If I am wrong, maybe we need a different solution.

**Comment by DemchenV** [comment]
Had some thoughts about a possible solution.
`docs build` rebuild all data docs, is it possible to create a command `docs update`, similar to UpdateDataDocsAction in validation action list? 
And if this command would be able to create data docs only for new validations? And has some parameters for incremental updating of an index page. It would be great and could solve my issue.

**Comment by cdkini** [comment]
Hey @DemchenV! We're looking into an `update` feature in the near future.

Do you happen to have this issue when you utilize checkpoints (and the associated `UpdateDataDocsAction`)? If you haven't tried that, would you mind doing so and letting me know if there's a performance gain?

I don't think this is an index page issue but rather a problem of recreating pages that already exists. The above solution might be the way to go for now until we find the engineering time to get a more robust solution in place.

**Comment by DemchenV** [comment]
@cdkini, I have an airflow job which runs a bunch of checkpoints with `UpdateDataDocsAction` step. 
I sent part of logs above, where I saw a very long duration of DefaultSiteIndexBuilder.build. So, if that doesn't mean that an index page was building for half an hour, what could be the reason?

**Comment by cdkini** [comment]
I've profiled the following code with 200 small expectation suites:
```python
context = ge.get_context()
context.build_data_docs()
```
<img width="2419" alt="Screen Shot 2021-12-02 at 12 10 30 PM" src="https://user-images.githubusercontent.com/49923762/144469880-ebeabc92-2ac2-4095-95e5-7d784d7ab456.png">

While the `build` method takes a long time to run, it is due to the rendering of the child pages. I think the actual creation of `index.html` is quite fast.

So how do we fix this? I think an `update` feature like you've mentioned is probably in order; we have some work in that direction here with https://github.com/great-expectations/great_expectations/pull/3752 but probably won't get to optimizing both validation and expectation suite site generation in the near future.

The `UpdateDataDocsAction` as part of Checkpoints is the closest thing to this proposed feature at the moment.

**Comment by cdkini** [comment]
Since this issue is duplicated by the discussion in https://github.com/great-expectations/great_expectations/issues/3396, I'm going to close this down.

Keep your eyes open for this feature down the line!
