### ISSUE TITLE
Argo Workflow Integration

### ISSUE THREAD

**Issue by xaraujo** [fivetran/great_expectations#3741]
**Is your feature request related to a problem? Please describe.**
Hi All, the request is not any problem. its just a new feature about the integration of GE with Argo as you have with Airflow and Flyte

It was mentioned in the discussion board a year ago, https://discuss.greatexpectations.io/t/can-i-use-great-expectations-in-an-argo-pipeline/515

This workflow manager is becoming more and more popular, so would be a very good asset have that integration.

Please consider

With Best Regards
Xavier

**Comment by cdkini** [comment]
Hey @xaraujo! Thanks for opening up this issue.

This seems like a great integration we'd love to have as part of our ecosystem but I'm afraid we don't currently have the bandwidth to devote engineering resources here. If this is something you would be interesting in contributing, we'd love to discuss it more and we would happily review any incoming PRs. Thanks!

**Comment by austiezr** [comment]
Hey @xaraujo ! Reaching out again to gauge your continued interest in this documentation, and to verify whether you have an interest in contributing on this.

**Comment by xaraujo** [comment]
Yes please close it.
I will do it later if I have time. Apologies for this.
