### ISSUE TITLE
Basic Dataset Profiler not working with Validator

### ISSUE THREAD

**Issue by roboverall** [fivetran/great_expectations#3746]
**Describe the bug**

BasicDatasetProfiler errors when the data_asset provided is of type ***Validator***.

`AttributeError: 'Validator'  object has no attribute 'get_table_columns'`

If I provide my in-memory spark dataframe as a ***Dataset*** it works as expected. 

However, in the source code the logic allows either a ***Dataset** or ***Validator*** to be passed.

`@classmethod
    def validate(cls, dataset):
        return isinstance(dataset, (Dataset, Validator))`

`if not cls.validate(data_asset):
            raise GreatExpectationsError("Invalid data_asset for profiler; aborting")
        expectation_suite = cls._profile(
            data_asset, configuration=profiler_configuration
        )`

The problem lies in the _profile method in the BasicDatasetProfiler class whereby it tries to call .get_table_columns() on a ***Validator***.

**To Reproduce**

Set up a context.

1. Imports
`from great_expectations.core.batch import BatchRequest, RuntimeBatchRequest`
`from great_expectations.profile.basic_dataset_profiler import `BasicDatasetProfiler`

2. Create batch request using RuntimeBatchRequest i.e. in-memory spark dataframe
`batch_request = RuntimeBatchRequest(
    datasource_name="my_spark_dataframe",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="wms-application-user",  # This can be anything that identifies this data_asset for you
    batch_identifiers={"batch_id": 3},
    runtime_parameters={"batch_data": df},  # Your dataframe goes here
)`

3. Create validator object
`validator = context.get_validator(
    batch_request=batch_request, expectation_suite_name="test-suite"
)`

4. Run Basic Dataset Profiler to return suite and validation result
`suite, validation_result = BasicDatasetProfiler().profile(validator, run_name="profiling")`

**Expected behavior**
A suite, validation_result to be returned from the BasicDatasetProfiler when a ***Validator*** is passed.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Hosted Environment: Databricks
 - Great Expectations Version: 0.13.43

**Additional context**

**Comment by cdkini** [comment]
Hey @roboverall! Thanks for opening up this issue.

Please note that the profiler you're using is specific to v2. We'd recommend looking into `UserConfigurableProfiler` or our Rule-Based Profiler if you'd like to achieve this functionality with v3. This should be achievable through the CLI.

I'm going to close this issue but please let us know if you run into any issues (check out #support in our Slack community).

**Comment by roboverall** [comment]
Thanks for the response @cdkini 

I wasn't aware this was specific to v2 so thanks for confirming.

I am trying to build a profiling results page that looks like the example in the documentation on **Data Discovery**.

https://docs.greatexpectations.io/docs/reference/data_discovery

I have since tried using the UserConfigurableProfiler to build this page but it doesn't quite render as per the BasicDataset profiler. Can I configure the UserConfigurableProfiler to work for this use case or will the BasicDatasetProfiler be available in v3 in the future?

**Comment by cdkini** [comment]
Ah unfortunately a 1-to-1 port of this functionality is not present in v3. We're not bringing this profiler to v3 but will be doing more work on profiling and metrics in the coming year to enable a better version of this functionality.

The actual contents of the validations page should be consistent but the overall layout is changed. Apologies if that causes any issues!

**Comment by roboverall** [comment]
That's a shame but excited to see what is released in the coming year on this. Thanks for your support!
