### ISSUE TITLE
Unknown datatypes INT and Varchar when creating expectation suites or checkpoints accessing Teradata tables

### ISSUE THREAD

**Issue by dsehnbru** [fivetran/great_expectations#3751]
**Describe the bug**

**To Reproduce**
1. Create a datasource accessing a Teradata DB
2. Create an expectation suite accessing a table of the Teradata DB created in step 1 bases on the profiler via the CLI. (the same happens when you create expectations for int and varchar columns manually and run a checkpoint against those and a teradata table)
3.  For columns with types int and varchar the output gives the message "No recognized sqlalchemy types in type_list for current dialect". 

**Expected behavior**
Given that the access to a teradata db via sqlalchemy works without any problemes based on the teradatasqlalchemy module, it should be possible to create expecations for all columns regardless of the data type.

**Environment (please complete the following information):**
 - Operating System: Windows 10
 - Great Expectations Version: 0.13.44

![teradata unknown datatypes int und varchar](https://user-images.githubusercontent.com/91957375/143549121-47126f25-9764-456a-b1db-e9cde5c47545.png)

**Comment by dsehnbru** [comment]
Describe the bug:

when creating expectation suites or checkpoints accessing Teradata tables GE will not recognize Int and Varchar data types

**Comment by austiezr** [comment]
Hey @dsehnbru! Thank you for raising this; we will review internally.

**Comment by austiezr** [comment]
Hey @dsehnbru! Thank you again for surfacing this issue. While we do have eyes on this, we are unfortunately unable to prioritize work here as GE for Teradata is still experimental and not fully supported. We would welcome a contribution in this area (@imamolp you may be interested in seeing this!), and we would be happy to offer guidance and review in support of any community efforts here.
