### ISSUE TITLE
Email Notification in V3

### ISSUE THREAD

**Issue by eggtart-destroyer** [fivetran/great_expectations#3753]
**Describe the bug**
Hi! I was following the How to trigger Email as a Validation Action part on the documentation. After adding the validation_operators part into the yml file and running checkpoint, it returns `You appear to be using a legacy capability with the latest config version (3.0).` No email was sent. It seems like validation operators will not work in the checkpoint? If this is the case, what should be used in v3 for email notification?

**To Reproduce**
1. Add the email notification code block as shown in the documentation site
2. run `great_expectations --v3-api checkpoint run getting_started_checkpoint`

**Expected behavior**
`You appear to be using a legacy capability with the latest config version (3.0).
    Your data context with this configuration version uses validation_operators, which are being deprecated.  Please consult the V3 API migration guide https://docs.greatexpectations.io/docs/guides/miscellaneous/migration_guide#migrating-to-the-batch-request-v3-api and update your configuration to be compatible with the version number 3.`

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.13.42

**Comment by eggtart-destroyer** [comment]
If anyone's wondering about the same issue, I put the `send_email_on_validation_result` code under action-list part of the checkpoint yml file and it now works. Cheers!

**Comment by austiezr** [comment]
Hey @eggtart-destroyer! Thanks for raising & closing; great to see you were able to resolve this!
