### ISSUE TITLE
PR #3722 broke compatibility with SQLAlchemy 1.3.24

### ISSUE THREAD

**Issue by hsheth2** [fivetran/great_expectations#3758]
**Describe the bug**

From the PR, the code uses:

```python
from sqlalchemy.engine import make_url
```

However, for SQLAlchemy 1.3.24 (and probably other versions as well), it should be:

```python
from sqlalchemy.engine.url import make_url
```

This issue produces import errors like this:

```
DatasourceInitializationError: Cannot initialize datasource my_sqlalchemy_datasource, error: Cannot initialize datasource my_sqlalchemy_datasource, error: ModuleNotFoundError: No module named 'sqlalchemy'
```

This was broken by #3722.

**To Reproduce**

See above.

**Expected behavior**

Import should work fine.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.44

**Additional context**

Given this PR from a month ago (#3499), it seems that supporting SQLAlchemy 1.3.24 is an explicit goal.

**Comment by austiezr** [comment]
Hey @hsheth2! Thanks for surfacing this; definitely unintended behavior. We'll review internally and respond soon!

**Comment by hsheth2** [comment]
Thanks for fixing, @austiezr!
