### ISSUE TITLE
Regex and like support in AthenaDialect

### ISSUE THREAD

**Issue by josges** [fivetran/great_expectations#3761]
**Is your feature request related to a problem? Please describe.**
Like and regex based expectations are currently raising a NotImplementedError when using AthenaDialect. This limits the usability when working with text columns.

**Describe the solution you'd like**
Implementation of `_get_dialect_regex_expression` and `_get_dialect_like_pattern_expression` for `pyathena.sqlalchemy_athena.AthenaDialect`.

**Describe alternatives you've considered**
I have been using `expect_column_values_to_be_in_set` which is kind of anoying for datasets where only the begining of the string is important.

**Comment by josges** [comment]
I am already working on this

**Comment by austiezr** [comment]
Hey @josges! Thanks for reaching out; super excited to see you've already begun a contribution in support of this! We'll discuss this issue internally and be in touch!
