### ISSUE TITLE
Ability to have additional columns in the unexpected_list result output

### ISSUE THREAD

**Issue by philgeorge999** [fivetran/great_expectations#3764]
I am applying many DQ checks to a table of approx 30M rows which I am validating using the Pyspark Dataframe GE API, and am frustrated that I cannot report on which rows have a problem - therefore it is not possible to direct the users towards investigating the problematic data.

The immediate problem is that unexpected_index_list is forced to None.  However even if it wasn't None, that wouldn't be particularly useful.

In my table I have a column called contract_id which includes a unique identifier for the bad row.  Also there is a contract_amount which shows us the relative value of this particular error.  I would like to be able to report the contract_ids back to the users, and also want to be able to report on the relative values.

Therefore I would like the ability to inject a list of 'meta column names' into the expectation call and then to have the relevant data returned in the output result structure.

If I were using Pandas dataframes I'd have an alternative approach of joining against the indexId list but that's not an option for me here as the data is too big, so we can't really proceed with GE unless some changes are made.

**Comment by austiezr** [comment]
Hey @philgeorge999! Thanks for surfacing this. We will review internally and be in touch.

**Comment by talagluck** [comment]
Hi, @philgeorge999! This appears to be a duplicate Issue with #3195, so we're going to close it for now, but if you feel differently, please feel free to re-open. We are planning on working on this over the next few weeks and will be in touch in the other Issue when this is implemented. Thanks!
