### ISSUE TITLE
Ability to include more useful aggregate metrics in the result object than just 'count' of failures

### ISSUE THREAD

**Issue by philgeorge999** [fivetran/great_expectations#3765]
In the result object from the expectation checks we currently see element_count, missing_count, missing_percent, unexpected_count, unexpected_percent.  However some DQ checks are more important than others.  In my case we are applying checks to contractual data and it would be very valuable to see which have potential monetary significance.

We have a contract_amount column in our data and for each DQ failure I would like to be able to report on SUM(ABS(contract_amount)) of failed rows  and 100*SUM(ABS(contract_amount)) of failed rows / SUM(ABS(contract_amount)) of all rows to help prioritise the issues.

If I were using the Pandas Dataframe API I could join the original dataset against the unexpected_index_list as a workaround and calculate SUMs there but in my case I am trying to use the Spark Dataframe API which has unexpected_index_list = None so I'm not able to produce this info at all at the moment.

I would like to see a feature where I can inject a spec of additional aggregate metrics I would like to see in the results output.

**Comment by austiezr** [comment]
Hey @philgeorge999! This is a super interesting use case; we'll review internally and be in touch. Is this something you be interested in contributing?

**Comment by talagluck** [comment]
Hi @philgeorge999! This is indeed really interesting. In terms of joining this to do the operation yourself, I believe this will be accomplished when #3195 is implemented.

As far as returning additional aggregate metrics, this could be accomplished with a custom expectation and custom metric which would implement what you are describing. Then when the results of the expectation are returned, this aggregate metric would be returned as well.

Realistically, this is not something that we will be able to prioritize in the immediate future. That said, we always welcome contributions, and are happy to offer guidance and support if this is something in which you are interested.
