### ISSUE TITLE
NotADirectoryError occurs when GE is installed in a zip file and build_data_docs() is called

### ISSUE THREAD

**Issue by joseignaciorc** [fivetran/great_expectations#3772]
**Describe the bug**
NotADirectoryError occurs when GE is installed in a zip file and build_data_docs() is called

<br>

**To Reproduce**

1: Have a very simple script named `my_great_expectations_script.py`
```py
from great_expectations.data_context import BaseDataContext
from great_expectations.data_context.types.base import DataContextConfig, DatasourceConfig, FilesystemStoreBackendDefaults
import great_expectations as ge
import tempfile

print(f"Great Expectations version: {ge.__version__}")
data_context_config = DataContextConfig(datasources={"example": DatasourceConfig(class_name="PandasDatasource")},
                                        store_backend_defaults=FilesystemStoreBackendDefaults(root_directory=tempfile.mkdtemp()+"/my_ge_workdir"))

context = BaseDataContext(project_config=data_context_config)
print(context.build_data_docs())

```

2: Install Great Expectations inside a ZIP file (following PEP 273).

```bash
python3.7 -m venv ge-venv

#base libraries provided by the system
./ge-venv/bin/pip install setuptools wheel numpy pandas scipy

#additional libraries go into a zip file
./ge-venv/bin/pip install great_expectations==0.13.44 -t extra_libraries_dir/
(cd extra_libraries_dir && zip -r ../extra_libraries.zip ./)

PYTHONPATH=./ge-venv/lib/python3.7/site-packages:extra_libraries.zip ./ge-venv/bin/python3 my_great_expectations_script.py
```
3: The following error occurs: 

> File "/home/josei/extra_libraries.zip/great_expectations/data_context/store/html_site_store.py", line 389, in copy_static_assets

> NotADirectoryError: [Errno 20] Not a directory: '/home/josei/extra_libraries.zip/great_expectations/data_context/store/../../render/view/static'

<br>

**Expected behavior**
The output should have been something like: 
> {'local_site': 'file:///tmp/tmp9j0kqa1h/my_ge_workdir/uncommitted/data_docs/local_site/index.html'}

<br>

**Environment (please complete the following information):**
 - Operating System: Linux
 - Python: 3.7
 - Great Expectations Version: 0.13.44
 - Reproducible in other environments

<br>

**Additional context**
Installing libraries like Great Expectations inside a Zip file is allowed by PEP 273 and recommended in some systems like AWS Glue (see [link](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html#aws-glue-programming-python-libraries-zipping)). I need this feature for my job, and I am working on a PR that fixes this issue :-)

**Comment by austiezr** [comment]
Hey @joseignaciorc! Thanks for surfacing this; excited to hear you're already working on a contribution!
