### ISSUE TITLE
Ability to disable progress bars for expectations

### ISSUE THREAD

**Issue by devdnhee** [fivetran/great_expectations#3775]
**Is your feature request related to a problem? Please describe.**
For my use case I need to run many expectations (eg. monitor quality on a fleet of devices). To disable the logging of progress bars on each expectation in my deployment the best solution I came up with is to monkey patch `great_expectations.validator.validator.validate.resolve_validation_graph`:
```
pbar = tqdm(...
                    #disable=len(graph.edges) < 3,
                    disable=True
                )
``` 
which is bad style and gets lost if I want to update the package

**Describe the solution you'd like**
extra boolean `progress_bar` attribute in `Validator`, which can be enabled in any function call that triggering expectations suites (for example checkpoints).

eg it would be nice if this would work:
```
checkpoint = SimpleCheckpoint(...)
checkpoint.run(..., progress_bar=False)
```

**Describe alternatives you've considered**
I've considered tqdm/tqdm#619 , but it doesn't work because the progress bar initialisation overwrites `disable` attribute

**Comment by talagluck** [comment]
Thanks for opening this issue @devdnhee - we will review and be in touch soon.

**Comment by cdkini** [comment]
@devdnhee this should be implemented as part of the above PR! I'll go ahead and close this down but please feel free to open a new issue if you run into any other problems.
