### ISSUE TITLE
Two new file expectations

### ISSUE THREAD

**Issue by anhollis** [fivetran/great_expectations#378]
Below is an attempt at addressing two of the potential file expectations mentioned in #321:

```
def expect_csv_file_line_column_delimiter_count_to_be_between(filename, min_count, max_count):
    success = True
    with open (filename,'r'):
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            if min_count is not None and len(row)<min_count:
                success=False
            if max_count is not None and len(row)>max_count:
                success=False
    return success
```

```
def expect_csv_file_line_column_delimiter_count_to_equal(filename, delimiter_count):
    success = True
    with open (filename,'r'):
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            if len(row) !=delimiter_count:
                success=False
    return success
```

Let me know if these expectations would be useful/worthwhile to add to the current set of file expectations. I welcome any feedback and suggestions on different ways of approaching these expectations.

**Comment by abegong** [comment]
These looks great. Three related questions:

(1) Naming conventions: are these specific to `csv`s? I'd lean towards `expect_file_line_column_delimiter_count_to_be_between`. This would allow us to take in pipe- and tab-delimited tabular formats, too.

(2) Can we parameterize the delimiters?`expect_file_line_column_delimiter_count_to_be_between(filename, delimiter, min_count, max_count)`

(3) If the expectation fails, what kind of helpful information can we retrieve? The number of failed rows? Delimiter counts in those rows...? If I know "This issue affects 100% / 20% / .001% of rows", I'd respond very differently.

**Comment by anhollis** [comment]
Thanks for the feedback! 

For question 1, I agree. The more general the text file the method can handle, the better. To answer question 2 as well, I was planning on including a **kwargs to allow the user to pass different keywords arguments for csv.reader() to the expectation. One such kwarg is a delimiter parameter. 

I agree that the information in part 3 should be returned to the user somehow. I know that for the pandas expectations, we had the column_map_expectation to compute these failure percentages. Are we planning on creating an overarching method similar to column_map_expectation for file expectations or do we want each file expectation to handle failure percentages on their own?

**Comment by abegong** [comment]
(1+2) I'm a bit leery of binding this expectation too tightly to `csv.reader()`. If all we're doing is checking the existence of delimiters, I don't think it makes sense to include kwargs for a specific function.

That said, I could imagine a separate Expectation: `expect_file_to_be_csv_reader_parseable`, similar to https://github.com/great-expectations/great_expectations/issues/375

(3) I'd put the logic in this expectation for now. If we find ourselves re-using it, we can factor it out later into its own decorator.

**Comment by anhollis** [comment]
Just to make sure I am understanding you correctly, you are thinking we should do something like the following:
```
def expect_csv_file_line_column_delimiter_count_to_equal(filename, delimiter, delimiter_count):
    success = True
    with open(filename,"r") as f:
        for line in f.readlines():
            if(line.count(delimiter) != delimiter_count):
                success=False
    return success
```
This would not rely on `csv.reader()`, but does the same thing. I think it would be good to have something like `expect_file_to_be_csv_reader_parseable` as well.

**Comment by abegong** [comment]
:+1:

**Comment by jpcampb2** [comment]
We had a quick conversation about this on our call today...

Propose:
1. expect_file_line_regex_match_count_to_be_between (ok with just be between vs also equal)
1. We refactor in the future to drop "file" since it will be redundant to a new type storage (see new inheritance hierarchy proposed in slack and #321)

**Comment by anhollis** [comment]
That all sounds good. I will go ahead and start working on building the expectation, and we can discuss the inheritance hierarchy at some point.
