### ISSUE TITLE
Possible enhancement to expect_table_columns_to_match_ordered_list

### ISSUE THREAD

**Issue by rlshuhart** [fivetran/great_expectations#379]
Hello,

First, thanks to all involved and contributing to the great_expectations project! This is a very valuable tool.

I ran into a potential opportunity to improve "expect_table_columns_to_match_ordered_list." I have a long python script blending various data sources and making calculations, and through this package I was able to discover that when the script runs in python 3.5 vs 3.6 it was developed in, two of the columns switch places and fails the column order expectation.  I've yet to figure out why this happens, but it did expose that there was an opportunity to improve the output of this great_expectations failure. While I knew it failed, it did not provide where it failed in the validation. It took a bit of debugging, but could have arrived sooner with an improved message.

I would be glad to tackle a pull request on this enhancement (if, indeed, it is agreeable that it would be) and welcome any feedback before starting. I would follow the contributing guidelines. 

Ryan

**Comment by abegong** [comment]
Yes, this sounds great---we welcome pull requests!

If you're looking for feedback before starting, let me suggest using this thread to mock up the exact output you're thinking of implementing. That'll let other respond before you put a bunch of time into development.

**Comment by rlshuhart** [comment]
Great!

My current thought is the below. 

```
    def expect_table_columns_to_match_ordered_list(self, column_list,
                               result_format=None, include_config=False, catch_exceptions=None, meta=None):

        if list(self.columns) == list(column_list):
            return {
                "success" : True
            }
        else:
            from itertools import zip_longest # <- this would move to the top of script
            position_index = range(len(column_list))
            compared_lists = list(zip_longest(position_index, list(column_list), list(self.columns)))
            mismatched = [{"Column Position": i, "Expected: ": k, "Found: ": v} for i, k, v in compared_lists if k != v]
            return {
                "success": False,
                "result": mismatched
            }
```

It would conceptually produce:

```
{
    "results": [
        {
            "result": [
                {
                    "Column Position": 2,
                    "Expected: ": "col_B",
                    "Found: ": "col_A"
                },
                {
                    "Column Position": 1,
                    "Expected: ": "col_A",
                    "Found: ": "col_B"
                },
                {
                    "Column Position":  null,
                    "Expected: ": null,
                    "Found: ": "new_column"
                }
            ],
           ...
}
```

Right now my test is my own data, so I would need to make a test with dummy data.

Looking forward to any feedback.

**Comment by ccnobbli** [comment]
I love this idea. My first reaction to the proposed output is that it is a bit clunky having a dictionary for each mismatched column.

Maybe something like this could work:
`result: {  "unexpected_list": { "col_B", "col_A"},  "unexpected_index": {1, 2 }, "expected_index": {2, 1}  }`

Although I do appreciate how your format includes the expected column in a clear way. I'm just wary about how much it differs from the standard GE format.

**Comment by rlshuhart** [comment]
Hi @ccnobbli, thanks for the feedback! I see what you mean. My output is a bit of a departure from the existing conventions. If I'm understanding the documentation correctly, I probably should stay within the result_format, like you were doing, described here: https://great-expectations.readthedocs.io/en/latest/result_format.html

Just a heads up, my wife is expecting to give birth any day now, so I might disappear for a couple weeks after that happens.

**Comment by rlshuhart** [comment]
I can't seem to find an existing test for this expectation. My search on GitHub within this repository for "def test_expect_table_columns_to_match_ordered_list" returned nothing. Could I get a pointer to where this function is tested? Thanks!

**Comment by ccnobbli** [comment]
it's in `tests/other_expectations/expect_table_columns_to_match_ordered_list_test_set.json`

GE has a unique test structure. The tests in the JSON file are essentially inputs and expected outputs to the expectation. Let us know if you have any questions about it

**Comment by rlshuhart** [comment]
Ah, got it. Thanks!

**Comment by ccnobbli** [comment]
Hey @rlshuhart ! Because this kind of expectation doesn't fit exactly fit into the "standard" expectations, deviating from the standard output format is not a big deal. The core dev team likes your proposed format for being explicit and that it would live nicely in the `details` field (which must be a _dictionary_, instead of a list):

```
 {
            "success":  True/False,
            "result":  {
                ....
               "details":  {
                     "a good name": [
                       {
                               "Column Position": 2,
                               "Expected: ": "col_B",
                               "Found: ": "col_A"
                       },
                       ......
                      ]
            },
           ...
}
```

**Comment by rlshuhart** [comment]
Message received. Thanks for the guidance!

**Comment by rlshuhart** [comment]
Thanks again! I think this can be closed.
