### ISSUE TITLE
Run checkpoint issue. Throws "catching classes that do not inherit from BaseException is not allowed"

### ISSUE THREAD

**Issue by x-thuang** [fivetran/great_expectations#3806]
**Describe the bug**
I used the --v3-api cli method for connecting to redshift, creating suite, creating checkpoint
The suite is only set with one expectation: `expect_column_values_to_be_between`
Then when I run this checkpoint:
`context.run_checkpoint(
    checkpoint_name="test_checkpoint1",  
    batch_request=None, 
    run_name=None
)`

It calculates midway then throws an exception:
```
Traceback (most recent call last):
  File "/Users/terryhuang/opt/anaconda3/lib/python3.8/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 798, in resolve_metric_bundle
    if isinstance(selectable, TextClause):
TypeError: isinstance() arg 2 must be a type or tuple of types

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/terryhuang/opt/anaconda3/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 397, in resolve_metrics
    new_resolved = self.resolve_metric_bundle(metric_fn_bundle)
  File "/Users/terryhuang/opt/anaconda3/lib/python3.8/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 811, in resolve_metric_bundle
    except OperationalError as oe:
TypeError: catching classes that do not inherit from BaseException is not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/terryhuang/opt/anaconda3/lib/python3.8/site-packages/great_expectations/validator/validator.py", line 710, in resolve_validation_graph
    self._resolve_metrics(
  File "/Users/terryhuang/opt/anaconda3/lib/python3.8/site-packages/great_expectations/validator/validator.py", line 1617, in _resolve_metrics
    return execution_engine.resolve_metrics(
  File "/Users/terryhuang/opt/anaconda3/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 400, in resolve_metrics
    raise ge_exceptions.MetricResolutionError(
great_expectations.exceptions.exceptions.MetricResolutionError: catching classes that do not inherit from BaseException is not allowed
```

**To Reproduce**
1. CLI >> `great_expectations --v3-api datasource new` with redshift db
2. CLI >> `great_expectations --v3-api suite new` with one `ExpectationConfiguration(ExpectationConfiguration="expect_column_values_to_be_between", ... )`
3. CLI >> `great_expectations --v3-api checkpoint new test_checkpoint1`
4. Then in .py
`context.run_checkpoint(
    checkpoint_name="test_checkpoint1",  
    batch_request=None, 
    run_name=None
)`

**Expected behavior**
The dataset only has 10 rows, 5 columns, filled with dummy data with simple values.
I expect the result to output something simple

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.44

**Additional context**
Data source:
```
name: {datasource_name}
class_name: Datasource
execution_engine:
  class_name: SqlAlchemyExecutionEngine
  credentials:
    host: {host}
    port: '{port}'
    username: {username}
    password: {password}
    database: {database}
    query:
      sslmode: prefer
    drivername: postgresql+psycopg2
data_connectors:
  default_runtime_data_connector_name:
    class_name: RuntimeDataConnector
    batch_identifiers:
      - default_identifier_name
  default_inferred_data_connector_name:
    class_name: InferredAssetSqlDataConnector
    name: whole_table
```

Expectation:
```
expectation_configuration = ExpectationConfiguration(
   expectation_type="expect_column_values_to_be_between",
   kwargs={
      "column": {col_name}",
      "min_value": 1,
      "max_value": 11
   },
)
suite.add_expectation(expectation_configuration=expectation_configuration)
```

checkpoint:
```
name: {my_checkpoint_name}
config_version: 1.0
class_name: SimpleCheckpoint
run_name_template: "%Y%m%d-%H%M%S-my-run-name-template"
validations:
  batch_request:
      datasource_name: {datasource}
      data_connector_name: default_inferred_data_connector_name
      data_asset_name: {table_name}
      data_connector_query:
        index: -1
    expectation_suite_name: {suite_name}
```

**Comment by austiezr** [comment]
Hey @x-thuang! Thanks for surfacing this; we'll review internally and reach back out.

**Comment by cdkini** [comment]
Hey @x-thuang! Would you mind letting me know what version of SQLAlchemy you're running? There are some nuances between 1.3 and 1.4 that might be causing this.

**Comment by terry152t** [comment]
Hi @cdkini, current version is: SQLAlchemy (1.3.23)

**Comment by cdkini** [comment]
@terry152t the issue seems to come from a faulty import; `TextClause` isn't being imported properly so it is being set to `None`. `isinstance` checks against `None` return the error you're seeing.

The above change should fix that error for you! I'll work on getting this merged but feel free to pull the branch and try for yourself if you'd like 😄

**Comment by cdkini** [comment]
@terry152t the PR will be merged shortly. I'll go ahead and close this issue but please feel free to reopen if you're still running into issues.
