### ISSUE TITLE
Ability to compare two column's values at a granular level (expect_column_values_to_match_set, with Evaluation Parameter functionality)

### ISSUE THREAD

**Issue by nateGarcia** [fivetran/great_expectations#3807]
**Is your feature request related to a problem? Please describe.**
I really need to be able to do a 1 to 1 comparison on my batch/sample of data against another query. This functionality seems definitely possible with the Evaluation Parameter feature (Which I love). GE has expectations that border on the line of this functionality, (e.g. `expect_column_pair_values_to_be_equal`), but either the result returned does not show me the unexpected/unmatched rows, or (in the case of the referenced expectation) the comparator field is not compatible to pass in a column of values from my Evaluation Parameter Query.

**Describe the solution you'd like**
I really need an expectation that can compare two columns (columnB being an Evaluation Parameter), and find the rows that are unmatched. It is important that this is a 1 to 1 comparison, as I would like to be able to perform this comparison with columns of integers; The column indices will have to match as there will most likely be duplicate values and the comparison will fail. I do not need any fancy renderer, but just the unexpected rows (`ColumnA, row30 != ColumnB, row30`). 

**Describe alternatives you've considered**
I have tried performing comparisons by configuring my batch to Union with another query and perform a comparison with `expect_column_proportion_of_unique_values_to_be_between`. This _has_ worked, but only with values that are uids or unique within their column already. I have failed to do a similar comparison with a column of `integers`. For example, using `expect_column_values_to_be_in_set` only checks a single column's value at a time against a pool of possible values. I need something like `expect_column_values_to_match_set`. Hopefully this is coming across clearly...

**Additional context**
I would be happy to contribute this expectation, or modify an existing one myself. However, I definitely need to be pointed in the right direction for how to do this. I wasn't sure how to do this based on the current documentation. Really looking forward to hearing from the team!

**Comment by austiezr** [comment]
Hey @nateGarcia! Thanks for reaching out. This is a super interesting use case, and we'd love to support a contribution here. 

We have some more robust documentation around this currently in progress; in the intervening time, I can point you to [this documentation](https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_expectations/), as well as [this artcile](https://medium.com/dataroots/how-to-write-custom-expectation-table-edition-9ffa8eb97464) contributed by another community member. I would also encourage you to browse some of the other [Contrib expectations](https://github.com/great-expectations/great_expectations/tree/develop/contrib/experimental/great_expectations_experimental/expectations) -- that was a big help for me in creating new expectations.

Happy to offer guidance and support as well, feel free to reach out!

**Comment by talagluck** [comment]
Hi @nateGarcia - could you please clarify a bit more about what you are trying to do here, and perhaps provide another example? Some of the use cases that you describe don't feel that far off from present functionality. Here are a few examples that come to mind:
- You could use `expect_column_values_to_be_in_set` where the set is populated by an evaluation parameter. 
- Another pattern that we recommend is doing some transformation prior to running Great Expectations, for instance, joining columns together that you would like to compare, or even potentially comparing two columns within a query, and running Great Expectations on the result of that query.
- I would think that `expect_column_pair_values_to_be_equal` would work, though it might require the use of the `include_unexpected_rows` flag in `result_format` (which has some warnings associated with it, but should be effective).

**Comment by nateGarcia** [comment]
Hello @talagluck !

As to your points,

**Comment by nateGarcia** [comment]
Hello @talagluck !
As to your points,

1. This metric only checks that observed_values match a value in the provided set. It does not flag when a value in the provided set DNE in the observed_values of my database table, making it out-of-scope for this use case.
2. This is what I am currently doing to check some values against an evaluation parameter with `expect_distinct_column_values_to_equal_set` (performing a similar transformation to data), but a metric that does the same for non-distinct values.
3. Please see this [slack](https://greatexpectationstalk.slack.com/archives/CUUMYDJAX/p1638283439020900?thread_ts=1636739954.308200&cid=CUUMYDJAX) thread. I do not see how to add the `include_unexpected_rows` flag in the documentation anywhere, could you provide some instructions here?

**Comment by nateGarcia** [comment]
Hello @talagluck ! Thanks for the response.
As to your points,

1. This metric only checks that observed_values match a value in the provided set. It does not flag when a value in the provided set DNE in the observed_values of my database table, making it out-of-scope for this use case.

2. This is what I am currently doing to check some values against an evaluation parameter (performing a similar transformation to data) with `expect_column_distinct_values_to_equal_set`. However, a metric that does the same for non-distinct values, e.g. a column with a set of possibly recurring integer values, will fit my use-case. I am verifying a calculation is being performed, so the indices must align with my provided `value_set`.

3. Please see [this](https://greatexpectationstalk.slack.com/archives/CUUMYDJAX/p1638283439020900?thread_ts=1636739954.308200&cid=CUUMYDJAX) slack thread. The columns are not in the same database, and I cannot pass an evaluation parameter because the field expects a str name.

 I had not noticed the `include_unexpected_rows` flag before! Does this flag apply to every metric, like `expect_column_distinct_values_to_equal_set`?

I hope this is clear. I would be happy to chat over zoom if it's easier.

**Comment by talagluck** [comment]
Hi @nateGarcia - I think I understand. For the first one, I wonder if `expect_column_kl_divergence_to_be_less_than` might be a roundabout way of achieving this.

`include_unexpected_rows` applies to all map metrics, and so would not apply for `expect_column_distinct_values_to_equal_set`.

I need to have a think about how to return a value in the provided set that doesn't match. This seems like it might be possible, but I need to work through the logistics. A zoom call might be a good idea - I'll ping you on Slack to set that up.

**Comment by talagluck** [comment]
Could you also unpack this a bit more?

> I have tried performing comparisons by configuring my batch to Union with another query and perform a comparison with expect_column_proportion_of_unique_values_to_be_between. This has worked, but only with values that are uids or unique within their column already. I have failed to do a similar comparison with a column of integers

I would think that this should work, and I'm curious where it fails.

**Comment by nateGarcia** [comment]
@talagluck 

>  Could you also unpack this a bit 

Of course! This workflow not preferable for non-distinct values, because I will definitely have repeated integers in my column, causing the check of proportional values to fail. Though it works well for unique or distinct values, using `expect_column_distinct_values_to_equal_set` is a much nicer implementation. Originally I was unaware of the better metric.

> I need to have a think about how to return a value in the provided set that doesn't match.

the `expect_column_distinct_values_to_equal_set` uses some `set` objects to assert that the `expected_set` and the `observed_set` are/aren't equal. `set` has the `.difference()` method that gathers the unexpected values from the two sets. I have tested the below code locally, and I get a list of unexpected values in stdout. However, I have no clue how to render this unexpected_set. In reference to these [lines](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py#L264-L280), I have added 
`unexpected_list = sorted(list(expected_value_set.difference(observed_value_set)))` on line `273` and I get the unexpected_list.

**Comment by nateGarcia** [comment]
@talagluck Do you have any thoughts on the `set.difference()` approach on `expect_column_distinct_values_to_equal_set`?

**Comment by talagluck** [comment]
Hi @nateGarcia - apologies, I lost track of this.

I think the approach you put forward makes a lot of sense. It sounds like this is missing two components to tie it all together:
1. The metric - for MapMetrics (metrics that are row-wise, like `column_values.in_set`), you get an `unexpected_list` automatically. However, you do not get this automatically for aggregate metrics, since in most cases, an aggregate metric is something more direct (like `column.mean`), which is then just directly compared to the Expectation kwargs. In this case, you would need to add a metric sort of like `distinct_values.equal_set.unexpected_count` (with a better name). It _may_ also be possible to just put this in the [return for the `validate` method](https://github.com/great-expectations/great_expectations/blob/c869dd44fa7b8a3bc5feddf90ad9ec9e476d2185/great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py#L282), but I'm not totally certain about this.
2. Once you have the metric accessible, you would update the renderers that reside in the Expectation file, which would make this available in data docs.

We've just done a pretty big rev on our Expectation contribution docs ([e.g. here](https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_metrics)). It wouldn't cover this exact use case, but it would be a good place to take a look in order to get started, and if you're interested, we could continue the conversation to help you along. We also have an Expectation hackathon currently under way, and I think it's reasonable for this to count as a contribution toward that.
