### ISSUE TITLE
Having a dark mode for DefaultJinjaIndexPageView or ValidationResultsPageRenderer

### ISSUE THREAD

**Issue by ierezell** [fivetran/great_expectations#3814]
**Is your feature request related to a problem? Please describe.**
More for a styling feature. 

**Describe the solution you'd like**
When using 
```python
# new_dataset is a great expectations PandasDataset
validation_result = new_dataset.validate(only_return_failures=True)
document_model = ValidationResultsPageRenderer().render(validation_result)
report = DefaultJinjaPageView().render(document_model)
HTML(report)
```

then the page appears white (which is fine). However all the rest of my environment is black / gray and it would be really nice to have a dark mode for those renderings.  

**Describe alternatives you've considered**
Keep it white and loose my eyes. 
Tweak the styling myself but I have no idea where to change it. 

**Additional context**
Using it in VsCode Jupyter built-in notebooks totally mess up with theming. 

Thanks in advance, 
Have a great day

**Comment by cdkini** [comment]
Hey @Ierezell thanks so much for opening this up. We'll take a look into this matter and see what we can do in regards to dark mode. Appreciate your patience!
