### ISSUE TITLE
Parsing error when using $PARAMETER with ExpectationConfiguration or as an EvaluationParameter

### ISSUE THREAD

**Issue by andersonterry** [fivetran/great_expectations#3816]
**Describe the bug**
Exception when trying to use $PARAMETER via evaluation parameters or expectation configuration;  "can only concatenate str (not \"int\") to str"

**To Reproduce**
1. set up expectation configuration with kwargs that specify min/max value for a column
2. attempt to run a validation for it (below)
3. See error (details below)

**Expected behavior**
Expected parameter to evaluate as it's type (int, long, etc) or at least as a string, e.g. "$PARAMETER": str(myIntValueHere) either either the expectation configuration kwarg, or the evaluation parameters

**Environment (please complete the following information):**
 - Azure DataBricks / dbfs / in memory DataFrame
 - Great Expectations Version: 0.13.45

**Additional context**

I'm seeing the same/similar issue as follows...I get the same (Azure DataBricks with in memory DF) whether specifying the $PARAMETER via the ExpectationConfiguration or as an Evaluation Parameter... in other words, the same issue repros using this syntax:

maxyear = 2020
minyear = 2000

print(df_ge.expect_column_values_to_be_between(
  min_value={
    "$PARAMETER": "str(minyear)"
  },
  max_value={
    "$PARAMETER": "str(maxyear)"
  },
  result_format={
    'result_format':'BOOLEAN_ONLY'
  }
))

___________________________________________

maxyear = 2020
minyear = 2000
ec_year_range = ExpectationConfiguration(**{
  "expectation_type":"expect_column_values_to_be_between",
  "kwargs":{
    "column": "year",
    "max_value": {
      "$PARAMETER": maxyear
    },
    "min_value": {
      "$PARAMETER": minyear
    }
  },
  "meta":{}
})
myTestSuite = context.create_expectation_suite("myTestSuite", overwrite_existing=True)
myTestSuite.add_expectation(expectation_configuration=ec_year_range, match_type="domain")
context.save_expectation_suite(expectation_suite=myTestSuite, expectation_suite_name="myTestSuite")

#TODO:  with the expectationSuite good to go, is it possible to call context.get_validator() here, or is the RuntimeBatchRequest (from the DataConnectors[] above) required??

print(df_ge.validate(expectation_suite=myTestSuite, evaluation_parameters={
  "min_value": minyear,
  "max_value": maxyear
}))

Here are the <b>results</b> produced:
{
  "evaluation_parameters": {
    "min_value": 2000,
    "max_value": 2020
  },
  "meta": {
    "great_expectations_version": "0.13.45",
    "expectation_suite_name": "myTestSuite",
    "run_id": {
      "run_time": "2021-12-08T17:36:22.398987+00:00",
      "run_name": null
    },
    "batch_kwargs": {
      "ge_batch_id": "ada60a5e-5848-11ec-9adb-00163e1124c6"
    },
    "batch_markers": {},
    "batch_parameters": {},
    "validation_time": "20211208T173622.398921Z",
    "expectation_suite_meta": {
      "great_expectations_version": "0.13.45"
    }
  },
  "results": [
    {
      "result": {},
      "exception_info": {
        "raised_exception": true,
        "exception_traceback": "Traceback (most recent call last):\n  File \"/local_disk0/pythonVirtualEnvDirs/virtualEnv-3ce10690-5a78-4517-bf4d-83bb9e27339f/lib/python3.7/site-packages/great_expectations/data_asset/data_asset.py\", line 930, in validate\n    self._data_context,\n  File \"/local_disk0/pythonVirtualEnvDirs/virtualEnv-3ce10690-5a78-4517-bf4d-83bb9e27339f/lib/python3.7/site-packages/great_expectations/core/evaluation_parameters.py\", line 222, in build_evaluation_parameters\n    if \"$PARAMETER.\" + **value[\"$PARAMETER\"] **in value:\nTypeError: can only concatenate str (not \"int\") to str\n",****
        "exception_message": "can only concatenate str (not \"int\") to str"
      },
      "meta": {},
      "success": false,
      "expectation_config": {
        "kwargs": {
          "column": "year",
          "max_value": {
            "$PARAMETER": 2020
          },
          "min_value": {
            "$PARAMETER": 2000
          }
        },
        "expectation_context": {
          "description": null
        },
        "expectation_type": "expect_column_values_to_be_between",
        "meta": {},
        "ge_cloud_id": null
      }
    }
  ],
  "success": false,
  "statistics": {
    "evaluated_expectations": 1,
    "successful_expectations": 0,
    "unsuccessful_expectations": 1,
    "success_percent": 0.0
  }
}

**Comment by cdkini** [comment]
Hey @andersonterry thanks for opening up this issue.

At first glance, I think the issue may stem from the following configuration:
```python
min_value={
"$PARAMETER": "str(minyear)"
},
max_value={
"$PARAMETER": "str(maxyear)"
},
```

`expect_column_values_to_be_between` only supports numeric values for `min_value` and `max_value`; as such, the issue you're seeing might be resulting from that. Would you mind trying this without casting to a string and seeing if that fixes your issue?

**Comment by andersonterry** [comment]
It continues to error altogether, based upon the implied type passed (float v int here)

#TypeError: can only concatenate str (not "float") to str
maxyear = 2020.0
minyear = 2000.0


#TypeError: can only concatenate str (not "int") to str
maxyear = 2000
minyear = 1999

print(df_ge.expect_column_values_to_be_between(
  min_value={
    "$PARAMETER": minyear
  },
  max_value={
    "$PARAMETER": maxyear
  },
  result_format={
    'result_format':'BOOLEAN_ONLY'
  }
))



#Additionally, seeing exact same results with the alternative ExpectationConfiguration syntax…



maxyear = 2020.0
minyear = 2000.0

ec_year_range = ExpectationConfiguration(**{
  "expectation_type":"expect_column_values_to_be_between",
  "kwargs":{
    "column": "year",
    "max_value": {
      "$PARAMETER": maxyear
    },
    "min_value": {
      "$PARAMETER": minyear
    }
  },
  "meta":{}
})



From: Chetan Kini ***@***.***>
Sent: Friday, December 10, 2021 11:24 AM
To: great-expectations/great_expectations ***@***.***>
Cc: Anderson, Terry ***@***.***>; Mention ***@***.***>
Subject: EXTERNAL EMAIL: Re: [great-expectations/great_expectations] Parsing error when using $PARAMETER with ExpectationConfiguration or as an EvaluationParameter (Issue #3816)

EXTERNAL EMAIL: Do not click any links or open any attachments unless you trust the sender and know the content is safe.



Hey @andersonterry<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fandersonterry&umid=3b3ad78d-977a-4e2f-a9d8-3d2adab0ba7c&auth=732345bef31a784e2798e5a08f43be53a71196f3-bb9e3c5660e3d6bad1740e3ef231b5cd73120e67> thanks for opening up this issue.

At first glance, I think the issue may stem from the following configuration:

min_value={

"$PARAMETER": "str(minyear)"

},

max_value={

"$PARAMETER": "str(maxyear)"

},

expect_column_values_to_be_between only supports numeric values for min_value and max_value; as such, the issue you're seeing might be resulting from that. Would you mind trying this without casting to a string and seeing if that fixes your issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fgreat%2dexpectations%2fgreat%5fexpectations%2fissues%2f3816%23issuecomment%2d991155356&umid=3b3ad78d-977a-4e2f-a9d8-3d2adab0ba7c&auth=732345bef31a784e2798e5a08f43be53a71196f3-1fa1ecbe8c0aaa6ddcf236621fa4d75613295b4a>, or unsubscribe<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2dauth%2fAT7GYVKCH32WIHDCTU3V6YDUQIZURANCNFSM5JUMT6YQ&umid=3b3ad78d-977a-4e2f-a9d8-3d2adab0ba7c&auth=732345bef31a784e2798e5a08f43be53a71196f3-8ea7628a4f35557d45e26aeda9136c01cbad5a3f>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by cdkini** [comment]
@andersonterry I believe the issue here is how the evaluation parameters are being passed in.

The expected usage is something like this:
```python
my_df.expect_column_values_to_be_in_set("my_column", value_set={"$PARAMETER": "runtime_values"})
my_df.validate(evaluation_parameters={"runtime_values": [1, 2, 3]})
```

Evaluation parameters are used to share state various stages of the GE workflow (i.e. the result of an expectation). If you know your value in advance and just want to pass them in, evaluation parameters are not necessary. 

```python
expect_column_values_to_be_between(
    column="passenger_count",
    min_value=1,
    max_value=6
)
```

Does that make sense? Our documentation around evaluation parameters are in need of some work so apologies for the confusion.

**Comment by andersonterry** [comment]
Ok, I must not be following along at all here…I get this error with both of these simple examples:

EvaluationParameterError: No value found for $PARAMETER runtime_minvalue


# https://greatexpectations.io/expectations/expect_table_row_count_to_equal
df_ge.expect_table_row_count_to_equal(value={"$PARAMETER": "runtime_values"})
df_ge.validate(evaluation_parameters={"runtime_values": 50})

# https://greatexpectations.io/expectations/expect_column_values_to_be_between
df_ge.expect_column_values_to_be_between("year", min_value={"$PARAMETER": "runtime_minvalue"}, max_value={"$PARAMETER": "runtime_maxvalue"})
df_ge.validate(evaluation_parameters={"runtime_minvalue": 1990, "runtime_maxvalue": 2000})



From: Chetan Kini ***@***.***>
Sent: Thursday, December 16, 2021 4:01 PM
To: great-expectations/great_expectations ***@***.***>
Cc: Anderson, Terry ***@***.***>; Mention ***@***.***>
Subject: EXTERNAL EMAIL: Re: [great-expectations/great_expectations] Parsing error when using $PARAMETER with ExpectationConfiguration or as an EvaluationParameter (Issue #3816)

EXTERNAL EMAIL: Do not click any links or open any attachments unless you trust the sender and know the content is safe.



@andersonterry<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fandersonterry&umid=2f775e02-2b75-4c38-adcf-07daaf72d7a3&auth=ae405231a53ab09394c93e61658595d0ed548af8-c70147b3877ee58a709381a17baa53d643079b46> I believe the issue here is how the evaluation parameters are being passed in.

The expected usage is something like this:

my_df.expect_column_values_to_be_in_set("my_column", value_set={"$PARAMETER": "runtime_values"})

my_df.validate(evaluation_parameters={"runtime_values": [1, 2, 3]})

Evaluation parameters are used to share state various stages of the GE workflow (i.e. the result of an expectation). If you know your value in advance and just want to pass them in, evaluation parameters are not necessary.

expect_column_values_to_be_between(

    column="passenger_count",

    min_value=1,

    max_value=6

)

Does that make sense? Our documentation around evaluation parameters are in need of some work so apologies for the confusion.

—
Reply to this email directly, view it on GitHub<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fgreat%2dexpectations%2fgreat%5fexpectations%2fissues%2f3816%23issuecomment%2d996226923&umid=2f775e02-2b75-4c38-adcf-07daaf72d7a3&auth=ae405231a53ab09394c93e61658595d0ed548af8-45d2546fb86a4a094aa0bce909ba7a6890e1f3f5>, or unsubscribe<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2dauth%2fAT7GYVPPU62IUTKVECSAJCTURJOTPANCNFSM5JUMT6YQ&umid=2f775e02-2b75-4c38-adcf-07daaf72d7a3&auth=ae405231a53ab09394c93e61658595d0ed548af8-9af0001079ee83266c2ed9376ef1e40cd3bb0461>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by cdkini** [comment]
Apologies for the delayed response here @andersonterry I was out on holiday. 

If you're using a validator, you can also set parameters with `Validator.get_evaluation_parameters(parameter_name, parameter_value)`. I'm working on bolstering this documentation but won't be able to get around to it in the near future.

Since the underlying issue with string concatenation is fixed, I'm going to go ahead and close this issue. If you're still running into problems, please let us know through Slack or another issue. Thanks!
