### ISSUE TITLE
AttributeError related to missing get_batch on run_validation_operator()

### ISSUE THREAD

**Issue by andersonterry** [fivetran/great_expectations#3817]
**Describe the bug**
Receiving a dataContextConfig error (AttributeError: 'Datasource' object has no attribute 'get_batch') when executing run_validation_operator against the batch specified

**To Reproduce**
1. Execute dataContextConfig below
2. Create/Save expectation suite to context
3. run_validation_operator()
4. See error:  AttributeError: 'Datasource' object has no attribute 'get_batch'

**Expected behavior**
Expected run_validation_operator() to succeed against the specified batch, and dataContextConfiguration

**Environment (please complete the following information):**
 - Azure DataBricks / PySpark 3.9
 - Great Expectations Version:  0.13.45

**Additional context**

datasource_BaseDirectory = "/mnt/rawzone/ClaimsTemp/"
datacontext_RootDirectory = "/mnt/"
  
#https://great-expectations.readthedocs.io/en/latest/reference/core_concepts/datasource.html#reference-core-concepts-datasources  
data_context_config = DataContextConfig(
    datasources={
      "mySparkDataSource": DatasourceConfig(
      class_name="Datasource",
      module_name="great_expectations.datasource",
      execution_engine={
          "class_name": "SparkDFExecutionEngine",
          "module_name": "great_expectations.execution_engine"
      },
      data_connectors={
          "myDataConnector":{
            "module_name": "great_expectations.datasource.data_connector",
            "class_name": "ConfiguredAssetFilesystemDataConnector",
            "glob_directive": "*.csv",
            "base_directory": datasource_BaseDirectory,
            "default_regex" :{
              "pattern": r"(.*).csv"
            },
            "assets":{
              "asset_Vehicles":{
                "base_directory": datasource_BaseDirectory,
                "pattern": "*.csv"
              }
            }
          }
        }
     )
   },
store_backend_defaults=FilesystemStoreBackendDefaults(root_directory=datacontext_RootDirectory),
)

context = BaseDataContext(project_config=data_context_config)

myTestSuite = context.create_expectation_suite("myTestSuite", overwrite_existing=True)
context.save_expectation_suite(expectation_suite=myTestSuite, expectation_suite_name="myTestSuite")

#https://great-expectations.readthedocs.io/en/latest/guides/how_to_guides/validation/how_to_validate_data_without_a_checkpoint.html?highlight=validate

# If you would like to validate in a PySpark or Pandas dataframe:
batch_kwargs = {'dataset': "df_ge", 'datasource': "mySparkDataSource"}
batch = context.get_batch(batch_kwargs, "myTestSuite")

results = context.run_validation_operator(
    "action_list_operator",
    assets_to_validate=[batch],
    run_id="tanderson2_test")

___________________________________

RESULTS

AttributeError: 'Datasource' object has no attribute 'get_batch'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-3905834515094480> in <module>
      6 # If you would like to validate in a PySpark or Pandas dataframe:
      7 batch_kwargs = {'dataset': "df_ge", 'datasource': "mySparkDataSource"}
----> 8 batch = context.get_batch(batch_kwargs, "myTestSuite")
      9 
     10 results = context.run_validation_operator(

/local_disk0/pythonVirtualEnvDirs/virtualEnv-3ce10690-5a78-4517-bf4d-83bb9e27339f/lib/python3.7/site-packages/great_expectations/data_context/data_context.py in get_batch(self, arg1, arg2, arg3, **kwargs)
   1560             expectation_suite_name=expectation_suite_name,
   1561             data_asset_type=data_asset_type,
-> 1562             batch_parameters=batch_parameters,
   1563         )
   1564 

/local_disk0/pythonVirtualEnvDirs/virtualEnv-3ce10690-5a78-4517-bf4d-83bb9e27339f/lib/python3.7/site-packages/great_expectations/data_context/data_context.py in _get_batch_v2(self, batch_kwargs, expectation_suite_name, data_asset_type, batch_parameters)
   1253 
   1254         datasource = self.get_datasource(batch_kwargs.get("datasource"))
-> 1255         batch = datasource.get_batch(
   1256             batch_kwargs=batch_kwargs, batch_parameters=batch_parameters
   1257         )

AttributeError: 'Datasource' object has no attribute 'get_batch'

**Comment by cdkini** [comment]
Hey @andersonterry thanks for opening up this issue! After reviewing your config, I believe the issue here is that you're utilizing batch kwargs with a v3-styled datasource. 

In v3, the recommended approach to to create batch requests; here is a link to our docs that might be of use: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/filesystem/spark

Additionally, we recommend that users move away from validation operators and instead use `checkpoint.run()` or `DataContext.run_checkpoint()` with v3.

**Comment by andersonterry** [comment]
Ok, I did this to be fully v3 compliant, and still get an error with the ConfiguredAssetFilesystemDataConnector data source/connector as follows;  the error messages in Azure DataBricks notebooks are pretty sketchy… any ideas?

Also note the regEx;  the batch file structure is such that there will only ever been one target file per folder.

Thanks!!


# DocRef:

# https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_configure_a_configuredassetdataconnector


# ERROR

OSError: [Errno 36] File name too long: '/mnt/raw/twosigma/great_expectations/checkpoints/\nname: my_checkpoint_test\nconfig_version: 1\nclass_name: SimpleCheckpoint\nrun_name_template: "%Y%m%d-%H%M%S-my-run-name-template"\nvalidations:\n  - batch_request:\n      datasource_name: mySparkDataSource\n      data_connector_name: myDataConnector\n      data_asset_name: asset_Vehicles\n      data_connector_query:\n        index: -1\n    expectation_suite_name: myTestSuite\n.yml'

#  DETAILS

# CSV options
file_type = "csv"
infer_schema = "false"
first_row_is_header = "true"
delimiter = "{"

df = spark.read.format(file_type) \
    .option("inferSchema", infer_schema) \
.option("header", "true")\
    .option("header", first_row_is_header) \
.option("sep", ",")\
    .load(file_location)


# Create a DataContext in code from a DataContextConfig with DatasourceConfig
datacontext_RootDirectory = "/mnt/raw/twosigma/great_expectations/"
datasource_VehiclesDirectory = "/mnt/raw/twosigma/pls_vehicles/"

# sample target file:   /dbfs/mnt/raw/twosigma/pls_vehicles/2021/09/22/07/48/vehicles.csv

my_spark_data_context_config = DataContextConfig(
    datasources={
      "mySparkDataSource": DatasourceConfig(
      class_name="Datasource",
      module_name="great_expectations.datasource",
      execution_engine={
          "class_name": "SparkDFExecutionEngine",
          "module_name": "great_expectations.execution_engine"
      },
      data_connectors={
          "myDataConnector":{
            "module_name": "great_expectations.datasource.data_connector",
            "class_name": "ConfiguredAssetFilesystemDataConnector",
            "glob_directive": "*.csv",
            "base_directory": datasource_VehiclesDirectory,
            "assets":{
              "asset_Vehicles":{
                "base_directory": datasource_VehiclesDirectory,
                "pattern":  r"(\d{4})/(\d{2})/(\d{2})/(\d{2})/(\d{2}/)vehicles\.csv",
                "group_names": ["year", "month", "day", "hour", "minute"]
              }
            }
          }
        }
     )
   },
store_backend_defaults=FilesystemStoreBackendDefaults(root_directory=datacontext_RootDirectory),
)

context = BaseDataContext(project_config=my_spark_data_context_config)
context.list_datasources()

# <output>

Out[33]: [{'class_name': 'Datasource',
  'execution_engine': {'class_name': 'SparkDFExecutionEngine',
   'module_name': 'great_expectations.execution_engine'},
  'module_name': 'great_expectations.datasource',
  'data_connectors': {'myDataConnector': {'class_name': 'ConfiguredAssetFilesystemDataConnector',
    'base_directory': '/mnt/raw/twosigma/pls_vehicles/',
    'module_name': 'great_expectations.datasource.data_connector',
    'assets': {'asset_Vehicles': {'base_directory': '/mnt/raw/twosigma/pls_vehicles/',
      'pattern': '(\\d{4})/(\\d{2})/(\\d{2})/(\\d{2})/(\\d{2}/)vehicles\\.csv',
      'group_names': ['year', 'month', 'day', 'hour', 'minute']}},
    'glob_directive': '*.csv'}},
  'name': 'mySparkDataSource'}]




# Expectation(s)

maxyear = 2020.0
minyear = 2000.0

ec_year_range = ExpectationConfiguration(**{
  "expectation_type":"expect_column_values_to_be_between",
  "kwargs":{
    "column": "year",
    "max_value": {
      "$PARAMETER": maxyear
    },
    "min_value": {
      "$PARAMETER": minyear
    }
  },
  "meta":{}
})

myTestSuite = context.create_expectation_suite("myTestSuite", overwrite_existing=True)
myTestSuite.add_expectation(expectation_configuration=ec_year_range, match_type="domain")
context.save_expectation_suite(expectation_suite=myTestSuite, expectation_suite_name="myTestSuite")



#  v3 uses RuntimeBatchRequest; leveraging the sparkDF here
rtb_request = RuntimeBatchRequest(
    datasource_name="mySparkDataSource",
    data_connector_name="myDataConector",
    data_asset_name="asset_Vehicles",
    runtime_parameters={
      "batch_data": df
    },
    batch_identifiers={
      "myTestBatch": 1234567890
    }
)


my_checkpoint_config = f"""
name: my_checkpoint_test
config_version: 1
class_name: SimpleCheckpoint
run_name_template: "%Y%m%d-%H%M%S-my-run-name-template"
validations:
  - batch_request:
      datasource_name: mySparkDataSource
      data_connector_name: myDataConnector
      data_asset_name: asset_Vehicles
      data_connector_query:
        index: -1
    expectation_suite_name: myTestSuite
"""

# This is v3;  use checkpoint.run() or context.run_checkpoint()
result: CheckpointResult = context.run_checkpoint(
  checkpoint_name=my_checkpoint_config,
  batch_request=rtb_request,
  run_name="myCheckpoint_testRun_01"
)

  #/dbfs/mnt/raw/twosigma/pls_vehicles/2021/09/22/07/48/vehicles.csv


  # <output>

  OSError: [Errno 36] File name too long: '/mnt/raw/twosigma/great_expectations/checkpoints/\nname: my_checkpoint_test\nconfig_version: 1\nclass_name: SimpleCheckpoint\nrun_name_template: "%Y%m%d-%H%M%S-my-run-name-template"\nvalidations:\n  - batch_request:\n      datasource_name: mySparkDataSource\n      data_connector_name: myDataConnector\n      data_asset_name: asset_Vehicles\n      data_connector_query:\n        index: -1\n    expectation_suite_name: myTestSuite\n.yml'




From: Chetan Kini ***@***.***>
Sent: Friday, December 10, 2021 11:20 AM
To: great-expectations/great_expectations ***@***.***>
Cc: Anderson, Terry ***@***.***>; Mention ***@***.***>
Subject: EXTERNAL EMAIL: Re: [great-expectations/great_expectations] AttributeError related to missing get_batch on run_validation_operator() (Issue #3817)

EXTERNAL EMAIL: Do not click any links or open any attachments unless you trust the sender and know the content is safe.



Hey @andersonterry<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fandersonterry&umid=3d72fcc0-9457-4560-8d56-1c49887e74ba&auth=ae405231a53ab09394c93e61658595d0ed548af8-35cf141162a7c6a3fb696003011f4bf7000e9b46> thanks for opening up this issue! After reviewing your config, I believe the issue here is that you're utilizing batch kwargs with a v3-styled datasource.

In v3, the recommended approach to to create batch requests; here is a link to our docs that might be of use: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/filesystem/spark

Additionally, we recommend that users move away from validation operators and instead use checkpoint.run() or DataContext.run_checkpoint() with v3.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fgreat%2dexpectations%2fgreat%5fexpectations%2fissues%2f3817%23issuecomment%2d991152530&umid=3d72fcc0-9457-4560-8d56-1c49887e74ba&auth=ae405231a53ab09394c93e61658595d0ed548af8-977c08ea79122f76bfcdb297bcd513dbbf1c43ef>, or unsubscribe<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2dauth%2fAT7GYVP5TFLSNP37BBEKOY3UQIZFZANCNFSM5JUQSXGQ&umid=3d72fcc0-9457-4560-8d56-1c49887e74ba&auth=ae405231a53ab09394c93e61658595d0ed548af8-29cf850d062e25c167d8e91220d7ec493127c726>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
