### ISSUE TITLE
ConfiguredAsset data source does not find named group RegEx asset, and generates schema error

### ISSUE THREAD

**Issue by andersonterry** [fivetran/great_expectations#3829]
**Describe the bug**
Testing the following yaml dataSource specification yields a schema error, and the output does NOT indicate that the expected asset (csv file) was identfied.

**To Reproduce**
1. define the ds as indicated below
2. execute yaml test and config list
3. observe results (also below) in cell output
4.  (a)  asset not located, and (b) schema error

**Expected behavior**
1.)  Expected single csv asset to be picked up by the dataSource spec:

	Available data_asset_names (1 of 1):
		asset_Vehicles (0 of 0): []

	Unmatched data_references (0 of 0):[]

2.)  No schema error:

Error while processing DataContextConfig: _schema
InvalidDataContextConfigError: Error while processing DataContextConfig: _schema

**Environment (please complete the following information):**
 - Azure DataBricks / PySpark
 - Great Expectations Version: [ 0.13.45]

**Additional context**

```python
datasource_VehiclesDirectory = "/dbfs/mnt/raw/twosigma/pls_vehicles/"
# actual file location is:    /dbfs/mnt/raw/twosigma/pls_vehicles/2021/09/22/07/48/vehicles.csv
my_configured_datasource_config_yaml = r"""
name: mySparkDataSource_configured
class_name: Datasource
module_name: great_expectations.datasource
execution_engine:
  module_name: great_expectations.execution_engine
  class_name: SparkDFExecutionEngine
data_connectors:
  myDataConnector_configured:
    class_name: ConfiguredAssetFilesystemDataConnector
    base_directory: datasource_VehiclesDirectory
    assets:
      asset_Vehicles:
        pattern: (?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<hour>\d{2})/(?P<minute>\d{2}/)vehicles\.csv
        group_names:
          - year
          - month
          - day
          - hour
          - minute
"""

# test the datasource
context.test_yaml_config(my_configured_datasource_config_yaml) 
context = BaseDataContext(project_config=my_configured_datasource_config_yaml)

# test the available datasources as configured
context.list_datasources()
```

RESULTS

Attempting to instantiate class from config...
	Instantiating as a Datasource, since class_name is Datasource
	Successfully instantiated Datasource

ExecutionEngine class name: SparkDFExecutionEngine
Data Connectors:
	myDataConnector_configured : ConfiguredAssetFilesystemDataConnector

	Available data_asset_names (1 of 1):
		asset_Vehicles (0 of 0): []

	Unmatched data_references (0 of 0):[]

Error while processing DataContextConfig: _schema
InvalidDataContextConfigError: Error while processing DataContextConfig: _schema
---------------------------------------------------------------------------
InvalidDataContextConfigError             Traceback (most recent call last)
<command-528770991276879> in <module>
     68 # test the datasource
     69 context.test_yaml_config(my_configured_datasource_config_yaml)
---> 70 context = BaseDataContext(project_config=my_configured_datasource_config_yaml)
     71 
     72 # test the available datasources as configured

/local_disk0/pythonVirtualEnvDirs/virtualEnv-38cb63e1-40fb-4a86-be6a-4c8ec4fe2b07/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py in usage_statistics_wrapped_method(*args, **kwargs)
    284                     nested_update(event_payload, args_payload_fn(*args, **kwargs))
    285 
--> 286                 result = func(*args, **kwargs)
    287                 message["success"] = True
    288             except Exception:

/local_disk0/pythonVirtualEnvDirs/virtualEnv-38cb63e1-40fb-4a86-be6a-4c8ec4fe2b07/lib/python3.7/site-packages/great_expectations/data_context/data_context.py in __init__(self, project_config, context_root_dir, runtime_environment, ge_cloud_mode, ge_cloud_config)
    326             None
    327         """

**Comment by cdkini** [comment]
Hey @andersonterry! Thanks so much for opening up this issue.

Let me review the contents of your config and bring up this matter with our engineering team.

**Comment by cdkini** [comment]
@andersonterry we didn't explicitly have support for named groups before - the above PR should remedy your issue. Would you mind seeing if that is the case?

**Comment by andersonterry** [comment]
I will have a look at this – thanks!!

From: Chetan Kini ***@***.***>
Sent: Wednesday, December 15, 2021 10:06 AM
To: great-expectations/great_expectations ***@***.***>
Cc: Anderson, Terry ***@***.***>; Mention ***@***.***>
Subject: EXTERNAL EMAIL: Re: [great-expectations/great_expectations] ConfiguredAsset data source does not find named group RegEx asset, and generates schema error (Issue #3829)

EXTERNAL EMAIL: Do not click any links or open any attachments unless you trust the sender and know the content is safe.



@andersonterry<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fandersonterry&umid=c7020451-4daf-44b1-ae3d-67a7e43ca3f4&auth=732345bef31a784e2798e5a08f43be53a71196f3-222df16f1ded8792ff240b5a875d674bcf714fc5> we didn't explicitly have support for named groups before - the above PR should remedy your issue. Would you mind seeing if that is the case?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fgreat%2dexpectations%2fgreat%5fexpectations%2fissues%2f3829%23issuecomment%2d994934046&umid=c7020451-4daf-44b1-ae3d-67a7e43ca3f4&auth=732345bef31a784e2798e5a08f43be53a71196f3-65390187809469dd2377988a5353db0263713ef1>, or unsubscribe<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2dauth%2fAT7GYVI4ROWMACXPNYODBPLURC4FZANCNFSM5JXKRDSA&umid=c7020451-4daf-44b1-ae3d-67a7e43ca3f4&auth=732345bef31a784e2798e5a08f43be53a71196f3-fc00a943bfe2d998028dc09740968d743f76655e>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by andersonterry** [comment]
Is there a way to pull in a specific branch into ADB in Azure?  This pulls in 13.47 currently for me...

dbutils.library.installPyPI("great_expectations")

**Comment by cdkini** [comment]
@andersonterry I'm not immediately familiar with ADB or how that would work. The changes should have been merged into the latest release so I believe that should be sufficient!

I usually test locally with `pip install -e .` but that may not be relevant here if you're not running GE in a traditional terminal environment.

**Comment by cdkini** [comment]
@andersonterry I'm going to close this issue down since the support for named groups has been added. Let us know if you run into any issues here!
