### ISSUE TITLE
Documentation does not say if Great Expectations' datasources are read-only

### ISSUE THREAD

**Issue by mars-f** [fivetran/great_expectations#3835]
**Describe the bug**
I’m connecting to my source SQL database as a user with write permissions.  I haven’t see anything in the Datasource docs or Getting Started guides that says the connection is read only.  I’d like the extra reassurance from the docs, or from a configuration option, that the connection is only used for reading data. 

**To Reproduce**
1. Go to the [Getting Started Guide](https://docs.greatexpectations.io/docs/tutorials/getting_started/connect_to_data), [Datasources under Core Concepts](https://docs.greatexpectations.io/docs/reference/datasources) docs, or [Datasources Legacy documentation](https://legacy.docs.greatexpectations.io/en/latest/reference/core_concepts/datasource.html).
2. Search for the words "read", "write", or "read only" in the web page content.
3. See no relevant search results.
4. Search for the words "read", "write", or "read only" using the site-wide search box in the upper right.
5. See no relevant search results.

**Expected behavior**
A clear, concise, searchable statement in the documentation that datasources are only used to read data.

**Environment (please complete the following information):**
 - Operating System: n/a
 - Great Expectations Version: n/a

**Additional context**
[Original bug report](https://greatexpectationstalk.slack.com/archives/CUUMYDJAX/p1638915031162900) on Slack

**Comment by cdkini** [comment]
Hey @mars-f thanks so much for opening up this issue! Let me bring this up internally before determining next steps.

**Comment by kenwade4** [comment]
https://docs.greatexpectations.io/docs/terms/datasource/#no-unexpected-modifications
