### ISSUE TITLE
Incorrect How to Edit this Suite command.

### ISSUE THREAD

**Issue by AlbertUlysses** [fivetran/great_expectations#3837]
**Describe the bug**
The "How to Edit this Suite" command is incorrect for version 3 API.

**To Reproduce**
1. Go to html home page
2. Click on expectations
3. Click on any suite
4. Click on "How to Edit this Suite"
5. The output says `great_expectations suite edit {suite.name}`

**Expected behavior**
It should say `great_expectations --v3-api suite edit {suite.name}`

**Environment (please complete the following information):**
 - Operating System: MacOs and Windows
 - Great Expectations Version: version 0.13.42
 
![Screen Shot 2021-12-10 at 4 35 01 PM](https://user-images.githubusercontent.com/47486070/145657397-6c25af17-b22d-4d07-be1f-6e59ecc7af8b.png)

**Comment by cdkini** [comment]
Hey @AlbertUlysses thanks so much for opening this up! Let me confer internally about this matter and get back to you regarding next steps.

**Comment by AlbertUlysses** [comment]
Hi @cdkini 
No problem, let me know if I can help. I found where the issue is and I am willing to update the wording then create a PR.

**Comment by talagluck** [comment]
Hi @AlbertUlysses - thanks again for opening this! In light of the 0.14 release, the `--v3-api` flag is no longer necessary, so we're going to close this for now.
