### ISSUE TITLE
Error message on expect_column_values_to_be_unique Expectation on Teradata

### ISSUE THREAD

**Issue by dsehnbru** [fivetran/great_expectations#3842]
**Describe the bug**
Running validation on Teradata column against a expect_column_values_to_be_unique - Expectation resulting in error 

**To Reproduce**
1. Create expect_column_values_to_be_unique - Expectation on any column of Teradata database
2. Run Expecation against Teradata datasource
**Expected behavior**
As this is obviously on of the most pivotal expectations, it should work against Teradata databases as well.

**Environment (please complete the following information):**
 - Operating System: Windows 10
 - Great Expectations Version: 0.13.44

**Additional context**
The expectation created in 1) works when run against a Sqlite database, so there has got to be a Teradata specific problem.

![expect_column_values_to_be_unique error](https://user-images.githubusercontent.com/91957375/145781854-dd741359-a33e-40bf-a600-6599ecdc08c5.jpg)

**Comment by cdkini** [comment]
Hey @dsehnbru thanks so much for opening this up! Our support for Teradata is in the experimental phase so there may be some issues that we're not actively able to prioritize.

@imamolp recently did some work so tagging for visibility.

**Comment by kyleaton** [comment]
Hi @dsehnbru, Following up here... We are closing this issue in favor of a GitHub Discussion to provide more visibility to those that would be interested in contributing to adding more support to Teradata. The conversation can be continued here: https://github.com/great-expectations/great_expectations/discussions/5889

Let us know if you are interested in contributing!
