### ISSUE TITLE
datasource connection error not raised

### ISSUE THREAD

**Issue by joostboonzajerflaes** [fivetran/great_expectations#3843]
**Describe the bug**
If a datasource connection is not valid (in bigquery) at least there is no clear error.

This is the error log:

```
File "/Users/../miniconda3/envs/airflow_customer_360/lib/python3.9/site-packages/great_expectations/data_context/data_context.py", line 1674, in get_batch_list
    datasource: Datasource = cast(Datasource, self.datasources[datasource_name])
KeyError: 'test_bigquery'
```
This has to do with the pass statement in data_context.py on line 473:

```
except ge_exceptions.DatasourceInitializationError:
        # this error will happen if our configuration contains datasources that GE can no longer connect to.
        # this is ok, as long as we don't use it to retrieve a batch. If we try to do that, the error will be
        # caught at the context.get_batch() step. So we just pass here.
        pass
```

If you don't have this pass but raise the error it does provide a clear error. So please change to:

```
except ge_exceptions.DatasourceInitializationError as e:
        # this error will happen if our configuration contains datasources that GE can no longer connect to.
        # this is ok, as long as we don't use it to retrieve a batch. If we try to do that, the error will be
        # caught at the context.get_batch() step. So we just pass here.
        raise e
```
Then you will get the actual error.

**To Reproduce**
1. use the v3 cli to create a datasource for bigquery
2. run a checkpoint without the proper credentials.
3. .. get a unclear keyerror which actually has different reasons under the hood
4. ..
5. no profit

**Expected behavior**
With raising the error:

```  
File "/Users/../miniconda3/envs/airflow_customer_360/lib/python3.9/site-packages/great_expectations/data_context/data_context.py", line 1886, in _instantiate_datasource_from_config
    raise ge_exceptions.DatasourceInitializationError(
great_expectations.exceptions.exceptions.DatasourceInitializationError: Cannot initialize datasource test_bigquery, error: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

**Environment (please complete the following information):**
 - Mac osx
 - Name: great-expectations
Version: 0.13.46

**Comment by cdkini** [comment]
Hey @joostboonzajerflaes thanks so much for opening this! I definitely agree that we could provide some additional information here.

Let me look into this and get back to you with a proposed solution.

**Comment by hanlonjohn23** [comment]
This issue is present when connecting to Snowflake datasources as well

**Comment by cdkini** [comment]
@joostboonzajerflaes @jhanlonhg that `pass` statement is there in order to provide some backwards compatibility. We want to eventually clean that up since it is a bit misleading but for the time being, we've gone ahead and adding some necessary logging to help users here.

Apologies for the confusion!
