### ISSUE TITLE
Option to suppress the output 

### ISSUE THREAD

**Issue by Alcampopiano** [fivetran/great_expectations#3871]
Please add an option to suppress the output of `context.add_checkpoint(**checkpoint_config)` in a notebook. A semicolon does not do the trick.

Beginners don't need to see this output and [other solutions](https://thesmithfam.org/blog/2012/10/25/temporarily-suppress-console-output-in-python/) are equally hard to read/intimidating.

Anything to reduce visual clutter may improve the onboarding experience.

**Comment by cdkini** [comment]
Hey @Alcampopiano thanks for opening up this issue! We'll review this matter and get back to you.

**Comment by austiezr** [comment]
Hey @Alcampopiano! The above PR will allow a semicolon to suppress output as expected.

**Comment by Alcampopiano** [comment]
Now this is awesome! Thank you so much for such a speedy change. Our Deepnote tutorial for GE will look will look even better now!
