### ISSUE TITLE
Documentation guide on how great_expectations could be used with Azure ML service

### ISSUE THREAD

**Issue by Li0425** [fivetran/great_expectations#3892]
**Reference**
[Avanade team using great_expectations in Azure Machine Learning pipeline for data expectation tests](https://greatexpectations.io/case-studies/avanade-case-study/)

My team is also implementing an ML solution using Azure Machine Learning pipeline. I would like to request for a guide on how this could be achieved and probably some best practices and tips when integrating the library with Azure ML.

This question has been posted in GE's slack channel, and here is one of the replies:
'...our team was using Azure ML pipelines defined using the SDK, which I 100% recommend using. All our expectations were run against data already in memory via the pandas “connector”.'

Thanks in advance!

**Comment by austiezr** [comment]
Hey @Li0425! Thanks for submitting this; we'll review this internally and get back to you!
