### ISSUE TITLE
Incorrect rendering for Boolean type between Json file to Jupyter Notebook cell

### ISSUE THREAD

**Issue by 80auline** [fivetran/great_expectations#3894]
**Describe the bug**
In Json format, boolean are represented by the 2 values: `true` and `false`.
In Python, boolean are represented by the 2 values: `True` and `False`.

The boolean type is extracted from the json file but not cast to a python boolean, so it is not recognized and it generates an error.

**To Reproduce**
1. `great_expectations --v3-api suite edit my_table`
2. `How would you like to edit your Expectation Suite?` -> `1. Manually, without interacting with a sample batch of data (default)`
5. Running JupyterNotebook cells:
```
expectation_configuration = ExpectationConfiguration(
    **{
        "meta": {},
        "kwargs": {
            "column": "input_date",
            "max_value": "2027-09-03 00:00:00",
            "min_value": "2015-01-01 00:00:00",
            "parse_strings_as_datetimes": true,
        },
        "expectation_context": {"description": None},
        "expectation_type": "expect_column_values_to_be_between",
    }
)
suite.add_expectation(expectation_configuration=expectation_configuration)
```
Errors:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/var/folders/pb/9yqny_053gn3730w7y713ycw0000gn/T/ipykernel_42880/17891162.py in <module>
      6             "max_value": "2027-09-03 00:00:00",
      7             "min_value": "2015-01-01 00:00:00",
----> 8             "parse_strings_as_datetimes": true,
      9         },
     10         "expectation_context": {"description": None},

NameError: name 'true' is not defined
```

**Expected behavior**
Correct casting from json file to Jupiter Notebook: `true` -> `True`

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.46

**Additional context**
Json expectation file:
```
    {
      "expectation_type": "expect_column_values_to_be_between",
      "kwargs": {
        "column": "input_date",
        "max_value": "2027-09-03 00:00:00",
        "min_value": "2015-01-01 00:00:00",
        "parse_strings_as_datetimes": true
      },
      "meta": {}
    }
```
Jupyter Notebook Incorrect rendering:
 
<img width="876" alt="Screenshot 2021-12-22 at 13 45 38" src="https://user-images.githubusercontent.com/11400917/147099238-2d83b0cd-d8f3-4a5c-9b0b-49d327132a94.png">

Jupyter Notebook Correct rendering:
<img width="1110" alt="Screenshot 2021-12-22 at 13 45 51" src="https://user-images.githubusercontent.com/11400917/147099282-5c261a63-49a3-46bd-bf67-e66b2351943b.png">

**Comment by austiezr** [comment]
Hey @80auline! Thanks for surfacing this; we'll review internally and respond!

**Comment by cdkini** [comment]
@80auline this should be fixed per the above PR! If you're seeing any other problems, please feel free to let us know in Slack or in another issue. Thanks!
