### ISSUE TITLE
(v3)  add_datasource() argument after ** must be a mapping, not DataContextConfig

### ISSUE THREAD

**Issue by andersonterry** [fivetran/great_expectations#3895]
**Describe the bug**

Receive an error when attempting to call context.add_datasource(...) as shown in project documentation:

REF:  

https://github.com/great-expectations/great_expectations/blob/f876b882f258d12c5fd1251a19d068a02e748020/tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_dataframe_python_configs.py#L90

"_add_datasource() argument after ** must be a mapping, not DataContextConfig_"

**To Reproduce**
1. Check out the documentation for ADB/Python in link above
2. Execute snippet as shown below
3. See error

![image](https://user-images.githubusercontent.com/83782741/147131202-ef19899b-0414-4677-ab87-21b519ae8655.png)

**Expected behavior**
No error;  dataSource should be added with no problems

**Environment (please complete the following information):**
 - Azure DataBricks / PySpark / Py 3.9
 - Great Expectations Version: [e.g. 0.13.47]

**Additional context**

```
my_spark_datasource_config = {
    "name": "mySparkDataSource",
    "class_name": "Datasource",
    "execution_engine": {"class_name": "SparkDFExecutionEngine"},
    "data_connectors": {
        "myRuntimeDataConnector": {
            "module_name": "great_expectations.datasource.data_connector",
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": [
                "test_batch"
            ],
        }
    },
}

context.add_datasource(**my_spark_data_context_config)
``` #add_datasource() argument after ** must be a mapping, not DataContextConfig

**Comment by talagluck** [comment]
Hi @andersonterry - it looks like you may have a typo. You'll want to pass `my_spark_datasource_config` in, rather than `my_spark_data_context_config`. I'm going to close this for now, but feel free to open a new issue if you need.
