### ISSUE TITLE
expect_column_pair_ratio_to_be_between

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#391]
![image](https://user-images.githubusercontent.com/1239085/46899165-d4515c80-ce44-11e8-9172-e7fc7941918c.png)

HT: https://twitter.com/chrisalbon/status/1050803364743634944

**Comment by jpcampb2** [comment]
I think this was spam?

**Comment by abegong** [comment]
Ha! No it’s real.

The expectation in the title would have prevented the problem in the image.

**Comment by jpcampb2** [comment]
Ha! I get it...I just saw the image, and totally didn't process, sorry!
