### ISSUE TITLE
Redshift and column_map_expectation

### ISSUE THREAD

**Issue by avanderm** [fivetran/great_expectations#392]
Hey,

Really like the package. I've been trying to use it with Redshift, but due to some behaviour in Redshift odd results pop up. For example, the expectation `expect_column_values_to_be_in_set` will always be successful (given you use the right data types) because of how Redshift evaluates booleans.

Given this line in your code [here](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/dataset/sqlalchemy_dataset.py#L67), it will roughly translate to
```
SELECT (... IS NULL) = false
```
which always evaluates to false and as a result the unexpected_count will always be 0 as well. In Redshift the correct query would be
```
SELECT CAST((... IS NULL) AS int) = false
```
I decided to raise it as an issue for now, since I'm unsure how to incorporate a fix. In my opinion it doesn't warrant a new DataSet class.

EDIT: I noticed that with no table involved in Redshift the query
```
SELECT (200 IS NULL) = false
```
does return true, yet it doesn't as soon as a table is involved (also checked that there are no actual NULL values).

**Comment by abegong** [comment]
@avanderm This is great feedback. We'll give it a look and see what it'll take to fix it.

@jpcampb2 I'm wondering if we can replicate this with postgresql...

**Comment by avanderm** [comment]
Hey @abegong, thanks for the feedback. I tested it with Postgres, it works fine there, seems it's redshift specific

EDIT: I've also tried sqlalchemy-redshift, with the driver as `redshift+psycopg2`, but the anomaly remains

**Comment by avanderm** [comment]
UPDATE: since the documentation of Redshift claims otherwise, I've decided to raise this issue to AWS (through my company so the response should be faster) and see what their answer is, the deficiency lies on their side imo.

**Comment by abegong** [comment]
Awesome---thanks for running it down with AWS.

**Comment by avanderm** [comment]
Their support team confirms it's an issue in Redshift. The IS NULL operator returns a faulty type (so you can't compare with the boolean false) when it is applied on a column declared as non null in a table.

**Comment by jpcampb2** [comment]
Thanks for the feedback on this. Did they give an indication about whether it's something they're going to address, or do we need to consider a workaround inside GE?

**Comment by avanderm** [comment]
The AWS support person I'm in contact with is contacting the Redshift service team to dig further into the cause. Can't put an ETA on a fix if they'll address it, hopefully their response will clarify that.

**Comment by avanderm** [comment]
Got a response back from the Redshift service team:

It looks like expressions in parentheses are not supported in Redshift. Although "value expression in parentheses"[1] is supported for Postgres, but Redshift doesn't support it.

Service team has recommended to use Redshift supported expressions[2], in this case the workaround would be CASE expression[3], for example,

```
test=> select case when test_field is null then false else true end from test123;
case
------
t
(1 row)
```

Below is the example to show the behaviour of  same query on Postgres and on Redshift.

### Redshift

```
test=# select (test_field is null ) = false from test123;
?column?
----------
f
(1 row)
```

```
test=# select case when test_field is null then false else true end from test123;
case
------
t
(1 row)
```

### Postgres

```
test=> select (test_field is null ) = false from test123;
?column?
----------
t
(1 row)
```

```
test=> select case when test_field is null then false else true end from test123;
case
------
t
(1 row)
```
Reference,
[1] https://www.postgresql.org/docs/8.0/static/sql-expressions.html
[2] https://docs.aws.amazon.com/redshift/latest/dg/r_expressions.html
[3] https://docs.aws.amazon.com/redshift/latest/dg/r_CASE_function.html
