### ISSUE TITLE
SQLAlchemy error connecting to Oracle

### ISSUE THREAD

**Issue by billzichos** [fivetran/great_expectations#393]
Trying to connect to my organization's Oracle database and receiving the following error:

> AttributeError: 'set' object has no attribute '_instantiate_plugins'

OS: Windows
Arch: 64
Python 3.6.6

It looks like a SQL alchemy error message, but I am able to connect when I directly call the SQLAlchemy functions - create_engine(), connect(), execute().

Here is the code I am trying:

> import great_expectations as ge
>
> options = {'oracle://[username]:[password]@[sid]'}
> sql_context = ge.get_data_context('SqlAlchemy', options)
>
> sql_dataset = sql_context.get_dataset("[tablename]")

**Comment by abegong** [comment]
Try substituting:
```
options = {
    'drivername': 'oracle',
    'host': 'YOUR_HOST',
    'port': 'YOUR_PORT',
    'username': 'YOUR_USERNAME',
    'password': 'YOUR_PASSWORD',
    'database': 'YOUR_DATABASE'
}
```

Alternatively, dropping the curly braces (which are causing python to interpret your connection string as a set) might work:
`options = 'oracle://[username]:[password]@[sid]'`

**Comment by billzichos** [comment]
Thank you Abe.   Your recommendation to drop the curly braces resolved my issue.

Great package!
