### ISSUE TITLE
Checkpoint dot notation not working in CLI

### ISSUE THREAD

**Issue by dkotschessa** [fivetran/great_expectations#3940]
**Describe the bug**
[note: this issue was discovered when using the [GE airflow provider](https://github.com/great-expectations/airflow-provider-great-expectations) so will use this as an example, but I was advised this is a core GE issue]

When checkpoints are stored in subdirectories, i.e. checkpoints/taxi/fail, they are listed as such in the cli:

```
$ great_expectations --v3-api checkpoint list
Using v3 (Batch Request) API
Found 2 Checkpoints.
 - taxi/fail/chk
 - taxi/pass/chk
```

But they cannot be executed this way as this would give a syntax error:

```
$ great_expectations --v3-api checkpoint run taxi/fail/chk
Using v3 (Batch Request) API
Keys in TupleFilesystemStoreBackend must not contain substrings in ['/', '\\'] : ('taxi/fail/chk',)
```

nor when using dot notation
```
$ great_expectations --v3-api checkpoint run taxi.fail.chk
Using v3 (Batch Request) API
Could not find Checkpoint `taxi.fail.chk` (or its configuration is invalid). Try running:
  - `great_expectations checkpoint list` to verify your Checkpoint exists
  - `great_expectations checkpoint new` to configure a new Checkpoint
  - 
```

**To Reproduce**
1. Create a valid checkpoints test_checkpoint
2. Move checkpoint files to a location in a file hierarchy i.e. `/checkpoints/dir1/dir2`
2. run great_expectations --v3-api checkpoint list

**Expected behavior**
checkpoints should be listed in dot notation

**Environment (please complete the following information):**
 - Operating System:MacOS, CentOS
 - Great Expectations Version: 0.13.43+

**Additional context**
Issue has been discussed with @talagluck in slack

**Comment by cdkini** [comment]
Hey @dkotschessa thanks for opening up this issue! We've recently added some support around dot notation so I'm surprised an issue is arising. Let me review that implementation and see if I can't figure out a path forward.

**Comment by cdkini** [comment]
Resolved per Slack conversation (latest release)
