### ISSUE TITLE
SparkDFDataset adding columns to dataframe for some expectations

### ISSUE THREAD

**Issue by gardnmi** [fivetran/great_expectations#3957]
**Describe the bug**
Some expectation methods in `SparkDFDataset` are adding columns to the original dataframe.  This can lead to issues when running other expectations further validate column count, names, etc.

**To Reproduce**
``` python
from great_expectations.dataset.sparkdf_dataset import SparkDFDataset

df = spark.read.format("csv")\
    .option("header", "true")\
    .option("inferSchema", "true")\
    .load("/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-01.csv.gz")

ge_df = SparkDFDataset(df)
result = ge_df.expect_column_values_to_be_unique('VendorID')

print(df.columns)

# Out[1]: ['VendorID',
#  'tpep_pickup_datetime',
#  'tpep_dropoff_datetime',
#  'passenger_count',
#  'trip_distance',
#  'RatecodeID',
#  'store_and_fwd_flag',
#  'PULocationID',
#  'DOLocationID',
#  'payment_type',
#  'fare_amount',
#  'extra',
#  'mta_tax',
#  'tip_amount',
#  'tolls_amount',
#  'improvement_surcharge',
#  'total_amount',
#  'congestion_surcharge']


print(ge_df.spark_df.columns)

# Out[2]: ['VendorID',
#  'tpep_pickup_datetime',
#  'tpep_dropoff_datetime',
#  'passenger_count',
#  'trip_distance',
#  'RatecodeID',
#  'store_and_fwd_flag',
#  'PULocationID',
#  'DOLocationID',
#  'payment_type',
#  'fare_amount',
#  'extra',
#  'mta_tax',
#  'tip_amount',
#  'tolls_amount',
#  'improvement_surcharge',
#  'total_amount',
#  'congestion_surcharge',
#  '__eval_col_VendorID'] <--------- added column  

```
**Expected behavior**
The column should be removed after the expectation has completed.

**Environment (please complete the following information):**
 - Databricks 9.1 LTS Spark 3.1.2
 - Great Expectations Version: 0.14.0

**Comment by talagluck** [comment]
Thanks for opening this issue, @gardnmi! The SparkDFDataset class is part of the V2 API. Do you happen to know if this is an issue with the V3 API as well? At this time, we're unable to prioritize fixes to the V2 API internally, but we are certainly happy to offer guidance for a contribution if that is something in which you are interested.
