### ISSUE TITLE
Autoinspection example not working

### ISSUE THREAD

**Issue by paulochf** [fivetran/great_expectations#396]
I've just tried to test the library (btw, seems very useful, thanks!).

I'm aware that are some issues regarding "bootstrapping" initial expectations, and I think the current suggestion is to use the `autoinspection` feature.

So, I tried to use [this example](https://great-expectations.readthedocs.io/en/latest/autoinspection.html), but it doesn't work due to `AttributeError: 'PandasDataset' object has no attribute 'autoinspect'`.

I would like to know if it's something wrong in my environment (having some guidance here would be great) or if it's a unknown bug.

Thanks!

**Comment by Shawnzy** [comment]
I had the same problem. Try this: After you create your great expectations dataframe, use df.get_expectations_config().  This will give you a config with an "expect_column_to_exist" expectation for each column in your dataframe.

**Comment by jcampbell** [comment]
@paulochf Apologies that I missed this issue; @Shawnzy thanks for responding.

@paulochf : it does seem likely that you needed to update your version of GE; the auto inspect method was added in v.0.4.5.
