### ISSUE TITLE
expect_table_column_values_to_be_able_to_cast_to()

### ISSUE THREAD

**Issue by Shawnzy** [fivetran/great_expectations#397]
I want to be able to test to see if I can type cast a string into a Datetime

**Comment by abegong** [comment]
Good suggestion.

Linking this to #110, since they're similar in spirit.

**Comment by DanGolding** [comment]
Is this not covered by [`expect_column_values_to_be_dateutil_parseable`](https://great-expectations.readthedocs.io/en/latest/dataset_module.html#great_expectations.dataset.base.Dataset.expect_column_values_to_be_dateutil_parseable) and [`expect_column_values_to_match_strftime_format`](https://great-expectations.readthedocs.io/en/latest/dataset_module.html#great_expectations.dataset.base.Dataset.expect_column_values_to_match_strftime_format)?

**Comment by jcampbell** [comment]
Thanks @DanGolding -- @Shawnzy did that address your case?
