### ISSUE TITLE
Utility to get Pandas DataFrame from PandasDataset

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#400]
It would be handy to have a utility `to_pandas` similar to `from_pandas` that returns a pandas dataframe from a `PandasDataset`.

**Comment by jcampbell** [comment]
@Aylr Sorry that I missed this issue earlier.

Since a `PandasDataset` is a subclass of a pandas Dataframe, it makes perfect sense to just do this in pandas:

```
import pandas as pd
df = pd.DataFrame(myGePandasDataset)
```

sounds like what you're after.
