### ISSUE TITLE
Bug when creating datadocs of a Suite having a multicolumn map expectation

### ISSUE THREAD

**Issue by mroblesquantil** [fivetran/great_expectations#4002]
**Describe the bug**
I defined a Suite with just the expectations expect_select_column_values_to_be_unique_within_record. When I try to build the data docs after validating a dataset with this Suite i get a AtributeError: "'str' object has no attribute 'get'".

![image](https://user-images.githubusercontent.com/94074924/149555145-e9a0350d-045b-44fd-8475-8fb634c9d500.png)

When I open the html I get the % of unexpected values but not the partial_unexpected_list

<img width="749" alt="image" src="https://user-images.githubusercontent.com/94074924/149555237-709ab35f-17b4-4593-8bff-151eeea575a0.png">

**To Reproduce**
1. Define a suite with the expectation expect_select_column_values_to_be_unique_within_record (v.3)
2. Validate a dataset with this Suite. Make sure the 
3. Build data docs 

**Environment:**
 - Operating System:  Windows
 - Great Expectations Version:  0.13.43

**Additional context**
Expectation Suite json:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/94074924/149555292-1fece554-4852-452f-8f42-f828f4708266.png">

**Comment by AFineDayFor** [comment]
Howdy @mroblesquantil, we're looking into this. Thank you for bringing it up.

**Comment by rdodev** [comment]
Hey @mroblesquantil is this still an issue with recent version of GX?
