### ISSUE TITLE
Custom Expectation

### ISSUE THREAD

**Issue by mikkilinenirc** [fivetran/great_expectations#4011]
**Describe the bug**
I have created a Custom Expectation by following this page,
https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_expectations
To do this we will say,
great_expectations suite new 
Choose Interactive mode
specify the suite name.
A jupyter notebook will be opened with prepopulated text, which has suite_name, validator & checkpoint at the end.
In this I have implemented up to "step-6" as per the document.
As per document it says copy the module under "Plugins" and import the expectation from there,
but when I try to import it says Module not found.
I even set the os.chdir("path/..../plugins")
from plugins import custom_expectation
2nd- Question
Here custom expectation means, the class I have created should appear while I am validating using validator right?
say I have created a custom_expectation.ipynb that has a class
class ExpectColumnMaxToBeBetweenCustom(ColumnExpectation)
while validating my data, when I say validator.? "my expect_column_max_to_be_between_custom" has to appear right?
How can I do this?

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: [e.g. 0.13.2]

**Additional context**

**Comment by AFineDayFor** [comment]
Based on Slack it appears you've already addressed this [here](https://app.slack.com/client/T7NEH00BA/CUW3WD6PK) so I'm closing this issue; however, can you please indicate the steps you took here. Also if it's not resolved, feel free to just go ahead and open.
