### ISSUE TITLE
validator.save_expectation_suite() method not able to save updated batch request in suite json

### ISSUE THREAD

**Issue by vshind1** [fivetran/great_expectations#4025]
**validator.save_expectation_suite() method not able to save updated batch request in suite json*
validation.save_expectation_suite() method not able to save batch_request after making changes. 

**To Reproduce**
1. execute the following command on CLI
`great_expectations suite new`
2. select data_asset according to your requirements 
3. Jupyter notebook will open
4. make changes in batch_request according to requirement (ex. change limit filed)
5. add expectation using validator object
6. execute all cells in Jupyter notebook
7. expectation results get generated with updated batch_request
8. But it is not able to save updated batch_request in-suite JSON
**Expected behavior**
validator.save_expectation_suite should save updated batch request in JSON suite 
`validator.save_expectation_suite(discard_failed_expectations=False)`

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.14.0

**Comment by AFineDayFor** [comment]
Howdy @vshind1. We'll continue working this in [4027](https://github.com/great-expectations/great_expectations/issues/4027) as that appears to be the same but with a bit more context. Please reach out if you feel that's incorrect.

**Comment by vshind1** [comment]
>

**Comment by vshind1** [comment]
> Howdy @vshind1. We'll continue working this in [4027](https://github.com/great-expectations/great_expectations/issues/4027) as that appears to be the same but with a bit more context. Please reach out if you feel that's incorrect.

@AFineDayFor I am good as long as the issue gets fixed, 
As our framework requires this fix, could please let us know the priority of these bugs at your end.
It would be great if you provide a rough release version in which it will get the fix.
