### ISSUE TITLE
Unable to edit the expectation suite if additional arguments are added in batch_request parameter.

### ISSUE THREAD

**Issue by namanchawla** [fivetran/great_expectations#4027]
**Description:**
   Unable to edit expectation suite if additional arguments were added in batch_request parameter while creating suite.

**Steps To Reproduce**
Step 1) Execute "great_expectations suite new"
   Output of Step 1: 
  How would you like to create your Expectation Suite?
      1. Manually, without interacting with a sample batch of data (default)
      2. Interactively, with a sample batch of data
      3. Automatically, using a profiler
Step 2)  Select option 2 (Interactively, with a sample batch of data)  

Output of Step 2: 
     A batch of data is required to edit the suite - let's help you to specify it.

Which data asset (accessible by data connector "default_runtime_data_connector_name") would you like to use?
   Step 3)  Which data asset (accessible by data connector "default_runtime_data_connector_name") would you like to use?
              Enter name of data asset (in this case value submitted by me is default) 
    Output of Step 3: 
[Code_modfiy_batch_request.txt](https://github.com/great-expectations/great_expectations/files/7904442/Code_modfiy_batch_request.txt)

            Name the new Expectation Suite [default.warning]:
    
   Step 4: Enter the name of expectation suite:
         Value submitted: test_suite_2
   Output of Step 4:
         Expectation suite gets created.
Step 5: 
Now while executing the template modify the batch_request like below:
import datetime

import pandas as pd

import great_expectations as ge
from great_expectations.core.batch import RuntimeBatchRequest
import great_expectations.jupyter_ux
from great_expectations.core.batch import BatchRequest
from great_expectations.checkpoint import SimpleCheckpoint
from great_expectations.exceptions import DataContextError

context = ge.data_context.DataContext()

# Note that if you modify this batch request, you may save the new version as a .json file
#  to pass in later via the --batch-request option
batch_request = {
    "datasource_name": "my_datasource",
    "data_connector_name": "default_runtime_data_connector_name",
    "data_asset_name": "default",
    "limit": 1000,
}

batch_request = RuntimeBatchRequest(
    datasource_name="my_datasource",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="default",  # This can be anything that identifies this data_asset for you
    runtime_parameters={"query": "SELECT * FROM etleap_integration_test_ds__etleap_integration_test_db.etleap_integration_test_tb"},
    batch_identifiers={"default_identifier_name": "default"},
)

# Feel free to change the name of your suite here. Renaming this will not remove the other one.
expectation_suite_name = "test_suite_2"
try:
    suite = context.get_expectation_suite(expectation_suite_name=expectation_suite_name)
    print(
        f'Loaded ExpectationSuite "{suite.expectation_suite_name}" containing {len(suite.expectations)} expectations.'
    )
except DataContextError:
    suite = context.create_expectation_suite(
        expectation_suite_name=expectation_suite_name
    )
    print(f'Created ExpectationSuite "{suite.expectation_suite_name}".')

validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name=expectation_suite_name,
)
column_names = [f'"{column_name}"' for column_name in validator.columns()]
print(f"Columns: {', '.join(column_names)}.")
# validator.head(n_rows=5, fetch_all=False)

if not suite.meta.get('citations'):
    suite.add_citation(batch_request=batch_request, comment="test")
    # validator._data_context.save_expectation_suite(suite)
else:
    suite.meta['citations'][-1]['batch_request']['data_asset_name'] = 'default'
    suite.meta['citations'][-1]['batch_request']['datasource_name'] = 'my_athena'
    suite.meta['citations'][-1]['batch_request']['data_connector_name'] = 'default_configured_data_connector_name'
    suite.meta['citations'][-1]['batch_request']['runtime_parameters'] = batch_request.runtime_parameters
    suite.meta['citations'][-1]['batch_request']['batch_identifiers'] = batch_request.batch_identifiers
print(suite)
suite.meta["notes"] = {
    "content": {
        "dimension": "properties.dimension",
        "severity": "properties.severity"
    },
    "format": "renderer.diagnostic.meta_properties",
}

context.save_expectation_suite(suite)

Step 6:  Edit the expectation suite ("great_expectations suite edit test_suite_2")
           Output: 
 How would you like to edit your Expectation Suite?
    1. Manually, without interacting with a sample batch of data (default)
    2. Interactively, with a sample batch of data
  Select option 2
[Unable to edit with updated batch_request.docx](https://github.com/great-expectations/great_expectations/files/7904486/Unable.to.edit.with.updated.batch_request.docx)

 It is giving error like:  TypeError: __init__() got an unexpected keyword argument 'batch_identifiers'

**Environment:**
Operating System: Windows10
great_expectation version: 0.14.0

**Comment by AFineDayFor** [comment]
Howdy @namanchawla. Thank you for opening this with us. We'll have an update after we're able to talk it over with the team.
