### ISSUE TITLE
Document `GE_HOME` environment variable

### ISSUE THREAD

**Issue by edgarrmondragon** [fivetran/great_expectations#4034]
**Describe the bug**

The docs hosted in https://great-expectations.readthedocs.io and https://docs.greatexpectations.io/docs/ fail to mention the possibility of passing a `GE_HOME` environment variable to tell `great_expectations` the location of the root dir when calling from a different path.

I had to dig through the code and issues to see if something like this was even possible and the references I could find were [a comment on an issue](https://github.com/great-expectations/great_expectations/issues/1231#issuecomment-604153064), the [the official Dockerfile](https://github.com/great-expectations/great_expectations/blob/develop/docker/Dockerfile#L12) and the lines of code where the variable is actually read; but nothing else.

**To Reproduce**

NA

**Expected behavior**

NA

**Environment (please complete the following information):**

 - Operating System: Any
 - Great Expectations Version: 0.14.2

**Additional context**

NA

**Comment by AFineDayFor** [comment]
Howdy @edgarrmondragon, we'll look into this more. Thank you very much for raising this.

**Comment by AFineDayFor** [comment]
Closed with #4164 merge.
