### ISSUE TITLE
Regex Issue

### ISSUE THREAD

**Issue by sncamie** [fivetran/great_expectations#4036]
file names are of the form 'plant_report_0-2_(unfiltered)_2022-01-20_02_29_16.csv' my regular expression is (.*)_
[mouldpresserrort.txt](https://github.com/great-expectations/great_expectations/files/7911023/mouldpresserrort.txt)
(\d{2})_(\d{2})\.csv. Using https://regexr.com/, the pattern matches the text. When i build a new suite, GE only matches 'plant_report_0-2_(unfiltered)_2022-01-20_02'  without the rest. Selecting one of the files results in " Unable to determine reader method from path:"

MouldPress_yaml = f"""
name: {datasource_name}
class_name: Datasource
execution_engine:
  class_name: PandasExecutionEngine
data_connectors:
  default_inferred_data_connector_name:
    class_name: InferredAssetFilesystemDataConnector
    base_directory: ../Data
    default_regex:
      group_names:
        - data_asset_name
      pattern: (.*)_(\d{2})_(\d{2})\.csv
  default_runtime_data_connector_name:
    class_name: RuntimeDataConnector
    batch_identifiers:
      - default_identifier_name
"""

#This is the output for the test_yaml_config
***********************************************************************************************************************
Attempting to instantiate class from config...
	Instantiating as a Datasource, since class_name is Datasource
	Successfully instantiated Datasource

ExecutionEngine class name: PandasExecutionEngine
Data Connectors:
	default_inferred_data_connector_name : InferredAssetFilesystemDataConnector

	Available data_asset_names (0 of 0):

	Unmatched data_references (3 of 3):['plant_report_3-2_(unfiltered)_2022-01-19_02_29_01.csv', 'plant_report_3-2_(unfiltered)_2022-01-19_10_29_07.csv', 'plant_report_3-2_(unfiltered)_2022-01-20_02_29_32.csv']

	default_runtime_data_connector_name:RuntimeDataConnector

	Available data_asset_names (0 of 0):
		Note : RuntimeDataConnector will not have data_asset_names until they are passed in through RuntimeBatchRequest

	Unmatched data_references (0 of 0): []

When I create a new suite, This is what I get on my CLI. It matches not the entirety of the name of the file but a part of it.

How would you like to create your Expectation Suite?
    1. Manually, without interacting with a sample batch of data (default)
    2. Interactively, with a sample batch of data
    3. Automatically, using a profiler
: 3

A batch of data is required to edit the suite - let's help you to specify it.

Which data asset (accessible by data connector "default_inferred_data_connector_name") would you like to use?
    1. plant_report_3-2_(unfiltered)_2022-01-19_02
    2. plant_report_3-2_(unfiltered)_2022-01-19_10
    3. plant_report_3-2_(unfiltered)_2022-01-20_02

Type [n] to see the next page or [p] for the previous. When you're ready to select an asset, enter the index.

Of course selecting any of the files results in an: Unable to determine reader method from path error

However, if I leave the pattern to just (*) then it matches all the files.

**Comment by AFineDayFor** [comment]
Howdy @sncamie. When you pass capture groups in your match, you may want to also provide an ordered list of their names, the `group_names` kwarg; you can see an example of this [here](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_configure_a_configuredassetdataconnector/#example-2-basic-configuration-with-more-than-one-data-asset).

As a brief example, the expression `pattern: '.*(\d\d\d\d)-(\d\d)-(\d\d).*'` would return:

```yml
name: my_datasource
class_name: Datasource
execution_engine:
  class_name: PandasExecutionEngine
data_connectors:
  default_inferred_data_connector_name:
    class_name: InferredAssetFilesystemDataConnector
    base_directory: ../demo
    default_regex:
      pattern: '.*(\d\d\d\d)-(\d\d)-(\d\d).*'
      group_names:
        - year
        - month
        - day
```

That would return including the output:

```output
DEFAULT_ASSET_NAME (3 of 3): ['*2022-01-19*', '*2022-01-19*', '*2022-01-20*']
```
