### ISSUE TITLE
BigQuery GEOGRAPHY column type not recognised

### ISSUE THREAD

**Issue by 80auline** [fivetran/great_expectations#4049]
**Describe the bug**
`GEOGRAPHY` BigQuery  type is not recognise and generates error in datadoc.

**To Reproduce**
1. `great_expectations --v3-api suite edit my_table`
2. `How would you like to edit your Expectation Suite?` -> `1. Manually, without interacting with a sample batch of data`
3. `Select a datasource` -> `datasource_BigQuery_analytics`
```datasources:
  datasource_BigQuery_analytics:
    connection_string: bigquery://my-project/my_dataset
    introspection:
      whole_table:
        data_asset_name_suffix: __whole_table
    module_name: great_expectations.datasource
    class_name: SimpleSqlalchemyDatasource
```
4. Provide: name of the table, temporary table, name of the file

JupyterNotebook configurations:
```
context = ge.data_context.DataContext()
batch_request = {
    "datasource_name": "datasource_BigQuery_scratch",
    "data_connector_name": "whole_table",
    "data_asset_name": "my_table__whole_table",
    "limit": 1000,
    "batch_spec_passthrough": {
        "bigquery_temp_table": "my-project.my_dataset.my_table"
    },
}

checkpoint_config = {
    "class_name": "SimpleCheckpoint",
    "validations": [
        {
            "batch_request": batch_request,
            "expectation_suite_name": expectation_suite_name
        }
    ]
}
checkpoint = SimpleCheckpoint(
    f"_tmp_checkpoint_{expectation_suite_name}",
    context,
    **checkpoint_config
)
checkpoint_result = checkpoint.run()
```
Json rules
```
...
    {
      "expectation_type": "expect_column_values_to_be_of_type",
      "kwargs": {
        "column": "loc_geo_point",
        "type_": "GEOGRAPHY"
      },
      "meta": {}
    }
...
```

Warnings
```
/Users/.venv/lib/python3.9/site-packages/pybigquery/sqlalchemy_bigquery.py:879: SAWarning: Did not recognize type 'GEOGRAPHY' of column 'loc_geo_point'
  util.warn(
2022-01-21T12:32:50+0000 - WARNING - No recognized sqlalchemy types in type_list for current dialect.
```
Datadoc error:
<img width="712" alt="GE issue" src="https://user-images.githubusercontent.com/11400917/150841006-fe0d08da-10c5-495b-9510-87e65697a548.png">

**Expected behavior**
`GEOGRAPHY` recognized and no error raised in the DataDoc

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.14.1

**Comment by joshua-stauffer** [comment]
Hi @80auline, thanks for raising this issue. It looks like we may need to specifically install BigQuery support for the GEOGRAPHY column. Could you try `pip install 'sqlalchemy-bigquery[geography]'` and see if the error persists? I'll look into replicating this on my end as well.

**Comment by joshua-stauffer** [comment]
Hi @80auline, just wanted to circle back to this. We have a PR in flight to address this issue, and I'll be in touch when it's merged. Thanks for your patience!

**Comment by joshua-stauffer** [comment]
Hi @80auline, this issue has been addressed in [PR 4182](https://github.com/great-expectations/great_expectations/pull/4182), and will be available in the next release. Closing this for now, but please feel free to reopen if the issue persists.
