### ISSUE TITLE
Creating expectation suite using profiler fails when: expect_column_values_to_be_in_set is used and element count >16000 w/ snowflake db

### ISSUE THREAD

**Issue by samLozier** [fivetran/great_expectations#4050]
**Describe the bug**
The default profiler configuration uses the `expect_column_values_to_be_in_set` which sometimes tries to set a rule for string columns that contain more than the number of elements that snowflake will allow for an in clause. (16000)

**To Reproduce**
1. Run the auto profiler on a snowflake table that contains a column with >16000 unique elements
2. If the profiler decided to apply this rule, the creation of the entire expectation suite will fail. 

**Expected behavior**
Handle the exception cleanly.  Pseudo-code below: 
```
if len(set_of_values) >16000 and connection.type == "snowflake":
    # skip adding this expectation to the suite, possibly raise warning
    continue
```

**Environment (please complete the following information):**
 - MacOs, Snowflake
 - Great Expectations Version: 0.14.0

**Additional context**
I would like to be able to use the `expect_column_values_to_be_in_set` as much as possible, so I don't like using the "excluded_expectations" kwarg if I can avoid it. Cleanly handling this exception would create better starting templates that include the expectation wherever possible.

**Comment by joshua-stauffer** [comment]
Hi @samLozier, thanks for raising this issue! Your solution looks workable, would you consider making a PR with these changes? Looks like this would also close #3527. Thanks for considering!

**Comment by samLozier** [comment]
I'll need to check with my corporate overlords to see if I can contribute on company time, otherwise I don't think I'll be able to get to it before the weekend.

Rather than a 1-off rule, do we want to see if the other data connectors have similar limits, or just clip it at an arbitrary point for all? Basically if a column has anywhere close to 16000 distinct values in it, its reasonably likely that it isn't categorical anyway, right? At least from the perspective of an auto profiler.

**Comment by samLozier** [comment]
While we're on the subject of the auto profiler, does it adjust the rules that it runs based on the size of the table at all? I made the mistake of running it on a snowflake table with 156 billion rows with a xs warehouse and it took me a minute to figure out why it was never finishing. That could be another PR if needed

**Comment by joshua-stauffer** [comment]
hey @samLozier, we're not aware of issues on other data connectors, but if you're able to test for that, of course that would be great. If we end up going the route of a blanket rule, there may be some cases for categorical data with high amounts of distinct values, so would probably be best to keep the number around at least 10,000.

In response to your last question, no, the profiler doesn't adjust for table size. Profiling a billion rows is probably not going to work - that could be a good opportunity to use a sampler on the DataConnector to limit it to a reasonable size. It sounds reasonable to add a check to the profiler to throw a helpful error if someone tries to profile an impossibly large table; I'll dig into why it's currently built this way, and see if there's any reason against something like that.

thanks for looking into this!

**Comment by RoyalTS** [comment]
Just stumbled on the same thing while taking GE for a spin. Hitting it on while trying to create my first suite using the profiler makes for a pretty bad first impression.

**Comment by samLozier** [comment]
@joshua-stauffer I went to take a look at this today, starting by simply trying to implement your suggestion. Before I got into the sampler I wanted to clarify the relationship between the limit argument in a batch_request vs the sampler thing you described. 

eg: 
```
    batch_request = {
        "datasource_name": datasource,
        "data_connector_name": "default_inferred_data_connector_name",
        "data_asset_name": tablename.lower(),
        "limit": 1000,
    }
```
does a batch request limit of 1000 mean that it's only returning 1000 rows, that it's iterating through the table 1000 at a time, or something else entirely? 

Regarding the sampler solution you suggested, is there any documentation on it and how to apply it? 

So far the only references I can find are: 
https://github.com/great-expectations/great_expectations/blob/cdbbbacd0fcda2f66ccd39c13c50fdf8efb4ab30/great_expectations/execution_engine/sqlalchemy_execution_engine.py#L1059
which can be followed upstream to : 
https://github.com/great-expectations/great_expectations/blob/983cb6ff081e2a6d09c42651f5236f75757bd4a1/great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py#L51
or 
https://github.com/great-expectations/great_expectations/blob/239418ddbf9289bc535c59a967b6e4021ce13c09/great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py#L47 
^^ that link is, so far, the only place I've found that makes any reference to valid sampling_method arguments. 

edit: 
found it (I think) text search was difficult 
https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_tables_in_sql

**Comment by joshua-stauffer** [comment]
Hi @samLozier -- yes, that doc is the best one to get started with sampling/splitting. The Batch Request `limit` param actually limits how many Batches could be returned. We're updating the docs on Batches and Batch Requests now, and I'll check to make sure that is clear, since its function isn't immediately intuitive (at least, wasn't for me!)

**Comment by AFineDayFor** [comment]
Closing this as it appears already addressed in both documentation and function :bow: feel free to open another issue if a smilier occurs :microscope:

Thank you for your keen eye, and aid in addressing this.
