### ISSUE TITLE
More flexibility in managing cardinality for rule-based profilers

### ISSUE THREAD

**Issue by john-schwegler-vectorsolutions** [fivetran/great_expectations#4051]
**Is your feature request related to a problem? Please describe.**
The maximum cardinality of a given variable for which it still makes sense to build a list varies quite a bit.  In some cases, 10 values is enough.  In other cases, there may be 10,000 distinct values for which a list is still useful.  Currently, GE has a bit of a break in the middle.  A cardinality of "FEW" provides a maximum of 59 distinct values, whereas "MANY" gives less than 10% of the number of rows in the table.  The latter is much too many distinct values when the source data has tens of millions of rows (or more).  Users generally know whether they want to use absolute or relative cardinality limits, mixing them results in ambiguity.

**Describe the solution you'd like**
It would be great to be able to have more values for both absolute (distinct count) and relative (percent of row count) cardinalities, as well as distinguishing the two from each other.  This could either be described as:

- A two part system with a category (Absolute, Relative), and a value indicating the cardinality threshold:
- (Absolute, 100) - Threshold of 100 distinct values to collect a value list
- (Absolute, 10000) - Threshold of 10000 distinct values to collect a value list
- (Relative, 1) - Threshold count equal to 1% of the rows in the data source to collect a value list
- (Relative, 0.01) - Threshold count equal to 0.01% of the rows in the data source to collect a value list
**(or)**
- A single part system, that still separates absolute and relative cardinalities
- ABS_VERY_FEW (<= 10)
- ABS_FEW (<= 100)
- ABS_SOME (<= 1000)
- ABS_MANY (<= 10000)
- ABS_VERY_MANY (<= 100000)
**(or)** more specific names (no need to look up the descriptive terms)
- ABS_100 - Absolute cardinality, maximum 100 distinct values
- ABS_1000 - Absolute cardinality, maximum 1000 distinct values
- REL_10 - Relative cardinality, 10% of row count
- REL_01 - Relative cardinality, 1% of row count
- REL_001 - Relative cardinality, 0.1% of row count

**Comment by joshua-stauffer** [comment]
Hi @john-schwegler-vectorsolutions, thanks for raising this! I'll look into it and get back to you soon.

**Comment by joshua-stauffer** [comment]
Hi @john-schwegler-vectorsolutions -- we're in the middle of some work on the rule-based profiler, and it looks like this will be in scope for the work we have planned. I'll forward this feedback to the team that will work on the feature, and will update this issue when the work is merged.

**Comment by john-schwegler-vectorsolutions** [comment]
Hi Joshua,

Thanks so much for the feedback!  This would be really helpful for some of
our planned use cases.

**Comment by anthonyburdi** [comment]
Hi @john-schwegler-vectorsolutions! Thank you for the suggestions, and I'm happy to report that we now have an implementation merged into our `develop` branch that will be released in the next scheduled GE release, with documentation to follow in an upcoming release. In the meantime if you'd like to try it out take a look at https://github.com/great-expectations/great_expectations/pull/4269, specifically the the [CardinalityChecker](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/rule_based_profiler/domain_builder/cardinality_checker.py) and [CategoricalColumnDomainBuilder](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/rule_based_profiler/domain_builder/categorical_column_domain_builder.py) classes. Note that with this implementation you also have the ability to use custom cardinality limits along with over 25 pre-built limits. cc @talagluck

**Comment by john-schwegler-vectorsolutions** [comment]
That's terrific!  I'll definitely take a look at it.

**Comment by john-schwegler-vectorsolutions** [comment]
This looks like a great, really complete implementation.  I'm really looking forward to using it.  Thanks for getting this into development so quickly!
