### ISSUE TITLE
an expectation that rows be distinct across multiple columns

### ISSUE THREAD

**Issue by ftrotter** [fivetran/great_expectations#406]
Hey, just playing with the framework. It does look very useful. 

For my use case, expect_column_values_to_be_unique is not really that useful. 

I need to be sure that a "DISTINCT/GROUP BY" has properly occurred during data generation. These frequently take the form of something like: 
``` 

SELECT 
    A,
    B, 
    C, 
    D,
    SUM(something_worth_summing) AS sum_something_worth_summing
FROM ThatTable
GROUP BY A, B, C, D

```

And the error that I want to check for is: 

``` 

SELECT 
    A,
    B, 
    C, 
    D,
    SUM(something_worth_summing) AS sum_something_worth_summing
FROM ThatTable
GROUP BY A, B, C, D, E

```

So I want to set an expectation that allows me to say "I should not see repeated rows with the same values of columns  A, B, C, D 

expect_column_values_to_be_unique allows me to do this on a single row. 

I know that I can create a meta-column that is just concatenation of A+B+C+D but I would expect that great expectation would save me from this work. 

-FT

**Comment by abegong** [comment]
Good idea.

What if we call the new expectation `expect_multi_column_values_to_be_unique`?

And if I've understood you correctly, this should return true:
```
A B C D
1 1 1 1
2 2 2 2
3 3 3 3 
```

...and this should return false:
```
A B C D
1 1 2 2
1 1 2 2 (duplicates row 1)
3 3 3 3
```

Would that fit the need?

**Comment by ftrotter** [comment]
yep that is is it. 

Further, the idea would be to allow the arguments to drive the results.

expect_multi_column_values_to_be_unique(A,B,C)

```
A B C D
1 1 1 1
1 1 2 1
1 2 2 1 
```
OK, because A, B, and C where never the same...

```
A B C D
1 1 1 1
1 1 1 2
1 2 2 1 
```
Not Ok, because the first and second row have the same values for A, B, and C. 

Note that the answer changes for different arguments... So the first example here would not be OK, if the function was called like this:

expect_multi_column_values_to_be_unique(A,B)

Also the arguments should not have to be in any specific order. So you could call the function like:

expect_multi_column_values_to_be_unique(A,C,D)

if you wanted. This makes it more useful on "strangely constructed" data sets which 
I see alot in real life ETL....

Does that all make sense?

**Comment by abegong** [comment]
Yes, that makes perfect sense.

The expectation itself should be quick to implement. The main work will be creating a new `@multi_column_map_expectation` decorator.

**Comment by ftrotter** [comment]
Just wondering what the ETA was on this... do you have a formal "accepted feature request" status or something? Is this something that I can expect in the next week/month/quarter etc etc?

Sorry to be a pest, but this feature is the key feature that makes the software "adoptable" for us...

Regards,
-FT

**Comment by jpcampb2** [comment]
@ftrotter -- I've just committed a branch and opened a PR with an idea for how this might be implemented. Please feel free to check it out and see if it works for you. Notably, I haven't tackled doing this in SQL yet.
