### ISSUE TITLE
Expectation docstrings not present in Jupyter notebooks

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#4062]
**Describe the bug**
Docstrings for `expect_*` methods are not present in Jupyter notebooks.

**To Reproduce**
1. Create or edit a suite
2. Enter an expectation method
3. With your cursor in the parens, pull up the docstring shortcut in Jupyter notebooks
4. Note lack of helpful doc string

**Expected behavior**
I expect to see the docstrings and parameters so I know how to use an expectation without looking up the docs.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.14.2 

**Additional context**
<img width="963" alt="Screen Shot 2022-01-25 at 4 01 12 PM" src="https://user-images.githubusercontent.com/928247/151079507-24392874-5b37-4e6c-91bc-0402fb1e2568.png">

**Comment by joshua-stauffer** [comment]
hi @Aylr, thanks for flagging this -- we'll take a look and get back to you soon!

**Comment by jcampbell** [comment]
Thank you, @Aylr -- you still get the title of usability king even in absentia. :)

I just did a PR to address this--would love your confirmation it's working for you.

**Comment by Aylr** [comment]
@jcampbell Thanks for the kind words and quick fix. I've just gotten back to this and it looks great!
