### ISSUE TITLE
Example Notebook Pathing Issues

### ISSUE THREAD

**Issue by taylorfturner** [fivetran/great_expectations#4069]
**Describe the bug**

1. The example notebooks in `/examples/notebooks/` do not work out of the box. I am testing on the `develop` branch. For example: 
- <file_name>: <path>
- `explore_titanic_data.ipynb`: `tests/examples/titanic.csv`
- `Crop_Expectations_With_Reshape.ipynb`: `tests/examples/FAO-Rice-Production-Asia.csv`
- `Tutorial.ipynb`: `/PATHTO/hospital_charge_data.csv`
**Note**: Additionally, some of these datasets don't appear to be in the repo anymore. 

2. `PandasDataset` is utilized for converting a dataframe object to what appears to be a ge-specific object. `PandasDataset` appears to be a legacy / deprecated class at this point.

**To Reproduce**
1. Go to `examples/notebooks/`
2. Open up any of the notebooks bullet-pointed above
3. Try to run the cells sequentially
4. See `FileNotFoundError`

**Expected behavior**
Notebook should ideally run out of the box post user installation of the core package requirements without having to alter any pathing within the notebook. 

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: develop branch

**Comment by joshua-stauffer** [comment]
hi @taylorfturner, thanks for raising this issue -- you're right, those are out of date. We'll look into it and update them accordingly.

**Comment by taylorfturner** [comment]
Glad to do it, @joshua-stauffer, and sounds good on the update. I just updated paths locally so not a blocker for me to get things running and make progress.

**Comment by vetedde** [comment]
Hi. I want take it.
Also I will update code from python2.x to python 3.x
For example, print json.dumps(titanic_df.get_expectation_suite(), indent=2) => print(json.dumps(titanic_df.get_expectation_suite().to_dict(), indent=2))

Or leave as is?

**Comment by austiezr** [comment]
Hey @vetedde ! Thanks for reaching out here; sorry for the delay! We've had an opportunity to internally review these notebooks and come to some decisions about how to best update the patterns for V3.

As you've also had eyes on this, I'd love to get your input on #4404!
