### ISSUE TITLE
Connecting to redshift private database

### ISSUE THREAD

**Issue by jambo1** [fivetran/great_expectations#407]
I am using v0.4.5 and am having quite a few issues connecting to a private redshift schema through a docker container. I am not massively experienced with Python and so any help or suggestions would be most welcome as I am aware that Redshift compatability has been added, I just can't seem to figure out the implementation.

The following does not work at retrieving the dataset with the errors above the calls

```import great_expectations as ge
import psycopg2
import sqlalchemy as sa
engine = sa.create_engine("redshift+psycopg2://user:password@host.docker.internal:5439/database")
metadata= sa.MetaData(engine)
table = sa.Table('table_name, metadata, schema='schema_name')

# This gives no such table error
dataset = ge.dataset.sqlalchemy_dataset.SqlAlchemyDataset(table, engine=engine)

# Or the following will give a different error, that too many positional arguments have been given
#(exact error: TypeError: _get_column_info() takes 8 positional arguments but 9 were given)
dataset = ge.dataset.sqlalchemy_dataset.SqlAlchemyDataset('table_name', engine=engine, schema='schema_name')
```

When I use the following I can retrieve a private table using sql alchemy, suggesting the engine is set up correctly at least
```
import psycopg2
import sqlalchemy as sa
engine = sa.create_engine("redshift+psycopg2://user:password@host.docker.internal:5439/database")
result=engine.execute('SELECT * FROM schema.table')
for row in result:
     print(row)
```
Thanks!

**Comment by jpcampb2** [comment]
Jamie--sorry to hear you're having issues connecting.

You want the second of the dataset initialization approaches you've got above (currently table_name is always used as text vs. as a SA Table object). Below is the code outline that worked for me; I wonder if there may be a version mismatch that is causing the _get_column_info() error; that appears to be in the redshift-sqlalchemy module (though it's related to the column inspection as well which is also quite new).


```
import sqlalchemy as sa
import great_expectations as ge

engine = sa.create_engine("redshift+psycopg2://user:password@host.docker.internal:5439/database")
dataset = ge.dataset.sqlalchemy_dataset.SqlAlchemyDataset('table_name', engine=engine, schema='schema_name')
```

If that's definitely not working, could you share the versions of sqlalchemy, psycopg2, and sqlalchemy-redshift that are in your docker environment (and confirm it's GE 0.4.5)?

**Comment by jambo1** [comment]
Hi James,

I had been using redshift-sqlalchemy, as opposed to sqlalchemy-redshift which seems to have been causing the problem! 

Thanks very much for your help, seems to be a great tool and looking forward to implementing it!

**Comment by jpcampb2** [comment]
Excellent--glad to hear it's resolved!
