### ISSUE TITLE
"how to configure a metrics store" documentation is not accurate

### ISSUE THREAD

**Issue by samLozier** [fivetran/great_expectations#4071]
**Describe the bug**
I understand this feature is currently marked as beta, but I am currently unable to reproduce the simple example in the docs and am pointing out a few of the issues I've encountered in the hope that they may help the next person. 

https://legacy.docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_metadata_stores/how_to_save_metrics.html

My checkpoint configuration is setup exactly as the docs show, however I am on GE v3, so perhaps that is the cause of the failures? I've also been testing on sqllite and snowflake, however most of the docs around the various "stores" seem to imply the use of a postgres even though the data contexts can some from (nearly) any type of datasource. 

bugs I've encountered trying to get this work: 
- using snowflake credentials leads to an error when the metric table is checked for existence. This try/except block does not work as expected, a key failure inside the table line causes a full-stop rather than a move to the "except" portion of the block: 
 https://github.com/great-expectations/great_expectations/blob/e2185c56bbb81b174334c311c6c808071f81addf/great_expectations/data_context/store/database_store_backend.py#L97
- Using sqllite locally part of it works, but I get an error from this line: https://github.com/great-expectations/great_expectations/blob/e2185c56bbb81b174334c311c6c808071f81addf/great_expectations/data_context/store/metric_store.py#L64 "TypeError: Object of type int64 is not JSON serializable" I looked into what's triggering it and its the statistics.successful_expectations metric, which has worked other times. The value that caused the error was 19, so it wasn't anything weird like -inf . I kept digging on this and it looks like the ExpectationSuiteValidationResult object is intended to have serializable values, so maybe this needs a new test to check for numpy datatypes? 
- Looking at the portion of the metrics that were saved to sqllite, I can see that the value column is a json column. This may be intentional, however it looks like it's an error. Each row in the "value" column has an entry like : `{"value": 2}` 

**To Reproduce**
1. Configure the metrics store like the documentation suggests
2. Configure the checkpoint to store metrics like the docs suggest
3. 

**Expected behavior**
I'm just hoping for a reproducible example, or more clarity about the current limitations of this feature. Is it under active development? does it work with v3? is it working for anyone? 

**Environment (please complete the following information):**
 - Operating System: macos
 - Great Expectations Version: 0.14.2

**Additional context**

**Comment by samLozier** [comment]
I spoke to @talagluck on slack and they gave me the following feedback:

> Hi @saml - thanks! We are in the process of updating our docs for this as we speak. That said, as you noted in your Issue, the V1 Metrics Store is a pretty experimental feature and is not thoroughly tested. We are in the process of implementing the V2 now, though it will likely take some time to finish up.
The database store backend should work with many SQL back-ends, but has only been tested with postgres. I know that others have reported issues with sqlite in the past for the reasons you describe and because sometimes the columns are not large enough to contain the results.

My understanding now is that a big update is in progress, so this ticket can probably be closed, though it may be helpful to flag the current docs as either deprecated or just remove them so that others don't spin their wheels trying to get it working.

**Comment by joshua-stauffer** [comment]
Hi @samLozier, thanks for raising this issue. I just wrapped up a rewrite of this doc, and expect it to merge shortly, but wanted to address some of the points you brought up. 
- metrics are stored as json objects, so that behavior is expected. I wasn't a part of the original architecture discussions, so I can't say for sure, but it looks to me like that may be a way to handle `value` being an arbitrary type, including list.
- Our tests for this functionality run against Postgres, and when I rewrote the guide, I also tested locally against Postgres. I've tried to make that more explicit in the rewrite. I expect the V2 of this feature to be more advanced and robust, but for now, hopefully its current behavior will at least be clearly doc'd.

If you have a chance to work through the new guide, I'd be interested to hear how it goes!

**Comment by tal** [comment]
@samLozier sorry which slack did i give you feedback?

**Comment by joshua-stauffer** [comment]
hi @tal -- looks like a case of mistaken identity, so I've updated the tag.

**Comment by joshua-stauffer** [comment]
@samLozier [the new guide is available here](https://docs.greatexpectations.io/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_metricsstore), so I'll close this issue, but feel free to reach out if you have further issues.

**Comment by anilkulkarni87** [comment]
The doc although says beta mode , it should explicitly say that this doesnt work for column level metrics and works for the statistics. Because of `"TypeError: Object of type int64 is not JSON serializable"`

**Comment by manugarri** [comment]
sorry if this is the wrong place to ask, for what i understand, is snowflake not supported for metrics?
