### ISSUE TITLE
expect_table_columns_to_match_list

### ISSUE THREAD

**Issue by RoyalTS** [fivetran/great_expectations#409]
Sometimes I only want to check that the set of columns matches some list but don't care about the ordering. It would therefore be great to have an expectation, call it `expect_table_columns_to_match_list` that isn't quite as strict as `expect_table_columns_to_match_ordered_list`. One could also add an `ordered` argument to the expectation and dispatch to the existing expectations if `True`.

**Comment by jpcampb2** [comment]
Both of those suggestions make sense and I agree would be clearer. In the meantime, though, you can get what you're looking for with a collection of `expect_column_to_exist` expectations (as are generated if you use the autoinspect feature).
