### ISSUE TITLE
Install great-expectations 0.14.4  on google composer environment composer-2.0.2-airflow-2.1.4

### ISSUE THREAD

**Issue by bonfab** [fivetran/great_expectations#4106]
When installing packages on an composer-2.0.2-airflow-2.1.4 environment with  `gcloud composer environments update great-expectations-env --location europe-west1 --update-pypi-packages-from-file requirements.txt` a dependency conflict occurs:
`black 22.1.0 has requirement click>=8.0.0, but you have click 7.1.2.`

My requirements.txt file contains:
```
great-expectations>=0.14.4
pybigquery>=0.10.2
```
The logs:
[log.txt](https://github.com/great-expectations/great_expectations/files/7979663/log.txt)

**Comment by kenwade4** [comment]
Hi @bonfab and @jruokola! Thanks for bringing this to our attention. I don't think this is a cloud composer issue, but an incompatibility between great expectation and apache-beam. We will discuss internally and update this ticket.

**Comment by jruokola** [comment]
Some updates:

Installing pybigquery>=0.10.2 results in no errors but black requires click >=8.0.0 and flask 1.1.4 has requirement click<8.0,>=5.1
That is most likely the root cause of the conflict

**Comment by jruokola** [comment]
Tried the installation on composer-2.0.2-airflow-2.0.2 and got pybigquery installed but installing great-expectations results in following `Failed to install PyPI packages. rich 9.2.0 has requirement typing-extensions<4.0.0,>=3.7.4, but you have typing-extensions 4.0.1.
`
Downgrading typing-extensions results to `Failed to install PyPI packages. apache-beam 2.32.0 has requirement typing-extensions<3.8.0,>=3.7.0, but you have typing-extensions 3.10.0.2.
`

**Comment by dtomlinson91** [comment]
I came across this this week on `composer-1.17.9-airflow-2.1.4`.

I'm not sure what can be done on GE side (or if anything should be done) as the incompatibility comes from the Composer base images pre-installing python dependencies.

Installing packages globally in Cloud Composer is messy, even if you get it to work the next time you upgrade the base image you'll have to uninstall anything extra you've installed before applying the upgrade, or the upgrade will fail with python dependency errors (this happened to me this week, I had to uninstall great expectations to apply the upgrade and I ran into this issue after upgrading and trying to reinstall).

I got around it using the [PythonVirtualenvOperator](https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/python.html#pythonvirtualenvoperator) - the only caveat is you cannot use the GE Operator.

```python
def run_great_expectations(
    data_context_path: str,
    datasource_name: str,
    expectation_suite_name: str,
    run_name: str,
    dataset_id: str,
    table_id: str,
    **kwargs,
) -> None:
    import great_expectations as ge
    from great_expectations.checkpoint.checkpoint import SimpleCheckpoint
    from great_expectations.core.batch import RuntimeBatchRequest

    context = ge.data_context.DataContext(context_root_dir=data_context_path)

    batch_request_runtime = RuntimeBatchRequest(
    datasource_name=datasource_name,
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name=f"bq://{dataset_id}/{table_id}",
    runtime_parameters={"query": f"SELECT * FROM {dataset_id}.{table_id}"},
    batch_identifiers={"default_identifier_name": "default_identifier"},
)

    checkpoint_config = {
    "class_name": "SimpleCheckpoint",
    "run_name_template": run_name,
    "validations": [
        {
            "batch_request": batch_request_runtime,
                "expectation_suite_name": expectation_suite_name,
            }
        ],
    }
    checkpoint = SimpleCheckpoint(f"_tmp_checkpoint_{expectation_suite_name}", context, **checkpoint_config)
    checkpoint.run()

    print("building great expectations documentation")

DataQualityRunCheckpointBigQuery = PythonVirtualenvOperator(
    task_id="DataQualityRunCheckpointBigQuery",
    python_callable=run_great_expectations,
    op_kwargs={
        "data_context_path": str(pathlib.Path(__file__).parents[0] / "great_expectations"),
        "datasource_name": DATASOURCE_NAME,
        "expectation_suite_name": EXPECTATION_SUITE_NAME,
        "run_name": RUN_NAME,
        "dataset_id": "ingestion",
        "table_id": TABLE_NAME,
    },
    requirements=[
        "pyarrow",
        "google-cloud-bigquery-storage",
        "google-cloud-storage",
        "great-expectations",
        "pybigquery",
        "fsspec",
        "gcsfs",
    ],
    system_site_packages=False,
    dag=dag,
)

```

Incidentally I found Cloud Composer isn't the best for running suites on large batches, as the worker nodes by default do not have a lot of RAM. Upgrading the RAM means (at least for Composer 1) destroying and re-creating the entire Airflow environment, plus the cost of running more powerful nodes that don't need the extra resources 90% of the time. I ended up wrapping flask around the `run_great_expectations()` function above, and deploying to Cloud Run and triggering a HTTP request from the DAG to run the suites.

**Comment by itroulli** [comment]
> Incidentally I found Cloud Composer isn't the best for running suites on large batches, as the worker nodes by default do not have a lot of RAM. Upgrading the RAM means (at least for Composer 1) destroying and re-creating the entire Airflow environment, plus the cost of running more powerful nodes that don't need the extra resources 90% of the time. I ended up wrapping flask around the `run_great_expectations()` function above, and deploying to Cloud Run and triggering a HTTP request from the DAG to run the suites.

You could leverage `KubernetesPodOperator` to run this task on a separate node-pool (consisted of more powerful nodes) that can also scale to 0.

**Comment by dtomlinson91** [comment]
@itroulli Can that be used in a Composer 1 environment? I thought it was for v2 but I could be mistaken.

**Comment by itroulli** [comment]
@dtomlinson91 Yes, you can definitely create a different node-pool and run your KubernetesPodOperator tasks there. For this specific node pool you are able to enable the cluster autoscaler and specify a min and a max number of nodes. However, you need to apply the proper configurations so that Airflow does not deploy other tasks on this pool. 

If you think that won't work very well in your case, there is also the option to put some extra tasks before and after the KubernetesPodOperator task to create and delete the extra node pool during the DAG runtime.

Composer 2 on the other hand offers autoscaling on the whole environment cluster which of course applies to every task that is run there.

I'm sorry for the late response, I missed the notification.

**Comment by lopamudra04** [comment]
Hello, Is there any update on this open issue?  
I am trying GE installation on Composer 1 and it is failing due to similar error

**Comment by austiezr** [comment]
Hey @lopamudra04 et al! We have eyes on this discussion & will be reviewing in the near future.

**Comment by alexsherstinsky** [comment]
Hello, @lopamudra04 -- since the last time this issue was brought to our attention, the GreatExpectations (GX) platform has undergone many improvements.  Would it be possible for you to try your use case with the Google Composer once again (if still relevant) using the latest version of GX (current release is version "0.16.15") and let us know what problems (if any) are surfaced?  Thank you so much for your collaboration and for using GX!

**Comment by dtomlinson91** [comment]
@alexsherstinsky I can confirm on the latest version of Cloud Composer (with latest version of Airflow it supports) `composer-2.2.1-airflow-2.5.1` that installing `great-expectations==0.16.15` is successful 🚀

**Comment by lopamudra04** [comment]
@alexsherstinsky I was able to use great expectations on composer 2.

**Comment by alexsherstinsky** [comment]
@lopamudra04 So does this mean that the problem resolved itself?  Or should we be troubleshooting further?  Thank you!

**Comment by alexsherstinsky** [comment]
@lopamudra04 I am hoping that my suggestions helped.  I am closing this issue for now. Please feel free to reopen and let us know at any time.  Thank you very much for using GX!
