### ISSUE TITLE
Clarify usage with fsspec-based filesystems

### ISSUE THREAD

**Issue by sdebruyn** [fivetran/great_expectations#4112]
**Is your feature request related to a problem? Please describe.**
With Pandas, Dask, PyArrow and more I can connect to fsspec-based filesystems to load my data. My data is stored as partitioned parquet on Azure Data Lake Storage gen2 and with Pandas I can load it like this:

```python
def _get_storage_options():
    return {
        "account_name": os.environ.get("AZURE_STORAGE_ACCOUNT"),
        "credential": ChainedTokenCredential(ManagedIdentityCredential(), AzureCliCredential()),
        "anon": False,
    }


def read_from_dl(path: str, columns: list[str] | None = None) -> pd.DataFrame:
    return pd.read_parquet(
        engine="pyarrow",
        path=f"abfs://{path}",
        columns=columns,
        use_nullable_dtypes=True,
        storage_options=_get_storage_options(),
    )
```

The code above uses the `adlfs` package, which is an implementation of fsspec for Azure. I wouldn't even need the credential per se, as the default setting behaves similarly.

How can I connect to that same data with Great Expectations? I thought it would be possible since someone did the same for S3 here: https://medium.com/hashmapinc/understanding-great-expectations-and-how-to-use-it-7754c78962f4

**Describe the solution you'd like**
A documentation page clarifying how you'd configure fsspec-based access or adding the necessary implementation details if needed.

**Describe alternatives you've considered**
The only alternative I have is using runtime connector and loading the dataframes myself. The Azure-based connector only loads single files and not partitioned parquet.

**Additional context**
Checked on Slack first, but @talagluck pointed me here

**Comment by kenwade4** [comment]
Hi @sdebruyn! Thanks for bringing this to our attention. We will discuss internally if we can prioritize this. In the mean time, if you are looking to make a contribution, we would be happy to help.

**Comment by sdebruyn** [comment]
hi @kenwade4 I am quite sure that it's already possible today since there seems to be a way to pass the arguments through `reader_options`. I just don't clearly see what this would look like in the YAML.

**Comment by kenwade4** [comment]
OK @sdebruyn, in the future, we will be putting some docs together that better explain the reader options and using them with a yaml config for various backends. In the meantime, anything you can pass to the `read_parquet` method, you should be able to pass to `reader_options`. While this link is for Spark, it should work for Pandas https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/filesystem/spark/#additional-notes

```
        batch_spec_passthrough:
          reader_options:
            use_nullable_dtypes: True
            ...
```

**Comment by austiezr** [comment]
Hey @sdebruyn ! Reaching out to confirm that the above solution worked for you. I'm closing this issue out for now, but feel free to re-open if you aren't able to reach a solution here!
