### ISSUE TITLE
Unable to use expectations for date-type columns in SQLAlchemy DataSet

### ISSUE THREAD

**Issue by rahulj51** [fivetran/great_expectations#413]
I want to use 
It looks like even if we pass a date to `min_value` and `max_value` in `expect_column_max_to_be_between` , the data types are changed to strings and the comparison fails because it tries to compare a string to date. It looks like this is happening because all arguments to expectations are converted to serializable format in `recursively_convert_to_json_serializable`.

Any suggestions on how we can handle this? Happy to submit a PR but I am not sure what's the best way to fix this.

Maybe one option is to implement the `parse_strings_as_datetimes` in `SQLAlchemyDataSet` just like we have done for pandas. But is that the best way? Ideally, it would be nice if the expectations can accept arbitrary data types.

**Comment by jcampbell** [comment]
@rahulj51 -- Great question; probably you're right that we should implement the `parse_strings_as_datetimes` option for sqlalchemy, but first to make sure I understand: are the data in your table stored as a date or date/time type, and that's what's being converted, or do you mean that you're passing datetime objects in as your min/max values to the expectation and those are being converted prior to comparison?

**Comment by rahulj51** [comment]
@jcampbell, the table contains a datetime column. I am passing datetime objects for min/max values. But inside the expect function, min/max parameters get converted to strings. So the comparison fails due to data-type mismatch.

**Comment by rahulj51** [comment]
Submitted a pull request #414

**Comment by jcampbell** [comment]
👍
