### ISSUE TITLE
YAML is not YML, so use the recommended extension.

### ISSUE THREAD

**Issue by AvdN** [fivetran/great_expectations#4153]
The YML file format is a little used XML derivative (and older than YAML). 

You should use `.yaml` for files containing YAML documents when possible according to the [FAQ on yaml.org](http://yaml.org/faq.html). 
You should use `.yaml` throughout for your own files, and for those programs that support the recommended extension (and unfortunately there are some dinosaurs). 
But, e.g in the root directory of the project you have  `.readthedocs.yml` instead of the appropriate `.readthedocs.yaml`

It has only been 15 (fifteen) years that `.yaml` has been the recommendation, but it is never to late to catch up.

**Comment by austiezr** [comment]
Hey @AvdN ! Thanks for surfacing this. We'll review this and adjust as necessary.
