### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by hershaw** [fivetran/great_expectations#418]
I was forced to read the book when I was 14 years old in school and it made me not want to read for many years after that. I have very strong feelings about this name because of my past and it is an actual barrier to me using this library.

Can we change the name please?

**Comment by abegong** [comment]
What if we add a trigger warning?

**Comment by hershaw** [comment]
That would help a lot. Still not sure if I would be able to use it on a regular basis though...

**Comment by manugarri** [comment]
we could change it to the-hobbit maybe? everyone loves The Hobbit

**Comment by hershaw** [comment]
Or maybe Expect of Thrones?

**Comment by jcampbell** [comment]
We do all get the beauty of being able to tell `pip` to install it though, right?

**Comment by hershaw** [comment]
`pip install expect-of-thrones`

**Comment by hershaw** [comment]
Oh wait. I just got it. That actually is pretty good. Really hard to admit it but it's true.

**Comment by rjurney** [comment]
Personally I could relate better to bitter_disappointment. A lot of people building data pipelines could.

**Comment by jcampbell** [comment]
I kinda want to leave this issue open forever. But now that @hershaw is in on the joke, I think we should close. Eventually we could go with something intentionally meaningless...`rothka`? `authere`? `srivnere`? (good luck figuring out the origin of those suggestions!!)
