### ISSUE TITLE
No "next" button in tutorial intro

### ISSUE THREAD

**Issue by masonhopkins** [fivetran/great_expectations#4188]
**Describe the bug**
Users cannot proceed through the [getting started tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/intro) due to the "Next" button missing.

**To Reproduce**
1. Go to https://docs.greatexpectations.io/docs/tutorials/getting_started/intro
2. See that there is a "Next" button mentioned, but nothing found and no ability to proceed in the tutorial.

**Expected behavior**
A next button to proceed through the tutorial.

**Environment (please complete the following information):**
Google Chrome Version 95.0.4638.54 (Official Build) (x86_64)

**Additional context**
N/A

**Comment by austiezr** [comment]
Hey @masonhopkins ! Thanks for surfacing this; it looks like you've found a link pointing to a deprecated version of our Getting Started tutorial!

The most current version of our tutorial [can be found here](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_overview/).

Could you detail where you reached the older tutorial from?

**Comment by masonhopkins** [comment]
@austiezr good to know, thanks. I was referred to the docs from a Medium article: https://medium.com/hashmapinc/performing-data-quality-checks-in-snowflake-part-1-a3253c982460

But the exact link that I used to get to the above tutorial was from the first prerequisite in the "How to use great expectations with airflow" documentation: https://docs.greatexpectations.io/docs/deployment_patterns/how_to_use_great_expectations_with_airflow
