### ISSUE TITLE
Validating custom SQL throws error about column does not exist

### ISSUE THREAD

**Issue by ylam** [fivetran/great_expectations#419]
**Current behavior:** When I create a custom SQL to query a SQLite database it throws an error message about no such column exists. 

**Expected behavior:** Able to write custom SQL query and then validate the data from custom SQL query against custom expectations.

**Environment:**
- great  expectation version 0.4.5
- python 3.7.1 64-bit

Code is accessible at Github -> https://github.com/ylam/great_expectations

**Reproduction steps:**
1. run `python sqlite_ex.py` which generates a new db namely `ge_custom_sql.db`
2. run `python run_ge_custom_sql.py` which generates the following error message about not able to access column street_name

**Error message:**
> Traceback (most recent call last):
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
>     cursor, statement, parameters, context
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
>     cursor.execute(statement, parameters)
> sqlite3.OperationalError: no such column: street_name
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "run_ge_custom_sql.py", line 43, in <module>
>     test_custom_sqlalchemydataset(custom_dataset)
>   File "run_ge_custom_sql.py", line 37, in test_custom_sqlalchemydataset
>     result = custom_dataset.expect_column_name_to_equal_pythonroad('street_name')
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/great_expectations/dataset/base.py", line 169, in wrapper
>     raise(err)
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/great_expectations/dataset/base.py", line 156, in wrapper
>     return_obj = func(self, **evaluation_args)
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/great_expectations/dataset/sqlalchemy_dataset.py", line 164, in inner_wrapper
>     evaluation_result = func(self, column, *args, **kwargs)
>   File "run_ge_custom_sql.py", line 10, in expect_column_name_to_equal_pythonroad
>     column_value = self.engine.execute(query).scalar()
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2166, in execute
>     return connection.execute(statement, *multiparams, **params)
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
>     return meth(self, multiparams, params)
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
>     distilled_params,
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
>     e, statement, parameters, cursor, context
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
>     util.raise_from_cause(sqlalchemy_exception, exc_info)
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
>     raise value.with_traceback(tb)
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
>     cursor, statement, parameters, context
>   File "/anaconda3/envs/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: street_name
> [SQL: SELECT street_name 
> FROM person]
> (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by ylam** [comment]
Hi @elsander and @bouke-nederstigt 

I've discussed with @abegong regarding an issue about not finding columns from a custom SQL. By any chance have you encountered this issue?

**Comment by abegong** [comment]
@elsander and @bouke-nederstigt : We're asking specifically because you built the code that goes with these tests: https://github.com/great-expectations/great_expectations/blame/master/tests/sqlalchemy_dataset/test_sqlalchemydataset.py#L107-L131

Thought you might have encountered the same issue as @ylam in the process.

**Comment by elsander** [comment]
I don't think I've run into this issue. Does it pass the `expect_column_to_exist` check?

**Comment by ylam** [comment]
Hi @elsander!

I've created another python script, [run_ge_sql_default_expectation.py](https://github.com/ylam/great_expectations/blob/master/run_ge_sql_default_expectation.py#L26), to test against `expect_column_to_exist`. We see that it fails. 

Run script

> (python3) Yins-MacBook-Pro:great_expectations yplam$ python run_ge_sql_default_expectation.py 
> Columns from custom dataset 
> [{'autoincrement': 'auto',
>   'default': None,
>   'name': 'id',
>   'nullable': True,
>   'primary_key': 1,
>   'type': INTEGER()},
>  {'autoincrement': 'auto',
>   'default': None,
>   'name': 'name',
>   'nullable': False,
>   'primary_key': 0,
>   'type': VARCHAR(length=250)}]
> Expect column from custom sql
> Traceback (most recent call last):
>   File "run_ge_sql_default_expectation.py", line 32, in <module>
>     test_custom_sqlalchemydataset(custom_dataset)
>   File "run_ge_sql_default_expectation.py", line 27, in test_custom_sqlalchemydataset
>     assert result['success'] == True
> AssertionError

My question is with `custom_sql` field specified when initializing with SQLAlchemyDataset can we expect this dataset to follow what's from `custom_sql`? 

```
custom_dataset = CustomSqlAlchemyDataset(table_name='person', engine=engine, custom_sql=query) 
```

Thanks,
Yin

**Comment by elsander** [comment]
Hmm. I think the main issue I ran into with `custom_sql` was support for databases with schemas. But that should be resolved, and doesn't seem like it's what you're running into here.
