### ISSUE TITLE
"list index out of range exception" after deleting the column from CSV for which  expectations are written.

### ISSUE THREAD

**Issue by shubhamArvikarM** [fivetran/great_expectations#4192]
**Describe the bug**
Getting list index out of range exception after deleting the column from CSV for which 
expectations are written.

**To Reproduce**
1. Use an automatic profiler to create expectations from CSV (use any CSV with some columns and values)
2. Create checkpoint.
3. delete one of the columns from CSV for which expectations are written
4. run the checkpoint
5. After running the checkpoint, it's throwing an exception "list index out of range" after running checkpoint.

**Expected behavior**
The checkpoint should be executed successfully even if the column is deleted.

**Environment (please complete the following information):**
-Operating System: Windows 10
-Great Expectations Version: 0.14.0
-python : 3.9.5

**Additional context**
exception is thrown for "expect_column_values_to_be_in_type_list" built in expectations only. 
Other built-in expectations (eg. expect_column_distinct_values_to_be_in_set, expect_column_distinct_values_to_equal_set ) and custom ones created by us work as expected. 
If the columns against these are deleted, the expectation fails and is shown in the data docs report.

![image](https://user-images.githubusercontent.com/99639275/153817701-690248d0-b8f8-4a88-8a92-3670eb09ed9e.png)

**Comment by joshua-stauffer** [comment]
hi @shubhamArvikarM, thanks for creating this issue. I'll take a look and get back to you!

**Comment by joshua-stauffer** [comment]
hi again @shubhamArvikarM -- this does seem to be a bug, I've addressed it in PR #4200. Thanks again for raising this!

**Comment by alkachawda** [comment]
Hi @joshua-stauffer : The same issue exists for the other built-in expectation for checking the data type : "expect_column_values_to_be_of_type". 
Is this too fixed in this PR or should a new issue be raised for the same?

**Comment by joshua-stauffer** [comment]
Thanks for flagging that as well, @alkachawda  -- I'll address it in the same PR.

**Comment by joshua-stauffer** [comment]
hi @shubhamArvikarM and @alkachawda -- [PR 4200](https://github.com/great-expectations/great_expectations/pull/4200) merged today, so I expect this bug to be fixed in this week's release. I'll close this issue for now, but in case you continue to see this error, feel free to reopen.
