### ISSUE TITLE
Granular Control Of result_format

### ISSUE THREAD

**Issue by greg-meinecke** [fivetran/great_expectations#4202]
Currently the `result_format` parameter is limited to `BOOLEAN_ONLY|BASIC|SUMMARY|COMPLETE` with `BASIC` being the default. If I am interested in my validation returning `unexpected_index_list`, I am forced to use `result_format:COMPLETE` and all of the fields that come with it (`partial_unexpected_list`,`unexpected_list`,`partial_unexpected_index_list`,etc...). This unnecessarily increases the size  of the validation result json.

I would like to be able to choose the fields returned in the validation result, maybe something like `result_format_field_list` where one can pass a list of the fields they would like returned in the result, in my case `result_format_field_list : ["unexpected_index_list"]`

**Comment by austiezr** [comment]
Hey @greg-meinecke ! Thanks for surfacing this. We'll review this functionality internally and get back with you soon!
