### ISSUE TITLE
Improve logging options and support

### ISSUE THREAD

**Issue by jcampbell** [fivetran/great_expectations#421]
Currently, it can be overly difficult to estimate progress or get incremental results during evaluation of a large expectation suite.

**Comment by abegong** [comment]
As a first step, I'd *love* to add stepwise time logging to expectation validation.

This would be a good candidate for centralized logging: send logging info to an API to track feature usage (Which expectations are used most frequently?), and profile efficiency (Which expectations consume the most compute?) As we start to put work into optimization, this info could be a godsend.

**Comment by jcampbell** [comment]
We have significantly enhanced logging in the more recent releases of GE (though still are not profiling). I'm going to close this issue now because it's so general, and we can address more specific future updates as needed.
