### ISSUE TITLE
Error: batch_data found in batch_request with GE 0.14.6

### ISSUE THREAD

**Issue by AngelQZhang** [fivetran/great_expectations#4219]
**Describe the bug**
Hi,
I'm using SimpleCheckpoint to validate some data in Dataframe, everything works fine until we install the new GE package 0.14.6. We got this error : Error: batch_data found in batch_request -- only primitive types are allowed as Checkpoint , returned from SimpleCheckpoint statement

**To Reproduce**  
     
    batch_request = RuntimeBatchRequest(
        datasource_name="data_quality_ds",
        data_connector_name="databricks_connector",
        data_asset_name=suite_name,
        batch_identifiers={
            "batch_id": run_id,
        },
        runtime_parameters={
            "batch_data": df,
        },
    )

    checkpoint = SimpleCheckpoint(
        f"{suite_name}_check",
        data_context=context,
        class_name="SimpleCheckpoint",
        validations=[
            {"batch_request": batch_request, "expectation_suite_name": suite_name}
        ],
    )

**Expected behavior**
The pipeline should return no error

<details>
 #<summary>Click to expand the error message!</summary>

---> 81     checkpoint = SimpleCheckpoint(
     82         f"{suite_name}_check",
     83         data_context=context,

/databricks/python/lib/python3.8/site-packages/great_expectations/checkpoint/checkpoint.py in __init__(self, name, data_context, config_version, template_name, run_name_template, expectation_suite_name, batch_request, action_list, evaluation_parameters, runtime_configuration, validations, profilers, ge_cloud_id, site_names, slack_webhook, notify_on, notify_with, expectation_suite_ge_cloud_id, **kwargs)
    906         ).build()
    907 
--> 908         super().__init__(
    909             name=checkpoint_config.name,
    910             data_context=data_context,

/databricks/python/lib/python3.8/site-packages/great_expectations/checkpoint/checkpoint.py in __init__(self, name, data_context, config_version, template_name, run_name_template, expectation_suite_name, batch_request, action_list, evaluation_parameters, runtime_configuration, validations, profilers, validation_operator_name, batches, ge_cloud_id, expectation_suite_ge_cloud_id)
    558 
    559         if batch_request_in_validations_contains_batch_data(validations=validations):
--> 560             raise ValueError(
    561                 f"""Error: batch_data found in batch_request -- only primitive types are allowed as Checkpoint \
    562 constructor arguments.

ValueError: Error: batch_data found in batch_request -- only primitive types are allowed as Checkpoint constructor arguments.

</details>

**Environment (please complete the following information):**
 - Operating System: [MacOS]
 - Great Expectations Version: [0.14.6]

**Additional context**

**Comment by joshua-stauffer** [comment]
Hi @AngelQZhang, thanks for raising this issue! What you're seeing is expected behavior -- Dataframes should be passed into a DataContext's `run_checkpoint` method:

```python
import great_expectations as ge
context = ge.get_context()
context.run_checkpoint(
    checkpoint_name=f"{suite_name}_check",
    validations=[
        {"batch_request": batch_request, "expectation_suite_name": suite_name}
    ],
)
```

Closing this for now, but if you continue to run into issues feel free to reopen.
