### ISSUE TITLE
UUID field in PostgreSQL data table causes fatal exception when building a suite 

### ISSUE THREAD

**Issue by john-schwegler-vectorsolutions** [fivetran/great_expectations#4262]
**Describe the bug**
Occurs when running a profiler against a Postgres table that has a UUID field.  Attempting to build the suite caused a fatal exception:
```
  File "C:\Program Files\Python38\lib\site-packages\great_expectations\validator\validator.py", line 271, in inst_expectation
    expectation_kwargs = recursively_convert_to_json_serializable(kwargs)
  File "C:\Program Files\Python38\lib\site-packages\great_expectations\data_asset\util.py", line 121, in recursively_convert_to_json_serializable
    new_dict[str(key)] = recursively_convert_to_json_serializable(test_obj[key])
  File "C:\Program Files\Python38\lib\site-packages\great_expectations\data_asset\util.py", line 128, in recursively_convert_to_json_serializable
    new_list.append(recursively_convert_to_json_serializable(val))
  File "C:\Program Files\Python38\lib\site-packages\great_expectations\data_asset\util.py", line 190, in recursively_convert_to_json_serializable
    raise TypeError(
TypeError: 38fc04ca-4562-4da6-ba89-6ab04cd6525e is of type UUID which cannot be serialized.
```

- The GE code appears to be explicitly deciding which JSON value types can be serialized.
- Changing the column data type to varchar allows this to run correctly, no exception caused

**To Reproduce**
1. Create a PostgreSQL table with a column of type UUID
2. Run a profiler against it to build an expectation suite
3. Run validation

**Expected behavior**
It should be possible to run the profiler and then validation without an exception occurring, and save the validation correctly.

**Environment (please complete the following information):**
- OS: Windows 11
- GE version 0.14.6

**Additional context**
Appears to occur in the data_asset\util.py when attempting to serialize a value from the data column.

**Comment by AFineDayFor** [comment]
Howdy @john-schwegler-vectorsolutions,
Would you be able to share your datasource configuration and a bit more context around this please?

I'm not able to replicate this when making a csv datasource, and running against it.

For reference my datasource looks like this:

```bash
cat data/replication/uuid.csv
```
```csv
int,uuid
9678,6A3DCB2B-7A1C-4AF0-B6DB-CA51434BB625
3186,3352C63C-8D4D-4B5A-9972-08DD7B31E520
17640,7B1B88FA-F2B1-4869-9B52-710273F44F47
32608,4E3AB4E5-FEDF-466D-BAB2-9F2C18E0E7EE
11390,BF729513-6763-4422-B428-10EA49A3BC5A
3205,C76C330D-503F-4754-9AF2-81DC4AE44983
8257,A5BD4F4D-DCE8-4EDE-B0AD-2A846FEEBFA4
19488,AB5DA129-40D4-424B-AEC0-02202E0EB926
28535,3D28C184-619A-4ABF-BC11-ACD5857E7DF2
28654,6BEF75DA-0362-406C-85B3-BD64619A08C5
5821,25CB6C37-A203-4492-AE96-6BE58AE39B63
29917,80BCBB5D-806F-4B82-BED3-7040813B23A2
```


```bash
yq '.datasources.uuid' great_expectations/great_expectations.yml
```

```json
{
  "data_connectors": {
    "default_inferred_data_connector_name": {
      "module_name": "great_expectations.datasource.data_connector",
      "default_regex": {
        "group_names": [
          "data_asset_name"
        ],
        "pattern": "(.*)"
      },
      "class_name": "InferredAssetFilesystemDataConnector",
      "base_directory": "../data/replication"
    },
    "default_runtime_data_connector_name": {
      "batch_identifiers": [
        "default_identifier_name"
      ],
      "module_name": "great_expectations.datasource.data_connector",
      "class_name": "RuntimeDataConnector"
    }
  },
  "module_name": "great_expectations.datasource",
  "class_name": "Datasource",
  "execution_engine": {
    "module_name": "great_expectations.execution_engine",
    "class_name": "PandasExecutionEngine"
  }
}
```

**Comment by john-schwegler-vectorsolutions** [comment]
Ah, I believe this would not happen for a CSV data source, because the columns are not strongly typed.  The problem is caused by the data type, not the content.  In PostgreSQL, when I changed the type from UUID to varchar, but left the values as they were, the problem went away. You probably need to use a SQL database that has the UUID type. 

Here's some sample PG SQL code to test against.  Use this to create a table, then run a profiler and validate the results.

CREATE TABLE IF NOT EXISTS public.activity_test
(
    activity_id uuid,
    activity_name character varying(200),
    CONSTRAINT activity_test_pkey PRIMARY KEY (activity_id)
);

INSERT INTO public.activity_test(
	activity_id, activity_name)
	VALUES ('3f22252d-5594-43cb-9b53-bbdfb1c346d1', 'test 1'),
	('671bac47-1ebc-4817-93f1-531bc9a9ddeb', 'test 2');

**Comment by austiezr** [comment]
Hey @john-schwegler-vectorsolutions! I'm attempting to replicate the behavior you're seeing here (creating the above `activity_test` table, profiling against it, and validating) and not encountering any issues. 

I've also built a suite explicitly setting expectations on `activity_id` and not encountering any issues.

I'm wondering if there may be a specific expectation causing problems here; are you able to share the expectation suite built by your profiler?

**Comment by john-schwegler-vectorsolutions** [comment]
Sure, I'll rerun it and pass the results back to you.  Thanks!

**Comment by john-schwegler-vectorsolutions** [comment]
I've rerun and gotten the same error.  I'm attaching my code, config file, and SQL script to generate the tables I was working with.  There's also a screenshot of the error I received.
[test_package_4262.zip](https://github.com/great-expectations/great_expectations/files/8181337/test_package_4262.zip)

**Comment by austiezr** [comment]
Hey @john-schwegler-vectorsolutions ! Just pinging again re: our conversation on slack. Feel free to reach out if this is still an issue and you'd like to investigate further with us.

**Comment by john-schwegler-vectorsolutions** [comment]
Hi Austin, sorry about not getting back to you.  I got caught up in some
other work.  I'll update GE and try rerunning my test case to see
what happens.

Thanks,
John

**Comment by austiezr** [comment]
Hey @john-schwegler-vectorsolutions! Reaching back out to verify if this is still an open issue for you; still haven't been able to replicate but happy to keep digging with you if need be!

**Comment by austiezr** [comment]
Hey @john-schwegler-vectorsolutions ! Closing this out for now, feel free to re-open if it continues to be an issue.
