### ISSUE TITLE
cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by li-songlu** [fivetran/great_expectations#4265]
**Describe the bug**
ImportError: cannot import name 'Iterable' from 'collections'

**To Reproduce**
1. conda install -c conda-forge great-expectations
2. import great_expectations as ge
3. See error: cannot import name 'Iterable' from 'collections'

**Environment (please complete the following information):**
 - Operating System:  MacOS
 - Great Expectations Version: python 3.10.0

**Comment by AFineDayFor** [comment]
Howdy @li-songlu, thanks for reaching out 🎉

At this time we do not support 3.10, though do provide support for  3.6 to 3.9 at this time. I'll close this for now, but if you have any issue launching on 3.6 - 3.9 can you re-open this please.
