### ISSUE TITLE
expect_table_row_count_to_equal_other_table does not work with SparkDFDataset

### ISSUE THREAD

**Issue by dxnnymurphy** [fivetran/great_expectations#4272]
**Is your feature request related to a problem? Please describe.**
Currently unable to perform this expectation on spark datasets.

**Describe the solution you'd like**
Add functionality to execute this expectation on this type of dataset.

**Additional context**
"exception_message": "'SparkDFDataset' object has no attribute 'expect_table_row_count_to_equal_other_table'"

**Comment by AFineDayFor** [comment]
Howdy @dxnnymurphy, thanks for reaching out 🎉

`expect_table_row_count_to_equal_other_table` is only [valid for SQL](https://docs.greatexpectations.io/docs/reference/expectations/implemented_expectations); as an aside SparkDFDataset would be v2, and we encourage you to try to move to v3.
