### ISSUE TITLE
Generated config file links to old docs

### ISSUE THREAD

**Issue by afeld** [fivetran/great_expectations#4290]
**Describe the bug**
The generated `great_expectations.yml` file contains URLs that point to the legacy (V2) documentation. You can see them in the [template generator](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/data_context/templates.py).

**To Reproduce**
1. Follow the [tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_overview/).
2. After the `init`, open `great_expectations/great_expectations.yml`.
3. Copy and paste one of the https://docs.greatexpectations.io links into your browser.
4. See the banner saying `This is Legacy V2 documentation.`

**Expected behavior**
The generated file should link to the corresponding/current version of the docs.

**Environment (please complete the following information):**
 - Operating System: MacOS, Windows
 - Great Expectations Version: 0.14.8

**Additional context**
none

**Comment by kenwade4** [comment]
@afeld thanks for pointing out the reference to old docs. We will apply a fix soon

**Comment by austiezr** [comment]
Closed by #4549
