### ISSUE TITLE
Misleading exception catching

### ISSUE THREAD

**Issue by akerone** [fivetran/great_expectations#4305]
**Describe the bug**
In great_expectations/data_context/store/store_backend.py, _at least_ from versions 0.14.0 to 0.14.8, line 103. 

This exception tells us that there is something wrong in great_expectations.yaml, when in reality it could be anything. In our case, it was a missing requirement to the `google-cloud-storage` library from pip. Without a proper stack trace, it took us too much time to trace down.
 
**To Reproduce**
1. Create a new venv
2. Install great expectations
3. Configure a Store to read from GCS (with `google-cloud-storage` not installed)
4. Try following the notebook after `great_expectations datasource new`

**Expected behavior**
Printing the full stack trace of the error that occurred, rather than just a simple warning text.

**Environment (please complete the following information):**
 - Operating System: Windows 10
 - Great Expectations Version: 0.14.0 to 0.14.8 (ad minimum)

**Additional context**
![image (1)](https://user-images.githubusercontent.com/3759202/156194449-1fa7c75c-853e-4c9d-bea6-dd924a8e0ea8.png)

**Comment by talagluck** [comment]
Thanks for raising this, @akerone - we will review and be in touch!

**Comment by austiezr** [comment]
Hey @akerone ! We have eyes on this issue and will be reviewing in the near future.

**Comment by rdodev** [comment]
Hey @akerone is this still an issue in the latest version of GX?

**Comment by akerone** [comment]
Hi, 

I don't know since we stopped using Great Expectations altogether due to this and other bugs.

**Comment by rdodev** [comment]
Hey @akerone This is truly disappointing to hear :( If it's not too much to ask, would you mind sharing if you're using a different DQ tool or did you device a homegrown solution?

**Comment by akerone** [comment]
Since we decided to use dbt for our ELT processes, we're using dbt tests w/ the dbt-expectations package which tries to replicate most GX tests in "dbt-native" macros. No need for two separate systems for ELT and testing.

**Comment by molliemarie** [comment]
Hello @akerone. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core  quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example). 

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar. 

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗

**Comment by molliemarie** [comment]
Hello @akerone. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core  quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example). 

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar. 

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
