### ISSUE TITLE
get_expectation_suite is not returning expectations involving the same column

### ISSUE THREAD

**Issue by ejohnson-amerilife** [fivetran/great_expectations#4324]
**Describe the bug**
after running `get_expectation_suite`, the resulting dictionary only contains the last expectation among a set of expectations that involve the same column and same expectation type with different inputs.

**To Reproduce**
The following is a reproduceable example:

```
import great_expectations as ge
import pandas as pd
print(ge.__version__) # 0.13.46

df = pd.DataFrame(
    {"col1":['a']*4+['b']*5+['c']*6}
)

df_ge = ge.dataset.PandasDataset(df)
df_ge.expect_column_values_to_be_in_set("col1",['a'],mostly=4/15)
df_ge.expect_column_values_to_be_in_set("col1",['b'],mostly=5/15)
df_ge.expect_column_values_to_be_in_set("col1",['c'],mostly=6/15)

df_ge.get_expectation_suite(discard_failed_expectations=False)
```
which prints the following dictionary containing ONLY the last expectation even though I expect all 3 tests to be included:

```
{
  "meta": {
    "great_expectations_version": "0.13.46"
  },
  "expectations": [
    {
      "meta": {},
      "kwargs": {
        "column": "col1",
        "value_set": [
          "c"
        ],
        "mostly": 0.4
      },
      "expectation_type": "expect_column_values_to_be_in_set",
      "expectation_context": {
        "description": null
      }
    }
  ],
  "data_asset_type": "Dataset",
  "expectation_suite_name": "default",
  "ge_cloud_id": null
}

```
**Expected behavior**
I expect 3 expectations to be included, not just the last one.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.46

**Comment by talagluck** [comment]
Hi @ejohnson-amerilife - thanks for reaching out!

Generally, within an Expectation Suite, Great Expectations does not allow more than one Expectation of a given type for a given Domain (e.g. column). If you are interested in having more than one, there are two potential approaches:
1. Splitting out the various Expectations to various Expectation Suites.
2. Using [conditional_expectations](https://docs.greatexpectations.io/docs/reference/expectations/conditional_expectations), for which each condition is a considered a separate Domain, and so this would enable you to have more than one expectation of a given type for a given column.

Given this, I'm going to close this for now, but please feel free to re-open if you feel you have a strong use-case for this functionality.

**Comment by ejohnson-amerilife** [comment]
Thank you @talagluck.
My general use case is to have an Expectation that checks for proportions of each level present in a categorical variable.

Say we have a categorical variable called "Col1" containing 3 levels: "a", "b", and "c" (reference the dataframe in my example above). Then it would be nice to have an Expectation that can check if the proportion of each level is between two numbers (lower bound and upper bound). So maybe input a dictionary into the expectation such that the keys are the levels and values are the bounds.

My example above was just a workaround for something close to that.
I can create a separate ticket requesting this feature if you cannot think of a way to implement that within the current functionality.
Thank you!

**Comment by ejohnson-amerilife** [comment]
As a workaround, I was able to use conditional expectations in a hacky way to force uniqueness by filtering on a value that doesn't exist, in this case "f1", "f2", "f3". There is nothing special about those choices. Again they just need to create a filter expression that doesn't actually filter out any rows and creates uniqueness in the expression. Here is my example redone with the workaround. It's not pretty but it works:

```
import great_expectations as ge
import pandas as pd
print(ge.__version__) # 0.14.9

df = pd.DataFrame(
    {"col1":['a']*4+['b']*5+['c']*6}
)

df_ge = ge.dataset.PandasDataset(df)
df_ge.expect_column_values_to_be_in_set(column='col1',value_set=['a'],row_condition='col1!="f1"',condition_parser='pandas',mostly=4/15)
df_ge.expect_column_values_to_be_in_set(column='col1',value_set=['b'],row_condition='col1!="f2"',condition_parser='pandas',mostly=5/15)
df_ge.expect_column_values_to_be_in_set(column='col1',value_set=['c'],row_condition='col1!="f3"',condition_parser='pandas',mostly=6/15)

df_ge.get_expectation_suite(discard_failed_expectations=False)
```

**Comment by talagluck** [comment]
Thanks for this, @ejohnson-amerilife!

In case you are interested, a custom Expectation could be a great way to solve this as well. You might be able to get a proxy for this using `expect_column_kl_divergence_to_be_less_than`, which can be used with categorical columns, though it might be somewhat heavy-weight.

It sounds like what you are describing is a sort of blend of `expect_column_proportion_of_unique_values...`, `expect_column_quantile_values...`, and `expect_column_distinct_value_to_be_in_set`.

You may be aware of this, but we are currently in the midst of a [hackathon for custom expectations](https://greatexpectations.devpost.com/)! This Expectation might actually be a reasonable fit for the Fair AI category. 

Just a heads-up that tt appears that you are running V2, and the custom Expectation workflow that we have now is specifically for V3.

Otherwise, your workaround makes sense!
