### ISSUE TITLE
UserConfigurableProfiler fails against Athena database

### ISSUE THREAD

**Issue by cameronezell** [fivetran/great_expectations#4339]
**Describe the bug**
Running `great_expectations suite new` and automatically generating an expectation using a profiler against an Athena database results in the error:
```
MetricResolutionError: (pyathena.error.DatabaseError) An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 6:10: mismatched input 'OFFSET'. Expecting: <EOF>
[SQL: SELECT "metric" 
FROM (SELECT * 
FROM "temp"."table" 
WHERE true) AS "great_expectations_sub_selection" 
WHERE "metric" IS NOT NULL ORDER BY "metric"
 LIMIT %(param_1)s OFFSET %(param_2)s]
[parameters: {'param_1': 2, 'param_2': 3345262}]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```

**To Reproduce**
1.  Configure `great_expectations.yml` to include an Athena data source
2. `great_expectations suite new` then choose to automatically create the suite using a profiler
3. Run the cells in the notebook and it will result in the error described above in cell 3

**Expected behavior**
The data profiler should build a suite based on the columns commented out from the ignored_columns in cell 2

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.14.9

**Additional context**
OFFSET + LIMIT is not supported in Athena. [This stackoverflow answer](https://stackoverflow.com/questions/51298622/aws-athena-presto-offset-support) shows how it can be implemented in Athena.

**Comment by talagluck** [comment]
Hi @cameronezell - thanks for raising! We currently don't offer fully tested support for Athena, and so this doesn't surprise me. I don't believe we have immediate plans to add support for Athena, but we are always interested in community contributions! If you are interested in contributing, please let us know if we can offer any guidance or assistance.
