### ISSUE TITLE
`DataDoc` time take when created on `s3-bucket`

### ISSUE THREAD

**Issue by guidoturtu** [fivetran/great_expectations#4343]
**Describe the bug**
When the data doc site creation is moved from local to s3 bucket it takes 20 additional minutes.

**To Reproduce**
1. Create python notebook to create or edit expectations.
2. Run the `simple checkpoint on `local-site`, commenting the `s3-site` config: 1 minute take. With 2 dummy validations
3. Run the `simple checkpoint on `s3-site`, commenting the `local-site` config: 20 minute take. With 2 dummy validations
4. Compare the difference

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.14.7

**Additional context**
 - Both validations paths has ~=50 vals.
 - The s3 bucket is full dedication for the data doc.
 - Tested was with the same `ipynb` only with site commented changed from local to s3.

**Comment by talagluck** [comment]
Thanks for raising this, @guidoturtu! We will review and be in touch.

**Comment by anthonyburdi** [comment]
Hi @guidoturtu! Thank you for reaching out about this issue. I'm doing a rotation on our devrel team for the next two weeks and had a chance to review and reproduce. I created a `Checkpoint` with an `UpdateDataDocsAction` and configured my data docs site as a local site and as an s3 backed site to compare. I found that the results match your experience, the s3 site was much slower (~9 sec vs ~0.25 sec). However after profiling using Python's `cProfile` the bulk of the additional time appears to be from making connection to s3 and transferring data (see the read, write, connect etc methods at the top of this list sorted by the `tottime` column, or the time spent in the listed function, excluding sub function calls):

![image](https://github.com/great-expectations/great_expectations/assets/9903066/d329e665-a151-4797-b58d-83ba44fb5436)

I also looked through the related code and I don’t see anything obvious in the following classes related to building s3 data docs that make unnecessary calls, but if you are interested we are always looking for ways to improve the performance of Great Expectations so if you are interested please take a look and if there are any potential improvements we can make - we would love a contribution or a recommendation:

- TupleS3StoreBackend
- SiteBuilder
- HtmlSiteStore
