### ISSUE TITLE
expect_table_row_count_to_be_between able to be a conditional expectation

### ISSUE THREAD

**Issue by ejohnson-amerilife** [fivetran/great_expectations#4349]
**Describe the solution you'd like**
I wish I could use GE to count rows after a filter has been set using [conditional expectations](https://docs.greatexpectations.io/docs/reference/expectations/conditional_expectations/)
with `expect_table_row_count_to_be_between`.
**Describe alternatives you've considered**
An alternative would be to first filter the dataframe, and then create separate expectation suites to test table row counts for each filter, but this is extremely tedious and makes maintenance a nightmare.

Thank you!

**Comment by austiezr** [comment]
Hey @ejohnson-amerilife ! Thank you for raising this; we're reviewing internally and will be in touch.

**Comment by rdodev** [comment]
Feature request has been noted, if and when this is prioritized, we'll let you know.
