### ISSUE TITLE
Expectation `expect_column_quantile_values_to_be_between` casts value ranges as string

### ISSUE THREAD

**Issue by mpolena** [fivetran/great_expectations#4361]
**Describe the bug**
I'm running `expect_column_quantile_values_to_be_between()` on a column with datetime values in order to check data recency for recurring data extracts in our data pipeline.

The expectation has been defined as follows:

`    batch.expect_column_quantile_values_to_be_between(
        column="StartDate",
        quantile_ranges={
            "quantiles":[.98],
            "value_ranges":[[datetime.now(timezone.utc) - relativedelta(months=2),
                             datetime.now(timezone.utc)]],
        },
        catch_exceptions=True,
        result_format={'result_format': 'COMPLETE'},
        include_config=True,
        meta={'error_msg': '.98th percentile StartDate value outside of acceptable range.',
              'severity': 'critical',
              'action': 'warn'},
)`

The comparison is defined in the following snipped in `great_expectations/dataset/dataset.py`:
`success_details = [
            range_[0] <= quantile_vals[idx] <= range_[1]
            for idx, range_ in enumerate(comparison_quantile_ranges)
        ]`

Here range_[0] and range[1] always appear as type `str` causing a TypeError mismatch:
`*** TypeError: '<=' not supported between instances of 'str' and 'Timestamp'`

**To Reproduce**
1. Create a sample dataset with a datetime column
2. Set expectation as described above
3. Run expectation on the column
4. See error produced.

**Expected behavior**
I expect the tuple values in `value_ranges` to be interpreted as `datetime`, not as `str` in order to perform a true date comparison and  avoid the TypeError described above. 

**Environment (please complete the following information):**
 - Operating System: [Linux]
 - Great Expectations Version: version 2 [0.14.5]

**Additional context**
Appreciate your help in looking at this issue.

**Comment by austiezr** [comment]
Hey @mpolena! Thanks for surfacing this issue. After some digging, it looks like this is an issue specific *only* to V2. Unfortunately, we're not able to prioritize work on the V2 API at this time as it has been overtaken in both stability and capability by the V3 API, which is now the default API for Great Expectations. 

If you're able to migrate to V3, we have a migration guide [available here](https://docs.greatexpectations.io/docs/guides/miscellaneous/migration_guide/); I can confirm that I was unable to replicate the issue you're experiencing above in V3 for most use-cases.

If you're unable to migrate to V3, I'm happy to provide support and guidance on a contribution here to help resolve this issue, but the core team will be unable to prioritize this work internally.

**Comment by mpolena** [comment]
Thanks for your reply @austiezr! We are currently in the process of migrating to V3.

**Comment by austiezr** [comment]
Great to hear @mpolena ! I'll close out this issue for now; feel free to re-open if necessary, and feel free to reach out w/ any questions around migration!

**Comment by mpolena** [comment]
@austiezr Had a comment related to adding $PARAMETER to this expectation inside value_ranges now that our migration to V3 is complete. So far, I've been unable to do so despite multiple tries.  Is that a possibility? And if so, what would that look like?
