### ISSUE TITLE
Add All Expectations from One Existing Suite to a New Suite

### ISSUE THREAD

**Issue by sherrywang31** [fivetran/great_expectations#4362]
We have a list of expectation suites that are shared across many dataset. They do things such as checking `id` column is unique and no missing, check `age` column is within expected range etc. They are then added to dataset specific expectation suites. We currently add expectation from each of these shared suites one by one:
```
shared_suites = ['shared_suite1', 'shared_suite2']
suite = context.create_expectation_suite(expectation_suite_name="user_activity")
for shared_suite in shared_suites:
     shared_suite = context.get_expectation_suite(expectation_suite_name = shared_suite)
     for expectation in shared_suite.expectations:
         config = ExpectationConfiguration(expectation_type = expectation['expectation_type'],
                                           kwargs = expectation['kwargs'],
                                           meta = expectation['meta'])
         suite.add_expectation(expectation_configuration = config)
```

It would be great to have a `add_expecataions_from_suite` function that allows us to add all expectations from one suite to another:
```
shared_suites = ['shared_suite1', 'shared_suite2']
suite = context.create_expectation_suite(expectation_suite_name="user_activity")
for shared_suite in shared_suites:
    shared_suite = context.get_expectation_suite(expectation_suite_name = shared_suite)
    suite.add_expectations_from_suite(suite = context.get_expectation_suite(suite = shared_suite))
```

Not sure if this would be a helpful for others, or if it already exists.

**Comment by austiezr** [comment]
Hey @sherrywang31 ! Thank you for surfacing this; we're reviewing internally and will be in touch.

**Comment by rdodev** [comment]
Feature request has been noted. If and when this work is prioritized, we'll announce it.
