### ISSUE TITLE
Slack Webhook Exposed in Log

### ISSUE THREAD

**Issue by sherrywang31** [fivetran/great_expectations#4394]
It seems that the slack webhook url is exposed when there's any error. Relevant code seems to be [here](https://github.com/great-expectations/great_expectations/blob/ee792823df549f58cc86c649a4c66bcc30817790/great_expectations/checkpoint/util.py#L47). 

Is this intended? Even though a webhook would only be exposed when problems are encountered, it still feel very insecure... Would it be better to set the log level as DEBUG? Am I missing anything here?

**Comment by austiezr** [comment]
Hey @sherrywang31 ! Thank you for raising this; we'll review internally and be in touch.
