### ISSUE TITLE
In append_expecation, add an option for *not* overwriting duplicate expectations.

### ISSUE THREAD

**Issue by jpcampb2** [fivetran/great_expectations#44]

**Comment by jpcampb2** [comment]
Have there been commits against this? Looking at 0.2 milestone issues...

**Comment by jpcampb2** [comment]
@abegong flagging this again; I think we missed it in our 0.2 discussions, but this is worth thinking about in the same vein as the remove_expectation proposal from #68

**Comment by jpcampb2** [comment]
+1
They need to use similar logic.

**Comment by abegong** [comment]
After digging into this, I'm not sure we want to allow multiple, conflicting expectations. What's a use case where we need it?

Instead, I think we need to make the logic behind overwriting very clear.

### A proposal
Expectations are uniquely identified by `expectation_type` and a mix of other parameters that's determined by the expectation decorator.

```
column_map_expectations                     type, column
column_aggregate_expectations               type, column
column_pair_map_expectations                type, column_A, column_B
column_pair_aggregate_expectations          type, column_A, column_B
Other                                       type only
```

By "uniquely identified", I mean that an expectation should be overwritten by another expectation if and only if all of their identifying parameters are the same.

### Is this the right logic?

AFAICT, this logic will "do the right thing" in pretty much every instance. The only exception I've been able to think of so far is matching against multiple sets or patterns. For example, you might `expect_column_values_to_match_regex` for multiple regexes on the same column. In these cases, my proposal for overwriting expectations would make multiple expectations impossible.

However, I don't think this is a problem, for two reasons. First, we've already implemented `expect_column_values_to_match_regex_list`. With `match_on="all"`, it accomplishes the same thing as multiple expectations.

Second, very few expectations can sensibly allow multiples. Really, it's just a handful that perform element-wise matching in complex (e.g. not binary, and not numerical) domains: `expect_column_values_to_match_regex`, `expect_column_values_to_be_in_set`, and `expect_column_values_to_match_json_schema`. To make these fully general, we would have to add 
`expect_column_values_to_be_in_set_list` and `expect_column_values_to_match_json_schema_list` with `match_on` parameters. This seems reasonable to me.

### Next steps

Good news: the business logic in `base.DataSet.append_expectation` already does this for `column_map` and `column_aggregate` expectations, plus generic expectations. So this is a principled discussion of what we're already doing, not a recommended change.

To fully implement this proposal, we'd need to:
1. Extend the logic in `base.DataSet.append_expectation` to cover `column_pair` expectations.
2. Implement `expect_column_values_to_be_in_set_list` and `expect_column_values_to_match_json_schema_list`
3. Add this description of the logic to the documentation.

@jpcampb2 : Any concerns, or can I go ahead with these changes?

**Comment by abegong** [comment]
Capturing notes from today's discussion:

1. I was wrong to say that there are only 3 functions where multiple expectations or (a list+`match="any"` option) are required to express any meaningful pattern in the relevant domain. For example, `expect_column_values_to_be_between` 0 and 10 OR 20 and 30 is a valid statement that can't be expressed without multiple expectations.

2. However, it's also a rare edge case. Users who need this exact functionality could easily implement it in custom expectations.

3. In addition, the pattern expressed above can be handled quite nicely by distributional expectations with proper partitions.

So, despite the fact that I was wrong about the expressiveness of expectations, we're sticking to the proposal.
-> Multiple expectations will be automatically overwritten, using the logic described above.

**Comment by jpcampb2** [comment]
+1

**Comment by jpcampb2** [comment]
Closing this issue, as we do not plan to implement it at this time.
