### ISSUE TITLE
GE_HOME not working with command `great_expectations init`

### ISSUE THREAD

**Issue by AlbertUlysses** [fivetran/great_expectations#4417]
**Describe the bug**
GE_HOME doesn't seem to work with the `great_expectations init` command.

**To Reproduce**
1. Setup GE_HOME 
2. Run `great_expectations init`
3. View the `great_expectations` folder in the same directory - not in the one we're point at.

**Expected behavior**
Should create a great_expectation project in the GE_HOME.

**Environment (please complete the following information):**
 - MacOS
 - Great Expectations Version:  0.14.10

**Additional context**
None. Current work around is using Python to run the command as a subprocess.run

**Comment by AFineDayFor** [comment]
Howdy @AlbertUlysses :wave: thank you for raising this with us and being a part of this lovely community :bow:

At this time as we can't replicate this behaviour we're closing this ticket; however, if you're still experiencing this can you please provide the means you're using to set the variable, proof it's set, and the output of the command just so we can brush over it once more? 🔬 


example of pass:

```bash
hannah@hannah-MacBook-Pro:s007-> /Users » hannah » Code » superconductive » ge_lab (0)
> great_expectations datasource list
/Users/hannah/Code/superconductive/ge_lab/.venv/lib/python3.9/site-packages/snowflake/connector/options.py:96: UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<8.1.0,>=8.0.0; extra == "pandas"'
  warn_incompatible_dep(
Using v3 (Batch Request) API
4 Datasources found:

 - name: csv
   class_name: Datasource

 - name: json
   class_name: Datasource

 - name: txt
   class_name: Datasource

 - name: uuid
   class_name: Datasource
```

example of fault:

```bash
git❨ main ❩
hannah@hannah-MacBook-Pro:s007-> /Users » hannah » Code » superconductive » ge_lab (0)
> export GE_HOME='./ge' ; great_expectations datasource list
/Users/hannah/Code/superconductive/ge_lab/.venv/lib/python3.9/site-packages/snowflake/connector/options.py:96: UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<8.1.0,>=8.0.0; extra == "pandas"'
  warn_incompatible_dep(
Using v3 (Batch Request) API
Error: No great_expectations directory was found here!
    - Please check that you are in the correct directory or have specified the correct directory.
    - If you have never run Great Expectations in this project, please run `great_expectations init` to get started.

git❨ main ❩
hannah@hannah-MacBook-Pro:s007-> /Users » hannah » Code » superconductive » ge_lab (1)
>
```
