### ISSUE TITLE
DatasourceInitializationError

### ISSUE THREAD

**Issue by SudanYogesh23** [fivetran/great_expectations#4421]
I am trying to connect to great expectation via SSO. with the below credentials

host = "XXXXXXXXX.us-east-1"  # The account name (include region -- ex 'ABCD.us-east-1')
username = "a692@XXX.com"
database = "POC_SAMPLE"  # The database name
schema = "XXXX_POC"  # The schema name
warehouse = "XXXXXXX_XS_WH"  # The warehouse name
role = "XXXXXXXX"  # The role name
authenticator_url = "externalbrowser"

I get the following error **DatasourceInitializationError: Cannot initialize datasource my_datasource, error: (snowflake.connector.errors.OperationalError) 250003: Failed to execute request: HTTPSConnectionPool(host='XXXXXXX.us-east-1.snowflakecomputing.com', port=443): Max retries exceeded with url: /session/authenticator-request?request_guid=368f7156-0ade-4db0-a5cc-2426f75305d9 (Caused by NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x000001FF2CE8FAC0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))** 

Great_expectations version - 0.14.10

**Comment by austiezr** [comment]
Hey @SudanYogesh23 ; thank you for raising this. We'll investigate and be in touch.

**Comment by rdodev** [comment]
Hey @SudanYogesh23 is this still an issue, we have not been able to replicate.
