### ISSUE TITLE
Custom inherited expectation class : can't override a required parameter

### ISSUE THREAD

**Issue by pmariac** [fivetran/great_expectations#4445]
**Describe the bug**
Trying to create a custom expectation using custom parameters based on [this doc](https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_parameterized_expectations).
I want to check that a value (as a string) is a positive integer value, so instead of creating a `expect_column_values_to_match_regex` and set the regex everytime, I want to create a `expect_column_values_as_string_to_be_positive_integer` with a fixed regex `"^\\d+$"`
When I run it, it fails because the "regex" parameter is "not set" !

**To Reproduce**
My class code :

```
from great_expectations.core import ExpectationConfiguration
from great_expectations.expectations.core import ExpectColumnValuesToMatchRegex
from typing import Optional

class ExpectColumnValuesAsStringToBePositiveInteger(ExpectColumnValuesToMatchRegex):
    default_kwarg_values = {
        "regex": "^\\d+$",
    }

    def validate_configuration(self, configuration: Optional[ExpectationConfiguration]):
        super().validate_configuration(configuration)
        assert "regex" not in configuration.kwargs, "regex cannot be altered"

```

**Expected behavior**
Based on the documentation I expect this class to work, but I get an error:

_expect_column_values_as_string_to_be_positive_integer raised an exception: regex is required_

```
great_expectations/expectations/core/expect_column_values_to_match_regex.py", line 115, in validate_configuration
raise InvalidExpectationConfigurationError(str(e))
great_expectations.exceptions.exceptions.InvalidExpectationConfigurationError: regex is required
```

**Environment (please complete the following information):**
- Operating System: windows
- Great Expectations Version: 0.14.10

**Additional context**
Please fix this issue or remove the documentation, I did not succeed a single time in creating a custom expectation!! (see also this other issue that is almost 4 months old now: https://github.com/great-expectations/great_expectations/issues/3776)
Although this is a VERY useful feature! I would be able to create a ton of custom expectations for my users simply by overriding parameters like these, think of expectations like:
- expect column value to be valid currency (based on expect_column_values_to_be_in_set)
- expect column value to be valid country (based on expect_column_values_to_be_in_set)
- expect column as a string to be a valid float format ((based on expect_column_values_to_match_regex)
- .....

These are "public" examples but I have a lot of business expectations like these that would be very useful.

**Comment by pmariac** [comment]
Also, if you want to maintain the feature of creating a custom expectation, this should be very useful to be able to override the result string that is generated after a run for the data docs....

**Comment by austiezr** [comment]
Hey @pmariac ! Thank you for raising this; I have eyes on this issue as we speak. Stay tuned!

**Comment by pmariac** [comment]
Seems like it is already "fixed" as the "custom parameterized" way of creating an expectation has been removed from the doc yesterday with the 0.14.11 release ??! Or maybe am I missing something here?

I'll have a look at this on next week.

**Comment by austiezr** [comment]
Interesting timing! Take a look at #4455; there was a bug (thank you for identifying 🙇 ) preventing the workflow detailed in the guide. That guide should come live again soon, and the workflow you were following should be repaired. There may be similar issues with related parameterized workflows we're investigating currently. Thank you again for surfacing @pmariac !

**Comment by austiezr** [comment]
Hey @pmariac! I'll be looking into this case over the next couple of days; in the meantime you may be interested in [this documentation](https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations); the pattern and workflow from the above PR for `RegexBasedColumnMapExpectations` (which I believe fits your use case) is now live!
