### ISSUE TITLE
Requirement range for cryptography package prevents using recent versions

### ISSUE THREAD

**Issue by hsenot** [fivetran/great_expectations#4480]
Hi there,

A [recent commit](https://github.com/great-expectations/great_expectations/commit/607c9129ff9c9a6008ac6146c5a61c1d3f24d676) introduced a hard range on the cryptography module <4.0 which effectively locks it to [3.4.8](https://github.com/pyca/cryptography/releases/tag/3.4.8) in August last year.

After 3.4.8, crytography releases are numbered 35.x, 36.x and so on.

My project will defer upgrading GE until cryptography can be upgraded to more recent versions - and I suspect others might too.

Is there a specific reason why the <4.0 was chosen as an upper bound? And can it be lifted to take advantage of recent cryptography package releases?

Thanks in advance!

**Comment by austiezr** [comment]
@hsenot Thank you for surfacing! This upper bound is a requirement for use of GE w/ Azure, but we don't believe it should be a general pin. Addressing ASAP.
