### ISSUE TITLE
Requirement range for mistune locks it to an unsecure version

### ISSUE THREAD

**Issue by hsenot** [fivetran/great_expectations#4495]
Hi there,

mistune version in [requirements.txt](https://github.com/great-expectations/great_expectations/blob/develop/requirements.txt#L10) is currently bookended by 2.0.0 (strictly) meaning it is subject to a known [security vulnerability](https://security.snyk.io/vuln/SNYK-PYTHON-MISTUNE-2328096), addressed in version 2.0.2.

Would you be able to relax the upper bound so that projects can upgrade to a non-vulnerable mistune dependency?

Thanks in advance! :-)

**Comment by austiezr** [comment]
Hey @hsenot ! Thank you for raising this; we've reviewed and addressed. Mistune is no longer pinned 🙇

**Comment by talagluck** [comment]
Temporarily reverted due to some issues with testing. We are looking into the best way to resolve this.

**Comment by austiezr** [comment]
Finally resolved; thanks again for raising @hsenot !

**Comment by dgarros** [comment]
@austiezr For information, the latest  version of `mistune` (`2.0.2`) created some incompatibility for me with Jupyter and I couldn't execute the Jupyter Notebook from the getting started guide out of the box

I fixed the issue by pinning `mistune` to an older version `0.8.4`. 

Environment
- Mac M1
- Python   3.9.9
- great-expectations    0.15.1
- mistune               0.8.4
- jupyter-client        7.2.2
- jupyter-core          4.10.0
