### ISSUE TITLE
Jinja2 replaced contextfilter 

### ISSUE THREAD

**Issue by cst-care** [fivetran/great_expectations#4538]
Hi all,

Jinja2 released a new version (3.1.0) and as described in the changelog
https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0
they replaced `contextfilter` with `pass_context. evalcontextfilter`. 

When importing Great Expectations `import great_expectations as ge` we get the error
`ImportError: cannot import name 'contextfilter' from 'jinja2'`

Either the version of jinja2 can be limited up to 3.0.3 or the function could be updated.

Here is the import of the dropped function
https://github.com/great-expectations/great_expectations/blob/ee792823df549f58cc86c649a4c66bcc30817790/great_expectations/render/view/view.py#L14

Here is the version requirement:
https://github.com/great-expectations/great_expectations/blob/1c403703307b4d255cfe9179a75a0e948578ceb0/requirements.txt#L7

Thanks

**Comment by fjork3** [comment]
Thanks for flagging this! This is addressed in today's release (0.14.12), which should be coming out shortly; the `jinja2` requirement is pinned to under 3.1.0 there.

**Comment by austiezr** [comment]
Addressed by #4537 and included in [0.14.12](https://github.com/great-expectations/great_expectations/tree/0.14.12) release, now live. Thanks @cst-care !

**Comment by fvde** [comment]
This is really bad for older version users, that cannot just upgrade. We are on 0.13.6 and this issue broke all of our code that uses GE...

**Comment by austiezr** [comment]
@fvde Definitely a sudden and frustrating issue; as this is a breaking change introduced by `Jinja2 3.1.0` we recommend pinning to `jinja2>=2.10,<3.1.0` to maintain the support you've been experiencing up to this point.
