### ISSUE TITLE
Rule based profiler error on v0.14.12

### ISSUE THREAD

**Issue by sncamie** [fivetran/great_expectations#4552]
**Describe the bug**
After upgrading to Great Expectations v0.14.12 from Great Expectations v0.14.9, when i run the Rule Based profiler. I get a 

```
TypeError: <great_expectations.data_context.types.base.DatasourceConfig object at 0x7f75feaba950> is of type DatasourceConfig which cannot be serialized.
``` 
If I downgrade to v0.14.9 again and run the same script, the script runs just fine. I did this several times and got the same result. I am not sure what changed between the versions. 

**To Reproduce**
1. Go to example rule based config on the docs page
2. Click on example yaml configuration
3. run the configuration on either versions. 

**Expected behavior**
I expected the code to run the same between the two versions. 

**Environment (please complete the following information):**
Linux
 - Great Expectations Version: 0.14.12

**Additional context**

**Comment by talagluck** [comment]
Thanks for raising this, @sncamie! We will review and be in touch.

**Comment by austiezr** [comment]
Hey @sncamie ! Are you able to verify that this is still an issue on the latest versions of Great Expectations? There has been a significant amount of work in this area in recent weeks.

**Comment by austiezr** [comment]
Hey @sncamie ! Closing this out for now; feel free to re-open if this continues to be an issue for you in the latest versions of GX.
