### ISSUE TITLE
Allow Expectations with Different Severities

### ISSUE THREAD

**Issue by jcampbell** [fivetran/great_expectations#456]
This issue captures the request to allow similar expectations with different levels of severity, without overwriting the existing expectation in the config.

For example:

```
df = DataAsset(no_evaluation=True, overwrite_existing_expectations="Never")
df.expect_column_values_to_be_between('weight', 50, 300,meta={"level":"warn"})
df.expect_column_values_to_be_between('weight', 25, 400, mostly=0.98,meta={"level":"error"})
df.expect_column_values_to_be_between('weight', 10, 1000, mostly=0.98,meta={"level":"explode"})
...
df.save_expectations_config()
```

**Comment by abegong** [comment]
IMO, the main change here is `overwrite_existing_expectations`.

The `meta.level` markup is a fun little use of `meta` as an open-ended bag for parameters. If it catches on, it might later be worth promoting this to a first-class part of the API.

On `overwrite_existing_expectations`: We already have some good code hooks and comments for this. Brain dumping now for future reference:

* See `_append_expectation` in `data_asset.base`
* `_copy_and_clean_up_expectations_from_indexes` and `remove_expectations` might also be affected.

**Comment by jcampbell** [comment]
Exactly--it's about adding control on when expectations are replaced.

The complication will be when you operate on a config that was created in this mode but the mode is not on at the time.

**Comment by RoyalTS** [comment]
Would be great to be able to specify expected failures a la pytest's `xfail`s as well.

**Comment by Aylr** [comment]
Our latest best practices suggest organizing these into separate suites with names like: warn, debug, critical, etc. Closing issue for now.
