### ISSUE TITLE
Core expectation on GitHub is not listed on Great Expectations website

### ISSUE THREAD

**Issue by andyjessen** [fivetran/great_expectations#4560]
**Describe the bug**
Core expectation on GitHub is not listed on Great Expectations website.  See example: expect_multicolumn_values_to_be_unique.py . There are other core expectations not present on website.

**To Reproduce**
1. Review great_expectations/great_expectations/expectations/core/ on GitHub
3. Go to "Explore Expectations" tool on greatexpectations.io/expectations.
4. Search for "expect_multicolumn_values_to_be_unique" expectation. Expectations is not found.
![Missing Expectation](https://user-images.githubusercontent.com/62343929/160244787-1565e04c-046b-4d29-aaec-7560325bbfdc.jpg)

**Expected behavior**
Core expectations on GitHub would be present on greatexpectations.io/expectations.

**Environment (please complete the following information):**
 - Operating System: MacOs
 - Great Expectations Version: [e.g. 0.13.2]

**Comment by andyjessen** [comment]
I see in the  expect_multicolumn_values_to_be_unique.py that this expectation has been deprecated. Perhaps this exclusion is intentional.

**Comment by austiezr** [comment]
Hey @andyjessen ! Thanks for surfacing this; we believe you should see the gallery updated to reflect this expectation soon. We'll keep an eye on this 👀

**Comment by andyjessen** [comment]
@austiezr - To fix , do we need to add a block like this? 

https://github.com/great-expectations/great_expectations/blob/46cb4da9c69156ac462260d5ecb8e64e6f9d67b7/great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py#L18-L20

**Comment by austiezr** [comment]
Hey @andyjessen! Just following up here; for the time being this expectation is intentionally not a part of the gallery. As we iterate both on our gallery and our core expectations, this (and others) may be introduced to the gallery.
