### ISSUE TITLE
use pytest skip mark instead of current suppress test mechanism

### ISSUE THREAD

**Issue by jcampbell** [fivetran/great_expectations#460]
Currently, pytest reports skipped tests as successful, whether because of being on a temporary not implemented list or because of a specific case being specified as skippable.

Instead, we should either not generate the test, or generate it but mark it as skipped to give more useful metrics.

**Comment by nmaze** [comment]
I'm interested in working on this if there's broad support for making this change!  I've used pytest markers before and adding them to this project's tests would be a nice way to familiarize myself with the codebase.

**Comment by jcampbell** [comment]
@nmaze -- That would be wonderful! Would like to have a quick discussion in slack or on a call to go over where the updates would take place? You can reach me at james@superconductivehealth.com

**Comment by cselig** [comment]
Has this been addressed yet? I was doing some related work that would dovetail well with this issue

**Comment by jpcampb2** [comment]
I don't believe so; definitely not a PR yet
