### ISSUE TITLE
rule based profiler throwing error on v 0.14.13

### ISSUE THREAD

**Issue by sncamie** [fivetran/great_expectations#4612]
Describe the bug
After upgrading to Great Expectations v0.14.13 from Great Expectations v0.14.12, when i run the Rule Based profiler. I get a
```
TypeError: list indices must be integers or slices, not str
```
If I downgrade to v0.14.12 again and run the same script, the script runs just fine. I did this several times and got the same result. I am not sure what changed between the versions.

To Reproduce

    Go to example rule based config on the docs page
    Click on example yaml configuration
    run the configuration on either versions.
    See error

Expected behavior
I expected the code to run the same between the two versions.

Environment (please complete the following information):
Linux

    Great Expectations Version: 0.14.13

**Comment by talagluck** [comment]
Thanks for raising this, @sncamie! We will review and be in touch.

**Comment by talagluck** [comment]
To confirm, have you checked the latest config in the docs? Rule Based Profilers are still in beta, and so the docs and configs are still subject to change.

**Comment by sncamie** [comment]
I havent checked yet. Just saw when I try to run. But I am sure with more  updates the issue will be resolved.

**Comment by austiezr** [comment]
Hey @sncamie ! Are you able to verify that this is still an issue on the latest versions of Great Expectations? There has been a significant amount of work in this area in recent weeks.

**Comment by austiezr** [comment]
Hey @sncamie ! Closing this out for now; feel free to re-open if this continues to be an issue for you in the latest versions of GX.
