### ISSUE TITLE
expect_table_columns_to_match_set in Rule Based Profiler

### ISSUE THREAD

**Issue by sncamie** [fivetran/great_expectations#4613]
I am trying to build expectations using the rule based profiler. One of the expectations I want to include is the, expect_table_columns_to_match_set. The issue is in the parameter_builder section. The class_name for that section, I expect would be ValueSetMultiBatchParameterBuilder and the domain_builder to be TableDomainBuilder. Currently, ValueSetMultiBatchParameterBuilder works in columns and does not seem to be working for tables. If there is another way to create this level expectation using the RBP?
Using the ValueSetMultiBatchParameterBuilder with the TableDomaiBuilder gives the following error

```
great_expectations.exceptions.exceptions.ProfilerExecutionError: column.distinct_values was not found in the resolved Metrics for ParameterBuilder.
```

**Comment by talagluck** [comment]
Thanks for the question, @sncamie! We will review and be in touch.

**Comment by talagluck** [comment]
Hi @sncamie! Just following up here, the ParameterBuilder you want to use is the [MeanTableColumnsSetMatchMultiBatchParameterBuilder](https://github.com/great-expectations/great_expectations/blob/dce8d59765cc8c6d2a220094efbb8fc0e550dcef/great_expectations/rule_based_profiler/parameter_builder/mean_table_columns_set_match_multi_batch_parameter_builder.py#L24). This takes column names from one Batch and sees how well this matches with column sets across all Batches, and then computes column sets based on that.

This was built more recently than your question, but resolves it, so I'm going to close this for now, but please feel free to re-open if you have additional questions. Thanks!
