### ISSUE TITLE
Is there expectation for table columns are subset of column list?

### ISSUE THREAD

**Issue by elisim** [fivetran/great_expectations#4633]
Hi,

I did the Getting Started Tutorial, and saw `expect_table_columns_to_match_ordered_list`. In my use-case, I expect my table columns will contain the e.g. `['a','b','c']` cols, or more. Meaning, it's okay if they will have more columns, though the specified columns must be there. 

I didn't find it here:

https://greatexpectations.io/expectations

Thanks,
Eli

**Comment by austiezr** [comment]
Hey @elisim ! Thanks for reaching out. We currently have the above `expect_table_columns_to_match_ordered_list` and `expect_table_columns_to_match_set` implemented. If you're interested in contributing, we'd be happy to offer guidance and support on a contribution towards an expectation like what you've described above. While I'm closing this issue for now, feel free to reach out in this thread or on our slack if you're interested in contributing.

**Comment by david-AH** [comment]
I need this exact functionality and am interested in contributing.

**Comment by david-AH** [comment]
Actually, upon further investigation, I believe the 'exact_match' kwarg to expect_table_columns_to_match_set provides what I needed.
