### ISSUE TITLE
Will Great Expectations support Dask for parallel data integrity validation?

### ISSUE THREAD

**Issue by vnnw** [fivetran/great_expectations#478]
As Pandas is now using as one of the underlying workhorses for data validation, I think it is quite possible to use Dask as an parallel alternative in case when Pyspark is inconvenient  for deployment.

**Comment by abegong** [comment]
Dask would be a great execution engine!

I'm not deeply familiar with the Dask internals. From a first glance, it looks like we could use the same pattern that we used with python. The main strategy would be to create a `DaskDataSet` class that inherits both from `dask.DataFrame` and `great_expectations.DataSet`

Does that sounds sensible?

Refs:
* DataFrame docs [here](http://docs.dask.org/en/latest/dataframe.html)
* `DataFrame` class [here](https://github.com/dask/dask/blob/master/dask/dataframe/core.py)
* `from_pandas` method [here](https://github.com/dask/dask/blob/d8c351e2610138db984288c6922c1e0e89c8e1ca/dask/dataframe/io/io.py)

**Comment by vnnw** [comment]
> Dask would be a great execution engine!
> 
> I'm not deeply familiar with the Dask internals. From a first glance, it looks like we could use the same pattern that we used with python. The main strategy would be to create a `DaskDataSet` class that inherits both from `dask.DataFrame` and `great_expectations.DataSet`
> 
> Does that sounds sensible?
> 
> Refs:
> 
> * DataFrame docs [here](http://docs.dask.org/en/latest/dataframe.html)
> * `DataFrame` class [here](https://github.com/dask/dask/blob/master/dask/dataframe/core.py)
> * `from_pandas` method [here](https://github.com/dask/dask/blob/d8c351e2610138db984288c6922c1e0e89c8e1ca/dask/dataframe/io/io.py)

[datatable](https://github.com/h2oai/datatable) may be a valuable option too.

**Comment by abegong** [comment]
Cross-linking from the community forum: https://discuss.greatexpectations.io/t/what-is-on-your-wishlist-for-great-expectations/18/2

**Comment by solalatus** [comment]
From purely the API perspective, [Modin](https://modin.readthedocs.io/en/latest/) could also be interesting, since it claims growing "drop in replacement compatibility" with Pandas.

**Comment by mlondschien** [comment]
Note that for a Dask implementation to be sensible, expectations should first be lazily evaluated. I.e. a `ge.DaskDataset.row_count` should return a `dask.delayed` object, which gets lazily evaluated in `Dataset.expect_table_row_count_to_be_between` or `ge.DaskDataset.expect_column_values_to_be_between`.  Evalutation should only take place in `validate` [here](https://github.com/great-expectations/great_expectations/blob/f9e8a8bd92952e923c4d9feafd1c92ff88b5f394/great_expectations/data_asset/data_asset.py#L711) (?).

**Comment by ksasikanth** [comment]
Is Dask availalble as an parallel processing dataset offering in GX now?

**Comment by ksasikanth** [comment]
Current Pandas based implementation seems to be good enough for use cases containing smaller amounts of data. For Larger dataset spark context is the only solution available which requires additional infra setup. Having Dask offering which is native to python might ease out the issue with executing data tests on mid-sized datasets
