### ISSUE TITLE
Page not found: documentation about data docs

### ISSUE THREAD

**Issue by bluinchiostro** [fivetran/great_expectations#4813]
**Describe the bug**
Opening the file great_expectations.yml and clicking on https://docs.greatexpectations.io/en/latest/reference/core_concepts/data_docs.html, this page doesn't exist

**To Reproduce**
1. Go to 'great_expectations.yml'
2. Click on 'https://docs.greatexpectations.io/en/latest/reference/core_concepts/data_docs.html'

**Expected behavior**
A correct web page will be displayed

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.14.13

**Comment by andyjessen** [comment]
Hi @bluinchiostro - We fixed this issue recently in this commit (7712dc6f).

**Comment by talagluck** [comment]
Thanks for raising this @bluinchiostro and for the context @andyjessen! We will review and be in touch.

**Comment by austiezr** [comment]
Resolved in #4846
