### ISSUE TITLE
SqlAlchemyDataset does not use the correct engine to connect if engine=None.

### ISSUE THREAD

**Issue by acompa** [fivetran/great_expectations#482]
If `engine` is `None` but the user provides `connection_string`, `SqlAlchemyDataset.__init__` instantiates an engine but then ignores it when trying to introspect.

[Think this part right here](https://github.com/great-expectations/great_expectations/blob/master/great_expectations/dataset/sqlalchemy_dataset.py#L207) should be `self.engine`.

I'm trying to get a fix to you. Hoping to have that soon.

**Comment by jcampbell** [comment]
I think you're exactly right--happy to merge a PR right away, and thanks for catching that.

FYI, we've opened up a slack channel now too, so feel free to jump in there and reach the team. Open invite is available on the main project README
