### ISSUE TITLE
Pandas Value must be a nonnegative integer or None in step 3 of Getting Started notebook

### ISSUE THREAD

**Issue by ymentha14** [fivetran/great_expectations#4824]
**Describe the bug**
When following the getting started tutorial at the step 3 (Create Expectations) the first cell of the `edit_getting_started_expectation_suite_taxi.demo` notebook raises a `ValueError: Value must be a nonnegative integer or None` is from at `pandas/_config/config.py:88`.

Changing the line 17 of .. from `if version.parse(pd.__version__) <= version.parse("1.0.0"):` to `if version.parse(pd.__version__) < version.parse("1.0.0"):` seems to solve the issue in my case. (See attached stack trace)

**To Reproduce**
1. Follow the steps 1,2 and 3 of the Getting Started tutorial
2. Execute `great_expectations suite new` as described
3. Execute first cell of resulting notebook

**Expected behavior**
Pandas should not raise this exception.

**Environment (please complete the following information):**
 - Operating System:
 
NAME="Progress Linux"
VERSION="5.99 (engywuck-backports)"
ID="progress-linux"
ID_LIKE="debian"
VERSION_CODENAME="engywuck-backports"
VERSION_ID="5.99"
PRETTY_NAME="Progress Linux 5.99 (engywuck-backports)"
ANSI_COLOR="1;34"
CPE_NAME=

 - Great Expectations Version: 0.15.0
 - Pandas Version: 1.0.0

**Additional context**

Stacktrace of the error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_347870/3417123095.py in <module>
      4 
      5 import great_expectations as ge
----> 6 import great_expectations.jupyter_ux
      7 from great_expectations.core.batch import BatchRequest
      8 from great_expectations.profile.user_configurable_profiler import UserConfigurableProfiler

~/miniconda3/envs/Project2Battery/lib/python3.7/site-packages/great_expectations/jupyter_ux/__init__.py in <module>
     17 if version.parse(pd.__version__) <= version.parse("1.0.0"):
     18     # support for negative integers was deprecated in version 1.0.1
---> 19     pd.set_option("display.max_colwidth", -1)
     20 else:
     21     pd.set_option("display.max_colwidth", None)

~/miniconda3/envs/Project2Battery/lib/python3.7/site-packages/pandas/_config/config.py in __call__(self, *args, **kwds)
    231 
    232     def __call__(self, *args, **kwds):
--> 233         return self.__func__(*args, **kwds)
    234 
    235     @property

~/miniconda3/envs/Project2Battery/lib/python3.7/site-packages/pandas/_config/config.py in _set_option(*args, **kwargs)
    125         o = _get_registered_option(key)
    126         if o and o.validator:
--> 127             o.validator(v)
    128 
    129         # walk the nested dict

~/miniconda3/envs/Project2Battery/lib/python3.7/site-packages/pandas/_config/config.py in is_nonnegative_int(value)
    842 
    843     msg = "Value must be a nonnegative integer or None"
--> 844     raise ValueError(msg)
    845 
    846 

ValueError: Value must be a nonnegative integer or None

**Comment by talagluck** [comment]
Thanks for raising this and tracking down the source of the bug, @ymentha14! Would you be interested in making a contribution to fix it? Please let us know if you need any guidance or support.
