### ISSUE TITLE
Data Doc show invalid validation result

### ISSUE THREAD

**Issue by helenduww** [fivetran/great_expectations#4877]
**Describe the bug**
I have three expectations in the expectation suite. Ran validation, first two expectations pass, the third one throw exception:
`MetricResolutionError: SqlAlchemyExecutionEngine only supports the great_expectations condition_parser.` Data Doc shows all three expectations failed with the same exception. 
<img width="655" alt="image" src="https://user-images.githubusercontent.com/53539465/163594192-e365874b-7913-40b8-860a-8305715606b8.png">

**To Reproduce**
1. Create a data source for Snowflake using a private key.
2. Expectation suite
```
{
  "data_asset_type": null,
  "expectation_suite_name": "rockerbox_mta_suite",
  "expectations": [
      {
      "expectation_type": "expect_compound_columns_to_be_unique",
      "kwargs": {
        "column_list": [
          "order_id",
          "event_id",
          "market"
        ],
        "ignore_row_if": "any_value_is_missing"
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_values_to_be_in_set",
      "kwargs": {
        "column": "market",
        "value_set": [
          "US",
          "UK"
        ]
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_sum_to_be_between",
      "kwargs": {
        "column": "EVEN",
        "condition_parser": "pandas",
        "max_value": 1.01,
        "min_value": 0.99,
        "row_condition": "ORDER_ID==18240968"
      },
      "meta": {}
    },
  ],
  "ge_cloud_id": null,
  "meta": {
    "citations": [
      {
        "batch_request": {
          "data_asset_name": "ods_rockerbox.mta_with_utm_and_ad_params_hd",
          "data_connector_name": "default_inferred_data_connector_name",
          "datasource_name": "rockerbox_mta_snowflake",
          "limit": 1000
        },
        "citation_date": "2022-04-15T14:12:40.072405Z",
        "comment": "Created suite added via CLI"
      }
    ],
    "great_expectations_version": "0.14.11"
  }
}
```
3. Create a checkpoint and run validation. All tests are failed with the same error message

**Expected behavior**
The first two tests pass, only the third one fails

**Environment (please complete the following information):**
 -  MacOS
 - Great Expectations Version: 0.14.11

**Additional context**

**Comment by AFineDayFor** [comment]
Howdy @helenduww, thanks for reaching out 🎉
We'll bring it up amount the team and get back to you. We may need to ask for a bit more context. Thank you for raising this.

**Comment by talagluck** [comment]
Hi @helenduww - apologies for delays here. It looks like like your backend is Snowflake, but you are attempting to use a `pandas` `condition_parser`. I believe that you need to specify `sql` as your `condition_parser` instead. Since this is a configuration issue, I'm going to close this for now, but please feel free to reopen if you have additional questions.
