### ISSUE TITLE
Great Expectation functions not seen in SparkDF Dataset

### ISSUE THREAD

**Issue by vysakhdevaraj** [fivetran/great_expectations#4928]
Hi,

As part of using the great expectations functions which are there in the default great expectations library ,the following functions I tried in the default great expectations.
expect_column_min_to_be_between
expect_column_max_to_be_between
expect_column_mean_to_be_between
expect_column_median_to_be_between

When I tried with the spark integrated great expectatiions which is sparkdf_dataset It seems the mentioned functions are not working or not there .Could you please confirm the mentioned functions are available in spark dataset?

Kindly advice any alternate solutions are there to use the above functions as part of sparkDF dataset or spark integrated solution.

**Comment by talagluck** [comment]
Hi @vysakhdevaraj - thanks for your question. What do you mean when you say they are not working? All of those expectations should work with Spark. Do you have an error message you can share?

On another note, it appears that that you are using the V2 API, based on your use of `sparkdf_dataset`. The V2 API is no longer being actively maintained, and so I would recommend that you use the V3 API instead.

**Comment by vysakhdevaraj** [comment]
Hi @talagluck  Thanks for the Update!! Now It worked .
