### ISSUE TITLE
Display content of SQL query in validation result doc

### ISSUE THREAD

**Issue by hkwweber** [fivetran/great_expectations#4970]
**Is your feature request related to a problem? Please describe.**
When I use a RuntimeBatchRequest to define the BigQuery data I want to read with a SQL query, there's no way for me to see what query I ran (and therefore what data was used) in the validation results doc. 

**Describe the solution you'd like**
Instead of `SQLQuery` displayed in the `query` field in the validation doc, I'd like to see the actual text of the query run, e.g. `SELECT * FROM <mytable> ...`. 
![Screen Shot 2022-04-08 at 17 02 05](https://user-images.githubusercontent.com/27975703/165547776-f41ac4a0-0002-4d2e-a8a1-c0ce79ad2d9f.png)

**Describe alternatives you've considered**
The status quo (displaying `SQLQuery` and not the query run) is an alternative. This works okay for adhoc use, e.g. if a user has just run a validation manually and immediately reads the validation docs, but in any other situation it would be really helpful to see the query used.

**Additional context**
Using RuntimeBatchRequest with SQL queries seems like a really powerful way to use BQ data, but not being able to see which query was used for a validation would make it hard for us to use in production.

**Comment by talagluck** [comment]
Thanks for raising this, @hkwweber - we will review and be in touch.

**Comment by talagluck** [comment]
Hi @hkwweber - thanks for your patience! I wanted to let you know that we'll be discussing this internally this week to figure out when we can prioritize.
