### ISSUE TITLE
Great Expectations throwing error after successful installation

### ISSUE THREAD

**Issue by rajnil-guha01** [fivetran/great_expectations#4998]
Hi,
I have installed great expectations using pip on my Mac OS which completes successfully. After successful installation when I try to run the command `great_expectations --version` it throws an error as below:

`ModuleNotFoundError: No module named 'scipy._lib'`

I am using below versions of Python and pip
Python: 3.8.0
pip: 22.0.4

**Comment by austiezr** [comment]
Hey @rajnil-guha01 ! Thanks for reaching out. Would you be able to provide some more context around your environment, the version of Great Expectations you've installed, whether you're on an M1 mac or not, etc?

**Comment by rajnil-guha01** [comment]
Hi @austiezr , thanks for checking. I just realised there was a problem with the python version installed on my Mac. I have re-installed it and it all seems to be working fine now. I have re-installed GE and am able to use it. We can close this issue for now, if I face any other issue I will create a new one then.

**Comment by austiezr** [comment]
Thanks for the update @rajnil-guha01 ! 🚀
