### ISSUE TITLE
package name and directory name conflict- please change main directory name (great_expectations)

### ISSUE THREAD

**Issue by zivshapiraintel** [fivetran/great_expectations#5000]
**Is your feature request related to a problem? Please describe.**
when I develop code locally, on my laptop, I use
`import great_expectations as ge`

which works fine, including the auto-complete and help, when I highlight a chosen method.

However, once I run 
`great_expectations init`

a directory with the name great_expectations is created at the same folder as my main code. From this point, the import looks into this directory and I lose all the auto complete and help, because this directory takes precedence to the package, with the same name.

**Describe the solution you'd like**
Please rename the main directory that is created when running the command great_expectations init, to avoid a conflict with the package name

**Comment by austiezr** [comment]
Hey @zivshapiraintel! Thanks for reaching out. Would you be able to provide some context around the workflow you're seeing this behavior with? As a general rule we would encourage calling `great_expectations init` from a working directory separate from the actual `great_expectations` package. We believe doing so should generally prevent name-space collisions of this type.

**Comment by zivshapiraintel** [comment]
Hi @austiezr, In my working directory I have python code (main.py) that imports great_expectations as ge, and uses methods, for example:

- `context = ge.data_context.DataContext(...`
- `context.save_expectation_suite(suite)`

The IDE (pycharm in my case) provides auto-complete and tooltip help (when highlighting the name of the method), as expected.

At the same directory, I need to run `great_expectations init` for the code to function (otherwise I get an error, that the directory is missing)

Once great_expectations directory is created, the precedence of the import shifts from the package to the directory, where for example: 

1. .data_context. is suddenly not found (marked in the IDE as missing)
2. no help provided when highlighting save_expectation_suite

if the name of the root directory, post running init, can be set via configuration to be different from the default great_expectations, there should be no issue.

I hope this clarifies the issue.

**Comment by zivshapiraintel** [comment]
relevant for me. i did not get a response to my clarification above

**Comment by austiezr** [comment]
Hey @zivshapiraintel! Thanks for your patience here. I can verify a couple of things; it isn't possible to change the name of the `great_expectations` directory name at this time, and it won't be for the foreseeable future. 

Additionally, I wasn't able to replicate the exact behavior you're seeing. I've set up a small `main.py` to work in, alongside a `great_expectations` directory. After verifying that my interpreter is utilizing a venv with Great Expectations installed, my Pycharm code completion pulls up results from both the directory & the package; I'm wondering if there may be a configuration in Pycharm python interpreter causing the issue you're experiencing. 

Would you be willing to re-configure clean (fresh env w/ Great Expectations, fresh Pycharm project configured w/ that env, fresh `great_expectations --v3 init`), and test if you still are seeing *only* code completion for the directory and not the package?

**Comment by zivshapiraintel** [comment]
hi @austiezr thanks for the useful info. i will try an update asap

**Comment by zivshapiraintel** [comment]
@austiezr i tried the command
1. for me it did not accept the --v3 option - it suggested **--v3-api** this worked and created the directory
2. this time the autocomplete and tooltips continued to work on the package and not the directory. That's fine for me.

![ge_dir_and_package](https://user-images.githubusercontent.com/11042279/183407105-a11a7543-102e-44b9-9731-cdc46ab5f3ac.png)
