### ISSUE TITLE
Support distributed filesystems in data_contexts

### ISSUE THREAD

**Issue by mastratton3** [fivetran/great_expectations#501]
Today you can instantiate a `SparkCSVDataContext` with an s3 path such as:

```
import great_expectations as ge
dc = ge.get_data_context("SparkCSV", "s3a://super-secret-bucket/best_datasets/")
```

You will be able to read files:
```
dc.get_dataset("cool_people.csv")
```

However, if you try to run `list_datasets()` you will get an exception as it'll try to read from the local filesystem.

**Comment by jcampbell** [comment]
Thanks for bringing up this issue. If you would be willing to be part of the preview of design for our next iteration of data contexts, I'd love to go over the design for the new context / datasource / generator system that we're building right now in the feature/data_context branch. Implementing better distributed filesystem support would look somewhat different in that context, so having a different perspective on how it *should* work would be useful right now.

**Comment by mastratton3** [comment]
Hey James - It would be great to be part of the preview.

**Comment by jcampbell** [comment]
Wonderful -- pinging on slack.

**Comment by jcampbell** [comment]
This support is now available!
