### ISSUE TITLE
Great Expectations function in spark Dataset shows error

### ISSUE THREAD

**Issue by vysakhdevaraj** [fivetran/great_expectations#5012]
Hi,
 As part of great expectation function execution using spark dataset , I am getting error for the function expect_column_quantile_values_to_be_between.

When I tried to execute the function with the great expectation dataset ,I am getting the following error.
sales_ge.expect_column_quantile_values_to_be_between(column='Unit price', allow_relative_error='lower', quantile_ranges={'quantiles': [0.05, 0.25, 0.5, 0.75, 0.95], 'value_ranges': [[15.28, 15.28], [32.9, 32.9], [55.04, 55.04], [77.72, 77.72], [97.21, 97.21]]})

ValueError                                Traceback (most recent call last)
<command-1046591616166754> in <module>
----> 1 sales_ge_float.expect_column_quantile_values_to_be_between(column='Unit price', allow_relative_error='lower', quantile_ranges={'quantiles': [0.05, 0.25, 0.5, 0.75, 0.95], 'value_ranges': [[15.28, 15.28], [32.9, 32.9], [55.04, 55.04], [77.72, 77.72], [97.21, 97.21]]})

/local_disk0/pythonVirtualEnvDirs/virtualEnv-a6af9de8-7ace-4082-8fa4-449b04d06c5c/lib/python3.8/site-packages/great_expectations/data_asset/util.py in f(*args, **kwargs)
     74         @wraps(self.mthd, assigned=("__name__", "__module__"))
     75         def f(*args, **kwargs):
---> 76             return self.mthd(obj, *args, **kwargs)
     77 
     78         f.__doc__ = doc

/local_disk0/pythonVirtualEnvDirs/virtualEnv-a6af9de8-7ace-4082-8fa4-449b04d06c5c/lib/python3.8/site-packages/great_expectations/data_asset/data_asset.py in wrapper(self, *args, **kwargs)
    287 
    288                         else:
--> 289                             raise err
    290 
    291                 else:

/local_disk0/pythonVirtualEnvDirs/virtualEnv-a6af9de8-7ace-4082-8fa4-449b04d06c5c/lib/python3.8/site-packages/great_expectations/data_asset/data_asset.py in wrapper(self, *args, **kwargs)
    274                 ):
    275                     try:
--> 276                         return_obj = func(self, **evaluation_args)
    277                         if isinstance(return_obj, dict):
    278                             return_obj = ExpectationValidationResult(**return_obj)

/local_disk0/pythonVirtualEnvDirs/virtualEnv-a6af9de8-7ace-4082-8fa4-449b04d06c5c/lib/python3.8/site-packages/great_expectations/dataset/dataset.py in inner_wrapper(self, column, result_format, row_condition, condition_parser, *args, **kwargs)
    153                 null_count = None
    154 
--> 155             evaluation_result = func(self, *args, **kwargs)
    156 
    157             if "success" not in evaluation_result:

/local_disk0/pythonVirtualEnvDirs/virtualEnv-a6af9de8-7ace-4082-8fa4-449b04d06c5c/lib/python3.8/site-packages/great_expectations/dataset/dataset.py in expect_column_quantile_values_to_be_between(self, column, quantile_ranges, allow_relative_error, result_format, include_config, catch_exceptions, meta)
   2928             )
   2929 
-> 2930         quantile_vals = self.get_column_quantiles(
   2931             column, tuple(quantiles), allow_relative_error=allow_relative_error
   2932         )

/local_disk0/pythonVirtualEnvDirs/virtualEnv-a6af9de8-7ace-4082-8fa4-449b04d06c5c/lib/python3.8/site-packages/great_expectations/dataset/sparkdf_dataset.py in get_column_quantiles(self, column, quantiles, allow_relative_error)
    738             or allow_relative_error > 1
    739         ):
--> 740             raise ValueError(
    741                 "SparkDFDataset requires relative error to be False or to be a float between 0 and 1."
    742             )

ValueError: SparkDFDataset requires relative error to be False or to be a float between 0 and 1.

Is this function suports in sparkdataset ? Please advice to proceed further.

**Comment by austiezr** [comment]
Hey @vysakhdevaraj! Thanks for reaching out.

It looks like you're using the V2 API; under the V2 API, `expect_column_quantile_values_to_be_between` supports `allow_relative_error` as either `False` or a float between 0 and 1. Currently you are trying to pass `allow_relative_error` as `"lower"`,  which is only supported by the V3 API.

If you're interested in migrating to the V3 API, we have a [migration guide available here](https://docs.greatexpectations.io/docs/guides/miscellaneous/migration_guide); the V3 API is more stable, powerful, and actively supported.

If you need to stick with the V2 API and want to see this functionality come into the V2 API, we would be happy to provide support and guidance on a community contribution here, but the core team will be unable to prioritize any work internally on the now-deprecated V2 API.
