### ISSUE TITLE
Creating pex file with great expectations issue

### ISSUE THREAD

**Issue by pavanpcr** [fivetran/great_expectations#5013]
**Describe the bug**

While building Pex file using the below command, it's throwing error as given below: 

**Command:** pex -v -r requirements.txt  dist/any.whl -o dist/any.pex --disable-cache --inherit-path=fallback --platform linux-x86_64-cp-37-cp37m

**ERROR:** Could not find a version that satisfies the requirement termcolor>=1.1.0 (from great_expectations->-r requirements.txt (line 9)) (from versions: none)
ERROR: No matching distribution found for termcolor>=1.1.0 (from great_expectations->-r requirements.txt (line 9))

**Expected behavior**
Pex file should be built successfully 

**Environment (please complete the following information):**
 - Operating System: MacOs M1 Chip
 - Great Expectations Version: 0.15.3
 - Python: 3.7.10

**Comment by austiezr** [comment]
Hey @pavanpcr ! Thanks for reaching out. Are you able to verify that you experience this behavior if attempting to build a Pex file from a different `requirements.txt`? While `termcolor` is a core requirement, it isn't managed by us, and if incompatible with Pex, is not something we will be able to address

**Comment by austiezr** [comment]
Hey @pavanpcr! Closing this out for now; if you feel this to be in error, feel free to re-open!
