### ISSUE TITLE
vectorized types in pandas

### ISSUE THREAD

**Issue by RoyalTS** [fivetran/great_expectations#502]
One set of tests that are not yet vectorized in pandas are the tests for data types. The current versions of these tests check column data type row by row, which is an excruciatingly slow process. Ideally, I think, one ought to do this in a vectorized fashion as well.

Alas, GE's type system doesn't map super neatly onto pandas'. But perhaps it ought to! Would you consider harmonizing GE's system with the system pandas uses internally (https://pandas.pydata.org/pandas-docs/stable/reference/general_utility_functions.html#data-types-related-functionality)? Alternatively would you consider a set of pandas-specific expectations that check for dtype rather than type?

**Comment by jcampbell** [comment]
We built a small PR to use dtypes to avoid row-level type checks where possible (essentially whenever dtype isn't `object`); it's #444  . One option is to go ahead and merge that.

Longer term, we're planning to try to more clearly differentiate "semantic types" (like 'integer') from storage types (like int64 / int32 / etc.) to ensure there's a class of expectations that are both performant and useful across data_asset types as well as a way to express the full range of necessary types.

I'd be happy to do a quick call to go over design options, and would definitely welcome a new PR with a revised approach.

**Comment by RoyalTS** [comment]
I think merging #444 is probably a step in the right direction and a good idea. Can still figure out better ways to handle this later.

**Comment by RoyalTS** [comment]
Were you planning on merging #444 sometime soon? Currently testing pandas DataFrames with 4.5 million rows and a couple hundred columns and it's taking a while :)

**Comment by jpcampb2** [comment]
Yes --thank you for flagging the importance of that; I will get it
integrated for our 0.7.1 release later today.

**Comment by RoyalTS** [comment]
fixed in #444 and commits thereafter
