### ISSUE TITLE
Treatment of missing/NULL as unexpected in expectation expect_column_values_to_match_regex

### ISSUE THREAD

**Issue by bluinchiostro** [fivetran/great_expectations#5027]
Running the expectation expect_column_values_to_match_regex verifies that the regex provided as an argument is respected by the elements of the column which, if different from strings, are transformed into strings before executing the expectation. 
However, if the column contains missing, the validation result always returns 100% matching. It is understandable that where the data is not there, it cannot conflict with the regex but wanting to open a discussion on validity, it would mean stating that the total of the rows is congruent to the constraint of the regex, while it satisfies the expectation only the percentage of data actually available (not missing). 

A further development of the expectation could be implemented in such a way that we can treat the missing as unexpected, specifying it with an additional argument.

The alternative is to manually perform the calculation after executing the checkpoint, subtracting from the number of rows the number of unexpected and the number of missing, but this takes a lot of time for different batches and expenditure of resources.

**Comment by rishabhsahrawat** [comment]
"It is understandable that where the data is not there, it cannot conflict with the regex"
Is it true in case of Great Expectations or in general?

**Comment by bluinchiostro** [comment]
Hey @rishabhsahrawat, it's a general consideration but great_expectations assumes that if a field is null, then expectation can't be executed

**Comment by AFineDayFor** [comment]
LGTM @bluinchiostro, the team shared the same conclusion in #5232 as well.
