### ISSUE TITLE
Support for Historical Data Docs on incremental data

### ISSUE THREAD

**Issue by abekfenn** [fivetran/great_expectations#5055]
**Is your feature request related to a problem? Please describe.**
Some datasets are extremely large and only change in relatively small increments over time. Currently, in order to produce data docs that illustrate the state of our expectations as it relates to the entire dataset, we must evaluate the entire dataset. However, large datasets can take a very long time to evaluate our expectations against despite the fact that the majority of the data has not changed.

**Describe the solution you'd like**
I would like the ability to evaluate my expectations against only incremental data while retaining the ability to understand the state of data quality for my entire dataset.

**Describe alternatives you've considered**
The only alternative I can think of is validating the entire dataset, which is not scalable for the aforementioned reasons.

**Additional context**
This would get admittedly tricky in providing lists of unexpected values and calculating percentages. Metadata across runs would have to be compared, unexpected_index_list(s) would have to be de-duped, and we would need a means of determining that one expectation in one batch is the same as another in a past batch (to make comparisons).

**Comment by austiezr** [comment]
Hey @abekfenn ! Thanks for reaching out. We *do* have eyes on these types of historical metrics and incremental validations. As we continue to address and review this type of functionality, our current recommendation for work-around would be to create data assets representing only the changed data, and running your extant expectation suites against these smaller batches.

Closing this out for now, but I'll update this thread as more information around functionality in this area becomes available!
