### ISSUE TITLE
Include_Config output not matching docs

### ISSUE THREAD

**Issue by andyjessen** [fivetran/great_expectations#5067]
**Describe the bug**
Attempting to reproduce the [include_config example](https://docs.greatexpectations.io/docs/reference/expectations/standard_arguments#include_config) from the docs. 

**To Reproduce**
1. Create ge dataframe
`import great_expectations as ge`
`import pandas as pd`
`result_values = ['B', 'C', 'D', 'F', 'G', 'H', 'A', 'E', 'E', 'E', 'E', 'E']`
`df = pd.DataFrame (result_values, columns = ['my_var'])`
`ge_df=ge.from_pandas(df)`
3. Apply expectation
`ge_df.expect_column_values_to_be_in_set(`
` "my_var",  ['B', 'C', 'D', 'F', 'G', 'H'],`
`    result_format="COMPLETE",`
` include_config=True,`
`)`
4. Results
{
  "success": false,
  "result": {
    "element_count": 12,
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_count": 6,
    "unexpected_percent": 50.0,
    "unexpected_percent_total": 50.0,
    "unexpected_percent_nonmissing": 50.0,
    "partial_unexpected_list": [
      "A",
      "E",
      "E",
      "E",
      "E",
      "E"
    ],
    "partial_unexpected_index_list": [
      6,
      7,
      8,
      9,
      10,
      11
    ],
    "partial_unexpected_counts": [
      {
        "value": "E",
        "count": 5
      },
      {
        "value": "A",
        "count": 1
      }
    ],
    "unexpected_list": [
      "A",
      "E",
      "E",
      "E",
      "E",
      "E"
    ],
    "unexpected_index_list": [
      6,
      7,
      8,
      9,
      10,
      11
    ]
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

**Expected behavior**
Results don't match documented example. Configuration not included

{
    'exception_index_list': [0, 10, 11, 12, 13, 14],
    'exception_list': ['A', 'E', 'E', 'E', 'E', 'E'],
    'expectation_type': 'expect_column_values_to_be_in_set',
    'expectation_kwargs': {
        'column': 'my_var',
        'result_format': 'COMPLETE',
        'value_set': ['B', 'C', 'D', 'F', 'G', 'H']
    },
    'success': False
}

**Environment (please complete the following information):**
 - Operating System:  MacOS
 - Great Expectations Version: 0.15.4

**Additional context**

**Comment by austiezr** [comment]
Hey @andyjessen ! Thanks for raising this. The `ge.from_pandas()` workflow is a V2 construct, and not currently under active development; as such, it may not behave as expected, and may exhibit some instability. Have you experienced this same behavior working with V3 workflows?

**Comment by austiezr** [comment]
Hey @andyjessen ! Closing this out for now; feel free to re-open if this continues to be an issue.
