### ISSUE TITLE
Improved organization of query stores

### ISSUE THREAD

**Issue by bluinchiostro** [fivetran/great_expectations#5138]
**Problem statement**
Query stores are very useful for dynamically passing a set as an evaluation parameter. However, writing queries to the yml file configuration document makes this file less readable when there are many queries.

**Proposed solution**
It would be desirable to be able to configure the query store the same way a suite is configured, for example, with one or more separate files, called up in the configuration file with a single line.

**Consequences of the improvement**
This feature would improve the structure and organization of the entire data quality process, also promoting the interaction between different team members who collaborate on different topics.

**Comment by austiezr** [comment]
Hey @bluinchiostro ! Thanks for raising this. We'll discuss internally and be in touch.

**Comment by bluinchiostro** [comment]
@austiezr It's still relevant

**Comment by talagluck** [comment]
Hi @bluinchiostro ! Thanks again for raising this. It is unlikely we will be able to prioritize this in the immediate future but we have had added this to our backlog, and will take it into account when we are able to make improvements to the Query Store. Closing for now.
