### ISSUE TITLE
Add datasource using auth tokens

### ISSUE THREAD

**Issue by Shubhkishore** [fivetran/great_expectations#5143]
**Is your feature request related to a problem? Please describe.**

Adding a new data source using auth tokens
For example, adding a mssql datasource (azure synapse sql) using Azure AD token. Something similar to [this](https://stackoverflow.com/questions/57193301/pass-azure-ad-token-for-azure-sql-db-in-pre-connection-arguments-to-sqlalchemy-c/57193499#57193499). 

**Describe the solution you'd like**
Add support to use connection strings using tokens for authentication. Something similar to the example stated above

**Describe alternatives you've considered**
Currently, all authentications are userid/password-based. This feature would help to authenticate through other mechanisms.

**Additional context**

**Comment by austiezr** [comment]
Hey @Shubhkishore ! Thanks for raising this. We're discussing internally how best to move forward on this; we'll be in touch with further guidance!

**Comment by austiezr** [comment]
Hey @Shubhkishore ! Thanks for reaching out. We believe you should already be able to do this, as Great Expectations supports connection via passing of a [connection string](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/database/mysql#3-add-credentials), including one parameterized with credentials of any type, including an auth token.

Closing this out for now, but if you aren't able to configure as above, feel free to re-open!
