### ISSUE TITLE
Outdated Data Docs link appear in Slack notifications

### ISSUE THREAD

**Issue by sravantit25** [fivetran/great_expectations#5151]
Hi,

In the Slack notifications that come up after a Checkpoint run,  I see that the link to the documentation in the generated message is outdated/doesn't work.

Snippet of the link from the message:

Learn how to review validation results in Data Docs: https://docs.greatexpectations.io/en/latest/guides/tutorials/getting_started/set_up_data_docs.html

**Comment by austiezr** [comment]
Hey @sravantit25 ! Thanks for raising this; we will review internally and get back to you.
