### ISSUE TITLE
`expect_column_max_to_be_between` unexpected exception with `PandasDataset`

### ISSUE THREAD

**Issue by holaluz-josep-martinez** [fivetran/great_expectations#5160]
**Describe the bug**
Hi, 

I'm running some validations over an in-memory `PandasDataset`. Two of them are `expect_column_min_to_be_between` and `expect_column_mmax_to_be_between`, and they raise a `TypeError` exception
```
'>=' not supported between instances of 'Timestamp' and 'str'
```
even if the column dtype and `min_value` and `max_value` are pandas Timestamp (`datetime64[ns]`) or `datetime`  objects.

I have tried to use the `parse_strings_as_datetimes` flag; doing so resolves the issue, but triggers the following warning
```
DeprecationWarning: The parameter "parse_strings_as_datetimes" is deprecated as of v0.13.41 in v0.16. As part of the V3 API transition, we've moved away from input transformation. For more information, please see: https://greatexpectations.io/blog/why_we_dont_do_transformations_for_expectations/
```

**To Reproduce**
Unzipping and running the following codeshould allow you to reproduce the issue I just described.
[ge_issues.zip](https://github.com/great-expectations/great_expectations/files/8727280/ge_issues.zip)

**Environment (please complete the following information):**
 - Operating System: Windows 10 Pro, version 21H2
 - Great Expectations Version: 0.15.5

Thank you in advance for your time and help

**Comment by austiezr** [comment]
Hey @holaluz-josep-martinez ! Thanks for reaching out. We'll review internally and be in touch.

**Comment by austiezr** [comment]
Hey @holaluz-josep-martinez ! Thanks for surfacing this; we have eyes on this issue and will be reviewing in the near future.

**Comment by austiezr** [comment]
Hey @holaluz-josep-martinez ! Are you able to confirm that this is still an issue on the most recent versions of Great Expectations? I'm unable to reproduce (no `TypeErrors`) from at least `great_expectations>=0.15.20`

**Comment by holaluz-josep-martinez** [comment]
Hi @austiezr! I'd say it is not an issue in the most recent versions (at least I can't reproduce it either).

**Comment by austiezr** [comment]
Hey @holaluz-josep-martinez ! Great to hear. Closing out for now; feel free to re-open if the issue re-surfaces!
