### ISSUE TITLE
CLA / TravisCI

### ISSUE THREAD

**Issue by jpcampb2** [fivetran/great_expectations#52]
These are more admin than code changes, but I'm putting them here so they don't get forgotten.

* Migrate repo
* Add CLA
* Hook up Travis

**Comment by jpcampb2** [comment]
In terms of repo migration, it looks like we can easily just set up a new organization from GitHub perspective which would allow me to setup Travis. Does GreatExpectations organization make sense?

**Comment by abegong** [comment]
@jpcampb2 Can we close this one?

**Comment by jpcampb2** [comment]
Done.
