### ISSUE TITLE
Slow performance for connecting S3 data sources with large number of objects

### ISSUE THREAD

**Issue by nzqs** [fivetran/great_expectations#5200]
**Is your feature request related to a problem? Please describe.**
Inferred and Configured data asset connectors are very slow when connecting to an s3 bucket and prefix with a large number of objects. For a bucket with ~10m objects, it takes over 4 hours for a validator to retrieve a batch of data. I was using the Spark execution engine, but I expect the Pandas engine would be similarly slow. The issue seems to be with the data connector, creating a batch from an in memory Spark df performs appropriately. 

I dug into the codebase a bit, and I think the bottleneck is [here](https://github.com/great-expectations/great_expectations/blob/7e53b615c36a53f78418ce46d6bc91a7011163c0/great_expectations/datasource/data_connector/util.py#L430) - boto retrieves 1000 keys at a time, requiring many thousands of list_objects_v2 calls for buckets with millions of objects. This looks single threaded, each call blocks until completion before the next is made

**Describe the solution you'd like**
I would like to use Inferred or Configured data connectors to have useful guarantees when creating batches of my data. An in-memory dataframe is not always available or convenient to create - using a BatchRequest is preferred. 
In spark, something like this runs on the order of seconds to minutes 
```
df = spark.read.format("delta").load("s3://bucket/keyspace/").where(F.col("partition_col") == "foo").where(F.col("date") == '2021-01-01')
```
If possible, I would like to see a BatchRequest's data_connector_query filter parameters (below) perform similarly, but I understand this may require an infeasible refactor of how a connector's data reference lists are populated with boto. 
```
batch_request = BatchRequest(
    ...
    data_connector_name="inferred/configured_data_connector",
    batch_spec_passthrough={"reader_method": "delta",},
    data_connector_query={"batch_filter_parameters": {"partition_col":"foo", "date": "2021-01-01", }},)
```

**Describe alternatives you've considered**
Both of these work well and will probably be my path forward for the time being
1. Using a Runtime data connector to wrap a pre-queried dataframe 
```
df = spark.read.format("delta").load("s3://bucket/keyspace/").where(F.col("partition_col") == "foo").where(F.col("date") == '2021-01-01')
runtime_batch_request = RuntimeBatchRequest(
    ...
    data_connector_name="spark_df_connector",
    runtime_parameters={"batch_data": df})
```
2. Alternatively, data can be split with a Data connector's splitting methods. But this again requires a Runtime data connector to be performant
```
df = spark.read.format("delta").load("s3://bucket/keyspace/")
spark_batch_request = RuntimeBatchRequest(
    ...
    data_connector_name="spark_df_connector",
    runtime_parameters={"batch_data": df},
    batch_spec_passthrough={
        "splitter_method": "_split_on_multi_column_values",
        "splitter_kwargs": {
            "column_names": ["partition_col", "date"],
            "batch_identifiers": {"partition_col":"foo", "date": "2021-12-31"},
        },
    },
)
```

**Additional context**
Original slack request for fuller code example and context [here](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1652736744882329)

**Comment by rdodev** [comment]
Howdy @nzqs we appreciate the report. I will reach out to the core dev team and put this issue and suggestion up for discussion.

**Comment by rdodev** [comment]
Hey @nzqs I believe my colleague @austiezr recommended using `ConfiguredAsset` as opposed to to `InferredAsset`. Did you have a chance to try this? Also we would appreciate if you can share your configs so we can better diagnose the issue.

**Comment by nzqs** [comment]
Hey @rdodev! Thanks for looking at this. I gave the `ConfiguredAssetS3DataConnector` a go and the performance is similarly poor when pointing to keyspaces with a large number of objects, probably due to making many boto list object calls to paginate through objects. 
Here's the environment I was running on. Let me know if there any specific configs the team needs
GE version 15.3
[Databricks runtime env 9.1](https://docs.databricks.com/release-notes/runtime/9.1.html)
Cluster: i3.4xlarge master + 19 workers of the same

**Comment by talagluck** [comment]
Hi @nzqs - thanks again for your config information here! This has been added to our backlog, though we do not know exactly when we will work on it.

**Comment by herrykarmito92** [comment]
@rdodev @talagluck 
I have same pain point but I'm implemented on Google BigQuery.

To reduce cost on BigQuery when we implemented GE , the best practice is to set partition table because we do not need to scanning whole table. Just needed for specific date or integer value.

But when i tried to implemented piece of code above, and error come out 
```
BigQuery not have splitter_kwargs function
```
and I tried using `data_connector_query` , engine also replied cannot find `batch_filter_parameters`

Do Great Expectations have a documentations about detail every connector?

**Comment by talagluck** [comment]
Hi @herrykarmito92 - thanks for your comment! Have you followed the documentation on splitting here? https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/datasource_configuration/how_to_configure_a_sql_datasource#splitting-methods

I believe that splitters should work for BigQuery. If after following the documentation above you are unable to get this to work, please open a new Issue, since it sounds like you are describing something unrelated.

**Comment by herrykarmito92** [comment]
Hi @talagluck 
I will retry again the process from the documentation your suggested.
Will update to you and posted via slack community.

Thank you very much.

> Hi @herrykarmito92 - thanks for your comment! Have you followed the documentation on splitting here? https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/datasource_configuration/how_to_configure_a_sql_datasource#splitting-methods
> 
> I believe that splitters should work for BigQuery. If after following the documentation above you are unable to get this to work, please open a new Issue, since it sounds like you are describing something unrelated.

**Comment by rdodev** [comment]
Issue has been noted in our product backlog. If and when this optimization work is prioritized, it will be announced or expressed in release notes.

**Comment by IOANNIS1234** [comment]
Hi @nzqs, I have the exact issue. But apart from the fact that it takes hours for a validator to retrieve a batch of data, every small file of S3 is treated independently. GE fires one Spark job for each file, resulting in a huge overhead of the Spark cluster. Is there an option to concatanate all files under one S3 directory together and only then create a Batch Request that will include all of them?
