### ISSUE TITLE
`TableExpectation.validate_metric_value_between_configuration` throws exception when comparting dicts

### ISSUE THREAD

**Issue by cbuffett** [fivetran/great_expectations#5221]
**Describe the bug**
The static method `validate_metric_value_between_configuration` has checks in place to validate that if the passed in min/max values are dictionaries, that they contain the `$PARAMETER` keyword, but then immediately attempts to compare said dictionaries using the `>` inequality operator, resulting in an exception:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [15], in <module>
     98 print(eval_param_urn_min)
     99 print(eval_param_urn_max)
--> 100 validator_target.expect_column_min_to_be_between(col_name, min_value={'$PARAMETER': eval_param_urn_min}, max_value={'$PARAMETER': eval_param_urn_min})
    101 validator_target.expect_column_max_to_be_between(col_name, min_value={'$PARAMETER': eval_param_urn_max}, max_value={'$PARAMETER': eval_param_urn_max})

File ~/.virtualenvs/great_expectations/lib/python3.8/site-packages/great_expectations/validator/validator.py:383, in Validator.validate_expectation.<locals>.inst_expectation(*args, **kwargs)
    377         validation_result = ExpectationValidationResult(
    378             success=False,
    379             exception_info=exception_info,
    380             expectation_config=configuration,
    381         )
    382     else:
--> 383         raise err
    384 return validation_result

File ~/.virtualenvs/great_expectations/lib/python3.8/site-packages/great_expectations/validator/validator.py:334, in Validator.validate_expectation.<locals>.inst_expectation(*args, **kwargs)
    327     configuration.process_evaluation_parameters(
    328         self._expectation_suite.evaluation_parameters,
    329         True,
    330         self._data_context,
    331     )
    333 try:
--> 334     expectation = expectation_impl(configuration)
    335     """Given an implementation and a configuration for any Expectation, returns its validation result"""
    337     if not self.interactive_evaluation and not self._active_validation:

File ~/.virtualenvs/great_expectations/lib/python3.8/site-packages/great_expectations/expectations/expectation.py:172, in Expectation.__init__(self, configuration)
    168 def __init__(
    169     self, configuration: Optional[ExpectationConfiguration] = None
    170 ) -> None:
    171     if configuration is not None:
--> 172         self.validate_configuration(configuration)
    173     self._configuration = configuration

File ~/.virtualenvs/great_expectations/lib/python3.8/site-packages/great_expectations/expectations/core/expect_column_min_to_be_between.py:213, in ExpectColumnMinToBeBetween.validate_configuration(self, configuration)
    202 """
    203 Validates that a configuration has been set, and sets a configuration if it has yet to be set. Ensures that
    204 necessary configuration arguments have been provided for the validation of the expectation.
   (...)
    210     None. Raises InvalidExpectationConfigurationError if the config is not validated successfully
    211 """
    212 super().validate_configuration(configuration=configuration)
--> 213 self.validate_metric_value_between_configuration(configuration=configuration)

File ~/.virtualenvs/great_expectations/lib/python3.8/site-packages/great_expectations/expectations/expectation.py:1613, in TableExpectation.validate_metric_value_between_configuration(configuration)
   1610 except AssertionError as e:
   1611     raise InvalidExpectationConfigurationError(str(e))
-> 1613 if min_val is not None and max_val is not None and min_val > max_val:
   1614     raise InvalidExpectationConfigurationError(
   1615         "Minimum Threshold cannot be larger than Maximum Threshold"
   1616     )
   1618 return True

TypeError: '>' not supported between instances of 'dict' and 'dict'
```

**To Reproduce**
Attempt to use the expect_column_min_to_be_between expectation with evaluation parameters

**Expected behavior**
Evaluation parameters should be substituted prior to inequality check or dictionaries should be handled separately.

**Environment (please complete the following information):**
 - Operating System: Ubuntu 20 (Windows WSL2)
 - Great Expectations Version: 0.15.4

**Additional context**
In this case, interactive evaluation was disabled.

**Comment by rdodev** [comment]
Hey @cbuffett Thanks for issue report. I'll be asking the dev team about this. A question though:

* What do you mean by "In this case, interactive evaluation was disabled." Did you manually disabled it?

**Comment by cbuffett** [comment]
Correct. It was disabled using `validator_target.interactive_evaluation = False`. This is necessary, otherwise an exception is thrown because the evaluation parameters haven't actually been created in memory yet (this happens when running the checkpoint later on I believe). This is called out in Step 3 of https://docs.greatexpectations.io/docs/guides/expectations/advanced/how_to_create_expectations_that_span_multiple_batches_using_evaluation_parameters/

**Comment by molliemarie** [comment]
Hello @cbuffett. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
