### ISSUE TITLE
Oracle SQL - Create temporary table error with invalid where clause

### ISSUE THREAD

**Issue by thanhmt-dev** [fivetran/great_expectations#5224]
**Describe the bug**
During init of expectation suite, creating oracle temporary table failed with invalid relational operator.

**To Reproduce**
1. Init with an oracle source from sqlalchemy connection string
2. Create expectation suite, select table and select option 3. Automated using profiler
3. Error
```python
DatabaseError: (cx_Oracle.DatabaseError) ORA-00920: invalid relational operator
[SQL: CREATE GLOBAL TEMPORARY TABLE ge_temp_8143ce6e ON COMMIT PRESERVE ROWS AS SELECT * 
FROM tx.customer 
WHERE true]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
````
**Expected behavior**
Work as expected

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.14

**Additional context**
If we replace where true by where 1=1, it work on our sqlalchemy code. We need a workaround

**Comment by rdodev** [comment]
Hey @thanh-tran-techx 👋 

A few questions:
1. Did you look into disabling temp tables?
2. Could you test this on a newer version of great_expectations?
3. We don't explicitly support Oracle, however, we would welcome Oracle-specific contributions from the community.

**Comment by thanhmt-dev** [comment]
I'm quite new to the lib, and still following the get started guide. I'm using the latest version of great_expectations.

I replaced this piece of code in the file `sqlalchemy_batch_data.py`, line 147 
`query = str(selectable).replace("WHERE true", "WHERE 1=1")`

Apparently `WHERE true` is not a valid SQL condition in Oracle.
The profiling work fine for now. Will report if any further bug occurs.
