### ISSUE TITLE
expect_column_values_to_match_regex skips Null(empty) column values

### ISSUE THREAD

**Issue by rishabhsahrawat** [fivetran/great_expectations#5232]
**Describe the bug**
I am using **expect_column_values_to_match_regex** function with regex, ^[-+]?(\\d*[.])?\\d+$. My spark dataframe column has a mix of negative, positive, float and also no values.

**Expected behavior**
Given my regex pattern, the function should raise an error. 

Any reasons why I am seeing this behaviour? 
Thank you in advance!

**Comment by AFineDayFor** [comment]
Howdy @rishabhsahrawat, thanks for reaching out and being a part of the community 🎉

The regular expression ( `^[-+]?(\d*[.])?\d+$` ) is valid in that it runs can capture positive and negative floats, and ints. Can you elaborate on why this is to fail in this case?

For us to further look into this, can you share your current configuration or workflow.

🙇

**Comment by rishabhsahrawat** [comment]
Hey @AFineDayFor ,
Thanks for your response. As I mentioned, the spark dataframe column also has no values (so basically just empty). My question is shouldn’t the regex fail since it does not have any expression for those empty/ no values?

**Comment by AFineDayFor** [comment]
Howdy @rishabhsahrawat :wave: if the regex doesn't present a match, the team concludes it ought to return a null and not be managed be supplied to metrics nor any metrics yielded.
