### ISSUE TITLE
Documentation encourages deprecated behavior for RuntimeDataConnector

### ISSUE THREAD

**Issue by sdebruyn** [fivetran/great_expectations#5233]
The current version of the [documentation for RuntimeDataConnector](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_configure_a_runtimedataconnector) puts the `batch_identifier` in the config.

This is [deprecated](https://github.com/great-expectations/great_expectations/pull/4889) in 0.15.2.

As a new user it is unclear what I have to change and how it impacts me. Please make sure the documentation is updated and recommends the right way of doing things when deprecating things.

**Comment by AFineDayFor** [comment]
Howdy @sdebruyn, thank you very much for raising this with us 🎉

**Comment by talagluck** [comment]
Hi @sdebruyn - thanks again for raising this! Closing this now, as it has been resolved.
