### ISSUE TITLE
SqlAlchemy row_condition for postgressql

### ISSUE THREAD

**Issue by gorikdesmetds** [fivetran/great_expectations#5260]
**Describe the bug**
When executing row_condition for condition_parser "great_expectations__experimental__", i receive the following error message:

SyntaxError: subquery in FROM must have an alias
LINE 2: FROM (SELECT * 
             ^
HINT:  For example, FROM (SELECT ...) [AS] foo.

The row_condition is 'col("STATUS")=="operational"'

**To Reproduce**
1. Go to 'expectation suite configuration'
2. add row_condition and parser to your exepctatation config for sqlALchemy data source
3. Try to run the expectation with validator

**Expected behavior**
Row condition can be added to the config

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.15.2

**Comment by austiezr** [comment]
Hey @gorikdesmetds ! Thanks for reaching out. Are you able to share some more information about your environment (Windows edition, SQLAlchemy version, backend), as well as the full expectation configuration? That will help us better understand what may be happening here.

**Comment by austiezr** [comment]
Hey @gorikdesmetds ! I'm going to close this out for now; if you're still experiencing this issue and are able to provide the context above, feel free to re-open!
