### ISSUE TITLE
Display selected columns in data docs in case of failures

### ISSUE THREAD

**Issue by colibri17** [fivetran/great_expectations#5265]
**Is your feature request related to a problem? Please describe.**
When an expectation fails, I cannot view on the dashboard (the data docs) the entire row (and not just the column value) which caused that failure. For example, if I have a failure because the maximum value of a numerical column _col1_ is over a threshold, I can see that value, but I cannot see the related _col2_ or _col3_ values.

**Describe the solution you'd like**
When adding an expectation, I would like to be able to specify which columns should be displayed in the dashboard in case of failures.

**Describe alternatives you've considered**
I am aware that there exists the option "unexpected_index_list" to get the ids of the dataset which causes the fails, but I would like to be able to view the entire row/the selected columns directly on the dashboard. I also tried the option "include_unexpected_rows", but id does not work as expected.

**Comment by kenwade4** [comment]
Hello @colibri17 thank you very much for raising this request. We are not going to be able to modify this behavior for the foreseeable future. As a workaround, you should be able to parse the validation results JSON.

**Comment by talagluck** [comment]
Hi @colibri17 - revisiting this, I believe it is resolved by #6448. I'm going to close this for now, but if you have any follow-ups in the short-term, please post them in this related issue: #3195 . Thanks!
