### ISSUE TITLE
Transient failures related to checkpoint config parsing by ruamel.yaml

### ISSUE THREAD

**Issue by gray-sat** [fivetran/great_expectations#5280]
**Describe the bug**
I'm implementing some simple expectations within a foreachBatch of a spark structured streaming application. BaseDataContext is instantiated once, along with its datasource and checkpoint config, and checkpoint validations are added at runtime via the validations kwarg.

I keep getting errors related to parsing the checkpoint configuration at some point after a number of batches & expectations have been successfully run for each checkpoint. I'm seeing various different errors occurring in run_checkpoint > get_checkpoint > get > deserialize > load related to ruamel yaml parsing depending on the retry.

**To Reproduce**
Run code like the following in a foreachBatch call during a Spark Structured Streaming application.
```
def init_context(self):
    if not self.context:
        data_context_config = DataContextConfig(
            store_backend_defaults=S3StoreBackendDefaults(default_bucket_name="fuse-expectations")
        )
        context = BaseDataContext(project_config=data_context_config)

        datasource_config = {
            "name": f"{self.suite_name}_datasource",
            "class_name": self.datasource_class,
            "execution_engine": {"class_name": self.engine_class},
            "data_connectors": {
                f"{self.suite_name}_batch_connector": {
                    "module_name": "great_expectations.datasource.data_connector",
                    "class_name": self.connector_class,
                    "batch_identifiers": self.batch_identifiers,
                }
            }
        }
        context.test_yaml_config(yaml.dump(datasource_config))
        context.add_datasource(**datasource_config)

        checkpoint_config = {
            "name": self.checkpoint_name,
            "config_version": 1,
            "class_name": "SimpleCheckpoint",
            "run_name_template": f"%Y%m%d-%H%M%S-{self.suite_name}-checkpoint",
            "runtime_configuration": {
                "result_format": {
                    "result_format": "COMPLETE",
                    "include_unexpected_rows": True
                }
            }
        }
        context.test_yaml_config(yaml.dump(checkpoint_config))
        context.add_checkpoint(**checkpoint_config)
        self.context = context
...

def run_checkpoint(...): 
    self.init_context()
    # batch_request normally returned elsewhere with same code
    batch_request = RuntimeBatchRequest(
        datasource_name=f"{self.suite_name}_datasource",
        data_connector_name=f"{self.suite_name}_batch_connector",
        data_asset_name=f"{self.suite_name}",
        batch_identifiers={
            "environment": os.environ.get("FUSE_ENV") or 'dev',
            "epoch_id": epoch_id
        },
        runtime_parameters={"batch_data": df}
    )
    checkpoint_validations = [{"batch_request": batch_request, "expectation_suite_name": self.suite_name}]
    ...
    return self.context.run_checkpoint(
        checkpoint_name=self.checkpoint_name,
        validations=checkpoint_validations
    )
```

A subset of exceptions I have encountered are attached along with the checkpoint config as stored in the S3 backend immediately following the failures. **Interestingly, when downloaded, the checkpoint config is stored as JSON locally, though it is marked as yml in S3 for both suffix and type.**

**Expected behavior**
Structured streaming batches should be processed as normal without failing after a number of successful batches and therefore successful parsing of the checkpoint configuration.

**Environment (please complete the following information):**
 - Operating System: Ubuntu 20.04.4 LTS
  Java: Zulu 8.56.0.21-CA-linux64
  Scala: 2.12.10
  Python: 3.8.10
  Delta Lake: 1.0.0

 - Great Expectations Version: 0.15.8

**Additional context**
Runtimes vary before failure. The longest I've seen is 59 minutes which amounts to approx. 20 batches. Sometimes it fails during the initial batch. Sometimes after just a few. TL;DR the time before exception is highly variable.

[checkpoint-configs.zip](https://github.com/great-expectations/great_expectations/files/8871914/checkpoint-configs.zip)
[exception_1.txt](https://github.com/great-expectations/great_expectations/files/8871925/exception_1.txt)
[exception_2.txt](https://github.com/great-expectations/great_expectations/files/8871924/exception_2.txt)
[exception_3.txt](https://github.com/great-expectations/great_expectations/files/8872219/exception_3.txt)

**Comment by kenwade4** [comment]
Hello @gray-sat thanks for reaching out. Can you tell us what happens if you load the checkpoint in memory (i.e. don't add the checkpoint to the store). You should be able to do checkpoint.run and pass in the batch request. After talking with the team, the combo of doing things in memory and saving things doesn't seem quite right.

**Comment by gray-sat** [comment]
Thanks for the response @kenwade4. If I understand what you mean by defining the checkpoint in memory, then it looks something like this:

```
def init_context(self):
    if not self.context:
        data_context_config = DataContextConfig(
            store_backend_defaults=S3StoreBackendDefaults(default_bucket_name="fuse-expectations")
        )
        context = BaseDataContext(project_config=data_context_config)

        datasource_config = {
            "name": f"{self.suite_name}_datasource",
            "class_name": self.datasource_class,
            "execution_engine": {"class_name": self.engine_class},
            "data_connectors": {
                f"{self.suite_name}_batch_connector": {
                    "module_name": "great_expectations.datasource.data_connector",
                    "class_name": self.connector_class,
                    "batch_identifiers": self.batch_identifiers,
                }
            }
        }

        context.test_yaml_config(yaml.dump(datasource_config))
        context.add_datasource(**datasource_config)
        self.context = context

...

def run_checkpoint(...):
        checkpoint_validations = [{"batch_request": batch_request}]
        checkpoint = SimpleCheckpoint(self.checkpoint_name, self.context, 1,
                                      run_name_template=f'%Y%m%d-%H%M%S-{self.suite_name}-checkpoint',
                                      expectation_suite_name=self.suite_name,
                                      runtime_configuration={"result_format": {"result_format": "COMPLETE",
                                                                               "include_unexpected_rows": True}})
        return checkpoint.run(validations=checkpoint_validations)
```

So far, this is working. This pattern strikes me as odd in that the only value which is changing per batch is the checkpoint validations to be run -- i.e. only the batch request is changing. Seems that the context should be able to handle loading the checkpoint config which is unchanging and passing only the validations which have changed since the last checkpoint run. The latter seems to be the pattern which is described by [the docs](https://docs.greatexpectations.io/docs/guides/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint/) as well.

Maybe those need to be updated, or am I misunderstanding the circumstances for which that documentation is relevant?

**Comment by molliemarie** [comment]
Hello @gray-sat. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
