### ISSUE TITLE
Running the OnboardingDataAssistant raises error. 

### ISSUE THREAD

**Issue by ejmoll** [fivetran/great_expectations#5315]
**Describe the bug**
When I try to run the OnboardingDataAssistant (third cell) of the 'Initialize a new Expectation Suite by profiling a batch of your data' notebook, I get the following error:  

> File ~\.conda\envs\hld\lib\site-packages\great_expectations\rule_based_profiler\parameter_builder\numeric_metric_range_multi_batch_parameter_builder.py:506, in NumericMetricRangeMultiBatchParameterBuilder._estimate_metric_value_range(self, metric_values, estimator_func, round_decimals, domain, variables, parameters, **kwargs)
```
    503 for metric_value_idx in metric_value_vector_indices:
    504     # Obtain "N"-element-long vector of samples for each element of multi-dimensional metric.
    505     metric_value_vector = metric_values[metric_value_idx]
--> 506     if np.all(np.isclose(metric_value_vector, metric_value_vector[0])):
    507         # Computation is unnecessary if distribution is degenerate.
    508         numeric_range_estimation_result = NumericRangeEstimationResult(
    509             estimation_histogram=np.histogram(
    510                 a=metric_value_vector, bins=NUM_HISTOGRAM_BINS
   (...)
    514             ),
    515         )
    516     else:
    517         # Compute low and high estimates for vector of samples for given element of multi-dimensional metric.
```
> 
> IndexError: index 0 is out of bounds for axis 0 with size 0

**To Reproduce**
1. In command line, run 'great_expectations suite new'
2. Create expectation suite through option 3: Automatically, using a profiler
3. Select a datasource 
4. Run the notebook: the third cell (context.assistants.onboarding.run(...)) raises an error

**Expected behavior**
I expect the notebook to run without errors. 

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.15.9

**Additional context**

**Comment by austiezr** [comment]
Hey @ejmoll ! Thanks for surfacing this; we'll review internally and be in touch.

**Comment by ejmoll** [comment]
@austiezr Thanks, looking forward for your reply :)

**Comment by austiezr** [comment]
Hey @ejmoll! Thanks for your patience. With the official launch of the OnboardingDataAssistant this past week, there's been a LOT of work done here. Are you able to verify whether or not you're still encountering this issue as of the most recent version of GX?

**Comment by austiezr** [comment]
Hey @ejmoll ! Closing this out for now; if you continue to encounter this issue, feel free to re-open!
