### ISSUE TITLE
Directory values in DataContext object not compatible in Windows

### ISSUE THREAD

**Issue by nikdotcodes** [fivetran/great_expectations#5333]
**Describe the bug**
When getting an object from a DataContext object (i.e. `get_checkpoint()`) in a windows environment it raises an `InvalidKeyError` and `FileNotFoundError` due to the concatenation of a Path (with `\\` seperators) with the "Base_Directory" key in DataContext object (has `/` seperator)

**To Reproduce**
```python
from great_expectations import DataContext
data_context = DataContext()
checkpoint = data_context.get_checkpoint("checkpointName")
```

**Actual behaviour**
```
Traceback (most recent call last):
  File "D:\..\lib\site-packages\great_expectations\data_context\store\tuple_store_backend.py", line 301, in _get
    with open(filepath) as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\..\\expectations\\great_expectations\\checkpoints/run_checkpointName_checkpoint.yml'
```
Notice the ``\\checkpoints/run_checkpointName_checkpoint`` separators

**Expected Behaviour**
A checkpoint object is created

**Environment**
- Windows 10 Pro (Build 10.0.19044)
- Great Expectations 0.15.9
- Python 3.10.2

**Comment by AFineDayFor** [comment]
Howdy @nikdotcodes :wave: thanks for raising this with us; we'll bring it up with the team :bow:

As GE is recommended to be ran on an Unix environment, rather than the NT kernel; are you able to produce a similar result on a Unix machine or is a hypervisor or container an option as well?
