### ISSUE TITLE
Unable to return string function of trino.sqlalchemy.datatype.DOUBLE

### ISSUE THREAD

**Issue by aezomz** [fivetran/great_expectations#5341]
**Describe the bug**
Unable to parse Trino DOUBLE() data type due to no str function. 
On this line of code
https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/rule_based_profiler/helpers/simple_semantic_type_filter.py#L125

**To Reproduce**
1. great_expectations suite new --profile onboarding-data-assistant
2. test runnning with any double column
3. I recommend testing with this catalog and table `tpcds.sf1.customer`  , column `acctbal`

**Expected behavior**
It should use the visit type of Trino Compiler which subclass GenericTypeCompiler.

I am happy to create a PR for this, but I am not sure how to fix this. Any guidance will be great.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: develop

**Additional context**

```
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 89, in _compiler_dispatch
    meth = getter(visitor)
AttributeError: 'GenericTypeCompiler' object has no attribute 'visit_DOUBLE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 623, in __str__
    return str(self.compile())
  File "/venv/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 606, in compile
    return dialect.type_compiler.process(self)
  File "/venv/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 402, in process
    return type_._compiler_dispatch(self, **kw)
  File "/venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 91, in _compiler_dispatch
    util.raise_(
  File "/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x13db3f2b0> can't render element of type <class 'trino.sqlalchemy.datatype.DOUBLE'> (Background on this error at: http://sqlalche.me/e/13/l7de)
```

**Comment by aezomz** [comment]
Ohh, i found the solution. Is to use compile with dialect specified directly, which will return the string version of the datatype.

I will create PR after I am done testing with Trino. To see if there is anymore fixing needed to run a MVP.

Below is the solution if your interested... 
```
# column_type: str = str(column_types_dict_list[0]["type"]).upper()
        column_type: str = column_types_dict_list[0]["type"].compile(dialect=dialect).upper()
```

**Comment by AFineDayFor** [comment]
Howdy :wave: thank you very much for raising this and taking charge @aezomz :bow:

**Comment by aezomz** [comment]
issue is fixed with the newer version of GE, which handles this.
