### ISSUE TITLE
Unable to create User DSN as Datasource

### ISSUE THREAD

**Issue by tchung555** [fivetran/great_expectations#5371]
When creating new datasource, the process did not seem to finish and got stuck.  I had to press Ctrl+C to quit the process and no datasource was created.  I copied the process and pasted in the **To Reproduce** section below.

**To Reproduce**
(.venv) PS C:\Users\XXXXX\ge_webinar_demo> great_expectations datasource new
Using v3 (Batch Request) API

What data would you like Great Expectations to connect to?
    1. Files on a filesystem (for processing with Pandas or Spark)
    2. Relational database (SQL)
: 2

Which database backend are you using?
    1. MySQL
    2. Postgres
    3. Redshift
    4. Snowflake
    5. BigQuery
    6. other - Do you have a working SQLAlchemy connection string?
: 6
Please install the optional dependency 'black' to enable linting. Returning input with no changes.
Because you requested to create a new Datasource, we'll open a notebook for you now to complete it!

[I 09:03:21.032 NotebookApp] Serving notebooks from local directory: C:\Users\XXXXX\ge_webinar_demo\great_expectations\uncommitted
[I 09:03:21.032 NotebookApp] Jupyter Notebook 6.4.12 is running at:
[I 09:03:21.032 NotebookApp] http://localhost:8888/?token=3d0ce50cd609a7f1d93fb78bab10be950d55bbc6cba8a2d3
[I 09:03:21.032 NotebookApp]  or http://127.0.0.1:8888/?token=3d0ce50cd609a7f1d93fb78bab10be950d55bbc6cba8a2d3
[I 09:03:21.032 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:03:21.116 NotebookApp] 

    To access the notebook, open this file in a browser:
        file:///C:/Users/XXXXXX/AppData/Roaming/jupyter/runtime/nbserver-2524-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=3d0ce50cd609a7f1d93fb78bab10be950d55bbc6cba8a2d3
     or http://127.0.0.1:8888/?token=3d0ce50cd609a7f1d93fb78bab10be950d55bbc6cba8a2d3
[W 09:03:25.167 NotebookApp] Notebook datasource_new.ipynb is not trusted
[W 09:03:25.183 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20220623090320 (::1) 58.110000ms referer=http://localhost:8888/notebooks/datasource_new.ipynb
[I 09:03:25.948 NotebookApp] Kernel started: 476dbd7a-507e-4acf-bec2-3d0ebd6f4289, name: python3
[I 09:05:25.460 NotebookApp] Saving file at /datasource_new.ipynb

**Expected behavior**
Should be able to create new datasource using Windows ODBC User DSN connection.

**Environment (please complete the following information):**
 - Operating System: Windows 10 Enterprise
 - Great Expectations Version: 0.15.11

**Comment by tchung555** [comment]
Screenshot where process is stuck and not moving on to next step.
![image](https://user-images.githubusercontent.com/108089010/175365257-af52316e-dae4-4ab1-b71f-0b2c02ed4756.png)

**Comment by AFineDayFor** [comment]
Howdy @tchung555 :wave: thank you for raising this with us :bow:

We'll bring it up with the team 😄

**Comment by tchung555** [comment]
Actually, I was able to continue and setup via Jupyter notebook but not able to connect to my Amazon Redshift ODBC DSN that I created.  Looks like the SQLAlchemy default code is trying to run the "SQL: SELECT schema_name()" for the test but I believe this is not a valid SQL query for Amazon Redshift.  Below is the log when I ran context.test_yaml_config(yaml_config=example_yaml):

Attempting to instantiate class from config...
	Instantiating as a Datasource, since class_name is Datasource
---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
File ~\.myvenv\lib\site-packages\sqlalchemy\engine\base.py:1819, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1818     if not evt_handled:
-> 1819         self.dialect.do_execute(
   1820             cursor, statement, parameters, context
   1821         )
   1823 if self._has_events or self.engine._has_events:

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\default.py:732, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    731 def do_execute(self, cursor, statement, parameters, context=None):
--> 732     cursor.execute(statement, parameters)

ProgrammingError: ('25P02', '[25P02] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 25P02] ERROR:  current transaction is aborted, commands ignored until end of transaction block\n (30) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

ProgrammingError                          Traceback (most recent call last)
File ~\.myvenv\lib\site-packages\great_expectations\datasource\new_datasource.py:54, in BaseDatasource.__init__(self, name, execution_engine, data_context_root_directory, concurrency)
     53 try:
---> 54     self._execution_engine = instantiate_class_from_config(
     55         config=execution_engine,
     56         runtime_environment={"concurrency": concurrency},
     57         config_defaults={"module_name": "great_expectations.execution_engine"},
     58     )
     59     self._datasource_config = {
     60         "execution_engine": execution_engine,
     61     }

File ~\.myvenv\lib\site-packages\great_expectations\data_context\util.py:117, in instantiate_class_from_config(config, runtime_environment, config_defaults)
    116 try:
--> 117     class_instance = class_(**config_with_defaults)
    118 except TypeError as e:

File ~\.myvenv\lib\site-packages\great_expectations\execution_engine\sqlalchemy_execution_engine.py:350, in SqlAlchemyExecutionEngine.__init__(self, name, credentials, data_context, engine, connection_string, url, batch_data_dict, create_temp_table, concurrency, **kwargs)
    349 # sqlite/mssql temp tables only persist within a connection so override the engine
--> 350 self.engine = self.engine.connect()
    351 if self._engine_backup.dialect.name.lower() == "sqlite" and not isinstance(
    352     self._engine_backup, sa.engine.base.Connection
    353 ):

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\base.py:3234, in Engine.connect(self, close_with_result)
   3220 """Return a new :class:`_engine.Connection` object.
   3221 
   3222 The :class:`_engine.Connection` object is a facade that uses a DBAPI
   (...)
   3231 
   3232 """
-> 3234 return self._connection_cls(self, close_with_result=close_with_result)

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\base.py:96, in Connection.__init__(self, engine, connection, close_with_result, _branch_from, _execution_options, _dispatch, _has_events, _allow_revalidate)
     92 else:
     93     self._dbapi_connection = (
     94         connection
     95         if connection is not None
---> 96         else engine.raw_connection()
     97     )
     99     self._transaction = self._nested_transaction = None

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\base.py:3313, in Engine.raw_connection(self, _connection)
   3292 """Return a "raw" DBAPI connection from the connection pool.
   3293 
   3294 The returned object is a proxied version of the DBAPI
   (...)
   3311 
   3312 """
-> 3313 return self._wrap_pool_connect(self.pool.connect, _connection)

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\base.py:3280, in Engine._wrap_pool_connect(self, fn, connection)
   3279 try:
-> 3280     return fn()
   3281 except dialect.dbapi.Error as e:

File ~\.myvenv\lib\site-packages\sqlalchemy\pool\base.py:310, in Pool.connect(self)
    303 """Return a DBAPI connection from the pool.
    304 
    305 The connection is instrumented such that when its
   (...)
    308 
    309 """
--> 310 return _ConnectionFairy._checkout(self)

File ~\.myvenv\lib\site-packages\sqlalchemy\pool\base.py:868, in _ConnectionFairy._checkout(cls, pool, threadconns, fairy)
    867 if not fairy:
--> 868     fairy = _ConnectionRecord.checkout(pool)
    870     fairy._pool = pool

File ~\.myvenv\lib\site-packages\sqlalchemy\pool\base.py:476, in _ConnectionRecord.checkout(cls, pool)
    474 @classmethod
    475 def checkout(cls, pool):
--> 476     rec = pool._do_get()
    477     try:

File ~\.myvenv\lib\site-packages\sqlalchemy\pool\impl.py:145, in QueuePool._do_get(self)
    144 except:
--> 145     with util.safe_reraise():
    146         self._dec_overflow()

File ~\.myvenv\lib\site-packages\sqlalchemy\util\langhelpers.py:70, in safe_reraise.__exit__(self, type_, value, traceback)
     69     if not self.warn_only:
---> 70         compat.raise_(
     71             exc_value,
     72             with_traceback=exc_tb,
     73         )
     74 else:

File ~\.myvenv\lib\site-packages\sqlalchemy\util\compat.py:208, in raise_(***failed resolving arguments***)
    207 try:
--> 208     raise exception
    209 finally:
    210     # credit to
    211     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    212     # as the __traceback__ object creates a cycle

File ~\.myvenv\lib\site-packages\sqlalchemy\pool\impl.py:143, in QueuePool._do_get(self)
    142 try:
--> 143     return self._create_connection()
    144 except:

File ~\.myvenv\lib\site-packages\sqlalchemy\pool\base.py:256, in Pool._create_connection(self)
    254 """Called by subclasses to create a new ConnectionRecord."""
--> 256 return _ConnectionRecord(self)

File ~\.myvenv\lib\site-packages\sqlalchemy\pool\base.py:371, in _ConnectionRecord.__init__(self, pool, connect)
    370 if connect:
--> 371     self.__connect()
    372 self.finalize_callback = deque()

File ~\.myvenv\lib\site-packages\sqlalchemy\pool\base.py:679, in _ConnectionRecord.__connect(self)
    675 # init of the dialect now takes place within the connect
    676 # event, so ensure a mutex is used on the first run
    677 pool.dispatch.connect.for_modify(
    678     pool.dispatch
--> 679 )._exec_w_sync_on_first_run(self.dbapi_connection, self)

File ~\.myvenv\lib\site-packages\sqlalchemy\event\attr.py:329, in _CompoundListener._exec_w_sync_on_first_run(self, *args, **kw)
    328 try:
--> 329     self(*args, **kw)
    330 except:

File ~\.myvenv\lib\site-packages\sqlalchemy\event\attr.py:343, in _CompoundListener.__call__(self, *args, **kw)
    342 for fn in self.listeners:
--> 343     fn(*args, **kw)

File ~\.myvenv\lib\site-packages\sqlalchemy\util\langhelpers.py:1695, in only_once.<locals>.go(*arg, **kw)
   1694 try:
-> 1695     return once_fn(*arg, **kw)
   1696 except:

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\create.py:686, in create_engine.<locals>.first_connect(dbapi_connection, connection_record)
    685 try:
--> 686     dialect.initialize(c)
    687 finally:
    688     # note that "invalidated" and "closed" are mutually
    689     # exclusive in 1.4 Connection.

File ~\.myvenv\lib\site-packages\sqlalchemy\dialects\mssql\base.py:2854, in MSDialect.initialize(self, connection)
   2853 def initialize(self, connection):
-> 2854     super(MSDialect, self).initialize(connection)
   2855     self._setup_version_attributes()

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\default.py:413, in DefaultDialect.initialize(self, connection)
    412 try:
--> 413     self.default_schema_name = self._get_default_schema_name(
    414         connection
    415     )
    416 except NotImplementedError:

File ~\.myvenv\lib\site-packages\sqlalchemy\dialects\mssql\base.py:2899, in MSDialect._get_default_schema_name(self, connection)
   2898 query = sql.text("SELECT schema_name()")
-> 2899 default_schema_name = connection.scalar(query)
   2900 if default_schema_name is not None:
   2901     # guard against the case where the default_schema_name is being
   2902     # fed back into a table reflection function.

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\base.py:1188, in Connection.scalar(self, object_, *multiparams, **params)
   1182 """Executes and returns the first column of the first row.
   1183 
   1184 The underlying result/cursor is closed after execution.
   1185 
   1186 """
-> 1188 return self.execute(object_, *multiparams, **params).scalar()

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\base.py:1306, in Connection.execute(self, statement, *multiparams, **params)
   1305 else:
-> 1306     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)

File ~\.myvenv\lib\site-packages\sqlalchemy\sql\elements.py:332, in ClauseElement._execute_on_connection(self, connection, multiparams, params, execution_options, _force)
    331 if _force or self.supports_execution:
--> 332     return connection._execute_clauseelement(
    333         self, multiparams, params, execution_options
    334     )
    335 else:

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\base.py:1498, in Connection._execute_clauseelement(self, elem, multiparams, params, execution_options)
   1490 compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
   1491     dialect=dialect,
   1492     compiled_cache=compiled_cache,
   (...)
   1496     linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
   1497 )
-> 1498 ret = self._execute_context(
   1499     dialect,
   1500     dialect.execution_ctx_cls._init_compiled,
   1501     compiled_sql,
   1502     distilled_params,
   1503     execution_options,
   1504     compiled_sql,
   1505     distilled_params,
   1506     elem,
   1507     extracted_params,
   1508     cache_hit=cache_hit,
   1509 )
   1510 if has_events:

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\base.py:1862, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1861 except BaseException as e:
-> 1862     self._handle_dbapi_exception(
   1863         e, statement, parameters, cursor, context
   1864     )
   1866 return result

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\base.py:2043, in Connection._handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   2042 elif should_wrap:
-> 2043     util.raise_(
   2044         sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   2045     )
   2046 else:

File ~\.myvenv\lib\site-packages\sqlalchemy\util\compat.py:208, in raise_(***failed resolving arguments***)
    207 try:
--> 208     raise exception
    209 finally:
    210     # credit to
    211     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    212     # as the __traceback__ object creates a cycle

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\base.py:1819, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1818     if not evt_handled:
-> 1819         self.dialect.do_execute(
   1820             cursor, statement, parameters, context
   1821         )
   1823 if self._has_events or self.engine._has_events:

File ~\.myvenv\lib\site-packages\sqlalchemy\engine\default.py:732, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    731 def do_execute(self, cursor, statement, parameters, context=None):
--> 732     cursor.execute(statement, parameters)

ProgrammingError: (pyodbc.ProgrammingError) ('25P02', '[25P02] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 25P02] ERROR:  current transaction is aborted, commands ignored until end of transaction block\n (30) (SQLExecDirectW)')
[SQL: SELECT schema_name()]
(Background on this error at: https://sqlalche.me/e/14/f405)

During handling of the above exception, another exception occurred:

ExecutionEngineError                      Traceback (most recent call last)
File ~\.myvenv\lib\site-packages\great_expectations\data_context\data_context\base_data_context.py:2053, in BaseDataContext._instantiate_datasource_from_config(self, name, config)
   2050 try:
   2051     datasource: Union[
   2052         LegacyDatasource, BaseDatasource
-> 2053     ] = self._build_datasource_from_config(name=name, config=config)
   2054 except Exception as e:

File ~\.myvenv\lib\site-packages\great_expectations\data_context\data_context\base_data_context.py:2099, in BaseDataContext._build_datasource_from_config(self, name, config)
   2098 module_name = "great_expectations.datasource"
-> 2099 datasource = instantiate_class_from_config(
   2100     config=config,
   2101     runtime_environment={"data_context": self, "concurrency": self.concurrency},
   2102     config_defaults={"module_name": module_name},
   2103 )
   2104 if not datasource:

File ~\.myvenv\lib\site-packages\great_expectations\data_context\util.py:117, in instantiate_class_from_config(config, runtime_environment, config_defaults)
    116 try:
--> 117     class_instance = class_(**config_with_defaults)
    118 except TypeError as e:

File ~\.myvenv\lib\site-packages\great_expectations\datasource\new_datasource.py:419, in Datasource.__init__(self, name, execution_engine, data_connectors, data_context_root_directory, concurrency)
    417 self._name = name
--> 419 super().__init__(
    420     name=name,
    421     execution_engine=execution_engine,
    422     data_context_root_directory=data_context_root_directory,
    423     concurrency=concurrency,
    424 )
    426 if data_connectors is None:

File ~\.myvenv\lib\site-packages\great_expectations\datasource\new_datasource.py:63, in BaseDatasource.__init__(self, name, execution_engine, data_context_root_directory, concurrency)
     62 except Exception as e:
---> 63     raise ge_exceptions.ExecutionEngineError(message=str(e))
     65 self._data_connectors = {}

ExecutionEngineError: (pyodbc.ProgrammingError) ('25P02', '[25P02] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 25P02] ERROR:  current transaction is aborted, commands ignored until end of transaction block\n (30) (SQLExecDirectW)')
[SQL: SELECT schema_name()]
(Background on this error at: https://sqlalche.me/e/14/f405)

During handling of the above exception, another exception occurred:

DatasourceInitializationError             Traceback (most recent call last)
Input In [19], in <cell line: 1>()
----> 1 context.test_yaml_config(yaml_config=example_yaml)

File ~\.myvenv\lib\site-packages\great_expectations\data_context\data_context\base_data_context.py:3684, in BaseDataContext.test_yaml_config(self, yaml_config, name, class_name, runtime_environment, pretty_print, return_mode, shorten_tracebacks)
   3682     traceback.print_exc(limit=1)
   3683 else:
-> 3684     raise e

File ~\.myvenv\lib\site-packages\great_expectations\data_context\data_context\base_data_context.py:3610, in BaseDataContext.test_yaml_config(self, yaml_config, name, class_name, runtime_environment, pretty_print, return_mode, shorten_tracebacks)
   3600     (
   3601         instantiated_class,
   3602         usage_stats_event_payload,
   3603     ) = self._test_instantiation_of_store_from_yaml_config(
   3604         name, class_name, config
   3605     )
   3606 elif class_name in self.TEST_YAML_CONFIG_SUPPORTED_DATASOURCE_TYPES:
   3607     (
   3608         instantiated_class,
   3609         usage_stats_event_payload,
-> 3610     ) = self._test_instantiation_of_datasource_from_yaml_config(
   3611         name, class_name, config
   3612     )
   3613 elif class_name in self.TEST_YAML_CONFIG_SUPPORTED_CHECKPOINT_TYPES:
   3614     (
   3615         instantiated_class,
   3616         usage_stats_event_payload,
   3617     ) = self._test_instantiation_of_checkpoint_from_yaml_config(
   3618         name, class_name, config
   3619     )

File ~\.myvenv\lib\site-packages\great_expectations\data_context\data_context\base_data_context.py:3777, in BaseDataContext._test_instantiation_of_datasource_from_yaml_config(self, name, class_name, config)
   3773 print(f"\tInstantiating as a Datasource, since class_name is {class_name}")
   3774 datasource_name: str = name or config.get("name") or "my_temp_datasource"
   3775 instantiated_class = cast(
   3776     Datasource,
-> 3777     self._instantiate_datasource_from_config_and_update_project_config(
   3778         name=datasource_name,
   3779         config=config,
   3780         initialize=True,
   3781     ),
   3782 )
   3784 anonymizer = Anonymizer(self.data_context_id)
   3786 if class_name == "SimpleSqlalchemyDatasource":
   3787     # Use the raw config here, defaults will be added in the anonymizer

File ~\.myvenv\lib\site-packages\great_expectations\data_context\data_context\base_data_context.py:2031, in BaseDataContext._instantiate_datasource_from_config_and_update_project_config(self, name, config, initialize)
   2028     except ge_exceptions.DatasourceInitializationError as e:
   2029         # Do not keep configuration that could not be instantiated.
   2030         self._datasource_store.delete_by_name(datasource_name=name)
-> 2031         raise e
   2033 return datasource

File ~\.myvenv\lib\site-packages\great_expectations\data_context\data_context\base_data_context.py:2024, in BaseDataContext._instantiate_datasource_from_config_and_update_project_config(self, name, config, initialize)
   2022 if initialize:
   2023     try:
-> 2024         datasource = self._instantiate_datasource_from_config(
   2025             name=name, config=substituted_config
   2026         )
   2027         self._cached_datasources[name] = datasource
   2028     except ge_exceptions.DatasourceInitializationError as e:
   2029         # Do not keep configuration that could not be instantiated.

File ~\.myvenv\lib\site-packages\great_expectations\data_context\data_context\base_data_context.py:2055, in BaseDataContext._instantiate_datasource_from_config(self, name, config)
   2051     datasource: Union[
   2052         LegacyDatasource, BaseDatasource
   2053     ] = self._build_datasource_from_config(name=name, config=config)
   2054 except Exception as e:
-> 2055     raise ge_exceptions.DatasourceInitializationError(
   2056         datasource_name=name, message=str(e)
   2057     )
   2058 return datasource

DatasourceInitializationError: Cannot initialize datasource my_redshift_dsn, error: (pyodbc.ProgrammingError) ('25P02', '[25P02] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 25P02] ERROR:  current transaction is aborted, commands ignored until end of transaction block\n (30) (SQLExecDirectW)')
[SQL: SELECT schema_name()]
(Background on this error at: https://sqlalche.me/e/14/f405)

**Comment by tchung555** [comment]
Basically I would like to connect using the Redshift User DSN created.
![image](https://user-images.githubusercontent.com/108089010/175471003-fb35a94e-e5a0-4863-9c3f-3df251a8e79a.png)

**Comment by tchung555** [comment]
I was able to connect using pyodbc and panda though:
![image](https://user-images.githubusercontent.com/108089010/175478017-0c1a9568-573e-46a5-80ee-49a2f3bd7fb7.png)

**Comment by rdodev** [comment]
Feature request has been noted and Product Management will decide on priority. Thanks.
