### ISSUE TITLE
Docs for "compile to docs"

### ISSUE THREAD

**Issue by RoyalTS** [fivetran/great_expectations#538]
This feature still seems largely undocumented or am I just looking in the wrong place?

**Comment by jcampbell** [comment]
We're still actively evolving both this feature and its docs, so you're correct. Later today, we will push a 0.7.1 release with additional bug fixes and documentation around compile to docs, but we also expect the feature to continue to evolve rapidly over the coming weeks and months.

That also means it's a really good time for feedback on what you'd like to see (in terms of data elements, etc.) in the feature, or other elements of documentation that need to be drafted.

**Comment by eugmandel** [comment]
@RoyalTS Here is a guide to this feature: https://great-expectations.readthedocs.io/en/latest/guides/data_documentation.html

Feedback on its clarity and readability is very much appreciated!
