### ISSUE TITLE
UserConfigurableProfiler - Memory Usage exceeds 8GB for large datasets

### ISSUE THREAD

**Issue by KentonParton** [fivetran/great_expectations#5389]
**Describe the bug**
While running the UserConfigurableProfiler, we regularly experienced OOM exceptions, killing our pods. 

We have replicated the issue locally in a docker container against the Snowflakes TPCH sample data. Starting with tpch_sf1.lineitem, the memory usage reached 1.6GB, tpch_sf10.lineitem memory usage reached 4GB and did not complete.

As the dataset increases, tpch_sf10.lineitem, tpch_sf100.lineitem, tpch_sf1000.lineitem the memory consumed increases.

When running the UserConfigurableProfiler, are large result sets serialized by GE during profiling or are they just single line stats? If the latter, what would be causing the high memory usage?

**To Reproduce**
1. Create a free trial Snowflake account.
2. git clone git@github.com:KentonParton/fast_api_ge_profiler.git
3. Update snowflake connection string on line 54 of ./app/main.py
4. Run the command "make", this will build the image and bring up the container
5. Open localhost:8003/docs
6. Under /root include a data_asset_name of tpch_sf1.lineitem or tpch_sf10.lineitem
7. Click "Execute"
8. While it's running, open a terminal and run "docker stats". Here you will be able to see the memory.
 

**Expected behavior**
I expected the compute and memory intensive tasks to be carried out on the DB engine, not our servers. I expected the memory usage to stay somewhat constant as the dataset size increased.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.15.0

P.S. When setting "create_temp_table" to True on line 32 an exception is thrown.

**Comment by AFineDayFor** [comment]
Howdy @KentonParton :wave: thanks for raising this with us :bow:

We'll raise it with the team :microscope:

That said, the article for [splitting and sampling tables](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_tables_in_sql) may help you get this over the line :cherry_blossom:

**Comment by KentonParton** [comment]
Hi @AFineDayFor, thanks for the suggestion. We do use splitting and sampling in some cases but doesn't seem necessary for profiling.

As mentioned, I would expect all compute and memory intensive tasks to be carried out on the query engine.

When can I expect a response from a dev? Thanks for your time.

**Comment by KentonParton** [comment]
Hi @AFineDayFor, would it be possible to get some dev eyes on this? Thanks!

**Comment by KentonParton** [comment]
Apologies for the shoulder tap @talagluck.

When using the UserConfigurableProfiler, are large result sets serialized by GE during profiling or are they just single line stats? Trying to figure out how to profile entire datasets without sampling if at all possible.

**Comment by talagluck** [comment]
Hi @KentonParton - thanks for the ping, and apologies for the delay in reply. In the case of SQL, large datasets should not be serialized at all, since compute is all sent back to the database. The only case where I might expect some amount of memory leak would be for pandas. 

How large is your dataset? I wonder if we might be running into constraints with getting our unique value expectations, since those will be expensive operations by definition. It is possible that we are not doing things efficiently with one of these Expectations, or with the UserConfigurableProfiler. 

I believe we will be doing some internal work on performance optimization over the next few weeks, and I will make sure that someone takes a look at this. In the meantime, I am curious whether you hit the same issues when using the [Onboarding Data Assistant](https://docs.greatexpectations.io/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant/).

**Comment by KentonParton** [comment]
Thanks for the response @talagluck.

Regarding dataset sizes.

| Snowflake Table  | Size | Row Count | Memory Utilization |
| ------------- | ------------- | ------------- | ------------- |
| snowflake_sample_data.tpch_sf1.lineitem  | 157.6 MB  | 6,001,215 | 1.6GB |
| snowflake_sample_data.tpch_sf10.lineitem  | 1.6 GB  | 59,986,052 | 4GB and container crashed |

_Note: Memory Utilization is the amount of memory used by docker container while UserConfigurableProfiler is being executed._

I don't believe "getting our unique value expectations" is the only causer because in the [reproducible example](https://github.com/KentonParton/fast_api_ge_profiler/blob/422ae7a815562339c2249130d41b856b07c740fd/app/main.py#L42), `UserConfigurableProfiler` is configured with `value_set_threshold="few",`. That being said, I did change `value_set_threshold` from the default `many` to `few` because I experienced errors with larger datasets.

I will give the Data Assistant a try and report back. Thanks again.

**Comment by talagluck** [comment]
Thanks for the follow-up, @KentonParton - this is useful to know. 

For reference, the `value_set_threshold` is used to determine for which columns it should run an ExpectColumnValuesToBeInSet Expectation. Otherwise, the UserConfigurableProfiler uses two unique value Expectations to determine column cardinality (this is what is tested against the `value_set_threshold`), and then adds those Expectations as well, assuming they are not excluded. Again, there are likely some inefficiencies with the profiler, and we will also look into whether there might also be inefficiencies with our unique value Expectations/Metrics on snowflake.

**Comment by KentonParton** [comment]
@talagluck I've got good news and bad news. The bad new is that the DataAssistant runs into the same high memory usage. It was going along very well but suddenly spiked. The good news is that I've identified some of the queries that are causing the spike in memory usage. They appear to be the same for Data Assistant and UserConfigurableProfiler.

Below you will see that queries, 1, 3, and 4 all return large result sets. `Query 1 --> 34.4 M rows`, `query 3 --> 1.4 M`, and `query 4 --> 100 K`.

<img width="2530" alt="Screenshot 2022-08-25 at 00 12 28" src="https://user-images.githubusercontent.com/20202312/186540653-490555e2-d157-4b82-9746-2f4c0cbf0830.png">

These are the respective queries:

** Query 1
```sql
SELECT l_comment AS value, count(l_comment) AS count 
FROM (SELECT * 
FROM tpch_sf10.lineitem 
WHERE true) AS great_expectations_sub_selection 
WHERE l_comment IS NOT NULL GROUP BY l_comment ORDER BY l_comment
```

** Query 3
```sql
SELECT l_extendedprice AS value, count(l_extendedprice) AS count 
FROM (SELECT * 
FROM tpch_sf10.lineitem 
WHERE true) AS great_expectations_sub_selection 
WHERE l_extendedprice IS NOT NULL GROUP BY l_extendedprice ORDER BY l_extendedprice
```

** Query 4
```sql
SELECT l_suppkey AS value, count(l_suppkey) AS count 
FROM (SELECT * 
FROM tpch_sf10.lineitem 
WHERE true) AS great_expectations_sub_selection 
WHERE l_suppkey IS NOT NULL GROUP BY l_suppkey ORDER BY l_suppkey
```

We can see that all of them are selecting a column in the process of getting the count. 


--------

On a separate note, I'd like to mention that the Data Assistant would error when it encountered a Snowflake DATE column. Below is the error. I ended up excluding the DATE columns.

```bash
'exception_info': {{'exception_traceback': 'Traceback (most recent call last):\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context\n    self.dialect.do_execute(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute\n    cursor.execute(statement, parameters)\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 804, in execute\n    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 276, in errorhandler_wrapper\n    handed_over = Error.hand_to_other_handler(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 331, in hand_to_other_handler\n    cursor.errorhandler(connection, cursor, error_class, error_value)\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 210, in default_errorhandler\n    raise error_class(\nsnowflake.connector.errors.ProgrammingError: 001010 (42846): SQL compilation error:\nincompatible types: [DATE] and [NUMBER(9,0)]\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py", line 424, in _get_column_quantiles_generic_sqlalchemy\n    quantiles_results: Row = sqlalchemy_engine.execute(quantiles_query).fetchone()\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1380, in execute\n    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection\n    return connection._execute_clauseelement(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement\n    ret = self._execute_context(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context\n    self._handle_dbapi_exception(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception\n    util.raise_(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_\n    raise exception\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context\n    self.dialect.do_execute(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute\n    cursor.execute(statement, parameters)\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 804, in execute\n    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 276, in errorhandler_wrapper\n    handed_over = Error.hand_to_other_handler(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 331, in hand_to_other_handler\n    cursor.errorhandler(connection, cursor, error_class, error_value)\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 210, in default_errorhandler\n    raise error_class(\nsqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 001010 (42846): SQL compilation error:\nincompatible types: [DATE] and [NUMBER(9,0)]\n[SQL: SELECT percentile_disc(%(percentile_disc_1)s) WITHIN GROUP (ORDER BY l_shipdate ASC) AS anon_1, percentile_disc(%(percentile_disc_2)s) WITHIN GROUP (ORDER BY l_shipdate ASC) AS anon_2, percentile_disc(%(percentile_disc_3)s) WITHIN GROUP (ORDER BY l_shipdate ASC) AS anon_3, percentile_disc(%(percentile_disc_4)s) WITHIN GROUP (ORDER BY l_shipdate ASC) AS anon_4 \nFROM (SELECT * \nFROM tpch_sf1.lineitem \nWHERE true) AS great_expectations_sub_selection]\n[parameters: {\'percentile_disc_1\': 0.0, \'percentile_disc_2\': 0.25, \'percentile_disc_3\': 0.75, \'percentile_disc_4\': 1.0}]\n(Background on this error at: https://sqlalche.me/e/14/f405)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/great_expectations/execution_engine/execution_engine.py", line 393, in resolve_metrics\n    resolved_metrics[metric_to_resolve.id] = metric_fn(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/great_expectations/expectations/metrics/metric_provider.py", line 34, in inner_func\n    return metric_fn(*args, **kwargs)\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py", line 143, in _sqlalchemy\n    return _get_column_quantiles_generic_sqlalchemy(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py", line 456, in _get_column_quantiles_generic_sqlalchemy\n    raise ValueError(\nValueError: The SQL engine dialect "<snowflake.sqlalchemy.snowdialect.SnowflakeDialect object at 0x16b937a00>" does not support computing quantiles with approximation error; set allow_relative_error to False to disable approximate quantiles.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/great_expectations/validator/validator.py", line 1296, in resolve_validation_graph\n    self._resolve_metrics(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/great_expectations/validator/validator.py", line 2217, in _resolve_metrics\n    return execution_engine.resolve_metrics(\n  File "/Users/me/code/fast_api_ge_profiler/.venv/lib/python3.9/site-packages/great_expectations/execution_engine/execution_engine.py", line 397, in resolve_metrics\n    raise ge_exceptions.MetricResolutionError(\ngreat_expectations.exceptions.exceptions.MetricResolutionError: The SQL engine dialect "<snowflake.sqlalchemy.snowdialect.SnowflakeDialect object at 0x16b937a00>" does not support computing quantiles with approximation error; set allow_relative_error to False to disable approximate quantiles.\n', 'exception_message': 'The SQL engine dialect "<snowflake.sqlalchemy.snowdialect.SnowflakeDialect object at 0x16b937a00>" does not support computing quantiles with approximation error; set allow_relative_error to False to disable approximate quantiles.', 'raised_exception': True}}}}
```

**Comment by talagluck** [comment]
Thanks for this, Kenton. I'll forward to the engineers who are looking into performance now.

Regarding the DATA columns, are you on the latest version of Great Expectations? This was a known bug, but I believe it has been fixed in one of the last couple of releases.

**Comment by KentonParton** [comment]
@talagluck yes I am using version `0.15.19`. I have pushed changes to the repo mentioned above https://github.com/KentonParton/fast_api_ge_profiler

They include the latest version of GE and the data assistant.

**Comment by talagluck** [comment]
Thanks for the confirmation, @KentonParton - I've confirmed that this is a bug which is currently being fixed.

**Comment by KentonParton** [comment]
@talagluck Was this addressed in 0.15.21 release by any chance?

**Comment by talagluck** [comment]
Hi @KentonParton - yes, I believe the update came in #5862. Is this working for you now?

**Comment by KentonParton** [comment]
Hi @talagluck , yes! Looks like it has been addressed for the `DataAssistant` and `UserConfigurableProfiler`. Thank you

**Comment by talagluck** [comment]
Thanks for the follow-up, @KentonParton! To confirm, you are no longer seeing the memory issue in the UserConfigurableProfiler?

**Comment by KentonParton** [comment]
Correct. It appears that the changes addressed both the UserConfigurableProfiler and DataAssistant.

The Snowflake Date issue with the DataAssistant has also been resolved.
