### ISSUE TITLE
Deprecation warning in Notebook during initialization of a new Expectation Suite by profiling a data batch

### ISSUE THREAD

**Issue by riwim** [fivetran/great_expectations#5420]
**Describe the bug**
Within the notebook provided for initializing a new Expectations Suite by profiling by the CLI tool, I get the following warning 

_/Users/user/ge/.venv/lib/python3.9/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py:133: DeprecationWarning: Specifying batch_identifiers as part of the RuntimeDataConnector config is deprecated as of v0.15.1 and will be removed by v0.18. Please configure batch_identifiers as part of Assets instead._

The warning occurs after this line has been executed within the first cell:

```python
context = ge.data_context.DataContext()
```

I did not change the content of this cell and therefore executed it exactly as it was generated by the CLI tool `great_expectations suite new`.

**To Reproduce**

1. Same steps as those to reproduce #5409, plus
2. `great_expectations suite new`
3. Choose _3. Automatically, using a profiler_
4. Choose a datasource and asset to profile
5. Choose a name for the suite and agree to open the notebook
6. Execute

    ```python
    import datetime

    import pandas as pd

    import great_expectations as ge
    import great_expectations.jupyter_ux
    from great_expectations.profile.user_configurable_profiler import (
        UserConfigurableProfiler,
    )
    from great_expectations.core.batch import BatchRequest
    from great_expectations.checkpoint import SimpleCheckpoint
    from great_expectations.exceptions import DataContextError
    ```

    Response:
    `2022-06-30T23:45:21+0200 - INFO - Great Expectations logging enabled at 20 level by JupyterUX module.`
9. Execute

    ```python
    context = ge.data_context.DataContext()
    ```

    Response: The deprecation warning shown in the bug description above.

**Expected behavior**
No deprecation warning by code of the current and unmodified codebase.

**Environment**
 - Operating System: MacOS 12.3.1
 - Great Expectations Version: 0.15.11

**Comment by talagluck** [comment]
Hi @riwim - thanks for raising this. We will review and be in touch.

**Comment by kyleaton** [comment]
Hi @riwim! This has been fixed. Thanks for raising this and if the problem persists, please feel free to reopen this issue.
