### ISSUE TITLE
Allow pytest test suite run for only the data sources available

### ISSUE THREAD

**Issue by RoyalTS** [fivetran/great_expectations#543]
`pyspark`, for example, is quite a heavy dependency if all I need it for is to be able to run the test suite successfully. One could, e.g., move the dataset specific imports in test_utils.py into the respective conditional blocks and skip individual tests using the [pytest mechanism](https://docs.pytest.org/en/latest/skipping.html#skipping-on-a-missing-import-dependency) for that sort of thing.

**Comment by jcampbell** [comment]
👍 We have too much difficulty onboarding new devs because of a complicated testing setup.

For the record, I'd eventually like to use command-line flags to control the environment, but I think using the same approach as mysql and postgres for now makes sense as I see you did in the PR.

**Comment by RoyalTS** [comment]
Perhaps the cleanest way is to simply check that contexts are available and skip/xfail for those that aren't. Pytest makes that kind of thing pretty easy.

Feel free to pull in my PR anytime though if you'd like to leave a more general solution to this for later.

**Comment by jcampbell** [comment]
Thanks; I'm going to merge your PR, and have added to my internal backlog looking into a better way to selectively and clearly enable/disable relevant subsets of the test suite.
