### ISSUE TITLE
MicrosoftTeamsNotificationAction wrong data_docs_pages URL when hosting in Azure Blob Storage

### ISSUE THREAD

**Issue by adrixp** [fivetran/great_expectations#5432]
**Describe the bug**
When a Teams notifications arrives, I tried to click on the 'Open data docs' button. But the URL is not correct since it send you to a Not Found resource. 

Generated URL: hostname.**blob**.core.windows.net/**$web**/validations/...
ExpectedURL   : hostname.**z6.web**.core.windows.net/validations/...

It is redirecting to the blob container instead of the Azure static website.

The notification and the data docs upload to Azure works nicely. 
Could it be a misconfiguration on my side?

#Azure Blob configuration:

```
data_docs_sites={
        "az_site": {
            "class_name": "SiteBuilder",
            "store_backend": {
                "class_name": "TupleAzureBlobStoreBackend",
                "container":  "\$web",
                "connection_string": data['AZURE_STORAGE_CONNECTION_STRING'],
            },
            "site_index_builder": {
                "class_name": "DefaultSiteIndexBuilder"
            },
        }
    }
```

#Microsoft Teams configuration:

```
renderer = {
    "module_name": "great_expectations.render.renderer.microsoft_teams_renderer",
    "class_name": "MicrosoftTeamsRenderer",
}

notify_on = "failure"

teams_action = {
    "class_name": "MicrosoftTeamsNotificationAction",
    "renderer": renderer,
    "microsoft_teams_webhook": data['TEAMS_WEBHOOK'],
    "notify_on": notify_on,
}
```

**To Reproduce**
1. Go to Microsoft Teams notification
2. Click on 'Open data docs'
3. The URL is not right

**Expected behavior**

Generated URL: hostname.**blob**.core.windows.net/**$web**/validations/...
ExpectedURL   : hostname.**z6.web**.core.windows.net/validations/...

**Environment (please complete the following information):**
 - Operating System: Databricks
 - Great Expectations Version: 0.15.12

**Additional context**
Followed this tutorial for [hosting static docs in azure](https://docs.greatexpectations.io/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_azure_blob_storage/)

**Comment by adrixp** [comment]
Also happen with EmailAction, maybe this would happen with all Actions.

Thanks,
Adrian

**Comment by adrixp** [comment]
Hi, 
Doing some research, Azure has 2 endpoints:
- Blob service: https://mystorageaccount.blob.core.windows.net/  ->Deploy files
- Static Website: https://mystorageaccount.z5.web.core.windows.net/   -> static website
[More info](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-custom-domain-name?tabs=azure-portal)

So I think that these Actions are using the same URL for deploying the data docs and for consulting the docs.
Would it be possible to add an extra parameter to MicrosoftTeamsNotificationAction?
Something like notify_url, and the result could be:
https://<notify_url>/validations/...

Thanks in advance,
Regards,
Adrian

**Comment by talagluck** [comment]
Hi @adrixp - thanks for raising this, and doing some digging! The solution you are proposing makes a lot of sense. Is this something you would have some interest in contributing? We are happy to offer guidance and support to help you get this across the line.

**Comment by adrixp** [comment]
Hi @talagluck, sure I would like to contribute. Could you provide me some docs in order to proceed? Thanks

**Comment by eavanvalkenburg** [comment]
I encountered this as well, static website in blob are indeed made available on a zXX.web address instead of the blob.core, and if the container is set to private then the blob.core address is unavailable, obviously the writing that the package does indeed goes to blob.core in the $web container, but the front end is different, I made a small function that does a rewrite before giving back the address, but hopefully that kind of logic can be included in the integration!

**Comment by HaebichanGX** [comment]
closed, as it's from a over a year ago with deprecated GX versions and Windows which we don't support
