### ISSUE TITLE
snowflake integer is being detected as a decimal.

### ISSUE THREAD

**Issue by Andrew-Pham99** [fivetran/great_expectations#5444]
**Describe the bug**
The expectation "Value Types Must Belong in This set" will detect the observed value of the column to be a decimal.

**To Reproduce**
1. Create "expect_column_values_to_be_in_type_list" expectation
2. Have integer in type list
3. Run validation on snowflake table
4. See error, snowflake detects the column to be decimal, even though column is an integer type

**Expected behavior**
The table should pass validation

**Environment (please complete the following information):**
 - Operating System: Ubuntu 
 - Great Expectations Version:  0.15.3

**Additional context**
Most likely has to do with snowflake storing numeric data types (both integers and decimals)  as NUMBER(precision, scale)

**Comment by talagluck** [comment]
Hi @Andrew-Pham99 - thank you for raising this. We will review and be in touch.

**Comment by rdodev** [comment]
Hey @Andrew-Pham99 sorry for hiatus in communication. Is this still an issue with latest GX version?

**Comment by Andrew-Pham99** [comment]
Looks Like the Issue Is still there, looking at the documentation it seems
that the expectation to detect data type for snowflake is unsupported
currently

**Comment by rdodev** [comment]
@Andrew-Pham99 thanks for that. I will mark this as an optimization request and bring awareness to product management.
