### ISSUE TITLE
nan semantics

### ISSUE THREAD

**Issue by RoyalTS** [fivetran/great_expectations#546]
Just stumbled on this: The way various pandas expectations are currently written will convert `np.nan` to `'nan'` instead of retaining missings (see e.g. [here](https://github.com/great-expectations/great_expectations/blob/5ce4d499da2301d0c0497b243813a349837e95d7/great_expectations/dataset/pandas_dataset.py#L723)). I believe that's what the code that was originally there did as well but it strikes me as anywhere between wrong and dangerous. Changing from `astype(str)` to `astype(object)` everywhere would solve this but would change current behavior substantially so I wanted to be sure you agreed with that change before I send a PR.

**Comment by abegong** [comment]
Hm. That's definitely worth a look.

@jcampbell did a deep dive into cross-platform NaN behavior recently, so he's definitely in the best position to evaluate, but he's on the road this week. Can you hold the though for another 5 days?

**Comment by RoyalTS** [comment]
> Can you hold the though for another 5 days?

Maybe even 6 :)

**Comment by abegong** [comment]
I was zero-indexing. ;)

**Comment by jcampbell** [comment]
This is a really important issue, and I think we need a deeper way of addressing it inside GE; we have to contend with the fact that for our expectation suites, we can use only a single special missing value (json `none`), whereas different backends (pandas especially) have multiple possible none values, and ideally we'd like to fold user-defined missing in as well.

I'd like to pin this as an internal issue that we need to address and take some time to fully review fix options--so far, I've just gotten to a pretty good understanding of where it'll affect us.

I'm just sneaking a look at the computer from vacation, and will mark this for when I get back, like @abegong mentioned.

**Comment by RoyalTS** [comment]
I don't think this is about different missing values – though that, too, is
an important issue (my 2 cents: for pandas GE should simply defer to
.isnull() to determine missingness).

This issue is about GE making missings non-missing in certain expectations,
which is almost surely wrong.
