### ISSUE TITLE
How to specify evaluation parameters for ExpectationConfiguration

### ISSUE THREAD

**Issue by femibyte** [fivetran/great_expectations#5492]
**Describe the bug**

I am trying to find out how to specify an evaluation parameter when I create an ExpectationConfiguration object.

**To Reproduce**

I have followed instructions as to how to create expectations using ExpectationConfiguration:

https://great-expectations.readthedocs.io/en/latest/guides/how_to_guides/creating_and_editing_expectations/how_to_create_a_new_expectation_suite_without_a_sample_batch.html

I define the ExpectationConfiguration as follows:

  ```
   expectation_configuration_2 = ExpectationConfiguration(
             expectation_type="expect_column_distinct_values_to_be_in_set",
         kwargs = {
            "column" : "gameid",
            "value_set" : {"$PARAMETER" : "runtime_values"}
            },
         meta={
          "notes": {
          "format": "markdown",
          "content": "Ensures that certain values of gameid are included. **Markdown** `Supported`"
           }
       }
    )
    suite.add_expectation(expectation_configuration=expectation_configuration_2)
```
but I get this error:

```great_expectations.exceptions.exceptions.EvaluationParameterError: No value found for $PARAMETER runtime_values```

**Expected behavior**
It should allow me to specify runtime_values as list while running a checkpoint.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.15.3

**Additional context**

**Comment by rdodev** [comment]
Hey @femibyte I believe you're looking at documentation for older/deprecated versions of great expectations. The relevant documentation can now be found [here](https://docs.greatexpectations.io/docs/guides/expectations/how_to_create_and_edit_expectations_based_on_domain_knowledge_without_inspecting_data_directly), please note there are some subtle but important differences in the config.

**Comment by femibyte** [comment]
> Hey @femibyte I believe you're looking at documentation for older/deprecated versions of great expectations. The relevant documentation can now be found [here]

Thanks @rdodev - however my question still stands. These docs don't sure how to specify evaluation parameters for ExpectationConfiguration.

**Comment by rdodev** [comment]
> 

@femibyte Pass in `kwargs` for example:

`evaluation_parameters={"upstream_row_count": upstream_row_count}`

**Comment by femibyte** [comment]
This is what I used 

```
  expectation_configuration_2 = ExpectationConfiguration(
             runtime_values = [12000001],
             evaluation_parameters = { 
                                       "runtime_values": runtime_values},
          
             expectation_type="expect_column_distinct_values_to_be_in_set",
            kwargs = {
            "column" : "gameid",
            "value_set" : {"$PARAMETER" : "runtime_values"}
            }
    )
```

I now get this error:

```
  File "postgres_validation.py", line 283, in <module>
    main()
  File "postgres_validation.py", line 277, in main
    pdc.create_expectations()
  File "postgres_validation.py", line 155, in create_expectations
    expectation_configuration_2 = ExpectationConfiguration(
TypeError: __init__() got an unexpected keyword argument 'runtime_values'
```

**Comment by rdodev** [comment]
@femibyte please try to place inside `kwargs` dictionary, seems you added it in the function call.

**Comment by femibyte** [comment]
@rdodev so what do I put for value_set then ?

     "value_set" : {"$PARAMETER" : "runtime_values"}

still produces this error

```great_expectations.exceptions.exceptions.EvaluationParameterError: No value found for $PARAMETER runtime_values```

**Comment by femibyte** [comment]
This is the code I currently have:

           expectation_configuration_2 = ExpectationConfiguration(
             expectation_type="expect_column_distinct_values_to_be_in_set",
              kwargs = {
              "evaluation_parameters" : { 
                                       "runtime_values": runtime_values},
            "column" : "gameid",
            "value_set" : {"$PARAMETER" : "runtime_values"}
            },
        )

**Comment by rdodev** [comment]
@femibyte please check out the docs as to when to use which: https://docs.greatexpectations.io/docs/reference/evaluation_parameters

**Comment by femibyte** [comment]
@rdodev - thx, this code now works and I can save the expectation:

           ```expectation_configuration_2 = ExpectationConfiguration(
             expectation_type="expect_column_distinct_values_to_be_in_set",
             kwargs = {
              "evaluation_parameters" : { 
                                       "runtime_values": runtime_values},
                                       "column" : "gameid",
            },
           )
          # Add the Expectation to the suite
         suite.add_expectation(expectation_configuration=expectation_configuration_2)```

How do I pass the evaluation parameters at run time if say I run a checkpoint  on the command line ?
Something like ?

`great_expectations checkpoint run my_checkpoint runtime_values=`

**Comment by rdodev** [comment]
> How do I pass the evaluation parameters at run time if say I run a checkpoint on the command line ?
> Something like ?

That's presently not possible through the CLI. Unfortunately.

**Comment by femibyte** [comment]
Ok, so how do I specify evaluation parameters to a checkpoint run in Python ? @rdodev

**Comment by rdodev** [comment]
> Ok, so how do I specify evaluation parameters to a checkpoint run in Python ? @rdodev

As shown in the link aI shared above re: evaluation parameters.

**Comment by rdodev** [comment]
Closing this as original question was answered. If you have more questions about specific usage, please reach out via Slack.
