### ISSUE TITLE
publishing data statistics when profiling data

### ISSUE THREAD

**Issue by shakti-garg** [fivetran/great_expectations#5513]
**Is your feature request related to a problem? Please describe.**
When profiling data using any of the provided profilers, I am only getting the validation suite for the selected columns in the dataset. It should also publish the statistics of the data like distribution of values, min, max, number of null values, etc.

**Describe the solution you'd like**
profile method should also persist the data statistics.

**Comment by rdodev** [comment]
Hi @shakti-garg 👋 

I'm not sure I follow. Upon profiling, datadocs will show expectations for min/max/null etc. Are you not seeing those?

**Comment by shakti-garg** [comment]
Hey @rdodev 

Thanks for the prompt response. 

Upon profiling, I am getting expectations like ``` mean must be greater than or equal to 1.5716 and less than or equal to 1.5716.```
What I am looking for is plain metrics like ``` mean: 1.5716```. 

I think your point is that metrics are embedded in expectations only but for my business flow, I want to have metrics and expectations separately. 
Why do I need metrics separately? because it will help the analysts with basic EDA(exploratory data analysis).

Please feel free to share your thoughts on this use case? If you align, then is it possible to publish data metrics along with the expectations.

**Comment by rdodev** [comment]
@shakti-garg thanks for explaining your use case. I will consult with the team and reach back out.

**Comment by shakti-garg** [comment]
@rdodev Did you get to consult with the team? Is there any ETA by when i can get some feedback on this problem.

In case this scenario makes sense, I am happy to contribute the fix though will need some help from you and your team in understanding code.

**Comment by rdodev** [comment]
@shakti-garg 👋 

Apologies for delay. Thanks for the use case explanation. I will re-raise this with my team and let you know.

**Comment by rdodev** [comment]
@shakti-garg after consulting with the team, this use case isn't supported at the moment and not trivial to fix. However, we're working on a feature that will enable this use case of EDA, but that's 3-6 months out. For now, we have an experimental feature that could at the very least make it easy to extract the metrics from the validation result. You can find the documentation [here](https://docs.greatexpectations.io/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant/). I'd like to emphasize that it's in experimental state, so I would expect running onto rough edges as you try it.

**Comment by shakti-garg** [comment]
@rdodev Thanks for the update. Happy to know that this feature is already in your plans. 

I have a look at the documentation you shared for the related experimental feature. Are you talking about `context.assistants.onboarding`? If yes, i am not able to grasp how the metrics can be extracted from its output. Can you point me to that code snippet.

**Comment by rdodev** [comment]
Hey @shakti-garg apologies. Yes, I meant to say on-boarding assistants help with exploratory data analysis, not the output as such. As for the desired metric in datadoc use case, we currently have no support for that use case, our engine tries to give reasonable suggestions, but it's ultimately up to the data engineer to decide which metric and expectations they need and want to use.
