### ISSUE TITLE
Management UI for GE

### ISSUE THREAD

**Issue by hebrd** [fivetran/great_expectations#5562]
**Is your feature request related to a problem? Please describe.**
Most of operations of GE are executed from CLI, which is not friendly to non-programmer.

**Describe the solution you'd like**
A management system with all kinds of web UI to create expectation, query validation results etc.

**Comment by bluinchiostro** [comment]
Hey @BrandonDotLin it's a great functionality and I think it's going to be implemented in the SaaS version of great_expectation. Let's see...

**Comment by AFineDayFor** [comment]
Howdy @BrandonDotLin 👋 Thanks for reaching out and and being a part of the community 🙇 

I'd go and agree with @bluinchiostro but if this is something you're raising because you're contemplating a contribution, we could only encourage it. We'd review and go from there 🔬

**Comment by austiezr** [comment]
Hey @BrandonDotLin ! Closing this out for now, but if you're interested in learning more about how this functionality is developing in Great Expectations, feel free to come to one of our [weekly cloud workshops](https://greatexpectations.io/cloud)!
