### ISSUE TITLE
Profiling huge volume of data

### ISSUE THREAD

**Issue by shakti-garg** [fivetran/great_expectations#5614]
**Is your feature request related to a problem? Please describe.**
Though profiling with around 200-300 MB of parquet data in S3 using spark is successful, it failed with OOM error when i ran it with ~45 GB of parquet data in S3.
Is it feasible to run profiling on such huge data with this tool? If yes, are there any benchmarks or case studies to reference.

**Comment by AFineDayFor** [comment]
Howdy @shakti-garg 👋 thanks for raising this with us.

In this context, an out of memory errors is a result of OOM tuning on a particular system. The tool can manage it, but the system you're executing it on would need the resources to manage the workload you're asking of it.

The guide ["How to configure a DataConnector for splitting and sampling a file system or blob store"](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_a_file_system_or_blob_store#additional-notes) may help you get this over the line.

I'll go ahead and close this. Ping if you feel that isn't the correct action.
