### ISSUE TITLE
Generating docs for datetimes leads to an unexpected type expectation

### ISSUE THREAD

**Issue by talagluck** [fivetran/great_expectations#562]
When generating docs for datetimes, we wind up getting the result "value types must belong to a set which has not yet been defined".

How can we get more expected expectations for columns with date datatypes?

![Screen Shot 2019-07-31 at 1 57 12 PM](https://user-images.githubusercontent.com/15267635/62235849-cea91100-b39b-11e9-8c67-60349b7f5e39.png)

**Comment by abegong** [comment]
Done.
