### ISSUE TITLE
expect_column_value_z_scores_to_be_less_than work wrongly when the column contain only 0 

### ISSUE THREAD

**Issue by syrineMH** [fivetran/great_expectations#5643]
**Describe the bug**
 i have problem implementing the expect_column_value_z_scores_to_be_less_than . My column has only 0. what i should get is the sucess of the operation but i'am getting the error below 
![bug](https://user-images.githubusercontent.com/75311155/182318846-8099f8e2-6dc8-4829-8d6b-272fc8268cd0.png)

**To Reproduce**

**Expected behavior
the formula is mean\std_dev. Since the mean and column equal to 0. There can not be a division. So what i expect is to prevent the division and get a status success.

**Environment (please complete the following information):**
 - Operating System:  Windows
 - Great Expectations Version: v.0.15.16

**Additional context**

**Comment by austiezr** [comment]
Hey @syrineMH ! Thanks for raising this; we'll review internally and be in touch.

**Comment by tyler-hoffman** [comment]
I was able to reproduce this with great-expectations 0.16.16. This issue appears to not be unique to bigquery. e.g. with pandas dataframes, we get back `success=False` if all values in the column are the same value.

**Comment by r34ctor** [comment]
Hi @syrineMH, unfortunately this is not something we will be able to address. However, if you'd like to contribute, we'd be more than happy to support you.

**Comment by r34ctor** [comment]
We'll close this issue off for now, but please feel free to re-open it!
