### ISSUE TITLE
Extensions for great_expectations 

### ISSUE THREAD

**Issue by bfatema62** [fivetran/great_expectations#570]
Hi,

I wanted to know if there are any extensions for this library that would be needed?

**Comment by abegong** [comment]
@bfatema62 I'm not sure what you're asking here. Can you clarify?

Also, this might be a good question to ask on slack: https://tinyurl.com/great-expectations-slack

**Comment by bfatema62** [comment]
I meant to ask if there are any additional extensions needed to get this
package to work in JupyterLab/Notebook

**Comment by jcampbell** [comment]
All of the direct requirements are installed as dependencies by `pip` or `conda`.

The SqlAlchemy and Spark Dataset backends require additional packages, as listed in optional includes sqlalchemy and pyspark, respectively.
