### ISSUE TITLE
Slack invite link dead

### ISSUE THREAD

**Issue by jeffcsauer** [fivetran/great_expectations#5707]
**Describe the bug**
Invite to `great_expectations` Slack broken URL on both greatexpectations.io as well as github.com/great-expectations/README.md

**To Reproduce**
1. Go to [this link](https://greatexpectationstalk.slack.com/join/shared_invite/zt-1d7ym4xed-tqJS3aJ_jkoUPk_Hp6bCIA#/shared-invite/error)
2. Observe that invite is no longer valid 

**Expected behavior**
Valid invite to great_expectations slack

**Environment (please complete the following information):**
NA

**Additional context**
NA

**Comment by austiezr** [comment]
Hey @jeffcsauer ! Thanks for raising this; we're investigating internally.

**Comment by austiezr** [comment]
Hey @jeffcsauer ! This has been resolved; the noted links should now point to https://greatexpectations.io/slack.
