### ISSUE TITLE
What is the difference between the dependencies listed under requirements and requirements dev?

### ISSUE THREAD

**Issue by bfatema62** [fivetran/great_expectations#571]

**Comment by abegong** [comment]
`requirements.txt` are needed for normal use of the library.

`requirements-dev.txt` includes some additional dependencies for development.

By default, `pip install great_expectations` installs `requirements.txt`, not `requirements-dev.txt`.

Does that answer your question?

**Comment by bfatema62** [comment]
So does that mean I need both the dependents in retirements.txt and
requirements.dev for the package to function ?

Sorry for the stupid question

**Comment by abegong** [comment]
The package should function with just `requirements.txt`.

You only need `requirements-dev.txt` if you're going to be making changes to the Great Expectations package itself.

**Comment by bfatema62** [comment]
Thank you so much !!
