### ISSUE TITLE
Can't access validations using the url generated for GCP with the Slack implementation.

### ISSUE THREAD

**Issue by Gonalb** [fivetran/great_expectations#5720]
I cannot access the validations  in Google Cloud Storage through the link in slack. It says access denied.
For the implementation I followed this guide: [Slack GE](https://docs.greatexpectations.io/docs/guides/validation/validation_actions/how_to_trigger_slack_notifications_as_a_validation_action/) (For webhook)
The implementation worked fine, I received the notification in the specified slack channel. The problem is that the link it generates does not allow me to open the .html.
The problem is my bucket is private and the url generated is for public buckets.

<img width="683" alt="Captura de Pantalla 2022-08-08 a la(s) 19 12 40" src="https://user-images.githubusercontent.com/85250037/183559601-b03f56b7-c02f-48c3-8d5b-bef36ad83626.png">
<img width="931" alt="Captura de Pantalla 2022-08-08 a la(s) 12 00 59" src="https://user-images.githubusercontent.com/85250037/183560085-961646c4-b574-4ddc-add9-fa6bf5536c44.png">

Instead of the url have googleapis which should have cloud.google. I tried it and it works. Basically it is the same as the url you have if you look for it from cloud storage.

https://storage.googleapis.com/path-to-html.
https://storage.cloud.google.com/path-to-html.

**Comment by austiezr** [comment]
Hey @Gonalb ! Thanks for raising this; we'll review internally and be in touch.

**Comment by Gonalb** [comment]
I was discussing with a colleague and the url with googleapis is for public buckets and our bucket is private we need that replaced with cloud.google.

**Comment by AFineDayFor** [comment]
Howdy @Gonalb and @austiezr 👋 thanks both for just all around being cool as cucumbers 🙇 

In the meantime @Gonalb, you can leverage custom renderers per the documentation [here](https://docs.greatexpectations.io/docs/terms/renderer), doing so would allow you to change the urls scheme. This is just a followup of our chat [here](https://greatexpectationstalk.slack.com/messages/CUTCNHN82/p1662665755737969) `^_^`
