### ISSUE TITLE
Deprecation warnings when calling Great Expectations data context (connecting to S3)

### ISSUE THREAD

**Issue by arthurmanners** [fivetran/great_expectations#5724]
**Describe the bug**
I'm getting a deprecation warning when I call data context, specifically when Great Expectations is configured to pulled expectation suites from S3. 

The warning seems to be an [SQLALchemy deprecation warning](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/engine/url.py):
```
venv-validation/lib/python3.9/site-packages/great_expectations/data_context/store/query_store.py:73: SADeprecationWarning: Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the URL.create() method options = URL(drivername, **credentials)
```

**To Reproduce**
1. Configure great_expectations.yml with S3 expectation store
2. Create a data context object: `context = ge.data_context.DataContext()`
3. See error

**Expected behavior**
The data context does not show the warnings when creating a data context connecting to local expectation suites. 

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.15.16

**Comment by austiezr** [comment]
Hey @arthurmanners ! Thanks for raising this; we'll review internally and discuss.
