### ISSUE TITLE
Plugin gallery

### ISSUE THREAD

**Issue by fkromer** [fivetran/great_expectations#5732]
**Is your feature request related to a problem? Please describe.**

It’s not easily to find ge plugins.

**Describe the solution you'd like**

An exploration site similar to the expectation gallery.

**Describe alternatives you've considered**

**Additional context**

**Comment by rdodev** [comment]
Hey @fkromer 👋 

I'm not sure I understand what you're asking for here. Can you please provide an example and more detail? Thanks!
