### ISSUE TITLE
Documentation issue with GCP Secret Manager YAML Examples

### ISSUE THREAD

**Issue by cah-jamey-weyenberg** [fivetran/great_expectations#5755]
There's an issue with the documentation for the GCp Secret Manager documentation. The Jupyter notebooks actually set this up properly, but the documentation on the website has the `credentials:` section in the wrong place, and occasionally uses the wrong class name of SqlAlchemyDatasource when it should be Datasource.

**Comment by cah-jamey-weyenberg** [comment]
I'm currently working on foxing this issue on the website

**Comment by cah-jamey-weyenberg** [comment]
I'm currently working on this fix now.

**Comment by rdodev** [comment]
Hey @cah-jamey-weyenberg 👋 

Thanks for this, please let me know when the PR is ready and I'll let the doc folks know.
