### ISSUE TITLE
SQL Alchemy error when running the Custom Query Expectation example

### ISSUE THREAD

**Issue by itaise** [fivetran/great_expectations#5767]
Hi, 
Background - we would like to develop custom query expectations (that will be ran on trino). 

I am running the example file for creating Custom Query Expectation as it is, and getting an error **on the 2 last** expectations in the examples: 
```
(sqlite, positive_test_row_condition)
  ERROR: "module 'sqlalchemy.sql' has no attribute 'Subquery'"
  
Traceback (most recent call last):
  File "/Users/venv/lib/python3.7/site-packages/great_expectations/execution_engine/execution_engine.py", line 394, in resolve_metrics
    **metric_provider_kwargs
  File "/Users/venv/lib/python3.7/site-packages/great_expectations/expectations/metrics/metric_provider.py", line 34, in inner_func
    return metric_fn(*args, **kwargs)
  File "/Users/venv/lib/python3.7/site-packages/great_expectations/expectations/metrics/query_metrics/query_table.py", line 47, in _sqlalchemy
    selectable, sa.sql.Subquery
AttributeError: module 'sqlalchemy.sql' has no attribute 'Subquery'
```
**To Reproduce**
1. Go to [example](https://github.com/great-expectations/great_expectations/blob/develop/contrib/experimental/great_expectations_experimental/expectations/expect_queried_table_row_count_to_be.py)
2. add to the examples part the required test backends: 
```
 "test_backends": [
                {
                    "backend": "sqlalchemy",
                    "dialects": ["sqlite"],
                }]
```
3. Copy to Pycharm and run it. 
4. By the way - The first 2 tests are passing.

Can you please help? 
thanks a lot!

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version:  0.15.17

**Comment by rdodev** [comment]
Hey @itaise 👋 

Thanks for reporting this issue. I'll consult with the team and let your know.
