### ISSUE TITLE
Multiple Deprecation Warnings

### ISSUE THREAD

**Issue by shivankitsharma** [fivetran/great_expectations#5789]
Getting Multiple Deprecation Warnings

`/local_disk0/.ephemeral_nfs/envs/pythonEnv-a689360d-b706-40ae-a5ae-256db4066b66/lib/python3.9/site-packages/great_expectations/data_context/util.py:554: UserWarning: SQLAlchemy is not installed, using urlparse to mask database url password which ignores **kwargs.
  warnings.warn(`

`/local_disk0/.ephemeral_nfs/envs/pythonEnv-a689360d-b706-40ae-a5ae-256db4066b66/lib/python3.9/site-packages/great_expectations/datasource/data_connector/runtime_data_connector.py:133: DeprecationWarning: Specifying batch_identifiers as part of the RuntimeDataConnector config is deprecated as of v0.15.1 and will be removed by v0.18. Please configure batch_identifiers as part of Assets instead.
  warnings.warn(`

`/databricks/python/lib/python3.9/site-packages/jinja2/environment.py:1088: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
  return concat(self.root_render_func(self.new_context(vars)))`

**Comment by talagluck** [comment]
Hi @shivankitsharma - thank you for raising this. Could you please supply some background information? What was the code and configuration that lead to these warnings? What version of Great Expectations are you running?

**Comment by shivankitsharma** [comment]
The errors are coming when loading Great Expectations 15.15. These happen even before the code is run 

I have been looking for a way to suppress these warnings but nothing has worked and it is a big problem. Please help me figure out how to disable these warnings

**Comment by rdodev** [comment]
Hey @shivankitsharma is this still an issue with latest GX?
