### ISSUE TITLE
Include SSL parameters in MySQL connection

### ISSUE THREAD

**Issue by rob-teeuwen** [fivetran/great_expectations#5798]
I am trying to connect to an Azure hosted MySQL database that requires SSL. I can't find a solution to pass SSL parameters. In sqlalchemy this should be possible like so: https://docs.sqlalchemy.org/en/14/dialects/mysql.html#ssl-connections but I don't think this translates to Great Expectations yet.

It would be great if a field could be added to pass these parameters in the data context. If this already exists, please let me know where I can find more information about how it's done. Thanks!

**Comment by talagluck** [comment]
Hi @rob-teeuwen - thanks for raising this. We will review this and be in touch.

**Comment by AFineDayFor** [comment]
Howdy @rob-teeuwen :wave: thanks for reaching out and being a part of the community :bow: 

Passing this over the execution engine should help you get this over the line.
You can briefly review some of the connection [execution_engine](https://docs.greatexpectations.io/docs/terms/execution_engine/#configuration)

```yaml
---
name: {datasource_name}
class_name: Datasource
execution_engine:
  ...
  connect_args:
  key: value
```
