### ISSUE TITLE
Custom store_backend classes

### ISSUE THREAD

**Issue by tommy-watts-depop** [fivetran/great_expectations#5825]
We would like to be able to extend or create new store_backend classes to follow behaviour specific to our use case. For example, a new class to extend TupleS3StoreBackend that allows us to edit checkpoints stored in s3 before loading.

Currently there is no way (that i can see) to add a custom class to the store_backend block in the stores section of the great_expectations.yml config since the module_name variable is fixed [here](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/data_context/data_context/abstract_data_context.py#L1420). It would be great if we could define custom classes here and allow paths to existing modules.

**Comment by kenwade4** [comment]
Hi @tommy-watts-depop 

Did you mean where we set `module_name = "great_expectations.data_context.store"` in `_build_store_from_config()`? We eventually pass that in as a config default to `instantiate_class_from_config()`. In that function the config default is overridden if someone uses a module_name in the store config
