### ISSUE TITLE
Expectation expect_column_values_to_be_in_type_list not working as expected

### ISSUE THREAD

**Issue by pcontrerasnun** [fivetran/great_expectations#5832]
**Describe the bug**
I'm running the expect_column_values_to_be_in_type_list expectation against a ClickHouse datasource. It seems GE is not able to retrieve correctly data types when data type is Nullable from ClickHouse.

Here's an example. Observed value should be Nullable(UInt16) 
```
    {
      "exception_info": {
        "exception_message": null,
        "exception_traceback": null,
        "raised_exception": false
      },
      "expectation_config": {
        "expectation_type": "expect_column_values_to_be_in_type_list",
        "kwargs": {
          "batch_id": "25085b0bf9564ec7ece302b737b6ee1e",
          "column": "CONSTRUCTIONYEAR",
          "type_list": [
            "Nullable(UInt16)"
          ]
        },
        "meta": {}
      },
      "meta": {},
      "result": {
        "observed_value": "Nullable"
      },
      "success": false
    }
```
Moreover, when the column is not nullable, GE retrieves correctly the data type but even though the observed value and the expected value are the same, GE says they are not. An example:
```
    {
      "exception_info": {
        "exception_message": null,
        "exception_traceback": null,
        "raised_exception": false
      },
      "expectation_config": {
        "expectation_type": "expect_column_values_to_be_in_type_list",
        "kwargs": {
          "batch_id": "25085b0bf9564ec7ece302b737b6ee1e",
          "column": "TYPOLOGYID",
          "type_list": [
            "UInt8"
          ]
        },
        "meta": {}
      },
      "meta": {},
      "result": {
        "observed_value": "UInt8"
      },
      "success": false
    }
```
When rendering the data doc checkpoint I get the following warning: 
```
No sqlalchemy dialect found; relying in top-level sqlalchemy types.
No recognized sqlalchemy types in type_list for current dialect.
```

**Expected behavior**
GE should be able to retrieve correctly Nullable data types from ClickHouse. `expect_column_values_to_be_in_type_list` should return `"success": true` when observed type and expected type are the same.

**Environment:**
 - Operating System: Ubuntu 18.04.6 LTS
 - Great Expectations Version: 0.15.19
 - ClickHouse: 20.7.2.30
 - clickhouse-sqlalchemy: 0.2.1
 - clickhouse-driver: 0.2.4

**Comment by austiezr** [comment]
Hey @pcontrerasnun! Thanks for raising this. We've captured this for our internal backlog.

 It may be some time before we're able to prioritize something like this. While the community has enabled *some* limited Clickhouse functionality, GX does not officially support Clickhouse. If you're interested in contributing here, we would be happy to support a PR!

As we've captured this report & don't officially support Clickhouse, we're closing this out for now, but will gladly offer guidance on a contribution here if one comes in. 🙇
