### ISSUE TITLE
Slack doesn't seem to work

### ISSUE THREAD

**Issue by jmoskovc** [fivetran/great_expectations#5842]
**Is your feature request related to a problem? Please describe.**
Can't connect to your slack, seems like the invite expired
I click the link on your web page and get this:

![image](https://user-images.githubusercontent.com/110917909/186719373-b8a4c750-c47a-4780-a9c7-348b731cb0c7.png)

**Describe the solution you'd like**
Connect to to Slack, so I can engage in discussion with the community ..

**Describe alternatives you've considered**
Tried to find other ways, but it seems like Slack is the preferred way..

**Comment by nomisbeme** [comment]
I had the same experience, but was able to join the Great Expectations Slack using the link in their twitter profile: [http://greatexpectations.io/slack](http://greatexpectations.io/slack)

**Comment by austiezr** [comment]
Hey @jmoskovc! Thanks for raising; this should now be resolved. If you're still unable to join our Slack community from a fresh link please feel free to re-open!
