### ISSUE TITLE
Expect_column_values_to_be_in_type_list Not working with RuntimeDataConnector with PostgreSQL datasource

### ISSUE THREAD

**Issue by cah-jamey-weyenberg** [fivetran/great_expectations#5864]
I found some interesting behavior while testing out a profiler-made expectation suite. I was working with a PostgreSQL datasource and testing the expectation suite with an InferredDataConnector and RuntimeDataConnector that used a very basic SELECT query to grab the same table. Interestingly enough, the InferredDataConnector batch_request worked with no issues. The RuntimeDataConnector batch_request ran into errors however. The stack trace is shown below. I dug into the source code a little bit and found that the actual_column_types_list does not have any "type" keys in it. Here's some example output from a print statement:` ****actualtypes****: [{'name': 'ad_group_key'}, {'name': 'ad_group_nam'}, {'name': 'row_add_stp'}, {'name': 'row_add_user_id'}, {'name': 'row_update_stp'}, {'name': 'row_update_user_id'}] `. And here is the stacktrace for the error:
```
Traceback (most recent call last):
File "/home/jamey.weyenberg/venv/lib64/python3.6/site-packages/great_expectations/validator/validator.py", line 848, in graph_validate
runtime_configuration=runtime_configuration,
File "/home/jamey.weyenberg/venv/lib64/python3.6/site-packages/great_expectations/core/expectation_configuration.py", line 1370, in metrics_validate
execution_engine=execution_engine,
File "/home/jamey.weyenberg/venv/lib64/python3.6/site-packages/great_expectations/expectations/expectation.py", line 707, in metrics_validate
execution_engine=execution_engine,
File "/home/jamey.weyenberg/venv/lib64/python3.6/site-packages/great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py", line 553, in _validate
for type_dict in actual_column_types_list
File "/home/jamey.weyenberg/venv/lib64/python3.6/site-packages/great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py", line 554, in
if type_dict["name"] == column_name
KeyError: 'type'
```

The query I passed in with the RuntimeDataConnector was a simple SELECT statement shown here:
`SELECT * FROM ad_group`

**Expected behavior**
To correctly identify the types in a column.

**Environment (please complete the following information):**
 - Operating System: Linux virtual machine
 - Python version: 3.6
 - Great Expectations Version: 0.14.13

**Additional context**
I think the issue is arising from the metrics variable being passed in. However, I couldn't quite find where this was coming from after going through the stack trace.

**Comment by sergiotj** [comment]
Same happens in snowflake

**Comment by billdirks** [comment]
Thanks for reporting this issue @cah-jamey-weyenberg. I am going to try to reproduce this issue. Could you provide your datasource configuration and the script you used to produce this error?

I notice you are on an older versions of Great Expectations (our current version is 0.16.11) and a Python we currently don't support (we only support 3.7+).  I'm curious if you've hit this with newer versions of our library and of Python.

**Comment by billdirks** [comment]
I haven't been able to reproduce this. Please feel free to reopen if you are still seeing this on the latest version of Great Expectations and on Python 3.7+.
