### ISSUE TITLE
How to define a custom Datasource/ DataConnector

### ISSUE THREAD

**Issue by hebrd** [fivetran/great_expectations#5875]
Any reference documents related to custom Datasource/ DataConnector? I would like to check the quality of data which is requested from API. Also datasource for clickhouse

**Comment by pcontrerasnun** [comment]
For ClickHouse, see this post https://discuss.greatexpectations.io/t/is-anyone-using-great-expectations-with-the-clickhouse-dbms/654/2. Note that CH is not fully supported so you may face some issues

**Comment by austiezr** [comment]
Hey @BrandonDotLin ! We don't currently have documentation around creating custom Datasources / DataConnectors. However, we do plan to expand our coverage in this area in the near future.

In the mean-time, if you're interested in this type of custom work, you may be interested in checking out this [PR adding support for AWS Glue](https://github.com/great-expectations/great_expectations/pull/5123/commits), as well as checking out how we handle support for various SQL dialects.

Closing out this issue for now, but I'll update here once our documentation goes live. 🙇
