### ISSUE TITLE
[Spark] expect_column_pair_values_A_to_be_greater_than_B(parse_strings_as_datetimes=True) is not working properly

### ISSUE THREAD

**Issue by mykola-yesypchuk-inflection** [fivetran/great_expectations#5888]
https://github.com/great-expectations/great_expectations/blob/1f2bc4d3c33faa898f76ecd3bf267bd788bae9bc/great_expectations/dataset/sparkdf_dataset.py#L1362

Data:
"col_a": ["07/11/1967", "04/07/1966", "01/03/1953"],
"col_b": ["08/10/1960", "03/07/1966", "01/01/1900"],
Engine: 
Spark
Command:
validator.expect_column_pair_values_A_to_be_greater_than_B("col_b", "col_a", parse_strings_as_datetimes=True)
Expected: 
expectation result=Failed
Now:
expectation result=True

Details:
When we compare dates fields(string fields in '%m/%d/%Y' format) using expect_column_pair_values_A_to_be_greater_than_B, all tests will be passed. 
I guess the reason that sparktypes.TimestampType() used in the code of expectation. The string value can't be parsed correctly and ignore all rows.

**Comment by austiezr** [comment]
Hey @mykola-yesypchuk-inflection ! Thanks for raising this; we'll investigate and be in touch.

**Comment by austiezr** [comment]
Hey @mykola-yesypchuk-inflection ! Unfortunately, we are no longer actively developing the V2 API. Additionally, Great Expectations is stepping back from performing any type of input transformation (we believe testing should be done on data as it is; see [this blog post](https://greatexpectations.io/blog/why_we_dont_do_transformations_for_expectations/) for further explanation).

If you're interested in contributing a fix in this area, I would be happy to provide review and guidance; however, at this time I'm closing out this issue.

**Comment by mykola-yesypchuk-inflection** [comment]
Thank you for your response.
