### ISSUE TITLE
Docs bug: Expectation Suite link broken on Index page's "Validation Results" tab

### ISSUE THREAD

**Issue by tylertrussell** [fivetran/great_expectations#5921]
**Describe the bug**
On a GE Docs static site (deployed to S3, in this case) on the Index page, "Validation Results" tab, the "Expectation Suite" column contains broken links for all validations listed.

Validations in this case have a full file path of `expectations/foo_baz_bar/foo_baz_bar_data_quality.json`.

**To Reproduce**
1. Create an expectation suite named like `expectations/foo_baz_bar/foo_baz_bar_data_quality.json`, deploy a GE Docs site, and run a validation
2. Go to the GE Docs site's Index Page
3. Observe any validation result rows in the "Validation Results" tab
4. At far right, click on the expectation suite's name
5. Observe 404 error

**Expected behavior**
The URL generated for the link should contain the full file path

**Environment (please complete the following information):**
 - Great Expectations Version: 0.15.6
 - S3 bucket behind Cloudfront

**Additional context**
I believe this problem only occurs when expectation suites are within nested folders, but have no good way to test this

**Comment by tylertrussell** [comment]
I noticed the link to the expectation suite at the top of any given Validation Result's page is also broken, but I am not sure if #5922 will fix that

**Comment by austiezr** [comment]
Hey @tylertrussell ! Thanks for raising this. Are you able to share your GE version & environment details? I'm unable to reproduce this behavior on 0.15.21.

**Comment by tylertrussell** [comment]
> Hey @tylertrussell ! Thanks for raising this. Are you able to share your GE version & environment details? I'm unable to reproduce this behavior on 0.15.21.

Hey @austiezr - we are on 0.15.6, perhaps upgrading will alleviate this problem.

Out of curiosity, what is the structure of your expectation files?  I was wondering if putting our expectations in a folder such as `expectations/foo_baz/foo_baz_data_quality.json` was causing this issue
