### ISSUE TITLE
[BUG] marshmallow package conflict with airflow

### ISSUE THREAD

**Issue by itaise** [fivetran/great_expectations#5929]
Hi, 
In great expectations latest version (0.15.21) marshmallow specific packages requirement was [added](https://github.com/great-expectations/great_expectations/pull/5866)
However, this is not compatible with Airflow, for example, the few latest versions: 
https://raw.githubusercontent.com/apache/airflow/constraints-2.3.4/constraints-3.7.txt
https://raw.githubusercontent.com/apache/airflow/constraints-2.3.3/constraints-3.7.txt
https://raw.githubusercontent.com/apache/airflow/constraints-2.3.2/constraints-3.7.txt

require an **earlier** version of marshmallow (3.16 or 3.17), so our builds are failing on pip conflicts.

Can you please check?

Thanks a lot!

**Comment by itaise** [comment]
@cdkini maybe you have some insight on that? Thanks a lot!

**Comment by rdodev** [comment]
Hey @itaise @cdkini is working on a fix for this. He'll provide an update soon.

**Comment by itaise** [comment]
thanks a lot!

**Comment by itaise** [comment]
Hi, @cdkini  @rdodev  any updates on this? thanks!

**Comment by orenewix** [comment]
Any news?

**Comment by orenewix** [comment]
@cdkini @rdodev can you please provide an update, if this remains on the next Airflow upgrade Wix will have to stop using GE package

**Comment by cdkini** [comment]
Apologies for the delayed response @itaise @orenewix.

Our current pin is as follows: `marshmallow>=3.7.1,<4.0.0`

I believe this was immediately updated after [the referenced PR above](https://github.com/great-expectations/great_expectations/pull/5866) was merged. Please let me know if you're still seeing issues with these updated bounds.

**Comment by austiezr** [comment]
Closed as resolved by #6213 ; if this issue persists, feel free to re-open with further context.
