### ISSUE TITLE
[BUG] Snowflake metadata is not caching

### ISSUE THREAD

**Issue by sergiotj** [fivetran/great_expectations#5933]
My environment:  MacOS
I am trying to connect snowflake to my code with greatest expectations to get some results regarding data quality and validation.

Everything is working great except the fact that every second GE is sending this query to SF: 
(SHOW /* sqlalchemy:_get_schema_primary_keys */PRIMARY KEYS IN SCHEMA myschema), and also this query 

(SELECT … FROM information_schema.columns ic WHERE ic.table_schema=myschema)

Also, I tried to add cache_column_metadata=True in my connection string but it didn't solve the issue.
I saw this issue as well https://github.com/great-expectations/great_expectations/issues/3429 but the solution proposed is not working in my side (the proposed solution is to using ConfiguredAssetSqlDataConnector).

```
data_context_config = DataContextConfig(
    datasources={
        "my_snowflake_datasource": DatasourceConfig(
            class_name="Datasource",
            execution_engine={
        "class_name": "SqlAlchemyExecutionEngine",
"connection_string": connstring
            },
            data_connectors={
    "default_configured_data_connector_name": {
        "class_name": "ConfiguredAssetSqlDataConnector",
        "module_name": "great_expectations.datasource.data_connector",
         "assets": {
                "table": {
                    "splitter_method" : "_split_on_column_value",
                    "splitter_kwargs": {
                        "column_name": "ds"
                    }
                }
           },
    },
            
            }
        )
    },
    store_backend_defaults=FilesystemStoreBackendDefaults(root_directory=temp_dir.name)
)
```

```
context = BaseDataContext(project_config=data_context_config)


batch_request=BatchRequest(
    datasource_name="my_snowflake_datasource",
    data_connector_name="default_configured_data_connector_name",
    data_asset_name="table",
    data_connector_query={
        "batch_filter_parameters": {"ds": "2022-01-01"}
    },
    batch_spec_passthrough={"create_temp_table": False, 'use_quoted_name': True},
)

```

**Comment by rdodev** [comment]
Hello @sergiotj thanks for raising this issue. I will bring this to the team's attention and get back to you.

**Comment by rdodev** [comment]
Hey @sergiotj 

I spoke with engineering and they said this issue should have been resolved in the latest release. Would you mind trying it and reporting back if you encounter any issues? Thanks!

**Comment by sergiotj** [comment]
Hi @rdodev! I just installed the last version - 0.15.22 and I have found the same issue :/

**Comment by kenwade4** [comment]
@sergiotj if you are using the InferredAssetSqlDataConnector, you can update your config so that it [doesn't introspect the entire database](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_configure_a_dataconnector_to_introspect_and_partition_tables_in_sql/), by adjusting `introspection_directives` settings like [in this test](https://github.com/great-expectations/great_expectations/blob/d12e9af949181d3a5af59e5e7cc88261b850e83b/tests/datasource/data_connector/test_sql_data_connector.py#L1758-L1780). Documentation updates are coming soon for this.

ConfiguredAssetSqlDataConnector had some bugs before, but you should be able to use it properly now. If you are using that, you shouldn't introspect at all.

**Comment by sergiotj** [comment]
@kenwade4 the problem isn't the introspection of the entire database. It's not doing that... The problem is the fact that for each expectation calculation in database, the GE is querying these queries: 

- SHOW /* sqlalchemy:_get_schema_primary_keys */PRIMARY KEYS IN SCHEMA myschema
- SELECT … FROM information_schema.columns ic WHERE ic.table_schema=myschema

Example:

1. Query get_schema_primary_keys and information_schema.columns
2. Calculates expectation expect_column_mean_to_be_between
3. Once again, query get_schema_primary_keys and information_schema.columns
4. Calculates expect_column_median_to_be_between
5. etc etc 

I do think that it should query get_schema_primary_keys and information_schema just one time. But it is doing it repeatedly!

**Comment by kenwade4** [comment]
Yea that shouldn't be happening @sergiotj

Are you running checkpoints to trigger this, running individual Expectations in a notebook, or something else?

Can you share more of your config information?

**Comment by sergiotj** [comment]
@kenwade4 here is my code:

```
from great_expectations.data_context.types.base import DataContextConfig, DatasourceConfig, InMemoryStoreBackendDefaults
from great_expectations.data_context import BaseDataContext

data_context_config = DataContextConfig(
    datasources={
        "my_snowflake_datasource": DatasourceConfig(
            class_name="Datasource",
            execution_engine={
        "class_name": "SqlAlchemyExecutionEngine",
"connection_string": f"snowflake://.......cache_column_metadata=True" 
            },
            data_connectors={
            "default_inferred_data_connector_name": {
                "class_name": "InferredAssetSqlDataConnector",
                "include_schema_name": True,
                "excluded_tables": None,
                "included_tables": ['schema.table'],
                "skip_inapplicable_tables": True,
                "introspection_directives": {
                    "schema_name": "schema",
                    "ignore_information_schemas_and_system_tables": True,
                    "information_schemas": None,
                    "system_tables": None,
                    "include_views": True,
                },
                "batch_spec_passthrough": None,
            },
            
            }
        )
    },
    store_backend_defaults=InMemoryStoreBackendDefaults()
)

context = BaseDataContext(project_config=data_context_config)

batch_request=BatchRequest(
                datasource_name="my_snowflake_datasource",
                data_connector_name="default_inferred_data_connector_name",
                data_asset_name="schema.table",
            )

validator = context.get_validator(batch_request=batch_request)

from great_expectations.profile.user_configurable_profiler import UserConfigurableProfiler

profiler = UserConfigurableProfiler(
    profile_dataset=validator,
    excluded_expectations=[
        "expect_column_quantile_values_to_be_between",
        "expect_column_mean_to_be_between",
        'expect_column_median_to_be_between',
        #'expect_column_values_to_be_in_set'
        "expect_table_row_count_to_be_between",
        #"expect_table_columns_to_match_ordered_list",
        "expect_column_proportion_of_unique_values_to_be_between",
        #"expect_column_values_to_be_in_type_list",
        "expect_column_values_to_be_unique",
        'expect_column_proportion_of_unique_values_to_be_between',
        "expect_compound_columns_to_be_unique",
    ]
)
```

**Comment by sergiotj** [comment]
I am wondering if the creation of the temp table could be the cause for the cache getting broken... What do you think about it? @kenwade4

**Comment by sergiotj** [comment]
@kenwade4 

I can solve this issue changing the function get_sqlalchemy_column_metadata in expectations/metrics/util.py to:


`
inspector_new = None
def get_sqlalchemy_column_metadata(
    engine: Engine, table_selectable: Select, schema_name: Optional[str] = None
) -> Optional[List[Dict[str, Any]]]:

    global inspector_new
    try:
        columns: List[Dict[str, Any]]

        if inspector_new is None:
            print('get inspector')
            inspector: reflection.Inspector = get_sqlalchemy_inspector(engine)
            inspector_new = inspector
        else:
            print('recover it')
            inspector = inspector_new
        try:
            # if a custom query was passed
            if isinstance(table_selectable, TextClause):
                columns = table_selectable.selected_columns.columns
            else:
                columns = inspector.get_columns(
                    table_selectable,
                    schema=schema_name,
                )
        except (
            KeyError,
            AttributeError,
            sa.exc.NoSuchTableError,
            sa.exc.ProgrammingError,
        ):
            # we will get a KeyError for temporary tables, since
            # reflection will not find the temporary schema
            columns = column_reflection_fallback(
                selectable=table_selectable,
                dialect=engine.dialect,
                sqlalchemy_engine=engine,
            )

        # Use fallback because for mssql and trino reflection mechanisms do not throw an error but return an empty list
        if len(columns) == 0:
            columns = column_reflection_fallback(
                selectable=table_selectable,
                dialect=engine.dialect,
                sqlalchemy_engine=engine,
            )

        return columns
    except AttributeError as e:
        logger.debug(f"Error while introspecting columns: {str(e)}")
        return None
`

The difference is the fact that I am saving the inspector in a global variable. The issue here is that for each column, the GE is always getting a new inspector (and that send those metadata queries to snowflake). Can you change it to just get the inspector once (at the beginning)?
