### ISSUE TITLE
[BUG] Batch IDs are *NOT* accessible in the order in which they were loaded in Validator

### ISSUE THREAD

**Issue by dansola** [fivetran/great_expectations#6035]
**Describe the bug**
When accessing validation results for example like this: `validation_results.meta["active_batch_definition"]["batch_identifiers"]`, the keys are not in the same order as they were loaded according to the order of `batch_identifiers` listed in the `great_expectations.yml` file for a datasource. I got this error when updating from 0.13.28 to 0.15.22.

Looking at the [changelog](https://github.com/great-expectations/great_expectations/blob/34839c0d35b464418e96c5d3e7d425be18036b13/docs/changelog.md), it looks like this bug was addressed by [PR #5112](https://github.com/great-expectations/great_expectations/pull/5112).

Any idea why this bug appears to be persisting? 

**To Reproduce**
1. Make a `RuntimeBatchRequest` instance.
2. Use `add_checkpoint()` method to to add a checkpoint config dictionary.
3. Use the `run_checkpoint()` method with the `RuntimeBatchRequest` instance passed in a dictionary, in a list, to the `validator` argument. Example: `validations=[{"batch_request": runtime_batch_request}]`. An action list is also provided.

**Expected behavior**
When working in a custom `ValidationResultsPageRenderer` child class, the `validation_results.meta["active_batch_definition"]["batch_identifiers"]` keys are expected to be in the same order as they are defined in the `great_expectations.yml` file. Instead they are in alphabetical order.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: [e.g. 0.15.22]

**Comment by talagluck** [comment]
Hi @dansola - thanks for opening this issue. We will review and be in touch.

**Comment by molliemarie** [comment]
Hello @dansola. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
