### ISSUE TITLE
Limit the value_set object size in validation results

### ISSUE THREAD

**Issue by rtitton** [fivetran/great_expectations#6047]
With `expect_column_values_to_be_in_set` expectation type, the provided `value_set` argument is put in the validation result json file, within the expectations_config dictionary.
Example of validation result:
![immagine](https://user-images.githubusercontent.com/15352090/191234844-1ee3fe5f-132a-4db4-b4de-0ada7d1f54c8.png)

When the provided value_set is defined as a query store reference, instead of a hard coded list, it can possibly be a very large set, leading to a very large validation json file.
Example of value_set configuration with query store reference:
![immagine](https://user-images.githubusercontent.com/15352090/191232146-c8414f3e-c842-4c8f-844d-6d94aa207df3.png)

In this case it would be useful to put only a partial list of values in the validation result to limit the size of the json file.
As an example, the partial_unexpected_list currently shows only a few elements.

I have configured my validation store as a data base so that a validation run pushes a json as is on a data base schema. I' having memory issues with a third party tool that reads and parses the jsons from the db, due to the size of value_set lists.

I propose the implementation of a new runtime configuration parameter at checkpoint level, named `expectation_config_value_set`, with the following possible values:
COMPLETE:  put all the values in the validation json file.
an integer number: put at most that number of values in the validation json file.

**Comment by talagluck** [comment]
Hi @rtitton - thanks for raising this. This is a really interesting issue - I understand the problem that you are facing, though it may not be addressable. Thinking about Expectation Suites as data contracts, I can imagine it being problematic for users to not know the value set of an Expectation that passes or fails without an external reference, since it will be difficult to understand what passed or failed. We will discuss internally and follow up. In the meantime, if you have any additional ideas here, please let us know.

**Comment by talagluck** [comment]
Hi @rtitton - thank you again for your feedback and your patience here. We have discussed this in greater detail, and come to the conclusion that this is not a change that we will want to make.

There are times when we will truncate Validation Results for a given Expectation Validation, e.g. if there are many failed rows. In that event, truncating those rows doesn't change the outcome - the Expectation has failed, and a user can go back and query their data using the failure information.

However, in this case, modifying the Expectation Configuration itself goes against the spirit of Great Expectations where tests serve as documentation. What will happen in this case is that if an Expectation passes or fails, truncating the contained `value_set` will make it impossible to know the actual Expectation that was run, and this would defeat the purpose. 

If you wish, you be able to build a custom Expectation that skips the rendering of this, but in the short-term this is not a change that we wish to make. I'm going to close this for now, but again, thank you for the feedback!

**Comment by claire7playe** [comment]
Hello, we would like to test the presence of all ids in a fact table by selecting those of a dim table which gives a list of 300 000 ids. I understand the idea of being able to recover the list in case of errors. Would it be possible to limit at least the value_set in the Data docs (the page takes 1-2 min to load). Or is there any other way to perform these tests with Great expectations?
