### ISSUE TITLE
Using PySpark Timestamp Type throws "TypeError: Object of type Timestamp is not JSON serializable"

### ISSUE THREAD

**Issue by juliankeppel** [fivetran/great_expectations#6073]
Hi,

I use GE version 0.15.24, PySpark version 3.2.1 and Python version 3.8.6

I have some custom expectations based on timestamp columns in PySpark dataframes.

The validation itself works perfectly, but whenever we want to call the result object, we get the following stacktrace: 
```
return json.dumps(self.to_json_dict(), indent=2)
  File "/usr/lib64/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib64/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Timestamp is not JSON serializable
```

It looks like there is a problem in correctly interpreting the PySpark Timestamp time. 

When I remove the corresponding expectations that include Timestamps, it works perfectly.

**Comment by austiezr** [comment]
Hey @juliankeppel ! Thanks for reaching out. Are you able to share the `_spark` & `_validate` methods of your Custom Expectations, as well as the workflow generating this stack trace?

**Comment by juliankeppel** [comment]
@austiezr 

The `expect_column_values_to_not_exceed_timerange`  inculded in the following class is our custom expectation that is probably responsible for the exception (because of the timestamps handled in it): 
```
class CustomSparkDFDataset(SparkDFDataset):  # type: ignore
    """Class which contatins all custom expectations."""

    @MetaSparkDFDataset.column_map_expectation
    @typing.no_type_check
    def expect_column_values_to_equal_value(
        self,
        column,
        value,
        mostly=None,
        result_format=None,
        include_config=True,
        catch_exceptions=None,
        meta=None,
    ) -> SparkDFDataset:
        """Expect column value to equal a specified value."""
        return column.withColumn(
            "__success",
            when(column[0] == value, lit(True)).otherwise(lit(False)),
        )

    @MetaSparkDFDataset.column_map_expectation
    @typing.no_type_check
    def expect_column_values_to_not_exceed_timerange(
        self,
        column,
        add_hours,
        add_minutes,
        mostly=None,
        result_format=None,
        include_config=True,
        catch_exceptions=None,
        meta=None,
    ) -> SparkDFDataset:
        """Expect column value to be within specified timerange."""
        min_timestamp = self.get_column_min(column.columns[0])
        max_timestamp = min_timestamp + timedelta(hours=add_hours, minutes=add_minutes)
        return column.withColumn(
            "__success",
            when(column[0].between(min_timestamp, max_timestamp), lit(True)).otherwise(
                lit(False)
            ),
        )
```

Our workflow is encapsulated in a custom wrapper library. What it basically does is to create a data context, collect expectations suites and validates the suites against a given Spark dataframe. This is how our workflow looks like:

```
# Create datafarme to validate

custom_df_to_validate = CustomSparkDFDataset(df_to_validate)

# Create wrapper object
great_expectations = MyGreatExpectations(
            SimpleSparkDFDataContextBuilder()
            .data_asset_type(CustomSparkDFDataset)
            .build()
        )

# Add different expectation suites (implemented somewhere else)
great_expectations.add_expectations(
            parse_expectation_suite(
                "my_validation_suite",
                expectations_1
                + expectations_2
                + custom_expectations
                + set_of_existing_ids_expectation,
            ),
            on=custom_df_to_validate,
        )

results = great_expectations.validate()

# Do something with the result object
results.to_json_dict() # Here the exception appears
```

The `validate` function basically calls `run_validation_operator` on the created data context.

**Comment by juliankeppel** [comment]
@austiezr Can you say anything to my issue here? I'm still stuggling and according to the stacktrace, it occurs directly in Great Expectations core (I accidently truncated it in the original post): `great_expectations/core/expectation_validation_result.py", line 424, in __repr__`

When I remove the expectations that handle Timestamp types, my complete workflow works as expected.

**Comment by austiezr** [comment]
`Dataset` objects such as `SparkDFDataset` have long been deprecated and not under active development (since `0.13.0`) -- likewise for Custom Expectations built for those objects. This serialization error is related to the constraints of those objects. If you're able to update your workflows in line with[ modern GX usage](https://docs.greatexpectations.io/docs/home/), you should see this type of functionality work without throwing these types of errors. Closing this out due to above deprecation.
