### ISSUE TITLE
Regex-Based Column Map Expectations based on MSSQL & Oracle DB

### ISSUE THREAD

**Issue by as93717913** [fivetran/great_expectations#6089]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
We need to check is data follow company's guideline like naming convention, and our company use mssql and oracle as standard DB stack 

**Describe alternatives you've considered**

**Additional context**

**Comment by austiezr** [comment]
Hey @as93717913 ! Thanks for raising this. We'll discuss internally and review how functionality should be addressed in this area.

**Comment by austiezr** [comment]
Hey @as93717913! As Great Expectations doesn't officially support Oracle, we're not able to implement for Oracle at this time. However, I'm currently testing an implementation for MSSQL, and we are happy to provide review and guidance if you're interested in contributing this functionality for Oracle as well.

**Comment by austiezr** [comment]
Closing as GX doesn't support MSSQL or Oracle at this time.
