### ISSUE TITLE
Can't support AWS china secrets manger for data context

### ISSUE THREAD

**Issue by karry-li-lego** [fivetran/great_expectations#6105]
As great_expectations/data_context/data_context/abstract_data_context.py
line 263  is:
if value.startswith("secret|arn:aws:secretsmanager"):
but for aws china region, the third part is **aws-cn**, not **aws**, so could you please support AWS China region?

**Comment by austiezr** [comment]
Hey @karry-li-lego ! Thanks for raising this. We'll review this behavior and be in touch.

**Comment by molliemarie** [comment]
Hello @karry-li-lego. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
