### ISSUE TITLE
FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.

### ISSUE THREAD

**Issue by dvorst** [fivetran/great_expectations#6132]
Using pandas v1.5.0

Getting warning: "FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead."

https://github.com/great-expectations/great_expectations/blob/85eed98305d4d741635459022b1e6eee7b4da370/great_expectations/core/util.py#L263

**Comment by AFineDayFor** [comment]
Howdy @dvorst :wave: thank you for raising this with us :bow:

We'll convey this to the team, thank you so very much for being observant.

**Comment by talagluck** [comment]
Resolved by #6205
