### ISSUE TITLE
Expecting property name enclosed in double quotes: line 11 column 9 (char 302) when running checkpoint doesn't matter which expectation or  dataframe

### ISSUE THREAD

**Issue by Jorgicol** [fivetran/great_expectations#6158]
ERROR:great_expectations.validation_operators.validation_operators:Error running action with name store_evaluation_params

Expecting property name enclosed in double quotes: line 11 column 9 (char 302) when running checkpoint doesn't matter which expectation or dataframe.

Not sure if it is due to the new version release, but working in 0.15.24 still crashing

**Comment by AFineDayFor** [comment]
Howdy @Jorgicol 👋 thanks for reaching out and bringing this to our attention🙇‍♀️ 

So we can reproduce this please share the configuration, and so we dan review it further can you please share the full stack trace below 🔬🦠

We'll raise this with the team.

Thanks for contributing to this stellar community with your time 😄 we appreciate it greatly and know it's the most important thing any of us have. 🙇‍♀️

**Comment by Jorgicol** [comment]
Hi AFineDayFor, appreciate your time and quick response. It seems this problem was due to my cluster cache, once It was cleaned it worked as usual. Thanks anyway. You can close this issue :)

**Comment by Jorgicol** [comment]
One of the json corresponding to a suite was with incorrect syntax, seems that when moving from blob to dbfs of databricks it is executed somehow and the error persist whenever I tried to run a df with a different suite. That was the real cause.

**Comment by talagluck** [comment]
Thanks for the follow-up, @Jorgicol!
