### ISSUE TITLE
expect_column_values_to_be_in_type_list() got multiple values for argument 'column'

### ISSUE THREAD

**Issue by berrisfordjohn** [fivetran/great_expectations#6187]
**Describe the bug**
We are running expectations in a generic method using the following python code.
When I try expect_column_values_to_be_in_type_list or expect_column_values_to_be_of_type I get the error 
Traceback (most recent call last):
  File "/home/kctw964/data_to_cmm/tests/test_expectation_handling.py", line 15, in <module>
    ret = method(df_ge, **test_to_run)
  File "/home/kctw964/data_to_cmm/.venv/lib/python3.9/site-packages/great_expectations/data_asset/util.py", line 76, in f
    return self.mthd(obj, *args, **kwargs)
TypeError: expect_column_values_to_be_in_type_list() got multiple values for argument 'column'

This seems to be an issue with **kargs in expect_column_values_to_be_in_type_list where column is passed both as an arg and a kargs

**To Reproduce**
import pandas as pd
import great_expectations as ge

data = {'car': ['Ford', 'Skoda']}

df = pd.DataFrame(data)
print(df)
expectations = {'expect_column_values_to_be_in_type_list': {'column':'car', 'type_list': ['object']}}

df_ge = ge.from_pandas(df)
print(df_ge)
for expectation in expectations:
    test_to_run = expectations[expectation]
    method = getattr(df_ge, expectation)
    ret = method(df_ge, **test_to_run)

This fails with the above traceback

**Expected behavior**
The argument column should be passed as a arg not kwarg. This seems to happen in all methods with **kargs as a variable

**Environment (please complete the following information):**
 - Operating System: Linux, MacOS, Windows
 - Great Expectations Version: 0.15

**Additional context**

**Comment by talagluck** [comment]
Hi @berrisfordjohn - thank you for opening an Issue. Where did you find the code that you are using here? This path is using V2, which we are on the way to deprecating. It also isn't a path that I've seen before, and is likely not tested. What are you trying to do? Does this fail for you on V3 as well?

**Comment by berrisfordjohn** [comment]
Thanks for the quick response. 
Seems github didn't notify of your quick response!

We created the code above. It may be unusual route to run the expectations.
What we were looking for was a method that was extensible (we didn't know which expectation someone would pick in advance), expectations could be driven by configuration outside of the code base, and could be run in a lambda function without Great Expectations reading from a file (i.e. we pass in a dataframe and expectations as arguments)

Is this possible using a different method? if so can you point me at the documentation?
Thanks

**Comment by talagluck** [comment]
Hi @berrisfordjohn - I don't think there is an exact parallel with what you are trying to do. [The guide for connecting to data with a Dataframe is here. ](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/in_memory/pandas) We are also currently working on code to make this process faster and easier, and will be updating our documentation in the coming weeks - please keep an eye out for this.

In the meantime, I'm going to close this issue since it uses an unsupported codepath, but please feel free to reach back out if you have additional questions. You may also get a quicker response for questions like this in Slack.
