### ISSUE TITLE
Using "row_condition" in conjunction with "$PARAMETER" in a Conditional Expectation

### ISSUE THREAD

**Issue by msanchezBek** [fivetran/great_expectations#6214]
**Request Summary**
I am looking to create a conditional expectation using: `expect_column_values_to_be_in_set`. Specifically, I would like the `row_condition` to check if a certain column is in a certain row of a csv file (instead of just comparing a column value to a string value).

**Desired Solution**
Theoretically I would be able to do this by using `row_condition` in conjunction with a `$PARAMETER` value which would look something like the following:
````
{
      "expectation_type": "expect_column_values_to_be_in_set",
      "kwargs": {
        "column": "COL1",
        "value_set": {
          "$PARAMETER": "valid_col_1_values"
        },
        "condition_parser": "pandas",
        "row_condition": {
          "column": "COL2",
          "expectation":  "expect_column_values_to_not_be_in_set",
          "value_set": {
            "$PARAMETER": "valid_col_2_names"
          }
        }
      }
    }
````
**Alternatives**
I have considered writing a wrapper that would take the content of the target csv (value of `valid_col_2_names` in the example) above and writing that to the above expectation's `row_condition` before validation is performed. For example:
````
...
"row_condition": "COL2 not in [<value1>, <value2>, ...] <- this list generated dynamically
...
````
This approach, however, seems hacky and against the spirit of how Great Expectations is structured. 

**Note**
I wasn't able to find an existing expectation that satisfied my requirement for this situation but I certainly acknowledge there could be one out there that I haven't seen. Please let me know if that's the case or if there's a cleaner way to evaluate the above expectation. Any input is appreciated! Thanks!

**Comment by AFineDayFor** [comment]
👋 Howdy @msanchezBek. 

Getting this sorted, if this is something you expect to contribute we'd be glad to review it at the time; however, if you'd want to help us figure out if this feels like a good fit for discussions and want to try it there that's always welcome too. 

I'm excited, it seems that you're excited to do an interesting thing :) rock on.

**Comment by molliemarie** [comment]
Hello @msanchezBek. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
