### ISSUE TITLE
SparkDFDatasource can't use DatabricksTableGenerator

### ISSUE THREAD

**Issue by sspitz3** [fivetran/great_expectations#623]
I'm trying to use `SparkDFDatasource` with a `DatabricksTableGenerator`. To me , it seems multiple problems are happening:

* `Datasource.add_generator` doesn't pass `type_` although `DatabricksTableGenerator requires it:
https://github.com/great-expectations/great_expectations/blob/master/great_expectations/datasource/datasource.py#L202

* `Datasource.get_batch` takes `batch_kwargs` as a `dict`, passing it to `SparkDFDatasource._get_data_asset`, which then tries `batch_kwargs.query`, rather than `batch_kwargs["query"]`:
https://github.com/great-expectations/great_expectations/blob/master/great_expectations/datasource/spark_source.py#L97

* In general, I'm not sure why `DatabricksTableGenerator._get_iterator()` is returning `dict_keyiterator` object. Shouldn't it give back the batch_kwargs dict?
https://github.com/great-expectations/great_expectations/blob/master/great_expectations/datasource/generator/databricks_generator.py#L28

**Comment by jcampbell** [comment]
Thanks for flagging -- I'm taking a look at this now.

**Comment by jcampbell** [comment]
You're exactly right on all three counts. We're planning to add integration testing for databricks but haven't yet. I'm going to make these changes and add some basic tests around them for the new release on Monday.
