### ISSUE TITLE
BasicDatasetProfiler is not generating Data Docs neither storing the profiler

### ISSUE THREAD

**Issue by jmcorreia** [fivetran/great_expectations#6235]
**Describe the bug**
I successfully profile the data using Spark DF and Great Expectations and I can see the results and expectations in the logs, but the profiler seems not to be stored (there is nothing inside the profiler folder) and it is also not showing in the UI (if is only showing the expecation suite).
I could not find any information/examples on the documentation on how to implement this. Am I missing something?
Can you share any example? Working with Spark or any other tool (because I could also not find profiler examples for other tools)?

**Expected behavior**
The profiler should be stored in the profilers folder. Moreover, there should be a profiling page in the UI with the histograms and so on.

**Environment:**
 - Operating System:MacOS
 - Great Expectations Version: latest

**Comment by jmcorreia** [comment]
I got the feedback that the BasicDatasetProfiler is deprecated.

**Comment by austiezr** [comment]
Closing this out for now, since (as noted) BDP is deprecated.
