### ISSUE TITLE
Postgresql hook connection

### ISSUE THREAD

**Issue by 708kelly** [fivetran/great_expectations#6236]
hi teams,
  I want to use it on airflow. Now, we use postgresql hook as connection. I had read the document and great_expectations/datasource/sqlalchemy_datasource.py. Now, it only provide use url to connect db. Is it possible to add a new connection approach or any recommend way to do it?
ref: https://stackoverflow.com/questions/61528860/sqlalchemy-engine-from-airflow-database-hook
thanks,
Kelly

**Comment by rdodev** [comment]
Hey @708kelly 👋 

I will convert this issue into a discussion and point the engineering team to it.
