### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Karaqz** [fivetran/great_expectations#6297]
**Describe the bug**
When entering the path of the root directory where the data is stored the error [WinError 2] The system cannot find the file specified shows up. This happens when following the [tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_connect_to_data) in step 2 but also when I try it with a local file. 

**To Reproduce**
1. Go to [the tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_overview).
2. Follow the steps untill you get to: _Enter the path of the root directory where the data files are stored. If files are on local disk enter a path relative to your current working directory or an absolute path._
3. See error

**Expected behavior**
This will now open up a new Jupyter Notebook to complete the Datasource configuration. Your console will display a series of messages as the Jupyter Notebook is loaded, but you can disregard them. The rest of the Datasource setup takes place in the Jupyter Notebook and we won't return to the terminal until that is done.

 - Great Expectations Version: [version 0.15.30]

**Comment by AFineDayFor** [comment]
howdy @Karaqz 👋 

can you share how you're declaring the path? is it full or relative? is the path name too long for py on the NT kernel?

can you share the full stack trace and configuration please?

**Comment by Karaqz** [comment]
@AFineDayFor 

I tried both full and relative. The path I used when trying it locally is only 14 chars so that can't be it I guess. 

I tried it both local as (following the tutorial) with git. Would love to share a stack trace and config but I have no idea how.

**Comment by talagluck** [comment]
Hi @Karaqz - I'm going to close this for now, but if you are still facing this and are able to share your config and full error stack trace, please feel free to ask this in our Slack.
