### ISSUE TITLE
Incorrect time within data_docs Run Time field - AEDT timezone

### ISSUE THREAD

**Issue by jstucken** [fivetran/great_expectations#6307]
**Describe the bug**
When data_docs run on an Australian Server (running Ubuntu 22.04), the display time within data_docs static html pages appear to be 11 hours ahead even though the time on the server is correct. 

I suspect this is related to Australian Eastern Daylight Time (AEDT) being 11 hours ahead of [Coordinated Universal Time](https://www.timeanddate.com/time/aboututc.html) (UTC).

**To Reproduce**
1. Use a Ubuntu server set to AEDT timezone
2. Run a simple test checkpoint, generating a new static **data_docs** html page as usual
3. Open the generated data_docs page in your browser (eg `great_expectations/uncommitted/data_docs/local_site/index.html`)
4. See the bug with the incorrect time of day (i.e. hour field) within the **Run Time** column.
5. This bug seems limited to the **hour** field, as the date and minute fields seem to match up to what is on the system and even the folder name created by Great Expectations itself (e.g. 20221107-**10**4457-my-run-name-template).

See screenshots below:

<img width="939" alt="data_docs1" src="https://user-images.githubusercontent.com/25559695/200204301-60bfd04e-78b1-450e-bb04-0be4c74b88cc.png">

<img width="640" alt="data_docs2" src="https://user-images.githubusercontent.com/25559695/200204305-8ab79c50-3319-4cc7-9a09-e7f3b585daf7.png">

**Expected behavior**
In the example highlighted above, one would expect the **Run Time** column to read **2022-11-07 10:32:42 AEDT** instead of **2022-11-07 21:32:42 AEDT**

**Environment (please complete the following information):**
 - Operating System: Ubuntu 22.04
 - Great Expectations Version: 0.15.28

**Additional context**
Thanks in advance for looking into this for us. We really appreciate all the work that goes into this excellent project. Even if you could point us towards the general direction where the code may reside for this functionality, our team could perhaps look at contributing a fix?

**Comment by austiezr** [comment]
Hey @jstucken ! Thanks for reaching out. We'll review this behavior internally and assess.

**Comment by puruzio** [comment]
Jeffrey Quinn on Slack found this issue before. and shared it with me.
If you change line 127 of checkpoint.py to this, (utcnow instead of now), it works as expected.

`run_time = run_time or datetime.datetime.utcnow()`

**Comment by jstucken** [comment]
Thanks @puruzio, this hack worked well :)

**Comment by austiezr** [comment]
Hey @jstucken & @puruzio ! Wanted to check in and let you know that this functionality is being addressed by the core team. No ETA as of now but we have eyes on it 🙇

**Comment by jstucken** [comment]
Thank you @austiezr. Appreciate what you guys do :)

**Comment by talagluck** [comment]
Resolved by #7244
