### ISSUE TITLE
Data Docs Relies on Images Hosted On AWS But Access Is Denied

### ISSUE THREAD

**Issue by jasonstinnett** [fivetran/great_expectations#6322]
**Describe the bug**
The default data docs HTML references two images hosted on AWS:
1. https://great-expectations-web-assets.s3.us-east-2.amazonaws.com/logo-long.png
2. https://great-expectations-web-assets.s3.us-east-2.amazonaws.com/full_logo_dark.png

Access is no longer available, therefore Great Expectations logos no longer show on data docs site pages. Instead there is a large blank area where the logos previously appeared.

**To Reproduce**
1. `great_expectations docs build`
2. Open any page on the data docs site
3. Observe that the logos no longer appear on the webpage
4. Attempt to access the images directly in a web browser & note access denied error message 

**Expected behavior**
Images load properly. Access is allowed because the software is built to rely on these web assets instead of local versions.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.15.2

**Additional context**
Seems to be a recent change.

**Comment by austiezr** [comment]
Hey @jasonstinnett ! Thanks for raising this; we'll assess internally and address soon. 🙇

**Comment by anthonyburdi** [comment]
Thanks for reporting @jasonstinnett! These should now be accessible. Please let us know if you have any further issues!

**Comment by jasonstinnett** [comment]
Confirming this looks good from my end as well, appreciate your help @austiezr @anthonyburdi !
