### ISSUE TITLE
Query is stuck when using runtime connector with Trino

### ISSUE THREAD

**Issue by itaise** [fivetran/great_expectations#6330]
Hi,
We are trying to use the **runtime** connector with **Trino** and there is an initial query that is stuck for a few minutes (about 3 -4 minutes) before tests start to run. 

This is the data connector configuration: 
```
 "default_runtime_data_connector_name": {
                    "class_name": "RuntimeDataConnector",
                    "batch_identifiers": ["query_string"]
            },
```

and the Batch request in the checkpoint: 

```
"batch_request": {
    "datasource_name": "wix_trino_datasource",
    "data_connector_name": "default_runtime_data_connector_name",
    "data_asset_name": "default_name",
    "runtime_parameters": {"query": f"SELECT * from my_table LIMIT 10"},
    "batch_identifiers": {"query_string": "whatever"},
},
```

According to @kenwade4  - The query is built in [this](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/expectations/metrics/util.py#L496-L577) part - it is running on information schema, before the expectations themselves started to run. 

can you please advise? The runtime connector with Trino will be super-useful to us :)
Thanks a lot!

**Expected behavior**
Initial query should not be "stuck" for a few minutes

**Environment (please complete the following information):**
- Operating System: MacOS
- SQLAlchemy 1.4.0
- Trino 0.317.0
- Great expectations -  0.15.31 (from the branch with the fix by @kenwade4) - 
git+https://github.com/great-expectations/great_expectations.git@dont-merge/trino-play

**Comment by austiezr** [comment]
Hey @itaise ! Thanks for reaching out and surfacing this. We'll review and investigate. 🙇

**Comment by itaise** [comment]
Update - when I edited the code manually and added a schema name to the query, it works as expected :) 
in the query below i added "data quality" condition - to [this part](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/expectations/metrics/util.py#L559)
The question is, from where should we take the schema name? the user need to supply it? 
In the debug mode, I see It is available in the sqlalchemy engine, in "default_schema" attribute. 

This code works as expected: 
```
col_info_query: Select = (
            sa.select(
                [
                    tables_table_query.c.schema_name,
                    tables_table_query.c.table_name,
                    columns_table_query.c.column_name,
                    columns_table_query.c.column_data_type,
                ]
            )
            .select_from(
                tables_table_query.join(
                    right=columns_table_query, onclause=conditions, isouter=False
                )
            )
            .where(sa.and_(*(tables_table_query.c.table_name == table_name,
                             tables_table_query.c.schema_name == 'data_quality'))) # I added this row
            .order_by(
                tables_table_query.c.schema_name.asc(),
                tables_table_query.c.table_name.asc(),
                columns_table_query.c.column_name.asc(),
            )
            .alias("column_info")
        )
col_info_tuples_list: List[tuple] = sqlalchemy_engine.execute(
            col_info_query
        ).fetchall()
```

**Comment by kenwade4** [comment]
https://github.com/great-expectations/great_expectations/pull/6350 should resolve
