### ISSUE TITLE
Hyperlinks in GCS (still) relative rather than absolute -> not working

### ISSUE THREAD

**Issue by morkunz** [fivetran/great_expectations#6344]
**Describe the bug**
As described in [this issue](https://github.com/great-expectations/great_expectations/issues/1528) over two years ago, the links in the index.html within Data Docs in a GCS bucket lead nowhere, because they are missing the prefix "https://_GCS stuff_". 

**To Reproduce**
Follow the steps in the older issue linked above (quintessence: Choose GCS for storing Data Docs

**Expected behavior**
Hyperlinks should work within a GCS bucket without an App Engine. 

**Environment (please complete the following information):**
GE is configured entirely in code in Google Cloud Functions, but that should not matter for the issue.

**Additional context**
I am trying to avoid using Google App Engine for different reasons. It would be nice to be given the option within GE to generate Data Docs for direct inspection in the GCS bucket, or perhaps get some handholding on how to change very small parts of the GE renderers rather than having to reimplement one "from scratch". The older issue linked above is still relevant, and perhaps GE's code now allows for an easier way to handle it.

**Comment by austiezr** [comment]
Hey @morkunz ! Thanks for bumping this. I'll be escalating this internally this week and be in touch as we begin to address.

**Comment by Patechoc** [comment]
I am just bumping this issue again, [identified in june 2020](https://github.com/great-expectations/great_expectations/issues/1528) and still present as is today.
Thanks for taking the time to look into it again

**Comment by prateekhavanur** [comment]
@morkunz ,Can you please let me know if it works with app engine in place?

**Comment by morkunz** [comment]
@prateekhavanur We are not using App Engine, but may in the future. Sorry, I can't test it quickly right now

**Comment by prateekhavanur** [comment]
I figured it out, sorry for the confusion. had made typo in the flask app while routing

**Comment by molliemarie** [comment]
Hello @morkunz. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
