### ISSUE TITLE
batch and batch_identifier become mismatched when concurrency is enabled

### ISSUE THREAD

**Issue by tommy-watts-depop** [fivetran/great_expectations#6346]
**Describe the bug**
When concurrency is enabled, during the validation operations the batch and batch_identifier become mismatched, leading to a key error when the datahub action tried to access the data asset.

They become decoupled [here](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/validation_operators/validation_operators.py#L341) during the asyncronous context.

**To Reproduce**
Enable concurrency and run for multiple validations, enable the datahub action.

**Additional context**
`  File "/Users/tommywatts/.pyenv/versions/great_expectations/lib/python3.8/site-packages/great_expectations/checkpoint/actions.py", line 72, in run
    return self._run(
  File "/Users/tommywatts/.pyenv/versions/great_expectations/lib/python3.8/site-packages/datahub/integrations/great_expectations/action.py", line 138, in _run
    datasets = self.get_dataset_partitions(batch_identifier, data_asset)
  File "/Users/tommywatts/.pyenv/versions/great_expectations/lib/python3.8/site-packages/datahub/integrations/great_expectations/action.py", line 633, in get_dataset_partitions
    query = data_asset.batches[
KeyError: 'bb6bbde9940312470e4817209b42949d'`

**Comment by austiezr** [comment]
Hey @tommy-watts-depop ! Thanks for raising this. I'll review and be in touch.

**Comment by tommy-watts-depop** [comment]
thanks @austiezr. 

FYI it looks like this works when max workers is set to 1 in the ThreadPoolExecutor and we only run with 1 thread

**Comment by tommy-watts-depop** [comment]
@austiezr any update on this?

**Comment by austiezr** [comment]
Hey @tommy-watts-depop ! Thanks for the ping and the further context. Still looking into behavior here, but I'll update you by midweek next week. 🙇

**Comment by tommy-watts-depop** [comment]
Thanks @austiezr

**Comment by tommy-watts-depop** [comment]
hi again @austiezr,

if you have any new findings at all for this issue would you mind sharing them? Happy to look into this too when i get time

Do you know why the ThreadPoolExecutor was chosen in this case? Is part of the GE run I/O bound ?

**Comment by tommy-watts-depop** [comment]
@austiezr i think the issue is [here](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/core/batch_manager.py#L162). Looks like with asynchronous runs the active batch id is always unchanged, so it looks like the AsyncResults always has the last batch in a group of batches set for batch spec and batch definition

**Comment by tommy-watts-depop** [comment]
@talagluck I think some possible solutions would be:

- to change the way the batches are cached so that the threads don't share the same batch during runs. We could have multiple active batches possibly?
- use a asyncio queue to manage which batches are active

**Comment by talagluck** [comment]
Thank you for the update, @tommy-watts-depop! Do you have a working example script you can share to help us troubleshoot? I've escalated to someone on the engineering team and we are working to replicate it now.

**Comment by tommy-watts-depop** [comment]
Hi @talagluck,

I have and example below. When you run this, you can see from the results that the batch_spec and active_batch_definition dictionaries are always the last table. If you look at the Batch Manager i think this is where the issue is. Please let me know if you need any more information !

```
import os

from great_expectations.data_context.data_context.base_data_context import BaseDataContext
from great_expectations.data_context.types.base import DataContextConfig, DatasourceConfig
from great_expectations.checkpoint import Checkpoint
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.core.expectation_configuration import ExpectationConfiguration


def generate_context() -> BaseDataContext:
    data_context_config = DataContextConfig(
        datasources={
            "redshift_depop": DatasourceConfig(
                class_name="Datasource",
                execution_engine={
                    "class_name": "SqlAlchemyExecutionEngine",
                    "create_temp_table": False,
                    "connection_string": os.environ.get("REDSHIFT_CONNECTION_STRING"),
                },
                data_connectors={
                    "runtime_data_connector": {
                        "class_name": "RuntimeDataConnector",
                        "batch_identifiers": ["filter"],
                        "name": "runtime_data_connector",
                    },
                },
            )
        },
        plugins_directory="depop_great_expectations/plugins/",
        stores={
            "expectations_store": {
                "class_name": "ExpectationsStore",
                "store_backend": {
                    "class_name": "InMemoryStoreBackend",
                },
            },
            "validations_store": {
                "class_name": "ValidationsStore",
                "store_backend": {
                    "class_name": "InMemoryStoreBackend",
                },
            },
            "evaluation_parameter_store": {
                "class_name": "EvaluationParameterStore",
                "store_backend": {
                    "class_name": "InMemoryStoreBackend",
                },
            },
        },
        expectations_store_name="expectations_store",
        validations_store_name="validations_store",
        evaluation_parameter_store_name="evaluation_parameter_store",
        anonymous_usage_statistics={"enabled": False},
        progress_bars={"globally": False},
        concurrency={"enabled": True}
    )
    return BaseDataContext(context_root_dir="./", project_config=data_context_config)


def get_validations(tables: list):
    return [
        {
            "batch_request": {
                "datasource_name": "redshift_depop",
                "data_asset_name": table,
                "runtime_parameters": {
                    "query": f"SELECT * FROM {table} WHERE date = '2023-02-01'",
                },
                "batch_identifiers": {"filter": "yesterday"},
                "data_connector_name": "runtime_data_connector",
            },
            "expectation_suite_name": f"{table}_suite",
        }
        for table in tables
    ]


tables = [
    "external.branch_cost_data",
    "external.branch_click_data",
    "external.branch_impression_data",
]
expectations = [
    {
        "expectation_type": "expect_column_values_to_not_be_null",
        "kwargs": {"column": "date"}}
]

context = generate_context()
validations = get_validations(tables)


for validation in validations:
    expectations_suite = context.create_expectation_suite(
        expectation_suite_name=validation["expectation_suite_name"],
        overwrite_existing=True,
    )
    expectations_suite.add_citation(
        comment="auto",
        batch_request=RuntimeBatchRequest(**validation["batch_request"]),
    )

    validator = context.get_validator(
        batch_request=RuntimeBatchRequest(**validation["batch_request"]),
        expectation_suite_name=validation["expectation_suite_name"],
    )
    validator.expectation_suite = expectations_suite
    for expectation in expectations:
        validator.append_expectation(
            expectation_config=ExpectationConfiguration(
                expectation_type=expectation["expectation_type"],
                kwargs=expectation["kwargs"],
            ),
        )

    validator.save_expectation_suite(discard_failed_expectations=False)

checkpoint = Checkpoint(
    data_context=context,
    name="test",
    expectation_suite_name="test",
    config_version=1.0,
    action_list=[
        {
            "name": "store_validation",
            "action": {
                "class_name": "StoreValidationResultAction",
            },
        }
    ],
    validations=validations,
    run_name_template="test",
)

results = checkpoint.run()

print(results)

```

**Comment by talagluck** [comment]
Hi @tommy-watts-depop - I'm going to close this for now since it's a tough one to reproduce and we won't be able to prioritize work on it in the immediate future. That said, if you are able to make a contribution here, please feel free to re-open and let us know. Thanks!

**Comment by Cage89** [comment]
This is still an issue and not mentioned anywhere in the documentation, so is concurrency supported or not?

**Comment by tommy-watts-depop** [comment]
@ca9071jp2 i don't believe it works correctly
