### ISSUE TITLE
unexpected_index_list on Spark

### ISSUE THREAD

**Issue by paulofelipe84** [fivetran/great_expectations#6359]
Based on the discussion started on [this closed issue](https://github.com/great-expectations/great_expectations/issues/929), I would like to bring back the request for support to row indices in `unexpected_index_list` when using Spark data frames. Perhaps a way of pointing out an index column that would then be used to generate the list.

In my current use case, we want to use the list of indices to flag the individual rows that have not passed validation in a dataset that would then be exposed to stakeholders.

**Comment by talagluck** [comment]
Hi @paulofelipe84 - thanks for raising. This is duplicative of the Issue here: https://github.com/great-expectations/great_expectations/issues/3195, which is currently being worked on. I'm going to close this for now, but if you have additional context, please feel free to add it in #3195.
