### ISSUE TITLE
SparkDF can't compute mean for decimal column

### ISSUE THREAD

**Issue by rogalski** [fivetran/great_expectations#6393]
**Describe the bug**
https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/dataset/sparkdf_dataset.py#L646
Decimal type fails explicitly, yet Spark is fully capable of computing mean of decimal typed column.

**To Reproduce**
1. Create parquet with decimal type
2. Run `expect_column_mean_to_be_between` expectations using Spark
3. Encounter exception

**Expected behavior**
- Exception should not happen, as Spark is capable of computing mean of such column.
- If exception is raised, it should explicitly mean the offending column type so that feedback to user is self-explainatory

**Environment (please complete the following information):**
- N/A, affects code in develop

**Additional context**
N/A

**Comment by austiezr** [comment]
Hey @rogalski ! Thanks for raising this. I've been able to reproduce this behavior, and will discuss with the team in the coming week. If you're interested in making a contribution to resolve this bug, we would be happy to provide review and guidance.
