### ISSUE TITLE
row_condition counts mismatch in Spark

### ISSUE THREAD

**Issue by sachinwadhwa** [fivetran/great_expectations#6416]
**Describe the bug**
I got this working for Spark dataset but element_count, unexpected_value and other counts shows for full dataset counts rather than filtered. 

```
{
    "expectation_type": "expect_column_values_to_match_regex",
    "kwargs": {
        "column": "name_first",
        "regex": "^((?![0-9]).)*$",
        "condition_parser": "great_expectations__experimental__",
        "row_condition ": "col(\"country_code\")==\"UK\""
    },
    "meta": {}
}

```

**To Reproduce**
~30 million rows in total, ~10 million are for country_code "UK".
output shows:
```
       "results": [
          {
            "result": {
              "element_count": 31367304,
              "unexpected_count": 8436,
              "unexpected_percent": 0.02690221303867608,
              "partial_unexpected_list": [
```

**Expected behavior**
element count to show: 10830896 
and other count must be reflective accordingly. 

**Additional context**
Using Spark Dataframe in Databrick environment (Spark 3.x)
Great Expectations Version: 0.15.34

**Comment by austiezr** [comment]
Hey @sachinwadhwa ! Thanks for reaching out. 

If you instead pass your `row_condition` with `===` as opposed to `==`, does behavior change at all?

**Comment by KHerashchenko** [comment]
@austiezr I am facing the same issue and tried === instead ==. It does not change behavior.

**Comment by KHerashchenko** [comment]
Additional context
Using SQLAlchemy in Snowflake
Great Expectations Version: 0.15.41

**Comment by talagluck** [comment]
Thank you @sachinwadhwa and @KHerashchenko and apologies for delays. Can you please share your datasource configurations, taking care to remove any sensitive information?
