### ISSUE TITLE
Presto: error: (builtins.ValueError) Protocol must be https when passing a password 

### ISSUE THREAD

**Issue by FreyaDingDing** [fivetran/great_expectations#6428]
**Describe the bug**
I try to connect prestoSql and getting error saying protocol need to be set. However I have set it in connect_args. 
I tried by python code locally and it actually works. suspect the args is not taken

**To Reproduce**
my config args is : 
datasource_config = {
    "name": "my_datasource",
    "class_name": "Datasource",
    "execution_engine": {
        "class_name": "SqlAlchemyExecutionEngine",
        "connection_string": "presto://username:password@host:port/hive/schema",
        "connect_args": {
            'protocol': 'https',
            'requests_kwargs': {'verify': False}
        }
    },
    "data_connectors": {
        "default_runtime_data_connector_name": {
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": ["default_identifier_name"],
        },
        "default_inferred_data_connector_name": {
            "class_name": "InferredAssetSqlDataConnector",
            "include_schema_name": True,
        },
    },
}

**Expected behavior**
the config_args should be taken.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: [0.15.34]
 - python
      pyhive | 0.6.5 |  
      presto-python-client | 0.8.3 |  
      sqlalchemy | 1.4.44 |  

**Additional context**
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/46193284/203721564-5d29fffd-933e-4fa1-8a84-fd9e976a6aaa.png">

**Comment by austiezr** [comment]
Hey @FreyaDingDing ! Thanks for reaching out. Great Expectations does not offer official support for Presto, so this may not be possible at this time. 

However, you may be able to pass the necessary parameters through [`kwargs`](https://github.com/great-expectations/great_expectations/blob/fd621f265c7afb26e9d9de864291cb059ce9a693/great_expectations/execution_engine/sqlalchemy_execution_engine.py#L267); this allows you to pass directly through to the SQLAlchemy engine.

As we don't currently support Presto and will not be able to prioritize work in this area at this time, I'm closing this issue out for now. If you're interested in contributing to the codebase in this area, please feel free to reach out and we'll be happy to provide review and guidance on the process.

**Comment by FreyaDingDing** [comment]
hi @austiezr  thanks for you reply. We will try by following your suggestion using kwargs.

**Comment by FreyaDingDing** [comment]
@austiezr  regarding reworking on the codebase, which files do we should focus on? could you please help give some advice? Thanks a lot!

**Comment by FreyaDingDing** [comment]
hi @austiezr , I tried to pass the parameters but not sure I did it in a right way? Could you help give some suggestions?
````
datasource_config = {
    "name": "my_datasource",
    "class_name": "Datasource",
    "execution_engine": {
        "class_name": "SqlAlchemyExecutionEngine",
        "connection_string": "presto://username:password@host:port/hive/schema",
    },
   "protocol": "https",  --> is this where kwargs should be?
    "data_connectors": {
        "default_runtime_data_connector_name": {
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": ["default_identifier_name"],
        },
        "default_inferred_data_connector_name": {
            "class_name": "InferredAssetSqlDataConnector",
            "include_schema_name": True,
        },
    },
}
````
