### ISSUE TITLE
include_unexpected_rows not working for Spark

### ISSUE THREAD

**Issue by jmcorreia** [fivetran/great_expectations#6430]
**Describe the bug**
I wanted to clearly identify the row that is failing an expectation and I got to know that I could achieve this by using 'include_unexpected_rows' in the expectation or checkpoint. https://docs.greatexpectations.io/docs/reference/expectations/result_format/#expectation-level-config 
However, when I am using this property, I get no difference in the return of the results.
Is there any limitation of this feature for spark?

**To Reproduce**
I am trying to use result_format complete and include_unexpected_rows, without success. I tried it for both expectations below.
expect_column_values_to_be_in_set
expect_column_values_to_not_be_null

**Expected behavior**
Return the complete row that failed the expectation. Either that or someway making it possible to identify the problematic row.

**Environment (please complete the following information):**
 - Operating System: Databricks, Spark
 - Version: 0.15.34

**Comment by talagluck** [comment]
Hi @jmcorreia - thanks for raising this. The docs here are somewhat misleading. Though it is possible to specify `result_format` at the Expectation level, this will currently only be properly handled at the Expectation level during that initial stage of adding the Expectation to the validator. The `result_format` directive will not otherwise be respected during Checkpoint validation.

This is a known gap in functionality that we hope to address in the not-too-distant future, but it will require some design work and is not a simple bugfix. I'm going to update the docs here to be clearer about that, and once I do that, I'll close this issue since it is not a straightforward bugfix, and we are already tracking this work internally. If you have any additional thoughts here, please don't hesitate to reach out. Thanks!

**Comment by jmcorreia** [comment]
Hi @talagluck thank you for your reply. Even at the checkpoint level, this is not working for me. Moreover, according to other community member on slack, this was also not working for them and they were forced to change to pandas, instead of Spark.

**Comment by talagluck** [comment]
Hi @jmcorreia - how are you specifying this at the Checkpoint level?

**Comment by jmcorreia** [comment]
Hi @talagluck, as stated in the documentation 
![image](https://user-images.githubusercontent.com/11615737/205660248-7b46a253-48cd-4f59-89e4-c4b8ca4c7c7b.png).

**Comment by talagluck** [comment]
Hi @jmcorreia - could you please share your Checkpoint config here?

If you pass `result_format` into the call to `run_checkpoint`, does this work for you?

**Comment by jmcorreia** [comment]
Hi @talagluck , sorry for the delay.
This is one of my trials 
![image](https://user-images.githubusercontent.com/11615737/209699092-f432d4d6-4727-4b3a-9875-63cb35b1a453.png)
and the output does not show the unexpected rows. 
This is what I see:
![image](https://user-images.githubusercontent.com/11615737/209699206-00ac2e56-61b1-4d4a-982e-c1b2ef3c6fab.png)
![image](https://user-images.githubusercontent.com/11615737/209699222-d65cb7fb-65bf-44c4-9259-7a5757c39894.png)
![image](https://user-images.githubusercontent.com/11615737/209699240-c5397f86-c503-402f-ae54-2126eabb0f4c.png)
![image](https://user-images.githubusercontent.com/11615737/209699259-c38dad77-3ac7-4a78-a026-ff18e90f05c2.png)

Am I missing something?

**Comment by jmcorreia** [comment]
@talagluck with this config I was now able to see the unexpected_rows. 
![image](https://user-images.githubusercontent.com/11615737/209706703-dbfe1c15-8188-4e85-9cde-89fcb33ff1b0.png)

However, those come only with the values, not with the schema. Is this the intended behaviour? Anyway I can configure to return the schema as well? For pandas it comes with the schema.

I am getting this 
![image](https://user-images.githubusercontent.com/11615737/209707175-5f4fc7cc-765f-4738-a6d8-ab963d608ef4.png)


instead of this 
![image](https://user-images.githubusercontent.com/11615737/209707033-d0ba67e3-c42c-42ea-b876-9505f4f1a153.png)

**Comment by talagluck** [comment]
Hi @jmcorreia - I'm glad you were able to get this to work. I'm surprised by this. Does the Spark table you are referencing have column names?

**Comment by data-han** [comment]
What was the change? Just changing to SUMMARY and only leaving 1 set of param?

Is it possible to publish these 'unexpected rows' on data doc?

**Comment by jmcorreia** [comment]
Hi @talagluck, sorry for the delay. Coming back to this, the dataframe has schema as you can see in the screenshot 
![image](https://user-images.githubusercontent.com/11615737/213466602-68bfc7f5-f60c-4e87-b4a0-c2667952f831.png).
Moreover, I tried now with the latest ID/PK feature and I am able to get data with schema like below: 
![image](https://user-images.githubusercontent.com/11615737/213466796-42b9dc64-8f27-4226-a7b2-3595490fcba6.png).

I will most likely go with ID/PK approach, but any idea what may be affecting the other one? Any bug or anything on my side?

**Comment by talagluck** [comment]
Hi @jmcorreia - it seems like this issue has expanded quite a lot, and I know we've chatted in Slack about this a bit as well, so I'm going to close this for now, but please feel free to open a new issue if you have additional questions or trouble with the feature. Thanks again for raising!

@data-han `unexpected_rows` won't be in Data Docs, but you can include `unexpected_index_query` as described in our docs.

**Comment by pavel-henrykhsen** [comment]
If you add all columns from your Spark DataFrame as `unexpected_index_column_names`, you will get unexpected rows in the `unexpected_index_list`
```python
            "unexpected_index_column_names": df.schema.names,
```
