### ISSUE TITLE
Checkpoints attempt to build data docs into s3, even if using local store

### ISSUE THREAD

**Issue by PSUlion16** [fivetran/great_expectations#6441]
**Describe the bug**
When executing **ge_context.run_checkpoint(checkpoint_name=checkpoint_name)**, great expectations attempts to authenticate to s3, raising an authentication error. This occurs even when using a local store. It seems as if great_expectations is trying to authenticate with AWS thru botocore regardless of if we tell it to or not.

When we run a checkpoint against a postgre datasource, the error is raised and validation results DO populate locally.

When we run a checkpoint against an s3 datasource, the error is raised and validation results DO NOT populate locally.

When we create a checkpoint against EITHER datasource (s3/postgre) no error is given.

This is run in a flask context.

**To Reproduce**

1. Define an postgre datasource ( we use minio locally through docker)
![image](https://user-images.githubusercontent.com/24613077/204368036-aeb6d20a-9816-4980-b06a-df39592bca48.png)

2. Define a s3datasource (we use postgre locally through docker)
![image](https://user-images.githubusercontent.com/24613077/204368115-a7038788-1837-430f-a2b6-c38c7c31d127.png)

3. Define a simple suite and expectations for both
4. Create checkpoints for both suites (PG / S3 checkpoints shown below, respectively)

![image](https://user-images.githubusercontent.com/24613077/204367901-0179598d-0637-4742-85ed-169d4765b3a7.png)
![image](https://user-images.githubusercontent.com/24613077/204367967-2901255f-d43f-4941-9b0e-dbef67eb78cc.png)

5. Run the checkpoints to show error - trace is attached

[error_trace_GE.txt](https://github.com/great-expectations/great_expectations/files/10106977/error_trace_GE.txt)

**Expected behavior**

When defining a datasource with no sites associated, we would expect our validations to populate to the local site, with no error given.

**Environment (please complete the following information):**
 - Operating System: IntelliJ

 - Framework: Flask
 - Python Version: 3.8+ (replicated on 3.8 and 3.11)
 - Great Expectations Version: 0.15.26

**Additional context**
It is important to note that we DID have an extra site defined within the great_expectations.yml, which even removed and despite having an empty list on the action, still attempts to auth to s3 for a s3 datasource:

![image](https://user-images.githubusercontent.com/24613077/204390469-f094a527-ad04-4d87-9d6e-ac69851f8d57.png)

It seems like specifying 'site_names' as a key, along with a list of sites within the action operator always creates this configuration above. Manually updating the configuration to 'site_names: - local_site' also does not have an effect.

**Comment by austiezr** [comment]
Hey @PSUlion16 ! Thanks for raising this. Looks to be related to #5899; the core team has taken this work under planning. 🙇

**Comment by PSUlion16** [comment]
@austiezr -- Make sure the core team pays attention to my note on the "site_names" key when allocating a checkpoint. Also, I put this above but we only get this exception when we run the checkpoint, not when creating it. We used to get an error when creating, but I think it was user error.

**Comment by cdkini** [comment]
@PSUlion16, thanks for your patience here!

The issue here is that we evaluate the entire config greedily instead of lazily based on what we actually need. As such, any references to AWS elsewhere in your config will get evaluated even in a local context.

The workaround here for the time being is to comment out any AWS/S3 configuration so we don't request `boto` during local site development.

Going to x-post a comment I made in another issue: https://github.com/great-expectations/great_expectations/issues/5899#issuecomment-1372732849

**Comment by PSUlion16** [comment]
@cdkini - I know you gave a workaround, but In our configuration from a datasource and checkpoint perspective, we do not have any ${VARIABLE} references to AWS. The only thing we substitute on the datasource for s3, are our boto3 options so we can connect to our s3 repo - see the following on how we have our local container boto3 options set up:

"boto3_options": {
						"aws_access_key_id": "admin",
						"aws_secret_access_key": "adminpassword",
						"endpoint_url": "http://localhost:9001"
					}

I've also checked the GE yaml, and we only have a local site defined. We have no issue making the checkpoint, only running validations using this checkpoint with the error:

![image](https://user-images.githubusercontent.com/24613077/213267202-62571fe2-56d2-4ac8-a5f5-806e8bea7c84.png)

Here is a snapshot of our s3 checkpoint:
![image](https://user-images.githubusercontent.com/24613077/213267035-b7064ef1-7940-4d79-beb2-5ca284767833.png)
