### ISSUE TITLE
[BUG] Expectations Raise "The column "xxx" in BatchData does not exist" Error

### ISSUE THREAD

**Issue by zhangchi1** [fivetran/great_expectations#6461]
**Describe the bug**
Hi team, we are working on integrating GX with snowflake datasource into our data validation system via GreatExpectations Version: 0.15.34.

We are planning to batch-run 3 expectations validation against a snowflake table named test_table. However, we got 
`Error The column "my_column" in BatchData does not exist`
for expectations **expect_column_values_to_not_be_null** and **expect_column_values_to_be_between**. 
However, expectation **expect_column_distinct_values_to_be_in_set**  worked as expected.    

> Detailed Error Msg: 
```
great_expectations.exceptions.exceptions.MetricResolutionError: Error: The column "my_column" in BatchData does not exist.
```

Does anyone know what the issue could be? Or is there any configuration issue in my expectation_suite, data_context_config, or checkpoint_config? Any help would be greatly appreciated ~~

**To Reproduce**
1. expectation_suite: 
```
{
  "data_asset_type": null,
  "expectation_suite_name": "test_table.demo",
  "expectations": [
    {
      "expectation_context": {
        "description": null
      },
      "expectation_type": "expect_column_values_to_not_be_null",
      "ge_cloud_id": null,
      "kwargs": {
        "column": "my_column"
      },
      "meta": {}
    },
    {
      "expectation_context": {
        "description": null
      },
      "expectation_type": "expect_column_distinct_values_to_be_in_set",
      "ge_cloud_id": null,
      "kwargs": {
        "column": "my_column",
        "value_set": [
          1,
          2,
          4
        ]
      },
      "meta": {}
    },
    {
      "expectation_context": {
        "description": null
      },
      "expectation_type": "expect_column_values_to_be_between",
      "ge_cloud_id": null,
      "kwargs": {
        "column": "my_column",
        "max_value": 6,
        "min_value": 1
      },
      "meta": {}
    }
  ],
  "ge_cloud_id": null,
  "meta": {
    "great_expectations_version": "0.15.34"
  }
}

```

**Expected behavior**
Expectations **expect_column_values_to_not_be_null** and **expect_column_values_to_be_between** should be able to find the column in batch data

**Environment (please complete the following information):**
 - Operating System: MacOS 
 - Great Expectations Version: 0.15.34
 - Python: 3.7

**Comment by austiezr** [comment]
Hey @zhangchi1 ! Thanks for raising this; definitely some unexpected behavior! Are you able to share your `great_expectations.yml`? That will help us to better diagnose what may be happening here.

Just to clarify, all three of theses expectations are being set against the same column?

**Comment by zhangchi1** [comment]
hi @austiezr, yes all 3 expectations are being set against a column called "my_column".

**Comment by zhangchi1** [comment]
and @austiezr, we are running it as a batch job. Here are our configs

1. DatasourceConfig
```
sf_datasource = DatasourceConfig(class_name="Datasource",
                                 execution_engine={
            "class_name": "SqlAlchemyExecutionEngine",
            "connection_string": sf_url,
        },
                                 data_connectors={
            "default_configured_asset_data_connector_name": {
                "module_name": "great_expectations.datasource.data_connector",
                "class_name": "ConfiguredAssetSqlDataConnector",
                "assets": {
                        f"{data_asset_name}": {
                            "module_name": "great_expectations.datasource.data_connector.asset",
                            "class_name": "Asset",
                            "schema_name": f"{schema}",
                            "batch_identifiers": {
        "some_key_maybe_pipeline_stage": "ingestion step 1",
        "some_other_key_maybe_airflow_run_id": "run 18",
    },
                        },
                    },
            },
        })
```
2. DataContextConfig
```
sf_data_context = DataContextConfig(
    config_version=3.0,
    datasources={"my_snowflake_datasource": sf_datasource},
    stores={
            "expectations_store": {
                "class_name": "ExpectationsStore",
                "store_backend": {
                    "class_name": "TupleFilesystemStoreBackend",
                    "base_directory": os.path.join(ge_root_dir, "expectations"),
                },
            },
            "validations_store": {
                "class_name": "ValidationsStore",
                "store_backend": {
                    "class_name": "TupleFilesystemStoreBackend",
                    "base_directory": os.path.join(
                        ge_root_dir, "uncommitted", "validations"
                    ),
                },
            },
            "evaluation_parameter_store": {"class_name": "EvaluationParameterStore"},
            "checkpoint_store": {
                "class_name": "CheckpointStore",
                "store_backend": {
                    "class_name": "TupleFilesystemStoreBackend",
                    "suppress_store_backend_id": True,
                    "base_directory": os.path.join(ge_root_dir, "checkpoints"),
                },
            },
        },
    expectations_store_name="expectations_store",
    validations_store_name="validations_store",
    evaluation_parameter_store_name="evaluation_parameter_store",
    checkpoint_store_name="checkpoint_store",
    data_docs_sites={
            "local_site": {
                "class_name": "SiteBuilder",
                "show_how_to_buttons": True,
                "store_backend": {
                    "class_name": "TupleFilesystemStoreBackend",
                    "base_directory": os.path.join(
                        ge_root_dir, "uncommitted", "data_docs", "local_site"
                    ),
                },
                "site_index_builder": {"class_name": "DefaultSiteIndexBuilder"},
            }
        },
    anonymous_usage_statistics={
            "data_context_id": "abcdabcd-1111-2222-3333-abcdabcdabcd",
            "enabled": True,
        },
    notebooks=None,
    concurrency={"enabled": False}
                                    )
```

3. BasesDataContext
```
context = BaseDataContext(project_config=sf_data_context)

```
4. Checkpoint
```

sf_checkpoint = Checkpoint(data_context=context, **{
        "name": f"{table}_checkpoint",
        "config_version": 1.0,
        "template_name": None,
        "run_name_template": f"%Y%m%d-%H%M%S-{table}-checkpoint",
        "expectation_suite_name": f"{table}.demo",
        "action_list": [
            {
                "name": "store_validation_result",
                "action": {"class_name": "StoreValidationResultAction"},
            },
            {
                "name": "store_evaluation_params",
                "action": {"class_name": "StoreEvaluationParametersAction"},
            },
            {
                "name": "update_data_docs",
                "action": {"class_name": "UpdateDataDocsAction", "site_names": []},
            },
        ],
        "evaluation_parameters": {},
        "runtime_configuration": {},
        "validations": [
            {

                "batch_request": {
                    "datasource_name": "my_snowflake_datasource",
                    "data_connector_name": "default_configured_asset_data_connector_name",
                    "data_asset_name": table,
                    # "data_connector_query": {"index": -1},
                },
            }
        ]
    })
```

5. Run the checkpoint as a batch job
```
results = sf_checkpoint.run()

```

**Comment by mb4828** [comment]
I'm having the same issue. Happy to provide another set of test data if needed. Interestingly, it only happens with some data files and not with others, so it could be non-deterministic or some kind of race condition

**Comment by zhangchi1** [comment]
> I'm having the same issue. Happy to provide another set of test data if needed. Interestingly, it only happens with some data files and not with others, so it could be non-deterministic or some kind of race condition

Hi I'm wondering what datasource are you using? Are you also facing the same issue with snowflake tables?

**Comment by mb4828** [comment]
> Hi I'm wondering what datasource are you using? Are you also facing the same issue with snowflake tables?

We're using InferredAssetFilesystemDataConnector to read csv files from our filesystem. I don't think it's related to the datasource

**Comment by zhangchi1** [comment]
Hi @austiezr, I want to follow up on this thread and wondering if you have any updates on this issue? I saw that we recently released a new version 0.15.36, does the latest release resolve the above issue? Thanks,

**Comment by austiezr** [comment]
Hey @mb4828! Are you able to share a sample of your failing data that we could test? Additionally, are you able to share the expectations experiencing this behavior? That will help us to better diagnose what may be happening.

@zhangchi1 Investigation is ongoing! We'll update here as needed.

**Comment by mb4828** [comment]
@austiezr 

> Hey @mb4828! Are you able to share a sample of your failing data that we could test? Additionally, are you able to share the expectations experiencing this behavior? That will help us to better diagnose what may be happening.

data.csv
```
"POS_DATE","PORTFOLIO_ID","CLIENT_ID","POS_CUR_PAR","MKT_VALUE_BASE","MKT_VALUE_LOCAL","WEIGHT","FX_COUNTER_QUANTITY","POS_ID","FREQUENCY"
"2022-02-28","ABC","DEF","1","1","","","","","M"
"2022-02-28","ABC","DEF","2","2","","","","","M"
"2022-02-28","ABC","DEF","3","3","","","","","M"
"2022-02-28","ABC","DEF","4","4","","","","","M"
"2022-02-28","ABC","DEF","5","5","","","","","M"
"2022-02-28","ABC","DEF","6","6","","","","","M"
"2022-02-28","ABC","DEF","7","7","","","","","M"
"2022-02-28","ABC","DEF","8","8","","","","","M"
"2022-02-28","ABC","DEF","9","9","","","","","M"

```

suite.json
```
{
  "data_asset_type": null,
  "expectation_suite_name": "TEST_SUITE",
  "expectations": [
    {
      "expectation_type": "expect_table_row_count_to_be_between",
      "kwargs": {
        "min_value": 1
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_to_exist",
      "kwargs": {
        "column": "POS_DATE"
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "POS_DATE"
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_values_to_match_regex",
      "kwargs": {
        "column": "POS_DATE",
        "regex": "\\d{4}-\\d{2}-\\d{2}"
      },
      "meta": {}
    }
  ],
  "meta": {
    "great_expectations_version": "0.15.26"
  }
}

```

Result:
![Screen Shot 2022-12-07 at 1 17 24 PM](https://user-images.githubusercontent.com/5355770/206264015-35231ea9-64e7-46ba-b83a-a1f5726b1373.png)

Strangely, it's only this file. Other files with the exact same schema work just fine

**Comment by joarobles** [comment]
I'm having the same issue, a workaround that worked for me was to set the `column` name in lowercase, even if it was originally named in uppercase

**Comment by zhangchi1** [comment]
> I'm having the same issue, a workaround that worked for me was to set the `column` name in lowercase, even if it was originally named in uppercase

thanks for sharing your info @joarobles . Just want to be clear that when you said `set the column name in lowercase`, you were talking about the expectation suite
```
"kwargs": {
        "column": "POS_DATE"
      },
```
but not the column name in the original table? In addition, are you using Snowflake tables as your `datasource`?

**Comment by joarobles** [comment]
Indeed @zhangchi1, also changing the column name in the original Snowflake table makes no difference to the expectation error

**Comment by joarobles** [comment]
this is now solved by [#6951](https://github.com/great-expectations/great_expectations/pull/6951)

**Comment by austiezr** [comment]
Closing as resolved by #6951 🚀

**Comment by tkaklam** [comment]
I know this is closed, but I am now facing exactly the same problem with all lower_key column names in both the data source and the gx config.

**Comment by joarobles** [comment]
@tkaklam I've seen in the Changelog that this seems to be solved in the latest versions of GX, on the other hand we ended up converting all case to upper by code

**Comment by FreyaDingDing** [comment]
hi @joarobles  I still got this issue on version 0.18.3 when use query asset to get batch request.  When I print validator.head() I could see the column, however once add validate rule e.g. validator.expect_column_values_to_not_be_null(column="my_column") then it will throw out error no such column "The column "my_column" in BatchData does not exist."
`  query_name = "select * from my_table" 
trino_datasource.add_query_asset(name=asset_name, query=query_name)
my_asset = data_context.get_datasource("trino").get_asset(asset_name)
batch_request = my_asset.build_batch_request()
expectation_suite_name = "test_column_not_null"
 data_context.add_or_update_expectation_suite(expectation_suite_name=expectation_suite_name)
validator = data_context.get_validator(batch_request=batch_request, expectation_suite_name=expectation_suite_name)
validator.expect_column_values_to_not_be_null(column="my_column")`

**Comment by resleal** [comment]
I'm still getting this error when using trino.

**Comment by tomerdgani** [comment]
We got this error using Trino. 
In our case - the fix was simply using just the table-name in the query, instead of <catalog>.<schema>.<table-name>  (though I'd expect this to work, too).
