### ISSUE TITLE
JSON5 support

### ISSUE THREAD

**Issue by azban** [fivetran/great_expectations#6462]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to add comments to expectation suites. For example, it would be nice to add context, links, etc. to specific values or expectations.

**Describe the solution you'd like**
Look for `.json5` extensions as well as `.json` extensions for expectation files. A JSON5 parser like https://github.com/Kijewski/pyjson5 could be used to parse both, or you could only use that if you detect JSON5 by file extension.

**Describe alternatives you've considered**
I'm guessing the decision to not allow YAML expectations was intentional, so I haven't given much thought on switching to that.

I'm happy to take a stab at this if this sounds like something y'all would be wiling to merge. Cheers.

**Comment by austiezr** [comment]
Hey @azban ! Thanks for raising this.

We'll discuss the potential for json5 support internally in the coming week; if so, we'd be happy to support a contribution in this area.

Additionally, you may be interested in [this functionality](https://docs.greatexpectations.io/docs/reference/expectations/standard_arguments/#meta) for expectations if you aren't already familiar.

**Comment by azban** [comment]
Sweet!

Thanks for sending the info about the "meta" argument. That's got the added benefit of storing it with the result, and probably suits my needs for now (maybe better than my suggesiton).

But may be nice to have lighter weight comments to, or there may be another use-case that I'm not thinking of.

**Comment by austiezr** [comment]
🙌 

If `meta` suits your needs, I'll close this issue out for now. After we discuss JSON5 internally, I'll bump this space as needed.
