### ISSUE TITLE
Reading Partitioned Parquets for Pandas DataFrames

### ISSUE THREAD

**Issue by AlbertUlysses** [fivetran/great_expectations#6483]
**Is your feature request related to a problem? Please describe.**
Partitioned parquets are an efficient way to store data and are commonly used in Spark. However, it would be nice not to use Spark anytime we need to read a partitioned dataset, as the resources necessary are sometimes not warranted. Additionally - Pandas, the library, has decided not to natively support partitioned parquets since other libraries support Partitioned parquets and return Pandas DataFrames.

**Describe the solution you'd like**
Let's consider reading partitioned parquets as the default way to read parquet files in Great Expectations. From the looks of it - it seems like S3fs is already in other parts of the library, and there might need to be some tweaks to the Pandas reader.

**Describe alternatives you've considered**
An alternate solution is to read the parquets with an external library and pass them into Great Expectations using the DataFrame option. If this option is selected, I suggest adding this in the documentation as the preferred way to read partitioned parquets into Great Expectations - to help future users.

**Additional context**
First, thanks for considering this, and I look forward to hearing feedback!
Secondly, I will be more than happy to provide my help as a contributor to add this functionality.

**Comment by austiezr** [comment]
Hey @AlbertUlysses! Thanks for raising this. We'll be discussing this internally this week; great to hear that you're open to contribution!

**Comment by alexsherstinsky** [comment]
Hi @AlbertUlysses -- have you made any progress toward the contribution you offered?  Please let us know.  Thank you.

**Comment by AlbertUlysses** [comment]
Hi @alexsherstinsky I was waiting on confirmation from GE team - if they are interested in a contribution I can work on it 👍

**Comment by tyler-hoffman** [comment]
Hi @AlbertUlysses , that would be awesome if you are willing to be a contributor on this. Please let us know if there's anything you need from us!

**Comment by austiezr** [comment]
Hey @AlbertUlysses! We've captured this for our internal backlog -- if you're still interested in contributing on this, feel free to let us know on this issue! 🙇
