### ISSUE TITLE
Package conflict with Airflow - jsonschema

### ISSUE THREAD

**Issue by itaise** [fivetran/great_expectations#6485]
Hi,
We are trying to install Great expectations along with Airflow, and getting a package conflict.

Since the addition of AWS glue catalog [PR](https://github.com/great-expectations/great_expectations/pull/5123), there is a requirement for jsonschema<=4.7.2 and >=2.5.1. 

But - in Airflow there is a constraint which is conflicting, for example: 
airflow 2.5.0 - jsonschema==4.17.3  (https://raw.githubusercontent.com/apache/airflow/constraints-2.5.0/constraints-3.7.txt)
airflow 2.4.0 - jsonschema==4.16.0 
airflow 2.3.4 - jsonschema==4.13.0

The conflict starts since airflow 2.3.4  an on, and great expectations 0.15.29 and on. 

Is it possible to change the upper bound of the jsonschema requirement? 

Thanks a lot!

**Comment by austiezr** [comment]
Hey @itaise! Thanks for raising this. We'll review this over the coming week. 🙇

**Comment by talagluck** [comment]
Resolved by #6495
