### ISSUE TITLE
MetricResolutionError when validating on Azure Synapse

### ISSUE THREAD

**Issue by pfuerste** [fivetran/great_expectations#6493]
**Describe the bug**
A RuntimeBatchRequest getting data from a Azure Synapse gets the data (validator.head() shows it),  but when used in a checkpoint throws the error below. Running checkpoints on another datasource (from Azure blob storage) works.

```
Traceback (most recent call last):\n  File \"/home/philip/miniconda3/envs/beopt/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py\", line 407, in resolve_metrics\n    resolved_metrics[metric_to_resolve.id] = metric_fn(\n  File \"/home/philip/miniconda3/envs/beopt/lib/python3.8/site-packages/great_expectations/expectations/metrics/metric_provider.py\", line 34, in inner_func\n    return metric_fn(*args, **kwargs)\n  File \"/home/philip/miniconda3/envs/beopt/lib/python3.8/site-packages/great_expectations/expectations/metrics/table_metrics/table_columns.py\", line 47, in _sqlalchemy\n    return [col[\"name\"] for col in column_metadata]\nTypeError: 'NoneType' object is not iterable\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/philip/miniconda3/envs/beopt/lib/python3.8/site-packages/great_expectations/validator/validation_graph.py\", line 268, in _resolve\n    self._execution_engine.resolve_metrics(\n  File \"/home/philip/miniconda3/envs/beopt/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py\", line 411, in resolve_metrics\n    raise ge_exceptions.MetricResolutionError(\ngreat_expectations.exceptions.exceptions.MetricResolutionError: 'NoneType' object is not iterable\n",
              "exception_message": "'NoneType' object is not iterable
```

**To Reproduce**
Datasource:

```
synapse_config = {
    "name": "synapse_datasource",
    "class_name": "Datasource",
    "module_name": "great_expectations.datasource",
    "execution_engine": {
        "class_name": "SqlAlchemyExecutionEngine",
        "module_name": "great_expectations.execution_engine",
        "connection_string": f"{connection_url}",
        "create_temp_table": "False",
    },
    # Currently connects to all tables
    "data_connectors": {
        # needed to be able to query to get assets
        "runtime_connector": {
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": ["default_identifier_name"],
        },
        "svrless_beopt_dev_connector": {
            "class_name": "InferredAssetSqlDataConnector",
            "include_schema_name": True
        }
    }
}
```

My BatchRequest:

```
batch_request = RuntimeBatchRequest(
    datasource_name="synapse_datasource",
    data_connector_name="runtime_connector",
    data_asset_name="default",
    runtime_parameters={"query": "SELECT * from anlagendaten.anlagendaten"},
    batch_identifiers={"default_identifier_name": "default_identifier"},
)
```

Running the checkpoint:

```
expectations = "synapse_anlagen_expectations"
checkpoint_config = {
    "name": "synapse_config",
    "config_version": 1,
    # "run_name_template": f"{expectations}",
    "action_list": [
        {
            "name": "store_validation_result",
            "action": {"class_name": "StoreValidationResultAction"}
        },
        {
            "name": "update_data_docs",
            "action": {"class_name": "UpdateDataDocsAction"}
        }
    ],
    "validations": [
        {
            "batch_request": batch_request,
            "expectation_suite_name": f"{expectations}"
        }
    ]
}
# context.test_yaml_config(yaml.dump(synapse_config))
checkpoint = Checkpoint(data_context=context, **checkpoint_config)
results = checkpoint.run(run_name="val_synapse_anlagendaten")
```

And my minimal suite:

```
{
  "data_asset_type": null,
  "expectation_suite_name": "synapse_anlagen_expectations",
  "expectations": [
    {
      "expectation_type": "expect_column_values_to_be_in_set",
      "kwargs": {
        "column": "ANLAGE_NAME",
        "value_set": [
          "US",
          "Europe"
        ]
      },
      "meta": {}
    }
  ]
}
    
```

**Expected behavior**
Data should be red and validated with Synapse as datasource.

**Environment (please complete the following information):**
 - Operating System: WSL (Ubuntu 20.04.5 LTS)
 - Great Expectations Version: [e.g. 0.15.34]

**Comment by rdodev** [comment]
Hey @pfuerste 👋 

GX presently doesn't support Azure Synapse. However, I have added relevant tags for our Product management team to consider adding support for it down the line. That having been said, we'd be happy to accept a contribution from the community if that's something you'd consider.

**Comment by pfuerste** [comment]
So just to be clear, querying Synapse with an InferredAssetSqlDataConnector works, but that data can't be used in checkpoints?
Do you know how to convert that data to a dataframe (as seen in validator.head())? With that, I could build a workaround for now and pass that in-memory dataframe into a runtimebatchrequest for another checkpoint.

I sadly currently don't have the time to look deeper into it and build it in a proper way.

**Comment by rdodev** [comment]
@pfuerste because GX doesn't 'know' the format/structure of the data there is no good way to convert that dataset into a GX in a way validators and metrics can use. But it's possible someone in the community has come up with a solution. Have you tried asking in out community Slack?

**Comment by pfuerste** [comment]
I did. If someone here wants to help me build a workaround in passing a dataframe generated from validator.head() to a checkpoint, that should maybe rather be done over there: https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1670317981761459

**Comment by talagluck** [comment]
Hi @pfuerste - just to be clear, it's possible that Azure Synapse may work with GX through a generic SqlAlchemy connection; however since this is not supported, we don't have any way to test it or to reproduce issues that arise with it. So using GX with Azure Synapse is a bit of a "use at your own risk" situation, though if you are interested in making a contribution, please do reach out. 

That said, we have logged this feedback and will review it if/when we decide to implement new backends ourselves in the future. I'm going to close this issue for now. Thanks!
