### ISSUE TITLE
Error RuntimeBatchRequests must specify exactly one corresponding BatchDefinition Spark, Glue

### ISSUE THREAD

**Issue by benreskallah** [fivetran/great_expectations#6508]
We are using great_expectations to validate data on AWS Glue. Source data are located in S3 in format "parquet".
We follow all requested steps defined the official Doc. While executing, the returned error is
"ValueError: RuntimeBatchRequests must specify exactly one corresponding BatchDefinition"

To Reproduce the error please follow the steps in https://docs.greatexpectations.io/docs/deployment_patterns/how_to_use_great_expectations_in_aws_glue/

below part of the script that show the batch_request config:
```
expectation_suite_name = "suite_name_1"
batch_request = RuntimeBatchRequest(
    datasource_name="fist_financial_statement",
    data_asset_name="data_asset_name",
    batch_identifiers={"default_identifier_name": "default_identifier"},
    data_connector_name="default_inferred_data_connector_name",
    runtime_parameters={"path": "s3://***.parquet"},
    batch_spec_passthrough={"reader_method": "parquet", "reader_options": {"header": True}},
)
suite = context.create_expectation_suite(
    expectation_suite_name="suite_name_1", overwrite_existing=True
)
validator = context.get_validator(
    batch_request=batch_request, expectation_suite_name="suite_name_1"
)
print(validator.head())
```

in addition, we are using a great_expectations.yaml file that contain the definition of the datasource 
```
datasources:
  fist_financial_statement:
    module_name:  great_expectations.datasource
    class_name: Datasource
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: SparkDFExecutionEngine
    data_connectors:
      default_inferred_data_connector_name:
        class_name: InferredAssetS3DataConnector
        bucket: ***
        prefix: ****
        default_regex:  
          pattern: (.*)
          group_names: 
            - data_asset_name
      default_runtime_data_connector_name:
        batch_identifiers: 
          - default_identifier_name
        module_name: great_expectations.datasource.data_connector
        class_name: RuntimeDataConnector

Error: ValueError: RuntimeBatchRequests must specify exactly one corresponding BatchDefinition
```
we expect to create the suite and run the checkpoint

**Environment:**
 - AWS Glue: 2.0
 - Spark: 2.4
 - Python: 3 
 - Great Expectations Version: last version

**Comment by rdodev** [comment]
Hey @benreskallah 👋

We're looking into this. Let me ask the team and we'll get back to you.

**Comment by rdodev** [comment]
Hey @benreskallah 

While we continue to investigate, one thing that jumped at us is that you are trying to use a non-runtime data connector with a runtime batch request (we realize this was copied from the example provided in the doc, sorry). We suggest trying to use a `RuntimeDataConnector` ([here](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_configure_a_runtimedataconnector)) and see if that gets you past this error.

**Comment by benreskallah** [comment]
hey @rdodev 
thanks for feedback, I confirm that we use S3 datasource and the same script (with little change) is running without error in local machine.
I already test the suggested proposition (df= spark.read.parquet(path) and in the batch_request= ... runtime_parameters={"batch_data": df}, ...) I had the same error
I put here the script and the great_expectations.yaml if this help in investigation
[application (1).zip](https://github.com/great-expectations/great_expectations/files/10188162/application.1.zip)

**Comment by rdodev** [comment]
@benreskallah 

Thanks for that. Will keep you posted.

**Comment by rdodev** [comment]
@benreskallah looking at the files you attached seems there's a misunderstanding in the suggested approach above. Basically look at your original code:

```
expectation_suite_name = "suite_name_1"
batch_request = RuntimeBatchRequest(
    datasource_name="fist_financial_statement",
    data_asset_name="data_asset_name",
    batch_identifiers={"default_identifier_name": "default_identifier"},
    data_connector_name="default_inferred_data_connector_name",
    runtime_parameters={"path": "s3://***.parquet"},
    batch_spec_passthrough={"reader_method": "parquet", "reader_options": {"header": True}},
)
suite = context.create_expectation_suite(
    expectation_suite_name="suite_name_1", overwrite_existing=True
)
validator = context.get_validator(
    batch_request=batch_request, expectation_suite_name="suite_name_1"
)
print(validator.head())
```
The data connector name _has to be_ of class `RuntimeDataConnector` because it's part of a `RuntimeBatchRequest`. So, if you were to change `RuntimeBatchRequest` in your config to `BatchRequest` we think that will get past this issue.
