### ISSUE TITLE
MSSQL TypeError: 16:00:00 type time which cannot be serialized.

### ISSUE THREAD

**Issue by YuliaPopovaTibra** [fivetran/great_expectations#6514]
DataHub uses great_expectations for profiling. I'm running great_expectations against Microsoft SQL table.

Code from DataHub
```
from great_expectations.core.util import convert_to_json_serializable

def get_column_unique_count_patch(self, column):
    if self.engine.dialect.name.lower() == "redshift":
        element_values = self.engine.execute(
            sa.select(
                [sa.text(f'APPROXIMATE count(distinct "{column}")')]  # type:ignore
            ).select_from(self._table)
        )
        return convert_to_json_serializable(element_values.fetchone()[0])
```

The issue appears in convert_to_json_serializable when it is works with **time** data type from MS SQL.
Error message is following

`'    return convert_to_json_serializable(\n'`
`           '  File "/tmp/datahub/ingest/venv-mssql-0.9.2/lib/python3.10/site-packages/great_expectations/core/util.py", line 296, in '`
`           'convert_to_json_serializable\n'`
`           '    raise TypeError(\n'`
`           'TypeError: 16:00:00 is of type time which cannot be serialized.\n'`

**Expected behavior**
"Time" datatype to be supported in convert_to_json_serializable

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.15.36
 - Python Version: 3.9.7

**Comment by rdodev** [comment]
Hi @YuliaPopovaTibra 

Thanks for raising this issue. GX currently doesn't fully support MSSQL so this is likely part of it. I'll bring it to the team's attention see what can be done about it. That said, we're always open to community contributions, so if you're inclined we're happy to accept a PR with a fix.

**Comment by YuliaPopovaTibra** [comment]
Hi @rdodev,
thank you for your answer. I don't believe that I have enough knowledge to fix this issue. I will keep an eye on new releases.

**Comment by molliemarie** [comment]
Hello @YuliaPopovaTibra. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗

**Comment by molliemarie** [comment]
Closing
