### ISSUE TITLE
expect_compound_columns_to_be_unique does not support mostly

### ISSUE THREAD

**Issue by kimfrie** [fivetran/great_expectations#6532]
**Is your feature request related to a problem? Please describe.**
I was going to add the parameter mostly to the expectation and found that it's not supported.
When looking at the `expectations/core/expect_compound_columns_to_be_unique.py` file, some logic for mostly has been implemented already.

While doing this i found a weird bug that caused the following exception:

>   File "/usr/local/lib/python3.10/site->packages/great_expectations/expectations/core/expect_compound_columns_to_be_unique.py", line 176, in >_prescriptive_renderer
>    params["mostly_pct"]["value"] = num_to_str(
>KeyError: 'mostly_pct'

**Describe the solution you'd like**
I have already worked on a solution to fix the KeyError and also on implementing mostly for said expectation for SQLAlchemy Dataset.

The mostly param should be accepted and working

I would open the PR in a bit

**Comment by austiezr** [comment]
Hey @kimfrie ! Thanks for raising this, and for the contribution! 🚀 The team will review & advise as needed.

**Comment by talagluck** [comment]
Closed as resolved by #6533. Thanks, @kimfrie!
