### ISSUE TITLE
Numpy Datetime TypeError in expect_column_pair_values_a_to_be_greater_than_b 

### ISSUE THREAD

**Issue by tmilitino** [fivetran/great_expectations#6552]
**Describe the bug**
I try to use expect_column_pair_values_a_to_be_greater_than_b expectation to validate my parquet files, but when run checkpoint I get a dtype exception. As image below.

![Captura de tela de 2022-12-09 22-59-52](https://user-images.githubusercontent.com/23370997/206824873-c1a9e23e-b96b-4e25-ba84-fb541f67edb7.png)

when debug convert_to_json_serializable function, does not has conditional for numpy datetime.

**Expected behavior**
numpy "DateTime" datatype to be supported in convert_to_json_serializable

**Environment (please complete the following information):**
 - Operating System: Ubuntu 20.04 Linux
 - Great Expectations 0.15.31
 - Python 3.10.6
 - File type: Parquet

Let me know if anything is unclear. 
Thx!

**Comment by tmilitino** [comment]
I created this condicional to numpy datetime in convert_to_json_serializable function. If it's ok, I can submit my PR for review

**Comment by austiezr** [comment]
Hey @tmilitino ! Thanks for raising this, and for the contribution! 🚀 The team will review and advise as needed.
