### ISSUE TITLE
Warning seen while passing batch request to an in memory checkpoint.

### ISSUE THREAD

**Issue by adarsha-jll** [fivetran/great_expectations#6558]
**Describe the bug**
In Memory checkpoint gives warning 
Expected type ‘Optional[BatchRequestBase]’, got ‘Dict[str, Union[Dict[str, str], Dict[str, Any]]]’ instead

**To Reproduce**
1. Add runtime batch request
```
    batch_request = RuntimeBatchRequest(
    datasource_name=self.data_source_name,
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name=self.batch_asset,  # data asset name
    runtime_parameters={"batch_data": df},  # Passing the DataFrame here.
    batch_identifiers={"default_identifier_name": "default_identifier"},
    )
```      
2. validations
```
    validation_list_db = [{'batch_request': {'datasource_name': datasource_name,
                                                 'data_connector_name': 'default_runtime_data_connector_name',
                                                 'data_asset_name': data_asset_name,
                                                 },
                               'expectation_suite_name': expectation_suite_name
                               },
                              ]
```
3. checkpoint
```
    context.add_checkpoint(name=self.checkpoint_name,
                                            config_version=1.0,
                                            class_name='SimpleCheckpoint',
                                            run_name_template=self.run_name_template,
                                            expectation_suite_name=self.expectation_suite_name,
                                            batch_request={},
                                            action_list=Base.action_list(self),
                                            evaluation_parameters={},
                                            runtime_configuration={},
                                            validations=validation_list_db,
                                            profilers=[],
                                            slack_webhook=self.db_utils.set_slack_url(),
                                            notify_on=self.db_utils.set_slack_notify(),
                                            notify_with='all',
                                            ge_cloud_id='',
                                            expectation_suite_ge_cloud_id=''
                                            )

    context.run_checkpoint(checkpoint_name=self.checkpoint_name,
                                             batch_request={
                                                 "runtime_parameters": {"batch_data": df},
                                                 "batch_identifiers": {
                                                     "default_identifier_name": "default_identifier"
                                                 },
                                             },
                                             )
```
**Expected behavior**
No error or warning is given for the run_checkpoint method. 
    But pycharm IDE gives
    Expected type ‘Optional[BatchRequestBase]’, got ‘Dict[str, Union[Dict[str, str], Dict[str, Any]]]’ instead
    
   but providing RuntimeBatchRequest this way does not do anything. 
   No visible logs, nor exceptions generated.
  ``` 
   run_checkpoint(checkpoint_name=self.checkpoint_name,
                               batch_request=RuntimeBatchRequest(
                                   datasource_name=self.data_source_name,
                                   data_connector_name="default_runtime_data_connector_name
                                   data_asset_name=self.batch_asset,  # data asset name
                                   runtime_parameters={"batch_data": df},  # Passing the DataFrame here.
                                    batch_identifiers={"default_identifier_name": "default_identifier"},
                                    ))

```

**Environment (please complete the following information):**
 - Operating System: [MacOS]
 - Great Expectations Version: [0.15.31]
 - Python 3.8.14

**Additional context**

**Comment by austiezr** [comment]
Hey @adarsha-jll ! Thanks for raising this. We'll review and assess.

**Comment by molliemarie** [comment]
Hello @adarsha-jll. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗

**Comment by molliemarie** [comment]
Closing
