### ISSUE TITLE
How to use Kedro with Great-expectations?

### ISSUE THREAD

**Issue by DhavalThkkar** [fivetran/great_expectations#6620]
**Describe the bug**
I am using Kedro to create a pipeline for ETL purposes and column specific validations are being done using Great-Expectations. There is a hooks.py file listed in Kedro documentation [here](https://kedro.readthedocs.io/en/stable/hooks/examples.html#add-data-validation). This hook is registered as per the instructions mentioned on Kedro-docs.

I am not able to use Kedro with Great-Expectations

**To Reproduce**

1. Created a kedro project using `kedro new`, project name `ecom_analytics`
2. Stored the datasets in `data/01_raw` folder called `dataset_raw.csv` & `dataset_validate.csv`
3. Initialize great_expectations project using `great_expectations init`
4. Create a new datasource using `great_expectations datasource new`. The name I added was `main_datasource`
5. Create a new expectation using `great_expectations suite new`. This expectation is called `data.raw` using data assistant
6. Edited the great_expectations suite using `great_expectations suite edit data.raw`
7. Created the catalog entries for the datasets in `conf/catalog.yml`
8. Added the Great expectations `hooks.py` given in the kedro documentation and registered the hook on `settings.py` file
9. Tried `kedro viz --autoreload`. This works to view the visualisation

**Expected behavior**
Use kedro with great-expectations to load the data with all the validations

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.15.41

**Additional context**
You can look at the latest commit at the `develop` branch to recreate the issue [here](https://github.com/DhavalThkkar/ecom-analytics/tree/develop)

**Comment by talagluck** [comment]
Hi @DhavalThkkar - thanks for raising this. The integration with Kedro is quite old, and so does not work with the current Great Expectations API. You may want to raise this with Kedro as well, since I think they had built the original integration. We don't have immediate plans to make updates here ourselves, but we will review and see what we can do in the new year.

**Comment by DhavalThkkar** [comment]
Hi @talagluck, I have created an issue for Kedro repo as well. I was just wondering if there's anything I can do to fast-track this

**Comment by talagluck** [comment]
Hi @DhavalThkkar - I'm glad that you want to use this! On our side, I don't think there's much we can do fast-track this for the moment, but I will bring it up when I can. The code for this is in the Kedro repo - I wonder if they'd be open to a contribution?

**Comment by talagluck** [comment]
Hi @DhavalThkkar - as mentioned above, there is not much we can do on our end in the short term. That said, we've logged this feedback and we will be in touch if anything changes here. Thanks again for raising!
