### ISSUE TITLE
Validation results for expect_table_row_count_to_equal shows None in html.

### ISSUE THREAD

**Issue by da-sbarde** [fivetran/great_expectations#6654]
I have run a validation ie expect_table_row_count_to_equal, it ran successfully but when I build a doc report from it, the html file shows - **Must have exactly None rows**. It should not display None in the html file, instead it should display a count. More surprising is that the validation result in json format is correct. 

Here is the link to html result- https://azureretailinput.s3.ap-south-1.amazonaws.com/fdeeb02df14b87830e9f33c23a998ecc.html

Below is the code snippet - validator.expect_table_row_count_to_equal(value=12
    )

**Comment by milithino** [comment]
I had this same issue, when i run GX with develop branch, this issue was fixed. I believe in the next release will be resolved

**Comment by austiezr** [comment]
Hey @da-sbarde (and @milithino 👋 )! Thanks for reaching out.

@da-sbarde are you able to share your GX version & environment details? That will help us to verify possible cause and resolution re: the coming release.

**Comment by talagluck** [comment]
Closing as this appears to be resolved. Thanks for raising!
