### ISSUE TITLE
How to connect Hadoop Database/Great Expectations running on Hadoop (HDFS)

### ISSUE THREAD

**Issue by miao111** [fivetran/great_expectations#6662]
### Discussed in https://github.com/great-expectations/great_expectations/discussions/4821

<div type='discussions-op-text'>

<sup>Originally posted by **rdodev** April  7, 2022</sup>
While Great Expectations can be made to work with HDFS as a file system data source, the GE execution engine does not support running in distributed environments. The purpose of this discussion thread is to hear from the community how they are using is GE on Hadoop, what work-arounds, if any, and what the tool chain looks like (Spark, Oozie, etc.).</div>

**Comment by austiezr** [comment]
Hey @miao111! There doesn't appear to be an issue report or feature request here. Please feel free to continue to discuss functionality in this area in the GitHub Discussion you've linked above, or open a new issue with the relevant information. For now, I'm closing this out.
