### ISSUE TITLE
Remove unused imports in integrate_validation_into_pipeline.ipynb

### ISSUE THREAD

**Issue by StevenMMortimer** [fivetran/great_expectations#668]
There are imports at the top of [integrate_validation_into_pipeline.ipynb](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/init_notebooks/integrate_validation_into_pipeline.ipynb) and I am not sure if they are needed. The lines in question are: 

```
import uuid # used to generate run_id
import tzlocal
```

**Comment by eugmandel** [comment]
@StevenMMortimer Thank you for filing this issue! The fix will be released with 0.7.9 next Tuesday.
