### ISSUE TITLE
CLI can't create a new suite from a csv file with uppercase file extension

### ISSUE THREAD

**Issue by olhmr** [fivetran/great_expectations#6685]
**Describe the bug**
When going through the steps to generate a new expectation suite from a sample batch of data, the process will fail with a `Unable to determine reader method from path` error if the batch is a csv file with an uppercase extension (i.e., `myfile.CSV`).

**To Reproduce**
1. Follow [the tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_setup) to create a new datasource (steps 1 and 2). 
2. Rename one of the files in the `data` folder to have an uppercase `.CSV` extension
3. Go through step 3 of the tutorial, selecting the uppercase `.CSV` file as the source of the batch data
4. It will fail with the above error
5. Do step 3 but for the other, lowercase, `.csv` file instead, and note that it succeeds

**Expected behavior**
`.csv` and `.CSV` should be treated the same way

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.15.41

**Additional context**
N/A

**Comment by austiezr** [comment]
Hey @olhmr ! Thanks for reaching out. We'll review and assess this functionality; if you're interested in resolving this issue & making a contribution, please feel free to open a PR and we will be happy to provide guidance and review.

**Comment by tmilitino** [comment]
Hi @austiezr, Can i go ahead in this issue?

**Comment by austiezr** [comment]
Hey @tmilitino ! Absolutely!
