### ISSUE TITLE
Feature request for column counts (e.g. expect_table_column_count_to_equal)

### ISSUE THREAD

**Issue by StevenMMortimer** [fivetran/great_expectations#669]
As of 0.7.7 there are two methods to check the row counts (`expect_table_row_count_to_be_between ` and `expect_table_row_count_to_equal`), but there are none to check the column counts. Yes, there are more strict checks for columns like `expect_column_to_exist ` and `expect_table_columns_to_match_ordered_list()`. However, sometimes you just need to check the shape and not existence by name. 

This feature request is for two column count expectations to be created that are analogous to the ones for row counts.

**Comment by eugmandel** [comment]
+1

**Comment by elsander** [comment]
I can take a stab at this! Would you want to pull this in to `v0.8.x` or should I merge against `develop`?

**Comment by Aylr** [comment]
Closing! Thanks @elsander !
