### ISSUE TITLE
Authentication problems with custom gcs_options

### ISSUE THREAD

**Issue by cbarros7** [fivetran/great_expectations#6699]
**Describe the bug**

Authentication error when using customizable credentials from `service_account.Credentials.from_service_account_info` option in both `InferredAssetGCSDataConnector` and `ConfiguredAssetGCSDataConnector` connector classes using the gcs_options parameter. 

**To Reproduce**
N/A (Please, see Additional context)

**Expected behavior**
The behavior of the code is expected to read the dictionary and return the Client successfully.

> _**Additional comment:**_ When downloading the GCP credentials in JSON format there is no `"info"` key. 

**Environment:**
 - Operating System: MacOS Ventura
 - Great Expectations Version: [e.g. 0.15.41]

**Additional context**. 
In my case, there is only the option to get the GCP credentials through a **Secret** stored in an _environment variable_ which is processed as follows:
 
``` 
account_secret = FunctionGetSecret()
gcp_service_account = json.loads(base64.b64decode(account_secret))
``` 

Once decoded the json is obtained with the credentials whose structure of the variable `gcp_service_account` is: 
``` 
{
   "type": "...",
   "project_id": "...",
   "private_key_id": "...",
   "private_key": "...",
   "client_email": "...",
   "client_id": "…",
   "auth_uri": "...",
   "token_uri": "....",
   "auth_provider_x509_cert_url": "....",
   "client_x509_cert_url": "...."
} 
```

In the source code of the `InferredAssetGCSDataConnector` class when referring to the `gcs_options` parameter it is expected to be processed with `service_account.Credentials.from_service_account_file` or `service_account.Credentials.from_service_account_info`. In my case, it is the latter. Therefore, the value of `gcs_options` must have the **"info"** key to apply the pop method to it. 

https://github.com/great-expectations/great_expectations/blob/7b31de3ec1fa6866c77eba0b71a15cc709ab8ffa/great_expectations/datasource/data_connector/inferred_asset_gcs_data_connector.py#L110

Now, as it could be observed above, the credentials do not come with this parameter so I proceed to add it: 

```
# The json file does not have the "info" key, it is added and as a value it is assigned the content of the credentials. 
json_service_account = {}
json_service_account['info']=gcp_service_account
```

The new structure of the json with this change would be: 

```
{“Info”: {
        	"type": "...",
        	"project_id": "...",
        	"private_key_id": "...",
        	"private_key": "...",
        	"client_email": "...",
        	"client_id": "…",
        	"auth_uri": "...",
        	"token_uri": "....",
        	"auth_provider_x509_cert_url": "....",
        	"client_x509_cert_url": "...."
      	},
}
```

Finally, I have performed a small simulation with a part of the source code detailed below. 

https://github.com/great-expectations/great_expectations/blob/7b31de3ec1fa6866c77eba0b71a15cc709ab8ffa/great_expectations/datasource/data_connector/inferred_asset_gcs_data_connector.py#L110-L115

```
[In]  from google.cloud import storage
    
      gcs_options = json_service_account
    
      if "info" in gcs_options:
         info = gcs_options.pop("info")
        credentials = service_account.Credentials.from_service_account_info(
        info=info
        )
    
     storage.Client(credentials=credentials, **gcs_options)

[Out]  <google.cloud.storage.client.Client at 0x7fcf33rtwsf90>
```

The connection of the credentials were successful. However, when I set the `Data Context` I get an error in the credentials configuration. The code I use is the following: 
```
project_config = DataContextConfig(
    config_version=2,
    plugins_directory=None,
    config_variables_file_path=None,
    datasources={
        "gcs_datasource": DatasourceConfig(
            class_name="Datasource",
            module_name="great_expectations.datasource",
             execution_engine={
                "class_name": "PandasExecutionEngine"
              },
            
            data_connectors={
                "default_inferred_data_connector_name": {
                    "class_name": "InferredAssetGCSDataConnector",
                    "name": "default_inferred_data_connector_name",
                    "bucket_or_name": BUCKET_NAME_GE,
                    "prefix": PREFIX_PATH,
                    "gcs_options": json_service_account, #previously created variable that contains dictionary with credentials
                    "default_regex": {
                            "pattern": "(.*)\.csv",
                    "group_names": [
                      "index"
                    ]      
                        
                    
                  }
                },
             
            }
    )},
```

When I try to execute this configuration I get error:
```
[In]  from great_expectations.data_context import BaseDataContext
       context = BaseDataContext(project_config=project_config)

[Out]  Cannot initialize datasource gcs_datasource: Cannot initialize datasource gcs_datasource, error: Unable to load GCS Client (it is required for InferredAssetGCSDataConnector).
```

**Comment by austiezr** [comment]
Hey @cbarros7 ! Thanks for raising this. We'll be in touch if we require further context while reviewing this issue.

**Comment by rdodev** [comment]
Hey @cbarros7 we have passed this feature/functionality request to Product management for prioritization. Unfortunately, we can't provide any estimates at this time.

**Comment by billdirks** [comment]
Hi - thanks for raising this. This is a really cool idea. We likely won’t be able to prioritize this in the immediate future, so I’m going to close this for now, but we’ve logged this product feedback and will be in touch if and when we are able to work on it.
