### ISSUE TITLE
Site rendering fails when using `expect_multicolumn_sum_to_equal` 

### ISSUE THREAD

**Issue by data-han** [fivetran/great_expectations#6758]
**Describe the bug**
After running the expectations and validations, data doc shows up correctly to determine whether the test case is a 'success' or 'failure'. However, in the description box, it is showing `(**{})` which does not provide much information as to what was the issue

This issue was raised in https://github.com/great-expectations/great_expectations/issues/4365 but seems like it is not resolved on my end

**To Reproduce**

**Expected behavior**
It should have a more descriptive statement

**Environment (please complete the following information):**
 - Operating System: Mac OS
 - Great Expectations Version: 0.15.42

**Additional context**
None

<img width="359" alt="image" src="https://user-images.githubusercontent.com/51312880/211754762-5e2099b9-2763-4129-9f5b-acbf1fdf8b08.png">

**Comment by rdodev** [comment]
Hey @data-han thanks for raising this issue. Will consult internally and provide updates as they are available.

**Comment by andrrreasss** [comment]
the same thing happens with expect_column_values_to_not_be_in_set

**Comment by talagluck** [comment]
Resolved by #7041
