### ISSUE TITLE
"The domain column is currently set to None" when running compound columns expectation on Pandas

### ISSUE THREAD

**Issue by KHerashchenko** [fivetran/great_expectations#6779]
**Describe the bug**
I am facing an exception while running expect_compound_columns_to_be_unique expectation using Pandas engine against DataFrame with multiple indices.  
```Error: The domain column is currently set to None. Please check your configuration.```

**To Reproduce**
1. Create Pandas DataFrame with multiple indices `col1`, `col2`
2. Create expectation expect_compound_columns_to_be_unique for `col3`, `col4`
3. Run checkpoint and retrieve `ExpectationValidationResult` object
4. You should see the error inside `exception_info` and empty `result` dict

**Expected behavior**
Instead, you should see validation results inside `result` dict

**Environment (please complete the following information):**
 - Operating System: Linux, Windows
 - Great Expectations Version: 0.15.42

**Additional context**
I believe there must be an issue in [ this line ](https://github.com/great-expectations/great_expectations/blob/0.15.42/great_expectations/expectations/metrics/map_metric_provider.py#L1785)  
While running expectations against compound columns, `domain_kwargs` does not contain `column` key, instead it contains `column_list`. That is why `expectation_domain_column_name` is being assigned to `None` and later exhausts into error [here](https://github.com/great-expectations/great_expectations/blob/0.15.42/great_expectations/expectations/metrics/util.py#L1086)

**Comment by rdodev** [comment]
@KHerashchenko could you provide more details as provided in the issue template?

**Comment by KHerashchenko** [comment]
@rdodev sorry for mess, I've finished editing issue

**Comment by molliemarie** [comment]
Hello @KHerashchenko. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
