### ISSUE TITLE
Context.assistance.onboarding .run not taking single batch

### ISSUE THREAD

**Issue by CHETANVINU** [fivetran/great_expectations#6798]
Hi 

When I ran the context.assistance.onboarding.run(my_batch) with spark. I'm getting" sparkDFDataset is not iterable. " I'm using single batch 

Regards,
Chetan

**Comment by austiezr** [comment]
Hey @CHETANVINU ! Thanks for reaching out. Are you able to share your configs, as well as the workflow generating this error, and complete stack trace? That will help us to better understand what may be happening here.

**Comment by talagluck** [comment]
Closed due to inactivity.
