### ISSUE TITLE
How can I remove an expectation that I no longer have or entered erroneously?

### ISSUE THREAD

**Issue by jpcampb2** [fivetran/great_expectations#68]

**Comment by jpcampb2** [comment]
Proposed API:
```
my_df.remove_expectation(
  expectation_type,
  column=None,
  expectation_kwargs={},
  remove_multiple_matches=False
)
```

`my_df.remove_expectation("expect_column_to_exist", "Unnamed:0")`
=> Removes expect_column_to_exist where column="Unnamed:0" (a single expectation)

`my_df.remove_expectation("expect_column_to_exist", {"column": "Unnamed:0"})`
=> Removes expect_column_to_exist where column="Unnamed:0" (a single expectation)

`my_df.remove_expectation("expect_column_to_exist", {"column": "Unnamed:0"})`
=> Throws a warning: "multiple expectations matched arguments. No expectations removed." 

`my_df.remove_expectation("expect_column_to_exist", remove_multiple_expectations=True)`
=> Removes all expect_column_to_exist expectations

`my_df.remove_expectation("expect_column_to_exist", "my_other_column", {"column": "Unnamed:0"})`
=> Raises an error 'Conflicting column names in remove_expectation: my_other_column and "Unnamed:0"'

`my_df.remove_expectation("expect_column_values_to_be_between", "my_column", {"mostly": .95})`
=> Removes expect_column_values_to_be_between with column=my_column and mostly=.95 (a single expectation). If mostly!=.95 then this removes nothing.

`my_df.remove_expectation("expect_column_values_to_be_between", {"mostly": .95}, remove_multiple_expectations=True)`
=> Removes all expect_column_values_to_be_between where mostly=.95.

Question: should we make the `expectation_type` parameter optional as well? Then you could remove *all* expectations with the same `mostly` parameter value (or any other parameter value) as well.

**Comment by jpcampb2** [comment]
This API makes sense to me. Did you explicitly consider and reject the idea of having some sort of expectation id that we build as well? If we build an expectation id as a hash of all_args (during expectation creation time, and potentially something else if needed) we could expose a much cleaner api of: ```df.remove_expectation(expectation_id)``` It could also be a nice way to organize results from validate...

**Comment by jpcampb2** [comment]
I thought about ids a bit. We'd definitely go that direction if
great_expectations were a full workflow application, backed by a database.
In an exploratory workflow, I think ids are more trouble than they're worth.

* If I run exactly the same expectation twice, does that change the id?
* What if I change the `mostly` parameter a little bit?
* What if I change it right back?

I don't think we want a hash, because collisions happen.

-- 
abegong@gmail.com
@abegong <https://twitter.com/AbeGong>
http://www.abegong.com

**Comment by abegong** [comment]
This will need to be updated to stay consistent with whatever decision we make on #44.

**Comment by jpcampb2** [comment]
I think that the result of #44 means that this works as proposed originally.
