### ISSUE TITLE
Partition docstrings don't match returned dictionary keys

### ISSUE THREAD

**Issue by StevenMMortimer** [fivetran/great_expectations#681]
In `categorical_partition_data()` the docstring [HERE](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/dataset/util.py#L71) says that the returned `partition_object` will be a dictionary with two keys: 1) `partition` and 2) `weights`. However, the code will return a dictionary with the keys `values` and `weights`.

In `kde_partition_data()` the docstring [HERE](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/dataset/util.py#L102) says that the returned `partition_object` will be a dictionary with two keys: 1) `partition` and 2) `weights`. However, the code will return a dictionary with the keys `bins` and `weights`.

There appears to be some tension or drift in how categorical partition objects and continuous partition objects are being defined. It seems like an effort started to make categorical and continuous return the same two dictionary keys (`partition` and `weights`), but then categorical adopted `values` and continuous partition objects adopted `bins` as their respective dictionary keys without the docstrings keeping up with the change.

**Comment by jcampbell** [comment]
Your hypothesis is exactly correct on the evolution. I'll fix the docstrings!
