### ISSUE TITLE
unexpected_rows in validation results are missing in some expectations

### ISSUE THREAD

**Issue by lu-lz** [fivetran/great_expectations#6813]
**Describe the bug**
1. Background: we are doing row-level validations and we want to extract the key of the erroneous rows from the unexpected_rows in the validation results. Therefore we configure include_unexpected_rows=True and result_format="COMPLETE".
2. Issue: We can get the complete list of unexpected rows in some of the expectations for example `expect_column_values_to_match_regex` shown in *Figure 1*. However, we got "unexpected_rows": [] in `expect_column_values_to_be_in_set` and "unexpected_rows": null for `expect_column_values_to_not_be_null` which are shown in *Figure 2* and *Figure 3* respectively.
*Figure 1*
![Figure1](https://user-images.githubusercontent.com/106143183/212905056-6b2541ae-2141-4288-8a8c-631b25240da3.png)
*Figure 2*
![Figure2](https://user-images.githubusercontent.com/106143183/212881716-27e58ded-a31f-49ea-908a-e9ba7ca992df.png)
*Figure 3*
![Figure3](https://user-images.githubusercontent.com/106143183/212881737-1af2d2d0-fdd7-454f-abbb-fad18a5f6a4b.png)

**To Reproduce**
N/A (Please, see Additional context)

**Expected behavior**
The unexpcted_rows should not depend on the type of expectations. All expectations should be able to show the unexpected_rows in the validation results if the values violates the validation rules.

**Environment (please complete the following information):**
 - Operating System: [Windows]
 - Great Expectations Version: [0.15.43]
 - database: BigQuery

**Comment by austiezr** [comment]
Hey @lu-lz ! Thanks for raising this. We'll review and assess this behavior.

**Comment by alexsherstinsky** [comment]
Hello, @lu-lz -- I just tried to utilize the specification of `result_format` in a way that would incorporate the directive to return the `include_unexpected_rows` as part of the result; I used the following syntax:
```
result = validator.expect_column_values_to_be_in_set(
    column= "my_column",
    value_set=my_value_set,
    mostly=1.0,
    result_format = {
        "result_format": 'SUMMARY',
        "partial_unexpected_count": 20,
        "include_unexpected_rows": True,
    },
    include_config=True,
    catch_exceptions=None,
    meta=None
)
print(result, 'Success: {0}'.format(result.success), str(type(result)))
```

and this worked properly for my test dataset.  What syntax are you using?  If not the one I indicated above, could you please try it and let us know whether or not you are now seeing the correct output, or if it is still missing the information you are seeking?

Thank you very much.

**Comment by donaldheppner** [comment]
Hi @lu-lz, we're closing this issue given the above suggested fix, please feel free to reopen if you are still facing this issue.
