### ISSUE TITLE
Failed validation on expectations where set __eval_col_ .

### ISSUE THREAD

**Issue by fifo2019** [fivetran/great_expectations#6824]
Hello, everyone!

Thank you, for your great contribution!

I'm use great-expectations==0.15.36

I have investigated the problem [Failed validation on expectation: expect_table_columns_to_match_set](https://github.com/great-expectations/great_expectations/issues/2017). Because I have this issue.

Location code: [great_expectations/great_expectations/dataset/sparkdf_dataset.py](https://github.com/great-expectations/great_expectations/blob/ad62cf6e04cf9df8b444b4f5d689afe635d1a942/great_expectations/dataset/sparkdf_dataset.py#L94)

I see it when I do:
1. Get df
2. Create ExpectationSuite 
![image](https://user-images.githubusercontent.com/46374972/213141824-4747ce87-7387-43fc-b703-cb441f389318.png)
3. Create SparkDFDataset 
![image](https://user-images.githubusercontent.com/46374972/213142081-e9c1853c-12ff-474e-b25e-d54890011436.png)
4. Run validate
![image](https://user-images.githubusercontent.com/46374972/213142547-dac9ce89-ddc2-4b64-b80b-0c885d9de5a5.png)
5. Result is failed because df have some columns as `"__eval_col_schema" and "__eval_col__table_"`
![image](https://user-images.githubusercontent.com/46374972/213143018-0e58c2d1-f6cd-42fd-9c52-fbe883ad6137.png)
 
I also see, if I run before method like `validate()`, I run method as `get_table_columns()` , then I don't have issue
![image](https://user-images.githubusercontent.com/46374972/213143950-499f1041-ffb6-4492-9fc1-2e2b50edabba.png)
![image](https://user-images.githubusercontent.com/46374972/213144689-075b7bb4-f784-46e7-8467-f658c30f5076.png)
![image](https://user-images.githubusercontent.com/46374972/213144401-95318d26-1a84-4a61-a7fd-ff330c8c4cdc.png)

After it I go to code to fix it and I found this line:
[line-with-issue](https://github.com/great-expectations/great_expectations/blob/ad62cf6e04cf9df8b444b4f5d689afe635d1a942/great_expectations/dataset/sparkdf_dataset.py#L95)

Here I see that on line 95 overwrite self.spark_df:
```
eval_col = "__eval_col_" + column.replace(".", "__").replace("`", "_")
self.spark_df = self.spark_df.withColumn(eval_col, col(column))
```

When I change this line 95 on (removed self):
```
eval_col = "__eval_col_" + column.replace(".", "__").replace("`", "_")
spark_df = self.spark_df.withColumn(eval_col, col(column))
```

And line 110 on:
`col_df = spark_df.select(col(eval_col))  # pyspark.sql.DataFrame`

After run my code and there is no issue anymore.

I also see line with `"__eval_col_"` on lines as 
[line 396](https://github.com/great-expectations/great_expectations/blob/ad62cf6e04cf9df8b444b4f5d689afe635d1a942/great_expectations/dataset/sparkdf_dataset.py#L396) 
[line 1163](https://github.com/great-expectations/great_expectations/blob/ad62cf6e04cf9df8b444b4f5d689afe635d1a942/great_expectations/dataset/sparkdf_dataset.py#L1163)
[line 1204](https://github.com/great-expectations/great_expectations/blob/ad62cf6e04cf9df8b444b4f5d689afe635d1a942/great_expectations/dataset/sparkdf_dataset.py#L1204)

**I would be very grateful if you fix it!!** 

**Thank you**

**Comment by austiezr** [comment]
Hey @fifo2019 ! This looks like an issue that can arise when mixing V2 & V3 constructs; unfortunately, the V2 API of Great Expectations has been deprecated, and is no longer under active development. Additionally, while it is *technically* possible to do the type of mixing & matching seen here, combining these workflows can be unstable, and is not a supported function of Great Expectations.

We would recommend migrating fully to the V3 API; take a look at [this migration guide](https://docs.greatexpectations.io/docs/guides/miscellaneous/migration_guide/#migrating-to-the-batch-request-v3-api), as well as our [Getting Started tutorial for V3](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_overview).

**Comment by fifo2019** [comment]
@austiezr Thank you so much! I'll try it.
