### ISSUE TITLE
unexpected_index_list is missing in some expectations

### ISSUE THREAD

**Issue by lu-lz** [fivetran/great_expectations#6840]
**Describe the bug**
1. Background: we are doing row-level validations and we configured the `unexpected_index_column_name =  unique_key` in the result format in checkpoint configuration file which is shown in *Figure1*.
2. Issue: We can get `unexpected_index_list` in some of the expectations for example `expect_column_values_to_not_be_null` shown in *Figure 2*. However, we couldn't get the `unexpcted_index_list` in `expect_column_pair_values_a_to_be_greater_than_b` shown in *Figure 3*

*Figure 1*
![Figure1](https://user-images.githubusercontent.com/106143183/213524718-089d04a9-6b68-4e28-86ac-5afcb34c4184.png)
*Figure 2*
![Figure2](https://user-images.githubusercontent.com/106143183/213531340-6748020f-6194-4e2e-b1b7-eddcba7609d5.png)
*Figure 3*
![Figure3 (3)](https://user-images.githubusercontent.com/106143183/213529037-079cc4f9-f6e7-41ac-8f20-ee85794ee8ba.png)

**To Reproduce**
N/A (Please, see Additional context)

**Expected behavior**
The `unexpected_index_list` should be present for all the expectations in the validation results when `unexpected_index_column_name`  is configured in the checkpoint file.

**Environment (please complete the following information):**
 - Operating System: [Windows]
 - Great Expectations Version: [0.15.43]
 - database: BigQuery

**Comment by austiezr** [comment]
Hey @lu-lz ! Thanks for raising this. We'll investigate this behavior and be in touch.

**Comment by lu-lz** [comment]
Hi @austiezr 
Thank you! 

Also there is another issue in the `unexpected_index_list`, it only returns 20 rows not the complete list the unexpected rows. e.g. `unexpected_count=375` however the number of elements in the `unexpected_index_list` is only 20.

**Comment by data-han** [comment]
`expect_column_pair_values_to_be_equal`
`expect_column_sum_to_be_between`

not working as well

**Comment by andrrreasss** [comment]
> Also there is another issue in the `unexpected_index_list`, it only returns 20 rows not the complete list the unexpected rows. e.g. `unexpected_count=375` however the number of elements in the `unexpected_index_list` is only 20.

As I understand it, this is normal behavior. There can be many strings. And only the top 10-20 come back. To get all rows the query text is returned.

**Comment by KHerashchenko** [comment]
For expect_column_values_to_not_be_null NEITHER unexpected_index_query NOR full unexpected_index_list is returned. How on earth should I retrieve the rows which failed validation????

**Comment by Shinnnyshinshin** [comment]
> For expect_column_values_to_not_be_null NEITHER unexpected_index_query NOR full unexpected_index_list is returned. How on earth should I retrieve the rows which failed validation????

Hi @KHerashchenko, could I check which level the `result_format` is set at?  `unexpected_index_query` and `unexpected_index_list` is only returned for [`COMPLETE`](https://docs.greatexpectations.io/docs/reference/expectations/result_format/#examples)

**Comment by Shinnnyshinshin** [comment]
Hi @lu-lz and @data-han

The `ColumnPair` Expectations that you described ( `expect_column_pair_values_to_be_equal ` and `expect_column_pair_values_a_to_be_greater_than_b `) were not part of the initial release, but have been implemented since [version 0.15.48](https://github.com/great-expectations/great_expectations/releases/tag/0.15.48). 

`expect_column_sum_to_be_between` is an aggregate Expectation, which means the expectation is compared against a metric we get for the whole column (in this case the sum of the values), and so there are no unexpected rows that we can describe as part of `unexpected_index_list`. 

I'll set this issue to "closed" for now, but please feel free to re-open if you continue to run into problems. Thank you!
