### ISSUE TITLE
expect_column_kl_divergence_to_be_less_than expectation does not render bar graph with boolean values

### ISSUE THREAD

**Issue by tmilitino** [fivetran/great_expectations#6909]
**Describe the bug**
expect_column_kl_divergence_to_be_less_than expectation does not render bar graph in data docs when used bollean values in partition_object

![image](https://user-images.githubusercontent.com/23370997/214206878-67c65dc1-62c3-4681-b05b-00874c5e89df.png)

**To Reproduce**
1. create/get file with boolean values ​​in a column
2. Create expectation with expect_column_kl_divergence_to_be_less_than
3. execute validate
4. See data docs without bar graph

**Expected behavior**
the data doc should render bar granph, when used boolean column

**Environment (please complete the following information):**
 - Operating System: Ubuntu 22.04
 - Great Expectations Version:0.15.44

**Comment by tmilitino** [comment]
I debugged and found a problem passing values ​​to jinja2. Some problem in jinja does not recognize boolean keys. I converted these boolean keys to string and solved this problem. Let me know if more info is needed.

**Comment by talagluck** [comment]
Thanks for raising this, @tmilitino, and thanks for opening the PR! The backlog is a bit full this week, but our team will review and be in touch shortly.
