### ISSUE TITLE
AttributeError: type object 'Draft7Validator' has no attribute 'FORMAT_CHECKER'

### ISSUE THREAD

**Issue by ms78692100** [fivetran/great_expectations#6966]
Hi

I have been using great expectation for while now. It was working fine till yesterday. Now I am getting below error message.

%pip install great-expectations

import great_expectations as ge

AttributeError: type object 'Draft7Validator' has no attribute 'FORMAT_CHECKER'

Is anyone able to help me please. It's urgent?

Thank You

**Comment by tanderson-eb** [comment]
As a temporary fix, we went back to a prior version - pip install great-expectations==0.14.13

**Comment by talagluck** [comment]
Resolved by #6984
