### ISSUE TITLE
Error "AttributeError: type object 'Draft7Validator' has no attribute 'FORMAT_CHECKER'"

### ISSUE THREAD

**Issue by YevgeniyaLee** [fivetran/great_expectations#6969]
**Describe the bug**
Error while initialising Great expectations DataContext
`AttributeError: type object 'Draft7Validator' has no attribute 'FORMAT_CHECKER'`

Hello, yesterday our application which uses Great expectations, failed, because of the error `AttributeError: type object 'Draft7Validator' has no attribute 'FORMAT_CHECKER'` while initialising Great expectations Data Context. 
While research it seems to us this happened because of [release](https://github.com/altair-viz/altair/pull/2771/files) of altair library used by Great expectations. To be more precise: [this line](https://github.com/binste/altair/blob/43f8ec88c8abd6d3aa44866d13363470746cda75/altair/utils/schemapi.py#L58) caused this issue. 
We fixed this temporarily with this:
`altair==4.2.0`

**Environment (please complete the following information):**
 - Running Great expectation in PySpark
 - Great Expectations Version: 0.15.15. We tried to upgrade version to 0.15.46 but it didn't help

**Comment by YevgeniyaLee** [comment]
Correct me If I am wrong, please, because I am not sure, but seems to me it could be somehow fixed by freezing dependencies instead of the pip range operator like [here](https://github.com/great-expectations/great_expectations/blob/9973a1cfb0f4794b8b0161e16c19c1610eeba03a/requirements.txt#L1) .

**Comment by talagluck** [comment]
Resolved by #6984
