### ISSUE TITLE
Data docs rendering crashes within 'expect_column_values_to_not_be_in_set' expectation_suite

### ISSUE THREAD

**Issue by kristinalviv** [fivetran/great_expectations#7002]
**Describe the bug**
Data docs rendering crashes with exception when running 'expect_column_values_to_not_be_in_set' expectation_suite.

I need to check that all values within specific columns are not empty. These columns have string datatype, hence 'expect_column_values_to_not_be_null' is not suitable (since it don't count empty string as null), hence I use 'expect_column_values_to_not_be_in_set'.
Tried to run _**the same value_set**_ with 'expect_column_values_to_be_in_set' and 'expect_column_values_to_not_be_in_set' expectation types - _**'expect_column_values_to_be_in_set' does not have any errors when rendering data docs, while 'expect_column_values_to_not_be_in_set' throws exception when data docs rendering is performed.**_ 
(e.g. "value_set": [""], which empty string; or "value_set": ["current"]) - both fails within expect_column_values_to_not_be_in_set', while successfull within 'expect_column_values_to_be_in_set' '.

Analyzed differences between those two expectations - maybe the bug fix [BUGFIX] Fixes ExpectColumnValuesToBeInSet to enable behavior indicated in Parameterized Expectations Doc #4455 (https://github.com/great-expectations/great_expectations/commit/b45edb527e6957cd5c18167e260a3d2adb779303#diff-02f563979277158ee3cd5ca5445ce25f85582c43e5ead67f411fc0559a8d3b53R414) to 'expect_column_values_to_be_in_set ' can be the reason? And should be also implemented per 'expect_column_values_to_not_be_in_set'?

**To Reproduce**
1. Add 'expect_column_values_to_not_be_in_set' expectation_suite  
2. Run the suite
3. Check the logs

**Expected behavior** Data docs rendering performed successfully
Actual behavior: Data docs rendering crashes.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.15.46, main

**Additional context**
An unexpected Exception occurred during data docs rendering. Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether. Please use the trace, included in this message, to diagnose and repair the underlying issue. Detailed information follows:        AttributeError: "'NoneType' object has no attribute 'kwargs'". Traceback: "Traceback (most recent call last):  File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/render/renderer/content_block/content_block.py", line 112, in _render_list    **kwargs,  File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/render/renderer/renderer.py", line 14, in inner_func    return renderer_fn(*args, **kwargs)  File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/expectations/expectation.py", line 151, in inner_func    ] = render_func(*args, **kwargs)  File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py", line 215, in _prescriptive_renderer    runtime_configuration=runtime_configuration,  File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/render/renderer_configuration.py", line 174, in __init__    super().__init__(**values)  File "pydantic/main.py", line 340, in pydantic.main.BaseModel.__init__  File "pydantic/main.py", line 1103, in pydantic.main.validate_model  File "/home/spark/.local/lib/python3.7/site-packages/great_expectations/render/renderer_configuration.py", line 350, in _validate_for_row_condition    kwargs = values["configuration"].kwargsAttributeError: 'NoneType' object has no attribute 'kwargs'".

**Comment by rdodev** [comment]
Hey @kristinalviv thanks for reporting this issue. Let me take a look and see what could be going on.

**Comment by talagluck** [comment]
Hi @kristinalviv - we did a bunch of work in this area recently - is this still an issue for you?

**Comment by talagluck** [comment]
I believe it was resolved by #6990

**Comment by alexsherstinsky** [comment]
Closing as per `https://github.com/great-expectations/great_expectations/issues/7002#issuecomment-1488348957`.
