### ISSUE TITLE
[Docs] Typo in How to trigger Email as an Action

### ISSUE THREAD

**Issue by ruankie** [fivetran/great_expectations#7003]
**Describe the bug**
There is a minor typo in the page describing [How to trigger Email as an Action](https://docs.greatexpectations.io/docs/guides/validation/validation_actions/how_to_trigger_email_as_a_validation_action):
In the Prerequisites section, the word `Checkpoint` is misspelt as `Checlpoint` 

**To Reproduce**
1. Go to the docs page [How to trigger Email as an Action](https://docs.greatexpectations.io/docs/guides/validation/validation_actions/how_to_trigger_email_as_a_validation_action)
2. See the prerequisites section near the top of the page.

**Expected behavior**
The reference to the checkpoint object must be spelled correctly: `Checkpoint`

**Environment (please complete the following information):**
- N/A

**Comment by ruankie** [comment]
Please assign to me, I'll take a look :)

**Comment by ruankie** [comment]
Fixed in PR #7004 
Awaiting approval

**Comment by rdodev** [comment]
Hey @ruankie 👋 thanks for catching this! I have approved the PR.
