### ISSUE TITLE
[Docs] Incorrect instructions for setting up email validation actions

### ISSUE THREAD

**Issue by ruankie** [fivetran/great_expectations#7006]
**Describe the bug**
The instructions for adding an email validation action are confusing. It tells you to add the config in the wrong file. It looks like this instruction came from a previous version where these config changes had to be made in a different file. It should be updated to be consistent with the new version of Great Expectations.

What the current docs tell you to do:
    - Add config for an email validation action to the `great_expectations.yml` file.

What the docs should tell you to do:
    - Add config for an email validation action to your checkpoint's `.yml` file.

**To Reproduce**
1. Go to the docs page [How to trigger Email as an Action](https://docs.greatexpectations.io/docs/guides/validation/validation_actions/how_to_trigger_email_as_a_validation_action)
2. Scroll down to [Section 2](https://docs.greatexpectations.io/docs/guides/validation/validation_actions/how_to_trigger_email_as_a_validation_action/#2-update-action_list-in-your-checkpoint-configuration)
3. See it suggests adding the config snippet to your `great_expectations.yml` file (this is incorrect).

**Expected behavior**
[Section 2](https://docs.greatexpectations.io/docs/guides/validation/validation_actions/how_to_trigger_email_as_a_validation_action/#2-update-action_list-in-your-checkpoint-configuration) of the docs should instead tell you to paste the yml config snippet in the relevant checkpoint folder (the checkpoint that must trigger an email upon completion).

**Comment by ruankie** [comment]
Please assign me, I'll take a look 😁

**Comment by rdodev** [comment]
Hey @ruankie really appreciate you looking for issues in our docs. Before you do any work, I'd like @Rachel-Reverie to chime in here and make sure desired goals are being met or if changes are needed.

**Comment by ruankie** [comment]
No problem @rdodev 
I went through it earlier today to set up some email validation triggers with Great Expectations and found the current instructions a little confusing. I eventually found the solution by looking at how to add other validation actions. Just thought I'd take a stab at clarifying the process.

**Comment by rdodev** [comment]
@ruankie thanks for that, truly. I have consulted with internal folks and your fix works great.
