### ISSUE TITLE
Extra filepath error in Slack notification

### ISSUE THREAD

**Issue by data-han** [fivetran/great_expectations#7016]
**Describe the bug**
Since upgrading (i think) to 15.43, the slack notification includes extra filepath error at the top. Im wondering what config I can change to remove it? (SS1 shows current, SS2 shows previous which is what I wanted) 

**To Reproduce**

**Expected behavior**
The extra line at the top should not been there

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]: MacOS
 - Great Expectations Version: [e.g. 0.13.2]: 0.15.46

SS1: After (current state)
![image](https://user-images.githubusercontent.com/51312880/215975552-5f817fb3-d892-4431-bec7-bf9c048f7288.png)
SS2: Before (what i want)
![image](https://user-images.githubusercontent.com/51312880/215975608-7595744c-3d53-49d5-a7db-4b7c511486c0.png)

checkpoint yml
![image](https://user-images.githubusercontent.com/51312880/215975850-e724efc4-d4c8-4948-a42e-282a1de6369e.png)

**Additional context**

**Comment by rdodev** [comment]
Hey @data-han thanks for raising this issue. Let me dig in for a bit and will get back to you.

**Comment by data-han** [comment]
Is this still being looked into? @rdodev

**Comment by data-han** [comment]
@rachhouse if you know @rdodev is available or someone else

**Comment by data-han** [comment]
@rachhouse Hi Rachel, sorry to bring you in, but have you seen this issue before and know a fix to this?
