### ISSUE TITLE
Change Result Format logic to not be additive or at least have a way to opt out

### ISSUE THREAD

**Issue by jmcorreia** [fivetran/great_expectations#7017]
**Description:**
The RESULT_FORMAT has an additive nature, so more detailed the RESULT_FORMAT, more keywords are added to the return. However, people using always "COMPLETE", for example, are, for sure, not interested in the "partial..." keywords. 

**Proposed Solutions**
Thus, the logic should be changed, not to be additive, but to have 1-1 relationship between keywords and RESULT_FORMAT selected. 
If this is technically not possible or do not make sense, I would say that at least for the COMPLETE RESULT_FORMAT, a an opt out flag should be available to chose if people want the "partial" keywords or not, for example.

**Comment by rdodev** [comment]
Hey @jmcorreia thanks for this.

I will bring this up and discuss with our engineers and determine what next steps, if any, we can take here. FWIW, `result_format` is something we've struggled with and there are currently plans to revamp this area -- nothing concrete I can share though.

**Comment by jmcorreia** [comment]
Hi @rdodev ,

thanks for the fast answer. Well that is good and bad to hear ahah. We currently have logic built around the results returned and thus around the result_format, so I will definitely be interested in hearing about any plans to revamp it in advance.
Thanks again!

**Comment by austiezr** [comment]
Hey @jmcorreia! Wanted to let you know we've captured this for our internal backlog; we'll leave this Issue open for the next week if you have any further input here, otherwise we'll close out.

**Comment by jmcorreia** [comment]
Hi @austiezr , @rdodev ,
just curious, was there any progress? :)

**Comment by austiezr** [comment]
Hey @jmcorreia! I'm no longer working on GX, so unfortunately can't provide much insight -- as of my last involvement w/ the codebase ~1 year ago, there hadn't been any change here, but @adeola-ak (👋) may have more recent info!
