### ISSUE TITLE
clash with another protobuf version

### ISSUE THREAD

**Issue by diman82** [fivetran/great_expectations#7026]
**Describe the bug**
DAG contating great_expecations opeartor in astronomer airflow environment - doesn't load

**To Reproduce**
1. Restart astronomer airflow environment

**Expected behavior**
DAG is succsesfully loaded

**Environment (please complete the following information):**
 - Operating System: Linux (docker on vm)
 - Great Expectations Version: 0.15.46

**Additional context**
```
Broken DAG: [/usr/local/airflow/dags/great_expectations/great_expectations_athena.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/google/cloud/secretmanager_v1/proto/resources_pb2.py", line 57, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by rdodev** [comment]
Hey @diman82 👋 

The folks at astronomer are now the owners and maintainers of this [operator](https://github.com/astronomer/airflow-provider-great-expectations). Did you try reaching out to them about this issue?

**Comment by diman82** [comment]
Thanks, I wasn't aware!
Will reach them.
