### ISSUE TITLE
connect to mysql5.7 throw ObjectNotExecutableError

### ISSUE THREAD

**Issue by chaozwn** [fivetran/great_expectations#7030]
**Describe the bug**
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/51357674/216347171-de9236c7-7212-4747-8c4e-204e4eb2c389.png">

when i run in mysql, this sql is correct.
![image](https://user-images.githubusercontent.com/51357674/216347663-55eef851-adc2-4d34-9a7c-258a9cf34d76.png)

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: [e.g. 0.13.2]

**Additional context**

**Comment by rdodev** [comment]
Hey @chaozwn 

Would you mind sharing relevant config/code? hard to tell what could be going on based on the screenshot.

**Comment by chaozwn** [comment]
> Hey @chaozwn
> 
> Would you mind sharing relevant config/code? hard to tell what could be going on based on the screenshot.

hi guy,
```
[{'class_name': 'Datasource',
  'data_connectors': {'default_inferred_data_connector_name': {'class_name': 'InferredAssetFilesystemDataConnector',
    'default_regex': {'group_names': ['data_asset_name'], 'pattern': '(.*)'},
    'base_directory': '../data',
    'module_name': 'great_expectations.datasource.data_connector'},
   'default_runtime_data_connector_name': {'class_name': 'RuntimeDataConnector',
    'assets': {'my_runtime_asset_name': {'class_name': 'Asset',
      'batch_identifiers': ['runtime_batch_identifier_name'],
      'module_name': 'great_expectations.datasource.data_connector.asset'}},
    'module_name': 'great_expectations.datasource.data_connector'}},
  'name': 'getting_started_datasource',
  'execution_engine': {'module_name': 'great_expectations.execution_engine',
   'class_name': 'PandasExecutionEngine'},
  'module_name': 'great_expectations.datasource'},
 {'class_name': 'Datasource',
  'data_connectors': {'default_runtime_data_connector_name': {'class_name': 'RuntimeDataConnector',
    'batch_identifiers': ['default_identifier_name'],
    'module_name': 'great_expectations.datasource.data_connector'},
   'default_inferred_data_connector_name': {'class_name': 'InferredAssetSqlDataConnector',
    'introspection_directives': {'schema_name': 'test'},
    'module_name': 'great_expectations.datasource.data_connector',
    'include_schema_name': True},
   'default_configured_data_connector_name': {'class_name': 'ConfiguredAssetSqlDataConnector',
    'assets': {'test1': {'class_name': 'Asset',
      'schema_name': 'test',
      'module_name': 'great_expectations.datasource.data_connector.asset'}},
    'module_name': 'great_expectations.datasource.data_connector'}},
  'name': 'mysql57',
  'execution_engine': {'module_name': 'great_expectations.execution_engine',
   'class_name': 'SqlAlchemyExecutionEngine',
   'credentials': {'host': 'localhost',
    'port': '40057',
    'username': 'root',
    'password': 123456,
    'database': 'test',
    'drivername': 'mysql+pymysql'}},
  'module_name': 'great_expectations.datasource'}]
```


Now you can close this notebook and delete it!

**Comment by chaozwn** [comment]
> Hey @chaozwn
> 
> Would you mind sharing relevant config/code? hard to tell what could be going on based on the screenshot.

{
  "data_asset_type": null,
  "expectation_suite_name": "mysql57_test1",
  "expectations": [],
  "ge_cloud_id": null,
  "meta": {
    "citations": [
      {
        "batch_request": {
          "data_asset_name": "test.test1",
          "data_connector_name": "default_inferred_data_connector_name",
          "datasource_name": "mysql57",
          "limit": 1000
        },
        "citation_date": "2023-02-03T02:47:09.920501Z",
        "comment": "Created suite added via CLI"
      }
    ],
    "great_expectations_version": "0.15.46"
  }
}

**Comment by rdodev** [comment]
Hey @chaozwn thanks for that. tThere is a lot going on in those configs. What is the use case here?

**Comment by abuchanan920** [comment]
FWIW - I'm seeing the exact same error.

**Comment by ghurruprasath** [comment]
@abuchanan920 @rdodev @chaozwn 

Stuck with the same error. Any idea how to fix this ?

![image](https://user-images.githubusercontent.com/39903300/218111931-0cac6818-e504-4814-a13a-a4b5bbff2065.png)

**Comment by austiezr** [comment]
Hey folks! If you're able to share your Great Expectations versions, complete stack trace, **as well as the workflow generating these errors**, that will help us to better investigate what may be happening here. Please remove any PII first!

**Comment by austiezr** [comment]
@abuchanan920 @ghurruprasath Are the two of you able to share your datasource configs as well?

**Comment by chaozwn** [comment]
> Hey @chaozwn thanks for that. tThere is a lot going on in those configs. What is the use case here?

hi, maybe you can build mysql57 in docker-compose.
Dockerfile：
```
FROM mysql:5.7

LABEL maintainer="dtstack"
```

Docker Compose:
```
version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}


services:
  chunjun-mysql5.7:
    build:
      context: ./mysql5.7
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL57_USERNAME}               
      - MYSQL_PASSWORD=${MYSQL57_PASSWORD}            
      - MYSQL_ROOT_PASSWORD=${MYSQL57_ROOT_PASSWORD}  
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/mysql57:/var/lib/mysql     
    ports:
      - "${MYSQL57_PORT}:3306"                       
    networks:
      - backend
    restart: always
```

maybe you can use [great_expectations](https://github.com/great-expectations/great_expectations) step by step config mysql, then you will find same problem.

**Comment by ghurruprasath** [comment]
/usr/lib64/python3.11/inspect.py:573: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getter(object, key)
/usr/lib64/python3.11/inspect.py:573: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getter(object, key)
/usr/lib64/python3.11/inspect.py:573: FutureWarning: pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getter(object, key)
2023-02-13T11:48:49+0000 - INFO - Great Expectations logging enabled at 20 level by JupyterUX module.
2023-02-13T11:48:49+0000 - INFO - FileDataContext loading zep config
2023-02-13T11:48:50+0000 - INFO - GxConfig.parse_yaml() failed with errors - [{'loc': ('xdatasources',), 'msg': 'field required', 'type': 'value_error.missing'}]
2023-02-13T11:48:50+0000 - INFO - GxConfig.parse_yaml() returning empty `xdatasources`
2023-02-13T11:48:50+0000 - INFO - Loading 'datasources' ->
{}
2023-02-13T11:48:50+0000 - INFO - Loaded 'datasources' ->
{}
Loaded ExpectationSuite "test_6" containing 0 expectations.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File /usr/local/lib64/python3.11/site-packages/sqlalchemy/engine/base.py:1410, in Connection.execute(self, statement, parameters, execution_options)
   1409 try:
-> 1410     meth = statement._execute_on_connection
   1411 except AttributeError as err:

AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

ObjectNotExecutableError                  Traceback (most recent call last)
Cell In[1], line 28
     24     suite = context.create_expectation_suite(expectation_suite_name=expectation_suite_name)
     25     print(f'Created ExpectationSuite "{suite.expectation_suite_name}".')
---> 28 validator = context.get_validator(
     29     batch_request=BatchRequest(**batch_request),
     30     expectation_suite_name=expectation_suite_name
     31 )
     32 column_names = [f'"{column_name}"' for column_name in validator.columns()]
     33 print(f"Columns: {', '.join(column_names)}.")

File /usr/local/lib/python3.11/site-packages/great_expectations/data_context/data_context/abstract_data_context.py:1862, in AbstractDataContext.get_validator(self, datasource_name, data_connector_name, data_asset_name, batch, batch_list, batch_request, batch_request_list, batch_data, data_connector_query, batch_identifiers, limit, index, custom_filter_function, sampling_method, sampling_kwargs, splitter_method, splitter_kwargs, runtime_parameters, query, path, batch_filter_parameters, expectation_suite_ge_cloud_id, batch_spec_passthrough, expectation_suite_name, expectation_suite, create_expectation_suite_with_name, include_rendered_content, **kwargs)
   1858         batch_request_list = [batch_request]  # type: ignore[list-item]
   1860     for batch_request in batch_request_list:
   1861         batch_list.extend(
-> 1862             self.get_batch_list(
   1863                 datasource_name=datasource_name,
   1864                 data_connector_name=data_connector_name,
   1865                 data_asset_name=data_asset_name,
   1866                 batch_request=batch_request,
   1867                 batch_data=batch_data,
   1868                 data_connector_query=data_connector_query,
   1869                 batch_identifiers=batch_identifiers,
   1870                 limit=limit,
   1871                 index=index,
   1872                 custom_filter_function=custom_filter_function,
   1873                 sampling_method=sampling_method,
   1874                 sampling_kwargs=sampling_kwargs,
   1875                 splitter_method=splitter_method,
   1876                 splitter_kwargs=splitter_kwargs,
   1877                 runtime_parameters=runtime_parameters,
   1878                 query=query,
   1879                 path=path,
   1880                 batch_filter_parameters=batch_filter_parameters,
   1881                 batch_spec_passthrough=batch_spec_passthrough,
   1882                 **kwargs,
   1883             )
   1884         )
   1886 return self.get_validator_using_batch_list(
   1887     expectation_suite=expectation_suite,  # type: ignore[arg-type]
   1888     batch_list=batch_list,
   1889     include_rendered_content=include_rendered_content,
   1890 )

File /usr/local/lib/python3.11/site-packages/great_expectations/core/usage_statistics/usage_statistics.py:314, in usage_statistics_enabled_method.<locals>.usage_statistics_wrapped_method(*args, **kwargs)
    311     if args_payload_fn is not None:
    312         nested_update(event_payload, args_payload_fn(*args, **kwargs))
--> 314     result = func(*args, **kwargs)
    315     message["success"] = True
    316 except Exception:

File /usr/local/lib/python3.11/site-packages/great_expectations/data_context/data_context/abstract_data_context.py:2014, in AbstractDataContext.get_batch_list(self, datasource_name, data_connector_name, data_asset_name, batch_request, batch_data, data_connector_query, batch_identifiers, limit, index, custom_filter_function, sampling_method, sampling_kwargs, splitter_method, splitter_kwargs, runtime_parameters, query, path, batch_filter_parameters, batch_spec_passthrough, **kwargs)
   1938 @public_api
   1939 @usage_statistics_enabled_method(
   1940     event_name=UsageStatsEvents.DATA_CONTEXT_GET_BATCH_LIST,
   (...)
   1964     **kwargs: Optional[dict],
   1965 ) -> List[Batch]:
   1966     """Get the list of zero or more batches, based on a variety of flexible input types.
   1967 
   1968     `get_batch_list` is the main user-facing API for getting batches.
   (...)
   2012 
   2013     """
-> 2014     return self._get_batch_list(
   2015         datasource_name=datasource_name,
   2016         data_connector_name=data_connector_name,
   2017         data_asset_name=data_asset_name,
   2018         batch_request=batch_request,
   2019         batch_data=batch_data,
   2020         data_connector_query=data_connector_query,
   2021         batch_identifiers=batch_identifiers,
   2022         limit=limit,
   2023         index=index,
   2024         custom_filter_function=custom_filter_function,
   2025         sampling_method=sampling_method,
   2026         sampling_kwargs=sampling_kwargs,
   2027         splitter_method=splitter_method,
   2028         splitter_kwargs=splitter_kwargs,
   2029         runtime_parameters=runtime_parameters,
   2030         query=query,
   2031         path=path,
   2032         batch_filter_parameters=batch_filter_parameters,
   2033         batch_spec_passthrough=batch_spec_passthrough,
   2034         **kwargs,
   2035     )

File /usr/local/lib/python3.11/site-packages/great_expectations/data_context/data_context/abstract_data_context.py:2091, in AbstractDataContext._get_batch_list(self, datasource_name, data_connector_name, data_asset_name, batch_request, batch_data, data_connector_query, batch_identifiers, limit, index, custom_filter_function, sampling_method, sampling_kwargs, splitter_method, splitter_kwargs, runtime_parameters, query, path, batch_filter_parameters, batch_spec_passthrough, **kwargs)
   2085 else:
   2086     raise gx_exceptions.DatasourceError(
   2087         datasource_name,
   2088         "The given datasource could not be retrieved from the DataContext; "
   2089         "please confirm that your configuration is accurate.",
   2090     )
-> 2091 return datasource.get_batch_list_from_batch_request(batch_request=batch_request)

File /usr/local/lib/python3.11/site-packages/great_expectations/datasource/new_datasource.py:214, in BaseDatasource.get_batch_list_from_batch_request(self, batch_request)
    208 batch_spec: PathBatchSpec  # type: ignore[no-redef]
    209 batch_markers: BatchMarkers  # type: ignore[no-redef]
    210 (
    211     batch_data,
    212     batch_spec,
    213     batch_markers,
--> 214 ) = data_connector.get_batch_data_and_metadata(
    215     batch_definition=batch_definition
    216 )
    217 new_batch = Batch(
    218     data=batch_data,
    219     batch_request=batch_request,
   (...)
    222     batch_markers=batch_markers,
    223 )
    224 batches.append(new_batch)

File /usr/local/lib/python3.11/site-packages/great_expectations/datasource/data_connector/data_connector.py:115, in DataConnector.get_batch_data_and_metadata(self, batch_definition)
    106 """
    107 Uses batch_definition to retrieve batch_data and batch_markers by building a batch_spec from batch_definition,
    108 then using execution_engine to return batch_data and batch_markers
   (...)
    112 
    113 """
    114 batch_spec: BatchSpec = self.build_batch_spec(batch_definition=batch_definition)
--> 115 batch_data, batch_markers = self._execution_engine.get_batch_data_and_markers(
    116     batch_spec=batch_spec
    117 )
    118 self._execution_engine.load_batch_data(batch_definition.id, batch_data)
    119 return (
    120     batch_data,
    121     batch_spec,
    122     batch_markers,
    123 )

File /usr/local/lib/python3.11/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py:1259, in SqlAlchemyExecutionEngine.get_batch_data_and_markers(self, batch_spec)
   1255 elif isinstance(batch_spec, SqlAlchemyDatasourceBatchSpec):
   1256     selectable: Union[Selectable, str] = self._build_selectable_from_batch_spec(
   1257         batch_spec=batch_spec
   1258     )
-> 1259     batch_data = SqlAlchemyBatchData(
   1260         execution_engine=self,
   1261         selectable=selectable,
   1262         create_temp_table=create_temp_table,
   1263         source_table_name=source_table_name,
   1264         source_schema_name=source_schema_name,
   1265     )
   1267 return batch_data, batch_markers

File /usr/local/lib/python3.11/site-packages/great_expectations/execution_engine/sqlalchemy_batch_data.py:161, in SqlAlchemyBatchData.__init__(self, execution_engine, record_set_name, schema_name, table_name, query, selectable, create_temp_table, temp_table_schema_name, use_quoted_name, source_schema_name, source_table_name)
    154         else:
    155             # compile selectable to sql statement
    156             query = selectable.compile(
    157                 dialect=self.sql_engine_dialect,
    158                 compile_kwargs={"literal_binds": True},
    159             )
--> 161     self._create_temporary_table(
    162         temp_table_name=generated_table_name,
    163         query=query,
    164         temp_table_schema_name=temp_table_schema_name,
    165     )
    166     self._selectable = sa.Table(
    167         generated_table_name,
    168         sa.MetaData(),
    169         schema=temp_table_schema_name,
    170     )
    171 else:

File /usr/local/lib/python3.11/site-packages/great_expectations/execution_engine/sqlalchemy_batch_data.py:295, in SqlAlchemyBatchData._create_temporary_table(self, temp_table_name, query, temp_table_schema_name)
    293         self._engine.execute(stmt_2)
    294 else:
--> 295     self._engine.execute(stmt)

File /usr/local/lib64/python3.11/site-packages/sqlalchemy/engine/base.py:1412, in Connection.execute(self, statement, parameters, execution_options)
   1410     meth = statement._execute_on_connection
   1411 except AttributeError as err:
-> 1412     raise exc.ObjectNotExecutableError(statement) from err
   1413 else:
   1414     return meth(
   1415         self,
   1416         distilled_parameters,
   1417         execution_options or NO_OPTIONS,
   1418     )

ObjectNotExecutableError: Not an executable object: 'SELECT * \ninto #ge_temp_352d91f0 from [BrXXXXg].[St_XXXLink] \nWHERE 1 = 1'

**Comment by ghurruprasath** [comment]
@austiezr  I get the above error when executing the validator code in the expectation suite.

**Comment by cmsachin610** [comment]
Similar error in MSSQL also. statement is a string (Insert to temp table) and doesn't have _execute_on_connection attribute

great_expectations\execution_engine\sqlalchemy_batch_data.py:161, in SqlAlchemyBatchData.__init__(self, execution_engine, record_set_name, schema_name, table_name, query, selectable, create_temp_table, temp_table_schema_name, use_quoted_name, source_schema_name, source_table_name)
    154         else:
    155             # compile selectable to sql statement
    156             query = selectable.compile(
    157                 dialect=self.sql_engine_dialect,
    158                 compile_kwargs={"literal_binds": True},
    159             )
--> 161     self._create_temporary_table(
    162         temp_table_name=generated_table_name,
    163         query=query,
    164         temp_table_schema_name=temp_table_schema_name,
    165     )
    166     self._selectable = sa.Table(
    167         generated_table_name,
    168         sa.MetaData(),
    169         schema=temp_table_schema_name,
    170     )
    171 else:
\great_expectations\execution_engine\sqlalchemy_batch_data.py:295, in SqlAlchemyBatchData._create_temporary_table(self, temp_table_name, query, temp_table_schema_name)
    293         self._engine.execute(stmt_2)
    294 else:
--> 295     self._engine.execute(stmt)
sqlalchemy\engine\base.py:1412, in Connection.execute(self, statement, parameters, execution_options)
   1410     meth = statement._execute_on_connection
   1411 except AttributeError as err:
-> 1412     raise exc.ObjectNotExecutableError(statement) from err
   1413 else:
   1414     return meth(
   1415         self,
   1416         distilled_parameters,
   1417         execution_options or NO_OPTIONS,
   1418     )

**Comment by hieu2102** [comment]
I'm getting similiar error with MySQL Enterprise 8.0

Expectation suite JSON
```json
{
  "data_asset_type": null,
  "expectation_suite_name": "yellow_tripdata_sample.warning",
  "expectations": [],
  "ge_cloud_id": null,
  "meta": {
    "citations": [
      {
        "batch_request": {
          "data_asset_name": "yellow_tripdata_sample",
          "data_connector_name": "default_configured_data_connector_name",
          "datasource_name": "my_datasource",
          "limit": 1000
        },
        "citation_date": "2023-02-20T06:01:03.233778Z",
        "comment": "Created suite added via CLI"
      }
    ],
    "great_expectations_version": "0.15.49"
  }
}
```
Stacktrace when calling `context.get_validator`

```
2023-02-20T13:14:08+0700 - INFO - Great Expectations logging enabled at 20 level by JupyterUX module.
2023-02-20T13:14:08+0700 - INFO - FileDataContext loading zep config
2023-02-20T13:14:08+0700 - INFO - GxConfig.parse_yaml() failed with errors - [{'loc': ('xdatasources',), 'msg': 'field required', 'type': 'value_error.missing'}]
2023-02-20T13:14:08+0700 - INFO - GxConfig.parse_yaml() returning empty `xdatasources`
2023-02-20T13:14:08+0700 - INFO - Loading 'datasources' ->
{}
2023-02-20T13:14:08+0700 - INFO - Loaded 'datasources' ->
{}
Traceback (most recent call last):
  File "/Users/code/python/great_expectations/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1410, in execute
    meth = statement._execute_on_connection
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/code/python/great_expectations/expectations.py", line 17, in <module>
    validator = context.get_validator(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/code/python/great_expectations/venv/lib/python3.11/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2410, in get_validator
    self.get_batch_list(
  File "/Users/code/python/great_expectations/venv/lib/python3.11/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 318, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/code/python/great_expectations/venv/lib/python3.11/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2577, in get_batch_list
    return self._get_batch_list(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/code/python/great_expectations/venv/lib/python3.11/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2654, in _get_batch_list
    return datasource.get_batch_list_from_batch_request(batch_request=batch_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/code/python/great_expectations/venv/lib/python3.11/site-packages/great_expectations/datasource/new_datasource.py", line 214, in get_batch_list_from_batch_request
    ) = data_connector.get_batch_data_and_metadata(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/code/python/great_expectations/venv/lib/python3.11/site-packages/great_expectations/datasource/data_connector/data_connector.py", line 119, in get_batch_data_and_metadata
    batch_data, batch_markers = self._execution_engine.get_batch_data_and_markers(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/code/python/great_expectations/venv/lib/python3.11/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 1290, in get_batch_data_and_markers
    batch_data = SqlAlchemyBatchData(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/code/python/great_expectations/venv/lib/python3.11/site-packages/great_expectations/execution_engine/sqlalchemy_batch_data.py", line 161, in __init__
    self._create_temporary_table(
  File "/Users/code/python/great_expectations/venv/lib/python3.11/site-packages/great_expectations/execution_engine/sqlalchemy_batch_data.py", line 295, in _create_temporary_table
    self._engine.execute(stmt)
  File "/Users/code/python/great_expectations/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'CREATE TEMPORARY TABLE ge_temp_bc469060 AS SELECT * \nFROM kafka.yellow_tripdata_sample \nWHERE true = 1'
```

**Comment by hieu2102** [comment]
Hi guy, 

I downgraded  SQLAlchemy from  `SQLAlchemy==2.0.4` to `SQLAlchemy==1.4.0` and it is working as expected

**Comment by ghurruprasath** [comment]
@hieu2102 Thank you. Downgrading SQL alchemy fixed the issue.

**Comment by rdodev** [comment]
hey all 👋 

I want to confirm here that GX does _not_ presently support SQLAlchemy 2+. Downgrading to latest non-v2 release of SQLAlchemy should fix many of the issues being observed.

**Comment by talagluck** [comment]
Thanks all - closing, since this appears to be linked to the SQL Alchemy version. We are working on adding support for SQLA 2, and will share widely when that is complete.
