### ISSUE TITLE
convert_to_json_serializable throws TypeError for np.datetime64 objects

### ISSUE THREAD

**Issue by klatifch** [fivetran/great_expectations#7042]
**Describe the bug**
[`convert_to_json_serializable`](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/core/util.py#L257) function can not serialize `np.datetime64` objects, causing issues during the rendering stage when baseline data is pulled from a database e.g. MySQL or otherwise. This bug is somewhat related to #6514.

**To Reproduce**
```
import numpy as np
from great_expectations.core.util import convert_to_json_serializable


dt64_obj = np.datetime64('2023-02-01T11:22:33.000000000')

print(
    convert_to_json_serializable(dt64_obj)  # Throws TypeError
)
```

**Expected behavior**
Serialization support for `np.datetime64` objects may be added in `convert_to_json_serializable` function. Example solution below:

```
    # To be added in great_expectations.core.util#convert_to_json_serializable function
    if isinstance(data, np.datetime64):
        return pd.Timestamp(data).isoformat()
```

**Comment by rdodev** [comment]
Hey @klatifch thanks for bringing this to our attention. I'll make sure to bring it to the attention of engineering.

**Comment by tmilitino** [comment]
Maybe the PR #6553  it solved this issue

**Comment by klatifch** [comment]
I was using 0.15.32 and switching to the latest version 0.15.47 solved this issue. Thank you!
