### ISSUE TITLE
[FEATURE] Include Data Quality Dimensions with each Expectations

### ISSUE THREAD

**Issue by data-han** [fivetran/great_expectations#7043]
**Is your feature request related to a problem? Please describe.**
Data quality dimensions include completeness, consistency, timeliness, validity, and uniqueness. If there is a way to tag each test case and in the Data Doc or some sort, shows up visualisation to tell users what is the overall quality % based on each dimension, that'd be nice. It can serve as a overall data quality report .

**Describe the solution you'd like**
when asserting an expectation, there is a way to include meta data. Right now, we can add 'notes' that will appear in Data Doc to tell us the description of each expectation in the expectation suite. What if there is another meta data e.g. 'tag' to let us tag each expectations? like in SS here 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/51312880/216639734-f5669dfe-9ac1-47aa-bf05-6f54fb33f4c1.png">

For example, 'Consistency' : At many companies, the same information may be stored in more than one place. If that information matches, it’s considered “consistent.”
IF we can compare the value of one column (table A at source) and another column (table B at downstream) to be the same then it is consistent. Using `expect_multicolumn_sum_to_equal` we may be able to do that

**Describe alternatives you've considered**

**Additional context**
Googled a dashboard screenshot
<img width="617" alt="image" src="https://user-images.githubusercontent.com/51312880/216639392-9f49bf7c-c412-43ea-83eb-c1fd63047a91.png">

**Comment by rdodev** [comment]
Hey @data-han thanks for this feature/idea. I will raise with Product management.

**Comment by talagluck** [comment]
Hi @data-han - thanks again for raising this. This is a really cool idea. We likely won't be able to prioritize this in the immediate future, so I'm going to close this for now, but we've logged this product feedback and will be in touch if and when we are able to work on it.
