### ISSUE TITLE
"expect_column_values_to_be_between" expectation is not working with zero as input

### ISSUE THREAD

**Issue by MohamedAliHamza** [fivetran/great_expectations#7082]
I'm trying to use `expect_column_values_to_be_between`  expectation by setting  **`min_value = 0`** & `max_value = 100` but I'm receiving this error;

> "exception_message": "Provided min threshold must be a datetime (for datetime columns) or number"

which comes from this [portion](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/expectations/expectation.py#L2315) of the code base.

I've tried to set another value of `min_value` with for instance 1 or -1 and it works fine, the only issue is with **zero** as input for `min_value` .

great-expectations version= "0.15.44"
[Slack Thread](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1675860806708059) 
full error traceback;

> "Traceback (most recent call last):\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/expectations/expectation.py\", line 2233, in validate_metric_value_between_configuration\n    assert (\nAssertionError: Provided min threshold must be a datetime (for datetime columns) or number\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/validator/validator.py\", line 1047, in graph_validate\n    result = configuration.metrics_validate(\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/core/expectation_configuration.py\", line 1428, in metrics_validate\n    return expectation_impl(self).metrics_validate(\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/expectations/expectation.py\", line 339, in __init__\n    self.validate_configuration(configuration=configuration)\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_values_to_be_between.py\", line 266, in validate_configuration\n    self.validate_metric_value_between_configuration(configuration=configuration)\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/expectations/expectation.py\", line 2254, in validate_metric_value_between_configuration\n    raise InvalidExpectationConfigurationError(str(e))\ngreat_expectations.exceptions.exceptions.InvalidExpectationConfigurationError: Provided min threshold must be a datetime (for datetime columns) or number\n",
        "exception_message": "Provided min threshold must be a datetime (for datetime columns) or number",

**Comment by austiezr** [comment]
Hey @MohamedAliHamza! Thanks for reaching out. Are you able to provide the config for this expectation?

**Comment by MohamedAliHamza** [comment]
Hi @austiezr, I'm not sure if I could do so since there were another developer in my team who's implemented that portion and I'm not fully aware of, but I could provide you with additional info like;
```
ExecutionEngine class name: SparkDFExecutionEngine
Data Connectors: runtime_connector:RuntimeDataConnector 
```
also our reference to integrate with GX was this [one](https://colab.research.google.com/drive/1CV69el6lrIHGDx-e9FDT-RWvahWW_7sS?usp=sharing#scrollTo=W3XIJ2ZYnFLI) . 

and this is the checkpoint result;

> {
  "evaluation_parameters": {},
  "meta": {
    "great_expectations_version": "0.15.44",
    "expectation_suite_name": "test-suite",
    "run_id": {
      "run_time": "2023-02-09T19:23:36.344930+00:00",
      "run_name": "DestinationPort match regex"
    },
    "batch_spec": {
      "data_asset_name": "test_source_20230209",
      "batch_data": "SparkDataFrame"
    },
    "batch_markers": {
      "ge_load_time": "20230209T192336.348589Z"
    },
    "active_batch_definition": {
      "datasource_name": "test-source",
      "data_connector_name": "runtime_connector",
      "data_asset_name": "test_source_20230209",
      "batch_identifiers": {
        "run_id": "my_source_partition_date=20230209_runtime=20230209"
      }
    },
    "validation_time": "20230209T192336.351817Z",
    "checkpoint_name": "test-suite_checkpoint",
    "validation_id": null,
    "checkpoint_id": null
  },
  "results": [
    {
      "result": {},
      "exception_info": {
        "exception_traceback": "Traceback (most recent call last):\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/expectations/expectation.py\", line 2233, in validate_metric_value_between_configuration\n    assert (\nAssertionError: Provided min threshold must be a datetime (for datetime columns) or number\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/validator/validator.py\", line 1047, in graph_validate\n    result = configuration.metrics_validate(\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/core/expectation_configuration.py\", line 1428, in metrics_validate\n    return expectation_impl(self).metrics_validate(\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/expectations/expectation.py\", line 339, in __init__\n    self.validate_configuration(configuration=configuration)\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_values_to_be_between.py\", line 266, in validate_configuration\n    self.validate_metric_value_between_configuration(configuration=configuration)\n  File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-cb733919-ebe1-4b99-a524-6fc78ae8df1c/lib/python3.9/site-packages/great_expectations/expectations/expectation.py\", line 2254, in validate_metric_value_between_configuration\n    raise InvalidExpectationConfigurationError(str(e))\ngreat_expectations.exceptions.exceptions.InvalidExpectationConfigurationError: Provided min threshold must be a datetime (for datetime columns) or number\n",
        "exception_message": "Provided min threshold must be a datetime (for datetime columns) or number",
        "raised_exception": true
      },
      "meta": {},
      "success": false,
      "expectation_config": {
        "kwargs": {
          "column": "RPM",
          "max_value": "100",
          "min_value": "0",
          "batch_id": "d988e94e0d81a9d6e7550ccc3db063af"
        },
        "expectation_type": "expect_column_values_to_be_between",
        "meta": {}
      }
    }
  ],
  "success": false,
  "statistics": {
    "evaluated_expectations": 1,
    "successful_expectations": 0,
    "unsuccessful_expectations": 1,
    "success_percent": 0.0
  }
}

**Comment by austiezr** [comment]
Hey @MohamedAliHamza! Thanks for this context.

There are a couple of things going on here; first, it looks like your `min_value` & `max_value` are be being passed as strings. Normally, this would be completely fine! However, it looks like there's a bug in how we're doing some type parsing for this expectation.

In the short term, passing those both values as integers (`min_value=0` as opposed to `min_value="0"`) should resolve this for you. We'll also address the bug here so this issue doesn't recur in the future. Thank you! 🚀

**Comment by MohamedAliHamza** [comment]
Hey @austiezr  I've tried to pass other values for instance 1 or -1 as a string, not integers and they work fine, that's a bit weird because if the issue comes from the datatype then it is supposed to be raised in all cases. 

also, I don't know why the checkpoint result shows  min_value, max_value as strings while both are integers in the first place.

**Comment by richardohara** [comment]
> However, it looks like there's a bug in how we're doing some type parsing for this expectation.

@austiezr Can you please tell me where the type parsing code is located? I'd like to take a look at it.

**Comment by tyler-hoffman** [comment]
@MohamedAliHamza thanks again for raising this issue.

We haven't yet added the fix for this, but wanted to check that you were able to get unblocked by using integers rather than strings.

> that's a bit weird because if the issue comes from the datatype then it is supposed to be raised in all cases.
For context, we also allow users to pass in datetimes as strings; the error you're seeing here is an artifact of our checks around that. We plan to fix this in the future to allow any string that should be parsable to an int, but for now, we recommend just passing in integers. 

Thanks again, and I hope that helps!

**Comment by richardohara** [comment]
Will something like this resolve the issue?

def is_parseable_int(min_value):
    try:
        int(min_value)
        return True
     except ValueError:
         return False

And then:

assert (
    min_val is None
                or is_parseable_date(min_val)
                or isinstance(min_val, (float, int, dict, datetime.datetime))
                or is_parseable_int(min_val)
            ), "Provided min threshold must be a datetime (for datetime columns) or number"

**Comment by richardohara** [comment]
Will something like this this help resolve the issue?

```python
def is_parseable_int(min_value):
   try:
        int(min_value)
        return True
    except ValueError:
        return False
``` 
And then:

```python
assert (
    min_val is None
            or is_parseable_date(min_val)
            or isinstance(min_val, (float, int, dict, datetime.datetime))
            or is_parseable_int(min_val)
), "Provided min threshold must be a datetime (for datetime columns) or number"
```

**Comment by austiezr** [comment]
Hey @MohamedAliHamza! Closing this out for now as we've captured this internally for our backlog & there looks to be a workaround provided for the short-term. 🙇
