### ISSUE TITLE
[BUG] unexpected_indices cannot be returned without 'unexpected_index_column_names'

### ISSUE THREAD

**Issue by data-han** [fivetran/great_expectations#7119]
**Describe the bug**
Without changing anything, the upgrade from 0.15.47 to 0.15.48 results in this error as shown
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/51312880/218242507-f2986f77-8ed6-4ec4-89de-996c28811ee2.png">

This is due to the fact im using column pair expectations and maybe with the recent id/pk with spark?
<img width="333" alt="image" src="https://user-images.githubusercontent.com/51312880/218242614-ea274122-23ca-4b09-beb4-2a241034232d.png">

Whether i have this  (with result_format)
<img width="784" alt="image" src="https://user-images.githubusercontent.com/51312880/218242533-b0507e3b-c397-4061-bd4a-98841397f51d.png">

or  (without result_format)
<img width="814" alt="image" src="https://user-images.githubusercontent.com/51312880/218242565-1c03a48c-8768-4eff-b94d-85bcf185f8d8.png">

which my checkpoint is default to this
<img width="263" alt="image" src="https://user-images.githubusercontent.com/51312880/218242584-c10e8ba6-4065-442f-85ab-7f42eecc1e81.png">

it shows up with this error

**To Reproduce**

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/51312880/218242507-f2986f77-8ed6-4ec4-89de-996c28811ee2.png">

**Expected behavior**
This error would not have shown (for all the pass test case) and for failed test case, the ID/PK feature that would have been activated

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows] Mac
 - Great Expectations Version: [e.g. 0.13.2] 0.15.48

**Additional context**

**Comment by talagluck** [comment]
Hi @data-han - thanks for raising this. We will review and be in touch.

**Comment by Shinnnyshinshin** [comment]
Hi @data-han a fix went out with the latest release. Could you try the latest GX and let us know if the problem is still there?

**Comment by data-han** [comment]
@Shinnnyshinshin  works now, thanks for the fix!
