### ISSUE TITLE
Accessing AWS Redshift External Tables using Spark Dataframe and applying Expectations 

### ISSUE THREAD

**Issue by SENOMOY** [fivetran/great_expectations#7127]
**Describe the bug**
While trying to fetch data from AWS Redshift external tables using Spark Dataframe and applying expectations on the data we are able to fetch the column information (metadata) but not able to print first few Rows or apply expectations

**To Reproduce**
Sample Code: 

spark_redshift_expectations_test.py : 

# Spark Imports
```
import pyspark
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[1]") \
.appName('spark_redshift_datasource') \
.getOrCreate()

df = spark.read.format("jdbc") \
.option("url", "jdbc:redshift://<hostname>:<port>/<database>") \
.option("driver", "com.amazon.redshift.jdbc42.Driver") \
.option("dbtable", "<schema>.<table_name>") \
.option("user", "<username>) \
.option("password", "<password>") \
.load()

df.registerTempTable("<table_name>")

df = spark.sql("select * from <table_name> limit 1000")
```

# Great Expectations Imports

```
import great_expectations as gx
from great_expectations.cli.datasource import sanitize_yaml_and_save_datasource,
 check_if_datasource_name_exists
from ruamel import yaml
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.data_context.types.base import (
DataContextConfig,
InMemoryStoreBackendDefaults,
)
from great_expectations.util import get_context

from great_expectations.core.batch import BatchRequest
from great_expectations.checkpoint import SimpleCheckpoint
from great_expectations.exceptions import DataContextError


context = gx.get_context()

datasource_config = {
"name": "spark_redshift_datasource",
"class_name": "Datasource",
"execution_engine": {"class_name": "SparkDFExecutionEngine"},
"data_connectors": {
"default_runtime_data_connector_name": {
"class_name": "RuntimeDataConnector",
"batch_identifiers": ["batch_id"],
}
},
}

context.test_yaml_config(yaml.dump(datasource_config))

context.add_datasource(**datasource_config)

suite = ExpectationSuite(
expectation_suite_name="spark_redshift_data_suite",
data_context=context
)

context.save_expectation_suite(expectation_suite=suite, 
overwrite_existing=False)

context.list_datasources()

data_batch_request = RuntimeBatchRequest(
datasource_name="mdms_spark_datasource",
data_connector_name="default_runtime_data_connector_name",
runtime_parameters ={"batch_data":df},
batch_identifiers = {"batch_id": "1"},
data_asset_name="top_1000"
)

expectation_suite_name = "spark_redshift_data_suite"
```

# Build validator
```
validator = context.get_validator(
batch_request= data_batch_request,
expectation_suite_name=expectation_suite_name
)
```

# Print table column names
```
column_names = [f'"{column_name}"' for column_name in validator.columns()]
print(f"Columns: {', '.join(column_names)}.")
```

![image](https://user-images.githubusercontent.com/16465618/218454866-1256a389-aa0f-4a80-b994-320305aac73c.png)

# Print table top 5 rows
```
validator.head(n_rows=5, fetch_all=False)
```

![image](https://user-images.githubusercontent.com/16465618/218454972-b45c9250-b4b6-4cd2-9ae2-fd484003a8c1.png)

# Expect global_id column to be unique
validator.expect_column_values_to_be_unique("<column_name>")

![image](https://user-images.githubusercontent.com/16465618/218455033-7540e579-8f7e-4a18-88a6-39fffc85037c.png)

Run Command: 
spark-submit \
--packages com.amazon.redshift:redshift-jdbc42:2.1.0.11 \
spark_redshift_expectations_test.py

**Expected behavior**
Usualy it should fetch its metadata and data both

**Environment (please complete the following information):**
 - Operating System: **AWS Linux 2**
 - Great Expectations **Version: 0.15.47**

**Comment by SENOMOY** [comment]
There is data in the table and spark is able to do row count and head(1): 

![image](https://user-images.githubusercontent.com/16465618/218458158-8d345f0d-cd31-4403-903a-4cc56a6abfaf.png)

**Comment by talagluck** [comment]
HI @SENOMOY - thanks for raising this. Can you please confirm the type of the df object you create in your first step? GX should work well on a Spark DataFrame, and I wonder whether this is some other type that GX doesn't know how to process.

**Comment by SENOMOY** [comment]
As you can see from the code I've created Spark Dataframe from redshift table

**Comment by talagluck** [comment]
Hi @SENOMOY  - can you please confirm the type of the df object you create in your first step, by calling `type(df)`?

**Comment by SENOMOY** [comment]
<class 'pyspark.sql.dataframe.DataFrame'>

**Comment by SENOMOY** [comment]
Same issue with Spark Dataframe created from MySQL table:

import great_expectations as gx
from ruamel import yaml
from great_expectations.core.batch import BatchRequest
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.core.expectation_suite import ExpectationSuite

import findspark
findspark.init()
import pyspark
from pyspark.sql import SparkSession

spark = SparkSession.builder \
.config("spark.jars","file:///C:/Users/subhajit.sen.IMPETUS/mysql-connector-java-8.0.28.jar") \
.master("local[1]") \
.appName("spark_mysql_datasource") \
.getOrCreate()

airports_df = spark.read.format("jdbc") \
.option("url", "jdbc:mysql://localhost:3306/test_db") \
.option("driver","com.mysql.jdbc.Driver") \
.option("dbtable", "airports") \
.option("user", "root") \
.option("password", "Welcome2mysql") \
.load()

airports_df.show(3,truncate=False)

+----------------------------+-----------+----------------+----+----+------------+-----------+--------+------------+---+---------------------+
|Name                        |City       |Country         |IATA|ICAO|Latitude    |Longitude  |Altitude|Timezone_Num|DST|Timezone             |
+----------------------------+-----------+----------------+----+----+------------+-----------+--------+------------+---+---------------------+
|Goroka Airport              |Goroka     |Papua New Guinea|GKA |AYGA|-6.081689835|145.3919983|5282    |10          |U  |Pacific/Port_Moresby
|Madang Airport              |Madang     |Papua New Guinea|MAG |AYMD|-5.207079887|145.7890015|20      |10          |U  |Pacific/Port_Moresby
|Mount Hagen Kagamuga Airport|Mount Hagen|Papua New Guinea|HGU |AYMH|-5.826789856|144.2960052|5388    |10          |U  |Pacific/Port_Moresby
+----------------------------+-----------+----------------+----+----+------------+-----------+--------+------------+---+---------------------+

context = gx.get_context()

spark_datasource_config = {
"name": "spark_mysql_datasource",
"class_name": "Datasource",
"execution_engine": {"class_name": "SparkDFExecutionEngine"},
"data_connectors": {
"default_runtime_data_connector_name": {
"class_name": "RuntimeDataConnector",
"batch_identifiers": ["batch_id"],
}
},
}

context.test_yaml_config(yaml.dump(spark_datasource_config))

context.add_datasource(**spark_datasource_config)

expectation_suite_name="spark_mysql_expectation_suite"

expectation_suite = ExpectationSuite (
    expectation_suite_name=expectation_suite_name,
    data_context=context
)

context.save_expectation_suite(expectation_suite=expectation_suite, overwrite_existing=True)

context.list_datasources()

airport_batch_request = RuntimeBatchRequest(
datasource_name="spark_mysql_datasource",
data_connector_name="default_runtime_data_connector_name",
runtime_parameters ={"batch_data":airports_df},
batch_identifiers = {"batch_id": "default_identifier"},
data_asset_name="airports"
)

airports_validator = context.get_validator(
batch_request=airport_batch_request,
expectation_suite_name=expectation_suite_name
)

column_names = [f'"{column_name}"' for column_name in airports_validator.columns()]
print(f"Columns: {', '.join(column_names)}.")

airports_validator.head(n_rows=5, fetch_all=False)


![image (2)](https://user-images.githubusercontent.com/16465618/221190763-2d2fe67e-814c-48b9-a474-6adb9cee8d10.png)

**Comment by talagluck** [comment]
Hi @SENOMOY - thanks so much for the update. We are taking a look and will follow up if we have additional questions.

**Comment by alexsherstinsky** [comment]
Hello, @SENOMOY I am continuing to learn more about this issue -- thank you for a great write up.  Is there a potential typographical error near the beginning?  I am seeing `mdms_spark_datasource` in the `BatchRequest`; however, the configuration contains a different `datasource_name` (`"spark_redshift_datasource"`).  Which of them is the correct one?  Please feel free to update the description, and I will check later (I am also continuing to familiarize myself with other aspects of your report and may have more questions later.).  Thank you very much.

**Comment by 1i1it** [comment]
Closing this since we haven't heard back! Please re-open if needed.
