### ISSUE TITLE
Inconsistent Capitalization of "Slack"

### ISSUE THREAD

**Issue by JoelGritter** [fivetran/great_expectations#7135]
**Describe the bug**
Maybe a bit nit-picky... but the capitalization of "Slack" at https://docs.greatexpectations.io/docs/#community-resources is rather inconsistent.

![Screen Shot 2023-02-13 at 21 08 25](https://user-images.githubusercontent.com/13542746/218622303-f88325ad-2650-469e-96c1-e9a2ae05094d.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://docs.greatexpectations.io/docs/#community-resources
2. See text

**Expected behaviour**
I would propose that all of the above should be capital S, that is "Slack".

**Comment by talagluck** [comment]
Thanks for raising this @JoelGritter and thanks for opening up the PR! Someone from the team will review and be in touch shortly.
