### ISSUE TITLE
Removing or limiting storing of logs 

### ISSUE THREAD

**Issue by data-han** [fivetran/great_expectations#7160]
**Is your feature request related to a problem? Please describe.**
I noticed that logs are created in /logs with every checkpoint run and it creates many small files (in terms of bytes and kilobytes). If users do not require them, is it possible to remove or limit them?

<img width="629" alt="image" src="https://user-images.githubusercontent.com/51312880/219249810-c4a945a2-a9b2-43c5-bf6b-ab693434ef63.png">

**Describe the solution you'd like**
Finding out a method to not store any logs, or clean up / limit them by number of x days

**Describe alternatives you've considered**
A manual clean up in S3 is tedious as there are many pages (created by many small files)

**Additional context**

**Comment by talagluck** [comment]
Hi @data-han - thanks for raising this. As far as I know, GX doesn't have any logging functionality. [Is it possible that you have logging enabled in S3 as described here?](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html)

**Comment by data-han** [comment]
Hi @talagluck . Thanks for this info! I will take a look and see if I can disable logging from S3 side. From the documentation, looks possible . Will close this now
