### ISSUE TITLE
Feature Request: Validation Run from CLI

### ISSUE THREAD

**Issue by salam-abdul** [fivetran/great_expectations#718]
Hi, 

I would like to be able to run validation on configured remote datasources with existing expectations.

Thank you

**Comment by Aylr** [comment]
Hi! @salam-abdul what would you imagine the cli looks like? Could you post some ideas for us to think about?

**Comment by Aylr** [comment]
We have new features such as https://docs.greatexpectations.io/en/latest/how_to_guides/validation/how_to_run_a_checkpoint_in_terminal.html that close this issue!
