### ISSUE TITLE
Snowflake connection string with @ in password is failing

### ISSUE THREAD

**Issue by s-agarbhi** [fivetran/great_expectations#7180]
Per following the steps mentioned in https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/database/snowflake/ guide, there is an error thrown when password has a '@' value in it.

In the snowflake connection string if there is any '@' value, then it is being split and connection string is changed totally.

example: 
password = "XXXX@YYYY"
error: cannot connect to YYYY@snowflake-url..... Incorrect username or password was specified.

Since the great expectations' snowflake connection string uses @ for building its own db string connection, password with @ is not working for the same.

**Comment by rdodev** [comment]
Hey @sagarwal-bhi 👋 

Would you mind sharing more details? GX version, OS, etc?

**Comment by s-agarbhi** [comment]
GX version == 0.15.42
OS = databricks notebook and windows

**Comment by rdodev** [comment]
Hey @sagarwal-bhi,

Thanks for that, I confirmed that there's an issue when using a password that contains an `@`. We unfortunately don't have an immediate work-around aside from using a different password.

**Comment by donaldheppner** [comment]
Alternatively, if you escape the @ symbol in the password manually (ex: `Test@1234` would become `Test%401234`) it should work (see: https://community.snowflake.com/s/article/Password-with-special-character-may-cause-authentication-failure-at-SQLAlchemy)

**Comment by billdirks** [comment]
I'm closing this since we have two workarounds posted (don't use `@` or manually escape it in your password) and we don't plan on making a change to Great Expectations to handle this currently. Thanks for filing this issue and bringing it to our attention!
