### ISSUE TITLE
Breaking change released in v0.15.48

### ISSUE THREAD

**Issue by jayceslesar** [fivetran/great_expectations#7191]
This function did not raise an error in v0.15.48 but now it does raise an error.  Consider adding an `exist_ok` kwarg similar to os.makedirs and default to True. 

After change
https://github.com/great-expectations/great_expectations/blob/0.15.48/great_expectations/data_context/store/checkpoint_store.py#L196

Before change
https://github.com/great-expectations/great_expectations/blob/0.15.47/great_expectations/data_context/store/checkpoint_store.py#L171

**Comment by jayceslesar** [comment]
Happy to contribute to this if you think that is the correct approach

**Comment by austiezr** [comment]
Hey @jayceslesar! We’re actively trying to move away from granular flags like `exists_ok` , and trying to better isolate & make explicit certain functionalities for better consistency within the API. `add` will now intentionally always attempt to create a new object and will raise an error if there is a collision.

However, you can migrate from `add_checkpoint` to `add_or_update_checkpoint` to retain the previous behavior; this should be a 1:1 construct that maintains the functionality you've been experiencing.

**Comment by austiezr** [comment]
Closing this out for now; if you're not able to get the behavior you're looking for after making the change above, please feel free to re-open!
