### ISSUE TITLE
params_with_json_schema is undefined in _prescriptive_renderer method of expect_select_column_values_to_be_unique_within_record

### ISSUE THREAD

**Issue by DavidSlayback** [fivetran/great_expectations#7204]
**Describe the bug**
Exactly as in #5938, but for a different file. The `params_with_json_schema` object is not declared in _prescriptive_renderer method in [expect_select_column_values_to_be_unique_within_record](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py#L182). So if an expectation suite uses expect_select_column_values_to_be_unique_within_record with mostly param < 1.0, it causes NameError: name 'params_with_json_schema' is not defined

**Environment (please complete the following information):**
 - Great Expectations Version: 0.15.48

**Comment by cdkini** [comment]
Hey @DavidSlayback, thanks for catching this!

I've written a fix here: https://github.com/great-expectations/great_expectations/pull/7261

**Comment by DavidSlayback** [comment]
Thank you! I considered submitting a PR but don't work with GE enough myself to be confident I identified everything

**Comment by cdkini** [comment]
No worries, appreciate the help here!
