### ISSUE TITLE
GX does not identify timestamp/date column datatype from Databricks sql

### ISSUE THREAD

**Issue by adarsha-jll** [fivetran/great_expectations#7208]
**Describe the bug**
GX does not identify timestamp/date column datatype from Databricks sql. The data is passed into GX as a pandas dataframe.

**To Reproduce**
1. connect to databricks sql, fetch data and create a pandas dataframe.
2. setup GX to use in memory checkpoint using the pandas datasource.
3. expectation suite defined for date column as 
{
      "expectation_type": "expect_column_values_to_be_in_type_list",
      "kwargs": {
        "column": "last_invited_on",
        "type_list": ["Timestamp_NTZ", "datetime64[ns]", "Timestamp", "datetime64[ns, UTC]"]
      },
      "meta": {}
    }
4. the column in the dataframe is of type ‘datetime64[ns, UTC]’
5. after running the checkpoint validation result does not identify the date column type, expectation fails. result is as below.
![image](https://user-images.githubusercontent.com/107102139/220823168-0ce78ce0-0b39-439b-a4a6-c6d59b7cb256.png)

**Expected behavior**
GX identifies date column type from databricks sql and the expectation validation status is pass.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: [0.15.48]
 - Python: 3.9.16

**Additional context**

**Comment by alexsherstinsky** [comment]
Hello, @adarsha-jll -- thank you very much for reporting this issue along with the example for how to reproduce it.  The team will triage it internally and update you on the next steps and/or if there are follow up questions.  Thanks again.

**Comment by molliemarie** [comment]
Hello @adarsha-jll. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
