### ISSUE TITLE
GX doesn't support airflow 2.2.2 anymore due to a new release (PR#7108)

### ISSUE THREAD

**Issue by EladHaziza94** [fivetran/great_expectations#7209]
**Describe the bug**
Even though I created a clean environment with just airflow2.2.2 and one dependency "airflow-provider-great-expectations==0.2.4"
I still get the following error (when I changed to 2.4.3 it worked fine):

Broken DAG: [/opt/airflow/dags/GREAT_EXPECTATION_TEST.py] Traceback (most recent call last):
  File "pydantic/fields.py", line 804, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 723, in find_validators
RuntimeError: no validator found for <class 're.Pattern'>, see `arbitrary_types_allowed` in Config

**To Reproduce**
1. Open the airflow docker-compse community file (https://airflow.apache.org/docs/apache-airflow/**2.2.2**/docker-compose.yaml)
2. Add the "GX" dependency on the _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-airflow-provider-great-expectations}
3. Lunch airflow with docker-compse (docker-compose up airflow-init) -> (docker-compose up)

**Expected behavior**
Even though we hadn't created any dags, the RuntimeError mentioned above should raise.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: latest

**Comment by Kilo59** [comment]
You are getting this error because we require `pydantic>=1.10.4`

**Comment by Kilo59** [comment]
You might be able to get around this by installing `typing_extensions>=4.2.0` before installing `airflow` or `great_expectations`

**Comment by talagluck** [comment]
Resolved by #7482
