### ISSUE TITLE
Support Evaluation Parameters referencing within-suite expectation validation results

### ISSUE THREAD

**Issue by jcampbell** [fivetran/great_expectations#721]
Currently, data context makes it possible to expose validation results that are produced in a previous expectation suite, but validation does not support evaluation parameters referencing outputs in the same suite.

It would be useful to be able to have expectations that match each other, such as
`expect_column_values_to_be_between('a', 1, {'$PARAMETER": "urn:great_expectations:...:expect_column_max_to_be_between:result"})`

**Comment by hell-io** [comment]
Upvoting this feature. Hasn't it been added yet?
