### ISSUE TITLE
Misleading GX website stating support for snowflake

### ISSUE THREAD

**Issue by s-agarbhi** [fivetran/great_expectations#7213]
Hi Team,

Following up on https://github.com/great-expectations/great_expectations/discussions/7205 ..

When I visit https://greatexpectations.io/expectations/ -> and filter by Snowflake, I can see green circles around lots of expectations for Snowflake. Yet, when I visit individually, in each of the supported expectations there is mention of contribution needed for Snowflake.

Can you please clarify the same? If it is rather to be released as part of next release then I can understand that website is updated first and expectations will be updated too in next few days. But if that's not the case, then I request that website should be updated to mark snowflake support similar to that of MSSQL.

Appreciate for the great work being done by the GX contributors here and my aim with this post is to get some transparency around Snowflake support.

**Comment by rdodev** [comment]
Hey @sagarwal-bhi :wave:
GX and the vast majority of our core expectations have complete support for Snowflake off the shelf. There is a bug in the expectation gallery website (we're fixing it) that's rendering the individual expectations as needing contribution when it fact they do not. Apologies for the confusion and thanks for raising this issue.
If you are running into actual issues with any of the expectations let us know. Otherwise, do you mind if I close this issue?

**Comment by s-agarbhi** [comment]
Thanks for the update. Please keep this issue open for a couple of days, until I can actually test to see which expectations are throwing error.

**Comment by s-agarbhi** [comment]
Hey @rdodev,

I have tried implementing the following expectations against snowflake data:
1.  expect_compound_columns_to_be_unique with column_list argument containing two column names
2.  expect_column_values_to_be_unique with column argument containing one column name

In both the cases, I'm receiving the following error:
COLUMN_NAME  in BatchData does not exist.

Batch request has simple query "select * from table_name" (https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/database/snowflake/)

Note: expect_table_row_count_to_be_between expectation works fine with the same queried data whereas column based expectations are failing. 

Environment details:
Databricks notebook, GX version 0.15.42

**Comment by austiezr** [comment]
Hey @sagarwal-bhi! As indicated by @rdodev, the majority of our core Expectations support Snowflake. However, not all Expectations will support all backends, and these expectations are among those. If you're interested in seeing these expectations enabled for Snowflake, we are happy to provide guidance and review on a PR!

**Comment by s-agarbhi** [comment]
Thanks @austiezr , appreciate your inputs.

Do you have an actual list of what's supported and what's not for Snowflake backend? as a beginning point, it will help us a lot in moving forward.

**Comment by lukedyer-peak** [comment]
@sagarwal-bhi : looks to be your having the same issue as https://github.com/great-expectations/great_expectations/issues/7145

**Comment by kujaska** [comment]
> Environment details: Databricks notebook, GX version 0.15.42

1) Did you try running the same expectations against snowflake data NOT from Databricks, but from CLI?

2) I've tried expect_column_values_to_be_unique in Databricks with great_expectations-0.16.1-py3-none-any.whl - and it looks like working fine (i.e. finding non-unique values correctly) at least for a numeric field in snowflake 
with these SQLs pushed down to snowflake:

SELECT count(*) AS "table.row_count" 
FROM ge_temp_52674bf9

SELECT "UnexpectedCountSubquery".unexpected_count 
FROM (SELECT sum(condition) AS unexpected_count 
FROM (SELECT CASE WHEN (cd_demo_sk IS NOT NULL AND cd_demo_sk IN (SELECT cd_demo_sk 
FROM ge_temp_52674bf9 GROUP BY cd_demo_sk 
HAVING count(cd_demo_sk) > 1)) THEN CAST(1 AS NUMERIC) ELSE CAST(0 AS NUMERIC) END AS condition 
FROM ge_temp_52674bf9) AS anon_1) AS "UnexpectedCountSubquery"

-- why is it so complex???
SELECT cd_demo_sk AS unexpected_values 
FROM ge_temp_52674bf9 
WHERE cd_demo_sk IS NOT NULL AND cd_demo_sk IN (SELECT cd_demo_sk 
FROM ge_temp_52674bf9 GROUP BY cd_demo_sk 
HAVING count(cd_demo_sk) > 1)
 LIMIT 20
 
-- why do we need this? 
 SELECT sum(CASE WHEN (cd_demo_sk IS NULL) THEN 1 ELSE 0 END) AS "column_values.nonnull.unexpected_count" 
FROM ge_temp_52674bf9

**Comment by kujaska** [comment]
> Do you have an actual list of what's supported and what's not for Snowflake backend? as a beginning point, it will help us a lot in moving forward.

+100500 and with GX release version please....

**Comment by s-agarbhi** [comment]
Sweet, upgraded to GX version 0.16.1 and the expectation expect_column_values_to_be_unique  works as expected. Thanks, I will evaluate the other expectations for Snowflake backend needed by our project.

Previously I was using 0.15.42 and there were errors using the same.

**Comment by talagluck** [comment]
Hi all - it sounds like the original issue has been resolved here. We have also updated our gallery so you should be able to find a list of Expectations that are supported for Snowflake here: https://greatexpectations.io/expectations/

I'm going to close this issue for now, but please feel free to open a new issue if you are still hitting a bug. Thanks!
