### ISSUE TITLE
SqlAlchemyDataset on Redshift gives no database found error

### ISSUE THREAD

**Issue by SENOMOY** [fivetran/great_expectations#7225]
**Describe the bug**

**To Reproduce**
pip install sqlalchemy-redshift
pip install redshift_connector

from great_expectations.dataset import SqlAlchemyDataset
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

first_table_full_name = 'mdms_test.mdm_customer'
first_table_column = 'global_id'
second_table_full_name = 'mdms_test.mdm_account'
second_table_column = 'acct_cust_global_id'
condition = '1=1'

query = f"""select count(1) from (
SELECT a.{first_table_column} FROM {first_table_full_name} a
LEFT JOIN {second_table_full_name} b
ON a.{first_table_column}=b.{second_table_column}
WHERE b.{second_table_column} IS NULL
and {condition}
GROUP BY 1
) AS T"""

print('Full SQL Query:\n')

print(query)

# build the sqlalchemy URL
url = URL.create(
drivername='redshift+redshift_connector', # indicate redshift_connector driver and dialect will be used
host='******.redshift.amazonaws.com', # Amazon Redshift host
port=5439, # Amazon Redshift port
database='mdms_test', # Amazon Redshift database
username='mdmsuser', # Amazon Redshift username
password='*******' # Amazon Redshift password
)

engine = create_engine(url, pool_pre_ping=True)

# Create a SqlAlchemyDataset
sql_dataset = SqlAlchemyDataset(
    engine=engine,
    table_name="my_temp_table",
    custom_sql= query)

![image](https://user-images.githubusercontent.com/16465618/221193340-5bc6063a-6727-48ea-8640-3be5e35da97e.png)

**Environment (please complete the following information):**

 - Operating System: AWS Linux
 - Great Expectations Version: 0.15.47

**Comment by SENOMOY** [comment]
![image](https://user-images.githubusercontent.com/16465618/221193453-6a7aa873-caa3-4f3d-bac5-864ffdf4b0f3.png)

**Comment by rdodev** [comment]
Hey @SENOMOY 👋 

SQLDatasets are deprecated and will be EOL'd in the near future. We suggest following our [Redshift documentation](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/database/redshift/) for up to date code samples.

**Comment by austiezr** [comment]
Closing this out for now; if you're still unable to connect to Redshift utilizing our latest API and docs, please feel free to re-open!
