### ISSUE TITLE
Passing A List As An Evaluation Paremeter

### ISSUE THREAD

**Issue by bkraft4257** [fivetran/great_expectations#7234]
**Describe the bug**
I wanted to create a dynamic expectation using an Evaluation Parameter and the expect_column_values_to_be_in_set.  I asked the question on Great Expectations Slack support channel 

"How do I create an Evaluation Parameter that I may use as a list for the expect_column_values_to_be_in_set"?

Austin Robinson asked me to file an issue on GitHub.

```
Austin Robinson (GX)
:gx:  [4 hours ago](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1677269473491059?thread_ts=1677248032.328259&cid=CUTCNHN82)
Hey 
[@Bob Kraft](https://greatexpectationstalk.slack.com/team/UNUSQPAHK)
! Thanks for reaching out. Would you be willing to raise a GitHub Issue detailing this behavior? From there we can review this functionality.
```

**To Reproduce**
I created a simple test case with the following expectation snippet.  

```
{
      "expectation_type": "expect_column_values_to_be_in_set",
      "kwargs": {
        "column": "as_of_dt",
        "value_set": [ {"$PARAMETER": "as_of_dt_string"} ]
      }
    }
```

This failed with the MetricResolutionError exception 

```
great_expectations.exceptions.exceptions.MetricResolutionError: <class 'dict'> is not defined formatter.\n",
              "exception_message": "<class 'dict'> is not defined formatter.",
              "raised_exception": true
            }
```

because I was passing the  {"$PARAMETER": "as_of_dt_string"}  inside a list.  For testing purposes, I rewrote the expectation without the list

```
{
      "expectation_type": "expect_column_values_to_be_in_set",
      "kwargs": {
        "column": "as_of_dt",
        "value_set":  {"$PARAMETER": "as_of_dt_string"} 
      }
    }
```

I then encountered this error "exception_message": "IN expression list, SELECT construct, or bound parameter object expected, got '2023-01-01'.",

**Expected behavior**
I want to be able to pass in a list as an evaluation parameter.   This functionality may already exist but I couldn't find it in your documentation. 

**Environment (please complete the following information):**
Linux 
great-expectations==0.15.42
python version 3.7.15

**Comment by austiezr** [comment]
Hey @bkraft4257 ! Thanks for raising this. We'll investigate this behavior and be in touch.

**Comment by molliemarie** [comment]
Hello @bkraft4257. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
