### ISSUE TITLE
AssertError During Great Expectations Installation 

### ISSUE THREAD

**Issue by richardohara** [fivetran/great_expectations#7239]
While setting up a development environment I ran the following installation command:
`pip install -e .`
And received the following error message:
`The extras requirements dir (req) contains files that do not adhere to the following format: requirements-dev-*.txt`

1. Fork and clone the development branch
2. Follow the instructions to set up a development environment
3. Execute the command pip install -e .
4. See the error message

The expected behavior is the install will successfully complete

Environment
 - Operating System: Windows]
 - Great Expectations Version: 

Additional Info
The bug is due to code in Setup.py. The code that sets up the directory path does not work with Windows machines. I have a fix and will submit a PR.

**Comment by cdkini** [comment]
Hey @richardohara, thanks for reaching out about this! A fix here would be greatly appreciated - we look forward to your PR.

**Comment by richardohara** [comment]
I submitted a pull request today. I somehow ended up with extra commits in the PR, three of which are mine and one that is not. I am not sure how to remove the extra commits. My commit that should be use is 6bd7a68. Sorry for making a mess of this.

**Comment by cdkini** [comment]
Apologies for the delayed response here @richardohara - looks like the changes are in! I'll go ahead and close this issue, thanks for your help!
