### ISSUE TITLE
Trino Error - Whole database scanned instead of just the table

### ISSUE THREAD

**Issue by JustinGuese** [fivetran/great_expectations#7256]
**Describe the bug**

Hey, I am trying to set up a trino datasource, but it scans the whole database even though i just specified a single table - what did I do wrong?

Even though I am specifying catalog "hive" schema "hive_example" in the trino connection string, it still scans e.g. hive_example2, hive_example3, etc. which takes a long time. I would expect from datasource_config to only scan the schema + catalog specified (hive.hive_example), or even better just that table (hive.hive_example.people), not the whole database...
(I can see all the select requests to other databases in trino)

**To Reproduce**

datasource_config -> like in your link, but trino url ....[trino.com:443/hive/hive_example](trino://user:pw@trino.com:443/hive/hive_example)
```
batch_request = BatchRequest(
  datasource_name = "trino_hive_hive_example_people",
  data_connector_name = "default_inferred_data_connector_name",
  data_asset_name = "hive_example.people"
)
```

**Expected behavior**

with connection string "trino://user:pw@trino.com:443/hive/hive_example" only hive.hive_example is scanned

**Real behaviour:**

with the above connection string all databases are scanned
hive.hive_example (expected one)
hive.hive_example2
psql.psql_example1

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.15.49

**Additional context**

some more background: if i configure the database like in the link you posted above, for every little command, CLI or python, the whole trino database gets scanned, it's kind of ridiculous! e.g. even `great_expectations suite list´ scans the whole trino database first (~10 minutes) before outputting anything :smile:

```python
table = "hive.hive_example.people"

catalog, schema, tablename = table.split(".")

SUITE_NAME = "suite_" + table.replace(".", "_")

context = gx.get_context()   # even this part triggers a whole Trino database scan
dburi = f"trino://{environ['TRINO_USER']}:{environ['TRINO_PASSWORD']}@{environ['TRINO_HOST']}:{environ['TRINO_PORT']}/{catalog}/{schema}"
da_name = "trino_" + table.replace(".", "_")

# first try to load existing datasource
try:
    datasource = context.get_datasource(da_name)
    print("Datasource %s already exists." % da_name)
    context.add_datasource(datasource)
except ValueError:
    print("creating datasource for ", da_name, " ...")
    datasource_config = {
        "name" : da_name,
        "class_name": "Datasource",
        "execution_engine": {
            "class_name": "SqlAlchemyExecutionEngine",
            "connection_string": dburi,
        },
        "data_connectors": {
            "default_runtime_data_connector_name": {
                "class_name": "RuntimeDataConnector",
                "batch_identifiers": ["default_identifier_name"],
            },
            "default_inferred_data_connector_name": {
                "class_name": "InferredAssetSqlDataConnector",
                "include_schema_name": True,
            },
        },
    }
    # test it
    context.test_yaml_config(yaml.dump(datasource_config))
    context.add_datasource(**datasource_config)

batch_request = BatchRequest(
    datasource_name= da_name,
    data_connector_name= "default_runtime_data_connector_name",
    data_asset_name= schema + "." + tablename,
    # limit= 1000
)
context.add_or_update_expectation_suite(SUITE_NAME)
validator = context.get_validator(
    batch_request= batch_request, expectation_suite_name=SUITE_NAME
)


# example expectation
validator.expect_column_to_exist("id")

##review & save expectations
print(validator.get_expectation_suite(discard_failed_expectations=False))
validator.save_expectation_suite(discard_failed_expectations=False)

checkpoint = createCheckpoint(SUITE_NAME, batch_request, context)

# finally run checkpoint
checkpoint_result = checkpoint.run()
```

**Comment by austiezr** [comment]
Hey @JustinGuese ! Thanks for raising this. We'll look into this behavior and be in touch.

**Comment by talagluck** [comment]
Hey @JustinGuese - I see a couple of potential issues here. First, it looks like you are using an InferredAssetSqlDataConnector which will indeed scan your whole DB. I think you will instead want to use a ConfiguredAssetSQLDataConnector, or a RuntimeDataConnector.

Second, if you do use a RuntimeDataConnector, you will need to use a RuntimeBatchRequest rather than a regular BatchRequest.

Finally, you might be interested to try out configuration use our new fluent style of configuring a Datasource. You can find the docs for that here: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data/

Could you please try that out and let us know if it is still an issue?

**Comment by austiezr** [comment]
Hey @JustinGuese; bumping this again to verify if you've been able to review @talagluck's recommendations above. As noted, an InferredAssetSqlDataConnector will, intentionally, scan your whole DB.

**Comment by austiezr** [comment]
Hey @JustinGuese! Closing this Issue out for now. If you're able to follow the above suggestions and still having an issue here, please feel free to re-open!
