### ISSUE TITLE
build data_docs in S3 bucket with AES256 encrpytion

### ISSUE THREAD

**Issue by elPichon98** [fivetran/great_expectations#7289]
**Is your feature request related to a problem? Please describe.**

Currently, I see no options that allows users to build data-docs in a S3 bucket that only allow uploads
AES256 encryption. This will help users who have to work with data that must always be encrypted 

Currently if a user attempts to upload to an S3 bucket with a policy that only allows encrypted uploads will lead to 
Access Denied Errors despite having correct credentials

**Describe the solution you'd like**

A nice way to make this possible is via a command line option such as 

`great_expectations docs build --site-name <your-site-name> --encryption-params AES256`

**Describe alternatives you've considered**
An alternative could be to ask if s3 requires any encrpytion

**Additional context**

**Comment by talagluck** [comment]
Hi @elPichon98 - thanks for raising this. Have you tried specifying this either under `boto3_options` or `s3_put_options` wherever you configure your S3 DataDocs store?

**Comment by elPichon98** [comment]
i did adjust the s3_put_options in the great_expectation yml file but still led to an access denied error can provide yml file as example

**Comment by talagluck** [comment]
Thanks, @elPichon98 - yes, please provide that. That will enable us to reproduce this more quickly and easily.

**Comment by molliemarie** [comment]
Hello @elPichon98. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
