### ISSUE TITLE
TupleAzureBlobStoreBackend Prefix List Keys

### ISSUE THREAD

**Issue by ashboot-rgb** [fivetran/great_expectations#7335]
Using TupleAzureBlobStoreBackend as the expectation, checkpoint and validation store. Was able to save expectations and checkpoint files to these stores, however, when invoking a checkpoint run resulted in a `Exception: DataContextError: expectation_suite EXPECTATION_SUITE_NAME not found`. It appears the list_keys() method has the filepath delimiter hardcoded as "/" potential fix is to use os.sep. Developing on Windows causes error, deploying to Linux works fine. 

> [tuple_store_backend.py](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/data_context/store/tuple_store_backend.py#L1065l)
` if az_blob_key.startswith(f"{self.prefix}{os.sep}"): `

 - Developing Azure Function in Windows
 - Deploying Azure Function in Linux
 - Great Expectations Version: 0.15.50

**Comment by richardohara** [comment]
Opened pull request #7339.

**Comment by austiezr** [comment]
Closed by #7339
