### ISSUE TITLE
"Edit this page" gives 404 on GitHub

### ISSUE THREAD

**Issue by rmoff** [fivetran/great_expectations#7344]
The link from https://docs.greatexpectations.io/docs/ to `Edit this page` is [to the `develop` branch](https://github.com/great-expectations/great_expectations/tree/develop/docs/intro.md) which doesn't include the page to be edited. 

Related perhaps? https://github.com/great-expectations/great_expectations/blob/4f2a3ab6d48e09dde46cbac6bf9712ee13f0f533/docs/docusaurus/docusaurus.config.js#L253

**Comment by alexsherstinsky** [comment]
@rmoff Thank you very much for reporting this; I will let our team know.  Kind Regards.

**Comment by alexsherstinsky** [comment]
@rmoff We have an update: This broken link will be removed by the next coming release.  Please check the latest GX version on this coming Friday, March 17, 2023.  Thanks again for alerting us to this issue.

**Comment by alexsherstinsky** [comment]
@rmoff Could you please verify that you are not getting the 404 error any more?  Thank you very much.

**Comment by rmoff** [comment]
No, I still get a 404 error. 

https://user-images.githubusercontent.com/3671582/226854414-c13bd5c2-d917-4128-95c4-80e3c5af3df6.mp4

**Comment by alexsherstinsky** [comment]
Hi @rmoff Thank you for providing the video of the issue.  I am sorry that it is still happening.  We have a release tomorrow, and I will work with the team so as to make an effort to get it resolved by then.  We will keep you posted.  Thank you very much for your patience.

**Comment by alexsherstinsky** [comment]
Hi @rmoff -- the fix to the 404 has been made an hour ago.  Please confirm on your end and let us know.  Having said that, if the real issue is that you want to edit a document (as a separate concern from getting a 404 error), then the edit should be made to the document and submitted as a pull request (and we can assist with the steps and procedures for this).  Thanks.

**Comment by rmoff** [comment]
I don't see the link at all any more ¯\_(ツ)_/¯

**Comment by alexsherstinsky** [comment]
@rmoff If you would like  to make an edit to a document, then please find the document in the "/docs/docusaurus/docs/" folder in the `develop` branch on GitHub and submit the change as a pull request.  The path to the document should follow the path of the URL (closely).  Please let us know how it goes.  Thank you.
