### ISSUE TITLE
Add rapid prototyping for custom expectations

### ISSUE THREAD

**Issue by jpcampb2** [fivetran/great_expectations#78]
The docs claim we have these functions enabled. We should. We don't.

```
    >> dataset.test_expectation_function(my_func)
    >> dataset.test_column_map_expectation_function(my_map_func, column='my_column')
    >> dataset.test_column_aggregate_expectation_function(my_agg_func, column='my_column')
```

**Comment by abegong** [comment]
@jpcampb2 I took a shot at implementing this, but got hung up on the decorator syntax.

https://github.com/superconductive/great_expectations/commit/f3eb83febc15a47905c7a3d01b8ffdb747610d78

Any ideas how to get this working? You've plumbed the arcane depths of decorators far more than I.

**Comment by abegong** [comment]
I think I got it. Check out: https://github.com/great-expectations/great_expectations/pull/130
