### ISSUE TITLE
Feature request: Hierarchical list of data asset names

### ISSUE THREAD

**Issue by elsander** [fivetran/great_expectations#791]
On Redshift (and presumably other dbs with schemas), `great_expectations.jupyter_ux.list_available_data_asset_names(context)` lists data assets in a seemingly arbitrary order. For Redshift, this means it lists all tables in all schemas in the Redshift cluster I'm connected to (many many tables). It would be easier for me to find what I'm looking for if the data asset listing reflected the hierarchy in the database. I can see a couple ways to do this:

- Allow filtering by schema, so that fewer data assets are listed
- Alphabetize by default
- Add functionality to list available schemas, and list available assets within a schema.

Allowing more flexibility as to what is listed would be the most helpful, but alphabetizing might be the easiest/most flexible 80% solution.

**Comment by Aylr** [comment]
Alphabetization was implemented a few releases ago. Feel free to reopen if that doesn't suit your needs!
