### ISSUE TITLE
get_column_mean for SparkDataset fails with type error.

### ISSUE THREAD

**Issue by ddanda** [fivetran/great_expectations#800]
The dict(self.spark_df.dtypes) always returns string type for all columns in the SparkDataset. 

TypeError                                 Traceback (most recent call last)
<ipython-input-38-2955aa9e2ca0> in <module>
      7 minvalue = ge_dataset.get_column_min('L_LINENUMBER')
      8 maxvalue = ge_dataset.get_column_max('L_LINENUMBER')
----> 9 mean = ge_dataset.get_column_mean('L_LINENUMBER')
     10 median = ge_dataset.get_column_median('L_LINENUMBER')
     11 

d:\experiment\pyspark_test\lib\site-packages\great_expectations\dataset\sparkdf_dataset.py in get_column_mean(self, column)
    219         types = dict(self.spark_df.dtypes)
    220         if types[column] not in ('int', 'float', 'double', 'bigint'):
--> 221             raise TypeError('Expected numeric column type for function mean()')
    222         result = self.spark_df.select(column).groupBy().mean().collect()[0]
    223         return result[0] if len(result) > 0 else None

TypeError: Expected numeric column type for function mean()

**Comment by jcampbell** [comment]
Thanks for reporting this @ddanda -- I'll investigate more asap and let you know what's going on

**Comment by jcampbell** [comment]
@ddanda : can you provide some more detail about your dataset and how you're loading it? I'm not able to reproduce this issue yet.

**Comment by ddanda** [comment]
i was loading from csv into Spark dataframe.

spark_df = spark.read.option('header', True).csv('E:\LineItem1GB\LineItem.csv')
ge_dataset = SparkDFDataset(spark_df)
mean = ge_dataset.get_column_mean('L_LINENUMBER')

i think the datatypes are not infered automatically when reading from csv.

**Comment by jcampbell** [comment]
Got it; you're right: by default schemas are not inferred.

If you check out the docs here https://docs.greatexpectations.io/en/latest/getting_started/create_expectations.html#reader-options it'll cover some options for specifying additional parameters including ones that are useful for getting the schema using spark.

Specifically, you can either specify the schema yourself (`schema` parameter) or, especially for numeric data, specify set the `inferSchema` parameter to true.

The full list of spark reader parameters is linked from our docs and is also available here: https://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.DataFrameReader

**Comment by mbassennesm** [comment]
I have experienced the exact same issue even when loading a dataframe from parquet. Example below:

```
data = spark.createDataFrame([
    {
        "city": "New York",
        "coast": "east",
        "population": 1e6,
    },
    {
        "city": "San Francisco",
        "coast": "west",
        "population": 1e5,
    },
])

data = data.withColumn("population", F.col("population").cast("decimal"))

data.printSchema()
```

GX successfully validates the column as DecimalType (hence the type is properly recognized), but returns the error below for the column mean expectation:

`
expect_column_mean_to_be_between raised an exception:
Expected numeric column type for function mean()
[Show exception traceback...](https://github.com/great-expectations/great_expectations/issues/800#section-5-content-block-2-cell-1-2-content-2-collapse-body-44d37fae-745e-43e2-8bb7-83d690bb7a51)

Traceback (most recent call last):
File "/job/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 555, in _process_direct_and_bundled_metric_computation_configurations
] = metric_computation_configuration.metric_fn( # type: ignore[misc] # F not callable
File "/job/.local/lib/python3.8/site-packages/great_expectations/expectations/metrics/metric_provider.py", line 90, in inner_func
return metric_fn(*args, **kwargs)
File "/job/.local/lib/python3.8/site-packages/great_expectations/expectations/metrics/column_aggregate_metric_provider.py", line 230, in inner_func
metric_aggregate = metric_fn(
File "/job/.local/lib/python3.8/site-packages/great_expectations/expectations/metrics/column_aggregate_metrics/column_mean.py", line 35, in _spark
raise TypeError("Expected numeric column type for function mean()")
TypeError: Expected numeric column type for function mean()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/job/.local/lib/python3.8/site-packages/great_expectations/validator/validation_graph.py", line 276, in _resolve
self._execution_engine.resolve_metrics(
File "/job/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 290, in resolve_metrics
return self._process_direct_and_bundled_metric_computation_configurations(
File "/job/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 559, in _process_direct_and_bundled_metric_computation_configurations
raise gx_exceptions.MetricResolutionError(
great_expectations.exceptions.exceptions.MetricResolutionError: Expected numeric column type for function mean()
`
