### ISSUE TITLE
Readthedocs search has broken links

### ISSUE THREAD

**Issue by louispotok** [fivetran/great_expectations#817]
Steps to reproduce:
1. go to https://great-expectations.readthedocs.io/en/latest/index.html
2. In the search bar, enter `distributional`

I see that the first result is https://docs.greatexpectations.io/en/latest/distributional_expectations.html
and the second result is https://docs.greatexpectations.io/en/latest/guides/distributional_expectations.html

Both of which are broken links.

The third result is https://docs.greatexpectations.io/en/latest/reference/distributional_expectations.html, which is correct.

**Comment by jcampbell** [comment]
This one really bothers me too--unfortunately, it's a known issue with readthedocs. They've got an open PR...another voice to help fix it would be most appreciated. https://github.com/readthedocs/readthedocs.org/pull/6186

**Comment by jcampbell** [comment]
They've just merged a PR to fix the issue! https://github.com/readthedocs/readthedocs.org/pull/6298

Once they've updated RTD (looks like about every two weeks?), we can wipe and rebuild.

**Comment by Aylr** [comment]
Rumor has it a release is soon.

**Comment by jcampbell** [comment]
readthedocs has pushed the latest release, and our docs have been rebuilt.
