### ISSUE TITLE
Add instructions on postgresql setup for testing

### ISSUE THREAD

**Issue by louispotok** [fivetran/great_expectations#818]
When I install all requiresments and try to run the test suite, I get this error (from line 65 of `tests/conftest.py`):

```postgresql tests are requested, but unable to connect to the postgresql database at "'postgresql://postgres@localhost/test_ci'")``` 

Are there special steps required to set up the postgres db for testing? If so, should probably add those (maybe into the contributing instructions).

**Comment by jcampbell** [comment]
Good point, will do. So you're not blocked: you can add `--no-postgresql`
to the pytest command to suppress those tests. It will fall back to only
sqlite.
