### ISSUE TITLE
Result from get_column_unique_count on Pandas and Spark are different

### ISSUE THREAD

**Issue by ddanda** [fivetran/great_expectations#820]
spark = SparkSession.builder.enableHiveSupport().getOrCreate()
spark.conf.set("spark.sql.execution.arrow.enabled", "true")
spark_df = spark.read.option('header', True).csv('E:\Python\VirtualEnvironments\GE\data\Titanic.csv')
spark_dataset = SparkDFDataset(spark_df)

df = pd.read_csv('E:/Python/VirtualEnvironments/GE/data/Titanic.csv')
pandas_dataset = PandasDataset(df)
unique_pandas_count = pandas_dataset.get_column_unique_count('Age')
unique_spark_count = spark_dataset.get_column_unique_count('Age')
print(unique_pandas_count, unique_spark_count)

![image](https://user-images.githubusercontent.com/12235608/67256473-04f6a980-f43c-11e9-8c0c-8e7e32e3b98f.png)

DropNa is not set for value_counts  in PandasDataset. is this expected ?

**Comment by jcampbell** [comment]
This is definitely a subtle issue. I suspect that what you're observing is that the default read csv behavior for pandas and spark are slightly different so I expect what's being read as na by Pandas (the unquoted string 'NA') is being treated by Spark as a legitimate column value (i.e. not NULL); both methods strip the actual value NULL.

Unfortunately, Spark doesn't allow one to disable that behavior, so we can't turn on dropna in Pandas and get consistent results (which I agree would be nice!)
