### ISSUE TITLE
adding sqlalchemy as a dependency?

### ISSUE THREAD

**Issue by sshah-wework** [fivetran/great_expectations#844]
After initial pip install, running `great_expectations add-datasource` failed for me because `sqlalchemy` was not installed. Checked `requirements.txt` and it's not there -- I'd like to add it but wanted to make sure there wasn't already a reason for this.

Thanks,
Shawn

**Comment by jcampbell** [comment]
Great question; we removed it as an explicit dependency so that users could install only tooling required for their specific backend (i.e. a spark user doesn't need sqlalchemy and vice versa). Sqlalchemy is listed in the optional dependencies, though, and hopefully you got an informative error message! If you've got other ideas for how to handle optional dependencies like that, let's review them here.

**Comment by sshah-wework** [comment]
Gotcha, I appreciate the lean approach! The error message was clear enough so I proceeded by installing `sqlalchemy` manually. However, after installing it and then trying to add a mysql-based datasource, the error message was less clear:

```
Cannot connect to the database.
  - Please check your environment and the configuration you provided.
  - Database Error: No module named 'MySQLdb'
  - Please `pip install psycopg2` and try again
```

It looks like it tried to load `MySQLdb` which then took some googling since `MySQLdb`'s pip module is unhelpfully named `mysqlclient`. 

Wondering if maybe there could be a phase of `init` which figures out which additional dependencies will be needed (most of which can be inferred from the answers to the existing set of questions) and install them as well?

**Comment by jcampbell** [comment]
I love that approach! We're reworking the init flow right now to handle additional db cases more gracefully (specifically mysql, actually, since right now it is very postgres-centric). Including more on specific dependencies required at that point is a great idea; I'll ensure we add it in.

**Comment by abegong** [comment]
This would also be a great tutorial post: "How to use Great Expectations with MySQL in a new python environment"

**Comment by sshah-wework** [comment]
Ah actually I had pasted the wrong error earlier (now fixed). It actually had instructed me to install `psycopg2` (even though it's a MySQL client dep missing), so definitely is a bit PG-centric at the moment.

@abegong that would be awesome :)

By the way, this is all the setup for a GE-based Airflow operator (or Airflow plugin with some convenient hooks for GE) that we're building for use internally. It does not seem that such an operator exists today and we're trying to build it generically so we can open source it! 

Would love your thoughts on this -- seems like it has come up in the past (#267)

**Comment by jcampbell** [comment]
On the airflow front: there's a very bare-bones example here: https://github.com/superconductive/airflow_meetup_demo

There's also a older operator implementation located here: https://github.com/great-expectations/great_expectations/tree/develop/examples/integrations/airflow

And last thought: if you join our slack channel (greatexpectations.io/slack), there are several airflow users in there, one of whom I know is actively working on building an operator that they may be willing to open source.
