### ISSUE TITLE
Broken "glossary" link in docs

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#846]
This link is not working: https://docs.greatexpectations.io/en/latest/glossary.html 

Occurs here:
https://docs.greatexpectations.io/en/0.8.3/getting_started/create_expectations.html#how-do-i-know-which-types-of-expectations-i-can-add

Also shows up in search:
<img width="1440" alt="Screen Shot 2019-11-01 at 11 16 50 AM" src="https://user-images.githubusercontent.com/1239085/68046739-d11c4f00-fc99-11e9-8ca0-ab2150a7be4e.png">

Thanks to Shrikant for flagging this in the public slack channel!

**Comment by eugmandel** [comment]
The URL of the glossary has changed to https://docs.greatexpectations.io/en/latest/reference/expectation_glossary.html.

The old (broken) link appears in the create expectations tutorial - this will be fixed in 0.8.4 (to be released on 2019-11-04.
