### ISSUE TITLE
Notebooks missing after CLI init

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#850]
## ENV
- Windows
- anaconda python 3.7
- ge 0.8.4

## STR
- ge init
- add sql datasource
- skip profiling because it's super slow
- open jupyeter
- note three empty folders (pandas, sql, spark)

## Hunches
Probably a path issue or windows packaging issue as I could not locate the `init_notebooks` folder in the `site_packages` anywhere.

A basic unit test on windows might have caught this if it's a path issue, but could not catch it if it's a packaging issue.

**Comment by david-dalisay** [comment]
👋 @Aylr and @jcampbell. I just ran into the empty notebooks directory issue this morning on Mac.

**Comment by Aylr** [comment]
This is fixed in the hot fix release 0.8.4.post0!
