### ISSUE TITLE
Formatting issues in cli_init page 

### ISSUE THREAD

**Issue by ian-whitestone** [fivetran/great_expectations#853]
https://docs.greatexpectations.io/en/latest/getting_started/cli_init.html

![image](https://user-images.githubusercontent.com/11096727/68444798-f4696180-01a5-11ea-8c40-5d5110ebc43f.png)

Looks like "datasource" and "generator_asset" weren't rendered properly?

**Comment by Aylr** [comment]
Good catch @ian-whitestone !

**Comment by Bussmeyer** [comment]
It seems to be no longer relevant. I search for the paragraph and I can't find it anywhere.

I think we can close this issue.
