### ISSUE TITLE
Slack webhook shouldn't be stored in great_expectations.yml by default

### ISSUE THREAD

**Issue by ian-whitestone** [fivetran/great_expectations#856]
Following the `great_expectations init`, i added a slack webhook, which got automatically dumped in the `great_expectations.yml`. 

By default, this webhook should be treated like a private token, and should live in the `uncommitted/config_variables.yml`  in my opinion.

**Comment by jcampbell** [comment]
@ian-whitestone can you replicate that issue? The default flow for init doesn't store in great_expectations.yml, and we expect users to use the config-variables file to store the webhook. Under what conditions is it being stored in great_expectations.yml?

**Comment by ian-whitestone** [comment]
huh. no i can't, that's weird. will re-open if i find a way to reproduce.

**Comment by jcampbell** [comment]
👍
