### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by StellaMutahi** [fivetran/great_expectations#859]
when trying to install great_expectations from the requirement.txt  file I get the error 

```: Python.h: No such file or directory
       #include "Python.h"
                ^~~~~~~~~~
      compilation terminated.
      error: command 'gcc' failed with exit status 1
```

**Comment by jcampbell** [comment]
Thanks for flagging this; do you know which specific underlying package is causing this error on your system? I think we would need more context to help point in the right direction.

**Comment by indyfree** [comment]
Typically installing `python3-dev` or `python3-devel` depending on your linux flavor solves this issue.

**Comment by jcampbell** [comment]
@indyfree : thank you!
@StellaMutahi : I'm going to close this issue pending any additional context.
