### ISSUE TITLE
Make it simple to unit test subclasses of DataSet

### ISSUE THREAD

**Issue by abegong** [fivetran/great_expectations#86]
Per today's call, we expect to define the API for each expectation method (with docstring and all args+kwargs) in the base DataSet class.

When a developer subclasses from DataSet (e.g. PandasDataSet, SparkDataSet, MumpsDataSet) (haha, right.) there's always the risk that they'll define the inherited method incorrectly. For example, they might forget to include a parameter. Or turn a positional arg into a keyword arg. This is especially likely because we're doing so much fancy footwork with decorators that manipulate function args.

To beat this risk, our best method is going to standardized unit testing. It need to be easy for developers to apply the same battery of unit tests used on PandasDataSet today to any future subclass of DataSet.

**Comment by abegong** [comment]
Made some good progress on this in the last week.

See `https://github.com/great-expectations/great_expectations/blob/develop/tests/test_sets/expect_column_values_to_match_json_schema_test_set.json` for an example.

**Comment by jpcampb2** [comment]
The new structure for tests is implemented! (See discussion in #167 and #224). Some tests are not yet migrated to the new format, but all new tests should be.
