### ISSUE TITLE
Allow user to specify endpoint_url for S3 store

### ISSUE THREAD

**Issue by cwerner** [fivetran/great_expectations#887]
Boto3 by default does not process any endpoint_url environment variable (i.e. S3_ENDPOINT) and thus cannot be used to access non-AWS S3 solutions (i.e. [MinIO](https://min.io)) without specifying the endpoint_url in the call of boto3.client() and boto3.resource() explicitly.

One solution is to monkey patch the methods like so at the start of the python script:

```
import functools
import boto3
boto3.client = functools.partial(boto3.client, endpoint_url=S3_ENDPOINT)
boto3.resource = functools.partial(boto3.resource, endpoint_url=S3_ENDPOINT)
```

**Comment by jcampbell** [comment]
This is addressed in #901
