### ISSUE TITLE
Timezone offset does not match system offset

### ISSUE THREAD

**Issue by bruno-curta** [fivetran/great_expectations#924]
I'm facing an issue due to the cancellation of daylight saving in Brazil
when I try to run create_expectations.ipynb in jupyter notebook I get the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-4ff81ee3e151> in <module>
      2 import os
      3 import great_expectations as ge
----> 4 import great_expectations.jupyter_ux
      5 import pandas as pd
​
~/anaconda3/envs/load/lib/python3.6/site-packages/great_expectations/jupyter_ux/__init__.py in <module>
    308 # When importing the jupyter_ux module, we set up a preferred logging configuration
    309 logger = logging.getLogger("great_expectations")
--> 310 setup_notebook_logging(logger)
​
~/anaconda3/envs/load/lib/python3.6/site-packages/great_expectations/jupyter_ux/__init__.py in setup_notebook_logging(logger)
     83     """
     84 
---> 85     def posix2local(timestamp, tz=tzlocal.get_localzone()):
     86         """Seconds since the epoch -> local time as an aware datetime object."""
     87         return datetime.fromtimestamp(timestamp, tz)
​
~/anaconda3/envs/load/lib/python3.6/site-packages/tzlocal/unix.py in get_localzone()
    163     global _cache_tz
    164     if _cache_tz is None:
--> 165         _cache_tz = _get_localzone()
    166 
    167     return _cache_tz
​
~/anaconda3/envs/load/lib/python3.6/site-packages/tzlocal/unix.py in _get_localzone(_root)
     88                         # We are using a file in etc to name the timezone.
     89                         # Verify that the timezone specified there is actually used:
---> 90                         utils.assert_tz_offset(tz)
     91                     return tz
     92 
​
~/anaconda3/envs/load/lib/python3.6/site-packages/tzlocal/utils.py in assert_tz_offset(tz)
     36                    tz_offset, system_offset
     37                )
---> 38         raise ValueError(msg)
​
ValueError: Timezone offset does not match system offset: -10800 != -7200. Please, check your config files.

This issue was also reported on GE Slack.
Could you please take a look on this? Please let me know if additional information is required.

Thanks
Bruno

**Comment by jcampbell** [comment]
It looks like this is coming from a dependency (tzlocal). As a workaround, you could skip the import of the jupyter_ux package, since that is where the logging setup, and so failed attempt to get local timezone, is happening. That package provides access to methods like `list_available_data_asset_names`, but (1) they are primarily useful for formatting json results, and (2) you can manually import them as you encounter them in the notebook.

We'll need to have either a change in your TZ config, a fix in the upstream package, or a different workaround in GE to make that work easier.

**Comment by jcampbell** [comment]
Looks like this is likely an issue with your linux configuration: https://github.com/regebro/tzlocal/issues/79

**Comment by bruno-curta** [comment]
Hi @jcampbell thanks for the answers! I realized my computer was not following network time, I have forced my time to be 1h delayed because the internet is setting Brazilian time as daylight saving time, while this is not happening this year as per government decision. So I have set it back to the standard network time and my clock is now 1h ahead, but it continues giving the same error even after restarting the computer. My pytz version is 2019.3, the latest.

get_localzone from tzlocal also returns the same problem, so surely is not an error on GE. I will check how to fix that in my configuration. I think we can close it here

below the error I got from 
>>> from tzlocal import get_localzone
>>> get_localzone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/curtarelli/anaconda3/envs/load/lib/python3.6/site-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/home/curtarelli/anaconda3/envs/load/lib/python3.6/site-packages/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/home/curtarelli/anaconda3/envs/load/lib/python3.6/site-packages/tzlocal/utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: -10800 != -7200. Please, check your config files.

**Comment by jcampbell** [comment]
Does the workaround work to be able to continue using Great Expectations in the meantime?

I'd suggest you comment on the issue linked above (https://github.com/regebro/tzlocal/issues/79) since it seems like you're not the only one experiencing that issue.

**Comment by bruno-curta** [comment]
The solution was found/discussed here https://github.com/regebro/tzlocal/issues/79
