### ISSUE TITLE
Return row ids in partial_unexpected_list

### ISSUE THREAD

**Issue by anderl80** [fivetran/great_expectations#929]
Returning the ids of failing rows could speed up the investigation process after a failing validation.

**Comment by jcampbell** [comment]
Agreed--this is often really useful. Which backend are you using and/or how are you thinking of "row ids"? Currently, there is an "unexpected_index_list" that is returned by PandasDataset for exactly this reason, but it requires an index be available on the Dataset.

**Comment by anderl80** [comment]
Have not tested `unexpected_index_list` using Pandas yet, but like to have the same concept for Spark DataFrames if an index is given (I guess it's a bit trickier here as Spark does intrinsically have no indices..). It's not super-important, but makes life a bit easier for investigations.

**Comment by jcampbell** [comment]
Agreed -- we'd effectively need to have the ability to designate the relevant column as an id, and/or just pick a column name whose values should be returned as ids.

**Comment by anderl80** [comment]
Sorry for my late response, it is not relevant now, you might close the issue.

**Comment by jaytanwar85** [comment]
Hello @jcampbell @anderl80 ,
I am looking for the same way to get all records from  partial_unexpected_list or failed records via spark dataframe.
Can you please suggest some reference or way to achieve this..?

**Comment by madalinastanciu** [comment]
Hello,
I am having a similar issue in a project but when using SQLAlchemy.
 When I try to see the `partial_unexpected_index_list` I get a null value. 
The examples shown here https://docs.greatexpectations.io/docs/reference/expectations/result_format/ work only if the input is a Pandas Dataframe. Is there an implementation for SQLAlchemy or other integrations?

**Comment by becavas** [comment]
partial_unexpected_index_list working on spark?

**Comment by williamdphillips** [comment]
This is still relevant for spark-based dataframes. The unexpected index list works correctly for pandas, but when using spark dataframes the unexpected index list contains all nulls (ge.dataset.SparkDFDataset(df)). Attempted to utilize pyspark pandas but haven't yet been able to get it to work.

Although spark dataframes don't actually have indexes like pandas, there should be some way to utilize this feature - possibly by specifying a column which has indexes.

**Comment by bendiknordeng** [comment]
We have the same problem as @williamdphillips

**Comment by paulofelipe84** [comment]
Having the same need here. That feature would be nice.
