### ISSUE TITLE
great_expectation profile to pick config assets

### ISSUE THREAD

**Issue by shirouto** [fivetran/great_expectations#934]
This is a feature proposal.

I find it a bit against one's expectations (yeah, lame pun) that running ```great_expectations profile``` for a ```SqlAlchemyDatastore``` will simply ignore the specified assets in the ```great_expectations.yaml```, and instead simply attempt to run profile over all the accessible assets upon database connection. It can become troublesome for large databases. Maybe at least some command line flag to switch on/off the behavior if the present one is so desirable.

By the way, the only way I know to restrict the ```schema_name``` in ```snowflake_sqlalchemy``` is by assembling the connection string via the provided ```URL```. Of course, there is the option you left open for passing a ```connection_string``` instead of itemized credentials. :-) Otherwise, one is stuck with fully qualifying database objects.

**Comment by eugmandel** [comment]
We are working on a profiler that will profile one data asset (table). Would love to show a preview when ready.
