### ISSUE TITLE
Unicode issues with init on Windows

### ISSUE THREAD

**Issue by jemmott** [fivetran/great_expectations#953]
Running `great_expectations init` on Windows 10 command prompt I see `[36m` and similar.

![great](https://user-images.githubusercontent.com/43320559/71606160-71201880-2b23-11ea-8804-e5882b00d397.PNG)

I tried running it in Jupyter and got `UnicodeEncodeError: 'charmap' codec can't encode characters in position 138-140: character maps to <undefined>`

**Comment by Aylr** [comment]
@jemmott I believe this was fixed in #1114 I'm going to close this - feel free to reopen it if you can't reproduce it!

**Comment by jemmott** [comment]
Confirmed fixed.  Great work!
