### ISSUE TITLE
Issue when displaying assets across Datasources (jupyter_ux.list_available_data_asset_names)

### ISSUE THREAD

**Issue by PSUlion16** [fivetran/great_expectations#965]
When invoking **_great_expectations.jupyter_ux.list_available_data_asset_names(context, 'data_source_name')_** a user will see the correct output of the data source along with any available assets.

When a user does the following the output will be a combination of all data sources:
   1) invokes **_great_expectations.jupyter_ux.list_available_data_asset_names(context)_**
   2) has multiple data sources defined

The following will show and example where a user has defined multiple data sources:
![multiple_datasources](https://user-images.githubusercontent.com/24613077/72022452-1890ff80-3236-11ea-9b5e-003911eaed49.JPG)

After examining the underlying code for jupyter_ux, I believe the issue presents itself at **line 141** within the **list_available_data_asset_names** method.

This issue causes a bit of confusion when determining existing data sources and assets. I have replicated by deleting and remaking data sources through the CLI. The example above takes place in a situations where I have three data sources defined (inbound_feeds, test_dropzones and test_plan).

**Comment by PSUlion16** [comment]
@jcampbell -- do you want me to work through this as well in terms of a PR? I should be able to look at the code refactor later this week.

**Comment by jcampbell** [comment]
@PSUlion16 I think that would be wonderful! I'm going to tag @eugmandel as well so he can coordinate, since he authored that section originally.  It might be useful to jump in the slack channel too so we could coordinate fixes while we're working actively on the 0.9.0 update!

**Comment by PSUlion16** [comment]
Awesome. Unfortunately SLACK and GIT is blocked on my work network, but will update you guys once I get on my personal Dev box at home - thanks!

**Comment by PSUlion16** [comment]
I am going to close this issue @jcampbell -- I can work around this by using UDFs I've created on my own Jupyter notebook -- I don't think I need to have this formatted version, either a Tuple format or these UDFs should work.

def show_expectation_suites():
    # View available expectation suites
    print('Available Expectation Suites:' + '\n')
    for expectation_suite_id in context.list_expectation_suites():
        if "checkpoint" not in expectation_suite_id.expectation_suite_name:
            print(expectation_suite_id.expectation_suite_name)

# User Defined Functions for this notebook - pull this into a separate PY file, for use in GE overall
def show_data_assets(data_asset_dict):
    try:
        for keys in data_asset_dict:
            print("Available assets for the datasource " + keys + ":")
            for assets in data_asset_dict[keys]['subdir_reader']['names']:
                if assets[1] == 'file':
                    print("\t" + assets[0])
    except:
        print("     ***No Data Assets have been defined for this datasource***")
