### ISSUE TITLE
Potential to Delete Expectation Suite with wrong parameter pass due to code bug(context.create_expectation_suite)

### ISSUE THREAD

**Issue by PSUlion16** [fivetran/great_expectations#970]
There is a potential for users to accidentally overwrite their expectation suites if the pass a STR value of 'True' or 'False' as a value for the **overwrite_existing** parameter in the **context.create_expectation_suite** method within **data_context.py**.

This parameter defaults to BOOL value of FALSE in the definition which normally will raise an error to the user if they try to create a new expectation suite with an existing suite's name. However, in a use case where the user passes this variable as either **overwrite_existing = 'True'** or **overwrite_existing = 'False'** they will have their expectation suite overwritten as
**_self._stores[self.expectations_store_name].has_key(key) and not overwrite_existing_** will evaluate to TRUE and FALSE, allowing the suite to be overwritten.

I would recommend changing **Line 1149** of the **data_context.py** to put a BOOL check around the overwrite_existing parameter to account for a situation in which a user passes the STR value of 'False' by accident or ignorance to method. This BOOL check will prevent the expectation suite from being overwritten. Would look as such:

**_if _self._stores[self.expectations_store_name].has_key(key) and not bool(overwrite_existing):_**

I whipped up a simple example of this to show how the behavior occurs with a simple method:
![image](https://user-images.githubusercontent.com/24613077/72177118-a3443c80-33a5-11ea-9857-b49ca0379bc0.png)

Chris

**Comment by jcampbell** [comment]
Great catch; would you be interested in making that into a PR? We love having additional community members contribute.

**Comment by PSUlion16** [comment]
As long as you guys don't mind - I'm all for adding to the code base. What branch should I be making the PR into?

**Comment by jcampbell** [comment]
We'd love it: for this, a PR into `develop` would be best.

**Comment by Aylr** [comment]
@jcampbell Is this issue resolved?
