### ISSUE TITLE
Issue when specifying DataFrame object as "dataset" parameter in batch_kwargs

### ISSUE THREAD

**Issue by PSUlion16** [fivetran/great_expectations#986]
When a user attempts to grab a batch of data, using a dynamically created dataframe object we will get the following error:

**Command:**
_my_explicit_batch_kwargs = {"dataset": "base_table_pd"}
data_asset_name_test = 'TRANSACTION_TEST'
expectation_suite_name_test = 'transactions'

batch = context.get_batch(data_asset_name=data_asset_name_test, expectation_suite_name=expectation_suite_name_test, batch_kwargs=my_explicit_batch_kwargs)_

**Error:**
![image](https://user-images.githubusercontent.com/24613077/72474566-ae84d700-37ae-11ea-827c-9471d0d2c926.png)

In this context, **base_table_pd** is a dynamically created Pandas DataFrame.

When I looked at the code, I believe this issue arises due to the fact that **base_table_pd** is passed by reference vs. value, which causes **Line 191 in pandas_datasource.py** to fail in the isinstance check. I have tested this behavior by replicating in Jupyter Notebooks with the same code snipped and new values --

![image](https://user-images.githubusercontent.com/24613077/72474865-57cbcd00-37af-11ea-9844-fb9ac9cb8c81.png)

While I CAN get batches of data by directly applying expectations on dataframes (such as your tutorial on youtube), it would be helpful to have the ability to dynamically invoke batches - so this get_batch would need to work.

Am I overlooking something here? FYI - i got get_batch working correctly with flat files, and tried to pass the actual DF to the context.get_batch as well, with no success.

Chris

**Comment by jcampbell** [comment]
Hmmm; is it possible that the issue is your quoting the reference?

For example:
```
df = pd.DataFrame({"a": [1,2,3]})  # my dynamically created dataframe
_my_explicit_batch_kwargs = {"dataset": df}  # not "df"
...
```

Would the above work?

**Comment by PSUlion16** [comment]
@jcampbell per our conversations, the issue was a result of an extra line of code that I couldn't see myself (code blind) ... I will close this out
