### ISSUE TITLE
Add support for read_pickle reader_method

### ISSUE THREAD

**Issue by jcampbell** [fivetran/great_expectations#988]
Currently, it's not possible to read pickle files directly (see: https://stackoverflow.com/questions/59766843/use-a-pickled-pandas-dataframe-as-a-data-asset-in-great-expectation)

Adding reader_method support for read_pickle would be a great option here!

**Comment by NelsonTorres** [comment]
Can I take this issue?

**Comment by abegong** [comment]
Yes, go for it!
