### ISSUE TITLE
Add Support for Offline Documentation Rendering

### ISSUE THREAD

**Issue by JacquesDonnelly** [fivetran/great_expectations#994]
Currently, the auto-generated documentation to view profiling results, expectation suites and validation results requires accessing various CDNs for vega, fontawesome etc...

From a machine without access to the internet this leads to unsightly docs. In this case it would be useful to be able to build the docs so they are fully supported without access to the internet (@abegong suggested possibly by providing a one off script to download the dependencies?)

I'll be taking a look at this over the next week to try and find a nice solution

**Comment by noklam** [comment]
@JacquesDonnelly  Did you find any solution? I encounter the same issue. Thank you.

**Comment by arunvelsriram** [comment]
@JacquesDonnelly did you get a chance to explore any solutions for this?

**Comment by arunvelsriram** [comment]
On top of my head immediate solution to this is to manually download and check-in the static js/css files. But this is quite tedious.

We could also make use of npm and a bundler like webpack.

It would be great if GE core members throw some suggestion on implementing this.

**Comment by arnold-jr** [comment]
I counted 19 distinct http resources. I, too, am looking for an easy solution.
